### ISSUE TITLE
关于警告信息:radio控件不能同时定义ms-attr-value与ms-duplex-string

### ISSUE THREAD

**Issue by xiarugu** [RubyLouvre/avalon#1002]
常见的一个应用场景是, 业务定义了多种产品类型(包含ID和一个Name)
当前编辑的产品有一个字段存储产品类型编号(type_id)
```
<label ms-repeat="all_type">
    <input type="radio" name="type" 
        ms-attr-value="el.id" 
        ms-duplex-string="product.type"/>{{el.name}}
</label>
```

这样的结构用于显示/修改当前产品的类型.
所以radio中同时定义ms-attr-value和ms-duplex-string是很常见的应用啊.
请帮处女座去掉这个warning吧!

PS: 虽然可以用ms-duplex-checked="el.checked" 配合 product.type = vm.all_type.find(function(n) { return n.checked }).id;
来代替上面的代码避免出现警告, 可是毕竟不优雅啊, 而且是单纯为了控制台不出现警告.

**Comment by IndexXuan** [comment]
强烈支持。有些业务就是需要动态渲染几个子项的value（value不是定值），同时利用ms-duplex-string绑定到vm中的某个属性，很好的组合，很强大的功能，最好别warning了。。。

**Comment by RubyLouvre** [comment]
那我加强一下检测吧，只针对input[type="text"]发出警告
