### ISSUE TITLE
1.46 mobile版本导致电话号码点击无效

### ISSUE THREAD

**Issue by xiarugu** [RubyLouvre/avalon#1004]
```
<a href="tel::4008517517">4008-517-517</a>
```
不知道mobile版本做了什么事件拦截, ios中, 以上号码点击不能弹出拨打电话的对话框.
去掉avalon.mobile脚本的调用后可以正常弹出呼叫对话框.
替换成modern版本无此问题

急待解决!

**Comment by xiarugu** [comment]
发现不是手机号的问题
而是最新的master版本中的bug
在这个issue中
https://github.com/RubyLouvre/avalon/issues/998

我昨天下载了司徒fix了mobile bug的master版本出现的这个bug
是所有链接都点不了了. 不只是手机号的问题
https://github.com/RubyLouvre/avalon/commit/40ffe7f4a1b44a3a55ce99895ca92028643726dd

**Comment by gogoyqj** [comment]
@xiarugu 是的，touch那一坨的逻辑造成的

**Comment by xiarugu** [comment]
在1.5版本发布前可不可以出个小版本fix一下呢, 用到的项目已经上线了, 救命啊

**Comment by RubyLouvre** [comment]
可以临时把mousedown事件干掉

**Comment by xiarugu** [comment]
怎么干掉? mousedown也有用到啊, 弹出的div需要document.onmousedown隐藏呢
拜托两位大神了, 出个小版本吧

**Comment by RubyLouvre** [comment]
已经好了
