### ISSUE TITLE
有没有类似avalon语法的服务端模板引擎

### ISSUE THREAD

**Issue by xiarugu** [RubyLouvre/avalon#1005]
从jQuery向MVVM转型的过程中, 从最初的不习惯, 抗拒, 到现在切身感觉到的开发效率的提升, 越来越喜欢avalon的语法了.

因为自己同时也需要写后台程序, 然后就想有没有类似avalon的语法的服务端模板引擎呢, asp.net或者php的. 不知哪位有了解的?(PS, 我自己是做asp.net)

就是也像avalon一样用 xx-if 或者 xx:if ,  xx-repeat/xx:repeat, xx-each/xx:each, 等方式来控制html标签是否输出. 以及输出的内容.

有哪位朋友了解这方面资料的吗

**Comment by RubyLouvre** [comment]
https://github.com/exolution/xCube/blob/master/XParser.js
有人在nodejs层搞了一个avalon的后端渲染，但版本比较旧了
