### ISSUE TITLE
avalon 与 jeasyui 一起使用时的表单处理

### ISSUE THREAD

**Issue by zinda2000** [RubyLouvre/avalon#1010]
jeasyui: http://jeasyui.com/
对于表单元素，jeasyui 会渲染成

	<input ...><div>...

这样的HTML，avalon 的 ms-duplex 就起不到作用

有没有好的办法来处理这个问题

**Comment by Lihuanghe** [comment]
参考这个使用widget跟easyUI配合使用。否则easyUI和avalon都会操作 dom造成混乱。确保只有一方操作dom.
http://lihuanghe.github.io/avalon-easyui-demo/jqueryUIwrapper.html
