### ISSUE TITLE
过滤器遍历数组里的对象时候不起作用

### ISSUE THREAD

**Issue by benpaobenpao** [RubyLouvre/avalon#1015]
代码示例
![000000filter](https://cloud.githubusercontent.com/assets/1629413/9542240/9d5b1fb2-4da1-11e5-81cf-42d28ae7f6e7.jpg)
例子地址
http://www.godgiftgame.com/avalon/examples/test.html

**Comment by RubyLouvre** [comment]
ms-class不支持过滤器！！！ http://avalonjs.github.io/#zh/filters/index.html
