### ISSUE TITLE
版本升级向下兼容的问题

### ISSUE THREAD

**Issue by xiarugu** [RubyLouvre/avalon#1016]
我发现avalon的版本升级很飘逸啊, 1.4.6一下子就抛弃了老class方式
1.5还没用, 但是看到描述里说已经抛弃了子对象的$watch

对于开发正式的商业项目来说, 稳定性和版本升级的兼容性会比性能更重要.

我喜欢avalon, 希望avalon越来越壮大. 版本飘逸是个要命的问题, 升级吧大项目全面根据新版本改一下是个庞大的工作, 还容易错漏, 不升级呢, 隔三差五的又会遇到新的bug.

真心纠结啊, 希望司徒和各位avalon开发认真考虑一下这个问题.
注重稳定版本的开发, 所有有影响力的框架都有一个共同点, 就是会不停的发布小版本, 达到几个经典的无bug稳定版本
对于大版本升级以后发现的旧版本bug, 如果有bug, 还是需要对旧版本发布修复bug的小版本升级.

否则对于商用项目, 最后可能会不得不挥泪割别avalon啊.

**Comment by pinghe** [comment]
+1 
1.X 建议继续维护开发，趋于稳定

1.5 版本号建议直接改为2.0，这是一个重大升级，切换大版本号。

**Comment by RubyLouvre** [comment]
1.4.6没有抛弃ms-class，那是升级出BUG，于是立即出了1.4.6.1

**Comment by RubyLouvre** [comment]
1.5只是放弃了子对象的$watch及$unwatch

**Comment by xiarugu** [comment]
稍微大点的项目很多地方用到子对象的$watch, 如果想升级到1.5, 就得找出并修改所有地方. 这是件可怕的事情, 如果继续支持子对象的$watch并不会额外降低太多性能或导致js文件大很多的话, 还是希望能够继续支持, 至少在1.5版本继续支持.
我手上的项目都是大量HTML5的那种企业管理系统, 项目里每个页面都要用到ajax和avalon, 整体升级是个可怕的工作量.

PS. 超级期待1.5, 我每天都到github上看看1.5正式版发布了没有.

**Comment by RubyLouvre** [comment]
那就是1.4.7，1.4.8，1.4.9继续推进吧。每个版本一个月，可以撑到年底。

但avalon必须 对新特征进行投入。
