### ISSUE TITLE
功能建议:自定义事件

### ISSUE THREAD

**Issue by xiarugu** [RubyLouvre/avalon#1017]
avalon的mobile版本有不少bug, 之前的submit问题fix以后, 今天又遇到一个新的都不知道怎么描述的bug,
然后我今天下重新下载了master中的mobile, 发现今天奇怪的bug没有了, 但是之前的submit问题又出现了
好苦恼.

然后我想到, mobile版本可能得到的关心不是很多, 所以才会有那么多bug
如果mobile版本只是多了对对触屏事件的支持的话, 我完全可以使用modern代替它, 然后用其他的方式来自己触发tap事件.

然后, 我发现avalon似乎不支持自定义事件.

这是个苦恼的事情, 希望下一个小版本能够加入对自定义事件的支持.

对所有ms-on-xxx的属性, 如果xxx不在目前的事件之列, 可不可以就简单的去监听这个xxx事件.
用户不管用jQuery还是原生javascript去触发这个自定义的xxx事件, 就能触发相应的vm中的事件回调.

**Comment by RubyLouvre** [comment]
自定义事件，必须当然浏览器支持才支持，这个在IE9才有可能;这个建议 使用$watch 代替

**Comment by xiarugu** [comment]
我猜司徒团队的项目可能需要兼容IE低版本的比较多, 我这边所有的项目都是运行在Chrome/Firefox这些现代浏览器上的, IE完全不考虑.
这又回到那个问题了, 没有什么问题是解决不了的, 问题就是用了一个框架当然希望它像把利剑用的称心应手. 
write less, do more
这应该是所有"框架"共同的目标对吧.

**Comment by xiarugu** [comment]
司徒, 可以先对modern版本实现自定义事件吗?
这个自定义事件实在是太有用也太需要啦.

**Comment by xiarugu** [comment]
例如在对列表项中的某个DOM进行某些特定操作的时候, 希望以当前el为参数调用某个函数, 如果没有自定义事件, 就需要在DOM上绑定一个特定的作为el唯一识别的属性值, 然后再到数组中根据这个属性值查找到目标el, 然后再调用.
如果有自定义事件的话, 只要在dom上绑定这个自定义时间, 外部js触发这个事件就可以了.
由于外部js是完全针对DOM的操作, 属于View的扩展, 直接调用模型中的指定模型本身就是一种丑陋的侵入.

<li ms-on-update="update(el)">xxx</li>

外部触发一下li的update自定义事件就可以了. 完全不用管这个li是什么, el是什么, 也不用管和li绑定的是什么数据.
