### ISSUE TITLE
ms-duplex绑定发生的内存泄漏

### ISSUE THREAD

**Issue by lkiarest** [RubyLouvre/avalon#1018]
使用mmstate路由，测试页面2基本就是一个空的只显示一个字符串，测试页面1里面放几个input，使用ms-duplex绑定到vm的属性。
在页面1和2之间切换的时候发现内存会一直增长不会释放。
使用chrome调试发现avalon.$$subscribers这个数组里的元素会持续增加, 打印如下：
```
before unload page 1: avalon.$$subscribers:
[Object, Object, Object, Object, ms-duplex-3: 1, ms-duplex-4: 1, ms-duplex-5: 1, ms-duplex-6: 1]
before unload page 1: avalon.$$subscribers:
[Object, Object, Object, Object, Object, Object, Object, Object, ms-duplex-3: 1, ms-duplex-4: 1, ms-duplex-5: 1, ms-duplex-6: 1, ms-duplex-7: 1…]
before unload page 1: avalon.$$subscribers:
[Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, ms-duplex-3: 1, ms-duplex-4: 1, ms-duplex-5: 1, ms-duplex-6: 1, ms-duplex-7: 1…]
before unload page 1: avalon.$$subscribers:
[Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, ms-duplex-3: 1, ms-duplex-4: 1, ms-duplex-5: 1, ms-duplex-6: 1, ms-duplex-7: 1…]
before unload page 1: avalon.$$subscribers:
[Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, ms-duplex-3: 1, ms-duplex-4: 1, ms-duplex-5: 1, ms-duplex-6: 1, ms-duplex-7: 1…]
```

**Comment by gogoyqj** [comment]
哦，那这里估计有没回收的地方

**Comment by lkiarest** [comment]
用的avalon.shim这个lib，测试了avalon里GC的几个方法，切换的时候只有injectDisposeQueue会被调用，rejectDisposeQueue，disposeData这些方法都不会调用，不知道是不是跟mmstate的处理有关系~

**Comment by lkiarest** [comment]
调试的时候发现还有一部分内存泄漏是在vm的$events对象，不知道跟上面这个有没有关系

**Comment by gogoyqj** [comment]
我来撸一把

**Comment by gogoyqj** [comment]
@lkiarest 你说的情况，我并没有发现啊，avalon.$$subscribers

**Comment by lkiarest** [comment]
@gogoyqj ~~不会吧，我用的是1.4.6最新的avalon.js，oniui也是最新的，mmrouter是用oniui里面包含的。。

**Comment by lkiarest** [comment]
@gogoyqj 我用mmRouter-demo-list 这个demo在chrome和ie上跑也有这个问题，内存涨的飞快 ^0^

**Comment by lkiarest** [comment]
@gogoyqj 我写了一个demo，用mmstate切换两个最简单的页面，subscribers会一直增涨，不知道是不是我的写法问题~~
demo地址: http://lkiarest.github.io/oniui-extend/#!/duplexDemo
点击切换page1和page2可以在控制台里看到打印的 log

**Comment by lkiarest** [comment]
@RubyLouvre 我更新你最新提交代码后input绑定的没问题了，
不过在上面例子的page1页面加了一个select标签，绑定到如下一个数组：
```
roomList: [{name: "room1", value:"0"}, {name: "room2", value:"1"}, {name: "room3", value:"2"}]
```
切换的时候打印subscribers里的元素也会被清掉，不过看chrome的调试工具里这些元素一直没有释放。。好像还有引用

**Comment by RubyLouvre** [comment]
已经修复

**Comment by lkiarest** [comment]
@RubyLouvre hi，请问上面这个绑定对象的问题搞好咯不~~

**Comment by RubyLouvre** [comment]
已经修复了

**Comment by lkiarest** [comment]
@RubyLouvre 请问还是这个修复吗？
```
fix ms-duplex与 mmState共用时，由于ms-duplex的属性没有变动，没有触发GC的问题
https://github.com/RubyLouvre/avalon/commit/8d7821ad1688c4c356d6332d02182f917d434b6f
```
我试的这个版本的代码在绑定对象的时候内存还会泄漏~  绑定string等属性没有问题了。

**Comment by xiarugu** [comment]
司徒, 要有版本控制啊, 同一个版本发布了不能再修改, 补丁要发补丁的版本, 你修改已发布的版本, 我们使用就凌乱了.

**Comment by xyhp915** [comment]
这个fixed issue - `fix ms-duplex与 mmState共用时，由于ms-duplex的属性没有变动，没有触发GC的问题`
[https://github.com/RubyLouvre/avalon/commit/8d7821ad1688c4c356d6332d02182f917d434b6f](https://github.com/RubyLouvre/avalon/commit/8d7821ad1688c4c356d6332d02182f917d434b6f)

```javascript
@@ -62,6 +62,9 @@ function injectDependency(list, data) {

+        if (new Date() - beginTime > 444 ) {
+            rejectDisposeQueue()
+        }
```
我这边有导致其他的bug出现，垃圾回收的时机可能有问题，下午看看....

**Comment by lkiarest** [comment]
@gogoyqj 可以帮忙看下这个demo页面的写法有啥问题么，司徒兄说已经修复了，不过绑定对象和数组的时候内存还是会有泄漏：
 http://lkiarest.github.io/oniui-extend/#!/duplexDemo

**Comment by lkiarest** [comment]
经过测试发现一个避免这种内存泄漏的方法：
1. vm定义的时候对象设置为{}, 数组设置为[]，就是都不设置数据
2. onload的时候再设置对象(=)和数组(pushArray)的值
3. unload的时候调数组的clear方法，(发现对象不用清除也可以)
按照以上步骤的话基本上对象不会有泄漏了，不过在chrome调试的时候经常会有其他几k的array数据((code deopt data))不知道是哪儿定义的
