### ISSUE TITLE
对象发生变化，未渲染？

### ISSUE THREAD

**Issue by taoliujun** [RubyLouvre/avalon#1019]
版本： avalon.modern.js 1.45 built in 2015.7.17

对象先定义，后使用。但为何ms-text中的内容可以渲染出来？

    <!DOCTYPE html>
	<html lang="zh-cn">
	<head>
		<meta charset="utf-8">
		<title>test</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
		<meta name="renderer" content="webkit">
		<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
	</head>
	<body ms-controller="test1">
		<span ms-text="data.mobile.home"></span>
		<span>{{data.mobile.home}}</span>
	</body>
	</html>
	<script src="front/res/js/avalon.modern.js" charset="utf-8"></script>
	<script>
		(function(){
			var app = avalon.define({
				$id: 'test1',
				data: {
	
				}
			});
			window.setTimeout(function(){
				app.data = {mobile: {
					home: '151 6197 6666'
				}};
			} , 1000);
			avalon.scan();
		})();
	</script>

下面是1秒后渲染的结果：

    151 6197 6666 {{data.mobile.home}}

**Comment by RubyLouvre** [comment]
按理是变成 151 6197 6666 151 6197 6666

**Comment by RubyLouvre** [comment]
入门教程有写

**Comment by RubyLouvre** [comment]
升级版本
