### ISSUE TITLE
在组件上绑定ms-duplex

### ISSUE THREAD

**Issue by xiarugu** [RubyLouvre/avalon#1020]
如题, 可不可以直接在自定义组件上绑定duplex,
现在的组件依然是"外挂", 数据交互还是要跟某个input进行, 是否可以实现直接在组件标签上绑定ms-duplex
对于使用者来说, 直接把组件当成一个input使用, 用ms-duplex进行赋值取值
而内部的实现交给组件开发者, 实现更彻底、干净、简洁的组件调用方式。
html简洁
```
<ms:calendar ms-duplex="book_date"></ms:calendar>
```
js更简洁
```
vm.book_date = '2015-9-2';
```

**Comment by RubyLouvre** [comment]
这个以后我会统一说的

**Comment by xiarugu** [comment]
意思是, 已经在开发计划中了?

**Comment by RubyLouvre** [comment]
https://github.com/RubyLouvre/avalon2/tree/master/component/checkboxlist 看这个的使用
