### ISSUE TITLE
avalon1.4.6 IE7/IE8使用ms-include-src指令时报错

### ISSUE THREAD

**Issue by fancyzhaoyue** [RubyLouvre/avalon#1021]
IE7:[object Error] IE8:TypeError: “fn”未定义 
具体用例 avalon学习教程 13,模板引用
http://www.html-js.com/article/Avalon-tutorial-13-template

**Comment by RubyLouvre** [comment]
升级到avalon1.4.6.1试试

**Comment by RubyLouvre** [comment]
这里太多例子，都不知道哪一个
