### ISSUE TITLE
ms-duplex -checked  与 checkbox插件联合使用问题

### ISSUE THREAD

**Issue by dick1306** [RubyLouvre/avalon#1025]
我们项目目前在使用avalon框架，但是使用过程中发现ms-duplex 对使用了checkbox美化插件后就不生效了。
  但是我们现在很难取舍，原生checkbox太丑，美化后的ms-duplex又不生效，请教一下司徒正美有办法解决下吗？

**Comment by dick1306** [comment]
抱歉，因为无法上传代码，我不确定我说的问题你是否理解，若有疑问请给我留言哈，希望能得到你的答复

**Comment by RubyLouvre** [comment]
checkbox美化插件应该使用DIV代替 <input type='checkbox"/>，你看一下那个插件有没有回调，然后在回调里修改 <input type='checkbox"/>的值

**Comment by dick1306** [comment]
哦有个问题是 div都是dom树加载完毕后通过js方法添加的，对我们使用者而言还是<input id="AlarmType" ms-duplex-checked="a" type="checkbox" >这样的写法。
而如果我等div加载上后再加上ms-duplex-checked=“a" 是不生效的，只会解析为一个普通属性。
所以还是搞不懂，请帮忙再看看呢

**Comment by dick1306** [comment]
我测试时发现，$("input[type=checkbox]").attr("ms-duplex-checked","a"); });  avalon.scan($("#AlarmType").html(),"test"); 扫描后发现解析不了，但是ms-class 可以解析出来变为class属性。所以不知道怎么处理了

**Comment by RubyLouvre** [comment]
avalon.scan($("#AlarmType").html(),"test");

**Comment by RubyLouvre** [comment]
avalon.scan($("#AlarmType").parent()[0], avalon.vmodels.test);

**Comment by dick1306** [comment]
继续提问：我试了下，我统一对所有的checkbox 扫描不行，只能一个个来扫描吗？avalon.scan($("input[type=checkbox]"),avalon.vmodels.test); 
麻烦你了，转前端新手请谅解

**Comment by RubyLouvre** [comment]
是的
自己写个函数批处理

**Comment by dick1306** [comment]
ok!非常感谢

**Comment by dick1306** [comment]
<script>
        jQuery(document).ready(function() {         			
			$("#AlarmType").iCheck({
        checkboxClass: 'icheckbox_square-aero',
        increaseArea: '20%'
    });
	    $(".icheckbox_square-aero").attr("ms-duplex-checked","a");   //DIV层做处理
       	
       avalon.scan($(".icheckbox_square-aero")[0], avalon.vmodels.test);
	  
	 });
		</script>
麻烦帮忙看看，加了插件还是不行，局部扫描我知道了但是用div代替还是不行呢
