### ISSUE TITLE
1.4.6(9月6日版) 元素绑定ms-click=‘callback’导致callback调2次的问题

### ISSUE THREAD

**Issue by wttyzy** [RubyLouvre/avalon#1026]
使用环境avalon1.4.6(9月6日更新)； 浏览器：IE8，版本8.0.6001.187002
代码：
&lt;div ms-controller="test"&gt;&lt;div class="testStyle" ms-click="callback"&gt;测试&lt;/div&gt;&lt;/div&gt;
&lt;script&gt;avalon.define({$id : "test", callback : function () {avalon.log("callback");}});&lt;/script&gt;
问题：
avalon.scan()后，点击测试，调用了callback函数2次
分析了源码发现，函数scanAttr中，for(i)循环元素attributes解析属性，length=2即attr[0]=class,attr[1]=ms-click。当i=1,在3072行getUid(elem)时为elem设置了uuid属性，导致for循环的attributes.length+1，length=3即attr[0]=class,attr[1]=uuid,attr[2]=ms-click。再循环时取i=2，又被绑定一次
不知道分析的是否正确，请查看下问题

**Comment by RubyLouvre** [comment]
```html

<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="avalon.js"></script>
        <script>
            avalon.define({
                $id: "test",
                callback: function () {
                    avalon.log("callback");
                }
            });
        </script>

    </head>
    <body>
        <div ms-controller="test"><div class="testStyle" ms-click="callback">测试</div></div>
    </body>
</html>

```

**Comment by RubyLouvre** [comment]
我这样写在IE11的IE8兼容模式下没问题啊？
你试试

**Comment by RubyLouvre** [comment]
```javascript
function getUid(obj, makeID) { //IE9+,标准浏览器
    if (!obj["ZZuuid"]  && !makeID) {
        obj["ZZuuid"] = ++disposeCount
        //uuid2Node[obj.uuid] = obj
    }
    return obj["ZZuuid"] 
}
```
属性按字母序Z最后，就算for循环了，也应该无所谓吧

**Comment by RubyLouvre** [comment]
https://github.com/RubyLouvre/avalon/commit/4acdc3d6f85a898c4edbdfd77b71913c35f87c80
