### ISSUE TITLE
关于新版组件中的$$template回调

### ISSUE THREAD

**Issue by anrip** [RubyLouvre/avalon#1027]
乍一看去，我以为这是模板，但是发现还有一个$template，再看说明，原来是ready的后续回调。

回调中，有$childReady，那么我们为何不使用$overReady，$allReady 等更加表意化的名称呢？

**Comment by anrip** [comment]
又或者$finalReady，总要比$$template好吧

**Comment by anrip** [comment]
另外一个配置 configs 的使用，其实这个是单词configuration的缩写，这个作为计算机用语时，是不可数名词，没有复数形态，故而使用config作为缩写即可。

**Comment by xiarugu** [comment]
+1
configs很别扭
另childReady可参考"冒泡"的思想, 都叫ready, 通过判断参数中的target来判断是自身ready还是子元素ready

**Comment by RubyLouvre** [comment]
$$template是用来微调$template的，好吧，configs改为config。
childReady是非常用的
