### ISSUE TITLE
[BUG] dropdown组件在ms-repeat中使用不了。

### ISSUE THREAD

**Issue by 25614112** [RubyLouvre/avalon#1028]
把dropdown组件放在ms-repeat中样式有错乱，点击没反应。
avalon版本1.45。
THX。

**Comment by RubyLouvre** [comment]
不知道你怎么用啊

**Comment by RubyLouvre** [comment]
不知道你怎么用啊

**Comment by RubyLouvre** [comment]
不知道你怎么用啊

**Comment by RubyLouvre** [comment]
不知道你怎么用啊

**Comment by RubyLouvre** [comment]
不知道你怎么用啊

**Comment by RubyLouvre** [comment]
不知道你怎么用啊

**Comment by RubyLouvre** [comment]
不知道你怎么用啊

**Comment by roscoe054** [comment]
把avalon升级到1.4.6应该可以解决

**Comment by RubyLouvre** [comment]
不知道你怎么用啊

**Comment by 25614112** [comment]
就是简单的在ms-repeat里面嵌一个dropdown，循环生成。。avalon.js版本是1.45。
avalon.js升级到1.46.2这个bug就解决了。
谢谢司徒正美大大。

在 2015-09-08 16:10:48，"司徒正美" <notifications@github.com> 写道：


不知道你怎么用啊

**Comment by 25614112** [comment]
就是简单的在ms-repeat里面嵌一个dropdown，循环生成。。avalon.js版本是1.45。
avalon.js升级到1.46.2这个bug就解决了。
THX。
