### ISSUE TITLE
mmstate页面切换时widget造成的内存溢出问题

### ISSUE THREAD

**Issue by lkiarest** [RubyLouvre/avalon#1029]
使用widget (比如dialog) 的时候如果使用如下定义：
```
<div ms-widget="dialog, $, $dlgOpts">
```
每次切换页面生成的id是随机的，就造成了evaluatorPool这Cache里保存的所有key都是随机的，
这个缓存的更新的shift方法只是把key对应的值值为void 0，这个key还是存在的，切换几次页面之后evaluatorPool对象里就会保存大量字符串(而且生成的特别长)~~

经过测试在shift方法里把旧的key delete掉就可以解决了：
```
    p.shift = function() {
        var entry = this.head
        if (entry) {
            this.head = this.head.newer
            this.head.older =
                    entry.newer =
                    entry.older =
                    this._keymap[entry.key] = void 0
            delete this._keymap[entry.key]; // 增加这一行，释放掉key里的字符串
        }
    }
```

**Comment by RubyLouvre** [comment]
有delete在chrome下变有性能问题

**Comment by gogoyqj** [comment]
这个确实会使得map越来越大的说，应该不止dialog，ms-repeat之类的，也会在map上挂属性吧

**Comment by lkiarest** [comment]
嗯，在chrome下面测试发现运行一段时间会有一部分对象存在闭包里，不会被释放~~ 不知道是不是把函数绑定到data.evaluator 造成的。。

**Comment by RubyLouvre** [comment]
已经delete了https://github.com/RubyLouvre/avalon/commit/651b96c25f74597abbc61df8701765d311b47e4c

**Comment by lkiarest** [comment]
@RubyLouvre 我把这行加上测试的~~ 开始几次切换页面没问题，再继续切换会出现闭包没有释放的情况~~ 情况比不加这行好一点，不过还是会造成每次切换有20k左右增长

**Comment by lkiarest** [comment]
我单独写的测试页面才有这个问题。。
不过我们项目里的库更新后没这个闭包的泄漏， 可能是我写的问题~~ 不管了
