### ISSUE TITLE
1.4.6.2 属性里的过滤器无效

### ISSUE THREAD

**Issue by yutent** [RubyLouvre/avalon#1030]
![image](https://cloud.githubusercontent.com/assets/11972650/9759908/2ad25eca-5723-11e5-86c5-52b51b9ce9d3.png)
![image](https://cloud.githubusercontent.com/assets/11972650/9759909/322f239c-5723-11e5-981d-862a3bb1a8e6.png)
![image](https://cloud.githubusercontent.com/assets/11972650/9759912/3c714c0e-5723-11e5-9c8e-b94ba272bdec.png)
![image](https://cloud.githubusercontent.com/assets/11972650/9759921/47fc9358-5723-11e5-85e0-f63e4935af24.png)

ms-attr-title="avalon.filters.date(el.PUB_TIME, '', 0)"   这样子就没问题

![image](https://cloud.githubusercontent.com/assets/11972650/9759926/52fd1e9e-5723-11e5-91c1-be47f4858465.png)

我翻了下社区，发现这个人遇到 的问题有点像
 http://www.avalon.org.cn/art/55eec2cb368035034a000051

**Comment by RubyLouvre** [comment]
本来就不支持啊，都不看文档！

**Comment by yutent** [comment]
@北京-司徒正美 sorry了，是我的错，以前的版本不报错，我一直没注意到属性里的过滤器没生效 ，嘿嘿
