### ISSUE TITLE
关于avalon加载数据问题~ 急。

### ISSUE THREAD

**Issue by z893495246** [RubyLouvre/avalon#1033]
描述一下我的问题，需求。  
我现在在做一个动态加载数据。  首先，我需要把数据循环展示一个li标签里。我在main.js里面定义了一个数组“menLIst[]”
1：当我点击“A”选项卡的时候，按照流程它应该跳转到A.js里，  这个时候，我会在A.js里面给menLIst[]添加数据。比如，menList[{menTitle:"公告"}，{menTile:"设置"}],     这个时候要循环menList里的数据展示在Li标签里。ms-repeate-XX可以解决这个问题
2：当我点击“B”选项卡的时候，按照流程它应该跳转到B.js里，  这个时候，我会在B.js里面给menLIst[]添加数据。比如，menList[{menTitle:"任务"}，{menTile:"考勤"}],   到这里数据就不一样了，因为我的需求是这样。   到这里循环展示数据也没有问题，很正常
3：  这里是重点，当我再次回去点A选项卡的时候，它应该是跳转到A.js里的。。。没错，它是跳转进去了。但是，加载的数据居然是B.js里的。。。。Li标签呈现的数据是：mentitle=任务。  但是我想要的效果是当我点击某个选项卡，li标签加载的数据是一一对应的，这里发生了什么事情，我不知道是怎么回事，居然会是这样。

**Comment by 178220709** [comment]
楼主难道是把自己还不熟悉的新框架用在了项目里面? 
扯这么多也没提到重点,
切换标签后menLIst的变化是什么样的?

**Comment by ChieveiT** [comment]
呃，能贴代码尽量贴代码吧，别人没功夫帮你分析使用场景和需求的，你必须自己锁定那几行有问题的代码然后贴出来

**Comment by chenshunyu** [comment]
不知所云

**Comment by RubyLouvre** [comment]
不明白你说什么 不过我觉得你应该用深拷贝能解决这问题

vm. menLIst = avalon.mix(true, [], alist)

跳到另一个页面，也是这档

vm.menList = avalon.mix(true, [], blist)

**Comment by RubyLouvre** [comment]
不明白你说什么 不过我觉得你应该用深拷贝能解决这问题

vm. menLIst = avalon.mix(true, [], alist)

跳到另一个页面，也是这档

vm.menList = avalon.mix(true, [], blist)

**Comment by RubyLouvre** [comment]
不明白你说什么 不过我觉得你应该用深拷贝能解决这问题

vm. menLIst = avalon.mix(true, [], alist)

跳到另一个页面，也是这档

vm.menList = avalon.mix(true, [], blist)

**Comment by z893495246** [comment]
谢谢你们，可能是我没表达清楚，我把我的解决办法贴出来
avalon.router.get('/notifyList', function () {
        appVM.clearPopup();
        appVM.curNavIndex = 1;
        if (!avalon.vmodels.notifyListVM) {
            require(["news/notifyList"], function (callback) {
                callback();
            })
        }
        else {
        	  avalon.vmodels.appVM.menuList=[{menuId:"notify-1",menuTitle:"公告列表",child:[{a:"子菜单1"},{a:"子菜单2"}],menuIcon:"",url:"#!/notifyList"},{menuId:"notify-1",menuTitle:"设置",child:[{a:"子菜单1"},{a:"子菜单2"},{a:"子菜单3"}],menuIcon:"",url:"#!/notifyList"},{menuId:"notify-1",menuTitle:"公告添加",child:[{a:"公告1"},{a:"公告2"}],menuIcon:"",url:"#!/notifyList"}];
            avalon.vmodels.appVM.mainContent = "notifyListTpl";

**Comment by z893495246** [comment]
其实，就是两个选项卡，当我点击A的时候，会跳转到A，加载A.JS里面的东西，  我猜想的是这样，当你第一次点击的时候，首先它会创建view，并且加载一些数据，当你第二次点击的时候，它会去判断你是否创建了？如果创建了，就不会再一次创建，所以我做了个判断，当创建了之后，再一次加载一下数据。

**Comment by RubyLouvre** [comment]
看我上面的代码
