### ISSUE TITLE
ms-duplex -checked  与 checkbox插件联合使用问题二

### ISSUE THREAD

**Issue by dick1306** [RubyLouvre/avalon#1037]
<script>
        jQuery(document).ready(function() {    
       //icheck插件     			
			$("#AlarmType").iCheck({
        checkboxClass: 'icheckbox_square-aero',
        increaseArea: '20%'
    });
	    $(".icheckbox_square-aero").attr("ms-duplex-checked","a");  //按照你上一个问题的提示，提到DIV值
       avalon.scan($(".icheckbox_square-aero")[0], avalon.vmodels.test); //扫描
	 });
		</script>

帮忙看下，我这样设置后依然不能双向绑定，帮忙看看怎么处理呢！还是哪里还没有理解对

**Comment by RubyLouvre** [comment]
不要用你的那个美化插件了，乱改东西

**Comment by RubyLouvre** [comment]
或者 你那块就不要用  ms-duplex-checked

**Comment by dick1306** [comment]
我这边现在实现是没有用ms-duplex-checked的。
主要是我感觉这个问题比较普遍，所以想咨询下你。
1、我找了几个插件，然后设置ms-duplex-checked都不生效
2、但是原生的checkbox基本上项目中用的很少，很不美观
3、所以感觉这样的话ms-duplex-checked 这么好的一个属性都废了
4、没有办法解决吗

**Comment by dick1306** [comment]
我们公司经过选择目前力推用avalon框架，所以我们是想深入使用，也希望avalon越来越好，对我们使用者也是好事情

**Comment by RubyLouvre** [comment]
那你需要自己手动更新原来input啊

callback(){  input.click() // 程序触发input被钩选，这时它就会同步ms-duplex-checked }
