### ISSUE TITLE
功能建议,在视图模型中直接定义$watch

### ISSUE THREAD

**Issue by xiarugu** [RubyLouvre/avalon#1038]
常见的模型定义方式
```
var m = { $id: 'xx' };
m.xxx = xxx;
m.xxx = xxx;
...
```
一般会写一个函数专门定义这个视图模型, 而且希望在这里同时定义好$watch相关的逻辑. 最后返回m
在外部通过avalon.define(m)来定义刚才返回的m.

可是$watch方法只能在定义完成的vm上调用.
建议司徒是否可以在define的过程中读取m中的$watch相关信息, 例如:
```
var m = { $id: 'app', name: 'Charlie' };
m.$watch = {};
m.$watch['name'] = function()
{ 
    alert('property name changed'); 
};

...

//在define的过程中读取m中的$watch信息绑定到vm
var vm = avalon.define(m);
```

**Comment by xiarugu** [comment]
另外如果可以允许在$watch中同时定义多个属性就更好了.
实际业务中经常会有这样的情况, 属性a,b,c的变化都会导致事件X的发生,
这时候写三局一样的$watch就显得很不优雅了.
如果可以这样就好了:
```
vm.$watch('属性A 属性B 属性C', function(newValue, oldValue, name)
{ 
    xxx 
});
```
就像jQuery一样, 空格隔开多个属性, 加这么个语法糖会方便很多.

**Comment by RubyLouvre** [comment]
暂时不变更，可能1.6，1.7考虑加入;现在加入的新特征太多，还没什么人用上1.5x

**Comment by xiarugu** [comment]
我已经在两个生产环境开始使用1.5.1了 一个项目是200多人使用的企业内部业务系统
另外一个是给银行客户使用的对外开放的系统(人多的时候日均数千人)

**Comment by xiarugu** [comment]
另外我发现一点变化
以前视图中的ms-if="xxx"
如果模型中没有定义xxx的话会默认作为false处理, 但是现在似乎ms-if会被忽略, 而且还会导致ms-if对应的标签内的绑定都被忽略.

这一点感觉比较糟糕.

希望模型中没定义的在视图中都视作null
