### ISSUE TITLE
异步渲染带来的问题

### ISSUE THREAD

**Issue by xiarugu** [RubyLouvre/avalon#1039]
描述一个常见的应用场景,
有A,B,C,D四种订单类型, 当我点击了A的时候, 表示当前选中了A类型, 
然后下面有某个input是ms-if="current==A"的逻辑, 选中A类型才会显示的.
然后为了提升用户体验, 我在点击订单类型触发choose_type, 设置current=A以后, 
$('#input').focus()
希望焦点自动落到下面的input上, 因为按照业务逻辑, 用户选完类型后就需要输入这个input的值.

问题来了, 因为异步渲染, 导致current=A以后, 下面的input不会立即出现, 所以我这里设置focus会失败无效.
或许我可以用setTimeout来实现, 但是, 为了不太能感觉到的性能提升, 导致我的逻辑代码变得更加复杂了. 

这是我们非常不愿意见到的, 类似的场景非常多.
做了A操作以后需要自动设置下一步的focus.

希望司徒考虑一下这个问题

**Comment by IndexXuan** [comment]
遇到过，如果是repeat出来的还能有的rendered回调，要是普通的确实没有个时机。

**Comment by xiarugu** [comment]
或者在avalon.config里加一个配置选项, 让用户选择打开或关闭异步渲染
昨晚切换到1.5.1以后今天遇到很多类似问题, 忘紧急解决

**Comment by xiarugu** [comment]
还有之前说的缺少模型属性的, 之前一直是作null处理的, 现在变成忽略了本来each/repeat循环中, el缺少某个属性就直接{{el.xxx}}不显示的, 结果现在变成保留{{el.xxx}}在原地了.

这都无端提高了大家的升级难度, 降低了升级意愿啊.

**Comment by xiarugu** [comment]
这个问题不解决可能周末就不得不退回1.46版本了

**Comment by xiarugu** [comment]
毕竟异步永远是程序员的一个头大的问题.
异步渲染如果要让大家不得不面临异步操作dom的话, 那就真的得不偿失了.

**Comment by IndexXuan** [comment]
直接在input上加入autofocus暂时解决嘛。。。兼容性要求很高很高吗。

**Comment by xiarugu** [comment]
刚发现另外一个问题
以前通过代码触发input的change事件是可以改变input上ms-duplex对应的视图模型的值的
现在不行了, 又要躺下一批代码.....

**Comment by xiarugu** [comment]
啊, 烦躁啊, 怎么$watch回调里的this指向也变了!!!

**Comment by xiarugu** [comment]
司徒你要玩儿死我们啊

**Comment by xiarugu** [comment]
@IndexXuan autofocus只会在页面初次加载是获得焦点, 后续通过ms-visible或者ms-if展现的dom中autofocus是没用的

**Comment by RubyLouvre** [comment]
```html
<!doctype hmtl>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
        <title>attribute</title>
        <script type="text/javascript" src="avalon.js"></script>
        <script>
            var vm = avalon.define({
                $id: "ava",
                txt: "avalon",
                eee:{}
            })
        </script>
    </head>

    <body ms-controller="ava">
        <div ms-if="eee.aaa" ms-text="txt">xxxx</div>
    </body>


</html>
```
只能保证eee.aaa这样。不能保证aaa的情况。以前1.45 也是这逻辑

**Comment by RubyLouvre** [comment]
已经处理ms-if的问题

**Comment by RubyLouvre** [comment]
avalon.config本来就有一个开关，处理异步渲染的kernel.async =true

```javascript
avalon.config({
    async: false
})
```

**Comment by xiarugu** [comment]
好, 我现在马上去关掉async

**Comment by RubyLouvre** [comment]
在这里的版本已经将$watch this 指向BUG也修了 https://github.com/RubyLouvre/avalon2

**Comment by xiarugu** [comment]
另外avalon.mix功能似乎有点问题
之前如果b是一个复杂对象(包含多属性, 数组型子属性)
avalon.mix(true, vm.a, vm.b)
是没有问题的, 现在升级以后会警告超出循环, 导致mix失败
必须改成 avalon.mix(true, vm.a, vm.b.$model) 才可以.

**Comment by RubyLouvre** [comment]
avalon.mix没有问题，一直没有改; 你不应该这样为vm.a赋值的，应该直接重写; vm.a = newa;
