### ISSUE TITLE
请教司徒用的什么压缩工具

### ISSUE THREAD

**Issue by xiarugu** [RubyLouvre/avalon#1040]
我下载未压缩的版本修改后用Uglify压缩后执行总是报错, 未压缩前运行没问题
想问问司徒github上的min版本是用什么工具压缩的?

**Comment by RubyLouvre** [comment]
gulp-uglify'

**Comment by liudianpeng** [comment]
gulp

**Comment by liudianpeng** [comment]
@xiarugu gulp

**Comment by xiarugu** [comment]
windows开发环境, 安装了nodejs以后, 捣鼓了几次uglify都安装失败, 放弃了.
