### ISSUE TITLE
avalon.componen的配置extends单词错误

### ISSUE THREAD

**Issue by anrip** [RubyLouvre/avalon#1042]
extend是一个动词，不应该使用s。

抱歉，我真不是来找事儿的，只是想我们的js能更好的和agular比肩

**Comment by RubyLouvre** [comment]
我是参考polymer来设计，它是使用extends, 第三人称单数; angular则使用extend;

当然使用 extend也可以，因为extends是保留字

**Comment by anrip** [comment]
我还真没注意到 extends 是保留字，平时自己也偶尔使用extends，后来经以为同事提醒，直接用extend，现在你的提醒，又让我更确定不使用extends了。
