### ISSUE TITLE
required + ms-if + form产生的一个坑

### ISSUE THREAD

**Issue by xiarugu** [RubyLouvre/avalon#1044]
```
<form id="postForm"></form>
<input type="text" form="postForm" ms-if="xxx" required/>
```
在某些开发环境下, 我们需要将一个表单域放置在表单元素之外. 这时候需要使用form属性.
而如果刚好这个input有required属性, 并且由ms-if控制显示, 同时满足这三个条件就会产生一个"坑".

按照使用者的角度来看, ms-if为false的时候, 这个元素会被从dom树移除, 但实际上, 这个input还在dom树中, 只是被avalon移到head标签里隐藏起来了.

但是移动和隐藏并不影响form和required的生效, 于是提交表单会抛出一个js错误, 因为浏览器在表单提交前会尝试focus到这个required, 但是值又为空的input上, 而因为不可见, focus失败, 于是产生了错误.

这应该不算是avalon的bug, 不过确实是一个坑, 司徒可以考虑要不要帮助使用者填坑, 以避免他们犯这个错误.

**Comment by xiarugu** [comment]
如果司徒想要填坑也很简单, 移除的时候把form属性变成其他名字(比如ava-form)
移入的时候再把 ava-form属性恢复成form

因为还有一些其他的属性会触发类似的错误, 例如H5的pattern属性

**Comment by RubyLouvre** [comment]
这需要加上ms-disabled

**Comment by xiarugu** [comment]
"使用者"可以有很多方法避免这个问题, 我的意思是avalon本身可以做一些事情来帮助使用者避免这个问题, 以达到"真的像被移除出了DOM树一样"的效果.

**Comment by RubyLouvre** [comment]
```
an-invalid-form-control-with-name-is-not-focusable
```
 大概是抛这个错误

已经 修正
https://github.com/RubyLouvre/avalon/commit/5779e5282f2416259ddcbc6c33c21a6232f91bf4
