### ISSUE TITLE
mmState 第三级状态无效问题

### ISSUE THREAD

**Issue by 77660331** [RubyLouvre/avalon#1047]
define(["utils","mmState"], function(utils){

// 应采用程序主状态视图
	avalon.state("appState", {
		url: "/",
		abstract: false, // 抽象状态，不会对应到url上
		views: {
		"appmain": {
			template: function() {
			return ""
			} // 指定一个返回字符串的函数来获取模板
                   // controllerUrl: "./controller/blog.js" // 指定控制器地址
		}, // 也可以不配置 ""，直接在子状态内定义 "@"来覆盖重写
		"header": { // 视图名字的语法请仔细查阅文档
			templateUrl: "/header.html?"+utils.$timeId()// 指定模板地址,
				   
			}, // 指定一个返回字符串的函数来获取模板
		"appmenubar": { // 视图名字的语法请仔细查阅文档
			template: function() {
			return ""
			},
			controllerUrl: "models/wsms/wsms.js" // 指定控制器地址
			}
		},
		onEnter: function () {
            // require(["wsmsState"], function(wsmsState) {
			 // alert("hello")
			   
			//})
        }
			
	})
		

	avalon.state("appState.wsms", {
            url: "models/wsms",
            abstract: false, // 等于true的话抽象状态，不会对应到url上
            views: {
                
					
					
				"appmenubar@": { // 视图名字的语法请仔细查阅文档
                    templateUrl: "models/wsms/menubar.html?"+utils.$timeId()
					//controllerUrl: "./controller/blog.js" // 指定控制器地址
                }
            },
			onEnter: function () {
          
		   
        }
        })
			
	avalon.state("appState.wsms.column", {
            url: "models/wsms/column",
            views: {
				
                "appmain@": {
            		  templateUrl: "models/wsms/column/column.html?"+utils.$timeId()
                  	  // 指定控制器地址
                }
                
            },
			onEnter: function () {
          
		   
        }
       })	
		
		
	avalon.state.config({
		onError: function() {
		 //console.log(arguments)
		} ,// 强烈打开错误配置
			onViewEnter: function(newNode, oldNode) {/*console.log(newNode)*/
			
			
		}
	})
	
})

<a href="#!/models/wsms/column">链接测试</a>  点击无法去到appState.wsms.column 状态，点击链接无反应

appState.wsms.column状态改为覆盖appState.wsms状态即：将

	avalon.state("appState.wsms.column", {
            url: "models/wsms/column",
            views: {
				
                "appmain@": {
            		  templateUrl: "models/wsms/column/column.html?"+utils.$timeId()
                  	  // 指定控制器地址
                }
                
            },
			onEnter: function () {
          
		   
        }
       })	

改为

	avalon.state("appState.wsms", {
            url: "models/wsms/column",
            views: {
				"appmenubar@": { // 视图名字的语法请仔细查阅文档
                    templateUrl: "models/wsms/menubar.html?"+utils.$timeId()
					//controllerUrl: "./controller/blog.js" // 指定控制器地址
                },
                "appmain@": {
            		  templateUrl: "models/wsms/column/column.html?"+utils.$timeId()
                  	  // 指定控制器地址
                }
                
            },
			onEnter: function () {
          
		   
        }
       })	

则点击链接正常，且之前的二级状态依然有效

**Comment by 77660331** [comment]
唉，并不是二级依然有效，而是直接覆盖了之前的二级，三级确实无效

**Comment by 77660331** [comment]
还有使用mmstate 一直会出现视图未定义的警告，虽然视图还是能渲染

warning:exception throwed in [avalon.injectBinding]  ReferenceError: header is not defined
    at Number.eval (eval at parseExpr (http://192.168.0.248/com/avalon.js:2953:23), <anonymous>:5:8)
    at Object.avalon.injectBinding.binding.update (http://192.168.0.248/com/avalon.js:1780:40)
    at Function.avalon.injectBinding (http://192.168.0.248/com/avalon.js:1824:13)
    at executeBindings (http://192.168.0.248/com/avalon.js:3082:16)
    at scanAttr (http://192.168.0.248/com/avalon.js:3211:13)
    at scanTag (http://192.168.0.248/com/avalon.js:3356:5)
    at scanNodeArray (http://192.168.0.248/com/avalon.js:3293:17)
    at scanNodeList (http://192.168.0.248/com/avalon.js:3283:5)
    at scanAttr (http://192.168.0.248/com/avalon.js:3216:9)
    at scanTag (http://192.168.0.248/com/avalon.js:3356:5)

**Comment by gogoyqj** [comment]
你这url写的不对，比如 stateA 对应 /a， 配置未/a， 那么 stateA.childB 对应的是 /a/b，那么配置的url属性应该是 /b啊，内部会自动 /a + /b

**Comment by 77660331** [comment]
哦，明白了，之前一直以为state的url是和location.href对应的 ，非常感谢
