### ISSUE TITLE
OniUI 的tree组件，遇到点问题~

### ISSUE THREAD

**Issue by z893495246** [RubyLouvre/avalon#1048]
我在做一个OA系统，需要展示上下级关系，用到tree这个控件。
我这边数据绑定不成功，但是也不报错，我的json数据：
{dept_id: 2，dept_name: "上海总部"，dept_no: 1}
{dept_id:5,dept_name:"渠道部"，dept_no:2}
{XX}
{XX}
-------------------------------------------------------------
当我用它自己的json数据的时候，是可以完美的展示的。它 的json：
zNodes =[
            { id:1, pid:0, name:"父节点1 - 展开", open:true},
            { id:11, pid:1, name:"父节点11 - 折叠"},
            { id:111, pid:11, name:"叶子节点111"},
            { id:112, pid:11, name:"叶子节点112"},
            { id:113, pid:11, name:"叶子节点113"},
            { id:114, pid:11, name:"叶子节点114"},
            { id:12, pid:1, name:"父节点12 - 折叠"},
            { id:121, pid:12, name:"叶子节点121"},
            { id:122, pid:12, name:"叶子节点122"},
            { id:123, pid:12, name:"叶子节点123"},
            { id:124, pid:12, name:"叶子节点124"},
            { id:13, pid:1, name:"父节点13 - 没有子节点", isParent:true},
            { id:2, pid:0, name:"父节点2 - 折叠"},
            { id:21, pid:2, name:"父节点21 - 展开", open:true},
            { id:211, pid:21, name:"叶子节点211"},
            { id:212, pid:21, name:"叶子节点212"},
            { id:213, pid:21, name:"叶子节点213"},
            { id:214, pid:21, name:"叶子节点214"},
            { id:22, pid:2, name:"父节点22 - 折叠"},
            { id:221, pid:22, name:"叶子节点221"},
            { id:222, pid:22, name:"叶子节点222"},
            { id:223, pid:22, name:"叶子节点223"},
            { id:224, pid:22, name:"叶子节点224"},
            { id:23, pid:2, name:"父节点23 - 折叠"},
            { id:231, pid:23, name:"叶子节点231"},
            { id:232, pid:23, name:"叶子节点232"},
            { id:233, pid:23, name:"叶子节点233"},
            { id:234, pid:23, name:"叶子节点234"},
            { id:3, pid:0, name:"父节点3 - 没有子节点", isParent:true}
        ]
tree的配置：
vm.tree = {
                children: vm.zNodes,
                edit: {
                    showRemoveBtn: function(leaf) {
                        return leaf.level > 0
                    }
                },
                data: {
                    simpleData: {
                        enable: true,
                        idKey: "dept_id",
                        pIdKey: "dept_no"
                    },
                    key: {
                        name: "dept_name", 
                    },

                    keep: {
                        leaf: false,
                        parent: true
                    }
                },
                view: {
                    editNameSelectAll: true,
                    showLine: function(leaf) {
                        return true
                        return leaf.level > 1 || 1
                    }
                },
                callback: {
                    onExpand: function(leaf) {
                        console.log(leaf)
                    },
                    beforeRemove: function(obj) {
                        return confirm("确认删除?")
                    },
                    onRemove: function(leaf) {
                        console.log("remove " + leaf)
                    },
                    onRename: function(arg) {
                        console.log("renamed")
                    },
                    beforeAdd: function(obj) {
                        return confirm("确认添加?")
                    },
                    onNodeCreated: function(obj) {
                        avalon.log("node onNodeCreated")
                    }
                }
            }
            vm.$treeOpt = {
                children: [vm.child[0]]
            }
            vm.$skipArray = ["tree"]

**Comment by z893495246** [comment]
当我取到自己的json数据的时候，我是这样直接赋值的vm.zNodes =MyJson.

**Comment by z893495246** [comment]
这是我的代码
---------------------------------------------------------------------------
define(['avalon', 'text!./departmentList.html'], function (avalon, tpl) {
    return function () {
        avalon.templateCache.departmentListTpl = tpl;
        var vm = avalon.define({
            $id: "departmentListVM",
            tree:{},
            $treeOpt:{},
            $skipArray:{},
            items: [],

            child:[],
             zNodes :[

            ],
            //加载itemList数据
            getItems: function (status) {
            	//var pager = avalon.vmodels.taskPager;
                vm.loading=true;
                $.ajax({url:"../dePartment",
                	type:"post",
                    dataType: "json",
                    data:{},
                    async : false,
                    success: function(data){
                    	console.log("data:",data);
                    	vm.zNodes=data;
                    	console.log('JSon:',vm.zNodes);
                    
                    },
                    error:function(data,statusText){
                    	console.log('出错了！！！！！！！！！',data.statusText);
                    }
                });

      
            },

        });
        vm.tree = {
                children: vm.zNodes,
                edit: {
                    showRemoveBtn: function(leaf) {
                        return leaf.level > 0
                    }
                },
                data: {
                    simpleData: {
                        enable: true,
                        idKey: "dept_id",
                        pIdKey: "dept_no"
                    },
                    key: {
                        name: "dept_name", 
                    },

                    keep: {
                        leaf: false,
                        parent: true
                    }
                },
                view: {
                    editNameSelectAll: true,
                    showLine: function(leaf) {
                        return true
                        return leaf.level > 1 || 1
                    }
                },
                callback: {
                    onExpand: function(leaf) {
                        console.log(leaf)
                    },
                    beforeRemove: function(obj) {
                        return confirm("确认删除?")
                    },
                    onRemove: function(leaf) {
                        console.log("remove " + leaf)
                    },
                    onRename: function(arg) {
                        console.log("renamed")
                    },
                    beforeAdd: function(obj) {
                        return confirm("确认添加?")
                    },
                    onNodeCreated: function(obj) {
                        avalon.log("node onNodeCreated")
                    }
                }
            }
            vm.$treeOpt = {
                children: [vm.child[0]]
            }
            vm.$skipArray = ["tree"]
       

        avalon.vmodels.appVM.mainContent = "departmentListTpl";

    }
});

**Comment by z893495246** [comment]
我觉得应该是我赋值有问题，赋值之后输出
----------------------------------------------------------
Son: [Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, $id: "avalon331029944122", $model: Array[20], $events: Object, _: Object, $watch: function…]0: Object$events: Object$fire: function () { [native code] }$id: "avalon557760477066"$model: Objectdept_id: 2dept_name: "上海总部"dept_no: 1__proto__: Object$reinitialize: function () {$unwatch: function () { [native code] }$watch: function () { [native code] }dept_id: (...)get dept_id: function accessor(value) {set dept_id: function accessor(value) {dept_name: (...)get dept_name: function accessor(value) {set dept_name: function accessor(value) {dept_no: (...)get dept_no: function accessor(value) {set dept_no: function accessor(value) {hasOwnProperty: function (name) {__proto__: Object1: Object2: Object3: Object4: Object5: Object6: Object7: Object8: Object9: Object10: Object11: Object12: Object13: Object14: Object15: Object16: Object17: Object18: Object19: Object$events: Object$fire: function (type) {$id: "avalon331029944122"$model: Array[20]$unwatch: function (type, callback) {$watch: function (type, callback) {_: Object_fire: function (method, a, b) {_splice: function splice() { [native code] }clear: function () {contains: function (el) { //判定是否包含ensure: function (el) {length: 20pop: function () {push: function () {pushArray: function (array) {remove: function (el) { //移除第一个等于给定值的元素removeAll: function (all) { //移除N个元素removeAt: function (index) { //移除指定索引上的元素reverse: function () {set: function (index, val) {shift: function () {size: function () { //取得数组长度，这个函数可以同步视图，length不能sort: function () {splice: function (start) {unshift: function () {__proto__: Array[0]

**Comment by gogoyqj** [comment]
你看一下tree的文档，tree的节点不能这么设置，应该是通过 reset(children)来设置

**Comment by z893495246** [comment]
问题已决绝~    是数据结构父子关系搞错了。。设计表的那个同事坑爹了，
