### ISSUE TITLE
1.5.1版本 ms-include问题

### ISSUE THREAD

**Issue by PhoonLee** [RubyLouvre/avalon#1049]
假设根目录有a.html  b.html俩个子页面
做子模板的切换的时候，是不断的在后面插入模板内容，而不是切换
1.4.6版本就没问题,是切换...是要另外配置吗?

**Comment by RubyLouvre** [comment]
这个前前前天已经搞定了，更新 https://github.com/RubyLouvre/avalon/tree/1.5.0
