### ISSUE TITLE
tag 1.5.1 -- avalon.modern.js 存在bug

### ISSUE THREAD

**Issue by mw312** [RubyLouvre/avalon#1050]
运行例子：include.html
当切换模板时，chrome浏览器报错：
Uncaught TypeError: avalon.setter is not a function(anonymous function) @ avalon.modern.js:3401
改为1.4.6.2版本的正常，但是将data-include-replace="false"改为false，依然自动替代掉其原父容器节点。

还有一个问题是：使用1.5.1版本的avalon.js，切换模板时使用指令data-include-replace="true"没有自动替代掉其原父容器节点。

代码如下：

        <script src="avalon.js"></script>
        <script>
           var model = avalon.define({
                $id: "test",
                url: "Template1",
                name: "司徒正美",
                password: '12345678',
                array: [1, 2, 3, 4, 5, 6, 7],
                add: function(e) {
                    if (this.value && e.which == 13) {//this为input元素
                        var a = this.value
                        model.array.push(a)
                        this.value = "";
                    }
                }
            })
        </script>
    </head>
    <body>
        <h3 style='text-align: center'>ms-include</h3>
        <div ms-controller="test">
            <select ms-duplex="url">
                <option>Template1</option>
                <option>Template2</option>
                <option>Template3</option>
            </select>
            <div ms-include-src="include{{url}}.html" data-include-replace="true"></div>
        </div>

**Comment by RubyLouvre** [comment]
这个好像是前前前天修了
更新到1.5.2就没事了

除一个警告就没事了

![image](https://cloud.githubusercontent.com/assets/190846/9899468/94b26272-5c8c-11e5-85ee-281c3cd9e355.png)
