### ISSUE TITLE
@司徒大哥。  tree组件添加，删除按钮失效

### ISSUE THREAD

**Issue by z893495246** [RubyLouvre/avalon#1053]
总是报错：Uncaught TypeError: arr.pushArray is not a function
我的代码是按照UI的列子copy过来改了一下。事件代码那一块没有动。
@RubyLouvre 大哥帮我看看呗，刚接触这个框架
--------------------------------------------------------------------------------------------------
```
  vm.tree = {
        		children: vm.zNodes,
                edit: {
                    showRemoveBtn: function(leaf) {
                        return leaf.level > 0
                    }
                },
                data: {
                    simpleData: {
                    	 enable: true,
                         idKey: "dept_id",
                         pIdKey: "dept_parent"
                    },
                    key: {
                        name: "dept_name", 
                    },
                    keep: {
                        leaf: false,
                        parent: true
                    }
                },
                view: {
                    editNameSelectAll: true,
                    showLine: function(leaf) {
                        return true
                        return leaf.level > 1 || 1
                    }
                },
                callback: {
                    onExpand: function(leaf) {
                        console.log(leaf)
                    },
                    beforeRemove: function(obj) {
                        return confirm("确认删除?")
                    },
                    onRemove: function(leaf) {
                        console.log("remove " + leaf)
                    },
                    onRename: function(arg) {
                        console.log("renamed")
                    },
                    beforeAdd: function(obj) {
                        return confirm("确认添加?")
                    },
                    onNodeCreated: function(obj) {
                        avalon.log("node onNodeCreated")
                    }


                }
        
            }
            vm.$treeOpt = {
                children: [vm.child[0]]
            }
            vm.$skipArray = ["tree"]
```

**Comment by RubyLouvre** [comment]
你没有说哪一个例子啊

**Comment by z893495246** [comment]
@RubyLouvre   tree - 简单数据模式                     这个例子

**Comment by z893495246** [comment]
@RubyLouvre http://ued.qunar.com/oniui/index.html#!/widgets?widgetId=tree&ex=ex2

**Comment by gogoyqj** [comment]
别用 vm.arr来个tree赋值，要用原生数组。。。或者 vm.arr.$model

**Comment by z893495246** [comment]
@gogoyqj  我啥也没赋值，那个报错是avalon.tree.js这个Ui文件报的错

**Comment by z893495246** [comment]
@gogoyqj http://ued.qunar.com/oniui/index.html#!/widgets?widgetId=tree&ex=ex2  你看这个UI例子就明白了，我照抄的。。。。。。他这个例子添加，删除，编辑都没问题的。

**Comment by RubyLouvre** [comment]
看一下控制台，有没有报错，是不是有些依赖没有加载到;或者你截图贴上来

**Comment by z893495246** [comment]
@RubyLouvre 有报错的
-----------------------------------------------------
Uncaught TypeError: arr.pushArray is not a function(anonymous function) @ avalon.tree.js:742avalon.ui.tree.avalon.define.vm.excute @ avalon.tree.js:1057avalon.ui.tree.avalon.define.vm.addNodes @ avalon.tree.js:726avalon.ui.tree.AddExtention.avalon.mix.addFun @ avalon.tree.edit.js:98avalon.ui.tree.avalon.define.vm.excute @ avalon.tree.js:1057(anonymous function) @ VM1810:4bindingExecutors.on.callback @ avalon.js:4121

**Comment by z893495246** [comment]
![Uploading 966.jpg…]()

**Comment by z893495246** [comment]
vm.addNodes = function(parentLeaf, nodes, isSilent) {
                return vm.excute('nodeCreated', {
                    isSilent: isSilent
                } , parentLeaf, function() {
                    // 数据构建
                    if(vm.data.simpleData.enable && (nodes instanceof Array)) {
                        nodes = vm.transformTozTreeNodes(nodes)
                    } else {
                        nodes = nodes instanceof Array ? nodes : [nodes]
                    }
                    nodes = dataFormator(nodes, parentLeaf, undefine, undefine, vm)
                    // 这里node依旧没有$id属性
                    // dataFormator(nodes, parentLeaf, "构建父子节点衔接关系", undefine, vm)
                    if(parentLeaf) parentLeaf.isParent = true
                    // open的监听可能没有捕捉到
                    if(!isSilent && parentLeaf) parentLeaf.open = true
                    var arr = vm.getNodes(parentLeaf), len = arr.length
                    arr.pushArray(nodes)   【就是这里的问题】是avalon.tree.js这个文件
                    var addNodes = arr.slice(len) || []
                    // 构建，只有在nodes被push到数组之后才会拥有$id,$events等属性
                    dataFormator(addNodes, parentLeaf, '\u6784\u5EFA\u7236\u5B50\u8282\u70B9\u8854\u63A5\u5173\u7CFB', undefine, vm);
                    // 更具$id属性build cache
                    avalon.each(addNodes, function(i, leaf) {
                        cache[leaf.$id] = leaf
                    })
                    return addNodes
                })
            }

**Comment by z893495246** [comment]
![966](https://cloud.githubusercontent.com/assets/14210139/9899907/89c9674a-5c8f-11e5-9bf6-1230f920e88b.jpg)

**Comment by z893495246** [comment]
![977](https://cloud.githubusercontent.com/assets/14210139/9899931/b148987c-5c8f-11e5-941d-bda1bc43d40f.png)
@RubyLouvre

**Comment by z893495246** [comment]
@RubyLouvre 大哥能帮忙解决不，，，实在不知道怎么办了。。。照例子抄的也报错

**Comment by gogoyqj** [comment]
```javascript
vm.tree = {
                children: vm.zNodes,
```

这里啊，不能把vmodel的属性赋值过去，必须要 原生数组

**Comment by z893495246** [comment]
@gogoyqj 不应该是个Json对象吗？ zNodes里面是json数据。  我数据显示是正常的。

**Comment by liudianpeng** [comment]
你为什么要用vm.tree = {
                children: vm.zNodes,}这样可以吗?我也是新手,这样不可以吧, 你这是又用simpleData,有用key,可以吗???????

**Comment by z893495246** [comment]
@liudianpeng 你去好好看看tree数据模式。。。。。

**Comment by liudianpeng** [comment]
@z893495246 简单数据模式是什么意思呢?????是不是还有其他的模式阿

**Comment by z893495246** [comment]
@liudianpeng  http://ued.qunar.com/oniui/index.html#!/widgets?widgetId=tree&ex=ex2  去看看

**Comment by liudianpeng** [comment]
@z893495246 这里面并没有配置key阿

**Comment by z893495246** [comment]
@gogoyqj  很感谢你回答我的问题，你说的那个vm.tree赋值那个问题，我觉得跟这个应该没有关系吧？因为我的vm.zNodes里面的值就是Json数组格式的~   回头我试试看~
