### ISSUE TITLE
使用ms-conponent报错:Uncaught ReferenceError: widgetList is not defined

### ISSUE THREAD

**Issue by Lihuanghe** [RubyLouvre/avalon#1054]
异常信息
`Uncaught ReferenceError: widgetList is not defined`\
demo地址： http://lihuanghe.github.io/avalontest/

![qq 20150916193328](https://cloud.githubusercontent.com/assets/7598107/9903608/441fe37a-5caa-11e5-8b01-461f6edea576.png)
点击首面-》记事本后，就会报错。

**Comment by RubyLouvre** [comment]
https://github.com/RubyLouvre/avalon/tree/1.5.2  好了
