### ISSUE TITLE
component组件带有id时，GC的顺序问题，导致新建的vm被销毁

### ISSUE THREAD

**Issue by Lihuanghe** [RubyLouvre/avalon#1056]
demo地址 ： http://lihuanghe.github.io/avalontest/#!/33
浏览器chrome:
我的自定义组件这么写的：有一个固定的ID,方便以后使用。
<jq:datagrid config="$datagridopt" $id="test"></jq:datagrid>
但是当页面切换后再进入有组件的页面后，是先执行组件的init方法，后销毁原来的组件，因为id相同导致新建的vm被销毁了。
效果是这样的：
第一次进来：
![1](https://cloud.githubusercontent.com/assets/7598107/9923872/77aeac4e-5d2c-11e5-8870-833a98ed42f0.png)
切换到另一个菜单：
![2](https://cloud.githubusercontent.com/assets/7598107/9923880/8770c446-5d2c-11e5-9c1c-4a955f2fab07.png)
再切换回来：
![3](https://cloud.githubusercontent.com/assets/7598107/9923890/95031ea6-5d2c-11e5-85b6-66f9288e2ec6.png)
此时在vmodels里就没有test这个vm了。

**Comment by RubyLouvre** [comment]
使用data-include-cached="true"

**Comment by Lihuanghe** [comment]
ok了，已经不会销毁了。页面比较少，不回收应该问题不大

**Comment by Lihuanghe** [comment]
这个问题我的最终解决办法是在router切换时在两个view中间插一个带有组件的loader的view，这样每次销毁的就是loader，不影响使用。可以看下这个http://lihuanghe.github.io/avalontest/#!/33
