### ISSUE TITLE
$watch 数组对象 的属性变化。

### ISSUE THREAD

**Issue by luchaoshuai** [RubyLouvre/avalon#1067]
```
 var model = avalon.define({
        $id:'test1',
        rows : [
            {
                a: 1,
                b: 1,
                c: 0.5,
                d: 0.5,
                e: 1.2,
                f: 0.83
            },
            {
                a: 2,
                b: 1,
                c: 0.5,
                d: 0.5,
                e: 1.2,
                f: 0.83
            }
        ],
        click: function () {
            model.rows.push({
                a: new Date-0,
                b: 0,
                c: 0,
                d: 0,
                e: 0,
                f: 0
            })
        }
    });
```
怎么样$watch到rows里面的各个属性变化？

**Comment by RubyLouvre** [comment]
请标注你使用的版本，1.4x是做不到，1.5x也不能监听push方法引起的变 化;详见avalonjs.github.io中的$watch部分

**Comment by luchaoshuai** [comment]
https://avalonjs.github.io/#zh/concepts/$watch.html 上的文档我看了，我现用的是1.4.6的。
我可以选用最新的。1.5.2.但是测试发现，1.5的版本不能用 row[name] 取值。只能用row.name.
------------------------------------------------------------------------------
<table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th ms-repeat-col='col'>
                        {{col.id}}.{{col.name}}
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr ms-repeat-row='rows'>
                    <td ms-repeat-col='col'>
                        {{col.id}}.{{col.name}}{{row[col.id]}}{{row.a}}
                        <br />
                        <input type="text" width="20" ms-duplex="row[col.id]">
                    </td>
                </tr>
            </tbody>
        </table>
------------------------------
  var model = avalon.define({
        $id:'performance',
        rows : [
            {
                a: 1,
                b: 1,
                c: 0.5,
                d: 0.5,
                e: 1.2,
                f: 0.83
            },
            {
                a: 2,
                b: 1,
                c: 0.5,
                d: 0.5,
                e: 1.2,
                f: 0.83
            }
        ],
        click: function () {
            model.rows.push({
                a: new Date-0,
                b: 0,
                c: 0,
                d: 0,
                e: 0,
                f: 0
            })
        },
        col : [ 
            { id: 'a', name: "no", desp: "行号", formula: '' },
            { id: 'b', name: "质量", desp: "净质量", formula: ['=e*f', '=c*d'] },
            { id: 'c', name: "体积", desp: "无说明信息", formula: ['=b/d'] },
            { id: 'd', name: "密度", desp: "无说明信息", formula: ['=b/c'] },
            { id: 'e', name: "毛重", desp: "带包装的，不纯时的重量", formula: ['=b/f'] },
            { id: 'f', name: "纯度", desp: "无说明信息", formula: ['=b/e'] }
        ]
    });
--------------------------
我想做一个由用户自已配置的，类似excel表格那样的，带有公式自动计算的表格。
司徒有相关的参考案例没，或着给个思路也好。

**Comment by RubyLouvre** [comment]
这个我的parser存在BUG，正在重写parser！

**Comment by RubyLouvre** [comment]
已经修复;但我
