### ISSUE TITLE
ms-include-src问题

### ISSUE THREAD

**Issue by PhoonLee** [RubyLouvre/avalon#1068]
版本1.4.6
ie8环境,ms-include-src引入外模板的时候,外模板页面上的js不运行..ie9及高级点的浏览器就能运行.

**Comment by Lihuanghe** [comment]
view模板里不要带js

**Comment by PhoonLee** [comment]
那都是写在rendered那边吗?

**Comment by RubyLouvre** [comment]
你不要在里面写script啊
