### ISSUE TITLE
avalon 1.5使用 require.js 引入后还是 undefined，1.4没问题。

### ISSUE THREAD

**Issue by virusdefender** [RubyLouvre/avalon#1069]
```html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<script src="http://requirejs.org/docs/release/2.1.20/comments/require.js"></script>
<script>
    require(["avalon14"], function(){
        console.log(avalon);
    });

    require(["avalon15"], function (avalon) {
        console.log(avalon);
    })


</script>
<div ms-controller="test">



</div>

</body>
</html>
```

avalon14和 avalon15就是官方下载的，没有改动。

**Comment by Lihuanghe** [comment]
你的avalon.js改成avalon14.js和avalon15.js了吗？

**Comment by virusdefender** [comment]
@Lihuanghe 改了啊

**Comment by RubyLouvre** [comment]
要用avalon.shim

**Comment by virusdefender** [comment]
@RubyLouvre 

hi~这个问题没有解决。

我现在更新 avalon 1.5.4还是这样的。仍然是上面的 demo。

avalon14的地址是https://github.com/RubyLouvre/avalon/blob/master/dist/avalon.shim.js

avalon15的地址是https://github.com/RubyLouvre/avalon2/blob/master/dist/avalon.shim.js

avalon15的时候输出 undefined

很需要1.5的 component 的特性，但是现在遇到的问题有些多~

谢谢了~
