### ISSUE TITLE
1.5.2使用数组的clear方法情空数组后，视图还是显示原有数组元素，不会改变。

### ISSUE THREAD

**Issue by xualen** [RubyLouvre/avalon#1072]
<!doctype html>
<html lang="en">

	<head>
		<meta charset="UTF-8" />
		<title>Document</title>
	</head>

	<body ms-controller='g'>
		<div ms-repeat='arr' ms-text='el' ms-click='deleteAll'></div>
	</body>

</html>
<script src="js/avalon.1.52.shim.min.js"></script>
<script src="js/jquery.min.js"></script>
<script>

	avalon.ready(function(){
		var vm=avalon.define({
			$id:'g',
			arr:[1,2,3,4,5,6,7],
			deleteAll:function(){
				vm.arr.clear();
				console.log(vm.$model.arr);
			}
		});

		avalon.scan();
	})

</script>

**Comment by wrx362114** [comment]
我也遇到这个问题了,只能用removeat来移出时才有效

**Comment by RubyLouvre** [comment]
已修
