### ISSUE TITLE
avalon mmstate smartgrid

### ISSUE THREAD

**Issue by davidduwei** [RubyLouvre/avalon#1075]
![qq 20150925173011](https://cloud.githubusercontent.com/assets/7507764/10097317/d2a47bb8-63aa-11e5-947e-5975ef43a3c9.png)
![qq 20150925173127](https://cloud.githubusercontent.com/assets/7507764/10097402/6cb9124a-63ab-11e5-9d59-89de9579992e.png)
![qq 20150925173133](https://cloud.githubusercontent.com/assets/7507764/10097666/4031d548-63ad-11e5-9919-05e291720bf7.png)
点击c，在迅速点击b。会存在找不到avalon.vmodels.smartgrid的情况。

**Comment by lazyhero** [comment]
你有尝试过子状态吗？ 这是最新的mmState 和 avalon1.5吗

**Comment by davidduwei** [comment]
@lazyhero 使用的avalon1.4最新版本。其他都是最新的。

**Comment by RubyLouvre** [comment]
smartgrid最近更新了几次，可以再试试

**Comment by davidduwei** [comment]
这个问题依然存在哈，
![qq 20151102205742](https://cloud.githubusercontent.com/assets/7507764/10882245/ff39759a-81a3-11e5-8479-c369623e9bb3.png)
我正常点击有时候都会报这个错误。

**Comment by roscoe054** [comment]
你的c状态怎么定义的，代码里没看到？

**Comment by davidduwei** [comment]
c状态我没有定义，错误会直接跳转到nopermission状态。

**Comment by roscoe054** [comment]
我试了下mmstate smartgrid一起用，没复现你的问题。所以可能是别的原因，最好能给出完整代码

**Comment by davidduwei** [comment]
刚刚更新 用的最新的代码试了下，还是存在这个问题哈，mmstate 使用的 https://github.com/RubyLouvre/mmRouter 下载的最新代码。
![Uploading 123.png…]()

index1.html:

&lt;ul&gt;
    &lt;li&gt;
      &lt;a href="#!/a"&gt;图片上传管理&lt;/a&gt;
    &lt;/li&gt;
    &lt;li&gt;
      &lt;a href="#!/b"&gt;商品套餐管理&lt;/a&gt;
    &lt;/li&gt;
    &lt;li&gt;
      &lt;a href="#!/c"&gt;没有此页面&lt;/a&gt;
    &lt;/li&gt;
  &lt;/ul&gt;
  &lt;div ms-view=""&gt;&lt;/div&gt;

    require(['mmState'], function() {
      avalon.define('root', function(vm) {});
      avalon.state("a", {
        controller: "root",
        url: "/a",
        views: {
          "": {
            templateUrl: "/omni/a.html",
            controllerUrl: '/omni/a.js'
          }
        }
      })
      avalon.state("b", {
        controller: "root",
        url: "/b",
        views: {
          "": {
            templateUrl: "/omni/b.html",
            controllerUrl: '/omni/b.js'
          }
        }
      });
      //无权限页面
      avalon.state("nopermission", {
        controller: "root",
        url: "/nopermission",
        views: {
          "": {
            templateUrl: "/omni/nopermission.html"
          }
        }
      });
      //接着下来通过mmState这个基于状态机的高级路由器，定义各种状态
      //（每个状态包含各个要处理的模板容器，获取模板的手段，中途会发生的各种回调）
      function errorcallback() {
        avalon.router.navigate('/nopermission');
      }
      avalon.scan();
      avalon.router.error(errorcallback);
      //启动路由
      avalon.history.start({
        basepath: "/"
      });
    })

a.html
&lt;div ms-controller="blog"&gt;a页面&lt;/div&gt;

<pre>
 define([], function() {
    var blog = avalon.define("blog", function(vm) {})
    return avalon.controller(function($ctrl) {
        $ctrl.$onRendered = function() {}
        $ctrl.$onEnter = function() {}
        $ctrl.$onBeforeUnload = function() {}
        $ctrl.$vmodels = []
    })
})
</pre>

b.html
&lt;div ms-controller="msb"&gt;
	b页面
	&lt;div class="" ms-widget="smartgrid,grid,$smartgridOpts"&gt;&lt;/div&gt;
&lt;/div&gt;

<pre>
define(['smartgrid/avalon.smartgrid'], function() {
	var blog = avalon.define("blog", function(vm) {})

	function getDatas(number) {
		var data = []
		for (var i = 0; i < number; i++) {
			data.push({
				name: "shirly" + i,
				age: parseInt(10 + Math.random() * 20),
				selected: i % 3 ? false : true,
				salary: parseInt(Math.random() * 100),
				operate: i % 5 ? 0 : 1,
				busy: !i % 3 && !i % 5 ? 0 : 1
			})
		}
		return data
	}
	return avalon.controller(function($ctrl) {
		$ctrl.$onRendered = function() {
				avalon.define('msb', function(vm) {
					vm.$smartgridOpts = {
						autoResize: false,
						columns: [{
							key: "name", //列标识
							name: "姓名", //列名
							sortable: true, //是否可排序
							isLock: true, //是否锁死列让其始终显示
							align: "left", //列的对象方式
							defaultValue: "shirly", //列的默认值
							customClass: "ddd", //自定义此列单元格类
							toggle: false, //控制列的显示隐藏
							width: 400 //设置列的宽度
						}, {
							key: "age",
							name: "年龄",
							sortable: true,
							width: 300
						}, {
							key: "salary",
							name: "薪水",
							type: "Number",
							sortable: true,
							align: "right",
							width: 300
						}],
						data: []
					}
				})
				avalon.scan();
				setTimeout(function() {
					var list = getDatas(40);
					avalon.vmodels.grid.render(list);
				}, 200)
			}
			// 进入视图
		$ctrl.$onEnter = function() {}
			// 对应的视图销毁前
		$ctrl.$onBeforeUnload = function() {}
			// 指定一个avalon.scan视图的vmodels，vmodels = $ctrl.$vmodels.concact(DOM树上下文vmodels)
		$ctrl.$vmodels = []
	})
})
</pre>

**Comment by davidduwei** [comment]
![123](https://cloud.githubusercontent.com/assets/7507764/10901105/fc45cdae-8223-11e5-8d25-8795dd33b210.png)

**Comment by roscoe054** [comment]
这是因为`avalon.vmodels.grid.render(list)`这句在setTimeout里面，它执行的时候切到已经别的state上面，avalon.vmodels.grid被销毁了。

**Comment by davidduwei** [comment]
用setTimeout主要是考虑到ajax肯定都会存在延时的，而且即便是去掉了setTimeout，如果数据不是直接传在data参数上，而是通过render渲染的还是会存在这样的问题哈，只是几率确实小了很多，难道创建avalon.vmodels.grid也是有延时的吗？

**Comment by roscoe054** [comment]
这都是因为切换快所致的，如果想防止报错，可以在切换的时候中断ajax，然后在render前面加个判断条件，看avalon.vmodels.grid是否为undefiend
