### ISSUE TITLE
avalon1.5同最新mmState结合问题

### ISSUE THREAD

**Issue by lazyhero** [RubyLouvre/avalon#1076]
具体问题贴在了[mmRouter-demo-list用avalon1.5改写问题](http://www.avalon.org.cn/art/560761d4368035034a0001a0)中文社区

现在1.5是还没有跟路由部分做整合吧？

**Comment by RubyLouvre** [comment]
oniui的mmRouter早已可以与avalon1.5+使用了

**Comment by RubyLouvre** [comment]
不过1.5不支持旧风格，你应该使用新风格定义VM就好了

**Comment by wuzhichen** [comment]
结合mmState还不是那么爽滑，mmState种的// 事件管理器 还用的就风格define定义

**Comment by lkiarest** [comment]
mmState感觉还是得司徒大神重写个吧~~  1.5还是有性能问题
