### ISSUE TITLE
升级到 1.5 之后 ms-widget 废了，我用的 carousel 和 camera 都跑不起来了

### ISSUE THREAD

**Issue by fish-ball** [RubyLouvre/avalon#1080]
用 1.4 是没有问题的，请确认？

**Comment by RubyLouvre** [comment]
是的，建议自己根据ms-widget从avalon.component重写 http://www.cnblogs.com/rubylouvre/p/4799687.html
改好，记得给我贡献代码

**Comment by fish-ball** [comment]
好吧，谢谢。。但是涉及这么大的 deprecation 从[版本管理](http://semver.org/lang/zh-CN/)的角度来说其实是要升一个主版本号的。。

**Comment by RubyLouvre** [comment]
https://github.com/RubyLouvre/avalon2/tree/master/component

**Comment by RubyLouvre** [comment]
这是已经改好的组件

**Comment by fish-ball** [comment]
OK，我会尽力的！

**Comment by fish-ball** [comment]
另外，司徒，我发现你新出来的版本貌似在 bower 和 npm 上面都还没有发布，而且 avalon2 里面那个 package.json 还是建议删掉为好吧。
