### ISSUE TITLE
1.5.2 创建组件 $template 内容里ms-duplex不存在的值时，导致无限报错

### ISSUE THREAD

**Issue by 554943871** [RubyLouvre/avalon#1081]
```
define(["avalon","text!./date.html","ui/vip/main"],function(avalon,tpl){
    console.log(tpl)
    avalon.component("vip:date", {
        $replace:true,
        $ready: function () {
        },
        $template:tpl
    })
    return avalon
})
```
其中tpl对应的是
`<div class="input-append date form_datetime">
    <input size="16" type="text" value="" readonly ms-duplex="el.beginTime">
    <span class="add-on"><i class="icon-th"></i></span>
</div>`

--------------
el.beginTime并不存在

则会在avalon源码里48行发生
function log() {
    if (window.console && avalon.config.debug) {
        // http://stackoverflow.com/questions/8785624/how-to-safely-wrap-console-log
        Function.apply.call(console.log, console, arguments)//这里不停报错
    }
}

**Comment by 554943871** [comment]
是chrome下

**Comment by 554943871** [comment]
$template里对应的内容是

`<div class="input-append date form_datetime">
    <input size="16" type="text" value="" readonly ms-duplex="el.beginTime">
    <span class="add-on"><i class="icon-th"></i></span>
</div>`

**Comment by RubyLouvre** [comment]
不存在当然报错

**Comment by 554943871** [comment]
问题是，他是死循环的方式在报错一直执行
Function.apply.call(console.log, console, arguments) 根本停不下来，代码不断的执行这一行
这个很不友好吧
