### ISSUE TITLE
IE 下组建构建问题，使用dialog时发现，无法toggle，报错avalon.vmodels[id]不是对象

### ISSUE THREAD

**Issue by 77660331** [RubyLouvre/avalon#1085]
```
&lt;!--用户登录对话框--&gt;<br />
&lt;div ms-controller=&quot;systemUser&quot;  &gt;<br />
&lt;oni:dialog  identifier=&quot;loginView&quot; config=&quot;$loginViewOpts&quot;&gt;<br />
&lt;div ms-include-src=&quot;loginViewUrl&quot; data-include-rendered=&quot;$getUser&quot; &gt;&lt;/div&gt;<br />
&lt;/oni:dialog&gt;<br />
&lt;/div&gt;
```
经测试，IE下发现组建无法构建 ,chrome下正常，以下是avalon.js 1.5.3版本 3398行代码

avalon.components = {}
avalon.component = function (name, opts) {
    if (opts) {
        avalon.components[name] = avalon.mix({}, componentHooks, opts)
    }
    for (var i = 0, obj; obj = componentQueue[i]; i++) {
		alert(obj) //经过测试(IE6，7，8)无法alert出object,chrome 正常
        if (name === obj.fullName) {

**Comment by 77660331** [comment]
<div ms-controller="systemUser"  >
<oni:dialog  identifier="loginView" config="$loginViewOpts">
<div ms-include-src="loginViewUrl" data-include-rendered="$getUser" ></div>
</oni:dialog>
</div>

**Comment by RubyLouvre** [comment]
看一下你的版本的 isWidget方法是怎么样的？贴上来瞧瞧。有一个版本存在问题

**Comment by 77660331** [comment]
function isWidget(el) { //如果为自定义标签,返回UI库的名字
    if(el.scopeName && el.scopeName !== "HTML" ){
        return el.scopeName
    }
    var fullName = el.nodeName.toLowerCase() 
    var index = fullName.indexOf(":")
    if (index > 0) {
        return fullName.slice(0, index)
    }
}

**Comment by 77660331** [comment]
换成以下这个，问题依旧：

function isWidget(el) { //如果为自定义标签,返回UI库的名字
    var fullName = el.localName|| el.scopeName
    var index = fullName && fullName.indexOf(":")
    if (index > 0) {
        return fullName.slice(0, index)
    }
}

systemUser.$watch("SessionTimeOut",function(newValue,oldValue){
		
		try{
		avalon.vmodels["loginView"].toggle = true
		}
		catch(e)
		{
			alert(e.message) //这里弹出"avalon.vmodels.loginView 为空或不是对象"
		}
				
		})

**Comment by 77660331** [comment]
isWidget方法 应该是没问题的

两个问题：一个是scanNodeArray方法在IE下要要改一下3195行：

var widget = elem.localName ? elem.localName.replace(library + ":", "") : elem.nodeName

改为：var widget = elem.nodeName.toLowerCase().replace(library + ":", "")

进入avalon.component方法后3461行

if (vmodel.$$template) {
                    avalon.clearHTML(elem)
                    elem.innerHTML = vmodel.$$template(keepTemplate) //这里会抛错
                }

暂时没找到解决方法，咋改都不行

try{
                if (vmodel.$$template) {
                    avalon.clearHTML(elem)
					//var div = document.createElement('div');
					//div.innerHTML = vmodel.$$template(keepTemplate)
					//elem.appendChild(div); 这里会弹出意外的调用的方法或属性
					
                    elem.innerHTML = vmodel.$$template(keepTemplate) //这个是avalon原来的
					
                }
				}
				catch(e)
				{
					alert(e.message) //未知的运行时错误
				}

**Comment by RubyLouvre** [comment]
给一个完整的例子上来我调试

**Comment by RubyLouvre** [comment]
elem　是什么元素啊?

**Comment by 77660331** [comment]
oni:dialog

另外，QQ发了离线文件给你

**Comment by RubyLouvre** [comment]
无法打开，苹果。你做一个简单的例子吧

**Comment by 77660331** [comment]
稍等

**Comment by RubyLouvre** [comment]
你必须在所有require之前，执行avalon.libraries("oni",{})

**Comment by RubyLouvre** [comment]
或者说，必须在浏览器解析到你的自定义标签之前，执行avalon.libraries("oni",{});否 则它是认不出这是自定义标签！

**Comment by RubyLouvre** [comment]
我记得我是有写的 http://avalonjs.github.io/#zh/bindings/component.html

如果你的组件是以ms为命名空间的话, 不需要使用avalon.library("ms"), 否则就要像下面这样做
 ```html
<script src="avalon.js"></script>
<script">
avalon.library("oni") //这个东西必须跟挨着avalon库,并且放到head标签中
</script>
```
如果你是使用requirejs加载avalon库, 那你需要在head标签中插入以下脚本
```
<script src="avalon.js"></script>
<script">
if(document.namespaces){
    document.namespaces.add("oni",'http://www.w3.org/1999/xhtml')
}
</script>
```

**Comment by 77660331** [comment]
问题解决，就是没有avalon.library("oni") 引起的，上一个版本也没有，更新了1.5.3才出现状况，问题关闭。谢谢，辛苦
