### ISSUE TITLE
当对象属性为 null 重新绑定的时候出现问题

### ISSUE THREAD

**Issue by fish-ball** [RubyLouvre/avalon#1091]
例如：

```
var vm = avalon.define({
    $id: 'test',
    data: {
        a: null
    }
});

vm.data = {
    a: 1
};
``` 

这个时候，我用的 `avalon.modern.js` 会出错。

在 883 行的 observeObject 定义里面：

```
function observeObject(source, options) {
    // ...
    var oldAccessors = typeof old === "object" ? old.$accessors : nullObject
    // ...
}
```

这句抛了错误，的确不严谨：

第一，对于 `old === null` 的情况，`typeof old` 是等于 `"object"` 的。

这时候显然 old 不会有 `$accessors` 属性。

而且事实上即使 `typeof old === "object"` 也不能保证一定有 `$accessor` 对象。

所以我自己改成：

```
var oldAccessors = (old && old.$accessors || nullObject)
```

这样就好了。

我不会更新源码，请审查一下我这样改行不行，可以的话把这个坑填了免得后人烦恼。

谢谢！

**Comment by RubyLouvre** [comment]
已经修复，thanks
