### ISSUE TITLE
版本1.5.2 input输入值后，过滤器currency和number失效

### ISSUE THREAD

**Issue by xualen** [RubyLouvre/avalon#1093]
<body ms-controller='global'>
		<div>{{cnt|currency('',0)}}</div>
		<div>
			<input type="text" ms-attr-value='cnt' ms-keyup='changeVal'/>
		</div>
	</body>

</html>
<script src="js/avalon.1.52.shim.js"></script>
<script>
	avalon.ready(function(){

		var vm=avalon.define({
			$id:'global',
			cnt:100000,
			changeVal:function(){
				vm.cnt= +this.value;
			}
		});
		avalon.scan();
	})
</script>

**Comment by RubyLouvre** [comment]
请上传完整的例子，你也可以使用avalon.config({async:false})简单处理
