### ISSUE TITLE
正美老师博客的一个教程案例似乎遇到了BUG

### ISSUE THREAD

**Issue by sikaco** [RubyLouvre/avalon#1095]
http://www.cnblogs.com/rubylouvre/p/3181291.html#top1
```
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>data-duplex-changed</title>
        <script src="avalon.js"></script>
    </head>
    <body ms-controller="duplex">
        <input ms-duplex="username" data-duplex-changed="callback">
        <script type="text/javascript">
            avalon.define({
                $id: "duplex",
                username : "司徒正美",
                callback : function(val){
                    avalon.log(val)
                    avalon.log(this)
                    return this.value = val.slice(0, 10)//不能超过10个字符串
                }
            });
 
        </script>
 
    </body>
</html>
```
这段代码运行后，按道理那个input框的value始终保持10位以内，然而实际并不是这样。
<img width="181" alt="2015-10-09 7 06 04" src="https://cloud.githubusercontent.com/assets/5554734/10392421/84a95d6a-6eb9-11e5-93ab-bf57f966582b.png">

这里输入10位字符后，如果连按某一个字符，比如“1”，就会发现会以三次中出现一次的频率出现第11位字符。为了更加明确我把callback部分的代码改成如下：
 callback : function(val){
            val = val.slice(0, 10);
            avalon.log(val);
            return this.value = val;//不能超过10个字符串
        }
<img width="214" alt="2015-10-09 7 11 31" src="https://cloud.githubusercontent.com/assets/5554734/10392429/965074e0-6eb9-11e5-8bae-612d801461ec.png">
然后input框的情况还是如上的。
这个算是Bug么，如果是，该如何解决呢？

版本为当前最新：avalon.mobile.js 1.46 built in 2015.10.3
浏览器也为chrome最新版：45.0.2454.101

**Comment by sikaco** [comment]
http://www.cnblogs.com/rubylouvre/p/3181291.html#top1

<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>data-duplex-changed</title>
        <script src="avalon.js"></script>
    </head>
    <body ms-controller="duplex">
        <input ms-duplex="username" data-duplex-changed="callback">
        <script type="text/javascript">
            avalon.define({
                $id: "duplex",
                username : "司徒正美",
                callback : function(val){
                    avalon.log(val)
                    avalon.log(this)
                    return this.value = val.slice(0, 10)//不能超过10个字符串
                }
            });
 
        </script>
 
    </body>
</html>

这段代码运行后，按道理那个input框的value始终保持10位以内，然而实际并不是这样。
<img width="181" alt="2015-10-09 7 06 04" src="https://cloud.githubusercontent.com/assets/5554734/10392421/84a95d6a-6eb9-11e5-93ab-bf57f966582b.png">

这里输入10位字符后，如果连按某一个字符，比如“1”，就会发现会以三次中出现一次的频率出现第11位字符。为了更加明确我把callback部分的代码改成如下：
 callback : function(val){
            val = val.slice(0, 10);
            avalon.log(val);
            return this.value = val;//不能超过10个字符串
        }
<img width="214" alt="2015-10-09 7 11 31" src="https://cloud.githubusercontent.com/assets/5554734/10392429/965074e0-6eb9-11e5-8bae-612d801461ec.png">
然后input框的情况还是如上的。
这个算是Bug么，如果是，该如何解决呢？

版本为当前最新：avalon.mobile.js 1.46 built in 2015.10.3
浏览器也为chrome最新版：45.0.2454.101

**Comment by sikaco** [comment]
<img width="832" alt="2015-10-09 7 15 51" src="https://cloud.githubusercontent.com/assets/5554734/10392494/2e7f9ade-6eba-11e5-9a98-fb4a622c4cdb.png">
不知道为什么，粘贴到github上内容就变成空了。这下截图

**Comment by RubyLouvre** [comment]
avalon.config({async:false})

**Comment by sikaco** [comment]
这行代码加到哪个位置呢？我加在开头或者临近script之前都没有效果

**Comment by sikaco** [comment]
位置应该没有错误，我同样加到config里的debut:false就起作用了。

**Comment by RubyLouvre** [comment]
已经 修复，不使用加avalon.config({async:false})了

**Comment by sikaco** [comment]
已下载github上新版avalon，弱弱地说一句，还是老样子。

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>data-duplex-changed</title>
    <script src="vendor/avalon/avalon.modern.js"></script>
</head>
<body ms-controller="duplex">
<input ms-duplex="username" data-duplex-changed="callback">
<script type="text/javascript">

    avalon.define({
        $id: "duplex",
        username : "司徒正美",
        callback : function(val){
            avalon.log(val)
            avalon.log(this)
            return this.value = val.slice(0, 10)//不能超过10个字符串
        }
    });

</script>

</body>
</html>

我马上用录屏软件把过程重现一下

**Comment by RubyLouvre** [comment]
https://github.com/RubyLouvre/avalon/tree/1.5.0

**Comment by sikaco** [comment]
代码还是在github显示不出来，我截图如下：
<img width="751" alt="2015-10-10 4 56 45" src="https://cloud.githubusercontent.com/assets/5554734/10410289/f599b2b6-6f6f-11e5-993b-d146d0e63e1b.png">

**Comment by RubyLouvre** [comment]
https://github.com/RubyLouvre/avalon/blob/1.5.0/avalon.js

**Comment by RubyLouvre** [comment]
试这个

**Comment by sikaco** [comment]
![default](https://cloud.githubusercontent.com/assets/5554734/10410339/86e2d56c-6f71-11e5-8add-071217892c9a.gif)

我看到刚才您的修复了。然后又去试了一下。还是这个样子。

**Comment by sikaco** [comment]
我描述一下bug，当输入到第10位后，再继续输一个字符，以常规速度点按，然后就会发现以30%~50%的频率出现此gif中出现的情况。

**Comment by RubyLouvre** [comment]
我试过是好的啊

**Comment by sikaco** [comment]
纳里。。
恩，我再换浏览器试了一下，发现Mac版Safari没有问题，然后Mac版和windows的Chrome都有这个问题，IE11也有这个问题

**Comment by RubyLouvre** [comment]
那就加avalon.config({async: false})
因为1.5改成异步的，吃掉最后一个字符不太及时

**Comment by sikaco** [comment]
问题依旧

**Comment by sikaco** [comment]
感觉这个bug有可能是一个疑难杂症的样子，可能有可能是错在一些不引人注意的底层的坑上，会比较费时间去排查。我这下主要是学习，项目上暂时遇到这个问题就用其他方法规避了。如果正美老师时间有限的话可以先不用管这个bug

**Comment by RubyLouvre** [comment]
我周一再找时间看看
