### ISSUE TITLE
关于select Option 使用ms-repeat 无法得到change 后的值

### ISSUE THREAD

**Issue by 77660331** [RubyLouvre/avalon#1097]
&lt;select name=&quot;select&quot; size=&quot;1&quot; id=&quot;select&quot; style=&quot;width:100px&quot; ms-duplex=&quot;Data.columns&quot; data-duplex-changed=&quot;$setarticleColumn&quot;&gt;<br />
  &lt;option  style=&quot; line-height:20px&quot;&gt;&lt;/option&gt;<br />
  &lt;option  ms-repeat-list=&quot;list&quot; value=&quot;{{list.Id}}&quot; style=&quot; line-height:20px&quot;&gt;{{list.columnName}}&lt;/option&gt;<br />
  &lt;/select&gt;</p>
<p>$setarticleColumn:function(s){console.log(s)}//这里输出的是 {{list.Id}}

**Comment by RubyLouvre** [comment]
value="{{list.Id}}" 这里错了，应该使用ms-attr-value
