### ISSUE TITLE
请问data-duplex-focus="true" avalon1.4.7 不自动聚焦

### ISSUE THREAD

**Issue by lee134134134** [RubyLouvre/avalon#1101]
请问data-duplex-focus="true" avalon1.4.7 不自动聚焦  我哪里错了

 <input ms-duplex="o" ms-data-duplex-observe="true" data-duplex-focus="true"/>{{o}}

**Comment by RubyLouvre** [comment]
已经被废掉了！使用autofocus属性，不支持就自己操作DOM。这东西始终搞不定，还引入了BGU
