### ISSUE TITLE
手机版触屏事件最新版本：warning: vm必须指定$id

### ISSUE THREAD

**Issue by flyingliu** [RubyLouvre/avalon#1114]
手机版触屏事件最新版本1.5.3操作实例时有报错。
http://avalonjs.github.io/zh/mobiles/touch-iframe.html

warning: vm必须指定$id

用回老版本就可以了。新版本触屏事件怎么写？

**Comment by RubyLouvre** [comment]
因为那个页面是用旧风格写的，改成新风格就好。avalon.define({$id: 'xxx' })这样的形式
