### ISSUE TITLE
建议定义一个avalon全局的broadcast方法

### ISSUE THREAD

**Issue by 77660331** [RubyLouvre/avalon#1122]
目前broadcast还要重新定义一个vm ,或者定义顶层VM，再调用其$fire

比较麻烦，例如，某个模块出发登录超时后，直接avalon.broadcast通知需要做出响应的其他模块

**Comment by RubyLouvre** [comment]
什么版本？

**Comment by RubyLouvre** [comment]
http://avalonjs.github.io/#zh/concepts/$fire.html

**Comment by lkiarest** [comment]
我自己写的全局的事件订阅、发布。。没用avalon的vm~~
