### ISSUE TITLE
avalon 1.5.4代码的4020行出错

### ISSUE THREAD

**Issue by liminghui** [RubyLouvre/avalon#1123]
原代码为以下，element not define
<pre>
elem.value = this.oldValue = curValue
if (fixCaret) {
    setCaret(element, pos, pos)
}
</pre>

应该改为
<pre>
elem.value = this.oldValue = curValue
if (fixCaret) {
    setCaret(elem, pos, pos)
}
</pre>

**Comment by RubyLouvre** [comment]
https://github.com/RubyLouvre/avalon/tree/master/dist

**Comment by RubyLouvre** [comment]
已经修了4天了
