### ISSUE TITLE
directive建议开放插值参数

### ISSUE THREAD

**Issue by xiarugu** [RubyLouvre/avalon#1124]
如果自定义directive的expr希望使用avalon的{{}}插值, 目前似乎比较困难, 
希望directive定义中能够开放一个参数, 用来指定自定义的directive是否需要启用插值

**Comment by RubyLouvre** [comment]
这个是自己写的，具体参考 https://github.com/RubyLouvre/avalon2/blob/master/src/19%20directive/effect.js

**Comment by xiarugu** [comment]
问题就是stringifyExpr这个函数很复杂, 又没有对外开放
如果把stringifyExpr这个函数公开到avalon.stringifyExpr 倒是也方便了许多

**Comment by RubyLouvre** [comment]
我下个版本公开出来

**Comment by RubyLouvre** [comment]
改好了，公开normalizeExpr
