### ISSUE TITLE
关于1.4.7修复ie低版本下光标的问题

### ISSUE THREAD

**Issue by wttyzy** [RubyLouvre/avalon#1125]
#1106 和#673 在1.4.7中修复了，但发现还是有些问题，描述如下：

&lt;html&gt;&lt;head&gt;&lt;scrpit src="avalon.js"&gt;&lt;/script&gt;&lt;/head&gt;
&lt;body ms-controller="test"&gt;&lt;input type="text"  ms-duplex-string="remarks"/&gt;{{remarks}}
&lt;script&gt;avalon.define({$id:"test", remarks:"1234567890"});&lt;/script&gt;
&lt;/body&gt;&lt;html&gt;

页面input当删除5的时候，会出现6-0被选中的情况。也就是说，当删除最后的字符时没什么问题，但当删除中间的字符时，会出现被选中的情况。
看了下源码，setCaret方法中，建议把3998行：range.moveEnd("character",end)这行删除，正美看下是否可行

注：例子测试环境是ie8

**Comment by RubyLouvre** [comment]
果然
