### ISSUE TITLE
关于ms-duplex绑定的问题，不知道是不是我写的方式有问题导致不能同步

### ISSUE THREAD

**Issue by liminghui** [RubyLouvre/avalon#1126]
<!DOCTYPE html>
	<html>
	    <head>
	        <meta charset="UTF-8">
	        <meta name="viewport" content="width=device-width, initial-scale=1.0">
	        <script src="avalon.js"></script>
	        <script>
	        
	            var vm = avalon.define({
	                $id: "test",
	                norValue:{
	                    name:"123"
	                },
	                oldValue:{
	                    name:"fff"
	                },
	                norValueClick:function(){
	                    vm.norValue.name = "wwwww";
	                },
	                oldValueClick:function(){
	                    var old = avalon.mix(vm.oldValue,{},true);
	                    vm.norValue = old;
	                }
	            })
	            
	        </script>
	    </head>
	    <body ms-controller="test">
	        <input type="text" ms-duplex="norValue.name" />
	        
	
	        <button type="button" ms-click="norValueClick">norValueBtn</button>
	        <button type="button" ms-click="oldValueClick">oldValuebtn</button>
	    </body>
	</html>

如上面的demo，如果我先点击了<code>oldValuebtn</code>，再点击<code>norValueBtn</code>，就不能重新同步了，不知道是不是我写的方式有问题，还望司徒大大教教

**Comment by RubyLouvre** [comment]
```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="avalon.js"></script>
        <script>

            var vm = avalon.define({
                $id: "test",
                norValue:{
                    name:"123"
                },
                oldValue:{
                    name:"fff"
                },
                norValueClick:function(){
                    vm.norValue.name = "wwwww";
                },
                oldValueClick:function(){
                    var old = avalon.mix(true, {}, vm.oldValue)
                   // var old = avalon.mix(vm.oldValue,{},true);
                    vm.norValue = old;
                }
            })

        </script>
    </head>
    <body ms-controller="test">
        <input type="text" ms-duplex="norValue.name" />


        <button type="button" ms-click="norValueClick">norValueBtn</button>
        <button type="button" ms-click="oldValueClick">oldValuebtn</button>
    </body>
</html>
```
方法都用错了，不会调试吗！
avalon.mix与jQuery.extend的传参是一致的
