### ISSUE TITLE
想问一问 ms-duplex和 ms-attr 区别

### ISSUE THREAD

**Issue by myseemylife** [RubyLouvre/avalon#1127]
ms-attr怎么使用可以达到ms-duplex的效果。对于表单中的input标签可以直接替换吗？

**Comment by RubyLouvre** [comment]
ms-attr是单向，不能监听用户行为，只能将VM中的数据放到对应属性 上；而ms-duplex是双向的，只能绑在表单元素上，并且为元素添加各种事件，能监听用户行为，只要是修改元素的value 值与checked, selected属性
