### ISSUE TITLE
1.5.3版本如何使用validation组件？

### ISSUE THREAD

**Issue by bzksx2** [RubyLouvre/avalon#1128]
在oniui上看教程，按其验证了下，无法生效，不知道是不是节点绑定需要作调整呢？因为在线事例用的还是1.46版本的，从1.5.1已经废弃掉了ms-widget，事例中  form ms-controller="test" ms-widget="validation" 是否要调整？

**Comment by RubyLouvre** [comment]
https://github.com/RubyLouvre/avalon2/tree/master/component

**Comment by RubyLouvre** [comment]
这里有

**Comment by xiarugu** [comment]
看了http://avalonjs.github.io/以及司徒上面提供的例子, 没有找到如何在component中进行简单的双工绑定
(注:配置方式, 非回调方式)

例如, 个人比较常用的需要component组件的地方是各种输入扩展
```
<ms:date ms-duplex="abc"></ms:date>

avalon.define({$id:'xxx',
abc: null
});
```
希望在component构建函数中可以获得传入的abc参数, 并且可以在component中对abc进行赋值(更新模型值)

**Comment by RubyLouvre** [comment]
你这个应该在config对象中设置

**Comment by xiarugu** [comment]
在config中通过回调固然可以实现, 不过框架存在的意义不正是write less, do more么.
如果使用者只想要简单的进行一个双工绑定, 却不得不为想要duplex的变量单独包装一个config对象, 感觉有点本木倒置了.

component存在的意义是扩展html的原生组件, 所以对视图模型以及调用者来说, 对component的使用应该和使用div, input这些原生组件一样简单直观. 如果因为html视图中使用了component而不得不改变视图模型的结构, 这样就产生了反向依赖.

例如vm中有一个vm.date变量 表示订单日期的, 那么不管视图中是用input直接呈现, 还是用某种component来展示、修改这个vm.date, 对于视图模型来说应该是透明的, 如果因为视图的变化而逼迫vm修改数据结构, 不是正违背了司徒当初创建avalon的初衷么.

试想, 负责html的同事写了一个调用日历组件A的html, 然后告诉写vm脚本的同事说, 你得修改vm的结构, date变量得封装在另外一个对象里.  然后过了几天, html的同事又发现了一个更好看的日历组件B, 而B组件对config的结构要求和A组件不一样, 这时候, 他又得告诉写js的同事再次修改date的封装config对象.

而实际上, 对于业务本身来说, vm.date 就是一个日期变量, 不管视图决定如果去展示、修改这个变量, 都不应该要求vm修改自己的结构啊.

**Comment by Lihuanghe** [comment]
就是因为组件接口不统一啊. ms-duplex光是为了统一不同浏览器原生组件的接口就费了多少事.你还想再一统一第三方的组件? 
光一个日期组件就有数不清第三方组件.你指望都统一成ms-duples一个接口? 也不是不可以, 给ms-duplex留个定制的口子,让业务自已实现与第三方组件的对接. 这样框架界面上是清晰了,不过通用性太差,业务侧还不如直接改个vm来的方便.

**Comment by xiarugu** [comment]
我还是坚持vm只持有数据, 不应该因为视图而变更.
输入类的组件任务就是展示、输入数据，如果一个组件需要除value输出值以外的信息, 那是组件配置自身的需求, 不应该要求vm变化.

设想一下, html自带的select本身就可以看成是一个组件.
为什么当初没有为select设定一个config, 把option列表和输出的value值给打包进去?

道理是一样的

**Comment by xiarugu** [comment]
组件本就应该是高内聚的, 组件的实现再复杂, 也不应该把这个工作转嫁给组件的使用者.

**Comment by RubyLouvre** [comment]
```
<ms:date><input ms-duplex="abc"></ms:date>
```
这样不行吗。我的新 BS组件就是这样

**Comment by xiarugu** [comment]
这样等于是吧内部结构暴露给调用者了, 如果以后组件升级不用input了呢
我之前有一个自定义的组件, 为了融合到avalon中, 是在内部放了一个隐藏的input:hidden, 通过对这个input:hidden进行赋值来进行双工绑定, 但是这是一种没有官方支持情况下的hacker方法.

**Comment by xiarugu** [comment]
最好的方式应该是ms-duplex直接就支持对component的双工
可以在component接口中提供两个特殊的接口, 一个update方法来修改value, 一个onChange事件来通知组件外部对value的赋值行为
```
avalon.component('ms:date', {
	$init: function(vm) {
		var value = vm.value;	//获取通过ms-duplex绑定的变量的值


		//do something
		value = 'new value';
		vm.$update(value);	//更新ms-duplex上绑定的外部视图模型的expr变量值
    }
});
```

**Comment by RubyLouvre** [comment]
现在的想法是这样的，<ms:xxx></ms:xxx>里面还是有HTML标签，自定义标签只是告诉这里需要生成一些标签或提供某些额外功能。

**Comment by RubyLouvre** [comment]
@xiarugu 

可以看一下这个如何处理duplex.  这个是非常好的范本
https://github.com/RubyLouvre/avalon.bootstrap/blob/master/js/flipswitch/flipswitch.js
