### ISSUE TITLE
在chrome下对<input type="number"双工绑定时，会提示无法读取selectionStart

### ISSUE THREAD

**Issue by coudly** [RubyLouvre/avalon#1129]
**描述：**
使用 `type="number"`的 `input`进行双工绑定时，在chrome下，会提示无法读取`selectionStart`。
`type="date'` 也有类似的问题

----
**报错代码：**
https://github.com/RubyLouvre/avalon/blob/1.5.4/dist/avalon.modern.js#L3345

**console信息：**
`warning:exception throwed in [avalon.injectBinding]  DOMException: Failed to read the 'selectionStart' property from 'HTMLInputElement': The input element's type ('number') does not support selection.(…)`

----
**环境：**
Google Chrome	45.0.2454.15 (正式版本) （32 位）
修订版本	3a1ba3bad4f392b9c08d4c20db31560fb377558d-refs/branch-heads/2454@{#102}
操作系统	Windows 6.1 SP1 企业版 7601
Blink	537.36 (@199335)
JavaScript	V8 4.5.103.11
Flash	18.0.0.209
avalon: 1.5.4

----
**示例代码**

https://jsfiddle.net/z9x1ovq7/3/

```html
<div ms-controller="demo">
<input ms-duplex-number="count" type="number" step="1" class="form-control" placeholder="请输入数量">
</div>
```

```js
avalon.define({
    $id: 'demo',
    count: 0
})
```

**相关avalon代码**
``` js
        switch (this.xtype) {
            case "input":
            case "change":
                curValue = this.pipe(value, this, "set")  //fix #673
                if (curValue !== this.oldValue) {
                    var fixCaret = false
                    if (elem.msFocus) {
                        var start = elem.selectionStart //出错，建议判断下 type=='number'特殊处理
                        var end = elem.selectionEnd
                        if (start === end) {
                            var pos = start
                            fixCaret = true
                        }
                    }
                    elem.value = this.oldValue = curValue
                    if (fixCaret) {
                        elem.selectionStart = elem.selectionEnd = pos
                    }
                }
                break
```

同类型的问题参考
http://stackoverflow.com/questions/21177489/selectionstart-selectionend-on-input-type-number-no-longer-allowed-in-chrome

**Comment by RubyLouvre** [comment]
收到，谢谢
