### ISSUE TITLE
页面2次加载后，绑定失效。

### ISSUE THREAD

**Issue by doocal** [RubyLouvre/avalon#1133]
1、a.html 页面 ajax 加载 b.html 绑定正常，再加载一次 b.html  绑定就失效了（只能绑定最后一次的值）。

可能描述的不是很清楚，下面是个小DEMO。一看就知道。

http://218.22.44.188/demo/

**Comment by RubyLouvre** [comment]
真是吐血，你不就能写一个setTimeout代替ajax吗

**Comment by doocal** [comment]
实现场景是AJAX加载的呀，例子只是表态效果。。。。

**Comment by RubyLouvre** [comment]
```
ajax = function(done){
  setTimeout(function(){
    done("我是字符串模板")
  })
}
```

**Comment by RubyLouvre** [comment]
我还要翻看你的源码，截你的AJAX请求!

**Comment by doocal** [comment]
OK懂了，我知道下次提问题的方式了，现已对DEMO(地址还可以访问)做了调整  。

代码如下：
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>DEMO</title>
</head>

<body>
<script src="http://cdn.bootcss.com/jquery/1.11.3/jquery.js"></script>
<script src="avalon.js"></script>
<table border="1">
  <tbody>
    <tr>
      <td><p>
      1、延时1秒加载。</br>
      2、点击“菜单1”，再点“子菜单1”，无法重新绑定新值。</p>
      <p>初次加载后直接点“子菜单1”，绑定值是正常的。</p></td>
    </tr>
    <tr>
      <td><a href="javascript:void(0)" onClick="ajax()">菜单1</a></td>
    </tr>
  </tbody>
</table>
<table border="1">
  <tbody>
    <tr>
      <td height="111" id="content">
      
      	<table width="233" border="1">
          <tbody>
            <tr>
              <td width="57"><a href="javascript:void(0)" onClick="ajax_sub()">子菜单1</a></td>
            </tr>
          </tbody>
        </table>
        <form id="form1" name="form1" method="post" ms-controller="avalon_demo1">
          <label for="textfield">Text Field:</label>
          <input type="text" name="textfield" id="textfield" ms-duplex="email">
          <label for="textfield">Text Field:</label>
          <input type="text" name="textfield" id="textfield" ms-duplex="textarea">
        </form>
      
      </td>
    </tr>
  </tbody>
</table>
<script>
//页面变量
var cur = {}

//默认数据
var data = {
	$id:"avalon_demo1",
	"email":"我是初始值email",
	"textarea":"我是初始值textarea",
}

function ajax(){
			
	setTimeout(function(){
		//如果模型已经绑定，不再绑定
		if(!avalon.vmodels[data.$id]){
			//绑定模型
			cur.model = avalon.define(data);
			avalon.scan();
		}										
	},1000)

}

function assignVM(vm, firstSource) {
  for (var i = 1; i < arguments.length; i++) {
    var nextSource = arguments[i];
    if (nextSource && typeof nextSource !== "object") continue;
    for (var i in vm) {
      if (vm.hasOwnProperty(i) && nextSource.hasOwnProperty(i)) {
        vm[i] = nextSource[i]
      }
    }
  }
  return vm
}

//子菜单1的点击事件
function ajax_sub(){
	var data_ = {
		"email":"新值email"+Math.random(),
		"textarea":"新值textarea"+Math.random(),
	}
	assignVM(cur.model,data_);
	avalon.scan();
}

$(document).ready(function(e) {
  ajax()
});

</script>
</body>
</html>

**Comment by RubyLouvre** [comment]
其实这不是avalon的问题，纯粹是变量被你冲掉的原因。你的cur是定义在b页面上，而每次加载b.html，都会将cur整个冲掉，并把它上面的VM冲掉。

**Comment by RubyLouvre** [comment]
```html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <title>DEMO</title>
    </head>

    <body>
        <script src="http://cdn.bootcss.com/jquery/1.11.3/jquery.js"></script>
        <script src="avalon.js"></script>
        <table border="1">
            <tbody>
                <tr>
                    <td><p>1、点击“菜单1”，再点“子菜单1”，无法重新绑定新值。</p>
                        <p>初次加载后直接点“子菜单2”，绑定值是正常的。</p></td>
                </tr>
                <tr>
                    <td><a href="javascript:void(0)" onClick="ajax()">菜单1</a></td>
                </tr>
            </tbody>
        </table>
        <table border="1">
            <tbody>
                <tr>
                    <td height="111" id="content">

                    </td>
                </tr>
            </tbody>
        </table>
        <!--BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB 开始-->

        <textarea style="display: none" id="ajaxData">
    <table width="233" border="1">
  <tbody>
    <tr>
      <td width="57"><a href="javascript:void(0)" onClick="ajax_sub()">子菜单1</a></td>
    </tr>
  </tbody>
</table>
<p>这是动态添加的内容</p>
<form id="form1" name="form1" method="post" ms-controller="test">
  <label for="textfield">Text Field:</label>
  <input type="text" name="textfield" id="textfield" ms-duplex="email">
  <label for="textfield">Text Field:</label>
  <input type="text" name="textfield" id="textfield" ms-duplex="textarea">
</form>
<script>
    //页面变量

    //如果模型已经绑定，不再绑定

    function ajax_sub() {

        var data_ = {
            "email": "新值email" + Math.random(),
            "textarea": "新值textarea" + Math.random()
        }
        var vm = avalon.vmodels.test
        if (vm) {
            assignVM(vm, data_)
        }
    }



       </script>
        </textarea>
        <!--BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB 结果-->
        <script>
            //这是A页面的

            var data = {
                $id: "test",
                "email": "我是初始值email",
                "textarea": "我是初始值textarea",
            }

            if (!avalon.vmodels["test"]) {
                //绑定模型
                console.log("-----初始化")
                var vm = avalon.define(data);
                avalon.scan(document.body, vm);
            }


            function ajax() {//一个伪装的ajax
                setTimeout(function () {
                    var d = document.getElementById("ajaxData").value
                   
                    $("#content").html(d)
                    var vm = avalon.vmodels["test"]
                    if (vm) {
                        //绑定模型
                        console.log("==========AJAX")
                        avalon.scan(document.body, vm);
                    }
                })

            }

            function assignVM(vm, firstSource) {
                for (var i = 1; i < arguments.length; i++) {
                    var nextSource = arguments[i];
                    if (nextSource && typeof nextSource !== "object")
                        continue;
                    for (var i in vm) {
                        if (vm.hasOwnProperty(i) && nextSource.hasOwnProperty(i)) {
                            vm[i] = nextSource[i]
                        }
                    }
                }
                return vm
            }

            $(document).ready(function (e) {
                ajax()
            });

        </script>
    </body>
</html>
````
