### ISSUE TITLE
获取绑定数据过滤的问题。

### ISSUE THREAD

**Issue by doocal** [RubyLouvre/avalon#1134]
var data = {
      $id : "avalon_demo1",
      email : "我是初始化值",
      $alert: function () {
        alert('abcd')
      }
    }

var value = cur.model.$model;

后台要接收JSON对象。

1、直接取 value 用 $.ajax({data:value }) 提交的时候会打印出 alert 窗口。
2、这样取的是一个字符串：JSON.stringify(value)。
3、现在只能 JSON.parse(JSON.stringify(value)) 获取JSON对象，但是显得好蛋疼，每次都要这样转。。。。。

可有更好的办法，拿到比较纯一点(如事件很明显不需要)JSON对象提交到后台。

**Comment by RubyLouvre** [comment]
自己封装一个方法吧
