### ISSUE TITLE
新版的avalon定义组件命名上挺奇怪的

### ISSUE THREAD

**Issue by codering** [RubyLouvre/avalon#1135]
必须要一个namespace, 目前还没看到其他js框架有这样做的，也不满足web components的命名规则。
现在组件定义都往web components上靠拢，假设以后web components成为标准，avalon这套命名方式完全没法迁移， 是吗？

**Comment by RubyLouvre** [comment]
不会啊

**Comment by RubyLouvre** [comment]
这是为了兼容IE6－8，并且web components只是用了一个叫document.registerElement为它添加4个回调

**Comment by RubyLouvre** [comment]
https://github.com/RubyLouvre/avalon.bootstrap/tree/master/js

可以看一下这里
