### ISSUE TITLE
初化后绑定方法无效。

### ISSUE THREAD

**Issue by doocal** [RubyLouvre/avalon#1136]
var data ={
$id:""
}
vm = avalon.define(data);

初始化个空的vm，后面怎么绑定一个新的方法（更新数据用官方的　assignVM　可以，但是方法不行）。

vm.ttttt = function(){
alert('后绑的方法。')
}

**Comment by RubyLouvre** [comment]
不能，必须先定义。入门教材也说了，先定义后使用。http://www.cnblogs.com/rubylouvre/p/4783966.html

**Comment by RubyLouvre** [comment]
但可以这样
```
var vm = avalon.define({id: "test",data: {}})

vm.data = {a:1, b: function(){}} //这里必须用 =

```

**Comment by doocal** [comment]
<button type="button" class="btn default" ms-click="data.b">重 置</button>

不行这样会报错的。

Uncaught TypeError: Cannot read property 'call' of undefined

**Comment by RubyLouvre** [comment]
方法就放在外面吧

**Comment by RubyLouvre** [comment]
试了，是好的;你在未重写data对象之前当然是undefined
