### ISSUE TITLE
avalon 加载器影响其它JS组件，怎么解决比较好？

### ISSUE THREAD

**Issue by doocal** [RubyLouvre/avalon#1144]
如题 avalon.js 引用后，其它JS组件里面判断加载器的代码全生效了，导致正常的引用失效。

要自己删除 avalon 里面的代码？

已知影响组件（layer 弹窗， ueditor 里面的（ZeroClipboard.js））

如下面的判断全部有问题了。。。。。
```
if (typeof define === "function" && define.amd) {
   define(function() {
     return ZeroClipboard;
    });
  } else if (typeof module === "object" && module && typeof module.exports === "object" && module.exports) {
    module.exports = ZeroClipboard;
  } else {
    window.ZeroClipboard = ZeroClipboard;
 }
```

**Comment by RubyLouvre** [comment]
看入门教程，使用AMD方式引入它们 http://avalonjs.github.io/#zh/engineering/jquery.html http://avalonjs.github.io/#zh/engineering/loader.html

**Comment by doocal** [comment]
不想使用AMD来引用，最好有个版本可以直接用且不影响。

**Comment by IndexXuan** [comment]
@doocal 有shim版本的avalon啊，不带amd加载器

**Comment by RubyLouvre** [comment]
必须要打包啊，要不请求数太多

**Comment by sundyxfan** [comment]
有没有shim版本？不然升级报错
