### ISSUE TITLE
avalon是否存在开发人员力量不足的问题? 

### ISSUE THREAD

**Issue by xiarugu** [RubyLouvre/avalon#1148]
如题
司徒avalon的团队是否存在开发力量/资金缺乏的问题?
项目是否有开放捐助通道? 我觉得一个免费而优秀的开源项目可能需要广大开发人员的捐助来变得更好更强大

**Comment by lazyhero** [comment]
应该不会吧……毕竟手下有团队在用

**Comment by RubyLouvre** [comment]
avalon的UI库至少5，6个……

**Comment by RubyLouvre** [comment]
但对于核心库的技术支持与宣传却不充足
