### ISSUE TITLE
关于 oniUI  tree组件的的问题

### ISSUE THREAD

**Issue by z893495246** [RubyLouvre/avalon#1149]
这是我的代码：
----------------------------------------------
define(['avalon', 'text!./departmentList.html'], function (avalon, tpl) {
    return function () {
        avalon.templateCache.departmentListTpl = tpl;
        var vm = avalon.define({
            $id: "departmentListVM",
            tree:{},
            $treeOpt:{},
            det:{},
            $skipArray:{},
            items: [],
            dom:null,
            dept_parent:null,
            dept_name:null,
            dept_no:"",
            dept_id:"",
            moban:null,
            SuperiorName:"",
            add_dept_name:"",
            recommend:[],
            itemsDealing: [],
            itemsDealingCount: -1, // 代表未加载
            itemsSuccess: [],
            itemsSuccessCount: -1,
            itemsFail: [],
            itemsFailCount: -1,
            curTabIndex: 0, // 处理状态
            curStatus:0,
            loading:false,// 是否已加载完
            $gridOpt:{
                onInit: function(){
                    avalon.log("--init---")
                }},
            pageable:false,
            autoResize: false,
            $pageSize:2,
            pageCount:10,
            $pageNo:1,
            $pageopt: {
                showJumper: true,
                showPages: 1,
                alwaysShowNext: true,
                perPages: 2,
                alwaysShowPrev: true,
                onJump: function (e, data) {
                    vm.getItems(vm.curStatus);
                }
            },
            child:[],
             
            // 加载itemList数据
            getItems: function (status) {
            	// var pager = avalon.vmodels.taskPager;
                vm.loading=false;
                $.ajax({url:"../dePartment",
                	type:"post",
                    dataType: "json",
                   // data:{},
                    async : false,
                    success: function(data){
                    	
                    	// var dataJSON = JSON.parse(data);
                    	console.log("data:",data);
                    	vm.child=data;
                    	
                    	console.log('JSon:',vm.child.length);
                    	vm.loading = true;
                    },
                    error:function(data,statusText){
                    	console.log('出错了！！！！！！！！！',data.statusText);
                    }
                });

      
            },
            // 保存
            saveClick:function(){
            	if (vm.det.$model.open){
            		vm.det.$model.open=1;
            	}else{
            		vm.det.$model.open=0;
            	}
	            	vm.det.$model.dept_name=vm.dept_name;
	            	vm.det.$model.dept_no=vm.dept_no;
	            	
	            	console.log('进去了');
	            	console.log('部门ID:',vm.dept_parent);
	            	
	            	console.log('部门名称:',vm.dept_name);
            	  vm.loading=true;
                  $.ajax({url:"../dePartment/update",
                  	type:"post",
                    contentType: "application/json",
                    dataType: "json",
                     data:JSON.stringify(vm.det.$model),
                      async : false,
                      success: function(data){
                    	  vm.dom.context.innerText=vm.dept_name;
                    	  console.log('保存成功！',vm.dom.context.innerText);
                      },
                      error:function(data,statusText){
                      	console.log('出错了！！！！！！！！！',data.statusText);
                      }
                  });
            },
            // 新建部门
            newClick:function(){
            	vm.moban=1;
            	if (vm.det.$model.open){
            		vm.det.$model.open=1;
            	}else
            		{
            		vm.det.$model.open=0;
            		}
            	/*for(var i=0;i<vm.child.length;i++){
            		if(vm.dept_parent==vm.child[i].dept_id){
            			console.log('父ID:',vm.child[i].dept_id,vm.child[i].dept_name);
            			vm.SuperiorName = vm.child[i].dept_name;
            			vm.dept_parent =  vm.child[i].dept_id;
            			break;
            		}
            	}*/
            	vm.SuperiorName= vm.dept_name;
            	vm.det.$model.dept_parent = vm.dept_id;
            	
            	console.log('子ID：',vm.det.$model.dept_parent);
            	console.log('名称:',vm.det.$model.dept_name);

           
            },  
            //保存新建
            addSaveClick:function(){
            	vm.det.$model.dept_name = vm.add_dept_name;
            	console.log('添加部门名称:',vm.det.$model.dept_name);
            	$.ajax({url:"../dePartment/save",
                   	type:"post",
                     contentType: "application/json",
                     dataType: "json",
                      data:JSON.stringify(vm.det.$model),
                       async : false,
                       success: function(data){
                    	   console.log('新建成功！');
                       },
                       error:function(data,statusText){
                       	console.log('出错了！！！！！！！！！',data.statusText);
                       }
                   });
            },
            delClick:function(arg){
            	console.log('元素:',arg);
            	$.ajax({url:"../dePartment/del",
                   	type:"post",
                     contentType: "application/json",
                     dataType: "json",
                      data:JSON.stringify(vm.det.$model),
                       async : false,
                       success: function(data){
                    	   $(vm.dom).remove();
                    	   console.log('删除成功！',data);
                       },
                       error:function(data,statusText){
                       	console.log('出错了！！！！！！！！！',data.statusText);
                       }
                   });
            }
            
        });
        vm.tree = {
                children: vm.child,
                edit: {
                    showRemoveBtn: function(leaf) {
                        return leaf.level > 0
                    }
                },
                data: {     
                    simpleData: {
                    	 enable: true,
                         idKey: "dept_id",
                         pIdKey: "dept_parent"
                    },
                    key: {
                        name: "dept_name", 
                    },
                    keep: {
                        leaf: false,
                        parent: true
                    }
                },
                view: {
                    editNameSelectAll: true,
                    showLine: function(leaf) {
                        return true
                        return leaf.level > 1 || 1
                    }
                },
                callback: {
                    onExpand: function(leaf) {
                        console.log(leaf)
                    },
                    beforeRename: function(arg) {
                    	console.log("before编辑")
                    },
                    onNodeCreated: function(arg) {
                    	console.log("onNodeCreated")
                    },
                    onRename: function(arg) {
                    	console.log("编辑")
                    },
                    beforeRemove: function(obj) {
                        return confirm("确认删除?")
                    },
                    beforeAdd: function(obj) {
                        return confirm("确认添加?")
                    },
                    beforeNodeCreated: function(arg) {
                    	
                    	 arg.newLeaf = {
                                 name: "管理员"
                             }

                    	console.log('进来了:',arg);
                    },
                    onNodeCreated: function(arg) {
                        console.log("add")
                    },
                    onClick:function(arg){
                    	vm.dom = $(this).parent().parent();
                    	console.log('获取的元素：',vm.dom.context.innerText);
                    	vm.moban = 0;
                    	vm.det=arg.leaf.$model;
                    	vm.dept_no = arg.leaf.$model.dept_no;
                    	vm.dept_parent = arg.leaf.$model.dept_parent;
                    	vm.dept_id = arg.leaf.$model.dept_id
                    	vm.dept_name = arg.leaf.$model.dept_name;
                    	console.log('部门ID:',arg.leaf.$model.dept_id);
                    	console.log('部门名称:',arg.leaf.$model.dept_name);
                    }
                }
            }
            vm.$treeOpt = {
                children: vm.child
            }
            vm.$skipArray = ["tree"]
        avalon.vmodels.appVM.mainContent = "departmentListTpl";

    }
    avalon.scan()
});
------------------------------------
child:[],   是绑定tree组件的数据的属性
getItem（）是第一次加载数据的方法，也是我要从数据库里获取的数据赋值给child[]
但是呢，现在有一个问题出现了，当我第一次加载这个js的时候，我的tree组件并没有加载数据，这个tree组件没有获取到数据，当我调试以后我发现，加载当前js的时候，第一次并没有去执行getItem这个方法（我在man.js 控制这里处理了一下，当第一次加载“当前”的js时候，会去调用getItem这个方法）。
而是第一次去执行了这段代码: vm.tree = {
                children: vm.child,
                edit: {
                    showRemoveBtn: function(leaf) {
                        return leaf.level > 0
                    }
                },........(最后面这段代码)

所以，现在有个问题，当我第二次加载当前js的时候，tree组件加载了数据，因为第二次调用这个js的时候会执行getItem方法。也就是说，第一次的时候vm.tree并没有得到数据。这该怎么去处理，虽然我知道了问题出在哪，也知道第一次应该给vm.tree数据，但是我并没有好的解决办法，对这个框架还不熟

**Comment by z893495246** [comment]
在线等，很急@司徒正美   大哥帮忙看下

**Comment by z893495246** [comment]
@RubyLouvre 大哥帮忙看下

**Comment by roscoe054** [comment]
你可以在getItem请求到数据之后，直接给tree组件的vm赋值，假如html是这样：
```html
<div ms-widget="tree, mytree, $treeOpt"></div>
```
在数据获取到之后，直接这样赋值：
```javascript
avalon.vmodels.mytree.children = data
```

**Comment by z893495246** [comment]
@roscoe054 你说的这个方法我刚才试了下，第一次是可以加载数据，但是，tree的数据源配置该怎么办呢？如果不配置tree.data的话，这个tree组件就不是正确的加载了。
--------这些tree的配置项该怎么办？如果保留的话，那第一次还是会加载vm.tree，不会加载getItem();

**Comment by roscoe054** [comment]
配置项不用动，只用把配置中的children设为空数组

**Comment by z893495246** [comment]
@roscoe054  这个是我改动之后的代码，简化了一下，只贴了重要的部分
-----------------------------------------------------------------
define(['avalon', 'text!./departmentList.html'], function (avalon, tpl) {
    return function () {
        avalon.templateCache.departmentListTpl = tpl;
        var vm = avalon.define({
            $id: "departmentListVM",
            tree:{},
            $treeOpt:{},
            det:{},
            $skipArray:{},
            items: [],
            dom:null,
            dept_parent:null,
            dept_name:null,
            dept_no:"",
            dept_id:"",
            moban:null,
            SuperiorName:"",
            add_dept_name:"",
            recommend:[],
            loading:false,// 是否已加载完
            child:[],
            // 加载itemList数据
            getItems: function (status) {
            	// var pager = avalon.vmodels.taskPager;
                vm.loading=true;
                $.ajax({url:"../dePartment",
                	type:"post",
                    dataType: "json",
                   // data:{},
                    async : false,
                    success: function(data){
                    	avalon.vmodels.mytree.children = data
                  
                    	vm.child=data;
                    	
                    	console.log('JSon:',vm.child.length);
                    	vm.loading = false;
                    },
                    error:function(data,statusText){
                    	console.log('出错了！！！！！！！！！',data.statusText);
                    }
                });

      
            },
        });
        vm.tree = {
                children: [],
                edit: {
                    showRemoveBtn: function(leaf) {
                        return leaf.level > 0
                    }
                },
                data: {     
                    simpleData: {
                    	 enable: true,
                         idKey: "dept_id",
                         pIdKey: "dept_parent"
                    },
                    key: {
                        name: "dept_name", 
                    },
                    keep: {
                        leaf: false,
                        parent: true
                    }
                },
                view: {
                    editNameSelectAll: true,
                    showLine: function(leaf) {
                        return true
                        return leaf.level > 1 || 1
                    }
                },
                callback: {
                    onExpand: function(leaf) {
                        console.log(leaf)
                    },
                    beforeRename: function(arg) {
                    	console.log("before编辑")
                    },
                    onNodeCreated: function(arg) {
                    	console.log("onNodeCreated")
                    },
                    onRename: function(arg) {
                    	console.log("编辑")
                    },
                    beforeRemove: function(obj) {
                        return confirm("确认删除?")
                    },
                    beforeAdd: function(obj) {
                        return confirm("确认添加?")
                    },
                    beforeNodeCreated: function(arg) {
                    	
                    	 arg.newLeaf = {
                                 name: "管理员"
                             }

                    	console.log('进来了:',arg);
                    },
                    onNodeCreated: function(arg) {
                        console.log("add")
                    },
                    onClick:function(arg){
                    	
                   
                    }
                }
            }
            vm.$treeOpt = {
                children: vm.child
            }
            vm.$skipArray = ["tree"]
        avalon.vmodels.appVM.mainContent = "departmentListTpl";

    }
    avalon.scan()
});
-------改动之后的tree效果

![0112](https://cloud.githubusercontent.com/assets/14210139/11058455/0e050adc-87ce-11e5-9a11-27905d5c0508.png)

**Comment by z893495246** [comment]
@roscoe054 tree没有按照data配置加载显示，数据是加载了。。。。但是那些data配置貌似没起作用

**Comment by z893495246** [comment]
@roscoe054 html那里我是这样写的
-----------------------------------------------
<div ms-widget="tree,mytree"> </div>

**Comment by z893495246** [comment]
<div ms-widget="tree,mytree"> </div>

**Comment by z893495246** [comment]
<div ms-widget="tree,mytree"></div>

**Comment by roscoe054** [comment]
又看了下文档，你可以试试开始children为空数组，得到数据后用reset方法设置，这样data依然有用：
```javascript
setTimeout(function(){
    avalon.vmodels.tree2.reset(zNodes)
}, 1000)
```

**Comment by z893495246** [comment]
@roscoe054 又要麻烦您了。 这个是tree按照data的配置项正确加载的效果
![06](https://cloud.githubusercontent.com/assets/14210139/11085495/0da4f714-8882-11e5-9499-2874a676e72d.png)
---------------这个是按照你说的改动之后的效果--------
![07](https://cloud.githubusercontent.com/assets/14210139/11085502/2648b1ac-8882-11e5-8496-247250b7b774.png)
-----------------------------我改动之后的代码------------------------------------------------
success: function(data){
                    	avalon.vmodels.mytree.children = data;
                    	avalon.vmodels.mytree.reset(data);
},
 vm.tree = {
                children: [],
                edit: {
                    showRemoveBtn: function(leaf) {
                        return leaf.level > 0
                    }
                },
                data: {     
                    simpleData: {
                    	 enable: true,
                         idKey: "dept_id",
                         pIdKey: "dept_parent"
                    },
                    key: {
                        name: "dept_name", 
                    },
                    keep: {
                        leaf: false,
                        parent: true
                    }
                },
                view: {
                    editNameSelectAll: true,
                    showLine: function(leaf) {
                        return true
                        return leaf.level > 1 || 1
                    }
                },
                callback: {
                    onExpand: function(leaf) {
                        console.log(leaf)
                    }
                }
            }
            vm.$treeOpt = {
                children: []
            }
            vm.$skipArray = ["tree"]
---------------这是我html的代码--------
ms-widget="tree,mytree,$treeOpt"

**Comment by z893495246** [comment]
@roscoe054 不知道我哪里写的还有问题

**Comment by roscoe054** [comment]
succes里面的`avalon.vmodels.mytree.children = data;`这句去掉，只用reset赋值就好了

**Comment by z893495246** [comment]
@roscoe054 OMG,可以了大哥。。。。。

**Comment by z893495246** [comment]
@roscoe054 对的，这句话应该不用了avalon.vmodels.mytree.children = data， 我刚才在调试中，才发现。。。

**Comment by z893495246** [comment]
@roscoe054 而且，html那里我也有改动，只保留了这两个ms-widget="tree,mytree

**Comment by z893495246** [comment]
@roscoe054 非常感谢您帮助我，非常感谢，这个问题困扰了我很久。

**Comment by z893495246** [comment]
@roscoe054 $treeOpt" 我并没有给他赋值，，，，    ms-widget的用法一直在模模糊糊的使用，并不知道他的原理。   这个问题一个月前就纯在，一直解决不掉，放了很长时间，最近项目快完工，才把一些有问题的东西拿出来解决，真的很开心，太感谢您了大哥

**Comment by RubyLouvre** [comment]
不明白，就看一下相关源码

**Comment by xiaomi1120** [comment]
你是怎么做到的 ，我也遇到了同样的问题

**Comment by z893495246** [comment]
@xiaomi1120   你看下我的源码，我上面把源码都发出来了，解决方案也有。你仔细看看

**Comment by z893495246** [comment]
@roscoe054 大哥，我这边又出现了一个新问题，能否麻烦您一下帮我看看https://github.com/RubyLouvre/avalon/issues/1161

**Comment by roscoe054** [comment]
调整一下你数据的顺序，子节点必须在父节点后面，中间不要放别的父节点

**Comment by Lihuanghe** [comment]
哎,看你这么纠结. jquery的ztree用着多顺手 ,老老实实用呗,干吗非得用oni::tree啊.
demo链接 (http://lihuanghe.github.io/avalontest/#!/34)
参考下:

**Comment by z893495246** [comment]
@Lihuanghe 从一开始我就跟经理推荐使用z-tree，可是我们经理是老顽固，不听从别人的建议~  这不，确定了是oniUI的问题，换了z-tree

**Comment by z893495246** [comment]
@roscoe054 但是，你不觉得它这个压根就不是tree吗？ 如果父子关系是根据数据的顺序来排列，还需要data配置干嘛？不死坑人吗？我往数据库里添加数据的时候不可能把儿子添加到父亲的下边吧~~~~
