### ISSUE TITLE
duplex方案求解

### ISSUE THREAD

**Issue by xiarugu** [RubyLouvre/avalon#1150]
用input做一个日期输入, 需要同时支持两种方式
1. 点击input弹出div点选日期, 对input进行赋值
2. 用户可以手工在input中输入日期值, change事件中对输入的值进行格式纠正(例如10/1补齐为2015-10-01, 错误的日期格式则直接把input置空)

在做第一种方式时, 直接对input赋值, 可以变更duplex对应的vm变量, 此时使用的是默认的data-duplex-event="input"

但是当实现第二种方式时, 使用自定义的duplexHooks进行实现, 发现用户还没有输入完就会触发hook中的get方法, 所以得把data-duplex-event更改为change
但是更改为change以后, 又会导致第一种方式失效, 即在data-duplex-event=change的情况下, 无法通过对input直接赋值来更新vm的变量值

是否我的思路不对, 此处不应该通过duplexHooks实现, 而是应该单纯用js/jquery进行change事件监测来进行呢

**Comment by RubyLouvre** [comment]
写一个例子啊

**Comment by RubyLouvre** [comment]
可以看一下oniui的日期选择器
