### ISSUE TITLE
内置ADM加载器 加载 bower下载的最新raphael时,会出现错误,加载eve.js

### ISSUE THREAD

**Issue by susan51531** [RubyLouvre/avalon#1151]
eve是在raphael.js文件中define('eve')的
raphael.js里面合并了两个模块,一个是eve,一个是raphael
其中raphael依赖eve

使用require.js时,没有错误,不会加载eve.js

DEMO结构:
<pre><code>
├── bower.json
├── index.html
├── js
│   └── app.js
├── package.json
└── vendor
    ├── avalon
    └── raphael
</code></pre>
bower.json:
```javascript
{
  "name": "demo",
  "main": "index.js",
  "dependencies": {
    "avalon": "~1.5.5",
    "raphael": "~2.1.4"
  }
}
```
index.html:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    <script src="vendor/avalon/avalon.js" data-main="js/app.js"></script>
</body>
</html>

```

js/app.js:
```javascript
require.config({
    baseUrl: '.',
    paths: {
        raphael: 'vendor/raphael/raphael'
    }
});

require(['raphael', 'domReady!'], function() {
    debugger;
});

```

**Comment by RubyLouvre** [comment]
你需要用avalon.shim＋r.js, requriejs进行合并 ，详见这里 http://avalonjs.github.io/#zh/engineering/loader.html
