### ISSUE TITLE
没找到component的例子啊

### ISSUE THREAD

**Issue by lxholding** [RubyLouvre/avalon#1156]
1.5 新组件说有例子在 component/pager/avalon.pager.js，但是没找到...

**Comment by RubyLouvre** [comment]
自己研究将jquery的bootstrap改成avalon组件吧

**Comment by RubyLouvre** [comment]
不要全部指望我

**Comment by RubyLouvre** [comment]
https://github.com/RubyLouvre/avalon.bootstrap

**Comment by lxholding** [comment]
thx,有例子就好
