### ISSUE TITLE
关于路由的问题

### ISSUE THREAD

**Issue by xinghunMeng** [RubyLouvre/avalon#1157]
想用路由加载html片段，网上的教程是根据1.3.6版本写的，但在新版本1.4.7.1下avalon.router方法打印是未定义，请问这个问题是出在哪里？

**Comment by IndexXuan** [comment]
你这看的百度搜出来的老教程了吧。去mmrouter的github主页！例子学习教程全有，适配1.5

**Comment by xinghunMeng** [comment]
谢谢看到了，那个例子看着好复杂，自己慢慢研究下吧，之前的那个百度的教程很简单，一看就懂了

**Comment by IndexXuan** [comment]
客气了，嵌套视图的mmState那个router例子很好！

**Comment by xinghunMeng** [comment]
现在在做一个公司的旅游交易平台，想直接jq直接撸，觉得太low了，就找了找有什么好用的单页面架构，这个兼容ie678，所以拿来试试，以后遇到问题多交流啊

**Comment by IndexXuan** [comment]
我也才做一个微信webapp'，avalon这个构架真不错！整个视图生命周期管理很好，加油！

**Comment by xinghunMeng** [comment]
路由的avalon版本是1.41，现在的是1.4.7.1，可以直接覆盖掉吧？

**Comment by xinghunMeng** [comment]
我加了你qq了
