### ISSUE TITLE
data-duplex-event="change"的情况下也应加入对value赋值的检测

### ISSUE THREAD

**Issue by xiarugu** [RubyLouvre/avalon#1159]
在xtype为input时, 除了浏览器的input事件, 通过脚本对input.value进行赋值也会触发vm的更新
然而, 在xtype为change时, 却只能通过change事件本身来触发 vm的更新

这样很不方便, 如果用js直接修改了input.value, 即便是xtype=change, vm也是应该更新的, 因为input的值确确实实发生了变化, 而且并非"正在输入"的状态

希望司徒把这里修改一下, 对change也能够作
watchValueInTimer(旧浏览器),  elem.avalonSetter=updateVmodel (新浏览器)
这两项处理

**Comment by RubyLouvre** [comment]
change事件是失去焦点时触发

**Comment by xiarugu** [comment]
举个栗子说明:
有一个简单的jQuery插件, 当用户输入1/1以后(onchange后), 这个插件会把1/1补全为"2015-01-01"
也就是input.value = "2015-01-01", 此时我觉得也是一种输入赋值行为, 也应该触发vm的更新.
而且这种输入行为是高于input/change事件本身的. 因为这种赋值是程序开发人员对"用户输入"的一种"扩展".

**Comment by RubyLouvre** [comment]
有一个data-duplex-change回调

**Comment by xiarugu** [comment]
data-duplex-changed是针对具体标签的配置属性, 插件希望实现的是一种全局的旁路扩展.

**Comment by xiarugu** [comment]
如果使用data-duplex-changed属性, 需要在每个有这样需求的input上都填写这个属性, 且相对应的处理回调也要写到每个页面的vm中, 这样就不叫插件了对吧.

**Comment by RubyLouvre** [comment]
你的插件内部 为这个input元素添加data-duplex-change回调就行了

**Comment by xiarugu** [comment]
data-duplex-change只能有一个, 而且只能是vm里的一个成员函数
插件只能操作DOM, 一来无法获得DOM所在的vm, 二来也无法在vm定义的过程中加入自己需要的callback(没有这样的全局回调)

**Comment by RubyLouvre** [comment]
avalon.tick 试一下这个

**Comment by xiarugu** [comment]
tick只是一个定时器而已啊

**Comment by xiarugu** [comment]
需求再明确的表述一下:
在data-duplex-event="change"的情况下, 想要通过对input的value属性直接赋值来实现对vm的更新
(目前在data-duplex-event="input"的情况下是可以实现的)

**Comment by xiarugu** [comment]
由此衍伸出去, 希望可以对一切tag(不仅是input/textarea/select等表单域标签)进行duplex绑定
比如
```
vm.dept = { id: 1, name: '采购部' };

<div data-api="ThePlugin" ms-duplex="dept"></div>

avalon.bind('duplex-update', function(binding)
{
  //当通过vm发生变化, 需要更新视图时触发
  //在此回调中需要传递elem和vm中的值(vm.name的值)
  //以便在此进行定制化的value显示
});

而在User内部进行一些键盘和鼠标操作导致其值发生变更后, 插件内部代码可以这样更新vm的值:
if (elem.avalonSetter)
    elem.avalonSetter({ id: 3, name: '销售部' });
```

这样可以实现 { id: 3, name: '销售部' } 这种复合值的显示与更新
常见的有下拉提示的输入框, 传统的ms-duplex只能获得、设置显示的文本, 但是我们希望获得的一般不是文本, 而是文本对应的那个id编号
