### ISSUE TITLE
功能建议:增加几个全局回调

### ISSUE THREAD

**Issue by xiarugu** [RubyLouvre/avalon#1160]
希望avalon能够增加几个全局回调来增强可扩展性
目前的data-duplex-changed, data-include-loaded等回调是针对具体标签的
而avalon-ms-duplex-init又是针对具体vm的

如果想要做"旁路"扩展比较困难
希望司徒能够增加几个全局回调, 来方便对avalon的扩展, 
全局回调不需要获得具体的vm, 可直接进行类似 avalon.bind('avalon-model-ready', callback) 这样的回调绑定

需要/考虑增加的全局回调
1. avalon.define以后, 即建立了某个vm后产生一个全局回调
2. avalon.scan中发现并完成某个ms-controller视图绑定后的回调(发现和完成可以考虑分开回调)
3. avalon-ms-duplex-init这样的全局回调, 即在avalon.scan扫描过程中每遇到一个duplex双工绑定产生一次回调, 其他的属性、节点也可以考虑回调

有了这些全局回调， avalon应该也差不多成神器了.

这其中也需要考虑性能的问题, 具体如何权衡还要司徒考量

**Comment by Lihuanghe** [comment]
能举例讲讲具体的业务场景吗? 我不明白这些特性在哪些使用场景下会用到.

**Comment by RubyLouvre** [comment]
avalon.scan后面的回调在1.3左右试过了，实现不了，因此你看ng, vue, knockout都没有这样的回调，因为无法判定DOM树有多少节点

**Comment by xiarugu** [comment]
scanTag里有个判断是否有ms-controller属性的, 直接在此处扫描完成后给出一次回调就OK.

**Comment by RubyLouvre** [comment]
那是在开标签中发现的，不是在闭标签，因此还是做不到

**Comment by xiarugu** [comment]
scanTag函数执行完毕就是对某个ms-controller绑定的结束吧

**Comment by xiarugu** [comment]
@Lihuanghe 
avalon的优点、长处是业务代码基本上不需要操作DOM, 所以短板也在DOM上
想要更细致更定制的产生DOM交互就是avalon的短板.
有了这些回调以后, jQuery、原生JS能够做的所有插件、组件就可以比较方便的加入对avalon的支持了.

**Comment by Lihuanghe** [comment]
我的理解是.那些与model没关系的,比如动画,纯粹的view的样式渲染应该使用jquery这些能灵活操作dom的库来实现.而不应该再用vm去操作数据,再利用vm的自动同步达到操作dom的目的.这样性能不好,代码跟思维方式也不一致:  
比如:要实现一个dom的颜色变化,dom的动画移动, 最直接的思维方式就是获取dom,然后修改颜色,移动位置或者修改大小. 那么代码实现上就应该是$('#divId').css() , $('#divId').move(). 这样思维和代码一致.容易被人理解.上手也较快.

而对待jquery一些组件,应该像对待原生组件一样,通过组件提供的api实现与组件的交互,而不应该跨过组件去直接操作组件内部的dom. 

 avalon的职责就是获取后台数据后,重新组织数据, 实现复杂的数据转换, 如果avalon能将数据自动同步到view最好, 不行就利用jquery或者jquery的组件api来操作dom实现业务.

**Comment by RubyLouvre** [comment]
可以搞一下ms-controller与ms-important所有元素的回调

大概是这里

```javascript
    var b = elem.getAttributeNode("ms-important")
    var c = elem.getAttributeNode("ms-controller")
    if (typeof a === "string") {
        return
    } else if (node = b || c) {
        var newVmodel = avalon.vmodels[node.value]
        if (!newVmodel) {
            return
        }
        //ms-important不包含父VM，ms-controller相反
        vmodels = node === b ? [newVmodel] : [newVmodel].concat(vmodels)
        var name = node.name
        elem.removeAttribute(name) //removeAttributeNode不会刷新[ms-controller]样式规则
        avalon(elem).removeClass(name)
        createSignalTower(elem, newVmodel)
    }
    scanAttr(elem, vmodels) //扫描特性节点
    if (newVmodel) {
        setTimeout(function () {
            for (var i in avalon.vmodels) {
                var v = avalon.vmodels[i]
                v.$fire("avalon-ms-scan-end", newVmodel.$id)
            }
        })
    }
```
你自己试一下，没问题再告诉我

**Comment by xiarugu** [comment]
@Lihuanghe 对对对, 黄河说的正是我想表达的意思
select我们通过ms-each来填充option, 为select组件提供了一个[{value, text}]的数据源, 正是因为select组件的接口如此,
那么同样的, 对待那些jQuery组件, 我们也应该视为同样的组件调用

@RubyLouvre 可能是我想的复杂了, 其实最想要的就是普通标签上的duplex实现
如果一个组件的构建方式是
```
<div data-api="Calendar"></div>
```
那么我希望
```
<div data-api="Calendar" ms-duplex="vm.date"></div>
```
就可以直接实现取值赋值, 至于Calendar内部怎样去进行 duplex的取值赋值, 那是组件开发者的工作, avalon要做的就是提供一种接口方式, 让组件开发者可以在vm变化时能够得到回调通知, 以便更新组件表现; 在组件值发生改变时有方法可以调用, 来进行updateVModel通知vm更新

**Comment by xiarugu** [comment]
```
$(document).on('avalon-duplex-update', '[data-api]', function(e, value)
{
//此处, $(this)得到的就是div元素, value得到的就是vm.date的值
});
......

//在用户做了一些操作, 导致Calendar组件的值发生变化时:
//假设此处div变量指向的就是Calendar组件外包装的div
typeof(avalon) == 'function' && avalon(div).updateVM(value);
//上面的效果类似于普通的表单组件发生input/change事件一样
```

**Comment by xiarugu** [comment]
司徒暂时不打算对普通标签实现duplex回调么?

**Comment by RubyLouvre** [comment]
这是做不到，普通标签没有这些事件！
