### ISSUE TITLE
oniUI  tree  又发生了一件很奇怪的事情

### ISSUE THREAD

**Issue by z893495246** [RubyLouvre/avalon#1161]
这个tree组件让我折腾了很久，看了文档，还是没找到哪里有问题。先看我的效果图，你就知道发生了什么事。
![01](https://cloud.githubusercontent.com/assets/14210139/11176526/dd1dc940-8c78-11e5-8b2f-cb64af98e4e6.jpg)
-------------------------------------------------------------------------------------------
很明显，人事部门，技术部门，客服部门都是父级菜单。  下面3个都是对应的子级菜单，子级“客服-小张”跟他的“父亲”客服部门对应的没有问题，但是，人事跟技术的父子关系出现了问题，并没有一一对应。
下面是我的数据属性。
![02](https://cloud.githubusercontent.com/assets/14210139/11176571/3772ac80-8c79-11e5-98da-e2ef4d60bb14.jpg)
-----------------------------------------------------------------
tree的data 配置关系，我是这样写的：
data: {     
                    simpleData: {
                    	 enable: true,
                         idKey: "dept_id",
                         pIdKey: "dept_parent"
                    },
                    key: {
                        name: "dept_name", 
                    },
                    keep: {
                        leaf: false,
                        parent: true
                    }
                }
------------------------------------我的源代码------------------------------
  vm.tree = {
                children: [],
                edit: {
                    showRemoveBtn: function(leaf) {
                        return leaf.level > 0
                    }
                },
                data: {     
                    simpleData: {
                    	 enable: true,
                         idKey: "dept_id",
                         pIdKey: "dept_parent"
                    },
                    key: {
                        name: "dept_name", 
                    },
                    keep: {
                        leaf: false,
                        parent: true
                    }
                },
                view: {
                
                }
}
-------真的不知道到底发生了什么，会出现这种情况。

**Comment by z893495246** [comment]
谁能帮帮我啊。。。。

**Comment by z893495246** [comment]
@RubyLouvre

**Comment by xiaomi1120** [comment]
我都没显示出来数据，。。你是如何显示出数据的？

**Comment by xiaomi1120** [comment]
@z893495246 你的数据是如何显示出来的？在线求

**Comment by z893495246** [comment]
@xiaomi1120   children: [], 这里不是放数据的吗？我明天给你发代码吧。
