### ISSUE TITLE
oni UI      tree组件的bug！！！

### ISSUE THREAD

**Issue by z893495246** [RubyLouvre/avalon#1162]
tree组件的父子关系data配置好像没起到作用，它的上下级关系并不是根据父子关系排列的，而是根据数据的顺序排列
-----------------------------这是tree组件的数据源【简单数据模式】----------------------
var zNodes =[
            { id:1, pid:0, name:"父节点1 - 展开", open:true},
            { id:11, pid:1, name:"父节点11 - 折叠"},
            { id:111, pid:11, name:"叶子节点111"},
            { id:112, pid:11, name:"叶子节点112"},
            { id:113, pid:11, name:"叶子节点113"},
            { id:114, pid:11, name:"叶子节点114"},
            { id:12, pid:1, name:"父节点12 - 折叠"},
            { id:121, pid:12, name:"叶子节点121"},
            { id:122, pid:12, name:"叶子节点122"},
            { id:123, pid:12, name:"叶子节点123"},
            { id:124, pid:12, name:"叶子节点124"},
            { id:13, pid:1, name:"父节点13 - 没有子节点", isParent:true},
            { id:2, pid:0, name:"父节点2 - 折叠"},
            { id:21, pid:2, name:"父节点21 - 展开", open:true},
            { id:211, pid:21, name:"叶子节点211"},
            { id:212, pid:21, name:"叶子节点212"},
            { id:213, pid:21, name:"叶子节点213"},
            { id:214, pid:21, name:"叶子节点214"},
            { id:22, pid:2, name:"父节点22 - 折叠"},
            { id:221, pid:22, name:"叶子节点221"},
            { id:222, pid:22, name:"叶子节点222"},
            { id:223, pid:22, name:"叶子节点223"},
            { id:224, pid:22, name:"叶子节点224"},
            { id:23, pid:2, name:"父节点23 - 折叠"},
            { id:231, pid:23, name:"叶子节点231"},
            { id:232, pid:23, name:"叶子节点232"},
            { id:233, pid:23, name:"叶子节点233"},
            { id:234, pid:23, name:"叶子节点234"},
            { id:3, pid:0, name:"父节点3 - 没有子节点", isParent:true}
        ];
------------------------------------------------------------------------------
大家可以尝试一下，把数据的顺序给打乱，看下效果，你就会发现，data的配置没有起到丝毫作用！

**Comment by gogoyqj** [comment]
![hehe](https://cloud.githubusercontent.com/assets/1776278/11178126/96adaac2-8c85-11e5-8026-002c88df429d.png)

**Comment by z893495246** [comment]
@gogoyqj 把数据源打乱，你就会发现奇迹。

**Comment by z893495246** [comment]
@gogoyqj 你用这个试试看效果
{ id:11, pid:1, name:"父节点11 - 折叠", open:false},
{ id:111, pid:11, name:"叶子节点111", open:false},
{ id:1, pid:0, name:"父节点1 - 展开", open:true},


{ id:112, pid:11, name:"叶子节点112", open:false},
{ id:113, pid:11, name:"叶子节点113", open:false},
{ id:114, pid:11, name:"叶子节点114", open:false},

**Comment by gogoyqj** [comment]
不支持乱序，ztree也不支持乱序

**Comment by z893495246** [comment]
@gogoyqj 阿。。。感觉这样有点不合理啊。

**Comment by z893495246** [comment]
@gogoyqj 如果不支持的话，那data配置不是毫无意义吗？

**Comment by z893495246** [comment]
@gogoyqj 涨知识了，原来是真的不支持乱序的~
