### ISSUE TITLE
表单列表文本框绑定后光标跳动

### ISSUE THREAD

**Issue by ttt22703** [RubyLouvre/avalon#1164]
var vm = avalon.define({
                    $id: "list",
                    list:
                            [
                                {id: 1, checked: false, sort: 0, title: "title1", category: "category1", visits: 1, add_time: "2015-11-17 09:23", status: 0},
                                {id: 2, checked: false, sort: 0, title: "title2", category: "category2", visits: 11, add_time: "2015-11-17 09:23", status: 0},
                                {id: 3, checked: false, sort: 0, title: "title3222222222", category: "category3", visits: 21, add_time: "2015-11-17 09:23", status: 0},
                                {id: 4, checked: false, sort: 0, title: "title4", category: "category4", visits: 11, add_time: "2015-11-17 09:23", status: 1},
                                {id: 5, checked: false, sort: 0, title: "title5", category: "category5", visits: 22, add_time: "2015-11-17 09:23", status: 1},
                                {id: 6, checked: false, sort: 0, title: "title6", category: "category6", visits: 2, add_time: "2015-11-17 09:23", status: 1},
                            ]
})

            <div ms-class="list-item" ms-repeat="list" >
                <div><input type="checkbox" ms-duplex-checked="el.checked" >{{el.id}}</div>
                <div><input type="text" ms-duplex="el.sort" data-duplex-event="change"></div>
                <div>{{el.title|truncate(10)}}</div>
                <div>{{el.category}}</div>
                <div>{{el.visits}}</div>
                <div>{{el.add_time|date("yyyy MM dd:HH:mm:ss")}}</div>
                <div>{{el.status==1?"审核":"待审"}}</div>
            </div>

**Comment by ttt22703** [comment]
别一个问题
 js是这样定义的
            var vm = avalon.define({
                $id: "insert",
                data: {
                    title: {
                        value: "1111",
                        is_require: true,
                        notice: ""
                    },

我想监控data.title.value属性的变化,不能监测到变化

vm.$watch("data,title.value",function(){})

**Comment by RubyLouvre** [comment]
第一个问题好了；第二个问题给出完整的页面

**Comment by RubyLouvre** [comment]
还要学一下markdown怎么高亮代码吧

**Comment by RubyLouvre** [comment]
https://github.com/RubyLouvre/avalon2

**Comment by ttt22703** [comment]
好，我试试去，呆会把那个完整的代码发上去。
