### ISSUE TITLE
component没有执行$ready

### ISSUE THREAD

**Issue by sikaco** [RubyLouvre/avalon#1165]
<img width="340" alt="2015-11-18 2 08 21" src="https://cloud.githubusercontent.com/assets/5554734/11233914/c3eb002e-8dfd-11e5-894e-2b31a2ec18a7.png">
<img width="487" alt="2015-11-18 2 07 45" src="https://cloud.githubusercontent.com/assets/5554734/11233943/1df91362-8dfe-11e5-902e-6b120537f8ce.png">

<img width="466" alt="2015-11-18 2 08 06" src="https://cloud.githubusercontent.com/assets/5554734/11233985/8fc01626-8dfe-11e5-84f9-f2bd0ffc857d.png">

可以看到并没有执行console.log，界面上的表格也没有渲染。
<img width="516" alt="2015-11-18 2 11 56" src="https://cloud.githubusercontent.com/assets/5554734/11234164/25064cb8-8e00-11e5-9c53-10399f6326eb.png">

**Comment by RubyLouvre** [comment]
能贴代码吗，要我重构一遍吗，

**Comment by RubyLouvre** [comment]
能用正常的JS好不好

**Comment by sikaco** [comment]
恩，，my wrong。
话说这下又可以了。囧
