### ISSUE TITLE
其实 for i = 1..5 有没有什么好方法，为什么不做一个新的循环方式呢？

### ISSUE THREAD

**Issue by fish-ball** [RubyLouvre/avalon#1168]
其实能不能做一个这样的循环方法？

```
<ul ms-for="5" data-for-begin="1" data-for-step="2">
  <li>{{ $index }}</li>
</ul>
```

其实有这个不是很好吗？现在如果想仅仅遍历一个数量其实没有什么好方法，如果为了这样要在 vm 里面再定义一个数组或者对象，感觉对代码的质量影响太大了，司徒你怎么看？

**Comment by RubyLouvre** [comment]
自己实现一个ms-for指令, 详见这里 http://avalonjs.github.io/#zh/bindings/directive.html
