### ISSUE TITLE
在自定义widget时，vm.$init 中有异常未能抛到浏览器

### ISSUE THREAD

**Issue by wolfJ** [RubyLouvre/avalon#1171]
avalon版本：1.46.
示例代码：
define(["avalon","mywidget"],function(avalon,template){
    var widget = avalon.ui[widgetName] = function (element, data, vmodels) {
    var vmodel = avalon.define('widgetNameId', function (vm) {
        //...
        vm.$init = function () {
        var aa=null;
        alert(aa.length);//此错误导致avalon挂了，错误也不会被抛至浏览器。        
        }
        //...
    }
});

**Comment by RubyLouvre** [comment]
代码不完整啊，另，建议使用1.5.*,          1.4.6不维护了

**Comment by RubyLouvre** [comment]
```javascript
 createSignalTower(elem, vmodel)
                try {
                    vmodel.$init(function () {
                        avalon.scan(elem, [vmodel].concat(vmodels))
                        if (typeof options.onInit === "function") {
                            options.onInit.call(elem, vmodel, options, vmodels)
                        }
                    })
                } catch (e) {
                    log(e)
                }
```

这是源码
