### ISSUE TITLE
容错期望

### ISSUE THREAD

**Issue by xiarugu** [RubyLouvre/avalon#1173]
在实际的业务逻辑中, 当一个变量的类型是object的时候, 如果这个实体不存在, 我们的惯性逻辑是对此变量赋"空"值, 例如某个公司的"联系人"信息, 
```
//有值:
company.contact = { name: '张三', phone: '13185247745' }

//无值:
company.contact = null;
```
但是这在avalon中是不被提倡的, 甚至是会导致严重错误的, 如果在模板中直接写的是 {{company.contact.name}}的话, 结果会变得不可预期.

之所以说不可预期, 大家可以尝试一下对contact进行反复的赋值, 为对象, 或为空字符, 或为null
1.如果初始化时contact是null, 而后进行了object赋值的话, suprise! 模板中成功的显示出了张三的名字.
2. 但是"再次"赋值为null, sadly, 这里不是想象中的变成空白, 而是变成了 {{company.contact.name}}, 对的, 你没有看错, 就是显示了模板的"源代码"!
3. 再次赋值为{ name: '张三' }, 页面没有变化, 还是显示处理前的"源码"
4. 再次赋值为''(空白字符串), 咦, 源码不见了, 变成了空白
5. 再次赋值 { name: '张三' }, 张三又回来了!

是不是被彻底绕晕了? 是的, 我也被绕晕了. 

啃了半天的代码以后, 终于发现了原因, avalon在执行表达式返回值的时候, 为了保证程序不崩溃, 使用了try catch, 可以认为对表达式的计算采用的是"预编译"的方法, 每个表达式对应一个Function, 而一旦这个Function计算产生了错误, 比如前面的步骤2中contact变成了null, 在计算表达式时, 相当于对一个null进行属性求值, 这是大家熟悉的错误类型, 这时, 
avalon会执行 delete binding.getter, 结束处理.

到这里都容易理解, 那么为什么再次赋值为 { name: '张三' }的时候, 张三却没有显示出来呢.
问题在于, avalon每次是否更新页面, 取决于表达式的计算值是否发生了变化.
1. 第一次计算成功, 得到了 "张三", avalon把这个值存储为该表达之的oldValue
2. 第二次联系人是null, 计算失败, avalon直接结束了计算处理, 
注意, 这次计算失败以后, 表达式的oldValue没有去碰他, 因此依然是"张三"
3. 再次 { name: '张三' } 回来的时候, avalon虽然计算出了结果是"张三", 但是因为oldValue也是"张三", 因此avalon认为值没有发生变化, 所以没有去更新页面, 页面也就保持着之前的 "源码" 状态了.

到这里, 我们就知道了, 问题在于计算表达式"出错", 

所以如果表达式写成 {{contact&&contact.name}}, 就不会存在这个问题了.

==============我是吸引眼球的分隔符========================
又或者, 司徒能够修改一下此处:
1. 当计算表达式出错时, 不是"保持源码", 而是视为计算结果为null, 这其实也是大多数模板引擎的处理方式, "尝试取值失败视为null"
2. 接上面这条, 计算失败也应该更新oldValue, oldValue = null
========================================================

至此结束, 强烈期望司徒能够修改此处, 我长期以来都以为是avalon不支持对象表达式置空, 原来司徒辛辛苦苦是有对新的object类型的value赋值进行绑定处理的, 就是这里的一个try catch的处理细节导致了误会.

**Comment by xiarugu** [comment]
我尝试只在a = binding.getter.apply(0, binding.args)这一条语句上进行try catch
失败时直接进行 a=null 的赋值
试了一下(包括深层嵌套), 发现也没有问题
暂时没弄明白计算失败时, 为什么要删除getter下次重建呢?

注: 以上讨论应该仅限于单向渲染, 双工绑定涉及到vm的赋值, 没有父对象自然不能对子对象进行赋值
所以如果涉及到 company.contact.name 的duplex的话, 应该在业务代码上手工创建新的contact对象

**Comment by RubyLouvre** [comment]
你有什么好办法，正在重写官网中，暂时抽不出时间

**Comment by xiarugu** [comment]
在avalon.injectBinding的binding.update中
原文:
```
if (binding.type === "on") {
    a = binding.getter + ""
} else {
    a = binding.getter.apply(0, binding.args)
}
```
改成:
```
if (binding.type === "on") {
    a = binding.getter + ""
} else {
    try { a = binding.getter.apply(0, binding.args) } catch(ex) { a = null }
}
```

**Comment by RubyLouvre** [comment]
已经整合到框架中，THX
