### ISSUE TITLE
avalon oniui mmstate GC回收问题

### ISSUE THREAD

**Issue by davidduwei** [RubyLouvre/avalon#1176]
版本：avalon1.4*+oniui+mmstate0.8
场景:在一个存在组件的的视图，通过链接进入一个不含有任何组件的视图，再通过链接返回到上一个视图，便发现调用组件那块就会出错了。
看了下源码中rejectDisposeQueue方法判断存入avalon.$$subscribers中type为widget的个数是否与oldInfo的widget个数是否相同判断是否需要执行disposeData函数销毁。上面这种场景就会存在oldInfo和newInfo组件个数相同，而不去执行销毁，当再次返回到上一次视图的时候，因为组件又重新生成了并push到了avalon.$$subscribers中，然后oldInfo和newInfo的widget不相同就去执行了销毁了上一次的组件导致了出错。不知有没有办法可以修改下来进行组件的销毁并且不报错呢。
<p style="color:#c00">组件其实是写了$remove的。按理说不需要自己再去写个GC去销毁组件及相关的元素吧。</p>
<pre>
while (data = disposeQueue[--i]) {
        var type = data.type
        if (newInfo[type]) {
            newInfo[type]++
        } else {
            newInfo[type] = 1
            allTypes.push(type)
        }
    }
    allTypes.forEach(function (type) {
        if (oldInfo[type] !== newInfo[type]) {
            iffishTypes[type] = 1
            diff = true
        }
    })
</pre>
//oldInfo.type的widget个数跟newInfo.type的个数相同了，iffishTypes的widget就不存在。下面if也就不会执行到里面呢。
<pre>
if (iffishTypes[data.type] && shouldDispose(data.element)) { //如果它没有在DOM树
                disposeQueue.splice(i, 1)
                delete disposeQueue[data.uuid]
                //delete uuid2Node[data.element.uuid]
                var lists = data.lists
                for (var k = 0, list; list = lists[k++]; ) {
                    avalon.Array.remove(lists, list)
                    avalon.Array.remove(list, data)
                }
                disposeData(data)
            }
</pre>

**Comment by RubyLouvre** [comment]
那你需要缓存上一个视图，需要用到data-view-cache="true"，具体你可以 到论坛里面找找，有人处理过

**Comment by davidduwei** [comment]
这个以前用过哈，但需求是视图切换的时候需要重新更新视图，原来是在视图销毁的时候在自己去delete相应的组件，但上面场景还是会存在这种问题，发现貌似还得去处理avalon.$$subscribers才行。
我现在是暂且在if (iffishTypes[data.type] && shouldDispose(data.element)) 那里加了一层||!iffishTypes[data.type] && shouldDispose(data.element) && data.type == 'widget'去解决的。因为确实会存在iffishTypes[data.type]不存在但是元素已经不存在的情况。

**Comment by RubyLouvre** [comment]
这样很可怕吧

**Comment by davidduwei** [comment]
什么情况下会导致内存泄露呢。

**Comment by RubyLouvre** [comment]
element想不被移除，可以在切换页面前对这个元素添加 elem.msRetain = 1(onBeforeUnload;然后再次进入此页面时，elem.msRetain = void 0(onEnter)

**Comment by davidduwei** [comment]
https://github.com/davidduwei/dw-learn
这种情况好像与上无关，我是整个视图第二次进来就要全部重新刷新，这样也会导致avalon.$$subscribers重复添加相同的ms-widget 对应的vmodels进去 。
我整个了很简单的例子。一个视图就加了一个Grid,dialog,另外一个视图就一段文字。通过gird列表点击查看详情，然后在点击上面的价格列表回到原视图就会出现报错（有时候不出现报错，这种情况就是因为输出的oldInfo.widget和newInfo.widget不相同会不报错，但大部分都是相同的）。
![image](https://cloud.githubusercontent.com/assets/7507764/11467888/346f31c6-9786-11e5-8545-8c89616ca1d1.png)

**Comment by davidduwei** [comment]
司徒大大好久有时间能不能给看看这个问题，我目前是在这个地方加了层专门针对widget处理的。
![image](https://cloud.githubusercontent.com/assets/7507764/11620444/ee988932-9ced-11e5-934f-873547e856c3.png)

**Comment by RubyLouvre** [comment]
为什么要特殊处理widget啊

**Comment by davidduwei** [comment]
因为针对路由加组件这种情况，从视图A（含有组件个数(2)）,进入导视图B（不含有组件），iffishTypes(data.type)是判断的widget的个数有没有发生变化做的GC,上面这种情况组件个数是不存在变化的，这个时候再从B回到视图A，widget又重新计算增加到4个呢，与原来2个不相同，并且shouldDispose中data.element判断的是第一次刚进入A视图的组件元素，所以这个时候进行了组件相应的vmodels销毁。就会存在报错。https://github.com/davidduwei/dw-learn 写了个很简单的例子。

**Comment by gogoyqj** [comment]
唉，所以视图里面出现的组件一般都这么写

```
<div ms-widget="dialog,$,opt"></div>
```

走匿名，然后在opt.onInit里面去获取vm

**Comment by davidduwei** [comment]
额，走匿名。确实能解决,还有就是不存在组件的视图都加个空组件都能解决啊，其实我就针对widget这种在GC回收的时候单独判断了下不存在元素也回收掉也不存在问题。而且也没必要去担心存不存在组件，或则必须得走匿名了。

**Comment by gogoyqj** [comment]
视图多了，组件多了，还能这么搞 - -，匿名是唯一选择了，不然就切回来 location.reload() 一下

**Comment by davidduwei** [comment]
GC针对这种页面上组件元素都不存在了 为什么不回收呢？

**Comment by gogoyqj** [comment]
循环引用，av有个定时器或者其他机制来触发去check，可以帮助释放一些，有一些地方可能有遗漏的
