### ISSUE TITLE
HTTPS版官网引用了HTTP的外部资源

### ISSUE THREAD

**Issue by zhang-z** [RubyLouvre/avalon#1184]
https://avalonjs.github.io/ 用了以下几个HTTP资源：

    <link href="http://cdn.bootcss.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
    <link href="http://cdn.bootcss.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="http://static.bootcss.com/www/assets/css/site.min.css?v5" rel="stylesheet">

有的浏览器会拒绝加载。前两个只需要改成```//cdn.bootcss.com```就可以。static.bootcss.com没有https站，得找别的解决方案。

另外，http的官网会报这几个warnings：

    avalon.shim.js:48
    warning:exception throwed in [avalon.injectBinding]  Error: warning:el.sub只能是对象或数组(…)
    warning!请改用ms-attr-href代替ms-href!
    warning!请改用ms-attr-src代替ms-src!

**Comment by RubyLouvre** [comment]
已经改了

**Comment by zhang-z** [comment]
还是有点问题，```<script src="http://cdn.bootcss.com/jquery/1.11.2/jquery.min.js"></script>```这行也该改成```//cdn.bootcss.com```
还有这行```<link href="//static.bootcss.com/www/assets/css/site.min.css?v5" rel="stylesheet">```，static.bootcss.com没有https版本
