### ISSUE TITLE
avalon.mix({}); 值覆盖问题？

### ISSUE THREAD

**Issue by Thinking80s** [RubyLouvre/avalon#1186]

**Comment by xingxiulaoxian** [comment]
没看到覆盖对象
avalon.mix({arr: [{id:12,lists:[{name:'hello'}]}]}, {id: 12,lists: []}); 
你那个少俩冒号
试试这个

**Comment by Thinking80s** [comment]
sorry 是我描述不准确，我在详细描述下。

**Comment by RubyLouvre** [comment]
这个方法就是jquery的extend方法，一模一样
