### ISSUE TITLE
avalon通过外部js调用某个model的方法，无法改变model中对象的属性?

### ISSUE THREAD

**Issue by yelikang** [RubyLouvre/avalon#1192]
步骤一:
\<a onclick="tempSearch('1')">\</a>"调用tempSearch
步骤二
var tempSearch =function(msg){
avalon.vmodels.testController.search(msg);
}
controller定义
var vm = avalon.define({
  $id:"testController",
  testVal:"",
  search:function(){
  vm.testVal="678"
}

})

步骤三
\<a ms-click="search('1')">\</a>可以改变model中对象的属性

如图，步骤1 直接通过onclick事件触发tempFn函数，tempFn函数调用avalon中某个model中的函数（步骤2），去改变model中对象的值；但是不行
而直接通过步骤3，页面上ms-click事件却可以改变对象中的值

**Comment by RubyLouvre** [comment]
不要onclick，要使用ms-click，确保能拿到vm

**Comment by yelikang** [comment]
@RubyLouvre    恩恩   测试发现直接用ms-click可以，但是因为数据是动态的，而又涉及到分页，使用的是datatables 所以想通过外部的onclick转换一下。
   现在问题解决了，不是avalon的问题，通过外部转换onclick同样可以改变对象属性值，是因为我页面上有个js跟avalon冲突了，改变了一下位置就好了，谢谢司徒大大
