### ISSUE TITLE
avalon中使用resizable拖拽元素容易失去对元素的控制

### ISSUE THREAD

**Issue by caixiaojian** [RubyLouvre/avalon#1195]
当我在使用 oniui的resizable的时候，在对一个元素添加resizable，在动态改变元素的x,y的时候 如果左右“快速”摇晃鼠标的时候，鼠标失去对元素的控制了，官方网站 http://hotelued.qunar.com/oniui/index.html#!/widgets?widgetId=resizable&ex=ex6 的demo也有这个问题，请问有解决办法吗？？？

**Comment by roscoe054** [comment]
已经修复了
