### ISSUE TITLE
1.5版本ms-duplex在ie edge版本下报错

### ISSUE THREAD

**Issue by qdafeng** [RubyLouvre/avalon#1196]
ie浏览器Edge模式下的报错
"无法获取未定义或 null 引用的属性“uuid”，

1.4版本是没问题的，其他浏览器都是ok的，求大大教我解决之法

**Comment by RubyLouvre** [comment]
请给出完整的例子

**Comment by qdafeng** [comment]
任何的input中的ms-duplex数据双向绑定都是报错的，这个不需要例子了吧

**Comment by RubyLouvre** [comment]
需要

**Comment by RubyLouvre** [comment]
贴一下详细错误消息

**Comment by roscoe054** [comment]
测过了1.5.6在edge下没有报错 http://jsfiddle.net/8w9pLohk/4/

**Comment by qdafeng** [comment]
辛苦楼上大哥帮忙解决，小弟刚学，只会用用
