### ISSUE TITLE
官网一个关于duplex的例子跑不起来

### ISSUE THREAD

**Issue by iulo** [RubyLouvre/avalon#1197]
http://avalonjs.github.io/#tutorial/directives/duplex.html

    <!DOCTYPE html>
    <html>
     
    <head>
        <title>ms-duplex</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <script src="avalon.js"></script>
        <script>
            avalon.define({
                $id: "test",
                aaa: {
                    xxx: "444",
                    yyy: "555"
                },
                bbb: "yyy",
                zzz: "text"
            })
        </script>
    </head>
     
    <body ms-controller="test">
        <input ms-duplex="aaa['xxx']">
        <input ms-duplex="aaa[bbb]">
        <input ms-duplex="zzz" ms-data-duplex-observe="zzz" />
        <p>{{aaa.xxx}}</p>
        <p>{{aaa.yyy}}</p>
        <p>{{zzz}}</p>
    </body>
     
    </html>

官网这个例子跑不起来，版本1.5.5

**Comment by iulo** [comment]
1.4.7可以

**Comment by iulo** [comment]
发现原来 `ms-data-duplex-observe` 已经废掉了

**Comment by RubyLouvre** [comment]
<input ms-duplex="aaa[bbb]">, 这个我去修修。 ms-data-duplex-observe 已经废掉了
