### ISSUE TITLE
如何对数组元素skipArray

### ISSUE THREAD

**Issue by xiarugu** [RubyLouvre/avalon#1199]
如果说avalon有什么性能瓶颈的话, 我想一定是列表的显示了. 也是用户最容易感觉到"卡顿"的地方.
很多场景下, 尤其是对于数据量较大的列表, 我们其实并不需要observe列表中每个元素的每个属性,

很多时候只是需要一个单向、一次性的渲染功能。
个人经常在列表循环内部全部写成::oneTime的形式
不过列表元素的observe还是非常占用资源, 要对列表元素进行忽略observe, 得在每个列表元素中都设置一个$skipArray, 还得囊括该元素的所有属性.

司徒是否可以开启一种特殊的绑定方式, 让avalon忽略对列表内部的observe, 仅对列表赋值本身监控.

类似 vm.$skipArray = " list.* " 之类的形式
或者 list.$skipArray = true 之类的.

**Comment by RubyLouvre** [comment]
已经开发出全新的modelFactory(减少VM的体积)，正在开发新的基于状态机的JSparser(减少绑定属性中的变量的匹配速度)。。。。

**Comment by xiarugu** [comment]
期待ING
