### ISSUE TITLE
关于avalon_$watch的问题

### ISSUE THREAD

**Issue by webLeeSun** [RubyLouvre/avalon#1201]
avalon版本1.5.5
两个数组，前一个define的时候就有内容，后一个是后添加进去的，
对象属性通过ms-duplex绑定在input上，
model.$watch进行监听：model.$watch('arr_1.*.a', function(o) {});
前一个input输入变化是，能监听到，后一个不行。
描述的不是很清楚，详细情况：
https://github.com/webLeeSun/question_avalon_watch.git

**Comment by roscoe054** [comment]
这种后添加进去的是不能watch的。。必须都先初始化

**Comment by RubyLouvre** [comment]
暂时无法支持这个功能

**Comment by webLeeSun** [comment]
你就差这点钱？
