### ISSUE TITLE
avalon#1.4.7怎么清理scan, vm上数组重新赋值,绑定的ms-repeat没有重新render

### ISSUE THREAD

**Issue by susan51531** [RubyLouvre/avalon#1203]
状态A中有一个使用bootstrap modal做的对话框,里面一个通过异步获取的array数据,使用ms-repeat显示
第一次进入状态A时,触发显示modal,能正常显示数据,
然后切换到别的状态后再切换回来,再触发显示modal,更新绑定在控制器上的array,没能显示数据,显示为空
感觉就像没有触发ms-repeat重新render一样,获取的数据不为空,

像下面这样分两步处理也不行
```javascript
    vm.list = []; // 先清空
    vm.list = data;
```

对话框大致是这样的
```javascript
var $modal,
    vm;
vm = avalon.vmodels.modalVMId;
$modal = $('bootstrapModalSelector').modal();
if(!vm) {
    vm = avalon.define({
        $id: 'modalVMId',
        list: []
    });
    avalon.scan($modal[0], vm); // 发现这句在位置B,对问题没影响
}
// 位置B
$moda.modal('show');
```

试过每次modal, hidden后,删除vm,然后每次显示modal都重建vm,再scan发现不行

只有同时modal通过模板clone新建,hidden后,执行下面
```javascript
$modal.data('bs.modal',null);
$modal.remove();
delete avalon.vmodels.modalVMId;
```
才可以

我想问有没有清理scan的方法

**Comment by RubyLouvre** [comment]
等我过段时间重构modelFactory就行了
