### ISSUE TITLE
1.5.x版本中，嵌套遍历中的双向绑定出现异常‘el is not defined’

### ISSUE THREAD

**Issue by juneryo** [RubyLouvre/avalon#1207]
````
<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
	<script type="text/javascript" src="avalon.js"></script>
</head>
<body class="ms-controller" ms-controller="test">
	<table>
		<tr ms-repeat="row">
			<td ms-repeat="col">
				<input ms-if="el.type == 'text'" ms-duplex="$outer.el[el.name]" />
				<select ms-if="el.type == 'select'" ms-duplex="$outer.el[el.name]">
					<option value=""></option>
					<option ms-repeat="el.option" ms-attr-value="$key">{{$val}}</option>
				</select>
			</td>
		</tr>
	</table>
</body>
<script type="text/javascript">
avalon.define({
	$id: 'test',
	col: [{name: 'id', type: 'text'}, {name: 'mode', type: 'select', option: {A: '类型一', B: '类型二'}}],
	row: [{id: '01', mode: 'A'}, {id: '02', mode: 'B'}]
});
avalon.scan();
</script>
</html>
````

修改text和select的值，会出现异常。
1.4.x好像没有这个问题的。

**Comment by RubyLouvre** [comment]
用得不对，row必须包含 col;

**Comment by juneryo** [comment]
row必须包含col？没大明白。。。
对于示例中的col，只是用来定义列的属性。
而row，可以看成是后台返回的结果集，结果集中包含col（列的定义）怎么都不太妥吧。
另外1.4.x支持，反而1.5.x不支持是出于什么考虑呢。

**Comment by RubyLouvre** [comment]
本来就不支持
是你们自己乱用，几重循环用几维数组，你这是分开两个数组

**Comment by juneryo** [comment]
好吧。。。如果不支持那也没办法。。。
不过两个数组的嵌套循环，内层循环需要取到外层循环的元素应该是个很常见的需求，对于这种需求有什么解决方案么。。。

**Comment by roscoe054** [comment]
@juneryo 可参考这个 [循环操作](http://www.html-js.com/article/Avalon-tutorial-11-circulating-operation)

**Comment by juneryo** [comment]
@roscoe054 
循环操作的教程其实很早就看过了，其中也有和这里一样的，对两个数组进行嵌套循环。
````
<div ms-controller="test">
    <div ms-repeat="num">
        <strong ms-repeat="data">
            {{el}}: {{$outer.el}}
        </strong>
    </div>
</div>
````
只是现在的情况是，循环出来的元素无法用到双向绑定上，或者这样循环根本就不对。

**Comment by scgy5555** [comment]
@juneryo 
<div ms-repeat-row="rows">
  <div ms-repeat-col="cols">
    {{row.type}}{{col.type}}
  </div>
<div>

**Comment by roscoe054** [comment]
@juneryo 可以绑定上啊，avalon版本1.5.6 http://jsfiddle.net/8w9pLohk/5/

**Comment by juneryo** [comment]
@roscoe054 不好意思哈  是我没描述清楚  值是可以显示出来  但是如果绑定到input上  修改input的值的时候  控制台里就会打印异常。
你提供的例子现在不方便看  一会儿看看。

**Comment by juneryo** [comment]
@scgy5555 替换el的名称对吧  谢了  这个倒还没想过  一会儿我试试  看看还会不会有异常。

**Comment by roscoe054** [comment]
@juneryo 加了input http://jsfiddle.net/8w9pLohk/6/

**Comment by juneryo** [comment]
@roscoe054 你的例子我测试过了，没问题。
不过我改了一下，把数组的内容变成对象，就不行了。
http://jsfiddle.net/8w9pLohk/7/

**Comment by juneryo** [comment]
@scgy5555 如果数组中的元素是对象，替换el的名称，绑定到input上，修改input时也是会异常的。

**Comment by anrip** [comment]
今天的版本已经解决此问题，请更新后尝试

**Comment by juneryo** [comment]
@anrip 好的，现在avalon2的git上版本还没更新，更新后我这里再试试。
