### ISSUE TITLE
1.5.5 监听的对象改造成了component

### ISSUE THREAD

**Issue by darcymzsun** [RubyLouvre/avalon#1208]
var vm = avalon.define({
                $id: "test",
                wordArray:[
                    {id: 1, name: "看英文选中文"},
                    {id: 2, name: "看中文选英文"},
                    {id: 3, name: "听音选中文"},
                    {id: 4, name: "听音写全拼"},
                    {id: 5, name: "看中文写全拼"},
                    {id: 6, name: "看图补全短语"}
                ]
            })

![qq 20151217145401](https://cloud.githubusercontent.com/assets/10953928/11863430/ba4ded5a-a4ce-11e5-87ce-e0216ead6acb.png)

**Comment by RubyLouvre** [comment]
是啊，Component其实就是一个VM
