### ISSUE TITLE
avalon mmState hash解析的兼容问题

### ISSUE THREAD

**Issue by tuxingsheng** [RubyLouvre/avalon#1211]
问题描述：
我有一个网址abc.com/pages/#!/login，如果是国内就需要解析成.cn，我想要的是abc.cn/pages/#!/login，实际上在某些手机浏览器（如：uc、微信）下，解析后变成了abc.cn/pages/，hash后面的url不见了，在手机版360浏览器中却能够正常解析出来

**Comment by RubyLouvre** [comment]
那是这些破浏览器的问题了，没法处理

**Comment by IndexXuan** [comment]
这和mmstate有啥关系？网址解析要不防在后台要么前台定向好才到avalon和mmstate接管，接管之前就丢了hash那自己想办法保存处理啊！
用mmstatezuole不少了，没发现有hash丢失问题，至少微信不丢

**Comment by RubyLouvre** [comment]
这个不太懂，到3群或5群问skipper
