### ISSUE TITLE
ie8 下avalon.bind后 ，avalon.unbind没起作用

### ISSUE THREAD

**Issue by ttt22703** [RubyLouvre/avalon#1217]
var arr = [
                [document, "click", function (e) {}]
];
avalon.bind(arr[0][0], arr[0][1], arr[0][2])
avalon.unbind(arr[0][0], arr[0][1], arr[0][2]);

**Comment by RubyLouvre** [comment]
用法不对，IE8下方法是被包装一次才能调用，因此需要移除bind 的返回 方法
```javascript
var remove = avalon.bind(elem, type, fn)
avalon.unbind(elem, type, remove)
```
