### ISSUE TITLE
CORS跨域问题。

### ISSUE THREAD

**Issue by dreamback** [RubyLouvre/avalon#1219]
尝试多次，1.5.x版
zepto,jquery 的ajax函数都支持cors跨域。
avalon，mmRequest内部ajax都不支持这方面的跨域请求（bugs），希望官方快解决。

**Comment by RubyLouvre** [comment]
这是后端处理！

**Comment by RubyLouvre** [comment]
https://github.com/RubyLouvre/mmRequest/blob/master/public/mmRequest.js#L708 源码已经添加上相应的请求头

**Comment by dreamback** [comment]
https://github.com/RubyLouvre/avalon/blob/master/dist/avalon.mobile.js#L2842
这里应该像mmRequest 里面那样。需要判断
```
if(!crossDomain)xhr.setRequestHeader("X-Requested-With", "XMLHttpRequest")
```
