### ISSUE TITLE
$watch 的行为不理想

### ISSUE THREAD

**Issue by wusfen** [RubyLouvre/avalon#1225]
![_yv149 3unr3_ 30 kiv6l](https://cloud.githubusercontent.com/assets/6390515/12061900/d40699e6-afcc-11e5-8464-15ba4df0c3a9.png)
![9ix6_l2ta__o v _ n jkbx](https://cloud.githubusercontent.com/assets/6390515/12061903/df917114-afcc-11e5-8977-f28de643dd45.png)

**Comment by RubyLouvre** [comment]
以后会处理

**Comment by woota** [comment]
@RubyLouvre 对于深层数据监听更变，有什么方法可以绕过去么？

**Comment by RubyLouvre** [comment]
不能，都是从最内层一直冒到最外层 实现的

**Comment by RubyLouvre** [comment]
等等吧，正在搞一个更好的实现
