### ISSUE TITLE
关于array的clear()的返回值的问题

### ISSUE THREAD

**Issue by yomefeeling** [RubyLouvre/avalon#1226]
v1.4.4
array.clear().pushArray([1,2,3]);
clear()返回的还是array，就可以链式操作

v1.5.5
array.clear().pushArray([1,2,3])
//Cannot read property 'array' of undefined
clear()返回的是undefined  所以无法进行链式操作

请问这是1.5.5版本就是这样改造的吗？
//目前的解决方法就是分开写
array.clear();
array.pushArray([1,2,3]);

**Comment by RubyLouvre** [comment]
这是我的大意

**Comment by RubyLouvre** [comment]
已经修复
