### ISSUE TITLE
关于1.5 新组件使用上感觉有功能能欠缺的地方

### ISSUE THREAD

**Issue by wangzf-no1** [RubyLouvre/avalon#1233]
http://runjs.cn/code/c54s7olz
组件我感觉使用上应该有自己的行为，组件内部处理行为逻辑，
对外只提供行为属性和方法，不参与组件逻辑等相关处理
比如：上面这个例子，组件对外提供add方法，内部则会处理相关逻辑（tip push）

目前我碰到的问题是：
组件内部无法准确获取vm 对象，这跟组件定义的方式有密切关系，
不知道是不是新版组件还没有开发完还是怎么地，

我目前是吧vm 保存到el上了
http://runjs.cn/code/xkigoytd

**Comment by Lostlover** [comment]
http://runjs.cn/code/xggliupw
你说的是这个意思吗

**Comment by wangzf-no1** [comment]
http://runjs.cn/code/bci2rh3h
大概是这样，
业务功能只关心 test controller，使用组件只关心组件提供的方法和属性，
具体其内部逻辑不关心，组件最好不要加id，组建多了之后维护也相当麻烦

**Comment by xiarugu** [comment]
强力支持, 我也一直觉得现有的组件定义方式使用起来很别扭.

**Comment by roscoe054** [comment]
组件中的方法可以先声明，然后在$init中再实现，这时是可以获取到vm的
https://github.com/RubyLouvre/avalon2/blob/master/component/spinner/avalon.spinner.js

**Comment by RubyLouvre** [comment]
过段时间 ,还在搞1.6

**Comment by wychurry** [comment]
var noop = function() {};
avalon.component("ms:alert", {
    show:false,
    msg: "",
    $replace: 1,
    close: noop,
    $init: function(vm){
        console.log(vm);
        vm.close = function(){
            vm.show = false;
        }
    },
    click: function(){
        console.log(this);
    },
    $template: heredoc(function(){
        /*
        <div class="alert_box" ms-class="{& show ? 'show':'' &}">
            <div class="alert alert-success alert-dismissible">
                <button type="button" ms-click="close" class="close">×</button>
                <h4><i class="icon fa fa-check"></i> Alert!</h4>
                {& msg &}
            </div>
        </div>
         */
    })
});
