### ISSUE TITLE
1.5.5版本无法监控定义好的class对象。

### ISSUE THREAD

**Issue by luqizheng** [RubyLouvre/avalon#1240]
请看 http://runjs.cn/detail/znitsjao
1.4.7 没有这个问题。

我预定义好一个 menu对象
<pre>
 function Menu(){
		this.name="";
		this.number="";
	 }
</pre>

然后定义好两个controller,test1, test2
* test1 用 {name:"",id:"", number:33"}
* test2 用  new Menu()

然后每隔一秒去更改test1和test2 的 number 属性。 test1能够正常更新，而 test2永远都是第一次赋值的值

**Comment by RubyLouvre** [comment]
你试败成普通对象，估计是isPlainObject方法过滤器了

**Comment by luqizheng** [comment]
我把它变成 普通对象是没有问题。就是自定义对象就无法监控。 查看 avalon.vmodels.test2.array[0].number 发现是一个普通的字符，而不是带有get/set的 对象。

**Comment by RubyLouvre** [comment]
你可以这样改

```
function Dog (obj){
   var instance = {}
   avalon.mix(instance, Dog.prototype)
   avalon.mix(instance, obj)
   return obj
}

Dog.proptotype = {
  xxx: 111
}
```
