### ISSUE TITLE
谁能找到avalon.controller的文档？谢谢了

### ISSUE THREAD

**Issue by lcsoftware** [RubyLouvre/avalon#1245]
谁能找到avalon.controller的文档？谢谢了

**Comment by Lostlover** [comment]
http://hotelued.qunar.com/oniui/index.html#!/widgets?widgetId=mmRouter&ex=doc
看看是需要这个吗

**Comment by IndexXuan** [comment]
这个几乎不需要了解，只在mmstate和mmrouter配合使用的具体视图里用，自动传入$ctrl参数，这个参数自身带有视图生命周期函数（不如页面onload）。具体可以在github上搜索mmRouter-list-demo项目

**Comment by lkiarest** [comment]
用法还是比较多的，不同的打包方式用法也不一样，所以还是要有个文档专门讲解下比较好
