### ISSUE TITLE
Windows 8.1 X64 下的 IE 11 ms-duplex 有问题

### ISSUE THREAD

**Issue by LancerComet** [RubyLouvre/avalon#1248]
现象为：
 - 中文输入法无法输入中文，微软拼音打开后会输入进去一堆字符且会被立刻清除；搜狗输入法会输入一堆空格；
 - 日文输入法无候选框；
 - 仅限 Windows 8.1 X64 的 IE11，Windows 10 无问题；
 - 1.4.5 之后的版本出现此问题；

此问题由多名用户反馈，使用 Hyper-V 安装 MSDN 纯净版 Windows 8.1 后验证重现。

**Comment by RubyLouvre** [comment]
http://www.ithome.com/html/win8/77473.htm
