### ISSUE TITLE
输入框，在已有的字符上面修改后光标会自动跳到最后

### ISSUE THREAD

**Issue by xxxlihui** [RubyLouvre/avalon#1249]

**Comment by RubyLouvre** [comment]
都没有指明是什么系统，什么浏览器，提供测试例子

**Comment by xxxlihui** [comment]
http://avalonjs.github.io/#home.html
10 秒钟看懂 avalon 这一节里第一个例子 的输入框，哪一个浏览器都会这样

**Comment by RubyLouvre** [comment]
这是版本问题，官网上的版本够旧的，换上新的就好了
