### ISSUE TITLE
avalon1.5 已经给ms-controller 增加了display:none样式，在chrome的34版本下，最后页面没有出来

### ISSUE THREAD

**Issue by wgq837051** [RubyLouvre/avalon#1251]
avalon1.5 已经给ms-controller 增加了display:none样式，在chrome的34版本下，最后页面没有出来，ms-controller没有改成display:block，重新加载页面就不会出现这种情况

**Comment by IndexXuan** [comment]
什么意思？页面因为你设置display没有出来，那为什么重新加载就没问题了？ms-controller正常的话会被框架scan，解析成avalonctrl=控制器名，如果加载了页面居然还有ms-controller就不对，肯定哪里错了，或者后期加载进来没手动scan这块区域。框架会在domready自动扫描一次，用了router等复杂后自己要手动avalon.scan（）一次，让avalon接管整个页面的控制。

**Comment by wgq837051** [comment]
给ms-controller增加display:none，就是让{{}}差值在页面展现时不显示，我是在jQuery的ready函数中加入avalon.define方法的，我加上avalon.scan（）方法，没有出现问题了。

**Comment by RubyLouvre** [comment]
它不会添加新的类名，只是将那个样式去掉
