### ISSUE TITLE
avalon教程->指令中ms-with中model.$watch("selected", function(v){});对于toLocaleString是否有误？

### ISSUE THREAD

**Issue by dingshijie** [RubyLouvre/avalon#1253]
原函数内容如下： 
model.$watch("selected", function(v) {
                var t = parseFloat(model.trend)
                model.data.sort(function(a, b) {
                    if (v === "name") {
                        return t * a[v].toLocaleString(b[v])
                    } else {
                        var ret = a[v] > b[v] ? 1 : -1
                        return t * ret
                    }
          })
 })
而这里实现的功能是对表格的排序，当选择的是name时，这里是否本意为安装name的值进行排序，这里的toLocaleString并不是排序的函数，排序的函数是localeCompare。
谢谢。

**Comment by RubyLouvre** [comment]
应该是写错了，在哪个页面，求地址

**Comment by dingshijie** [comment]
这个页面下
http://avalonjs.github.io/#tutorial/directives/repeat.html
![a](https://cloud.githubusercontent.com/assets/10086325/12574214/c3f9e240-c43c-11e5-84e3-a014ed3ed7d7.jpg)
