### ISSUE TITLE
npm仓库版本更新

### ISSUE THREAD

**Issue by woota** [RubyLouvre/avalon#1254]
为什么npm装包的版本才到0.1.9，而官网都到1.5.x了？

**Comment by avalonjs** [comment]
那个不是avalon的项目，那个名字被别人占了，avalon一直不能用npm安装

**Comment by woota** [comment]
@avalonjs 要不要支持一下npm呢？使用avalonjs之类的名称。那样包管理起来方便一点

**Comment by anrip** [comment]
稍后我制作一个，负责更新吧。

**Comment by woota** [comment]
@anrip 那个已经8个月没更新过了

**Comment by avalonjs** [comment]
那个已经被废掉,avalon2会支持后端渲染
