### ISSUE TITLE
avalon-1.5.5监听无效！

### ISSUE THREAD

**Issue by ahaiboa** [RubyLouvre/avalon#1257]
问题如下：

场景 - 监听于vm对象

1、对象曾经稍深（第二层对象、监听第三层【第二层对象的属性】）
![2016-01-28_110422](https://cloud.githubusercontent.com/assets/13414314/12633810/872e4ea4-c5af-11e5-94f2-ca8b01b9a5c3.png)

测试结果：

![2016-01-28_110501](https://cloud.githubusercontent.com/assets/13414314/12633821/8f97c3b8-c5af-11e5-934e-1f126cb65dda.png)

未进入监听方法。。

2、监听对象提到第一层，监听该对象属性（监听曾经第二层）
![qq 20160128110525](https://cloud.githubusercontent.com/assets/13414314/12633850/cb32e3c6-c5af-11e5-841e-744d8a861dbb.png)

测试结果：

![qq 20160128110538](https://cloud.githubusercontent.com/assets/13414314/12633865/e38ca4fc-c5af-11e5-83d4-f3f44985fbe4.png)

未进入监听方法。。

故，初步断定应该是avalon该版本（当然，以下版本还未测试过）监听有问题，望早日修复，且最好能支持多级监听，谢谢！！

**Comment by bluefox1688** [comment]
1.5.5版本的监听有点改动，这是官网的说明。
如果你想监听二级或三级对象的属性时，需要跑到avalon.define的外面，定位到目标属性的父对象上添加$watch回调。

`var model = avalon.define({
    $id: "test",
    data: {
        xxx: 222,
        yyy: 333
    }
})
model.data.$watch("xxx", function(a, b) {
    //................
})`
