### ISSUE TITLE
数据循环绑定ms-reapeat  起始偏移 循环长度 步进控制

### ISSUE THREAD

**Issue by HuoHun** [RubyLouvre/avalon#1259]
ms-repeat  中  添加些循环起始偏移 循环长度 步进控制

ms-repeat-offset="3"  从循环体第三个开始
ms-repeat-length ="5"  循环5条数据
ms-repeat-step = "3"    每次循环步进为3

**Comment by RubyLouvre** [comment]
没有意义！并且与　avalon现有规则冲突！

**Comment by HuoHun** [comment]
恩 ，看见1.6新的repeat功能了。

**Comment by RubyLouvre** [comment]
这个到时应该结合过滤器来实现
