### ISSUE TITLE
avalon.router.go 返回上一页，无法调用路由器配置

### ISSUE THREAD

**Issue by bluefox1688** [RubyLouvre/avalon#1261]
`avalon.router.go("detail",{
 	"goodsid":goodsid,
 	"who":Init.who
});`
以上是我通过avalon.router.go进入详细页的方式，可以成功的进入，也可以调用详细页的路由器配置，但是想返回上一页的时候，就会出现url的可以发现了变化，但是无法调用url对应的路由器配置。
然后如果再重新进入详细页，再返回上一页，又正常调用了上一页的路由器配置。

`<a ms-attr-href="#!/detail/<%= el.id %>/<%= who %>">测试</a>`
然后我测试了另一种方式，直接在html使用a链接进入详细页，也可以成功进入详细页，返回上一页，url也正常配置对应的路由器配置。

这里总结一下要反馈的问题
有使用avalon.router.go，返回上一页无法使用对应的路由器。
使用环境：
window 10，360极速浏览器，avalon 1.55版本，mmHistory.js 0.9版

**Comment by gogoyqj** [comment]
没看懂

**Comment by lkiarest** [comment]
使用navigate试试呢

**Comment by gogoyqj** [comment]
直接history.back()
