### ISSUE TITLE
avalon 不用ajax加载原始数据

### ISSUE THREAD

**Issue by xiongxt** [RubyLouvre/avalon#1265]
我看了很多MVVM框架，对于加载数据都是通过ajax加载，对于原始数据是通过模板的方式写在静态HTML文件里面的这种情况，就无法自动装载出来，请问avalon对于这种情况有解决的办法没有。
毕竟对于很多网站，要考虑到seo，不能把所有数据都通过ajax来获取。

**Comment by RubyLouvre** [comment]
http://avalonjs.github.io/#tutorial/engineering/seo.html avalon的论坛就是使用phantomjs实现的
