### ISSUE TITLE
问题报告

### ISSUE THREAD

**Issue by net027** [RubyLouvre/avalon#1270]
avalon-1.4.7.2
只要页面上存在 name="nodeType"的元素，无论这个元素是否在ms-controller的范围内，
avalon就会失效，控制台也没有任何提示信息，
比如在页面添加一个元素：<input type="radio" name="nodeType" />

**Comment by Lihuanghe** [comment]
没发现你说的问题：

http://lihuanghe.github.io/avalontest/test.html
