### ISSUE TITLE
官网上手机格式化的一个问题

### ISSUE THREAD

**Issue by nbin2008** [RubyLouvre/avalon#1271]
http://avalonjs.github.io/#tutorial/concepts/$watch.html
下面的demo，手机号码格式化。
问题描述：在官网上面，是正常运行的。拷贝在本地，会出现光标错位的情况，当我输入4个数字的时候，实际上 phone 的值已经是5位了，然后光标还在第四位上。一样的代码，官网上面是正常的，本地就有bug，找不到原因，1.4和1.5版本分别测试，还是有bug。

**Comment by RubyLouvre** [comment]
版本不对吗？

**Comment by RubyLouvre** [comment]
嗯，这个应该是使用1.4.×为宜。1.5.×的确有BUG
