### ISSUE TITLE
avalon1.55 组件在ie8以下浏览器与requirejs混用时无法解析

### ISSUE THREAD

**Issue by longlywork** [RubyLouvre/avalon#1275]
因为项目使用的是requirejs作为amd加载器，我下载了avalon的shim版本，照着https://github.com/RubyLouvre/avalon2/tree/master/component 上的例子改了下，发现用avalon自带的加载器组件在ie6-8解析ok，但用requirejs就无法解析

**Comment by RubyLouvre** [comment]
为什么啊？有什么错误

**Comment by RubyLouvre** [comment]
http://avalonjs.github.io/#tutorial/engineering/loader.html 看这里

**Comment by longlywork** [comment]
没有错误，我也按照规范来的，我打印了日志，我注册了一个ms:rating组件，ie8下的截图
1. 正常的
![s](https://cloud.githubusercontent.com/assets/7630878/13387816/8617f25e-def5-11e5-885d-73da62d69869.png)
2.requirejs的
![e](https://cloud.githubusercontent.com/assets/7630878/13387834/a8f0d8a4-def5-11e5-9499-92f878511f74.png)

**Comment by longlywork** [comment]
我写的demo，rating.html用avalon的加载器，rating1.html用的requirejs的加载器
[rating.zip](https://github.com/RubyLouvre/avalon/files/150475/rating.zip)

**Comment by RubyLouvre** [comment]
![image](https://cloud.githubusercontent.com/assets/190846/13389354/2cc68b90-df02-11e5-9759-2b5894e0391a.png)
这个很好解决，红色的部分写在页面的最上方，不用打包

**Comment by longlywork** [comment]
谢谢
