### ISSUE TITLE
ms-attr ms-hover等出现不能正常绑定，但是事件却绑定成功了，用的是1.45版本的avalon

### ISSUE THREAD

**Issue by xingxiulaoxian** [RubyLouvre/avalon#1278]
主要是ie8中会出现这种情况，一般都是attr这种属性会出现

这是出现这种情况时候的代码，这里是用的avalon.dialog的插件

    <DIV class=oni-dialog-btns>
     <INPUT class=tg_laber_btn type=button uuid="33" ms-attr-value="confirmName" ms-hover="oni-state-hover"> 
     <INPUT class=tg_laber_btn type=button uuid="34" ms-attr-value="cancelName">
   </DIV>

**Comment by RubyLouvre** [comment]
没有例子，无法处理
