### ISSUE TITLE
关于组件调用的遇到的问题。。。。

### ISSUE THREAD

**Issue by kaleys** [RubyLouvre/avalon#1287]
avalon里面的组件，如果组件对应的element在DOM里移除了，会对应的回收这个组件，即在avalon.vmodes里移除这个组件。

我在项目中遇到了如下问题：
我在A页面调用组件`<ms:sendsms $id="sendsmstest" data-disabled="true"></ms:sendsms>`，
然后用`avalon.router.go()`跳转到B页面，再马上再跳回到A页面
然后在A页面访问`avalon.vmodels['sendsmstest']`,是访问不到这个组件【多访问几次】
因为在从A跳转到B的时候，触发了avalon的回收机制，导致组件信息被销毁了

我想问如果想在A页面继续访问这个页面，除了将组件

的ID变成动态的还有没有好的方法

[测试代码地址](https://github.com/kaleys/testAvalon)

**Comment by RubyLouvre** [comment]
$dispose: Function 该组件被移出DOM树，并且元素不存在msRetain属性时的销毁回调, 传入vm与当前元素

**Comment by RubyLouvre** [comment]
http://avalonjs.github.io/#tutorial/component/index.html
