### ISSUE TITLE
duplex不能应用于富文本，怎么样实现对象与富文本值对应

### ISSUE THREAD

**Issue by dolphin0618** [RubyLouvre/avalon#1292]
duplex不能应用于富文本，怎么样可以做到让js对象的值，能随着富文本编辑器内容变化而更新
![yze 7whm07xtv47l0vioamj](https://cloud.githubusercontent.com/assets/8371743/13780611/2c595868-eafb-11e5-9261-b48401d63c98.jpg)

**Comment by RubyLouvre** [comment]
你的富文本编辑器是自己创建了另一个元素，来显示内容的，因此你必须 找一下这个编辑器插件有没有什么onChange之类的回调，在这个回调里面手动将你的编辑器的内容 同步到vm中

```javascript
vm.xxx = $(eidtor).html()
```
