### ISSUE TITLE
整体替换时候ViewModel上旧结构中没有个对象，视图层无法正常渲染

### ISSUE THREAD

**Issue by mougeli** [RubyLouvre/avalon#1293]
`<div ms-if='supports' ms-repeat='supports'>
    <ul class="table-view">
        <li class="table-view-cell media" ms-repeat='$val.modules'>
            <div class="media-body">
                {{$key}}
            </div>
            <div class='cell-tip-text' ms-if='$val&&$val.content'>
                {{$val.content}}
                <span style="float:right" ms-if='$val.timestamp&&$val.timestamp.updatedTime'>更新时间{{$val.timestamp.updatedTime * 1000|date('MM/dd HH:mm')}}</span>
            </div>
        </li>
    </ul>
</div>
define('ctrl/test', ["mmRequest", "avalon"], function () {
  var json1 = {
    schoolId: "1",
    supports: {
      edu: {
        modules: {
          lesson: {
            content: "Content-1",
            timestamp: {},
          },
          score: {
            content: "Content-2",
          }
        }
      }
    }
  };
  var json2 = {
    schoolId: "1",
    supports: {
      edu: {
        modules: {
          lesson: {
            content: "Content-1",
            timestamp: {
              updatedTime: 123456789
            }
          },
          score: {
            content: "Content-2",
            timestamp: {
              updatedTime: 123456789
            }
          }
        }
      }
    }
  };
  var ctrl = avalon.define({
    $id: "test",
    supports: {}
  });

  return avalon.controller(function ($ctrl) {
    $ctrl.$vmodels = [ctrl];
    $ctrl.$onEnter = function (param, rs, rj) {
      ctrl.supports = avalon.mix(true, {}, json1.supports);
      setTimeout(function () {
        ctrl.supports = avalon.mix(true, {}, json2.supports);
      }, 1000)
    };
  });
});
`

**Comment by RubyLouvre** [comment]
到3群或5群里找 skipper
