### ISSUE TITLE
1.55通配符是真的吗

### ISSUE THREAD

**Issue by cjz9032** [RubyLouvre/avalon#1298]
vm.data 
`vm.$watch('data.*.checked',function(){
debugger
})`

应该只是监测,watch时的状态, 
`vm.data.removeAt` 毫无反应

我能想到的解决方案是  `watch('data.length', reWatchChecked )`
但是reWatch也不知道怎么写
还是说要等1.6版本

**Comment by RubyLouvre** [comment]
没有代码，无法调试

**Comment by RubyLouvre** [comment]
你说的情况 1.5都支持啊，另1.6已经废掉了，现在全力开发2

**Comment by RubyLouvre** [comment]
你说的情况 1.5都支持啊，另1.6已经废掉了，现在全力开发2

**Comment by cjz9032** [comment]
http://jsbin.com/xijuxa/2/edit?html,js,console,output
 
`     //mock ajax---------重点
          setTimeout(function(){
            //一层
            vm.data=[{i:1,selected:true}]; //无用
            //二层
            //vm.data.push({i:3,selected:true});  //无用
            //vm.data.removeAt(1); 
          },3000);`

**Comment by RubyLouvre** [comment]
打不开啊，你能贴上来吗

**Comment by cjz9032** [comment]
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
 
  <script type="text/javascript" src="http://libs.baidu.com/jquery/1.8.3/jquery.js"></script> 
  <script src="//cdn.bootcss.com/avalon.js/1.5.5/avalon.js"></script>
      <script>
        avalon.library("mc") //这个东西必须跟挨着avalon库,并且放到head标签中 
        
        avalon.define({
    $id: "demoCtrl",
          $config:{
            data:[{i:1,selected:false},{i:2,selected:false}]
          }
          
});
    </script>
    
  
  <title>JS Bin</title>
</head>
  
<body ms-controller="demoCtrl">
   <mc:datagrid config="$config" ></mc:datagrid>
</body>
  <script>
    
     
 
    var _interface = function () { };
    avalon.component("mc:datagrid", {
        data: [], //数据源
        //外部事件
        onInit: _interface, //初始化接口
        //内部事件
        clickItem:  _interface, //初始化接口
        //内部接口
        //默认配置 
       $template: '<div><div ms-repeat-item="data" ms-click="clickItem($event,$index)">  {{item.i}} {{item.selected}}</div></div>',

        $replace: true,
        $construct: function (hooks, vmOpts, elemOpts) {
            var options = avalon.mix(hooks, vmOpts, elemOpts);
            return options; //返回VM的定义对象
        },
        $dispose: function (vm, elem) {
            elem.innerHTML = elem.textContent = "";
        },
        $init: function (vm, elem) { 
          //内部事件
          vm.clickItem=function(e,i){
             var state=!vm.data[i].selected;
             vm.setSelected(i,state);
          };
          //内部接口
          vm.setSelected=function(i,state){
             vm.data[i].selected=state;
          };
          
          
          //mock ajax---------重点
          setTimeout(function(){
            //一层
            //vm.data=[{i:1,selected:true}]; //change 没反应了
            //二层
            vm.data.push({i:3,selected:true});  //新增的change 没反应了,老的还有
            //vm.data.removeAt(1);  //这个当然change还是有的.压根没变什么
          },3000);
          
          
            //======= 观测方法 START =======//
          
            vm.$watch("data.*.selected", function (newVal, oldVal) {
                console.log('selected change');
            });
           
            //======= 观测方法 END =======//

        },
        $ready: function (vm, elem) {
            //初始化操作
            vm.onInit(vm, elem); //调用外部初始化函数
            vm.isInit = false;
            console.log("ready");
        }
    });

    var widget = avalon.components["mc:datagrid"];
    widget.regionals = {};

 
    
    </script>
</html>
