### ISSUE TITLE
avalon2.0出来后,还会继续维护1.x吗?

### ISSUE THREAD

**Issue by zhuxianbin** [RubyLouvre/avalon#1306]
avalon2.0会完全抛弃IE678吗?1.x会继续维护吗?
因为我觉得使用avalon的亮点在于兼容性与轻便,如果失去了这些,好像就没什么竞争力了,像vuejs这种可能会更轻便一些.
如果两套都维护的话.我建议效仿jquery3.0,从命名上都叫avalon2.0,缀词有所区分,这样起码还给开发者一些期待.

**Comment by RubyLouvre** [comment]
认真看readme

**Comment by RubyLouvre** [comment]
会的！avalon2会支持IE6
