### ISSUE TITLE
1.5 版本中循环 --> 修改Item对象 不会同步

### ISSUE THREAD

**Issue by avkojwer1** [RubyLouvre/avalon#1308]
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body ms-controller="test">
	{{data.aaa}}
	<ul>
		<li ms-repeat="data">{{$key}} -- {{$val}}</li>
	</ul>
	
	<ul>
		<li ms-repeat="array_1">{{el}}</li>
	</ul>

	<ul>
		<li ms-repeat="array_2">{{el.text}}</li>
	</ul>
	
	<button ms-click="click">click me</button>
<script src="http://cdn.bootcss.com/avalon.js/1.5.4/avalon.js"></script>
	<script type="text/javascript">
		

		var model = avalon.define({
				$id:"test",
				array_1:['葡萄','椰子','橙子','火龙果'],
				array_2:[
					{text:'a'},
					{text:'b'},
					{text:'c'}
				],
				data:{
					aaa:111,
					bbb:222,
					ccc:333,
					ddd:444
				},
				name:"123",
				click: function(){
					**model.data.aaa = 5555;    //无效**
					model.array_2[0].text = '99';  //有效
					**model.array_1[0] = '火龙果';   //无效**
				
				}
			});

	</script>
</body>
</html>

**Comment by RubyLouvre** [comment]
model.array_1[0] = '火龙果';   这个确定无效

**Comment by xiarugu** [comment]
直接对数组元素进行赋值是捕捉不到的, 建议的做法是用splice, 
或者
```
model.array_1.set(0, '火龙果');
model.array_2.set(0, { text: '99' });
```
