### ISSUE TITLE
ms-view能用effect吗

### ISSUE THREAD

**Issue by cjz9032** [RubyLouvre/avalon#1309]
还是说 直接onload回调中强行手动加动画效果的= =

**Comment by RubyLouvre** [comment]
1.5使用mmState来做

**Comment by gogoyqj** [comment]
https://github.com/gogoyqj/mmRouter-demo-list/tree/master/requirejs - 看这里

ms-view元素配置 oni-mmRouter-slide的class

然后配置 onEnterView在里面自己来控制
