### ISSUE TITLE
指令的update的在execHooks()中的调用思路

### ISSUE THREAD

**Issue by HuoHun** [RubyLouvre/avalon#1312]
指令部分的代码，
priority这样用的bindings.sort(byPriority)，
parse 这样用的directives[binding.type].parse(binding, num, elem)
diff这样用的directives[type].diff(current, previous || emptyObj, type, name)

update我没找到呢？？
execHooks()这里是如何调用到update()？？

**Comment by RubyLouvre** [comment]
在每个指令里面有添加update  的操作
```
 var list = cur.change || (cur.change = [])
                if(avalon.Array.ensure(list, this.update)){
                    steps.count += 1
                }  ```
