### ISSUE TITLE
教程avalon2学习教程08插入移除操作，示例错误

### ISSUE THREAD

**Issue by masktw** [RubyLouvre/avalon#1313]
我直接复制教程中的示例到本地，任意点击按钮1-》按钮2-》按钮1 控制台就会提示错误：TypeError: node.getElementsByTagName is not a function(…) "parse on binding【 @curIndex = i 】fail"

**Comment by RubyLouvre** [comment]
什么浏览器，下主干的再试一下

**Comment by masktw** [comment]
重新下的主干的，点击直接报以上错误。
360和chrome都是

**Comment by RubyLouvre** [comment]
那里有两个例子
都报错吗

**Comment by RubyLouvre** [comment]
你的链接对不，script标签引用avalon的 路径，我是好的

**Comment by RubyLouvre** [comment]
好了，应该是之前for循环优化过度出问题了
