### ISSUE TITLE
Avalon 2.0算正式发布了么？

### ISSUE THREAD

**Issue by cnx2016** [RubyLouvre/avalon#1319]
把打了‘2.0’Tag的代码拉取下来，随便写个简单的例子，在IE8中运行报错了。
[myFirstAvalon.html.txt](https://github.com/RubyLouvre/avalon/files/216623/myFirstAvalon.html.txt)

**Comment by RubyLouvre** [comment]
2.0TAG已经停止了，2.0直接放在主干上

**Comment by RubyLouvre** [comment]
还没有正式发布，现在是b2

**Comment by cnx2016** [comment]
Thanks for the reply.
