### ISSUE TITLE
ms-attr一个十分诡异的地方

### ISSUE THREAD

**Issue by cjz9032** [RubyLouvre/avalon#1320]
`            <mc:button ms-if="hasButton" config="$btn_opt"
                       ms-attr-str="{{JSON.stringify(el.$model)}}">
            </mc:button>`

为什么这个拿出来不是个str 而是el呢?

**Comment by RubyLouvre** [comment]
什么版本？1.5吗

**Comment by RubyLouvre** [comment]
ms-attr-str="JSON.stringify(el.$model)" 不是所有东西都要加花括号

**Comment by cjz9032** [comment]
1.5  加括号是因为我各种写法都试过了
没加括号取出来是object object这么一个衣服加了是。。手机打字好慢  我回去先

**Comment by cjz9032** [comment]
1.5  加括号是因为我各种写法都试过了
没加括号取出来是object object这么一个衣服加了是。。手机打字好慢  我回去先

**Comment by RubyLouvre** [comment]
不要加{{}}！！！
