### ISSUE TITLE
新版本avalonjs出现了双向绑定数据失效

### ISSUE THREAD

**Issue by muhouhuanghun** [RubyLouvre/avalon#1328]
使用了1.55的avalonjs，官方教程里面$watch最后一个例子失效了，无法限制号码长度不大于11，并且出现了光标前移的问题。而使用官方教程中引用的1.46的avalonjs文件则一切正常。

**Comment by RubyLouvre** [comment]
这个设置 
```
avalon.config({async: false})
```
