### ISSUE TITLE
关于遍历数据的问题

### ISSUE THREAD

**Issue by chen77134056** [RubyLouvre/avalon#1331]
我用的是1.5.6
arr:[
 ['ni11','wo11','ta11',{name:'chen',age:25}],
 ['ni22','wo22','ta22','haha22'],
 ['ni33','wo33','ta33','haha33']
]

我目的是用$watch监听修改age属性值后发生回调但是我用下面的代码不能执行回调

vm.$watch("arr.*.age",function(newvalue,oldvalue){ //失败
   //代码
});

但是我用1.4.x的写法就可以回调，我就想知道1.5.x的写法要怎么找到那个对象中的age属性

**Comment by RubyLouvre** [comment]
问题是你怎么 修改的
