### ISSUE TITLE
1.5版本，ie8直接调用model的方法的时候this是指向window的

### ISSUE THREAD

**Issue by wmlgl** [RubyLouvre/avalon#1350]
rt

**Comment by RubyLouvre** [comment]
这个在入门教程说了
VBScript中方法的中this不是指向VM

**Comment by wmlgl** [comment]
写了个1.4版本的插件， 会出现bingding的属性都变成null的情况，能帮看看不？
网站：http://wangcaiit.com/jimei/admin/index.html
插件js：http://wangcaiit.com/jimei/admin/app/lib/ms-component.js

插件是个组件加载器，组件定义在html里（控制器原型和html模版），然后通过ms-include-src把html文件加载到页面里，加载完成后通过Component.create方法创建并控制器和dom元素。

我还写了两个指令（ms-comp-bind-xxx,ms-comp-duplex-xxx）用来绑定组件和组件的属性, 里直接使用parseExprProxy也会出现上述情况，所以现在使用的$watch。

现在的问题出现在第二次切换“酒店管理”和“房单列表”的时候。
截图：http://pan.baidu.com/s/1c1NF1kc
酒店模版：http://wangcaiit.com/jimei/admin/app/HotelPage.html
房单模版：http://wangcaiit.com/jimei/admin/app/FolioPage.html
公用组件库：http://wangcaiit.com/jimei/admin/app/Component.html
