### ISSUE TITLE
avalon2 组件模板内如何设置 img a 这种含有属性的标签的默认值呢？

### ISSUE THREAD

**Issue by rayroad** [RubyLouvre/avalon#1351]
avalon2 组件模板内如何设置 img a 这种含有属性的标签的默认值呢？
我现在是直接给了个slot插槽 使用时再写相应的标签 有其他的方法么？

**Comment by RubyLouvre** [comment]
img a不是自定义标签，用不了slot;
不是有一个defaults对象吗
这里有一些例子

https://github.com/RubyLouvre/avalon/tree/master/perf
