### ISSUE TITLE
发现一个很奇怪的问题

### ISSUE THREAD

**Issue by rayroad** [RubyLouvre/avalon#1352]
![image](https://cloud.githubusercontent.com/assets/1949219/15103071/9bc75c1e-15d9-11e6-84e4-61cb9eb31ccc.png)
组建模板内 多个img标签之后如果没有一个slot标签 那么最后一个img元素不会被正确渲染

**Comment by rayroad** [comment]
且这个solt必须有值

**Comment by RubyLouvre** [comment]
`<img >` --> `<img />` 试试

还有，你的例子都不全，要一个完整可运行的短小页面啊！

**Comment by rayroad** [comment]
改<img /> 还是不行 完整例子如下
`<!DOCTYPE html>
<html>
  <head ms-controller="head-vm">
    <title>测试</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <script src="src/vendor/avalon/2/avalon.js"></script>
    <script>
      var tmpl = '<ms-thumbs>'+
                   '<div>'+
                     '<img ms-attr="{src:@thumbSrc}" />'+
                     '<img ms-attr="{src:@thumbSrc}" />'+
                     //'<span>{{@space}}</span>'+
                   '</div>'+
                 '</ms-thumbs>';
      avalon.component('ms-thumbs', {
        template: tmpl,
        defaults: {
          thumbSrc: './src/asset/images/enterprise-logo.png',
          space: ''
        }
      })
  
      var vm = avalon.define({
        $id: 'widget',
        config: {
          thumbSrc: './src/asset/images/doctor-photo.png'
        }
      })
  
    </script>
  </head>
  
  <body>
    <div ms-controller='widget' >
      <xmp ms-widget="[{is:'ms-thumbs'},@config]"></xmp>
    </div>
  </body>
</html>`

**Comment by RubyLouvre** [comment]
又修了

**Comment by rayroad** [comment]
这个问题可以了，凌晨还在工作，辛苦了！

**Comment by RubyLouvre** [comment]
已经完全修复了
