### ISSUE TITLE
mixinHooks 方法应该没有做低版本IE的hack

### ISSUE THREAD

**Issue by rayroad** [RubyLouvre/avalon#1353]
RT

**Comment by RubyLouvre** [comment]
已经修了，试一试

**Comment by rayroad** [comment]
基于今天凌晨发布版本的`dist/avalon.js`
在IE8环境下运行[#1352](https://github.com/RubyLouvre/avalon/issues/1352)内的例子
····
//第7275行
optionMixin[k].push(v)
//控制台报错 `SCRIPT438: 对象不支持“push”属性或方法`
//采用try方法跳过
try{
	optionMixin[k].push(v)
}catch(e){
	continue
}
//之后
//第7632行
keys[key] = obj[key]
//控制台报错 `SCRIPT438: 对象不支持此属性或方法`
//继续采用try方法跳过
try{
	keys[key] = obj[key]
}catch(e){
	continue
}
//之后
//第8388 - 8395行
window.parseVB('Class ' + className + body)
window.parseVB([
	'Function ' + className + 'Factory(a, b)', //创建实例并传入两个关键的参数
	'\tDim o',
	'\tSet o = (New ' + className + ')(a, b)',
	'\tSet ' + className + 'Factory = o',
	'End Function'
].join('\r\n'))

//控制台报错 `SCRIPT1041: 名称重定义`
····
这里就不清楚怎么办了
尝试注释掉`window.parseVB('Class ' + className + body)`
后边的8398行会报错`SCRIPT506: 类没有被定义: 'VBClass124454299247'`

**Comment by RubyLouvre** [comment]
已经修复了,改用hasOwnProperty搞定!
