### ISSUE TITLE
现在最新的2.0包括2.0s怎么让IE8跑起来？

### ISSUE THREAD

**Issue by terranc** [RubyLouvre/avalon#1354]
尝试了avalon.coding.me上的例子，在IE8上也不停的报fail。
求解。

**Comment by RubyLouvre** [comment]
哪一个啊？自己拷下来运行，不要直接运行官网！

**Comment by terranc** [comment]
`<!DOCTYPE html>
<html>
    <head>
        <title>first example</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="./dist/avalon.js"></script>
        <script>
            var vm = avalon.define({
                $id: "test",
                name: "司徒正美"
            })
        </script>
    </head>

    <body ms-controller="test">
        <input ms-duplex="@name">
        <p>Hello,{{@name}}!</p>
    </body>
</html>`

**Comment by RubyLouvre** [comment]
好了,想不到outerHTML在IE6-8下有BUG

**Comment by terranc** [comment]
貌似还是不行，用的现在master里最新的，代码依然是上面的，现在连那个fail报错也木有了

**Comment by RubyLouvre** [comment]
用今天的版本

**Comment by RubyLouvre** [comment]
应该开新ISSUE，给出可运行的例子

**Comment by terranc** [comment]
开始我也不清楚是新版本的问题还是之前就没改好，所以没新开
