### ISSUE TITLE
ms-for的data-for-rendered问题

### ISSUE THREAD

**Issue by braveCS** [RubyLouvre/avalon#1355]
avalon2里2个ms-for嵌套使用时，外部的ms-for的data-for-rendered触发的时候，内部的ms-for还没有渲染完成。想要在内部ms-for渲染完成后处理逻辑很捉急。  avalon1里的一些功能在avalon2找不到对等的功能，回调少了很多。 来自avalon新手。

**Comment by RubyLouvre** [comment]
你想干什么啊,又要混用其他库吗?
有例子吗?请贴完整的可运行短小页面!
