### ISSUE TITLE
目前的版本在win7-ie8下加载报错

### ISSUE THREAD

**Issue by bluedarker** [RubyLouvre/avalon#1357]
> 我是在微软提供的win7－ie8测试虚拟机上跑的，不过应该和系统环境无关

![e366aba8-a82f-4e62-b8fa-23ef20133d59](https://cloud.githubusercontent.com/assets/3773524/15153260/1b074728-170b-11e6-8d2a-f2c3dc7efcd6.jpg)

之前跑bootcdn上的最新版本也是报错，以为版本有问题换了git上的还是不行。
项目比较急看来只能换1.4稳定版了

**Comment by RubyLouvre** [comment]
什么版本？
