### ISSUE TITLE
1.4.6 版本，对象设置 {} 后，validate不起作用了

### ISSUE THREAD

**Issue by hitgou** [RubyLouvre/avalon#1362]
<form ms-controller="test" ms-widget="validation">
		<div style="width:200px; float:left;">
		    <input id="i1" ms-duplex-required="aaa['xxx']">
		    <p>{{aaa.xxx}}</p>
		</div>
	</form>

		    var test = avalon.define({
		    	$id: 'test',
		         aaa : {
		             xxx: "444",
		             yyy: "555"
		         }
                     });

            setTimeout(function() {
                avalon.vmodels.test.aaa = {};
                // avalon.scan();
                avalon.log("set time out");
            }, 3000);

**Comment by RubyLouvre** [comment]
当然没作用了，对象都被你清掉了
