### ISSUE TITLE
avalon2 ie8下ms-click 点击改变 ms-if状态有小bug

### ISSUE THREAD

**Issue by JSlife23** [RubyLouvre/avalon#1364]
var vm = avalon.define({
        $id:"infoWind",
        w:'',
        h:'',
        currentIndex:0,
        toggle:true,
        minWind:function(){
          if( this.w == 600 && this.h == 140) {
            this.w = 650;
            this.h = 150;
            this.toggle = true;
          }else{
            this.w = 600;
            this.h = 140;
            this.toggle = 'false';

          }

        },
        maxWind:function(){

            if( this.w == '100%'  ){
              this.w = 650;
              this.h = 150;
            }else{

              this.w = this.h  = '100%';
                this.toggle = true;
            }

        },
        tabSwitch:function(index){
          this.currentIndex = index
        }
    })

              <div class="toolbar clearfix">
                  <div class="tabSwitch fl">
                      <ul class="infoList" ms-if="@toggle == true" >
                          <li ms-class="{active:@currentIndex == 0}" ms-click="@tabSwitch(0)" > <a href="#">报警信息</a> </li>
                          <li ms-class="{active:@currentIndex == 1}"  ms-click="@tabSwitch(1)" > <a href="#">命令信息</a> </li>
                          <li ms-class="{active:@currentIndex == 2}" ms-click="@tabSwitch(2)" > <a href="#">设备信息</a> </li>
                      </ul>
                      <span ms-if="@toggle != true" >消息</span> 
                  </div>
                  <div class="controlSize fr">
                      <span href="#" ms-click="@minWind" >
                        <img src="./images/iw_min.gif" alt="" />
                      </span>
                      <span href="#" ms-click="@maxWind" >
                        <img src="./images/iw_max.gif" alt="" />
                      </span>
                  </div>

              </div>

**Comment by RubyLouvre** [comment]
this.toggle = 'false'; --->     this.toggle = false

**Comment by RubyLouvre** [comment]
你都不说明是什么BUG,贴一大堆代码上来 我真是醉了!
span 要用display: inline-block才能点击吧
minWind --> mminWindow吧, 哪有用一个单词作缩写wind是风的意思,不能缩写

```html
<!DOCTYPE html>
<html>
    <head>
        <title>TODO supply a title</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src='../dist/avalon.js'></script>
        <script>
            var vm = avalon.define({
                $id: "test",
                w: '',
                h: '',
                currentIndex: 0,
                toggle: true,
                minWind: function (e) {
                    e.preventDefault()
                      console.log("minWindow")
                    if (this.w == 600 && this.h == 140) {
                        this.w = 650;
                        this.h = 150;
                        this.toggle = true;
                    } else {
                        this.w = 600;
                        this.h = 140;
                        this.toggle = false

                    }

                },
                maxWind: function (e) {
                    e.preventDefault()
                    console.log('maxWindow')
                    if (this.w == '100%') {
                        this.w = 650;
                        this.h = 150;
                         this.toggle = false
                    } else {

                        this.w = this.h = '100%';
                        this.toggle = true;
                    }

                },
                tabSwitch: function (index) {
                    this.currentIndex = index
                }
            })
        </script>
    </head>
    <body>



        <div class="toolbar clearfix" ms-controller="test">
            <div class="tabSwitch fl">
                <ul class="infoList" ms-if="@toggle == true" >
                    <li ms-class="{active:@currentIndex == 0}" ms-click="@tabSwitch(0)" > <a href="#">报警信息</a> </li>
                    <li ms-class="{active:@currentIndex == 1}"  ms-click="@tabSwitch(1)" > <a href="#">命令信息</a> </li>
                    <li ms-class="{active:@currentIndex == 2}" ms-click="@tabSwitch(2)" > <a href="#">设备信息</a> </li>
                </ul>
                <span ms-if="@toggle != true" >消息</span> 
            </div>
            <div class="controlSize fr">
                <span href="#" ms-click="@minWind" style="display:inline-block" >
                    <img src="./images/iw_min.gif" alt="" />
                </span>
                <span href="#" ms-click="@maxWind" style="display:inline-block" >
                    <img src="./images/iw_max.gif" alt=""  />
                </span>
            </div>

        </div>
    </body>
</html>

```
