### ISSUE TITLE
问题 选项卡切换的时候第一条数据不更新

### ISSUE THREAD

**Issue by liuming1989** [RubyLouvre/avalon#1366]
做了一个简单的选项卡，用到了ms-repeat的数据更新，但是第一个选项卡的数据只有第一次更新，跳到第二个选项卡之后，再点击第一个选项卡，还保持第二个选项卡的数据
<!DOCTYPE html>
<html>
<head lang="zh-CN">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
   <script src="lib/js/avalon.js" type="text/javascript"></script>
    <title>vrPort</title>
</head>
<body>

<div class="vrPort_content">
        <div class="vrPort_row row" ms-controller="listFf">
            <div class="subTab">
                <header class="hd clearfix">
                    <ul>
                        <li ms-class="{{service}}"  ms-click="changeUl(1)"><div>我们的服务</div></li>
                        <li ms-class="{{sell}}"     ms-click="changeUl(2)"><div>我要卖房</div></li>
                        <li ms-class="{{buy_title}}" ms-click="changeUl(3)"><div>我要买房</div></li>
                    </ul>
                </header>
            </div>
            <div class="desc_above">
                <ul>
                    <li class="" ms-repeat="infoListFf" ms-mouseover="changeW(el)" style="margin-bottom: 15px">
                       
                        <div class="desc" style="display: table;">
                            <div class="row0">
                                <h4>{{el.title}}</h4>
                                <p>{{el.desc}}</p>
                            </div>
                        </div>
                    </li>

                </ul>
            </div>
        </div>
    </div>

<script>
       //服务页面的控制
        var Fu = [
            {"id": "1", "desc": "123", "src": "image/service/f_mianfei.png", "title": ""},
            {"id": "2", "desc": "123", "src": "image/service/f_moni.png", "title": ""},
            {"id": "3", "desc": "123", "src": "image/service/f_gongxiang.png", "title": ""},
            {"id": "4", "desc": "123", "src": "image/service/f_dajian.png", "title": ""},
            {"id": "5", "desc": "123", "src": "image/service/f_ronghe.png", "title": ""},
            {"id": "6", "desc": "123", "src": "image/service/f_anquan.png", "title": ""}
        ];
        var buy = [
            {"id": "1", "desc": "456", "src": "image/sell/m_tuiguang.png", "title": ""},
            {"id": "2", "desc": "456", "src": "image/sell/m_wuxu.png", "title": ""},
            {"id": "3", "desc": "456", "src": "image/sell/m_baituo.png", "title": ""},
            {"id": "4", "desc": "456", "src": "image/sell/m_dichengben.png", "title": ""},
            {"id": "5", "desc": "456", "src": "image/sell/m_suishi.png", "title": ""},
            {"id": "6", "desc": "456", "src": "image/sell/m_quanjing.png", "title": ""}
        ];
        var mai = [
            {"id": "1", "desc": "789", "src": "image/buy/b_haokanfang.png", "title": ""},
            {"id": "2", "desc": "789", "src": "image/buy/b_chenjin.png", "title": ""},
            {"id": "3", "desc": "789", "src": "image/buy/b_zubuchuhu.png", "title": ""},
            {"id": "4", "desc": "789", "src": "image/buy/b_zhuangxiu.png", "title": ""},
            {"id": "5", "desc": "789", "src": "image/buy/b_butie.png", "title": ""},
            {"id": "6", "desc": "789", "src": "image/buy/b_shoucang.png", "title": ""}
        ];
        var vmF = avalon.define({
            $id: "listFf",
            Fu: Fu,
            buy:buy,
            mai:mai,
            service:"on",
            sell:"",
            buy_title:"",
            infoListFf: Fu,
            changeUl: function (flag) {
                if (flag==1) {
                 
                    vmF.infoListFf = Fu;
                } else if(flag==2) {
                
                    vmF.infoListFf = buy;
                }else{
                  
                    vmF.infoListFf = mai;
                }
            },
            changeW:function(el){
             
            }

        });
        avalon.scan();

</script>

</body>

</html>

**Comment by RubyLouvre** [comment]
？例子呢？

**Comment by liuming1989** [comment]
[Uploading demo.zip…]()

**Comment by liuming1989** [comment]
<!DOCTYPE html>
<html>
<head lang="zh-CN">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
   <script src="lib/js/avalon.js" type="text/javascript"></script>
    <title>vrPort</title>
</head>
<body>

<div class="vrPort_content">
        <div class="vrPort_row row" ms-controller="listFf">
            <div class="subTab">
                <header class="hd clearfix">
                    <ul>
                        <li ms-class="{{service}}"  ms-click="changeUl(1)"><div>我们的服务</div></li>
                        <li ms-class="{{sell}}"     ms-click="changeUl(2)"><div>我要卖房</div></li>
                        <li ms-class="{{buy_title}}" ms-click="changeUl(3)"><div>我要买房</div></li>
                    </ul>
                </header>
            </div>
            <div class="desc_above">
                <ul>
                    <li class="" ms-repeat="infoListFf" ms-mouseover="changeW(el)" style="margin-bottom: 15px">
                       
                        <div class="desc" style="display: table;">
                            <div class="row0">
                                <h4>{{el.title}}</h4>
                                <p>{{el.desc}}</p>
                            </div>
                        </div>
                    </li>

                </ul>
            </div>
        </div>
    </div>



<script>
       //服务页面的控制
        var Fu = [
            {"id": "1", "desc": "123", "src": "image/service/f_mianfei.png", "title": ""},
            {"id": "2", "desc": "123", "src": "image/service/f_moni.png", "title": ""},
            {"id": "3", "desc": "123", "src": "image/service/f_gongxiang.png", "title": ""},
            {"id": "4", "desc": "123", "src": "image/service/f_dajian.png", "title": ""},
            {"id": "5", "desc": "123", "src": "image/service/f_ronghe.png", "title": ""},
            {"id": "6", "desc": "123", "src": "image/service/f_anquan.png", "title": ""}
        ];
        var buy = [
            {"id": "1", "desc": "456", "src": "image/sell/m_tuiguang.png", "title": ""},
            {"id": "2", "desc": "456", "src": "image/sell/m_wuxu.png", "title": ""},
            {"id": "3", "desc": "456", "src": "image/sell/m_baituo.png", "title": ""},
            {"id": "4", "desc": "456", "src": "image/sell/m_dichengben.png", "title": ""},
            {"id": "5", "desc": "456", "src": "image/sell/m_suishi.png", "title": ""},
            {"id": "6", "desc": "456", "src": "image/sell/m_quanjing.png", "title": ""}
        ];
        var mai = [
            {"id": "1", "desc": "789", "src": "image/buy/b_haokanfang.png", "title": ""},
            {"id": "2", "desc": "789", "src": "image/buy/b_chenjin.png", "title": ""},
            {"id": "3", "desc": "789", "src": "image/buy/b_zubuchuhu.png", "title": ""},
            {"id": "4", "desc": "789", "src": "image/buy/b_zhuangxiu.png", "title": ""},
            {"id": "5", "desc": "789", "src": "image/buy/b_butie.png", "title": ""},
            {"id": "6", "desc": "789", "src": "image/buy/b_shoucang.png", "title": ""}
        ];
        var vmF = avalon.define({
            $id: "listFf",
            Fu: Fu,
            buy:buy,
            mai:mai,
            service:"on",
            sell:"",
            buy_title:"",
            infoListFf: Fu,
            changeUl: function (flag) {
                if (flag==1) {
                 
                    vmF.infoListFf = Fu;
                } else if(flag==2) {
                
                    vmF.infoListFf = buy;
                }else{
                  
                    vmF.infoListFf = mai;
                }
            },
            changeW:function(el){
             
            }

        });
        avalon.scan();

</script>

</body>

</html>

**Comment by liuming1989** [comment]
<!DOCTYPE html>
<html>
<head lang="zh-CN">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
   <script src="lib/js/avalon.js" type="text/javascript"></script>
    <title>vrPort</title>
</head>
<body>

<div class="vrPort_content">
        <div class="vrPort_row row" ms-controller="listFf">
            <div class="subTab">
                <header class="hd clearfix">
                    <ul>
                        <li ms-class="{{service}}"  ms-click="changeUl(1)"><div>我们的服务</div></li>
                        <li ms-class="{{sell}}"     ms-click="changeUl(2)"><div>我要卖房</div></li>
                        <li ms-class="{{buy_title}}" ms-click="changeUl(3)"><div>我要买房</div></li>
                    </ul>
                </header>
            </div>
            <div class="desc_above">
                <ul>
                    <li class="" ms-repeat="infoListFf" ms-mouseover="changeW(el)" style="margin-bottom: 15px">
                       
                        <div class="desc" style="display: table;">
                            <div class="row0">
                                <h4>{{el.title}}</h4>
                                <p>{{el.desc}}</p>
                            </div>
                        </div>
                    </li>

                </ul>
            </div>
        </div>
    </div>



<script>
       //服务页面的控制
        var Fu = [
            {"id": "1", "desc": "123", "src": "image/service/f_mianfei.png", "title": ""},
            {"id": "2", "desc": "123", "src": "image/service/f_moni.png", "title": ""},
            {"id": "3", "desc": "123", "src": "image/service/f_gongxiang.png", "title": ""},
            {"id": "4", "desc": "123", "src": "image/service/f_dajian.png", "title": ""},
            {"id": "5", "desc": "123", "src": "image/service/f_ronghe.png", "title": ""},
            {"id": "6", "desc": "123", "src": "image/service/f_anquan.png", "title": ""}
        ];
        var buy = [
            {"id": "1", "desc": "456", "src": "image/sell/m_tuiguang.png", "title": ""},
            {"id": "2", "desc": "456", "src": "image/sell/m_wuxu.png", "title": ""},
            {"id": "3", "desc": "456", "src": "image/sell/m_baituo.png", "title": ""},
            {"id": "4", "desc": "456", "src": "image/sell/m_dichengben.png", "title": ""},
            {"id": "5", "desc": "456", "src": "image/sell/m_suishi.png", "title": ""},
            {"id": "6", "desc": "456", "src": "image/sell/m_quanjing.png", "title": ""}
        ];
        var mai = [
            {"id": "1", "desc": "789", "src": "image/buy/b_haokanfang.png", "title": ""},
            {"id": "2", "desc": "789", "src": "image/buy/b_chenjin.png", "title": ""},
            {"id": "3", "desc": "789", "src": "image/buy/b_zubuchuhu.png", "title": ""},
            {"id": "4", "desc": "789", "src": "image/buy/b_zhuangxiu.png", "title": ""},
            {"id": "5", "desc": "789", "src": "image/buy/b_butie.png", "title": ""},
            {"id": "6", "desc": "789", "src": "image/buy/b_shoucang.png", "title": ""}
        ];
        var vmF = avalon.define({
            $id: "listFf",
            Fu: Fu,
            buy:buy,
            mai:mai,
            service:"on",
            sell:"",
            buy_title:"",
            infoListFf: Fu,
            changeUl: function (flag) {
                if (flag==1) {
                 
                    vmF.infoListFf = Fu;
                } else if(flag==2) {
                
                    vmF.infoListFf = buy;
                }else{
                  
                    vmF.infoListFf = mai;
                }
            },
            changeW:function(el){
             
            }

        });
        avalon.scan();

</script>

</body>

</html>

**Comment by liuming1989** [comment]
例子
<!DOCTYPE html>
<html>
<head lang="zh-CN">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
   <script src="lib/js/avalon.js" type="text/javascript"></script>
    <title>vrPort</title>
</head>
<body>

<div class="vrPort_content">
        <div class="vrPort_row row" ms-controller="listFf">
            <div class="subTab">
                <header class="hd clearfix">
                    <ul>
                        <li ms-class="{{service}}"  ms-click="changeUl(1)"><div>我们的服务</div></li>
                        <li ms-class="{{sell}}"     ms-click="changeUl(2)"><div>我要卖房</div></li>
                        <li ms-class="{{buy_title}}" ms-click="changeUl(3)"><div>我要买房</div></li>
                    </ul>
                </header>
            </div>
            <div class="desc_above">
                <ul>
                    <li class="" ms-repeat="infoListFf" ms-mouseover="changeW(el)" style="margin-bottom: 15px">
                       
                        <div class="desc" style="display: table;">
                            <div class="row0">
                                <h4>{{el.title}}</h4>
                                <p>{{el.desc}}</p>
                            </div>
                        </div>
                    </li>

                </ul>
            </div>
        </div>
    </div>



<script>
       //服务页面的控制
        var Fu = [
            {"id": "1", "desc": "123", "src": "image/service/f_mianfei.png", "title": ""},
            {"id": "2", "desc": "123", "src": "image/service/f_moni.png", "title": ""},
            {"id": "3", "desc": "123", "src": "image/service/f_gongxiang.png", "title": ""},
            {"id": "4", "desc": "123", "src": "image/service/f_dajian.png", "title": ""},
            {"id": "5", "desc": "123", "src": "image/service/f_ronghe.png", "title": ""},
            {"id": "6", "desc": "123", "src": "image/service/f_anquan.png", "title": ""}
        ];
        var buy = [
            {"id": "1", "desc": "456", "src": "image/sell/m_tuiguang.png", "title": ""},
            {"id": "2", "desc": "456", "src": "image/sell/m_wuxu.png", "title": ""},
            {"id": "3", "desc": "456", "src": "image/sell/m_baituo.png", "title": ""},
            {"id": "4", "desc": "456", "src": "image/sell/m_dichengben.png", "title": ""},
            {"id": "5", "desc": "456", "src": "image/sell/m_suishi.png", "title": ""},
            {"id": "6", "desc": "456", "src": "image/sell/m_quanjing.png", "title": ""}
        ];
        var mai = [
            {"id": "1", "desc": "789", "src": "image/buy/b_haokanfang.png", "title": ""},
            {"id": "2", "desc": "789", "src": "image/buy/b_chenjin.png", "title": ""},
            {"id": "3", "desc": "789", "src": "image/buy/b_zubuchuhu.png", "title": ""},
            {"id": "4", "desc": "789", "src": "image/buy/b_zhuangxiu.png", "title": ""},
            {"id": "5", "desc": "789", "src": "image/buy/b_butie.png", "title": ""},
            {"id": "6", "desc": "789", "src": "image/buy/b_shoucang.png", "title": ""}
        ];
        var vmF = avalon.define({
            $id: "listFf",
            Fu: Fu,
            buy:buy,
            mai:mai,
            service:"on",
            sell:"",
            buy_title:"",
            infoListFf: Fu,
            changeUl: function (flag) {
                if (flag==1) {
                 
                    vmF.infoListFf = Fu;
                } else if(flag==2) {
                
                    vmF.infoListFf = buy;
                }else{
                  
                    vmF.infoListFf = mai;
                }
            },
            changeW:function(el){
             
            }

        });
        avalon.scan();

</script>

</body>

</html>
