### ISSUE TITLE
版本 2.0.1

### ISSUE THREAD

**Issue by linjia06** [RubyLouvre/avalon#1368]
在这个版本下 ms-duplex 指令 ，在输入法  中文（简体，中国）微软拼音  下没能双向同步（绑定），搜狗中文输入法可以双向绑定，IE11 浏览器下出现，谷歌、火狐浏览器正常！

**Comment by RubyLouvre** [comment]
IE11不支持微软拼音，这个问题好久了！我搞不清为什么不同步，那东西太怪了。

**Comment by RubyLouvre** [comment]
微软拼音好像才会触发compositionstart 不会触发compositionend，没救，但我又无法知道用户是用什么拼音输入法

**Comment by linjia06** [comment]
在IE11 微软中文拼音 输入法下 ，文本框中是可以输入 中文文字的！
谢谢司徒大大的答复！

**Comment by RubyLouvre** [comment]
当然可以输入，但无法监听，微软总是出BUG

**Comment by linjia06** [comment]
刚刚试了一下  1.4.7.2 这个版本，ms-duplex 在IE11 下  用微软中文输入法  是可以 双向同步的！ 
用的 src="//cdn.bootcss.com/avalon.js/1.4.7.2/avalon.js"  这个引用！

**Comment by RubyLouvre** [comment]
好吧，我那在IE下就不用compositionstart,
