### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by gwhzh21** [RubyLouvre/avalon#1369]
例子http://avalonjs.coding.me/cn/doc.html
输入内容后回车，勾选所有，会不停的打勾取消，打勾取消。checkOne事件反复的执行。

**Comment by RubyLouvre** [comment]
应该是class绑定报错引起的, 明天再测则

**Comment by gwhzh21** [comment]
依然如故。

**Comment by RubyLouvre** [comment]
已经修复！
