### ISSUE TITLE
1.5版本，变量赋值出现问题

### ISSUE THREAD

**Issue by iamllitog** [RubyLouvre/avalon#1373]
![image](https://cloud.githubusercontent.com/assets/6738756/15416257/e2c78be8-1e7b-11e6-87ce-680d3c25c0b0.png)
infoListFf 首次赋值Fu可以成功，但是Fu值被改变了，导致第二次执行changeUl(1)失败，详情https://github.com/liuming1989/demo.git

**Comment by iamllitog** [comment]
![image](https://cloud.githubusercontent.com/assets/6738756/15416305/7b92b0c8-1e7c-11e6-95da-6b20c5f072bf.png)
这样到是可以成功的

**Comment by RubyLouvre** [comment]
Fu是什么鬼啊？vmFn.infoListFf.clear().pushArray(Fu)，为什么要重复赋相同的东西

对你的变量命名无言了

**Comment by iamllitog** [comment]
:(又不是我写的代码，只是帮小朋友提问题
