### ISSUE TITLE
使用require的text插件加载html代码模板片段运用到组件之中，绑定的数据都无法生效

### ISSUE THREAD

**Issue by UncleYuan** [RubyLouvre/avalon#1375]
avalon 做组件的时候，直接用html字符串的设置template属性十分不方便  [](于是使用require的text插件加载html代码模板，但是在chrome下一切正常，ie8下初始的数据还是生效的，但是双向数据的绑定已经失效。如链接所示：[https://www.baochoudai.com/avalonForm/form.html](https://www.baochoudai.com/avalonForm/form.html)

**Comment by bluedarker** [comment]
是不是用的cdn的，自己打包master主线代码吧。我前两天也出过一样的问题

**Comment by RubyLouvre** [comment]
升级到https://github.com/RubyLouvre/avalon/tree/2.0.2/dist 这里的版本试试，另，请使用webpack 进行打包
