### ISSUE TITLE
组件在IE8下仍然是使用IE6.7的polling方式销毁

### ISSUE THREAD

**Issue by bluedarker** [RubyLouvre/avalon#1378]
> window.Node我这边win7-IE8虚拟机下测试也不是function，也没看到你本次提交有定义。我更新打包测试也是使用polling方式销毁

**Comment by RubyLouvre** [comment]
IE6-8都是polling，因为IE6－7没有暴露Node, Element, HTMLElement等元素构造器，而IE8只暴露了Elememnt与HTMLElement构造器，但其原型只能添加新方法，不能覆盖已有方法！
