### ISSUE TITLE
求ms-js的正确使用方式

### ISSUE THREAD

**Issue by gwhzh21** [RubyLouvre/avalon#1382]
`<head>`
`<script>`
`var vm = avalon.define({`
`            $id:'test',`
   `         tpl: '<div><a href="#/ms-header">ms-header</a></div>',`
  `          dialogtpls:[],`
 `           opendialog: function (hash) {`
`                vm.dialogtpls.push('<div><' + hash + ' ms-widget=\"{$id:"' + hash + '",cached: true}\"></' + hash + '></div>');`
      `      },`
     `       showpage: function (hash) {`
    `            vm.tpl = '<div><' + hash + ' ms-widget=\"{$id:"' + hash + '",cached: true}\"></' + hash + '></div>';`
     `       },`
    `        closedialog: function () {`
   `             vm.dialogtpls.pop();`
  `          }`
 `       });`
`</script>`
`</head>`
`<body ms-controller="test" style="position:relative">`
`<ul>`
 `       <li><a ms-click="@showpage('ms-pager')">显示一层</a></li>`
`</ul>`
`<div class="showdialog">`
  `      <!--ms-for:($index,el) in @dialogtpls -->`
 `       <!--ms-js:var $first = $index === 0 -->`
`        <div ms-html="el"></div>`
        `<div ms-if="$first">{{$index}}</div>`
        `<!--ms-for-end:-->`
    `</div>`
`</body>`
显示一层单击之后，出现message: "Cannot read property 'nodeType' of undefined"，去掉
ms-js:var这段，一切正常。是否我的使用方式有问题？

**Comment by RubyLouvre** [comment]
ms-js已经删掉，发现这个东西太可怕了

**Comment by RubyLouvre** [comment]
![image](https://cloud.githubusercontent.com/assets/190846/15463260/b814d528-20fa-11e6-9681-19f4171f3c43.png)


![image](https://cloud.githubusercontent.com/assets/190846/15463272/d8e2337c-20fa-11e6-9618-221a3ddb2523.png)
http://avalonjs.coding.me/cn/doc.html#directive_prop
