### ISSUE TITLE
大家有用swiper插件吗？是怎么用的呢？

### ISSUE THREAD

**Issue by Jason7Le** [RubyLouvre/avalon#1387]

**Comment by gwhzh21** [comment]
https://segmentfault.com/a/1190000002962202

**Comment by Jason7Le** [comment]
`swiper初始化时直接写扫描的上面吗？：`var mySwiper = new Swiper('.swiper-container', {
                        autoplay: 2000,
                        loop: true,
                        observer: true,//修改swiper自己或子元素时，自动初始化swiper
                        observeParents: true,//修改swiper的父元素时，自动初始化swiper
                        pagination : '.swiper-pagination',
                        paginationType : 'fraction',
                    });

                vm.active_flag = "shop";
                avalon.scan();``

**Comment by Jason7Le** [comment]
![5555](https://cloud.githubusercontent.com/assets/12834229/15494705/85019bf2-21be-11e6-88b2-d0e47684c482.png)

**Comment by RubyLouvre** [comment]
没有用过，并且avalon2也不能与操作DOM的UI这样，涉及操作DOM的部分，需要在组件的onReady中处理
