### ISSUE TITLE
avalon.mobile，如何使用默认的onclick

### ISSUE THREAD

**Issue by linkFly6** [RubyLouvre/avalon#1393]
avalon在mobile上好像用touchStart来模拟click，现在遇到移动端一个上传图片的问题：
```HTML
<label for="upload" ></label>
<input accept="image/*"  type="file" style="display:none;" id="upload"/>
```
点击`label`的时候在正常情况下会通过`for`属性关联到`input[type=file]`上，但因为avalon.mobile直接接管了click，导致for关联并不生效。

请问有什么好的方案可以解决这个问题么？

我大概记得avalon.mobile的实现好像就是使用`touchStart`，如果描述有误，烦请指点。

**Comment by RubyLouvre** [comment]
不能吧，移动端上使用ms-on-tap事件
