### ISSUE TITLE
2.0网址的例子在IE下无法工作.

### ISSUE THREAD

**Issue by alanthinker** [RubyLouvre/avalon#1395]
http://avalonjs.coding.me/cn/doc.html 的双向绑定示例中 html tag 没有闭合. 
该网址的例子好像在IE下也无法工作. 不知道还有没有其他错误原因.

用户代码不正确时, 框架如果能给出相应的错误提示就更好了.

**Comment by RubyLouvre** [comment]
已经修正了;
