### ISSUE TITLE
IE-edge下input输入框绑定ms-duplex，无法拿到input数据的问题

### ISSUE THREAD

**Issue by wtagain** [RubyLouvre/avalon#1398]
引用的avalon.js及html如下

[test.zip](https://github.com/RubyLouvre/avalon/files/286169/test.zip)

avalon为[官网](http://avalonjs.github.io/#about)下载的最新版本

在ie edge下打开test.html，edge版本25.10586.0.0

正常情况如下:
![22](https://cloud.githubusercontent.com/assets/8341761/15603904/f8cceac8-242f-11e6-87ca-7c83b60abe3e.png)

切换成中文输入法，输入asd，不选择中文，直接回车
![33](https://cloud.githubusercontent.com/assets/8341761/15603907/fd90a356-242f-11e6-8fb5-6abfa3b7da98.png)

无法获得正确的输入结果
![44](https://cloud.githubusercontent.com/assets/8341761/15603919/09d17cd0-2430-11e6-874a-bc8dd74b310a.png)

**Comment by RubyLouvre** [comment]
这是avalon1.5吧，这个没有办法搞定，后来avalon2使用虚拟DOM才能搞定！
