### ISSUE TITLE
IE8 报 SCRIPT5007: 无法获取未定义或 null 引用的属性“display”

### ISSUE THREAD

**Issue by byends** [RubyLouvre/avalon#1402]
多个组件打包成一个组件的时候报错

有几个文件，所以zip了一下，放在微云了

[avalon2_IE8_Bug](http://share.weiyun.com/aca36987c6181d154f1501ab83f5f1bf)

**Comment by RubyLouvre** [comment]
周一看

**Comment by RubyLouvre** [comment]
这BＵＧ比较难修，请耐心l；或者这东西是不是只　有打包后才出错，打包前没错？

**Comment by byends** [comment]
刚试了下，多个组件不打包也是报一样的错

**Comment by RubyLouvre** [comment]
这个再更新一下试试

**Comment by RubyLouvre** [comment]
不会这个，拆开markdown!
