### ISSUE TITLE
初始化web组件的问题

### ISSUE THREAD

**Issue by virusdefender** [RubyLouvre/avalon#1404]
avalon 版本1.5

ms-include的时候，如果这个模板已经加载过，那这个模板中的vm就已经存在了，不需要再重新声明了。但是模板中里面的web组件不是，每次都会重新初始化，执行`init`和`ready`方法。

这个可以设置不重新初始化么？因为我写了一个翻页组件，重新初始化后，之前的页码数据就丢失了。

**Comment by RubyLouvre** [comment]
自己 加if分支判定;
