### ISSUE TITLE
ms-for and ms-if

### ISSUE THREAD

**Issue by muweigg** [RubyLouvre/avalon#1405]
> `<table ms-controller="test">
    
    <tr><td>{{index}}</td><td>{{el}}</td></tr>
    
</table>`

这样使用貌似不行，只能用下面的方式：

> `<table ms-controller="test">
        <tr ms-for="(index, el) in @data"><td>{{index}}</td><td>{{el}}</td></tr>
    </table>`

ms-if 是否支持注解的写法，比喻：

> `

`

avalon 2.x 是否能添加这样的功能？

**Comment by RubyLouvre** [comment]
不能
