### ISSUE TITLE
avalon.vmodels的缓存问题（error:[test] had defined）

### ISSUE THREAD

**Issue by kimmy0109** [RubyLouvre/avalon#1407]
我们公司的spa框架是通过ajax局部刷新来添加html页面到制定工作区域的，在使用2.0版本时发现添加一张由avan构建的界面（在官网中的hello，司徒正美得用例）
第一次加载时一切正常，当第二次加载会报error:[test] had defined!，而在1.5版本中没有这个问题。比较了下2个版本的define方法2.0可能对于vm做了缓存并做了判断而1.5没有。

**Comment by RubyLouvre** [comment]
就是已经定义了
你不要重复定义test
