### ISSUE TITLE
为什么require文件的时候要添加http或者https协议

### ISSUE THREAD

**Issue by wxxcarl** [RubyLouvre/avalon#1408]
<pre><code>require.config({
  paths: {
    jquery: "http://res.qiakr.com/plugins/jquery/jquery-2.0.0.min",
    mmRouter:"http://res.qiakr.com/plugins/avalon/mmRouter"
}
})</code></pre>
以上代码没问题，以下代码有问题
<pre><code>require.config({
  paths: {
    jquery: "//res.qiakr.com/plugins/jquery/jquery-2.0.0.min",
    mmRouter:"//res.qiakr.com/plugins/avalon/mmRouter"
}
})</code></pre>
资源都加载了，但是不执行后续操作了，没有执行加载模块的回调

**Comment by RubyLouvre** [comment]
用requirejs吧，估计我的正则有问题
