### ISSUE TITLE
一个关于测试的建议.

### ISSUE THREAD

**Issue by alanthinker** [RubyLouvre/avalon#1417]
是不是可以在avalon生成了dom元素后, 用jquery进行验证, (验证dom元素是否存在, 各个属性是否正确等) 如果验证失败就报警.
可以利用工具将各个测试用例都合并在一个html文件中, 然后文件一打开, 通过debug窗口的日志, 立刻就可以看到是否有错了.

每次修改bug后, 增加一个此bug对应的测试用例.
这样在以后进行大的修改后, 就可以进行回归测试了. 快速判断新的版本是否导致原来的测试用例失败.

刚测试了一下2016-6-2中午的版本, input的type="checkbox" 多了一对双引号, 导致复选框无法生成.

**Comment by RubyLouvre** [comment]
那时我们还没有打tag，开发版

**Comment by RubyLouvre** [comment]
有karma
