### ISSUE TITLE
数组循环后，事件参数生成bug,用的是仓库主干的最新版本/*! built in 2016-6-2:19 version 2.06

### ISSUE THREAD

**Issue by liuwei3230** [RubyLouvre/avalon#1419]
详情见附件
[a2test.zip](https://github.com/RubyLouvre/avalon/files/295538/a2test.zip)

**Comment by RubyLouvre** [comment]
升级今天的版本！不行再开新ISSUE，贴上简单例子，不要上传ZIP

**Comment by RubyLouvre** [comment]
已经修复 https://github.com/RubyLouvre/avalon/commit/62b72f92250486a85a9736f0a807c2e0e10c5e60
