### ISSUE TITLE
组件使用slot插入的元素里的事件被渲染成同一个事件

### ISSUE THREAD

**Issue by byends** [RubyLouvre/avalon#1420]
avalon 版本（built in 2016-6-2:20 version 2.06）

```html
<div class="btn-box">
    <div class="addr-btn blue" ms-click="@confirmDialog">保存</div>
    <div class="addr-btn" ms-click="@closeDialog">取消</div>
</div>
```
  
渲染成同一个事件了：  
 
![image](https://cloud.githubusercontent.com/assets/772787/15765797/58ab72e4-296b-11e6-8d76-fd8a68208377.png)

阻止冒泡居然就好了，而且生成的事件名变短了，所以觉得不应该是随机数的问题:  

```html
<div class="btn-box">
    <div class="addr-btn blue" ms-click="@confirmDialog | stop">保存</div>
    <div class="addr-btn" ms-click="@closeDialog">取消</div>
</div>
```

![image](https://cloud.githubusercontent.com/assets/772787/15765823/a64d6aac-296b-11e6-801d-1cc2fda9c5d1.png)

**Comment by RubyLouvre** [comment]
给一个完整的页面好不？例子要简洁，但要完整，又不知道你是什么版本

**Comment by RubyLouvre** [comment]
这个今天（6月7日）已经修复！
