### ISSUE TITLE
IOS真机上网页出现不加载样式的问题

### ISSUE THREAD

**Issue by bIgMunich** [RubyLouvre/avalon#1428]
windows，google，safiri
  做了一个手机网页，在谷歌模拟环境下正常，但是到IOS iphone6,6s下不加载样式
  用的是tap。使用webpack打包的

**Comment by byends** [comment]
你打包 有没有生成独立的 css 文件？

**Comment by bIgMunich** [comment]
打包至生成avalonmobile的js而已，css文件是我项目里面本地的，在windows上各个浏览器调试都是ok，在安卓机部分显示也正常，但是IOS全部没有加载
我做了一个demo测试结果如此

**Comment by byends** [comment]
不懂楼主的意思，如果 css 代码也打包进去的，我建议你 还是使用 webapck 配置生成独立的文件，webpack 打包 可以自动帮你插入` <link ` 代码到 html  `head` 头部

但，最重要的， 这些都和 avalon 没有关系

**Comment by bIgMunich** [comment]
我刚才又打了一次包，效果还是如此，我没明白的意思，那么能麻烦你帮我讲tap打包进去，我测试下吗？看看我们打包的效果哪里出现了问题，纠结了好几天了，我可以发QQ给你，我的demo吗？谢谢

**Comment by bIgMunich** [comment]
- 
![img_0033](https://cloud.githubusercontent.com/assets/16953690/15811771/4808ade6-2bdf-11e6-8ecc-8760dcbcc8b5.PNG)

电脑上都正常，唯独在手机上显示如此
 
这个demo的前三个是用avalon动态生成，而后面的都是手动html，谢谢

**Comment by bIgMunich** [comment]
PC版本
![mbt7c n ghte59 wf11zw](https://cloud.githubusercontent.com/assets/16953690/15811787/961dade2-2bdf-11e6-8fdf-c3326079fb65.png)

**Comment by byends** [comment]
把你html 代码贴出来，你发这些截图没啥用

**Comment by bIgMunich** [comment]
@{
    Layout = null;
}
<html>
<head>
    <title>主页</title>
    <link href="~/Content/index.css" rel="stylesheet" />
    <script src="~/Scripts/avalon.js"></script>
    <script>
        var vm = avalon.define({
            $id: "test",
            a: "哈哈哈",
            data: [1, 2],
            tapFunction: function () {
                alert("12456");
                vm.a = "111111111111";
            },
            changgeName: function () {
                vm.a = "changge";
            }
        })
    </script>
</head>
<body>
    <div id="main" class="content" ms-controller="test">
        
        <div class="contentRight">
            <div class="contentRightList" ms-for="($index, el) in ~data" ms-click="~changgeName">
                <div class="topContent">
                    <span class="topContentLeft">名字</span>
                    <span class="topContentRight">{{~a}}</span>
                </div>
            </div>
            <div class="contentRightList">
                <div class="topContent">
                    <span class="topContentLeft">名字</span>
                    <span class="topContentRight">111</span>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

**Comment by bIgMunich** [comment]
![image](https://cloud.githubusercontent.com/assets/16953690/15812199/54fad8da-2be4-11e6-8fae-551508b326ed.png)
![image](https://cloud.githubusercontent.com/assets/16953690/15812207/64465d78-2be4-11e6-9746-a0623ab6141e.png)

**Comment by bIgMunich** [comment]
红圈的样式全掉在IOS真机上全掉

**Comment by bIgMunich** [comment]
打包的时候，将tap打包进去生成的Mobilejs

**Comment by bIgMunich** [comment]
是不是因为.net的razor和@符号冲突，我改成~这个关键key，然后avalon在扫描的时候，将~开头的css样式给截取了？

**Comment by byends** [comment]
你抓包看看 `index.css` 文件 有没有 正常加载

**Comment by byends** [comment]
乱猜啥啊，要去调试找原因，先确定是否是 avalon 的影响

**Comment by bIgMunich** [comment]
好的，我调试取了

**Comment by bIgMunich** [comment]
谢谢你的帮助
