### ISSUE TITLE
doc问题

### ISSUE THREAD

**Issue by heipacker** [RubyLouvre/avalon#1430]
“@符合 ” 这里应该是符号吧  把这个文档改改？

**Comment by byends** [comment]
你看到了的话就直接 提交 pr 上去，司徒看到 会合并的

**Comment by heipacker** [comment]
ok

2016-06-06 11:56 GMT+08:00 羽飞 <notifications@github.com>:

**Comment by RubyLouvre** [comment]
已经搞定
