### ISSUE TITLE
smartgrid 在 ie10 ei11闪动的问题

### ISSUE THREAD

**Issue by mylyh** [RubyLouvre/avalon#1432]
好像背景先灰色在变成白色, 有个渐变, 闪动, 
![image](https://cloud.githubusercontent.com/assets/14024564/15811161/548577cc-2bd8-11e6-803a-8af52e935512.png)

**Comment by mylyh** [comment]
![image](https://cloud.githubusercontent.com/assets/14024564/15811171/6990d15c-2bd8-11e6-9bcd-4bc77a5d4d7d.png)
正常是这样的

**Comment by RubyLouvre** [comment]
那是个loading吧

**Comment by mylyh** [comment]
但是其他浏览器, 不会有这种闪动的渐变, 非常快渲染出来
