### ISSUE TITLE
 双重循环，如果内循环是option标签则渲染不正确

### ISSUE THREAD

**Issue by yyqhlw** [RubyLouvre/avalon#1434]
版本:1.5.5 
浏览器:ie8

option标签个数渲染正确， 但是text值为{{el.text}}

**Comment by RubyLouvre** [comment]
改成ms-text

**Comment by RubyLouvre** [comment]
你没有例子，可能其他地方写错

**Comment by yyqhlw** [comment]
![image](https://cloud.githubusercontent.com/assets/3954559/15817531/02b26c92-2c0b-11e6-8202-c037bde85e9d.png)

问题并没有解决

**Comment by yyqhlw** [comment]
ms-text 是多余的，刚才测试忘记删除了

**Comment by RubyLouvre** [comment]
不要贴图，使用markdown，将代码贴上来

**Comment by RubyLouvre** [comment]
明白了
你下面的那个 ms-repeat没有指定变量名，改成ms-repeat-elem;然后其他地方改成elem.text,

**Comment by yyqhlw** [comment]
我是尝试了其他可能性才提问的， 你上面说的方式也没有解决


`<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>种子项目</title>
	<link rel="stylesheet" href="libs/bootstrap/bootstrap.css">
	<link rel="stylesheet" href="libs/bootstrap/bootstrap-theme.css">
	<link rel="stylesheet" href="css/comm.css">
</head>
<body ms-controller="app">
<ul>
	<li ms-repeat="lis">
		<select>
			<option ms-repeat="ops" ms-attr-value="el.text">{{el.text}}</option>
		</select>
	</li>
</ul>
<div ms-view></div>
<script src="http://cdn.bootcss.com/avalon.js/1.5.5/avalon.js"></script>
<script type="text/javascript">
	avalon.define({
		$id:"app",
		lis:[{name:111},{name:222},{name:333},{name:444},{name:555}],
		ops:[{text:111,value:111},{text:111,value:111},{text:111,value:111},{text:111,value:111},{text:111,value:111}]
	})
</script>
</body>
</html>`

**Comment by yyqhlw** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>种子项目</title>
	<link rel="stylesheet" href="libs/bootstrap/bootstrap.css">
	<link rel="stylesheet" href="libs/bootstrap/bootstrap-theme.css">
	<link rel="stylesheet" href="css/comm.css">
</head>
<body ms-controller="app">
<ul>
	<li ms-repeat="lis">
		<select>
			<option ms-repeat="ops" ms-attr-value="el.text">{{el.text}}</option>
		</select>
	</li>
</ul>
<div ms-view></div>
<script src="http://cdn.bootcss.com/avalon.js/1.5.5/avalon.js"></script>
<script type="text/javascript">
	avalon.define({
		$id:"app",
		lis:[{name:111},{name:222},{name:333},{name:444},{name:555}],
		ops:[{text:111,value:111},{text:111,value:111},{text:111,value:111},{text:111,value:111},{text:111,value:111}]
	})
</script>
</body>
</html>

**Comment by yyqhlw** [comment]
另外就是官方群怎么加不进去? 加了几次都是没反应的。 
我们公司是用avalon作为框架在生产线的，  所以有啥问题希望加个群交流下

**Comment by RubyLouvre** [comment]
加群要注明官网名啊
你连官网也不知，当然不给加

**Comment by RubyLouvre** [comment]
你的循环是有问题，把上面的ms-repeat去掉就好了！你的数组不是二维数组，不能使用二重循环;将这里的例子过一遍吧。https://github.com/RubyLouvre/avalon/tree/1.4/examples 上面有教你怎么循环

**Comment by yyqhlw** [comment]
谢谢，我先看看示例

**Comment by yyqhlw** [comment]
为什么在其他浏览器下是正常的， 单独ie8下有这个问题，所以我认为这是框架的一个bug

**Comment by yyqhlw** [comment]
而且在IE8 下 如果内循环的标签是其他的标签比如 li ，则是正常的

**Comment by RubyLouvre** [comment]
IE8下需要使用更严格的写法。。。。
