### ISSUE TITLE
2.0.3对数组的splice处理时会有问题

### ISSUE THREAD

**Issue by qiangtou** [RubyLouvre/avalon#1436]
此问题在最新的2.0.6好像也存在

https://github.com/RubyLouvre/avalon/blob/2.0.3/dist/avalon.js#L7785

当neo.length>old.length时，item为undefined,可能影响后续处理

	        if (method === 'splice' && Object(this[0]) === this[0]) {
	            var old = this.slice(a, b)
	            var neo = ap.slice.call(arguments, 2)
	            var args = [a, b]
	            for (var j = 0, jn = neo.length; j < jn; j++) {                        
	                var item = old[j]
                      //当neo.length>old.length时，item为undefined,可能影响后续处理
	                args[j + 2] = modelAdaptor(neo[j], item, item && item.$events, {
	                    id: this.$id + '.*',
	                    master: true
	                })
	            }

	        }

**Comment by RubyLouvre** [comment]
是的，已经修了，`item && item.$events ` ==> `(item && item.$events || {})`
