### ISSUE TITLE
组件重复初始化, 值绑定有出问题

### ISSUE THREAD

**Issue by mylyh** [RubyLouvre/avalon#1438]
第一初始化日期控件显示是正常的(给组件赋值成2016-6-5), 进入下面那段代码 

然后返回到列表编辑其中一个, 跳转到编辑页面, 也进入下面段代码, (给组件赋值成2016-6-6), 日期组件的值就不会变化了;  组件还是显示 2016-6-5

然后返回列表页面, 点击其他群发, 第二次编辑又进入这段代码, 跳转到这个编辑页(给组件赋值成2016-6-7), 但是这时候页面渲染完显示的是 2016-6-6;

每次编辑组件显示的都是上一次给组件的初始化的值;

require(["../scripts/UI/avalon.oniui-master/datepicker/avalon.datepicker", "../scripts/UI/avalon.oniui-master/slider/avalon.slider"], function(avalon) {
                 
                var one = avalon.define("dateOne", function(vm) {

                  
                    if( blog.op =="edit"   ){
                         vm.oneDate = "";
                       // 每次编辑给组件初始不同的值
                         vm.oneDate = blog.editData.sendTime;
     

                    }else{

                          vm.oneDate = comm.getFormatDate( new Date() , '-');
                    }
                   
                   //这里打印出来的是 2016-6-7, 组件渲染完显示的是2016-6-6
                    avalon.log( blog.editData.sendtime );

                    vm.datepicker = {
                        onSelectTime: function(vmodel) {
                            var currentTime = new Date(vmodel.year, vmodel.month, vmodel.day, vmodel.hour, vmodel.minute)
                             
                             blog.oneDate = comm.getFormatDate(new Date(currentTime) , '-');
     
                        }
                    }
                    
                    
                    //blog.oneDate =  blog.editData.sendTime;
     
                }) 
                
                avalon.scan();

});

页面之间的切换, 用的是mmsate

**Comment by mylyh** [comment]
而且发现分页控件也有这个问题, 编辑的第一次的时候不更新页面, 到了第二次更新, 才把上一次的数据更新到页面

**Comment by mylyh** [comment]
<div class="gp-filter hx-filter mb_0 clearfix">
                      <div class="label" ms-controller='dateOne'>
                    
                            <input type="text"  ms-widget="datepicker" data-datepicker-timer="true" ms-duplex="oneDate" class="" style="width:156px" >  
                        </div>
                        
                </div>

**Comment by mylyh** [comment]
![image](https://cloud.githubusercontent.com/assets/14024564/15850125/f2a20eac-2cc8-11e6-8485-f7d111954fc7.png)
![image](https://cloud.githubusercontent.com/assets/14024564/15850133/03fc1e86-2cc9-11e6-8eb0-18df70c0d30a.png)

**Comment by RubyLouvre** [comment]
每个组件都有onInit方法，通过它得到组件VM;然后 将它保存在某个位置（全局）;然后 通过它来是否重新初始化

**Comment by mylyh** [comment]
有没具体的列子, 我再视图跳出的时候, 移除组件也没效果,  下次进来, 还是显示上一次的编辑的值

  // 对应的视图销毁前
        $ctrl.$onBeforeUnload = function() {
            blog.receiverNumbers = "";
            blog.messageContent = "";
            blog.editData = {};
            blog.messageLeft = 350;

            blog.vmSartDate && blog.vmSartDate.$remove();
            blog.vmOneDate && blog.vmOneDate.$remove();
            blog.vmOneDate = null;
        }

**Comment by mylyh** [comment]
vm.datepicker = {
                        onSelectTime: function(vmodel) {
                            var currentTime = new Date(vmodel.year, vmodel.month, vmodel.day, vmodel.hour, vmodel.minute)
                             
                             blog.oneDate = comm.getFormatDate(new Date(currentTime) , '-');
     
                        } ,
                        onInit: function(o){
                             blog.vmOneDate = o.$vmodel;
                             //或者 blog.vmOneDate = o;
                        },
                        onDispose: function(){
                            alert(2)
                        }
                    }

**Comment by mylyh** [comment]
var one = avalon.define("dateOne", function(vm) {

                    if( blog.op =="edit"   ){
                         vm.oneDate = "";
                         vm.oneDate = blog.editData.sendTime;
 
                    }else{

                          vm.oneDate = comm.getFormatDate( new Date() , '-');
                    }
                    
                    avalon.log( blog.editData.sendtime );
                    vm.datepicker = {
                        onSelectTime: function(vmodel) {
                            var currentTime = new Date(vmodel.year, vmodel.month, vmodel.day, vmodel.hour, vmodel.minute)
                             
                             blog.oneDate = comm.getFormatDate(new Date(currentTime) , '-');
     
                        } ,
                        onInit: function(o){
                             blog.vmOneDate = o.$vmodel;
                            
                             return false;
                        },
                        onDispose: function(){
                           
                        }
                    }
                    
                    vm.onInit = function(o){
                         
                    }

**Comment by RubyLouvre** [comment]
什么版本啊？oniui的问题不要在这里，那是同事们搞的库
