### ISSUE TITLE
2.0.4中ms-validate报错

### ISSUE THREAD

**Issue by areyouse7en** [RubyLouvre/avalon#1440]
Uncaught TypeError: Cannot read property 'nodeType' of undefined  
avalon.modern.js:5848
avalon.js:2760

**Comment by RubyLouvre** [comment]
有例子不？

**Comment by areyouse7en** [comment]
就官方例子http://avalonjs.coding.me/cn/ms-rules.html#start

![qq 20160608110855](https://cloud.githubusercontent.com/assets/3938443/15881566/87b77388-2d69-11e6-9ab1-6d89d7ce7cb2.png)

**Comment by RubyLouvre** [comment]
那晚些时候看

**Comment by RubyLouvre** [comment]
已经修复
