### ISSUE TITLE
组件模版ms-for报错Uncaught TypeError: Cannot read property 'renderCount' of undefined

### ISSUE THREAD

**Issue by juefeng** [RubyLouvre/avalon#1442]
![qq 20160608120945](https://cloud.githubusercontent.com/assets/3349391/15882577/94fd60f8-2d72-11e6-8dae-3baa0782e2fa.png)
![qq 20160608121153](https://cloud.githubusercontent.com/assets/3349391/15882588/b20fea80-2d72-11e6-92d8-f6a900608b2f.png)

**Comment by RubyLouvre** [comment]
不要截图上来行不？使用markdown贴代码

**Comment by RubyLouvre** [comment]
不过更新今天的版本应该修好了！因为有另外两个ISSUE都提到这个
