### ISSUE TITLE
avalon.modern.js组件onInit修改变量报错Uncaught TypeError: Failed to execute 'insertBefore' on 'Node': 2 arguments required, but only 1 present.

### ISSUE THREAD

**Issue by juefeng** [RubyLouvre/avalon#1443]
var tpl = '<div><select>' +
                '<option ms-for="el in @numList">{{el}}</option>' +
                '</select></div>';

        avalon.component('ms-pager', {
            template: tpl,
            defaults: {
                numList: [6, 12, 18, 24, 30],
                onInit: function (e) {
                    console.log('onInit')
                    e.vmodel.numList = [1,2,3];
                }
            }

        })
        var vm = avalon.define({
            $id: 'test',
        })

    </script>
<div ms-controller="test">
    <xmp ms-widget="{is:'ms-pager'}"></xmp>

加载的是**avalon.modern.js**

**Uncaught TypeError: Failed to execute 'insertBefore' on 'Node': 2 arguments required, but only 1 present.**

**Comment by RubyLouvre** [comment]
什么浏览器？

**Comment by RubyLouvre** [comment]
已经修复！
