### ISSUE TITLE
组件模版ms-for="el in @xxx"中 el 在xxx改变后值错乱

### ISSUE THREAD

**Issue by juefeng** [RubyLouvre/avalon#1446]
测试 /*! built in 2016-6-8:22 version 2.07 by 司徒正美 */
<pre><code class="hljs"><span class="xml"><span class="hljs-doctype">&lt;!DOCTYPE html&gt;</span>
<span class="hljs-tag">&lt;<span class="hljs-title">html</span> <span class="hljs-attribute">lang</span>=<span class="hljs-value">"en"</span>&gt;</span>
    <span class="hljs-tag">&lt;<span class="hljs-title">head</span>&gt;</span>
        <span class="hljs-tag">&lt;<span class="hljs-title">link</span> <span class="hljs-attribute">href</span>=<span class="hljs-value">"//cdn.bootcss.com/bootstrap/2.3.2/css/bootstrap.min.css"</span> <span class="hljs-attribute">rel</span>=<span class="hljs-value">"stylesheet"</span>&gt;</span>
        <span class="hljs-tag">&lt;<span class="hljs-title">script</span> <span class="hljs-attribute">src</span>=<span class="hljs-value">"/avalon.js"</span>&gt;</span><span class="undefined"></span><span class="hljs-tag">&lt;/<span class="hljs-title">script</span>&gt;</span>
        <span class="hljs-tag">&lt;<span class="hljs-title">script</span> <span class="hljs-attribute">type</span>=<span class="hljs-value">"text/javascript"</span>&gt;</span><span class="nimrod">
            <span class="hljs-keyword">var</span> test_vm = avalon.define({
                $id:'test'
            });
            avalon.component(<span class="hljs-string">"ms-pager"</span>, {
                <span class="hljs-keyword">template</span>: '&lt;<span class="hljs-keyword">div</span> class=<span class="hljs-string">"pagination"</span>&gt;'+
              '&lt;ul&gt;&lt;li ms-<span class="hljs-keyword">for</span>=<span class="hljs-string">"el in @pages"</span> ms-attr=<span class="hljs-string">"{class:(el == @current_page ? \'active\' : \'\')}"</span>&gt;&lt;a href=<span class="hljs-string">"#"</span> ms-click=<span class="hljs-string">"@gotoPage(el, $event)"</span>&gt;</span></span><span class="hljs-expression">{{<span class="hljs-variable">el</span>}}</span><span class="xml"><span class="scala">&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;'+
            '&lt;/div&gt;',
                defaults: {
                    total_page: <span class="hljs-number">25</span>,
                    current_page: <span class="hljs-number">1</span>,
                    show_page: <span class="hljs-number">7</span>,
                    pages:[<span class="hljs-number">1</span>,<span class="hljs-number">2</span>,<span class="hljs-number">3</span>,<span class="hljs-number">4</span>,<span class="hljs-number">5</span>,<span class="hljs-number">6</span>,<span class="hljs-number">7</span>],
                    gotoPage: function(page, e){
                        <span class="hljs-keyword">this</span>.current_page = page;
                        <span class="hljs-keyword">this</span>.pages = <span class="hljs-keyword">this</span>.getPages();
                        console.log(<span class="hljs-keyword">this</span>.pages);
                    },
                    getPages: function() {
                        <span class="hljs-keyword">var</span> pages = [];
                        <span class="hljs-keyword">var</span> s = <span class="hljs-keyword">this</span>.show_page, l = <span class="hljs-keyword">this</span>.current_page, r = <span class="hljs-keyword">this</span>.current_page, c = <span class="hljs-keyword">this</span>.total_page;
                        pages.push(l);
                        <span class="hljs-keyword">while</span>(<span class="hljs-literal">true</span>) {
                            <span class="hljs-keyword">if</span>(pages.length &gt;= s) {
                                <span class="hljs-keyword">break</span>;
                            }
                            <span class="hljs-keyword">if</span>(l &gt; <span class="hljs-number">1</span>) {
                                pages.unshift(--l);
                            }
                            <span class="hljs-keyword">if</span>(pages.length &gt;= s) {
                                <span class="hljs-keyword">break</span>;
                            }
                            <span class="hljs-keyword">if</span>(r &lt; c) {
                                pages.push(++r);
                            }
                        }

                        <span class="hljs-keyword">return</span> pages;
                    }
                }
            });
        </span><span class="hljs-tag">&lt;/<span class="hljs-title">script</span>&gt;</span>
    <span class="hljs-tag">&lt;/<span class="hljs-title">head</span>&gt;</span>
    <span class="hljs-tag">&lt;<span class="hljs-title">body</span>&gt;</span>
        <span class="hljs-tag">&lt;<span class="hljs-title">div</span> <span class="hljs-attribute">ms-controller</span>=<span class="hljs-value">"test"</span>&gt;</span>
            <span class="hljs-tag">&lt;<span class="hljs-title">xmp</span> <span class="hljs-attribute">ms-widget</span>=<span class="hljs-value">"{is:'ms-pager'}"</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-title">xmp</span>&gt;</span>
        <span class="hljs-tag">&lt;/<span class="hljs-title">div</span>&gt;</span>
    <span class="hljs-tag">&lt;/<span class="hljs-title">body</span>&gt;</span>
<span class="hljs-tag">&lt;/<span class="hljs-title">html</span>&gt;</span></span>
</code></pre>
刚开始页面是
1 2 3 4 5 6 7 active 是第1页
点了第7页后是
4 5 6 7 8 9 10 active 是第7页
再点第10页后变成这样
3 4 5 6 7 8 9 active 是第5页

两次点击事件打印page的值是7跟6

**Comment by RubyLouvre** [comment]
已经修正 https://github.com/RubyLouvre/avalon/commit/6c7dd32252e0869d7d7517c4aaf9f599fdd12c9e

**Comment by RubyLouvre** [comment]
```   
      '<ul><li ms-for="el in @pages" ms-attr="{class:(el == @current_page ? \'active\' : \'\')}"><a href="#" ms-click="@gotoPage(el, $event)">{{el}}</a></li></ul>'+

```
这里有错 , class是关键字，要用引号引起来

并且class应该用,ms-class，不要用ms-attr
