### ISSUE TITLE
关于ms-duplex数据与视图不同步问题

### ISSUE THREAD

**Issue by sayll** [RubyLouvre/avalon#1449]
```
<body ms-controller="test">
<script>
	avalon.ready(function () {
	    var vm = avalon.define({
	        $id: 'test',
	        val: [],
	        key: true,
	        fn: function () {
	            console.log(this.val);
	        },
	        fn1: function () {
	            console.log(vm.key);
	            vm.key = !vm.key;
	        }
	    });
        avalon.scan(document.body)
	})
</script>
<div>
	<button ms-on-click="@fn1"> test</button>
	<br>
	<input type="checkbox" value="a" ms-duplex-string="@val" ms-on-click="@fn">
	<input type="checkbox" value="b" ms-duplex-string="@val" ms-on-click="@fn">
	<input type="checkbox" value="c" ms-duplex-string="@val" ms-on-click="@fn">
	<input type="checkbox" value="d" ms-duplex-string="@val" ms-on-click="@fn">
	<p ms-if="@key">  {{@val}}</p>
	<p>  {{@val}}.</p>
</div>
</body>
```

======================================================================
问题版本：2.07版
方法@fn中，可以从控制台看出@val内数组确实添加了a,b,c,d中的数据，但视图{{@val}}没有同步过来。
1：|{{@val}}:跟上其他字符，视图就同步正常。
2：{{@val}}数据通过ms-if从新插入DOM，数据就会更新显示

**Comment by RubyLouvre** [comment]
你这是什么代码，给出一个简单的页面吧

**Comment by RubyLouvre** [comment]
看不懂你写什么

**Comment by sayll** [comment]
@RubyLouvre 
<body ms-controller="test">
<script>avalon.ready(function () {
    var vm = avalon.define({
        $id: 'test',
        val: [],
        fn: function () {
            console.log(this.val);
        },
        fn1: function () {
            console.log(vm.key);
            vm.key = !vm.key;
        }
    });
    console.log(vm.dom);
    avalon.scan(document.body)
})
</script>
<div>
	<button ms-on-click="@fn1"> test</button>
	<br>
	<input type="checkbox" value="a" ms-duplex-string="@val" ms-on-click="@fn">
	<input type="checkbox" value="b" ms-duplex-string="@val" ms-on-click="@fn">
	<input type="checkbox" value="c" ms-duplex-string="@val" ms-on-click="@fn">
	<input type="checkbox" value="d" ms-duplex-string="@val" ms-on-click="@fn">
	<p>  {{@val}}</p>
	<p>  {{@val}}.</p>
</div>
</body>

**Comment by sayll** [comment]
<body ms-controller="test">
<script>avalon.ready(function () {
    var vm = avalon.define({
        $id: 'test',
        val: [],
        fn: function () {
            console.log(this.val);
        },
        fn1: function () {
            console.log(vm.key);
            vm.key = !vm.key;
        }
    });
    console.log(vm.dom);
    avalon.scan(document.body)
})
</script>
<div>
	<button ms-on-click="@fn1"> test</button>
	<br>
	<input type="checkbox" value="a" ms-duplex-string="@val" ms-on-click="@fn">
	<input type="checkbox" value="b" ms-duplex-string="@val" ms-on-click="@fn">
	<input type="checkbox" value="c" ms-duplex-string="@val" ms-on-click="@fn">
	<input type="checkbox" value="d" ms-duplex-string="@val" ms-on-click="@fn">
	<p>  {{@val}}</p>
	<p>  {{@val}}.</p>
</div>
</body>

**Comment by sayll** [comment]
#1448 `<body ms-controller="test">
<script>avalon.ready(function () {
    var vm = avalon.define({
        $id: 'test',
        val: [],
        fn: function () {
            console.log(this.val);
        },
        fn1: function () {
            console.log(vm.key);
            vm.key = !vm.key;
        }
    });
    console.log(vm.dom);
    avalon.scan(document.body)
})
</script>
<div>
	<button ms-on-click="@fn1"> test</button>
	<br>
	<input type="checkbox" value="a" ms-duplex-string="@val" ms-on-click="@fn">
	<input type="checkbox" value="b" ms-duplex-string="@val" ms-on-click="@fn">
	<input type="checkbox" value="c" ms-duplex-string="@val" ms-on-click="@fn">
	<input type="checkbox" value="d" ms-duplex-string="@val" ms-on-click="@fn">
	<p>  {{@val}}</p>
	<p>  {{@val}}.</p>
</div>
</body>`

**Comment by sayll** [comment]
@RubyLouvre 囧，回复半天代码不成功，上面修改了，请前辈看看。p标签第二才能正常同步。只有在插值后追加一个东西，空格都可以，才能正常同步

**Comment by RubyLouvre** [comment]
你每次不给完整页面

**Comment by sayll** [comment]
```
<!DOCTYPE html>
<html lang="zh-cmn-Hans">
<head>
	<meta http-equiv="content-type" content="text/html;charset=utf-8">
	<title></title>
	<meta name="renderer" content="webkit">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome">
	<meta name="keywords" content="">
	<meta name="description" content="">
	<meta name="msapplication-tap-highlight" content="no">
	<script src="avalon.modern.js"></script>
</head>
<body ms-controller="test">
<script>
	avalon.ready(function () {
		var vm = avalon.define({
			$id: 'test',
			val: [],
			key: true,
			fn: function () {
				console.log(this.val);
			},
			fn1: function () {
				console.log(vm.key);
				vm.key = !vm.key;
			}
		});
		avalon.scan(document.body)
	})
</script>
<div>
	<button ms-on-click="@fn1"> test</button>
	<br>
	<input type="checkbox" value="a" ms-duplex-string="@val" ms-on-click="@fn">
	<input type="checkbox" value="b" ms-duplex-string="@val" ms-on-click="@fn">
	<input type="checkbox" value="c" ms-duplex-string="@val" ms-on-click="@fn">
	<input type="checkbox" value="d" ms-duplex-string="@val" ms-on-click="@fn">
	<p ms-if="@key">  {{@val}}</p>
	<p>  {{@val}}.</p>
</div>
</body>
</html>
```
抱歉

**Comment by sayll** [comment]
```
<!DOCTYPE html>
<html lang="zh-cmn-Hans">
<head>
	<meta http-equiv="content-type" content="text/html;charset=utf-8">
	<title></title>
	<meta name="renderer" content="webkit">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome">
	<meta name="keywords" content="">
	<meta name="description" content="">
	<meta name="msapplication-tap-highlight" content="no">
	<script src="avalon.modern.js"></script>
</head>
<body ms-controller="test">
<script>
	avalon.ready(function () {
		var vm = avalon.define({
			$id: 'test',
			val: 0,
		});
		avalon.scan(document.body)
	})
</script>
<div>
	<input type="text" ms-duplex-number="@val">
	<p> {{@val}}</p>
</div>
</body>
</html>
```
前辈，还有这段代码，input里面确实无法输入小数点，无论数字前或者数字后跟。除非通过复制黏贴的形式才可以放入input框内。
=======================================
问题都在2.07版出现的。

**Comment by RubyLouvre** [comment]
https://github.com/RubyLouvre/avalon/blob/master/src/seed/lang.share.js#L22

**Comment by RubyLouvre** [comment]
用这里的 https://github.com/RubyLouvre/avalon/tree/master/dist

**Comment by RubyLouvre** [comment]
否是就是你的电脑有问题了

**Comment by sayll** [comment]
=================================================
前辈，抱歉。我的错，我发现，我用的版本是5月11日的版本。公司的版本才是2.07的。
现在新版本2.07，这二个问题都已经修复了。现在没问题了
