### ISSUE TITLE
chrome 53  出现警告 'KeyboardEvent.keyIdentifier' is deprecated

### ISSUE THREAD

**Issue by andypinet** [RubyLouvre/avalon#1450]
'KeyboardEvent.keyIdentifier' is deprecated and will be removed in M53, around September 2016. See https://www.chromestatus.com/features/5316065118650368 for more details.

**Comment by andypinet** [comment]
使用https://segmentfault.com/a/1190000004947858 表单验证例子发现

**Comment by andypinet** [comment]
chrome 53以下版本没有出现

**Comment by RubyLouvre** [comment]
因为我是遍历了事件对象的所有属性，然后将它复制到我的伪事件对象中去;

这不是什么BUG。只是警告用户以后不用这个东西
