### ISSUE TITLE
组件模版问题

### ISSUE THREAD

**Issue by juefeng** [RubyLouvre/avalon#1455]
测试 /*! built in 2016-6-11:11 version 2.08 by 司徒正美 */
还是这个例子，上次也存在的问题。
<pre><code class="hljs"><span class="xml"><span class="hljs-doctype">&lt;!DOCTYPE html&gt;</span>
<span class="hljs-tag">&lt;<span class="hljs-title">html</span> <span class="hljs-attribute">lang</span>=<span class="hljs-value">"en"</span>&gt;</span>
    <span class="hljs-tag">&lt;<span class="hljs-title">head</span>&gt;</span>
        <span class="hljs-tag">&lt;<span class="hljs-title">link</span> <span class="hljs-attribute">href</span>=<span class="hljs-value">"//cdn.bootcss.com/bootstrap/2.3.2/css/bootstrap.min.css"</span> <span class="hljs-attribute">rel</span>=<span class="hljs-value">"stylesheet"</span>&gt;</span>
        <span class="hljs-tag">&lt;<span class="hljs-title">script</span> <span class="hljs-attribute">src</span>=<span class="hljs-value">"/avalon.js"</span>&gt;</span><span class="undefined"></span><span class="hljs-tag">&lt;/<span class="hljs-title">script</span>&gt;</span>
        <span class="hljs-tag">&lt;<span class="hljs-title">script</span> <span class="hljs-attribute">type</span>=<span class="hljs-value">"text/javascript"</span>&gt;</span><span class="nimrod">
            <span class="hljs-keyword">var</span> test_vm = avalon.define({
                $id:'test'
            });
            avalon.component(<span class="hljs-string">"ms-pager"</span>, {
                <span class="hljs-keyword">template</span>: '&lt;<span class="hljs-keyword">div</span> class=<span class="hljs-string">"pagination"</span>&gt;'+
              '&lt;ul&gt;&lt;li ms-<span class="hljs-keyword">for</span>=<span class="hljs-string">"el in @pages"</span> ms-class=<span class="hljs-string">"el == @current_page ? \'active\' : \'\'"</span>&gt;&lt;a href=<span class="hljs-string">"#"</span> ms-click=<span class="hljs-string">"@gotoPage(el, $event)"</span>&gt;</span></span><span class="hljs-expression">{{<span class="hljs-variable">el</span>}}</span><span class="xml"><span class="scala">&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;'+
            '&lt;/div&gt;',
                defaults: {
                    total_page: <span class="hljs-number">25</span>,
                    current_page: <span class="hljs-number">1</span>,
                    show_page: <span class="hljs-number">7</span>,
                    pages:[<span class="hljs-number">1</span>,<span class="hljs-number">2</span>,<span class="hljs-number">3</span>,<span class="hljs-number">4</span>,<span class="hljs-number">5</span>,<span class="hljs-number">6</span>,<span class="hljs-number">7</span>],
                    gotoPage: function(page, e){
                        <span class="hljs-keyword">this</span>.current_page = page;
                        <span class="hljs-keyword">this</span>.pages = <span class="hljs-keyword">this</span>.getPages();
                        console.log(<span class="hljs-keyword">this</span>.pages);
                    },
                    getPages: function() {
                        <span class="hljs-keyword">var</span> pages = [];
                        <span class="hljs-keyword">var</span> s = <span class="hljs-keyword">this</span>.show_page, l = <span class="hljs-keyword">this</span>.current_page, r = <span class="hljs-keyword">this</span>.current_page, c = <span class="hljs-keyword">this</span>.total_page;
                        pages.push(l);
                        <span class="hljs-keyword">while</span>(<span class="hljs-literal">true</span>) {
                            <span class="hljs-keyword">if</span>(pages.length &gt;= s) {
                                <span class="hljs-keyword">break</span>;
                            }
                            <span class="hljs-keyword">if</span>(l &gt; <span class="hljs-number">1</span>) {
                                pages.unshift(--l);
                            }
                            <span class="hljs-keyword">if</span>(pages.length &gt;= s) {
                                <span class="hljs-keyword">break</span>;
                            }
                            <span class="hljs-keyword">if</span>(r &lt; c) {
                                pages.push(++r);
                            }
                        }

                        <span class="hljs-keyword">return</span> pages;
                    }
                }
            });
        </span><span class="hljs-tag">&lt;/<span class="hljs-title">script</span>&gt;</span>
    <span class="hljs-tag">&lt;/<span class="hljs-title">head</span>&gt;</span>
    <span class="hljs-tag">&lt;<span class="hljs-title">body</span>&gt;</span>
        <span class="hljs-tag">&lt;<span class="hljs-title">div</span> <span class="hljs-attribute">ms-controller</span>=<span class="hljs-value">"test"</span>&gt;</span>
            <span class="hljs-tag">&lt;<span class="hljs-title">xmp</span> <span class="hljs-attribute">ms-widget</span>=<span class="hljs-value">"{is:'ms-pager'}"</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-title">xmp</span>&gt;</span>
        <span class="hljs-tag">&lt;/<span class="hljs-title">div</span>&gt;</span>
    <span class="hljs-tag">&lt;/<span class="hljs-title">body</span>&gt;</span>
<span class="hljs-tag">&lt;/<span class="hljs-title">html</span>&gt;</span></span>
</code></pre>
刚开始页面是
1 2 3 4 5 6 7 active 是第1页
点了第7页后是
4 5 6 7 8 9 10 active 是第7页
再点第**4**页后变成这样
1 2 3 4 5 6 7 active 是第**1**页

**显示的页数已经没有上次错乱的问题，但是active还是不行。试过ms-attr="{'class':}"加引号，跟没加引号
效果是一样的，用ms-class也是同样的效果。
或者是我的代码有问题？**

**Comment by RubyLouvre** [comment]
```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>确认订单</title>
        <link href="//cdn.bootcss.com/bootstrap/2.3.2/css/bootstrap.min.css" rel="stylesheet">
        <script src="../dist/avalon.js"></script>
        <script>

            var vm = avalon.define({
                $id: "test",
                total_page: 25,
                current_page: 1,
                show_page: 7,
                pages: [1, 2, 3, 4, 5, 6, 7],
                gotoPage: function (page, e) {
                    this.current_page = page;
                    this.pages = this.getPages();
                    //console.log(this.pages);
                },
                getPages: function () {
                    var pages = [];
                    var s = this.show_page,
                            l = this.current_page,
                            r = this.current_page,
                            c = this.total_page;
                    pages.push(l);
                    while (true) {
                        if (pages.length >= s) {
                            break;
                        }
                        if (l > 1) {
                            pages.unshift(--l);
                        }
                        if (pages.length >= s) {
                            break;
                        }
                        if (r < c) {
                            pages.push(++r);
                        }
                    }

                    return pages;
                }
            })



        </script>
    </head>
    <body ms-controller="test">
      
        <div class="pagination">
            <ul>
                <li ms-for="el in @pages" 
                    ms-class="el == @current_page ? 'active':''">
                    <a href="#" ms-click="@gotoPage(el, $event)">{{el}}</a>
                </li>
            </ul>
        </div>
    </body>
</html>
```

**Comment by RubyLouvre** [comment]
搞定，明天加入单元测试中
