### ISSUE TITLE
avalon2 兼容问题IE6-8 下抛出VMLTag 未定义

### ISSUE THREAD

**Issue by FreedomGitHub** [RubyLouvre/avalon#1462]
<!DOCTYPE html>
<html>
    <head>
        <title>ms-validate</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge" /> 
        <script src="../dist/avalon.js"></script>
        <script>
            var vm = avalon.define({
                $id: 'test',
                button: {//注意这里不能以 $开头
                    buttonText: "按钮内容"
                }
            })

            avalon.component('ms-button', {
                template: '<button type="button"><span><slot name="buttonText"></slot></span></button>',
                defaults: {
                    buttonText: "button"
                },
                soleSlot: 'buttonText'
            })

        </script>
    </head>

    <body ms-controller="test">
    
    <ms-button ms-widget="@button"></ms-button>
    
    <xmp ms-widget='[{is:"ms-button"},@button]'></xmp>
    <wbr ms-widget='[{is:"ms-button"},@button]'/>
    <template ms-widget='[{is:"ms-button"},@button]'></template>
</body>
</html>

**Comment by FreedomGitHub** [comment]
/*! built in 2016-6-10:12 version 2.07 by 司徒正美 */

**Comment by FreedomGitHub** [comment]
version 2.08

**Comment by RubyLouvre** [comment]
npm install已经升到2.0.9了
