### ISSUE TITLE
组件模版问题

### ISSUE THREAD

**Issue by juefeng** [RubyLouvre/avalon#1468]
测试 /*! built in 2016-6-13:2 version 2.08 by 司徒正美 */
<pre><code class="hljs"><span class="xml"><span class="hljs-doctype">&lt;!DOCTYPE html&gt;</span>
<span class="hljs-tag">&lt;<span class="hljs-title">html</span> <span class="hljs-attribute">lang</span>=<span class="hljs-value">"zh-CN"</span>&gt;</span>
    <span class="hljs-tag">&lt;<span class="hljs-title">head</span>&gt;</span>
        <span class="hljs-tag">&lt;<span class="hljs-title">meta</span> <span class="hljs-attribute">http-equiv</span>=<span class="hljs-value">"Content-Type"</span> <span class="hljs-attribute">content</span>=<span class="hljs-value">"text/html; charset=UTF-8"</span>&gt;</span>
        <span class="hljs-tag">&lt;<span class="hljs-title">link</span> <span class="hljs-attribute">href</span>=<span class="hljs-value">"//cdn.bootcss.com/bootstrap/2.3.2/css/bootstrap.min.css"</span> <span class="hljs-attribute">rel</span>=<span class="hljs-value">"stylesheet"</span>&gt;</span>
        <span class="hljs-tag">&lt;<span class="hljs-title">script</span> <span class="hljs-attribute">src</span>=<span class="hljs-value">"//cdn.bootcss.com/jquery/1.7.2/jquery.min.js"</span>&gt;</span><span class="undefined"></span><span class="hljs-tag">&lt;/<span class="hljs-title">script</span>&gt;</span>

        <span class="hljs-tag">&lt;<span class="hljs-title">script</span> <span class="hljs-attribute">src</span>=<span class="hljs-value">"/Public/avalon.js"</span>&gt;</span><span class="undefined"></span><span class="hljs-tag">&lt;/<span class="hljs-title">script</span>&gt;</span>

        <span class="hljs-tag">&lt;<span class="hljs-title">script</span>&gt;</span><span class="lasso">
            <span class="hljs-built_in">var</span> test_mv <span class="hljs-subst">=</span> avalon<span class="hljs-built_in">.</span><span class="hljs-class"><span class="hljs-keyword">define</span></span>({
                 <span class="hljs-variable">$id</span>: <span class="hljs-string">'test'</span>,
                 items:<span class="hljs-preprocessor">[</span><span class="hljs-string">'请选择'</span>, <span class="hljs-string">'选项一'</span>, <span class="hljs-string">'选项二'</span><span class="hljs-preprocessor">]</span><span class="hljs-markup">,
                 value:'请选择',
            });
        </span></span><span class="hljs-tag">&lt;/<span class="hljs-title">script</span>&gt;</span>
    <span class="hljs-tag">&lt;/<span class="hljs-title">head</span>&gt;</span>
    <span class="hljs-tag">&lt;<span class="hljs-title">body</span>&gt;</span>
        <span class="hljs-tag">&lt;<span class="hljs-title">div</span> <span class="hljs-attribute">ms-controller</span>=<span class="hljs-value">"test"</span>&gt;</span>
            <span class="hljs-tag">&lt;<span class="hljs-title">xmp</span> <span class="hljs-attribute">ms-widget</span>=<span class="hljs-value">"{is:'ms-select', items:@items, value:@value}"</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-title">xmp</span>&gt;</span>
            <span class="hljs-tag">&lt;<span class="hljs-title">xmp</span> <span class="hljs-attribute">ms-widget</span>=<span class="hljs-value">"{is:'ms-pager'}"</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-title">xmp</span>&gt;</span>
        <span class="hljs-tag">&lt;/<span class="hljs-title">div</span>&gt;</span>

        <span class="hljs-tag">&lt;<span class="hljs-title">div</span> <span class="hljs-attribute">id</span>=<span class="hljs-value">"page_tpl"</span> <span class="hljs-attribute">style</span>=<span class="hljs-value">"display:none;"</span>&gt;</span>
            <span class="hljs-tag">&lt;<span class="hljs-title">div</span> <span class="hljs-attribute">class</span>=<span class="hljs-value">"pagination"</span>&gt;</span>
              <span class="hljs-tag">&lt;<span class="hljs-title">ul</span>&gt;</span>
                <span class="hljs-tag">&lt;<span class="hljs-title">li</span> <span class="hljs-attribute">ms-for</span>=<span class="hljs-value">"(key,val) in @pages"</span> <span class="hljs-attribute">ms-class</span>=<span class="hljs-value">"[(val == @current_page) &amp;&amp; 'active']"</span> &gt;</span><span class="hljs-tag">&lt;<span class="hljs-title">a</span> <span class="hljs-attribute">ms-click</span>=<span class="hljs-value">"@gotoPage($event, val)"</span> <span class="hljs-attribute">href</span>=<span class="hljs-value">"#"</span>&gt;</span></span><span class="hljs-expression">{{<span class="hljs-variable">val</span>}}</span><span class="xml"><span class="hljs-tag">&lt;/<span class="hljs-title">a</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-title">li</span>&gt;</span>
              <span class="hljs-tag">&lt;/<span class="hljs-title">ul</span>&gt;</span>
            <span class="hljs-tag">&lt;/<span class="hljs-title">div</span>&gt;</span>
        <span class="hljs-tag">&lt;/<span class="hljs-title">div</span>&gt;</span>

        <span class="hljs-tag">&lt;<span class="hljs-title">div</span> <span class="hljs-attribute">id</span>=<span class="hljs-value">"select_tpl"</span> <span class="hljs-attribute">style</span>=<span class="hljs-value">"display:none;"</span>&gt;</span>
            <span class="hljs-tag">&lt;<span class="hljs-title">div</span> <span class="hljs-attribute">ms-class</span>=<span class="hljs-value">"['btn-group', (@open?'open':'')]"</span>&gt;</span>
              <span class="hljs-tag">&lt;<span class="hljs-title">a</span> <span class="hljs-attribute">id</span>=<span class="hljs-value">"open_select"</span> <span class="hljs-attribute">class</span>=<span class="hljs-value">"btn dropdown-toggle"</span> <span class="hljs-attribute">data-toggle</span>=<span class="hljs-value">"dropdown"</span> <span class="hljs-attribute">ms-click</span>=<span class="hljs-value">"@openSelect(@value, $vmodel)"</span> <span class="hljs-attribute">href</span>=<span class="hljs-value">"#"</span>&gt;</span>
                </span><span class="hljs-expression">{{@<span class="hljs-variable">value</span>}}</span><span class="xml">
                <span class="hljs-tag">&lt;<span class="hljs-title">span</span> <span class="hljs-attribute">class</span>=<span class="hljs-value">"caret"</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-title">span</span>&gt;</span>
              <span class="hljs-tag">&lt;/<span class="hljs-title">a</span>&gt;</span>
              <span class="hljs-tag">&lt;<span class="hljs-title">ul</span> <span class="hljs-attribute">class</span>=<span class="hljs-value">"dropdown-menu"</span>&gt;</span>
                <span class="hljs-tag">&lt;<span class="hljs-title">li</span> <span class="hljs-attribute">ms-for</span>=<span class="hljs-value">"(key, val) in @items"</span> &gt;</span><span class="hljs-tag">&lt;<span class="hljs-title">a</span> <span class="hljs-attribute">href</span>=<span class="hljs-value">"javascript:;"</span> <span class="hljs-attribute">class</span>=<span class="hljs-value">"not-close"</span> <span class="hljs-attribute">ms-click</span>=<span class="hljs-value">"@select(key, $event)"</span>&gt;</span></span><span class="hljs-expression">{{<span class="hljs-variable">val</span>}}</span><span class="xml"><span class="hljs-tag">&lt;/<span class="hljs-title">a</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-title">li</span>&gt;</span>
              <span class="hljs-tag">&lt;/<span class="hljs-title">ul</span>&gt;</span>
            <span class="hljs-tag">&lt;/<span class="hljs-title">div</span>&gt;</span>
        <span class="hljs-tag">&lt;/<span class="hljs-title">div</span>&gt;</span>
        <span class="hljs-tag">&lt;<span class="hljs-title">script</span>&gt;</span><span class="javascript">
            avalon.component(<span class="hljs-string">"ms-select"</span>, {
                template: $(<span class="hljs-string">"#select_tpl"</span>).html(),
                defaults: {
                    items:[],
                    value:<span class="hljs-string">''</span>,
                    name:<span class="hljs-string">'test_select'</span>,
                    open: <span class="hljs-literal">false</span>,
                    onInit: <span class="hljs-function"><span class="hljs-keyword">function</span><span class="hljs-params">(e)</span></span>{
                        <span class="hljs-keyword">var</span> vm = <span class="hljs-keyword">this</span>;
                        avalon.bind(<span class="hljs-built_in">document</span>, <span class="hljs-string">'click'</span>, <span class="hljs-function"><span class="hljs-keyword">function</span><span class="hljs-params">(e)</span></span>{
                            <span class="hljs-keyword">if</span>(e.target.id != <span class="hljs-string">'open_select'</span>) {
                                vm.closeSelect.call(vm);
                            }
                        });
                    },
                    select: <span class="hljs-function"><span class="hljs-keyword">function</span><span class="hljs-params">(key, e)</span> </span>{
                        <span class="hljs-keyword">this</span>.value = <span class="hljs-keyword">this</span>.items[key];
                    },
                    openSelect: <span class="hljs-function"><span class="hljs-keyword">function</span><span class="hljs-params">(val, e)</span> </span>{
                        <span class="hljs-built_in">console</span>.log(e);
                        <span class="hljs-keyword">this</span>.open = <span class="hljs-literal">true</span>;
                    },
                    closeSelect: <span class="hljs-function"><span class="hljs-keyword">function</span><span class="hljs-params">()</span></span>{
                        <span class="hljs-keyword">this</span>.open = <span class="hljs-literal">false</span>;
                    }
                }
            });
            avalon.component(<span class="hljs-string">"ms-pager"</span>, {
                template: $(<span class="hljs-string">"#page_tpl"</span>).html(),
                defaults: {
                    total_page: <span class="hljs-number">40</span>,
                    current_page: <span class="hljs-number">1</span>,
                    show_page: <span class="hljs-number">7</span>,
                    pages: [<span class="hljs-number">1</span>,<span class="hljs-number">2</span>,<span class="hljs-number">3</span>,<span class="hljs-number">4</span>,<span class="hljs-number">5</span>,<span class="hljs-number">6</span>,<span class="hljs-number">7</span>],
                    gotoPage: <span class="hljs-function"><span class="hljs-keyword">function</span><span class="hljs-params">(e, page)</span></span>{
                        <span class="hljs-keyword">if</span>(page &gt; <span class="hljs-keyword">this</span>.total_page || page &lt; <span class="hljs-number">1</span>) {
                            <span class="hljs-keyword">return</span> <span class="hljs-literal">false</span>;
                        }
                        <span class="hljs-keyword">this</span>.current_page = page;
                        <span class="hljs-keyword">this</span>.pages = <span class="hljs-keyword">this</span>.getPage(page, <span class="hljs-keyword">this</span>.total_page, <span class="hljs-keyword">this</span>.show_page);
                    },
                    getPage: <span class="hljs-function"><span class="hljs-keyword">function</span><span class="hljs-params">(p, ps, s)</span> </span>{
                        <span class="hljs-keyword">var</span> pages = [], l = p, r = p;
                        <span class="hljs-keyword">if</span>(ps &lt; s) {

                            <span class="hljs-keyword">for</span>(<span class="hljs-keyword">var</span> i = <span class="hljs-number">1</span>; i &lt;= ps; i++) {
                                pages.push(i);
                            }
                        } <span class="hljs-keyword">else</span> {
                            pages.push(p);
                            <span class="hljs-keyword">while</span> (<span class="hljs-literal">true</span>) {
                                <span class="hljs-keyword">if</span> (pages.length &gt;= s) {
                                    <span class="hljs-keyword">break</span>;
                                }
                                <span class="hljs-keyword">if</span> (l &gt; <span class="hljs-number">1</span>) {
                                    pages.unshift(--l);
                                }
                                <span class="hljs-keyword">if</span> (pages.length &gt;= s) {
                                    <span class="hljs-keyword">break</span>;
                                }
                                <span class="hljs-keyword">if</span> (r &lt; ps) {
                                    pages.push(++r);
                                }
                            }
                        }
                        <span class="hljs-keyword">return</span> pages;
                    }
                }
            });
        </span><span class="hljs-tag">&lt;/<span class="hljs-title">script</span>&gt;</span>
    <span class="hljs-tag">&lt;/<span class="hljs-title">body</span>&gt;</span>
<span class="hljs-tag">&lt;/<span class="hljs-title">html</span>&gt;</span></span>
</code></pre>

选了菜单之后：
1、点击分页两次后出现重复渲染。
2、ms-class="['btn-group', (@open?'open':'')]" 修改@open值无反应

**Comment by RubyLouvre** [comment]
我正在去掉一些强力的缓存

https://github.com/RubyLouvre/avalon/tree/master/components/select

**Comment by RubyLouvre** [comment]
已经搞定!

**Comment by juefeng** [comment]
辛苦了

**Comment by juefeng** [comment]
@RubyLouvre 
测试 /*! built in 2016-6-16:19 version 2.09 by 司徒正美 */
上面的代码 组件ms-pager加上这个之后 
<pre><code class="hljs">onInit: <span class="hljs-function"><span class="hljs-keyword">function</span><span class="hljs-params">(e)</span></span>{
                        <span class="hljs-keyword">var</span> vm = e.vmodel;
                        vm.total_page = <span class="hljs-number">40</span>;
                        vm.pages = [<span class="hljs-number">1</span>,<span class="hljs-number">2</span>,<span class="hljs-number">3</span>,<span class="hljs-number">4</span>,<span class="hljs-number">5</span>,<span class="hljs-number">6</span>,<span class="hljs-number">7</span>];
                        <span class="hljs-comment">// this.total_page = 40;</span>
                        <span class="hljs-comment">// this.pages = [1,2,3,4,5,6,7];</span>
                    },
</code></pre>

组件ms-pager中的ms-for不渲染(消失了)

**Comment by juefeng** [comment]
额。是这样有改动变量值的
<pre><code class="hljs">onInit: <span class="hljs-function"><span class="hljs-keyword">function</span><span class="hljs-params">(e)</span></span>{
                        <span class="hljs-keyword">var</span> vm = e.vmodel;
                        vm.total_page = <span class="hljs-number">30</span>;
                        vm.pages = [<span class="hljs-number">1</span>,<span class="hljs-number">2</span>,<span class="hljs-number">3</span>,<span class="hljs-number">4</span>,<span class="hljs-number">5</span>,<span class="hljs-number">6</span>];
                        <span class="hljs-comment">// this.total_page = 40;</span>
                        <span class="hljs-comment">// this.pages = [1,2,3,4,5,6,7];</span>
                    },
</code></pre>

**Comment by RubyLouvre** [comment]
例子能完整一点吗
