### ISSUE TITLE
ms-validate中validateInBlur和validateInKeyup设置false无效

### ISSUE THREAD

**Issue by shanzhongke** [RubyLouvre/avalon#1469]
validateInBlur和validateInKeyup设置false无效 相应事件还是会触发验证 其他几个配置项没试
`<!DOCTYPE html>
<html>

	<head>
		<title>ms-validate</title>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<script src="//cdn.bootcss.com/avalon.js/2.0s/avalon.js"></script>
		<script>
			var vm = avalon.define({
				$id: "test",
				aaa: "",
				bbb: '',
				ccc: '',
				validate: {
					onError: function(reasons) {
						reasons.forEach(function(reason) {
							console.log(reason.getMessage())
						})
					},
					onValidateAll: function(reasons) {
						if (reasons.length) {
							console.log(reasons)
						} else {
							console.log('全部通过')
						}
					},
					validateInKeyup:false,
					validateInBlur:false
				}
			})
		</script>
	</head>

	<body ms-controller="test">
		<form ms-validate="@validate">
			<p><input ms-duplex="@aaa" placeholder="username" ms-rules='{required:true,chs:true}'>{{@aaa}}</p>
			<p><input type="password" id="pw" placeholder="password" ms-rules='{required:true}' ms-duplex="@bbb" /></p>
			<p><input type="password" ms-rules='{required:true,equalto:"pw"}' placeholder="再填一次" ms-duplex="@ccc | change" /></p>
			<p><input type="submit" value="submit" /></p>
		</form>
	</body>

</html>`

**Comment by RubyLouvre** [comment]
已经处理，请到这里下载 https://github.com/RubyLouvre/avalon/tree/master/dist
