### ISSUE TITLE
官网的一个小bug

### ISSUE THREAD

**Issue by jinwyp** [RubyLouvre/avalon#1478]
http://avalonjs.coding.me/cn/ms-attr.html

页面 使用滚轮往下滚 滚不了,因为左边页面高度不够, 结构出现抖动的现象, 不知道到人还以为是滚不了呢.

**Comment by areyouse7en** [comment]
我觉得司徒也是懒得弄官网了。。
看这里吧
https://segmentfault.com/a/1190000004886685

**Comment by shanzhongke** [comment]
官网bug不止这一个。。自定义标签里的dom插入点这一章根本点不进去 需要用调试器  一些文章也有重复文字

**Comment by RubyLouvre** [comment]
ms-attr是要求你点左边的菜单啊，我都全部高亮了！因为不可能 在一个页面上把所有指令都写上，这么多例子会产生大量的VM，会互相干扰的
