### ISSUE TITLE
avalon1.4，文本框有焦点时使用js脚本修改值，会导致其绑定的vm属性无法更新

### ISSUE THREAD

**Issue by mirari** [RubyLouvre/avalon#1480]
IE11和Chrome50均遇到此问题，1.4最新版本第3789行
```
function newSetter(value) { // jshint ignore:line
                setters[this.tagName].call(this, value)
                if (!this.msFocus && this.avalonSetter) {
                    this.avalonSetter()
                }
        }
```

在日期选择器操作文本框等场景会遇到，按以下步骤使用时会出现问题：
1.文本框获得焦点
2.使用val()或者.value修改文本框的值
3.使用blur()使文本框失焦
第2步虽然触发了change事件，但是因为文本框正处于焦点，avalonSetter不会执行，结果文本框的值变了，对应的VM属性却没有变化。

**Comment by RubyLouvre** [comment]
是啊，必须失去焦点才更新

**Comment by mirari** [comment]
但是第三步失去焦点的时候还是没有更新，结果input的value跟vm属性就不一致了

**Comment by RubyLouvre** [comment]
那你自己更新时将msFocus属性变成false就行了
