### ISSUE TITLE
嵌套组件构造过程

### ISSUE THREAD

**Issue by chenbogen** [RubyLouvre/avalon#1484]
遇到一个奇怪的问题，如果是动态创建一个组件，是不能保正组件包含的组件会先完成到可以用的情况喔！意思是外层能用不保证内层的组件能用，这可能是发生在内层组件重写了$contructor的情况，外层的$refs没有找到里面的组件， 也没有回调外层组件的$childReady。
版本是：avalon.1.56

**Comment by RubyLouvre** [comment]
1.5要求子组件ready后，才触发父组件的$ready

**Comment by chenbogen** [comment]
多谢回复。
还有一个问题：
我在使用oniui的avalon.dialog.js， 发现dialog.js里有$ready,但我有这样的组件HTML结构：
<div ms-click="clicktt">{{mytestname}}</div>
<oni:dialog ms-attr-identifier="moods2_{{$id__}}"></oni:dialog>
<oni:dialog ms-attr-identifier="moods3_{{$id__}}"></oni:dialog>

在控制台输出的是：
父$ready
dialog id: moods2_mytest788599370054
dialog id: moods3_mytest788599370054

子组件没有在父组件前运行$ready。请问一下，为什么会这样呢？

**Comment by RubyLouvre** [comment]
因为它是基于定时器与DOM事件机制的，因此不太稳定！
