### ISSUE TITLE
avalon2 在实现全选功能时的双工绑定存在兼容性问题

### ISSUE THREAD

**Issue by duanSD** [RubyLouvre/avalon#1494]
avalon2 在实现全选功能时的双工绑定存在兼容性问题 在safrai中无法做单选操作。会自 动全选。自动全取消，我看了一个是双工绑定产生的问题，用司徒正美的那个 全选的实例在safrai浏览器都没法正常操作。小司徒解决一下。
ms-duplex safrai在造成了，重复渲染。所以在safrai中才会不停的选中，取消，2.09中也没有解决这个问题

**Comment by ko300** [comment]
ms-duplex-checked闪动的问题，前两天修复了。
我在ios上测试没问题，可以更新最新版本试下。

**Comment by duanSD** [comment]
这个问题在搜狗浏览器里面还是存。并且框架好像完全不兼容搜狐浏览器。var obj = Object.getOwnPropertyDescriptor(ep,'innerHTML')，在搜狗中无法取到obj

**Comment by RubyLouvre** [comment]
请给出完整例子

**Comment by duanSD** [comment]
是在组件使用时产生的问题 你在框架中找到那行代码就知道什么回事了。刚出来的2.10也存在这问题加个检测就OK了，现在2.10中我也发现表单验证回调中。没法用avalon.vmodels 中取到的是一个空对象。不知道回什么。

**Comment by RubyLouvre** [comment]
重新起一个ISSUE，贴一个简单 的页面啊！你都不给页面！
