### ISSUE TITLE
绑定数组时 动态变更数组会存在没法正常渲染的情况 是由于用了ms-if的条件来操作这个数组。改成ms-if就好了

### ISSUE THREAD

**Issue by duanSD** [RubyLouvre/avalon#1495]

**Comment by duanSD** [comment]
我双工组定日期输入控制时。手动输入的是可以取到的。但是用日期框选择的。或用输入法输入的中文就会取不到。必须手机操作输入框才能在绑定属性中取到value.我调试了一下，好像是非手动输入在Input中没有进行监控

**Comment by RubyLouvre** [comment]
使用filterBy吧
