### ISSUE TITLE
[2.0.7] Bug? ms-click绑定同一函数的不同参数，结果竟然相同

### ISSUE THREAD

**Issue by jinwyp** [RubyLouvre/avalon#1497]
使用bower 安装的avalon最新版
chrome 51.0.2704.63

例如做一个分页功能， 上一页按钮 和 下一页按钮 绑定的功能

```
<a href="" aria-label="Previous" ms-click="@changePagination(@orderCurrentPage-1, $event)">
     <span aria-hidden="true" >< 上一页</span>
</a>
<a href="" aria-label="Next" ms-click="@changePagination(@orderCurrentPage+1, $event)">
    <span aria-hidden="true">下一页 ></span>
</a>

```

点击上一页的效果的效果竟然 与下一页相同， 都是+1 的效果。  感觉是个bug。

而且令人奇怪的是， 如果给@changePagination(@orderCurrentPage-1, $event, '')  加上第三个参数， （不改变该changePagination 函数的定义代码） 功能竟然正常了。

**Comment by areyouse7en** [comment]
用最新版，这个bug已经修复了。https://github.com/RubyLouvre/avalon/issues/1458

> /*! built in 2016-6-16:22 version 2.09 by 司徒正美 */

**Comment by RubyLouvre** [comment]
LS将你的版本给他，打tag的，

最近版本太多了
