### ISSUE TITLE
在添加组件的时候框架内出现扫描元系的时候出现未找到的vnode的情况下会阻塞其它的代码执行。会使整个组件失效。

### ISSUE THREAD

**Issue by duanSD** [RubyLouvre/avalon#1500]
建议框架能有一定的容错性。每次使用你的新一些的框架都还需要调试你框架，挺麻烦的。特别是一些基本的能力检测，希望能做些优化。

**Comment by duanSD** [comment]
还有双工绑定好像没有属性劫持一样。我在input框中从日期控件添加的日期数据。没法获取到

**Comment by RubyLouvre** [comment]
日期控件大多数是新件另一个input，不是原来的input，因此获取不了。必须找此控件的回调函数，与vm的$watch机制一起搭配使用
