### ISSUE TITLE
avalon 1.5怎么获得select中value和text

### ISSUE THREAD

**Issue by koeltp** [RubyLouvre/avalon#1503]
你好！
我找了很久怎么avalon 1.5怎么获得select中value和text，但一直没有找到解决办法，看到都是有value就会获得value，没有value就获得text，我想两个都同时获取到，只有请求大神赐福。谢谢。

**Comment by RubyLouvre** [comment]
这个使用JQ吧，都是取value

**Comment by koeltp** [comment]
目前已用jq解决了，但非常感谢大神提供Avalon的解决方案。
