### ISSUE TITLE
自定义组件上ms-if失效

### ISSUE THREAD

**Issue by shanzhongke** [RubyLouvre/avalon#1504]
`<xmp ms-if="@show" ms-widget='[{is:"ms-dialog"}]'></xmp>`
模板依旧会被渲染出来，只能在父级元素上加ms-if
/*! built in 2016-6-16:22 version 2.09 by 司徒正美 */

**Comment by RubyLouvre** [comment]
ms-widget的优先级高于ms-if,翻看所有指令的源码，里面都有一个priority属性
具体为
```
ms-imporant ms-controller ms-for ms-widget ms-effect ms-if   ...

```
ms-duplex的优先级最低，当同一个元素的所有指令及其内部的所有指令执行完，才执行ms-duplex
