### ISSUE TITLE
avalon2.09  无法通过ms-html递归迭代了

### ISSUE THREAD

**Issue by gogtz** [RubyLouvre/avalon#1506]
avalon2.09  无法通过ms-html递归迭代了   2.06版本可以，我用主页里无限树的例子试过了

树的例子：http://avalonjs.coding.me/cn/examples.html

**Comment by gogtz** [comment]
我更新了最后一个版本，无此问题了，不好意思，以后我会先更新版本确认问题再提Issues的，辛苦了

**Comment by gogtz** [comment]
这是avalon2官网例子中tree的代码，用2.1.0版本，tree只渲染了第一层，明显是ms-html="@tmpl"无效了

<pre>
&lt;!DOCTYPE html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
    &lt;meta charset="UTF-8"&gt;
    &lt;title&gt;Title&lt;/title&gt;
    &lt;script type="text/javascript" src="avalon.js"&gt;&lt;/script&gt;
&lt;/head&gt;
&lt;body&gt;
&lt;blockquote&gt;
    &lt;div ms-controller="tree"&gt;
        &lt;ul ms-for="el in @tree"&gt;{{el.text}}
            &lt;span ms-click='@toggle($event,el)' ms-text="@trigger(el)"&gt;&lt;/span&gt;
            &lt;div ms-html="@tmpl" ms-visible="el.subtree.length " &gt;&lt;/div&gt;
        &lt;/ul&gt;
    &lt;/div&gt;
    &lt;script&gt;
        avalon.define({
            $id: "tree",
            trigger: function (el) {
                if (el.subtree &amp;&amp; el.subtree.length) {
                    return el.open ? '[+]' : '[-]'
                } else {
                    return ''
                }
            },
            toggle: function (event, elem) {
                var el = event.target
                elem.open = el.open = !el.open
                var tree = el.nextElementSibling
                tree.style.display = el.open ? '' : 'none'
            },
            tree: [
                {text: "aaa", open: 1, subtree: [
                    {text: 1111, open: 1, subtree: []},
                    {text: 2222, open: 1, subtree: [
                        {text: 777, open: 1, subtree: []}
                    ]},
                    {text: 3333, open: 1, subtree: [
                        {text: 8888, open: 1, subtree: []},
                        {text: 999, open: 1, subtree: []}
                    ]}
                ]},
                {text: "bbb", open: 1, subtree: [
                    {text: 4444, open: 1, subtree: []},
                    {text: 5555, open: 1, subtree: []},
                    {text: 6666, open: 1, subtree: []}
                ]},
                {text: "ccc", open: 1, subtree: []},
                {text: "ddd", open: 1, subtree: []},
                {text: "eee", open: 1, subtree: [
                    {text: 1234, open: 1, subtree: []}
                ]},
                {text: "fff", open: 1, subtree: []}
            ],
            tmpl: "&lt;ul ms-for='el in el.subtree'&gt;&lt;li&gt;{{el.text}}&lt;span ms-click='@toggle($event,el)' ms-text='@trigger(el)'&gt;&lt;/span&gt;&lt;div ms-html='@tmpl' ms-visible='el.subtree.length '&gt;xxx&lt;/div&gt;&lt;/li&gt;&lt;/ul&gt;"

        })
    &lt;/script&gt;
&lt;/blockquote&gt;
&lt;/body&gt;
&lt;/html&gt;
</pre>

**Comment by RubyLouvre** [comment]
知道了，我源码了漏了东西。现在好了
