### ISSUE TITLE
这个问题在搜狗浏览器里面还是存。并且框架好像完全不兼容搜狐浏览器。var obj = Object.getOwnPropertyDescriptor(ep,'innerHTML')，在搜狗中无法取到obj

### ISSUE THREAD

**Issue by duanSD** [RubyLouvre/avalon#1507]
框架好像完全不兼容搜狐浏览器。var obj = Object.getOwnPropertyDescriptor(ep,'innerHTML')，在搜狗中无法取到obj,把它进行检测后能渲染页面。便是没法更新 是组件处理那一块的问题吧。在这浏览器中没法取到Element的innerHTML
产生的问题是组件内的ms-for没法渲染数据

**Comment by RubyLouvre** [comment]
写一个完整的例子上来 类似这样的 https://github.com/RubyLouvre/avalon/issues/1483

**Comment by RubyLouvre** [comment]
什么问题啊，avalon好像只用它来监听元素是否被移除
```
 //访问器属性需要用getOwnPropertyDescriptor处理
    var ep = Element.prototype, oldSetter
    function newSetter(html) {
        var all = avalon.slice(this.getElementsByTagName('*'))
        oldSetter.call(this, html)
        fireDisposedComponents(all)
    }
    if (!Object.getOwnPropertyDescriptor) {
        oldSetter = ep.__lookupSetter__('innerHTML')
        ep.__defineSetter__('innerHTML', newSetter)
    } else {
        var obj = Object.getOwnPropertyDescriptor(ep, 'innerHTML')
        oldSetter = obj.set
        obj.set = newSetter
        Object.defineProperty(ep, 'innerHTML', obj)
    }

```

**Comment by pod4g** [comment]
mark

**Comment by duanSD** [comment]
//访问器属性需要用getOwnPropertyDescriptor处理
    var ep = Element.prototype, oldSetter
    function newSetter(html) {
        var all = avalon.slice(this.getElementsByTagName('*'))
        oldSetter.call(this, html)
        fireDisposedComponents(all)
    }
    if (!Object.getOwnPropertyDescriptor) {
        oldSetter = ep.__lookupSetter__('innerHTML')
        ep.__defineSetter__('innerHTML', newSetter)
    } else {
        var obj = Object.getOwnPropertyDescriptor(ep, 'innerHTML')
        oldSetter = obj.set
        obj.set = newSetter
        Object.defineProperty(ep, 'innerHTML', obj)
    }
我添加了个obj的检测就没问题了。

**Comment by RubyLouvre** [comment]
什么意思？

**Comment by RubyLouvre** [comment]
人呢？

**Comment by duanSD** [comment]
var obj = Object.getOwnPropertyDescriptor(ep, 'innerHTML')
       if(obj){ 
        oldSetter = obj.set
        obj.set = newSetter
        Object.defineProperty(ep, 'innerHTML', obj)
       }

只有这样子。还能在搜狗浏览器里正常跑起来

**Comment by RubyLouvre** [comment]
求完整的代码，innerHTML那部分的

**Comment by RubyLouvre** [comment]
这PC上的搜狗吗，window下？

**Comment by duanSD** [comment]
是的。这不是大问题。细节我也懒得整理了。反正解决就OK了。avalon2比1要进步很多。主要在通用组件上不是很完善 。有些项目要转到avalon2上现来。有原来的oniui的组件用不了。需要重新做组件。比较麻烦。我有偿试把原来的组件转换过来。但发现并不是那么简单。
