### ISSUE TITLE
html标签内的&nbsp;转换错误，变成文本了

### ISSUE THREAD

**Issue by gogtz** [RubyLouvre/avalon#1513]
<pre>
&lt;!DOCTYPE html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
    &lt;meta charset="UTF-8"&gt;
    &lt;title&gt;Title&lt;/title&gt;
    &lt;script type="text/javascript" src="/vendor/plug-in/avalon2/avalon.js"&gt;&lt;/script&gt;
&lt;/head&gt;
&lt;body&gt;
&lt;blockquote&gt;
    &lt;div ms-controller="tree" id="tree"&gt;
        &lt;div id="btn"&gt; &nbsp; &nbsp; &lt;/div&gt;
        &lt;br/&gt;&lt;span style="color:red"&gt;html标签内的&amp;nbsp;转换错误，变成文本了，&amp;amp;没问题&lt;/span&gt;
    &lt;/div&gt;
    &lt;script&gt;
        avalon.define({
            $id: "tree"
        });
    &lt;/script&gt;
&lt;/blockquote&gt;
&lt;/body&gt;
&lt;/html&gt;
</pre>

**Comment by weeksun23** [comment]
这个我也遇到了。。。求解

**Comment by gogtz** [comment]
这个问题在2.09版本里没有，应该是个小问题，等着正美修复就好

**Comment by RubyLouvre** [comment]
什么意思啊？
你是说#btn中的空白吗

这个avalon与IE6－8都会去掉

**Comment by weeksun23** [comment]
```html
       <div class="modal-header" ms-if='@title'>
        <button type="button" class="close" ms-click='@close(null)'><span>&times;</span></button>
        <h4 class="modal-title" ms-html="@title"></h4>
      </div>
```
这段代码作为模板后，这个&times ;也变成文本了，就是bootstrap的对话框的关闭按钮

**Comment by RubyLouvre** [comment]
升到2.1.0还有吗？
我看到 `&times`不是变成一个X号吗

**Comment by RubyLouvre** [comment]
2.1.0好像没有这问题了

**Comment by weeksun23** [comment]
OK 谢谢

**Comment by RubyLouvre** [comment]
没事通知一下
