### ISSUE TITLE
组件的模板中的&copy;&times;还是当做字符串显示出来了

### ISSUE THREAD

**Issue by weeksun23** [RubyLouvre/avalon#1519]
在最新的2.10版本中实测：
```html
<body ms-controller="start" class='ms-controller'>
  <xmp ms-widget="[{is : 'test'},@$config]"></xmp>
  <script src='../src2/avalon.js'></script>
  <script>
    avalon.component("test",{
      template : "<div>asd231&copy;&times;</div>",
      defaults : {

      }
    });
    avalon.define({
      $id : "start",
      $config : {

      }
    });
  </script>
</body>
```

**Comment by RubyLouvre** [comment]
嗯，正在处理

**Comment by gogtz** [comment]
这个问题主要是avalon.js中VText1568行document.createTextNode(this.nodeValue)的问题，document.createTextNode不能很好的转换HTML转义符！
------------------------------------------------------------------------------------------------------------------
我的解决方案
将1563行VText.prototype.toDOM方法修改为如下
<pre>
toDOM: function () {
    /* add Start by benbean */
    p = document.createElement("p");
    p.innerHTML = this.nodeValue;
    return p.childNodes[0].cloneNode();
    /* add End */
    //return document.createTextNode(this.nodeValue)
},
</pre>
这样，转换文本节点就可以了，但这样的修改会引起在reconcile方法的4322行，空白节点的删除中产生死循环，所以将4322行的修改为如下
<pre>
    //如果是空白节点,移除后不变索引,后面的节点跟上来
    /* modify Start by benben */
    var nv = vnodes[index].nodeValue;
    if(nv && /^(?:&nbsp;)+$/.test(nv.replace(/\s/g, ''))) {
        // 只删除真的空节点，不删除&nbsp;节点
        index++
    } else {
        parent.removeChild(el);
    }
    /* modify End */
    continue
</pre>

不知道我的方案是否可行，请正美参考~~~

**Comment by gogtz** [comment]
看到上午十点正美更新的代码有些改动，又试了一下

1563行VText.prototype.toDOM方法如上方修改，保持不变，主要解决&copy;&times;未有效转换

4296行reconcile方法做如下修改
<pre>
	function reconcile(nodes, vnodes, parent) {
	    //遍平化虚拟DOM树
	    vnodes = flatten(vnodes)
	    var map = {}
	    vnodes.forEach(function (el, index) {
	        map[index] = getType(el)
	    })
	    var newNodes = [], change = false, el, i = 0
	    while (el = nodes[i++]) {
	        var vtype = getType(el)
	        var v = newNodes.length
			/// add Start By benben   <<---------------------------------------------修改
			var nv = vnodes[v] && vnodes[v].nodeValue
			/// add End
	        if (map[v] == vtype) {
	            newNodes.push(el)
	            var vnode = vnodes[v]
	            if (vnode.dynamic) {
	                vnode.dom = el
	            }
	            if (el.nodeType === 1 && !vnode.isVoidTag && !containers[vnode.type]) {
	                reconcile(el.childNodes, vnode.children, el)
	            }
			/// add Start by benben <<---------------------------------------------修改
	        } else if(nv && /^(?:&amp;nbsp;)+$/.test(nv.replace(/\s/g, ''))) {
				//  解决&lt;button&gt;&amp;nbsp;&amp;nbsp;&lt;/button&gt;变&lt;button&gt;&lt;/button&gt;的情况
				newNodes.push(el)
			/// add End
			} else {
	            change = true
	            if (rforRange.test(map[v])) {
	                var vv = vnodes[v]
	                var nn = document.createComment(vv.nodeValue)
	                vv.dom = nn
	                newNodes.push(nn)
	            }
	        }
	    }
	    if (change) {
	        var f = document.createDocumentFragment(), i = 0
	        while (el = newNodes[i++]) {
	            f.appendChild(el)
	        }
	        while (parent.firstChild) {
	          //  console.log(parent.firstChild)
	            parent.removeChild(parent.firstChild)
	        }
	        parent.appendChild(f)
	    }
	}
</pre>

**Comment by RubyLouvre** [comment]
嗯'
但1
Ie6到8下for指令有bug

**Comment by gogtz** [comment]
正好借机会学习源码了，，，具体的修改方案你定，我的方案仅为参考

**Comment by RubyLouvre** [comment]
```html
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <script src="../dist/avalon.js"></script>
    </head>

    <body ms-controller="start" class='ms-controller'>
    <xmp ms-widget="[{is : 'test'},@$config]"></xmp>
    <script src='../src2/avalon.js'></script>
    <script>
        avalon.component("test", {
            template: "<div>asd231&copy;&times;</div>",
            defaults: {
            }
        });
        avalon.define({
            $id: "start",
            bbb: "<span>ddd&nbsp;&copy;&times;</span>",
            $config: {
            }
        });
    </script>
    <div ms-text="@bbb"></div>
    <div ms-html="@bbb"></div>
</body>
</html>



````

**Comment by RubyLouvre** [comment]
```javascript
VText.prototype = {
    constructor: VText,
    toDOM: function () {
       var a =  VText.decoder = VText.decoder || document.createElement('p')
       a.innerHTML = this.nodeValue
       return a.removeChild(a.firstChild) 
    },
    toHTML: function () {
        return this.nodeValue
    }
}

````

**Comment by RubyLouvre** [comment]
终于告一段落
