### ISSUE TITLE
求指教，ms-if  的一个问题

### ISSUE THREAD

**Issue by Jackey-Sparrow** [RubyLouvre/avalon#1521]
ms-if值设置为true后，跑到源码里面，最关键的一行代码是
4641行： elem.parentNode.replaceChild(keep, elem) 。
请问replacechild后，有什么方法可以知道这个操作已经完成？ 

版本：

/*==================================================
 Copyright (c) 2013-2015 司徒正美 and other contributors
 http://www.cnblogs.com/rubylouvre/
 https://github.com/RubyLouvre
 http://weibo.com/jslouvre/
 
 Released under the MIT license
 avalon.shim.js 1.5.6 built in 2015.12.28
 support IE6+ and other browsers
 ==================================================*/

**Comment by RubyLouvre** [comment]
知道不了，因为整个流程是异步的
