### ISSUE TITLE
ie 光标问题

### ISSUE THREAD

**Issue by zhouzm** [RubyLouvre/avalon#1524]
xp -- ie6:
1. 在 input/textarea 内首次输入字符或粘贴或删除不会触发刷新，但首次选中替换输入可以。
2. 在 input/textarea 内删除时(光标位于文本 **中** 部或 **尾** 部，delete/backspace)，包括选中文字删除，光标会闪烁到文字 **首** 部，如果选中部分位于尾部则正常。
3. 在 input/textarea 内输入时(光标位于文本首部或中部)，光标会闪烁到文本 **尾** 部。如果选中文本中部内容进行替换输入，输入内容错位出现在文本 **首** 部，如果是选中后粘贴替换则不会错位。

win7 -- ie8
1.在 input/textarea 内删除、输入或粘贴时(光标位于文本 **首** 部或 **中** 部)，光标会闪烁到文字 **尾** 部。

**Comment by RubyLouvre** [comment]
写例子！

**Comment by zhouzm** [comment]
就是教程里的例子：

```html
<!DOCTYPE html>
<html>
    <head>
        <title>TODO supply a title</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="./dist/avalon.js"></script>
        <script>
            var vm = avalon.define({
                $id: "test",
                a: 111
            })
        </script>
        <style>
            .ms-controller{
                display:none;
            }
        </style>
    </head>
    <body>
        <div ms-controller="test">
            <input ms-duplex="@a" />
            <textarea ms-duplex="@a" ></textarea>
            <p>{{@a}}</p>
        </div>
    </body>
</html>
```

**Comment by gogtz** [comment]
正美，关于这个问题，我单步调了一下源码，调查结果如下：

原因1：function getCaret(field)  这个方法在IE下获取光标的部分有问题，这个问题我以前遇到过，并参考了<a href="http://www.zhangxinxu.com/wordpress/2011/04/js-range-html%e6%96%87%e6%a1%a3%e6%96%87%e5%ad%97%e5%86%85%e5%ae%b9%e9%80%89%e4%b8%ad%e3%80%81%e5%ba%93%e5%8f%8a%e5%ba%94%e7%94%a8%e4%bb%8b%e7%bb%8d/">js-range-html文档文字内容选中、库及应用介绍</a>找到了解决方案；
getCaret方法做如下修改
<pre>
function getCaret(field) {
    var start = NaN, end = NaN
    if (field.setSelectionRange) {
        start = field.selectionStart
        end = field.selectionEnd
    } else if (document.selection && document.selection.createRange) {
		/// modify Start by benben
		var range = document.selection.createRange(),
			length = range.text.length,
			dupl;
		// input与textarea取光标位置的方法是不同的
		if(field.nodeName === 'INPUT') {
			dupl = range;
			range.moveStart('character', -field.value.length);
		} else {
			dupl = range.duplicate();
			range.moveToElementText(field);
			dupl.setEndPoint('StartToStart', range);
		}
		// textarea的文本值中\r会影响到光标位置，所以要处理一下
		end = dupl.text.replace( /\r/g, '' ).length;
		start = end - length;
		//start = 0 - range.duplicate().moveStart('character', -100000)
		//end = start + range.text.length
		/// modify End
    }
    return {
        start: start,
        end: end
    }
}
</pre>
原因2：在input内输入时，function updateModelHandle()方法会被调用两次，在第二次调用时field.caretPos的值就不对了；
至于为什么会调用两次，小弟接触avalon2不久无法深入跟踪，只能暂做如下修改：
<pre>
// 修改if的条件，让第二次调用不再取光标位置
if (elem.caret && !field.caretPos) {
	try {
		var pos = field.getCaret(elem)
		if (pos.start === pos.end || pos.start + 1 === pos.end) {
			field.caretPos = pos
		}
	} catch (e) {
		avalon.warn('fixCaret error', e)
	}
}
</pre>
原因3：恢复光标位置时，做一下延时，以前我记得只有IE中才要这样做，在avalon2中不知道会不会和原因2的两次调用有关，无法深度跟踪，仅能做如下修改
<pre>
// avalon.js 4728行左右
updateView[data.type].call(data)
if (dom.caret) {
	setTimeout(function() {
		var pos = data.caretPos
		pos && data.setCaret(dom, pos.start, pos.end)
		data.caretPos = null
	}, 1);
}
</pre>
上述三个修改后，光标问题解决了，但是IE7下，文本框首次输入不响应的问题依旧

我只是在chromium47和IE10的7~10模式下做了测试，，仅供参考；

**Comment by RubyLouvre** [comment]
那你继续努力一下，认真看一下源码

**Comment by gogtz** [comment]
努力了，看了一上午源码，有些位置跟踪不下去了，调用两次的问题和框架的机制有关吧，短时间内还无法完全理解

**Comment by RubyLouvre** [comment]
IE6-8的onpropertychange 有 BUG,加一个keyup事件可以解决

https://github.com/digitalBush/jquery.maskedinput/blob/master/src/jquery.maskedinput.js

**Comment by RubyLouvre** [comment]
更新一下，我做了大量修改

**Comment by RubyLouvre** [comment]
IE6下调试用
```


avalon.log = function(){
    var str =  avalon.slice(arguments).join(" ")
    avalon.ready(function(){
      var div =  document.createElement('div')
      document.body.appendChild(div)
      div.innerHTML = str
    })
}
```
