### ISSUE TITLE
在Ios真机上使用了tap以后，样式丢失

### ISSUE THREAD

**Issue by bIgMunich** [RubyLouvre/avalon#1527]
你好，管理员
      这个问题上次提出来过一次，但是今天重新提一次，在Ios真机上利用webpack打包tap以后，avalon初始化样式丢失，谢谢

**Comment by bIgMunich** [comment]
这是用source在IOS上查看源代码的结果，和PC段查看源代码结果一样
![img_0076](https://cloud.githubusercontent.com/assets/16953690/16371189/7fa3edd0-3c77-11e6-8961-8b1882febb68.PNG)
![img_0077](https://cloud.githubusercontent.com/assets/16953690/16371195/86a1ebbe-3c77-11e6-93ea-e3f4bc8501fe.PNG)

**Comment by RubyLouvre** [comment]
样式丢失应该查看webpack 打包问题！

**Comment by RubyLouvre** [comment]
在这里学习 webpack  https://segmentfault.com/search?type=article&q=webpack

**Comment by RubyLouvre** [comment]
看一下人家怎么提ISSUE

https://github.com/RubyLouvre/avalon/issues/1526
不要截图！
自己在 PC上调好吧
