### ISSUE TITLE
问一个组件异步加载数据和事件给调用者使用的问题？

### ISSUE THREAD

**Issue by jinwyp** [RubyLouvre/avalon#1530]
1 例如我写一个 组件分页， 但传入的totalPages变量 是异步获取的数据， 导致orderListTotalPages共有多少分页没有正确初始化，如何解决？
```
<xmp ms-widget="{is:'ms-pagination', totalPages:@orderListTotalPages }"></xmp>
```

```
var vm = avalon.define({
                $id: "financialDetailsController",
                orderSearchText  : '',
                orderList        : [],
                orderListTotalPages : 1
})

$.ajax({
                url    : "/api/financial/order/details",
                method : "POST",
                data   : params1,
                success:function(data){

                    vm.orderList = data.list;
                    vm.orderListTotalPages = Math.ceil(data.count / data.pagesize);
                    console.log(vm.orderListTotalPages)
                }
            })
```

2 组件中的点击分页后， 需要把事件暴露出来给外部调用ajax重新获取数据，如何解决？ 相当于angular中指令的& 引用传函数如何实现？

**Comment by RubyLouvre** [comment]
在事件里，直接修改VM啊！

**Comment by jinwyp** [comment]
不知道为什么， orderListTotalPages变化后， 组件ms-pagination里面的totalPages 没有变化，双向绑定没起作用

**Comment by jinwyp** [comment]
问个问题，组件的参数名称要和外面传入的参数名称才可以双向绑定？  如 totalPages:@orderListTotalPages 要写成 totalPages:@totalPages 才可以双向绑定？

**Comment by RubyLouvre** [comment]
你的思路不对啊，你要搞一个配置对象
## 页面VM ##
```javascript
var vm  = avalon.define({
 $id: "test",
 pager: {
    totalPages:222,
    showPages: 10
 }
})
```
##  组件定义 ##
```javascript
//注意，如果你不带ms-， 那么就能使用ms-pager 自定义标签
avalon.component("pager", {
   template: template,
   defaults:  {
     showPages: 6,
    totalPages: 15,
    currentPage:1,
    pages: [] //pages是组件的内部方法根据showPages, totalPages计算出来的，不是外面传进来的，也是不一开始规定好的
   }
})

```
## 页面调用 ##
```html
<wbr ms-widget="[{is: "pager"}, @pager]" />
```

## 异步调用 ##
```javascript
$.ajax({
                url    : "/api/financial/order/details",
                method : "POST",
                data   : params1,
                success:function(data){
                    vm.page.totalPages = Math.ceil(data.count / data.pagesize);
                    console.log(vm.orderListTotalPages)
                }
            })
```

**Comment by RubyLouvre** [comment]
totalPages:@totalPages 才可以双向绑定？

不是

**Comment by jinwyp** [comment]
在问几个问题
1 <wbr ms-widget="[{is: "pager"}, @pager]" /> 这种数组传值和 <xmp ms-widget="{is:'ms-pagination', totalPages:@orderListTotalPages }"></xmp>  这种对象传值有什么不同吗？
例如该例子里面是 对象传值 
https://github.com/RubyLouvre/avalon/blob/master/components/select/index.html


2 wbr, template 有什么区别， 文档写的是都没有孩子 但文档例子中 怎么template 还写了孩子节点 
http://avalonjs.coding.me/cn/ms-widget.html
<template ms-widget="@config" ><ms-dialog ms-widget="@config"></ms-dialog></template>

是不是文档写错了？

**Comment by RubyLouvre** [comment]
1.  都差不多，不过建议组件相关的东西都放在各自的配置对象中。第一种，由于是数组，avalon会做扁平化处理。并且页面上也相对干净些。

2.
wbr是半闭合标签，'<wbr />'
template是HTML5 的新标签，是开标签，它与DIV一样可以在里面放东西，但是它有一个特点，放了东西，它的children与childNodes都是0，这是基础知识啊，翻一下firefox的官网就能查到。

由于它们都没有孩子，因此不会给页面造成负担。
