### ISSUE TITLE
计算属性怎么没有用

### ISSUE THREAD

**Issue by koeltp** [RubyLouvre/avalon#1533]
http://avalonjs.github.io/#tutorial/concepts/computed.html
此页面中的fullName输入框没有随着我上面两个输入框的输入而变化，请大神赐教

`$computed: {
        MobileVlidCodeToggle: {
            get: function () {
                console.log("xxxx" + this.model.Gender);
                if (this.model.Gender == 1)
                    return true;
                return false;
            }
        }`

当我的this.model.Gender的值发生变化时，这个里面的console.log()并没有输入。

**Comment by RubyLouvre** [comment]
计算属性只能用于第一层属性上，太复杂了，依赖收集就出问题了

**Comment by RubyLouvre** [comment]
因此avalon2是废掉计算属性

**Comment by RubyLouvre** [comment]
建议直接看avalon2, http://avalonjs.coding.me/
其组件功能与动画功能，性能什么 比第一代强大多了

**Comment by koeltp** [comment]
学习了，在新一代项目引用了。再此一并谢谢大神。

**Comment by RubyLouvre** [comment]
嗯
