### ISSUE TITLE
data-for-rendered指令绑定问题

### ISSUE THREAD

**Issue by JaynLeaew** [RubyLouvre/avalon#1536]
模版：
`<tr  ms-for="($i, el) in @menus" data-for-rendered="@afterRendered"></tr>`

vm：
`var vm = avalon.define({`
  `$id: 'dt-menu',`
   `menus: [],`
   `afterRendered: function() {`
        `// actions to do`
  ` }`
`})`

浏览器报错：
`TypeError: __vmodel__.afterRendered is not a function(…) "parse on binding【 @afterRendered 】fail"`

调试发现`__vmodel__`引用的对象是`window`

**Comment by RubyLouvre** [comment]
搞定了！
