### ISSUE TITLE
checkbox的ms-duplex-checked的问题

### ISSUE THREAD

**Issue by gogtz** [RubyLouvre/avalon#1538]
已更新到最新版本，问题：点击change按钮，checked值改变后div的class未连动，昨天下午4点前的版本没有这个问题
代码如下
<pre>
<code>
&lt;!DOCTYPE html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
    &lt;meta charset="UTF-8"&gt;
    &lt;script type="text/javascript" src="/vendor/plug-in/avalon2/avalon.js"&gt;&lt;/script&gt;
    &lt;script type="text/javascript" src="/vendor/plug-in/jquery/jquery.js"&gt;&lt;/script&gt;
    &lt;style&gt;
        .red {
            color:red;
        }
    &lt;/style&gt;
&lt;/head&gt;
&lt;body&gt;
&lt;div ms-controller="tree"&gt;
    &lt;div ms-class="{red:@red}"&gt;哈哈哈&lt;/div&gt;
    &lt;input id="cb1" type="checkbox" ms-duplex-checked="@red"/&gt;
    &lt;input type="button" value="change" ms-click="@change"/&gt;
&lt;/div&gt;
&lt;/body&gt;
&lt;script&gt;

    avalon.define({
        $id: "tree",
        red: false,
        change: function() {
            var cb = document.getElementById('cb1');
            cb.checked = !cb.checked;
        }
    });
&lt;/script&gt;
&lt;/html&gt;
</code>
</pre>

**Comment by RubyLouvre** [comment]
当然不联动啊，为什么要联动啊！你是操作DOM！都不是操作数据！

**Comment by gogtz** [comment]
之前的版本联动啊

**Comment by RubyLouvre** [comment]
不可能，以前都没有处理checked! 你要操作VM，不能操作DOM啊，内部进的是虚拟DOM！你操作什么DOM啊！

**Comment by gogtz** [comment]
如果是jquery的checkbox插件的话，都是把checkbox隐藏，有事件控制checkbox的checked来实现的

**Comment by RubyLouvre** [comment]
之前也是走change事件，你改checked也不会触发change事件!

**Comment by RubyLouvre** [comment]
除非你插件内部 触发了change事件

**Comment by gogtz** [comment]
那双向绑定的意义何在？

**Comment by gogtz** [comment]
我刚刚试过，，换成昨天下午4点前的版本，是可以联动的

**Comment by RubyLouvre** [comment]
双向只是针对 value!你看一下vue, react ,angular那个能这么做。只有avalon还处理了value，其他只用事件。不会用到事件

**Comment by RubyLouvre** [comment]
```
 avalon.define({
        $id: "tree",
        red: false,
        change: function() {
            var cb = document.getElementById('cb1');
            cb.checked = !cb.checked;
           cb.click()
        }
    });
```

**Comment by gogtz** [comment]
要把操作写到change事件里？

**Comment by RubyLouvre** [comment]
你们在jquery插件的点击后回调反过来操作DOM

**Comment by RubyLouvre** [comment]
其他框架的双绑（V－》 VM）是使用事件的

**Comment by RubyLouvre** [comment]
不是改属性就能触发的

**Comment by RubyLouvre** [comment]
不同版本不一样，IE6－8是使用click,IE9＋是使用change

**Comment by gogtz** [comment]
哦，知道了。。。。checkbox可能是个特例吧，，它的checked比value用处大
那还是按标准来吧，我改改代码看看

**Comment by RubyLouvre** [comment]
你直接 封装一个fireEvent方法
将click, change 都触发一遍
不是jquery的trigger，那个只能触发JQ自己的事件

**Comment by RubyLouvre** [comment]
```
function fireClick(el) {
    if (el.click) {
        el.click()
    } else {
//https://developer.mozilla.org/samples/domref/dispatchEvent.html
        var evt = document.createEvent('MouseEvents')
        evt.initMouseEvent('click', true, true, window,
                0, 0, 0, 0, 0, false, false, false, false, 0, null);
        !el.dispatchEvent(evt);
    }
}
```

**Comment by RubyLouvre** [comment]
你应该在JQ的插件的回调里改vm的属性
