### ISSUE TITLE
360兼容模式下或者ie8下avalon2 ms-for循环不起作用

### ISSUE THREAD

**Issue by bihongbin3027** [RubyLouvre/avalon#1539]
```
<!DOCTYPE html>
<html>
    <head >
        <title>测试</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <script src="avalon2.js"></script>
        <script>
            var vm = avalon.define({
                $id: 'test',
                array: ["aaa","bbb","ccc","ddd"]
            })
        </script>
    </head>

    <body>
        <div ms-controller='test'>
            <ul>
	            <li ms-for="($index, el) in @array">
	            	{{el}} --- {{$index}}
	            </li>
	        </ul>
        </div>
    </body>
</html> 
```

**Comment by bihongbin3027** [comment]
<!DOCTYPE html>
<html>
    <head >
        <meta charset="utf-8">
    	<title>测试</title>
        <script type="text/javascript" src="http://cdn.bootcss.com/jquery/2.1.0/jquery.js"></script>
        <script>
            var vm = avalon.define({
                $id: 'test',
                array: ["aaa","bbb","ccc","ddd"]
            })
        </script>
    </head>
    <body>
        <div ms-controller='test'>
            <ul>
	            <li ms-for="($index, el) in @array">
	            	{{el}} --- {{$index}}
	            </li>
	        </ul>
        </div>
    </body>
</html>

**Comment by bihongbin3027** [comment]
![image](https://cloud.githubusercontent.com/assets/15045200/16445579/e142acb2-3e15-11e6-9c52-66029860b132.png)有这个错

**Comment by bihongbin3027** [comment]
![w2krv 4 t go vg y _ud7](https://cloud.githubusercontent.com/assets/15045200/16446079/5fb0314e-3e18-11e6-9f25-f03fe734e853.png) ie8-10还有edge浏览器都会出现这个报错

**Comment by RubyLouvre** [comment]
不是我说你，这是很古老的avalon版本，下个新版本就好了

![image](https://cloud.githubusercontent.com/assets/190846/16446857/69b0c5b0-3e1c-11e6-85ce-b85f1b15c240.png)
