### ISSUE TITLE
avalon2.1.0重写了ms-html后script，style等标签无法正常使用

### ISSUE THREAD

**Issue by Canox3** [RubyLouvre/avalon#1544]
在2.1.0版本之前 ms-html 解析时，包含script，style等标签是可以正确执行的。
新版本会在这些标签内显示undefined，如标签改为div则正确读取。

现在是不支持直接写这些标签了，还是需要用新的方法调用。

**Comment by RubyLouvre** [comment]
已经修复，并加入测试全家桶
