### ISSUE TITLE
avalon2.09 升级到2.1 报错

### ISSUE THREAD

**Issue by virgoboy** [RubyLouvre/avalon#1548]
TypeError: undefined is not an object (evaluating 'dom.nodeValue = vdom.nodeValue') at avalon.modern.js : 1916
IOS

**Comment by RubyLouvre** [comment]
升到昨天的版本看

然后提交一个简单可还原现场的例子

像这样

https://github.com/RubyLouvre/avalon/issues/1546

**Comment by RubyLouvre** [comment]
人呢，没人我就关了
