### ISSUE TITLE
2.13 duplex 无法中文输入

### ISSUE THREAD

**Issue by areyouse7en** [RubyLouvre/avalon#1550]
> built in 2016-7-2:12 version 2.13 by 司徒正美

搜狗输入法，中文。直接闪掉，输不了中文。

**Comment by RubyLouvre** [comment]
什么浏览器？给例子啊，这么久了还不会写ISSUE吗

**Comment by areyouse7en** [comment]
https://github.com/RubyLouvre/avalon/issues/1549

就是你刚解决的这个同样的例子啊。。所以我才不写的。。
chrome，搜狗浏览器

**Comment by aben711** [comment]
在录入中文的时候，录入拼音的数量都变成了空格显示在录入文字的前后
录入： 双向绑定 四个字 就变成 " 双向绑定                  "
avalon: v2.13  
chrome版本 50.0.2661.102 m

**Comment by RubyLouvre** [comment]
已经处理

**Comment by RubyLouvre** [comment]
如果不想升级，自己源码里 搜 compositionEnd方法
改成
```
function compositionEnd() {
    composing = false;
    setTimeout(updateVModel)
}
```
