### ISSUE TITLE
{{ }} 中三元表达式解析问题，注释for指令嵌套问题

### ISSUE THREAD

**Issue by gogtz** [RubyLouvre/avalon#1551]
at built in 2016-7-1:11 version 2.13

问题1:
这一句，{{ 'c-' + (idx1 &lt; 1 ? 'red' : idx1 &gt; 1 ? 'green' : 'blue') }}
控制台报错：Uncaught SyntaxError: Unexpected token ;
调试一下，这句被解析为：var __value__ = 'c-' + (idx1 &amp;lt; 1 ? 'red' : idx1 &amp;gt; 1 ? 'green' : 'blue')

问题2：
注释指令&lt;!--ms-for:(idx2, item2) in item1--&gt;，嵌套时，控制台报错：Uncaught TypeError: Cannot read property 'insertBefore' of undefined

例子代码：
<pre>
<code>
&lt;!DOCTYPE html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
    &lt;meta charset="UTF-8"&gt;
    &lt;script type="text/javascript" src="/vendor/plug-in/avalon2/avalon.js"&gt;&lt;/script&gt;
    &lt;script type="text/javascript" src="/vendor/plug-in/jquery/jquery.js"&gt;&lt;/script&gt;
    &lt;style&gt;
        .c-red {
            color: red;
        }
        .c-green {
            color: green;
        }
        .c-blue {
            color: blue;
        }
    &lt;/style&gt;
&lt;/head&gt;
&lt;body&gt;
&lt;div ms-controller="test"&gt;
    &lt;!--ms-for:(idx1, item1) in @arr--&gt;
    &lt;p&gt;Group这是标题&lt;/p&gt;
        &lt;!--ms-for:(idx2, item2) in item1--&gt;
        &lt;div&gt;内容1&lt;/div&gt;
        &lt;div ms-class="'c-' + (idx1 &lt; 1 ? 'red' : idx1 &gt; 1 ? 'green' : 'blue')"&gt;
            内容2 {{ 'c-' + (idx1 &lt; 1 ? 'red' : idx1 &gt; 1 ? 'green' : 'blue') }}
        &lt;/div&gt;
        &lt;!--ms-for-end:--&gt;
    &lt;!--ms-for-end:--&gt;
&lt;/div&gt;

&lt;/body&gt;
&lt;script&gt;
    avalon.define({
        $id: "test",
        arr: [
                'a', 'b', 'c'
        ]
    });
&lt;/script&gt;
&lt;/html&gt;
</code>
</pre>

**Comment by RubyLouvre** [comment]
第二个问题分明是语法错误
http://avalonjs.coding.me/cn/ms-for.html
