### ISSUE TITLE
再提，{{ }} 中三元表达式解析问题，注释for指令嵌套问题

### ISSUE THREAD

**Issue by gogtz** [RubyLouvre/avalon#1552]
at built in 2016-7-2:18 version 2.14
问题一：{{ }} 中三元表达式解析问题，控制台虽然不报错了，但画面的结果不对
例子中的结果是：内容2 {{ (idx1 

问题二，例子这样写不行，控制台报错，如果把里层的ms-for用DIV包一下就可以了

例子：
<pre>
<code>
&lt;!DOCTYPE html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
    &lt;meta charset="UTF-8"&gt;
    &lt;script type="text/javascript" src="/vendor/plug-in/avalon2/avalon.js"&gt;&lt;/script&gt;
    &lt;script type="text/javascript" src="/vendor/plug-in/jquery/jquery.js"&gt;&lt;/script&gt;
    &lt;style&gt;
        .c-red {
            color: red;
        }
        .c-green {
            color: green;
        }
        .c-blue {
            color: blue;
        }
    &lt;/style&gt;
&lt;/head&gt;
&lt;body&gt;
&lt;div ms-controller="test"&gt;
    &lt;!--ms-for:(idx1, item1) in @arr--&gt;
    &lt;p&gt;Group这是标题&lt;/p&gt;
        &lt;!--ms-for:(idx2, item2) in item1--&gt;
        &lt;div&gt;内容1&lt;/div&gt;
        &lt;div ms-class="'c-' + (idx1 &lt; 1 ? 'red' : idx1 &gt; 1 ? 'green' : 'blue')"&gt;
            内容2 {{ (idx1 &lt; 1 ? 'red' : idx1 &gt; 1 ? 'green' : 'blue') + '-' + item2 }}
        &lt;/div&gt;
        &lt;!--ms-for-end:--&gt;
    &lt;!--ms-for-end:--&gt;
&lt;/div&gt;

&lt;/body&gt;
&lt;script&gt;
    avalon.define({
        $id: "test",
        arr: [
            {a: 'a1',b:'b1'}, {a:'a2',b:'b2'}, {a:'a3',b:'b3'}
        ]
    });
&lt;/script&gt;
&lt;/html&gt;
</code>
</pre>

**Comment by RubyLouvre** [comment]
在第二个循环中包一层吧

此外升级一下

**Comment by RubyLouvre** [comment]
我加快新一代html parser的研发

**Comment by RubyLouvre** [comment]
```html

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script type="text/javascript" src="../dist/avalon.js"></script>
    <style>
        .c-red {
            color: red;
        }
        .c-green {
            color: green;
        }
        .c-blue {
            color: blue;
        }
    </style>
</head>
<body>
<div ms-controller="test">
    <!--ms-for:(idx1, item1) in @arr-->
        <p>Group这是标题</p>
        <div>
        <!--ms-for:(idx2, item2) in item1-->
        <div>内容1</div>
        <div aaa="<div>xxx</div>"
            ms-class="'c-' + (idx1 < 1 ? 'red' : idx1 > 1 ? 'green' : 'blue')">
            内容2 {{ (idx1 < 1 ? 'red' : idx1 > 1 ? 'green' : 'blue') + '-' + item2 }}

        </div>
       
        <!--ms-for-end:-->
        </div>
    <!--ms-for-end:-->
</div>

</body>
<script>
    var vm = avalon.define({
        $id: "test",
        arr: [
            {a: 'a1',b:'b1'}, {a:'a2',b:'b2'}, {a:'a3',b:'b3'}
        ]
    });
</script>
</html>

```

你为什么不使用ms-for啊

**Comment by RubyLouvre** [comment]
好了，现在你什么也不改也能了，发现是markRepeatRange方法的BUG

**Comment by RubyLouvre** [comment]
已经加入单元测试全家桶中
