### ISSUE TITLE
ie8 64位浏览器，多次加载页面，会出现avalon加载不了, avalon对象为null

### ISSUE THREAD

**Issue by hjc5345** [RubyLouvre/avalon#1554]
ie8 64位浏览器，多次加载页面，会出现avalon加载不了, avalon对象为null

求解决， 感谢～

avalon版本: 1.5.6
操作系统: win7 64位
浏览器: ie8 64位

用了seajs加载, 不知道会不会有影响

**Comment by RubyLouvre** [comment]
不要用这个。你应该用webpack打包后才用

**Comment by RubyLouvre** [comment]
那个是seajs的缓存BUG吧。avalon对象都没有，不能算avalon的BUG
