### ISSUE TITLE
onValidateAll 问题

### ISSUE THREAD

**Issue by shanzhongke** [RubyLouvre/avalon#1559]
onValidateAll这个回调的触发是只能通过submit事件和手动触发两种方式触发对吗？我看教程里说“整体验证后或调用了validateAll方法后触发”，validateAll这个就是手动触发吧？请问这个手动触发方法怎么调用？

**Comment by caolinjian** [comment]
同问

**Comment by areyouse7en** [comment]
同问

**Comment by RubyLouvre** [comment]
你在ms-validator的配置对象里设置了onValidateAll方法，再定义一个onInit方法

```html
<!doctype html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Drag-Drop</title>
        <script src="../dist/avalon.js"></script>
    </head>
    <body>
        <div ms-controller="validate1">
            <form ms-validate="@validate">
                <p><input ms-duplex="@aaa" placeholder="username"
                          ms-rules='{required:true,chs:true}' >{{@aaa}}</p>
                <p><input type="password" id="pw" placeholder="password"
                          ms-rules='{required:true}' 
                          ms-duplex="@bbb" /></p>
                <p><input type="password" 
                          ms-rules="{required:true,equalto:'pw'}" placeholder="再填一次"
                          ms-duplex="@ccc | change" /></p>
                <p><input type="submit" value="submit"/></p>
            </form>
        </div>
        <script>
var manualValidate
var vm = avalon.define({
    $id: "validate1",
    aaa: "",
    bbb: '',
    ccc: '',
    validate: {
        onInit: function(){
            var validator = this['_ms_validator_']
            var dir = avalon.directives.validate
            manualValidate = function(){
                dir.validateAll.call(validator, validator.onValidateAll)
            }
            //使用在外面调用
        },
        onError: function (reasons) {
            reasons.forEach(function (reason) {
                console.log(reason.getMessage())
            })
        },
        onValidateAll: function (reasons) {
            if (reasons.length) {
                console.log('有表单没有通过')
            } else {
                console.log('全部通过')
            }
        }
    }
})
        </script>
    </body>
</html>


```

**Comment by RubyLouvre** [comment]
我刚添加 了一个方法，简单流程

```html
<!doctype html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Drag-Drop</title>
        <script src="../dist/avalon.js"></script>
    </head>
    <body>
        <div ms-controller="validate1">
            <form ms-validate="@validate">
                <p><input ms-duplex="@aaa" placeholder="username"
                          ms-rules='{required:true,chs:true}' >{{@aaa}}</p>
                <p><input type="password" id="pw" placeholder="password"
                          ms-rules='{required:true}' 
                          ms-duplex="@bbb" /></p>
                <p><input type="password" 
                          ms-rules="{required:true,equalto:'pw'}" placeholder="再填一次"
                          ms-duplex="@ccc | change" /></p>
                <p><input type="submit" value="submit"/></p>
            </form>
        </div>
        <script>
var vm = avalon.define({
    $id: "validate1",
    aaa: "",
    bbb: '',
    ccc: '',
    validate: {
        onManual:avalon.noop,//IE6-8必须指定,avalon一会儿会重写方法
        onError: function (reasons) {
            reasons.forEach(function (reason) {
                console.log(reason.getMessage())
            })
        },
        onValidateAll: function (reasons) {
            if (reasons.length) {
                console.log('有表单没有通过')
            } else {
                console.log('全部通过')
            }
        }
    }
})

setTimeout(function(){
    vm.validate.onManual()
})
        </script>
    </body>
</html>

```

**Comment by RubyLouvre** [comment]
https://github.com/RubyLouvre/avalon/commit/7557d9ab13a0965f37603aee7975e09de16f7364

**Comment by caolinjian** [comment]
想依样画葫芦弄出单个验证的没成功，，，，
manualValidate = function() {
                    dir.validate.call(validator, field, false,event)   
                }
field event 弄不出来，

**Comment by RubyLouvre** [comment]
用onInit
```javascript
 onInit: function(){
            var validator = this['_ms_validator_']
            var dir = avalon.directives.validate
            manualValidate = function(){
                dir.validateAll.call(validator, validator.onValidateAll)
            }
            //使用在外面调用
        },
```

**Comment by caolinjian** [comment]
validateAll的可以，我是说手动调用单个field的校验 (￣▽￣")

**Comment by RubyLouvre** [comment]
不能

**Comment by caolinjian** [comment]
谢谢~ o(*￣▽￣*)ブ。用了下，然后意识到，手动调用很怪，其实就是validateInKeyup:true的情况。要是这个属性可以针对单个validator就好了，而不是整个validate

**Comment by caolinjian** [comment]
用oninit的方式会有个问题，就是viewValue变了但是modelValue，如果在我外面某个$watch调用manualValidate()的话，要怎么得到update后执行，，，。校验单个validator的需求又弄不出来了 Σ( ° △ °|||)︴

**Comment by caolinjian** [comment]
<!doctype html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Drag-Drop</title>
        <script src="../dist/avalon.js"></script>
    </head>
    <body>
        <div ms-controller="validate1">
            <form ms-validate="@validate">
                <p><input ms-duplex="@aaa" placeholder="username"
                          ms-rules='{required:true,chs:true}' >{{@aaa}}</p>
                <p><input type="password" id="pw" placeholder="password"
                          ms-rules='{required:true}' 
                          ms-duplex="@bbb" /></p>
                <p><input type="password" 
                          ms-rules="{required:true,equalto:'pw'}" placeholder="再填一次"
                          ms-duplex="@ccc | change" /></p>
                <p><input type="submit" value="submit"/></p>
            </form>
        </div>
        <script>
var vm = avalon.define({
    $id: "validate1",
    aaa: "",
    bbb: '',
    ccc: '',
    validate: {
        onManual:avalon.noop,//IE6-8必须指定,avalon一会儿会重写这方法
        onError: function (reasons) {
            reasons.forEach(function (reason) {
                console.log(reason.getMessage())
            })
        },
        onValidateAll: function (reasons) {//它会被onManual调用
            if (reasons.length) {
                console.log('有表单没有通过')
            } else {
                console.log('全部通过')
            }
        }
    }
})

vm.$watch('*',function(){
    vm.validate.onManual()
})
        </script>
    </body>
</html>

这个列子里，我把那个setTimeout改成$watch的方式。这里调用vm.validate.onManual() 它校验的值其实是上一次的value。这个地方怎么处理？

**Comment by RubyLouvre** [comment]
没有，你自己看一下源码。有好主意告诉我。
