### ISSUE TITLE
ms-dblclick错误

### ISSUE THREAD

**Issue by shanzhongke** [RubyLouvre/avalon#1560]
ms-dblclick与ms-click效果一致 单击即触发
另外还有个问题想问
<xmp ms-widget="[{is:'ms-gridList',pageindex:@index}]">这里将组件pageindex属性覆盖后，外层vm里index的改变是否也会使组件vm里的pageindex改变？

**Comment by RubyLouvre** [comment]
dblclick就是直接avalon.bind(el, dblclick,fn)，估计你的浏览器有些问题
