### ISSUE TITLE
函数绑定疑惑

### ISSUE THREAD

**Issue by shanzhongke** [RubyLouvre/avalon#1568]
刚看到分页组件里 ms-class='{disabled: @isDisabled("prev",1, @loop)}   isDisabled这个函数会多次触发？多次触发条件是什么？
另外@loop是什么？似乎不是自定义的

**Comment by RubyLouvre** [comment]
@loop已经被我删掉了。这是我改自别人组件的东西

触发条件是 每更新一次页面数据就会触发一次。除非上面肯定数据没有发生变化

**Comment by RubyLouvre** [comment]
https://github.com/RubyLouvre/ms-pager/blob/master/template.html
