### ISSUE TITLE
监控不到日期控件的选择值

### ISSUE THREAD

**Issue by leupom** [RubyLouvre/avalon#1569]
input框的值是通过日期控件选择输入的，avalon无法监控到值变化，已测试的日期控件有layDate和bootstrap-datetimepicker。
还有改变avalon监控的数组，无法自动选中相应的checkbox，而操作checkbox时，值是可以同步到相应的数组里面的。

**Comment by RubyLouvre** [comment]
如果是第三方组件，当然是监控不了，因为人家的那个input已经不是我最初绑定扫描的那个。


第二个问题，请给出完整的页面
