### ISSUE TITLE
两个Bug的演示

### ISSUE THREAD

**Issue by leupom** [RubyLouvre/avalon#1576]
[bug.zip](https://github.com/RubyLouvre/avalon/files/351440/bug.zip)

**Comment by RubyLouvre** [comment]
能直接贴上来吗，说明什么浏览器，什么版本，怎么操作

**Comment by leupom** [comment]
我已经发你cheng19840218@gmail.com邮箱了，也上传了bug.zip文件。

**Comment by RubyLouvre** [comment]
正在看

**Comment by RubyLouvre** [comment]
第2个例子是要用ms-duplex-number

**Comment by RubyLouvre** [comment]
http://avalonjs.coding.me/duplex-parser.html
