### ISSUE TITLE
[2.10] ms-text中三元运算符和过滤器组合使用问题

### ISSUE THREAD

**Issue by weijian1** [RubyLouvre/avalon#1579]
**问题描述**：在ms-text中，使用三元运算符（条件 ? 结果1 : 结果2）的时候，如果在“结果1”或“结果2”里面加上过滤器，则会报错提示“SyntaxError: missing : in conditional expression”。

**版本**： built in 2016-7-7:3 version 2.10 by 司徒正美

**截图**：
![qq20160708-0 2x](https://cloud.githubusercontent.com/assets/9735144/16684271/c5477b78-4536-11e6-9112-e8fd353cb099.png)

**代码**：
```
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <script src="avalon.js"></script>
    <script>
        var vm = avalon.define({
            $id: "test",
            is_true: 1
        })
    </script>
</head>
<body ms-controller="test">
    <p>{{@is_true == 1 ? 'true' | uppercase : 'false' | uppercase}}</p>
</body>
</html>
```

**Comment by RubyLouvre** [comment]
你用错了，你用的是angular的语法。avalon的过滤器传参要加()， 并且uppercase，avalon也没有参数！

http://avalonjs.coding.me/filter.html

**Comment by RubyLouvre** [comment]
你最好不要用avalon.next，这个版本的测试比较少
