### ISSUE TITLE
如何手动销毁vm？

### ISSUE THREAD

**Issue by shanzhongke** [RubyLouvre/avalon#1585]
如何手动销毁vm？
单页切换时发现以前的操作会被记录下来  想到销毁该页面对应vm 是否合适？

**Comment by RubyLouvre** [comment]
不要销毁啊

**Comment by RubyLouvre** [comment]
销毁了，性能很差

**Comment by RubyLouvre** [comment]
因为你的数据是这样，页面就这样呈现。因此既回来再改数据了

**Comment by shanzhongke** [comment]
我的单页里还用了几个组件 那每次切换页面的时候既要还原页面vm默认值 还要还原组件vm默认值？
内存里加载的vm和组件vm多了 不影响性能？

**Comment by RubyLouvre** [comment]
那就要将avalon.vmodels, avalon.scopes中对应的东西删掉。。。。

**Comment by RubyLouvre** [comment]
为什么要还原默认值，这需要不合理

**Comment by shanzhongke** [comment]
从新页面切回前几个页面 发现列表还保持在之前的操作状态比如多选 所以要还原默认值
