### ISSUE TITLE
新版本avalon ms-for中通过模板嵌套ms-for报错！

### ISSUE THREAD

**Issue by gogtz** [RubyLouvre/avalon#1586]
At built in 2016-7-11:17 version 2.10 by 司徒正美

浏览器错误信息

> html TypeError: Cannot read property 'children' of undefined(…) TypeError: Cannot read property 'children' of undefined
>     at fireEnd (http://127.0.0.1/vendor/plug-in/avalon2/avalon.js:6997:21)
>     at Function.lexer (http://127.0.0.1/vendor/plug-in/avalon2/avalon.js:6957:14)
>     at Object.avalon.directive.diff (http://127.0.0.1/vendor/plug-in/avalon2/avalon.js:3758:35)
>     at http://127.0.0.1/vendor/plug-in/avalon2/avalon.js:7325:39
>     at String.replace (native)
>     at diffProps (http://127.0.0.1/vendor/plug-in/avalon2/avalon.js:7320:19)
>     at diff (http://127.0.0.1/vendor/plug-in/avalon2/avalon.js:7288:22)
>     at diff (http://127.0.0.1/vendor/plug-in/avalon2/avalon.js:7291:22)
>     at diff (http://127.0.0.1/vendor/plug-in/avalon2/avalon.js:7299:21)
>     at Function.diff (http://127.0.0.1/vendor/plug-in/avalon2/avalon.js:7291:22) diffProps error

<pre>&lt;!DOCTYPE html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
    &lt;meta charset="UTF-8"&gt;
    &lt;title&gt;Title&lt;/title&gt;
    &lt;script type="text/javascript" src="avalon.js"&gt;&lt;/script&gt;
&lt;/head&gt;
&lt;body&gt;
&lt;blockquote&gt;
    &lt;div ms-controller="tree"&gt;
        &lt;ul ms-for="el in @tree"&gt;{{el.text}}
            &lt;span ms-click='@toggle($event,el)' ms-text="@trigger(el)"&gt;&lt;/span&gt;
            &lt;div ms-html="@tmpl" ms-visible="el.subtree.length " &gt;&lt;/div&gt;
        &lt;/ul&gt;
    &lt;/div&gt;
    &lt;script&gt;
        avalon.define({
            $id: "tree",
            trigger: function (el) {
                if (el.subtree &amp;&amp; el.subtree.length) {
                    return el.open ? '[+]' : '[-]'
                } else {
                    return ''
                }
            },
            toggle: function (event, elem) {
                var el = event.target
                elem.open = el.open = !el.open
                var tree = el.nextElementSibling
                tree.style.display = el.open ? '' : 'none'
            },
            tree: [
                {text: "aaa", open: 1, subtree: [
                    {text: 1111, open: 1, subtree: []},
                    {text: 2222, open: 1, subtree: [
                        {text: 777, open: 1, subtree: []}
                    ]},
                    {text: 3333, open: 1, subtree: [
                        {text: 8888, open: 1, subtree: []},
                        {text: 999, open: 1, subtree: []}
                    ]}
                ]},
                {text: "bbb", open: 1, subtree: [
                    {text: 4444, open: 1, subtree: []},
                    {text: 5555, open: 1, subtree: []},
                    {text: 6666, open: 1, subtree: []}
                ]},
                {text: "ccc", open: 1, subtree: []},
                {text: "ddd", open: 1, subtree: []},
                {text: "eee", open: 1, subtree: [
                    {text: 1234, open: 1, subtree: []}
                ]},
                {text: "fff", open: 1, subtree: []}
            ],
            tmpl: "&lt;ul ms-for='el in el.subtree'&gt;&lt;li&gt;{{el.text}}&lt;span ms-click='@toggle($event,el)' ms-text='@trigger(el)'&gt;&lt;/span&gt;&lt;div ms-html='@tmpl' ms-visible='el.subtree.length '&gt;xxx&lt;/div&gt;&lt;/li&gt;&lt;/ul&gt;"

        })
    &lt;/script&gt;
&lt;/blockquote&gt;
&lt;/body&gt;
&lt;/html&gt;
</pre>

**Comment by RubyLouvre** [comment]
已经修正
