### ISSUE TITLE
关于ms-for的一点想法

### ISSUE THREAD

**Issue by gogtz** [RubyLouvre/avalon#1587]
正美，正在比着你的分页组件学习写组件，在页码生成时，avalon2的ms-for指令只能以集合来做遍历，总感觉不顺手，而且还有很多时候，构建组件结构时只是做循环，是否能扩展一个纯循环的功能，

比如：5次循环      ms-for="(index, 0) to 5"   或者   ms-for="(index, 0, 1) in 5" 

括号里分别为：循环变量，初始值，步长

以上只是在学习avalon2时的一些想法，仅供参考。

**Comment by RubyLouvre** [comment]
你可以使用avalon.range来生成数组 http://avalonjs.coding.me/api.html#range

ms-for还非常复杂的，不想轻易加功能

**Comment by jinwyp** [comment]
说实话 不建议增加更多的语法， 语法越多，文档越乱，结果导致用起来麻烦。就像ng option的用法太多了
