### ISSUE TITLE
ms-if, ms-text的问题

### ISSUE THREAD

**Issue by Canox3** [RubyLouvre/avalon#1590]
![20160713113154](https://cloud.githubusercontent.com/assets/7719747/16791131/6ec37ab6-48ee-11e6-99f1-474c6fd80d6e.png)
![20160713113314](https://cloud.githubusercontent.com/assets/7719747/16791135/77b6eb26-48ee-11e6-94ef-77dc140f8f53.png)
![20160713113327](https://cloud.githubusercontent.com/assets/7719747/16791133/777e49ce-48ee-11e6-9864-4c337a5a9c14.png)

在2.1.5及之前版本都运行正常，测试2.1.6版本时就直接报错

**Comment by RubyLouvre** [comment]
写简单例子上来。是不是你有的标签没有闭合啊。
`<input > `----> `<input />`

**Comment by RubyLouvre** [comment]
人呢，写例子。或用IDE校正一下HTML的闭合

**Comment by Canox3** [comment]
我重新排查了一下错误，如果HTML页面里出现这样的类似注释中包含双引号的语句，下面的avalon代码就无法正常执行
例如

 __
__

**Comment by RubyLouvre** [comment]
给一个完整一点的页面我调调

**Comment by Canox3** [comment]
`<!DOCTYPE html>
<html>
<body ms-controller="test">
    __
    <div ms-for="el in @arr">{{el}}</div>
<script src="js/avalon2.16.js"></script>
<script>
    var vm = avalon.define({
        $id:"test",
        arr:[1,2,3,4,5]
    });
</script>
</body>
</html>`

**Comment by RubyLouvre** [comment]
不要贴图，我还要对着敲一遍

唉

真不为别人着想！

**Comment by RubyLouvre** [comment]
已经修复，更新

**Comment by Canox3** [comment]
幸苦了。
我最开始发的代码，不知道为什么被转义了，最后只好贴图了。

**Comment by RubyLouvre** [comment]
使用 ```  ```啊
