### ISSUE TITLE
DOM解析bug

### ISSUE THREAD

**Issue by gogtz** [RubyLouvre/avalon#1592]
built in 2016-7-13:15 version 2.16 by 司徒正美

在Chromium47.0.2526.80中控制始报错：
Uncaught Error: a没有闭合

<pre>
<code>
&lt;!DOCTYPE html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
    &lt;meta charset="UTF-8"&gt;
    &lt;script type="text/javascript" src="/vendor/plug-in/avalon2/avalon.js"&gt;&lt;/script&gt;
&lt;/head&gt;
&lt;body&gt;
&lt;div ms-controller="test"&gt;
    &lt;code&gt;&amp;lt;a&amp;gt;&lt;/code&gt;
&lt;/div&gt;
&lt;/body&gt;
&lt;script&gt;
    avalon.define({
        $id: 'test'
    })
&lt;/script&gt;
&lt;/html&gt;
</code>
</pre>

**Comment by RubyLouvre** [comment]
已经修正
