### ISSUE TITLE
关于avalon1.5.6加载，偶尔报错的问题

### ISSUE THREAD

**Issue by hjc5345** [RubyLouvre/avalon#1593]
想请教一个问题： avalon1.5.6源码3669行左右
DOC.namespaces 这个命名空间添加有什么特殊含义吗？
在ie8和ie9下，有时会因为document的namespaces属性还没加载而报错，导致avalon库加载失败。

附具体源码片段：
avalon.libraries = []
avalon.library = function (name, opts) {
if (DOC.namespaces) {
DOC.namespaces.add(name, 'http://www.w3.org/1999/xhtml');
}
avalon.libraries[name] = avalon.mix({
$init: noop,
$ready: noop,
$dispose: noop
}, opts || {})
}

**Comment by RubyLouvre** [comment]
那你可以在avalon这个库加载前，在页面上加上

```
if (document.namespaces) {
document.namespaces.add(name, 'http://www.w3.org/1999/xhtml');
}

```

**Comment by hjc5345** [comment]
这样直接访问，ie8会报 未指明错误

**Comment by RubyLouvre** [comment]
不会啊，那是你其他地方错了吧
