### ISSUE TITLE
ms-html与{{}}插值表达式的小bug

### ISSUE THREAD

**Issue by gogtz** [RubyLouvre/avalon#1594]
At built in 2016-7-13:20 version 2.16 by 司徒正美

问题1，ms-html=' ... &lt;kbd&gt;&amp;lt;script&amp;gt;&lt;/kbd&gt;'  结果不对，kbd变成空了;

问题2，#1552的两个问题又出现了

<pre>
<code>
&lt;!DOCTYPE html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
    &lt;meta charset="UTF-8"&gt;
    &lt;script type="text/javascript" src="/vendor/plug-in/avalon2/avalon.js"&gt;&lt;/script&gt;
    &lt;style&gt;
        kbd {
            padding: 2px 4px;
            font-size: 90%;
            color: #fff;
            background-color: #333;
            border-radius: 3px;
            -webkit-box-shadow: inset 0 -1px 0 rgba(0, 0, 0, .25);
            box-shadow: inset 0 -1px 0 rgba(0, 0, 0, .25);
        }
    &lt;/style&gt;
&lt;/head&gt;
&lt;body&gt;
&lt;div ms-controller="test"&gt;
    &lt;code&gt;&amp;lt;a&amp;gt;&lt;/code&gt;&lt;br/&gt;
    &lt;p ms-html="@wenti1"&gt;&lt;/p&gt;
    &lt;p ms-for="item in @wenti2"&gt;问题2：{{ item &lt; 1 ? '小于0' : item &gt; 1 ? '大于1' : item }}&lt;/p&gt;
&lt;/div&gt;
&lt;/body&gt;
&lt;script&gt;
    avalon.define({
        $id: 'test',
        wenti1: '它使用了不同于传统 &lt;kbd&gt;&amp;lt;script&amp;gt;&lt;/kbd&gt; 标签的脚本加载步骤',
        wenti2: [0, 1, 2]
    })
&lt;/script&gt;
&lt;/html&gt
</code>
</pre>

**Comment by RubyLouvre** [comment]
又修正了
