### ISSUE TITLE
组件传参中的非监控属性疑惑

### ISSUE THREAD

**Issue by shanzhongke** [RubyLouvre/avalon#1595]
<xmp cached='true' ms-widget="[{is:'ms-pager',$items:@$items}]"></xmp>
使用组件时如果使用$开头的非监控属性作为参数 以后该属性改变时 组件视图是否会改变？

**Comment by RubyLouvre** [comment]
不会

**Comment by shanzhongke** [comment]
你写的分页组件里为啥用了？$buttons

**Comment by RubyLouvre** [comment]
因为我知道，我以后会怎么改avalon。而你不知道。
