### ISSUE TITLE
avalon 1.5.6 光标 bug

### ISSUE THREAD

**Issue by mice33** [RubyLouvre/avalon#1604]
![input-132](https://cloud.githubusercontent.com/assets/4945433/16868767/0edaa52e-4aac-11e6-8607-0b24d48b3cf9.gif)

效果如 gif 图中显示, 在 Chrome 下使用 avalon 1.5.6, 代码如下复制[官方手机号码格式化例子](http://rubylouvre.github.io/mvvm/avalon.watch.html)

`
<!DOCTYPE html>
<html>
    <head>
        <title>ms-duplex</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <script src="avalon.js" ></script>
        <script>
            var test = avalon.define({
                $id : 'test',
                phone : ''
            });
            test.$watch("phone", function(a) {
                var b = a.replace(/\s+/g, "")
                var array = b.split("")
                var ret = ""
                for (var i = 0, n = array.length; i < n; i++) {
                    if (i > 10)//不能超过11位
                        break
                    if (i == 3) {
                        ret += " "
                    }
                    if (i == 7) {
                        ret += " "
                    }
                    ret += array[i]
                }
                test.phone = ret;
            })
        </script>
    </head>
    <body ms-controller="test">
        <input type="text " ms-duplex="phone"  />
        <p>{{phone}}</p>
    </body>
</html>
`

但在官方例子中使用 avalon 1.3.2 无此 BUG, 如 gif 图中显示
[http://rubylouvre.github.io/mvvm/avalon.watch.html](http://rubylouvre.github.io/mvvm/avalon.watch.html)

**Comment by RubyLouvre** [comment]
建议升级到2.0.

**Comment by RubyLouvre** [comment]
https://segmentfault.com/a/1190000005362826 看这个
