### ISSUE TITLE
路由和ajax插件不能在avalon2工作了？

### ISSUE THREAD

**Issue by hyingreborn** [RubyLouvre/avalon#1605]

**Comment by RubyLouvre** [comment]
ajax可以用。
路由组件正在重写

**Comment by hyingreborn** [comment]
找了很多独立的前端路由框架，要么不能良好兼容IE67，要么功能太复杂。就希望有一个默认使用hashbang的，良好兼容IE67的前端路由，history api有点要跟后端路由抢饭碗的意思...期待avalon2的路由~
