### ISSUE TITLE
关于组件中使用<slot>理解疑惑

### ISSUE THREAD

**Issue by gogtz** [RubyLouvre/avalon#1606]
[http://avalonjs.coding.me/component.html](url) 文档中的图例说明如下：
<img src='http://avalonjs.coding.me/dom-insert.png'/>
我理解为：
<pre>
<code>
&lt;div class='dialog'&gt;
&lt;div class='header'&gt;
  &lt;slot name='header'&gt;&lt;/slot&gt;
&lt;/div&gt;
&lt;div class='body'&gt;
  &lt;slot name='body'&gt;&lt;/slot&gt;
&lt;/div&gt;
&lt;div class='footer'&gt;
  &lt;slot name='footer'&gt;&lt;/slot&gt;
&lt;/div&gt;
&lt;/div&gt;

&lt;div ms-controller='test'&gt;
&lt;ms-dialog&gt;
&lt;span slot='header'&gt;这是标题&lt;/span&gt;
&lt;div slot='body'&gt;这里放许多内容与元素&lt;/div&gt;
&lt;p slot='footer'&gt;&lt;button&gt;关闭&lt;/button&gt;&lt;/p&gt;
&lt;/ms-dialog&gt;
&lt;/div&gt;
</code>
</pre>

的结果应该为：
<pre>
<code>
&lt;div class='dialog'&gt;
&lt;div class='header'&gt;
  &lt;span slot='header'&gt;这是标题&lt;/span&gt;
&lt;/div&gt;
&lt;div class='body'&gt;
  &lt;div slot='body'&gt;这里放许多内容与元素&lt;/div&gt;
&lt;/div&gt;
&lt;div class='footer'&gt;
  &lt;div slot='body'&gt;这里放许多内容与元素&lt;/div&gt;
&lt;/div&gt;
&lt;/div&gt;
</code>
</pre>

但现在的结果为：
<pre>
<code>
&lt;div class='dialog'&gt;
&lt;div class='header'&gt;
  &amp;lt;span slot='header'&amp;gt;这是标题&amp;lt;/span&amp;gt;
&lt;/div&gt;
&lt;div class='body'&gt;
  &amp;lt;div slot='body'&amp;gt;这里放许多内容与元素&amp;lt;/div&amp;gt;
&lt;/div&gt;
&lt;div class='footer'&gt;
  &amp;lt;div slot='body'&amp;gt;这里放许多内容与元素&amp;lt;/div&amp;gt;
&lt;/div&gt;
&lt;/div&gt;
</code>
</pre>

调试代码：
<pre>
<code>
&lt;!DOCTYPE html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
    &lt;meta charset="UTF-8"&gt;
    &lt;script type="text/javascript" src="/vendor/plug-in/avalon2/avalon.js"&gt;&lt;/script&gt;
    &lt;script&gt;
        avalon.component('ms-dialog', {
            template: "&lt;div class='dialog'&gt;&lt;div class='header'&gt;&lt;slot name='header'&gt;&lt;/slot&gt;&lt;/div&gt;&lt;div class='body'&gt;&lt;slot name='body'&gt;&lt;/slot&gt;&lt;/div&gt;&lt;div class='footer'&gt;&lt;slot name='footer'&gt;&lt;/slot&gt;&lt;/div&gt;&lt;/div&gt;"
        });
        avalon.define({
            $id: 'test'
        })
    &lt;/script&gt;
&lt;/head&gt;
&lt;body&gt;
&lt;div ms-controller="test"&gt;
    &lt;ms-dialog&gt;
        &lt;span slot='header'&gt;这是标题&lt;/span&gt;
        &lt;div slot='body'&gt;这里放许多内容与元素&lt;/div&gt;
        &lt;p slot='footer'&gt;&lt;button&gt;关闭&lt;/button&gt;&lt;/p&gt;
    &lt;/ms-dialog&gt;
&lt;/div&gt;
&lt;/body&gt;
&lt;/html&gt;
</code>
</pre>

**Comment by RubyLouvre** [comment]
slot机制分为两大类型

一个是soleSlot元素，那么你在页面上定义的组件容器(wbr, xmp, template, ms-元素)的内部都是soleSlot的内容，里面所有东西都会被成一个html字符串

举例说，最简单的ms-button组件

```javascript
avalon.component('ms-button', {
    template: '<button type="button"><span><slot /></span></button>',
    defaults: {
        buttonText: "button"
    },
    soleSlot: 'buttonText'
})

```

它的template其实会翻译成
```html
<button type="button"><span ms-html="##buttonText"></span></button>
```
　
如果外面是这样调用

```
<ms-button><b>xxx</b><span class="icon"></span><ms-button>
```

组件vm的buttonText属性会被赋值 
```
vm.buttonText = '<b>xxx</b><span class="icon"></span>'
```

但你是这样调用
```
<wbr :widget="{is: 'ms-button'}" />
<xmp :widget="{is: 'ms-button'}" ></xmp>
<ms-button ></ms-button>
```

容器元素没有节点，或只是空白，vm.buttonText是不会被赋值，还是使用默认的button

第二种情况，存在多个slot

```
avalon.component('ms-dialog', {
                template: heredoc(function () {
                    /*
                     <div class="dialog">
                     <slot name='header'/>
                     <slot name='body'/>
                     <slot name='footer'/>
                     </div>
                     */
                }),
                defaults: {
                    header: '<div>header</div>',
                    body: '<div>body</div>',
                    footer: '<div>footer</div>'
                }
            })
```

传参是这样的

```
<ms-dialog :widget="[{$id:'aaa'}]">
        <div slot="header" >面板1</div>
        <div slot="body" >面板2</div>
        <div slot="footer" >面板3</div>
</ms-dialog>
```
那么组件VM是变成这样
```
 header: '<div>面板1</div>',
  body: '<div>面板2</div>',
 footer: '<div>面板3</div>'
```

此外，你还可以在组件的template中不写slot元素，只是在外面组件容器里面加slot属性

如ms-tabs

```
avalon.component('ms-tabs', {
    template: heredoc(funcion(){
/*
<div class="ms-tabs">
    <ul class="ms-tabs-buttons">
        <li class="ms-tabs-button" 
            :for="($index,el) in @triggers"
            :class="[$index === @selectedIndex && 'active']"
            :click="@cbProxy($event,$index)">{{el}}</li>
    </ul>
    <div class="ms-tabs-panels">
        <div class="ms-tabs-panel" 
             :for="($index, el) in @panels" 
             :visible="$index === @selectedIndex"
             :html="el"
             ></div>
    </div>
</div>
*/
   }),
    defaults: {
        triggers: [111, 222, 333],
        panels: [],
        selectedIndex: 0,
        cbProxy: function (e, i) {
            if (typeof this.onSwitch === 'function') {
                var ret = this.onSwitch(e, i)
            }
            if (ret !== false) {
                this.selectedIndex = i
            }
        }
    }
})

```

```html
<ms-tabs ms-widget="[{$id:'aaa'}]">
        <div slot="panels" >
            <p>这次的实验对师兄打击很大，也让他能够真正地静下来去思考自己的人生，他说不想再那么痛苦地强撑，也不必给自己如此大的压力，开始重新规划自己未来的道路。</p></div>
        <div slot="panels" ><p>不过，像《青年文摘》《读者》等流行读物，我们是应该看，但最好只把它当做获得资讯的方式，不要把它们当成你全部的阅读，不然，你会变得很肤浅。</p>
        </div>
        <div slot="panels" ><p>鼹鼠的土豆在她的豆瓣上说：我送书的时候没有人要，我送荔枝，一会就抢光了。</p>
          </div>
    </ms-tabs>
```
这样vm.panels就会被一个html数组所重写

**Comment by gogtz** [comment]
:for  :class  :click   这些是在模板中写指令的语法吗？所有的指令在模板内都可以这么写么？

**Comment by RubyLouvre** [comment]
所有都可以，不限模板
