### ISSUE TITLE
IE8 ms-on指令this指向问题

### ISSUE THREAD

**Issue by PhoonLee** [RubyLouvre/avalon#1608]
avalon@2.1.3版本

html:
`<div ms-controller="demo"><p ms-on-click="@car.onClick">{{@car.name}}</p></div>`

js:
`var demo=avalon.define({
    $id:'demo',
    car:{
        name:'Lenbo',
        onClick:function(){
             this.name='Fala'
        }
}
})`

在主流的高级浏览器，onClick 的 this 指向是 demo.car
在 IE8，onClick 的 this 指向的是 demo

**Comment by RubyLouvre** [comment]
那你不要在里面定义事件。

**Comment by PhoonLee** [comment]
但是都在外面定义的话，当业务量大的时候，岂不是很乱？
当然这只是我个人观点 :)

**Comment by RubyLouvre** [comment]
没有办法 旧式IE的兼容是很恶心，我也心绞力瘁

**Comment by RubyLouvre** [comment]
业务量大应该拆成多个controller

**Comment by RubyLouvre** [comment]
2.17版如果发现你的controller（VM）很大，会提示你进行拆分的
