### ISSUE TITLE
表单验证疑惑

### ISSUE THREAD

**Issue by shanzhongke** [RubyLouvre/avalon#1610]
能否手动控制某个输入框的验证功能是否开启？

**Comment by RubyLouvre** [comment]
不能，我看一下其他验证框架也没有这功能

**Comment by shanzhongke** [comment]
那我只能在验证回调里加判断了

**Comment by RubyLouvre** [comment]
validation的错误提示，可以参考这个 http://ued.qunar.com/oniui/index.html#!/widgets?widgetId=validation

本来就是从这个过来的
