### ISSUE TITLE
表单验证疑惑

### ISSUE THREAD

**Issue by shanzhongke** [RubyLouvre/avalon#1617]
ms-for循环中不能包括ms-validate？？ms-validate的值不能相同？

**Comment by RubyLouvre** [comment]
但没有人会循环生成多个表单吧。这个需求也太不合理

**Comment by sunriseyuen** [comment]
N个输入框是一个数组,用ms-for循环生成一个表单。这个需求正常。

**Comment by shanzhongke** [comment]
另外vm中的属性为对象时不是要求定义后不能直接添加子元素吗？数组没有这个限制吧？数组可以一个一个单独添加吧？

**Comment by RubyLouvre** [comment]
是的，数组的元素是简单数据类型就要用set方法，这个官网有写

**Comment by shanzhongke** [comment]
但如果数组中多个元素都要更新 你推荐的方式是用一个新数组直接覆盖vm中的原数组？
