### ISSUE TITLE
请问，这是bug么？富文本编辑器编辑一些内容后，用了avalon2渲染，好像出错了。

### ISSUE THREAD

**Issue by cloudus** [RubyLouvre/avalon#1626]
请问，这是bug么？富文本编辑器编辑一些内容后，用了avalon2渲染，好像出错了。
![001](https://cloud.githubusercontent.com/assets/12695053/17076853/0f3b4d6c-50f0-11e6-978c-5d97a64004f7.png)
![002](https://cloud.githubusercontent.com/assets/12695053/17076855/16225256-50f0-11e6-8f36-b5d79b4b54a9.png)

**Comment by cloudus** [comment]
![Uploading 003.png…]()

**Comment by cloudus** [comment]
附加一些图片。
![003](https://cloud.githubusercontent.com/assets/12695053/17076915/2bb97d46-50f1-11e6-80af-11c90fd6dd2e.png)
![004](https://cloud.githubusercontent.com/assets/12695053/17076919/36615656-50f1-11e6-96ff-87c1a2cd9e34.png)
![005](https://cloud.githubusercontent.com/assets/12695053/17076921/39f9d216-50f1-11e6-8d90-dd025a875455.png)

**Comment by RubyLouvre** [comment]
roman×××这个属性有问题

**Comment by RubyLouvre** [comment]
有特殊字符了

**Comment by cloudus** [comment]
请问如何解决呢？因为富文本是必须的哦。

**Comment by RubyLouvre** [comment]
roman**这个是什么东西，数据不足，无法处理。

**Comment by cloudus** [comment]
http://fy.ekbon.cn/index.php?c=article&a=detail&articleid=27
谢谢~

**Comment by RubyLouvre** [comment]
看一下源码

原因是因为你某一行style属性有错误，双引号里面又有双引号

你换一个好一点的IDE，一下子就标出来

这是你的BUG，又怪到avalon的头上来了

**Comment by cloudus** [comment]
这是用ueditor编辑器编写的内容，请问这个问题如何规避呢？一般用户都是直接复制粘贴文章过来了……

**Comment by RubyLouvre** [comment]
后端处理一下将双引号中的双引号改成单引号。。。或加一个语法检测，不合格式不能提交。就像反XSS一样
