### ISSUE TITLE
ms-class的键名无法是变量。请问如何解决？

### ISSUE THREAD

**Issue by cloudus** [RubyLouvre/avalon#1627]
ms-class的键名无法是变量。请问如何解决？
![006](https://cloud.githubusercontent.com/assets/12695053/17081676/65798eec-5194-11e6-818e-74a0bf9d1e9a.png)

**Comment by RubyLouvre** [comment]
avalon2可以这样
```
ms-class="['imgs-box'+row.images_class]"
```

http://avalonjs.coding.me/directives/ms-class.html

**Comment by cloudus** [comment]
谢谢~
