### ISSUE TITLE
iOS 10.0(14A5297c) 微信内ms-duplex 失败

### ISSUE THREAD

**Issue by zlj002** [RubyLouvre/avalon#1629]
如题,   avalon  1.5.6     avalon.shim.js    和 avalon.modern.shim.js 都是无法绑定

**Comment by RubyLouvre** [comment]
肯定是你用错了，我们这么多人在微信上用都没有事

**Comment by RubyLouvre** [comment]
http://avalonjs.github.io/#tutorial/engineering/weixin.html

**Comment by RubyLouvre** [comment]
看一下这里

**Comment by zlj002** [comment]
不是的，是其他手机iOS 版本都正常，但是 iOS 10.0(14A5297c)  不可以

**Comment by RubyLouvre** [comment]
有报错没有，并且你都没有例子。给一个例子，并且将它的错误也放上来。我没有iOS10

**Comment by zlj002** [comment]
感谢司徒的回复
![image](https://cloud.githubusercontent.com/assets/8316796/17162062/1a6c6002-53e5-11e6-849d-a8f310c45e62.png)
![image](https://cloud.githubusercontent.com/assets/8316796/17162173/6540894a-53e6-11e6-8933-4c0f5eb6a063.png)

**Comment by RubyLouvre** [comment]
嗯，等正式版出来吧。
