### ISSUE TITLE
1.5.x版本bug提交

### ISSUE THREAD

**Issue by yutent** [RubyLouvre/avalon#1635]
1、ms-html， 如果值一个iframe标签字符串，即   '<iframe src="http://baodi.com"></iframe>'， 显示时没问题，但想清空这个值时，iframe也顺利被清除了，但是会触发一次对`url(如上面的百度地址)`的访问，且必定是超时。 这个情况是100%复现。

2、看代码里，好像每个vm都有一个 $up, $ups，但是实际上这2个值全是null。
3、组件，1.4时，可以在组件内获取到上一级vm，但是1.5没的了，上面问题2提到的那个2个值也是null。 不知道是不是有其他方法获取到上一级的vm呢？

**Comment by RubyLouvre** [comment]
不要与iframe混用。avalon内部没有处理iframe的相关逻辑。

**Comment by RubyLouvre** [comment]
那些东西没有写在文档中，是某个版本的试验性API，不要使用。

**Comment by yutent** [comment]
那有没有办法在组件里获取上级vm呢？

**Comment by RubyLouvre** [comment]
没有啊，这个不是用redux这样的框架搞吗？！那个很好用，强烈推荐。可以解耦父子组件
