### ISSUE TITLE
360浏览器在记住密码时，获取不取密码

### ISSUE THREAD

**Issue by koeltp** [RubyLouvre/avalon#1638]
你好！我用的AVALON 1.5.6 ，360浏览器在记住密码时，获取不取密码。目前是直接jq去获得一下解决，请问avalon有什么补救方法吗？

**Comment by RubyLouvre** [comment]
这个很简单，先将原来的值置为空，再赋回来

**Comment by RubyLouvre** [comment]
也就是说，这个密码不是你自己赋值的，也不是框架赋值的，因此你必须重新赋值一下吧。

<input ms-duplex="password" />

var a = vm.password// a = "" ??是这个意思吗

你

**Comment by koeltp** [comment]
我是直接从vm中拿，但是拿不到。
对a="";
我说下过程吧、
我先登录，这时候360极速浏览器提示记住密码。我选择记住密码。然后登陆进去了。然后再注销账号。再去登录页面，这时候登录页面的账号和密码是记住的，账号和密码页面上都是有的。点击提交 ，vm.password是“”。

**Comment by RubyLouvre** [comment]
只有360是这样吗？看你的描述是已经发生页面跳转
