### ISSUE TITLE
IE下ms-class问题

### ISSUE THREAD

**Issue by shanzhongke** [RubyLouvre/avalon#1645]
IE下 点击切换无效 ms-class 中！取反无效

    <body ms-controller="test">
        <div ms-class="{disabled1:!@asd}"></div>
        <button ms-click="@cli">123</button>
        <script>
            avalon.define({
                $id: 'test',
                asd: false,
                cli: function() {
                    this.asd =true;
                }
            });
        </script>
    </body>

**Comment by RubyLouvre** [comment]
什么浏览器下！IE6－8
```javascript
var vm = avalon.define({
            $id: 'test',
            asd: false,
            cli: function() {
                vm.asd =true;
            }
        });
```
