### ISSUE TITLE
组件递归疑惑

### ISSUE THREAD

**Issue by shanzhongke** [RubyLouvre/avalon#1648]
请问组件在模板内能否递归地调用自己？在写树状列表 感觉需要重复调用组件  是否有例子？

**Comment by RubyLouvre** [comment]
https://github.com/RubyLouvre/avalon/tree/master/perf/component

**Comment by RubyLouvre** [comment]
https://github.com/RubyLouvre/avalon/blob/master/perf/component/%E6%A0%91(%E7%BB%84%E4%BB%B6%E5%BD%A2%E5%BC%8F).html
