### ISSUE TITLE
郁闷了，只不过更新了一下avalon2 的最新一个版本，居然就运行不了

### ISSUE THREAD

**Issue by koeltp** [RubyLouvre/avalon#1651]
以前是avalon 2.0.3版本，代码如下面：
`<div ms-controller="artitle_vm">
    <div class="postItem clearfix" ms-for="el in #bbb">
   </div>
</div>
`
`
 var vm = avalon.define({
            $id: "artitle_vm",
            bbb: [],
            init: function () {
                hy_ajax.get("Api/Article/Index")
                    .success(function (e) {
                        vm.bbb = e;
                        console.log(e);
                    })
                    .error(function (error) {
                        console.log(error);
                    }).ajax();

            }
        });

        $(function () {
            vm.init();
        });
`

现在更新为最新版本avalon 2.1.2 ，居然提示我说：Uncaught SyntaxError: Invalid or unexpected token，错误行在avalon.js 36行
`var loop = (function(){
try{
var __value__ = #bbb`

去掉ms-for里的“#”符号则又报:parse other binding【 bbb 】fail
我是asp.net MVC

**Comment by RubyLouvre** [comment]
不应该用两个##吗

**Comment by RubyLouvre** [comment]
改成两个##了，因为有人投诉说 #&1213; (web font) ， #a9ea00 (颜色值），#id (ID)，非常常用，要改成两个##

**Comment by koeltp** [comment]
嗯，谢谢。
