### ISSUE TITLE
如何将页面模块化？

### ISSUE THREAD

**Issue by rubyisapm** [RubyLouvre/avalon#1655]
因为是后台系统，页面相对复杂，有各种弹框操作。
我的想法是把vm的js和其相关的html都分离出来。
一种方法是单独分离：
在avalon1时，使用ms-include-src引用html；在js层面将每一个模块的vm分离为一个单独的模块，向外部提供方法。
但是ms-include-src在avalon2里删除了。所以我找不到方法可以让现有页面去引用另一个html模板文件。
另外还想到的一种方法：
使用avalon的组件概念；
但这个解决方案有一些问题：
1. 这种组件定义很奇怪，不是为了重用，而是为了分离。似乎不符合组件的初衷。
2. 组件定义时要写的是字符串，感觉相当难写难改，因为都是大段的html。

我想请教下老师，如何做是合理的方案？或者avalon里面有哪些特性是我可以用来解决这种问题的吗？

**Comment by RubyLouvre** [comment]
使用webpack 打包

**Comment by RubyLouvre** [comment]
webpack有一些插件可以将多个子页面合成一个完整的页面

**Comment by rubyisapm** [comment]
好的，谢谢老师。

**Comment by RubyLouvre** [comment]
```
  <div ms-controller="layout">
             <div id='header' ms-html="header">
            
            </div>

            <div id='sidebar' ms-html="@sidebar">

            </div>
            <div id='main' ms-html="@main">

            </div>
            <div id="footer" ms-html="@footer">

            </div>
        </div>
        
        var h = require('text!header.html)
        var s = require('text!sidebar.html)
        var m = require('text!main.html)
        var f = require('text!footer.html)
        avalon.define({
           $id: "layout",
           header: h,
           sidebar: s,
           main: m,
           footer: footer
        })
       

```

**Comment by caoqitong826** [comment]
发现用text-loader 有问题，用text-webpack-loader 可以

**Comment by RubyLouvre** [comment]
你怎么用啊，我一直用得很好的

**Comment by liaohui1080** [comment]
@rubyisapm  如果不用webpack 应该怎么做

**Comment by bingfengwx** [comment]
@liaohui1080 如果不使用webpack 可以试试模板引擎

**Comment by liubin595338764** [comment]
@RubyLouvre  请教下：打包成多个子页面的时候，我是使用vm嵌套，路由变化后加载子vm的内容，然后手动scan，那么子vm怎么监听获取父vm的数据变化呢？
