### ISSUE TITLE
新增html模板后怎么进行扫描，avalon.scan()方法失效

### ISSUE THREAD

**Issue by qppq54s** [RubyLouvre/avalon#1656]
您好
我使用的是framwork7+avalon，最近想升级到avalon2，但是发现新增一个页面以后，执行avalon.scan()方法失效，而且多次加载页面会报错，请问avalon2怎么处理这种逻辑呢

代码类似是这样的：
`F7.onPageBeforeInit('alarm_history', function () {
     var alarmHistoryAv = avalon.define({
        $id: "alarmHistoryCtl",
        data: []
    });
    getData();
    function getData() {
           data = [...]
    }
    avalon.scan()
});`

**Comment by RubyLouvre** [comment]
http://avalonjs.coding.me/directives/ms-html.html

详看这里
