### ISSUE TITLE
我用webpack打包出来会报avalon未定义

### ISSUE THREAD

**Issue by ShangXinbo** [RubyLouvre/avalon#1657]
common.bundle.js?7493443…:2600 Uncaught TypeError: Cannot set property 'avalon' of undefined
index.bundle.js?7493443…:130 Uncaught ReferenceError: avalon is not defined
为什么呢

**Comment by RubyLouvre** [comment]
不懂你怎么打包，自己看webpack。

**Comment by RubyLouvre** [comment]
https://github.com/PackageBox/webpack-avalon2-seed

**Comment by ShangXinbo** [comment]
就是用webpack.optimize.CommonsChunkPlugin 把avalon放到公共入口common.bundle.js里，会有一个global.avalon=avalon 这里avalon会是undefined

**Comment by ShangXinbo** [comment]
我看avalon已经用webpack封装了entry，是不是这个原因呢，有没有不用webpack打包的avalon版本可以使用

**Comment by RubyLouvre** [comment]
注意,最后必须返回avalon,用于webpack.cofig的 output配置
当然以后改一下webpack.config，可能就不需要这样写。有关如何利用webpack 进行工程化，我也在不断探索。大家有好的方案可以留言给我。


http://www.cnblogs.com/rubylouvre/p/5622738.html

**Comment by ShangXinbo** [comment]
最后必须返回avalon是什么意思，不明白，我觉得是我用的avalon版本内已经有了wepack的entry，我打包后每个页会生成一个entry，但官方webpack要求一个页面只能有一个entry。是不是这个原因

**Comment by ShangXinbo** [comment]
我想知道有没有不用wepack打包的版本供大众使用

**Comment by RubyLouvre** [comment]
我的avalon.test 是这样的
```

var avalon = require('../dist/avalon')
require('../components/button/index')
require('../components/panel/index')

module.exports = avalon

```

你是打包整个工程吗？

**Comment by ShangXinbo** [comment]
我用的是2.1.8版本，再302行会有个global.avalon，这个会引起一个报错Cannot set property 'avalon' of undefined，也就是说这个global是undefined
```
/* WEBPACK VAR INJECTION */(function(global) {//avalon的核心,这里都是一些不存在异议的*核心*方法与属性
				function avalon(el) {
					return new avalon.init(el)
				}

				global.avalon = avalon
				if(typeof window !== 'undefined'){
					window.avalon = avalon
				}

				avalon.init = function (el) {
					this[0] = this.element = el
				}
```

**Comment by ShangXinbo** [comment]
是要打包整个工程，包括所有静态文件和html组件

**Comment by RubyLouvre** [comment]
没有试过，自己研究一下那个该死的webpack

**Comment by Lihuanghe** [comment]
avalon是打的独立的entry,你需要用script标签引入，在webpack里配置externals外部引入avalon.

**Comment by ShangXinbo** [comment]
哦，我知道了，但是webpack文档说一个页面只有一个entry，这样引用的话，一个页面就会有多个entry，好像有问题

**Comment by Lihuanghe** [comment]
刚试了试：
```
var avalon = require('./avalon')
console.log(avalon === window.avalon)
```

这样也可以用,log打印结果是 `true`

**Comment by RubyLouvre** [comment]
你们怎么打包啊

http://www.cnblogs.com/rubylouvre/p/5622738.html

我这样是可以的

**Comment by jeff8912** [comment]
这样做不是非得前后端分离了吗？有没有不分离的，直接script标签引用就能用的版本？
