### ISSUE TITLE
请教 ms-include重新加载外部模板的方法是什么？

### ISSUE THREAD

**Issue by ZeroBinbin** [RubyLouvre/avalon#1658]
我们使用的是avalon1.5x版本的，
当前我们使用的方法是给src重新赋值，然后局部扫描
代码如下:
$('#childPage').html("")
$("#childPage").attr("ms-include-src", src);
avalon.scan($("#childPage").get(0),avalon.vmodels[vmo]);
在外部模板中有创建VM,
在重新加载后，有一定几率原来的VM销毁了，但是并没有重新创建VM
（另外在外部模板中创建VM的ID是一样的，不知道跟这个有没有关系）

**Comment by RubyLouvre** [comment]
你改一下数据就行了。

**Comment by RubyLouvre** [comment]
之前是
```
vm.sss = "aaa/bbb.html"
<div ms-include-src="sss"></div>
```


然后
```
vm.sss = "aaa/ccc.html"
```

**Comment by ZeroBinbin** [comment]
果然，谢谢了
