### ISSUE TITLE
详细的版本列表在2.18以上的版本

### ISSUE THREAD

**Issue by ShangXinbo** [RubyLouvre/avalon#1659]
我现在用2.18,换到其他版本都会出现不同的问题，包括低版本也包括2.110，我想知道可以如何找到准确的2.18的下载地址，或这分支或这tag

**Comment by ShangXinbo** [comment]
网上包括avalon的cdn列表都不能同步最新版本，现在找个版本很难找

**Comment by RubyLouvre** [comment]
网上的cdn好像是让爬虫 每个月爬一次。
https://github.com/RubyLouvre/avalon/tree/

**Comment by RubyLouvre** [comment]
npm install avalon2@2.1.8 试试这个
