### ISSUE TITLE
更新版本后遇到bug

### ISSUE THREAD

**Issue by gogtz** [RubyLouvre/avalon#1661]
at built in 2016-8-3:2 version 2.110 by 司徒正美
是个解析Bug，无法定位问题在哪，2.1.17之前还是正常的，因是在项目工程里所以无法提交例子代码。

浏览器控制台报错如下：

<pre>
<code>

var vnodes = [];
(function(__vmodel__){
vnodes.push({
props: {"class": "row"},
type:"div",
nodeType:1,
"ms-controller":"fixedHeaderTwo",
local:__local__,
vmodel:(function(){
var vm = avalon.vmodels["fixedHeaderTwo"]
if(vm &amp;&amp; __vmodel__&amp;&amp; vm !== __vmodel__){
return __vmodel__ = avalon.mediatorFactoryCache(__vmodel__, vm)
}else if(vm){
return __vmodel__ = vm
}
})(),
order:"ms-controller",
children:(function(){
var vnodes = [];
vnodes.push({
props: {"class": "col-sm-6"},
type:"div",
nodeType:1,
children:(function(){
var vnodes = [];
vnodes.push(avalon.getCachedNode("8; 图片展示1 "));

vnodes.push({
props: {"class": "panel panel-white panel-carousel dots-left no-border no-radius"},
type:"div",
nodeType:1,
children:(function(){
var vnodes = [];
vnodes.push({
props: {"class": "panel-body no-padding height-200"},
type:"div",
nodeType:1,
children:(function(){
var vnodes = [];
vnodes.push({
props: {"data-slick": "{'slidesToShow': 1, 'speed': 300, 'dots': true, 'arrows': false}",
"class": "carousel"},
type:"div",
nodeType:1,
children:(function(){
var vnodes = [];
vnodes.push({
dynamic:"for",
vmodel:__vmodel__,
nodeType:8,
type:"#comment",
nodeValue:"ms-for:item in @$imageSlick1",
signature:"for4697170000000001",
template:"&lt;div class=\"slide padding-20 height-200\" ms-css=\"{ background: 'url(\\\\'' + item[0] + '\\\\')' }\"&gt;&lt;h5 class=\"text-bold text-extra-small text-dark-transparent text-uppercase\"&gt;Prjects &lt;i class=\"fa fa-arrow-circle-o-right\"&gt;&lt;/i&gt;&lt;/h5&gt;&lt;div ms-attr=\"{ 'data-text': item[2], 'data-color': item[3] }\" class=\"lettericon margin-right-10\" data-box=\"round\" data-size=\"lg\"&gt;&lt;/div&gt;&lt;h3 class=\"inline-block\" ms-text=\"item[1]\"&gt;&lt;/h3&gt;&lt;div class=\"block margin-top-10 \"&gt;&lt;span class=\"label background-dark text-white margin-top-10 margin-right-5\"&gt;{{ item[4] }}%&lt;/span&gt;&lt;span class=\"cl-effect-19\"&gt;&lt;/span&gt;&lt;a href=\"#\" class=\"text-extra-small\"&gt; 跟踪项目进度 &lt;/a&gt;&lt;/div&gt;&lt;/div&gt;"});

var loop = (function(){
try{
var __value__ = __vmodel__.$imageSlick1
return __value__
}catch(e){
	avalon.warn(e, "parse other binding【 @$imageSlick1 】fail")
	return ""
}
})() 
avalon._each(loop,function($key, item, traceKey, __local__, vnodes){
vnodes.push({
props: {"class": "slide padding-20 height-200"},
type:"div",
nodeType:1,
"ms-css":(function(){
try{
var __value__ = { background: 'url(\\'' + item[0] + '\\')' }
return __value__
}catch(e){
	avalon.warn(e, "parse css binding【 { background: 'url(\\\\'' + item[0] + '\\\\')' } 】fail")
	return ""
}
})(),
order:"ms-css",
children:(function(){
var vnodes = [];
vnodes.push(avalon.getCachedNode("h5;class-text-bold text-extra-small text-dark-transparent text-uppercase;131"));

vnodes.push({
props: {"class": "lettericon margin-right-10",
"data-box": "round",
"data-size": "lg"},
type:"div",
nodeType:1,
"ms-attr":(function(){
try{
var __value__ = { 'data-text': item[2], 'data-color': item[3] }
return __value__
}catch(e){
	avalon.warn(e, "parse attr binding【 { 'data-text': item[2], 'data-color': item[3] } 】fail")
	return ""
}
})(),
order:"ms-attr",
children:[],
dynamic:true});

vnodes.push({
props: {"class": "inline-block"},
type:"h3",
nodeType:1,
"ms-text":1,
children:[{
nodeType:3,
type:"#text",
dynamic:true,
nodeValue:avalon.parsers.string((function(){
try{
var __value__ = item[1]
return avalon.parsers.string(__value__)
}catch(e){
	avalon.warn(e, "parse text binding【 item[1] 】fail")
	return ""
}
})())}],
order:"ms-text",
dynamic:true});

vnodes.push({
props: {"class": "block margin-top-10 "},
type:"div",
nodeType:1,
children:(function(){
var vnodes = [];
vnodes.push({
props: {"class": "label background-dark text-white margin-top-10 margin-right-5"},
type:"span",
nodeType:1,
children:(function(){
var vnodes = [];
vnodes.push({
type: "#text",
nodeType:3,
dynamic:true,
nodeValue: String((function(){
try{
var __value__ = item[4]
return avalon.parsers.string(__value__)
}catch(e){
	avalon.warn(e, "parse text binding【  item[4]  】fail")
	return ""
}
})() + "%")
});

return vnodes
})(),
skipAttrs:true});

vnodes.push(avalon.getCachedNode("span;class-cl-effect-19;34"));

vnodes.push(avalon.getCachedNode("a;class-text-extra-small;href-#;49"));

return vnodes
})(),
skipAttrs:true});

return vnodes
})(),
dynamic:true});

vnodes.push({
nodeType:8,
type:"#comment",
nodeValue:"for4697170000000001",
key:traceKey});
},__local__,vnodes)
vnodes.push({
nodeType:8,
type:"#comment",
signature:"for4697170000000001",
nodeValue:"ms-for-end:"});

return vnodes
})(),
skipAttrs:true});

return vnodes
})(),
skipAttrs:true});

return vnodes
})(),
skipAttrs:true});

vnodes.push(avalon.getCachedNode("8; / 图片展示1 "));

return vnodes
})(),
skipAttrs:true});

vnodes.push({
props: {"class": "col-sm-6"},
type:"div",
nodeType:1,
children:(function(){
var vnodes = [];
vnodes.push(avalon.getCachedNode("8; 图片展示2 "));

vnodes.push({
props: {"class": "panel panel-white panel-carousel dots-left no-border no-radius"},
type:"div",
nodeType:1,
children:(function(){
var vnodes = [];
vnodes.push({
props: {"class": "panel-body no-padding height-200"},
type:"div",
nodeType:1,
children:(function(){
var vnodes = [];
vnodes.push({
props: {"data-slick": "{'slidesToShow': 1, 'speed': 300, 'dots': true, 'arrows': false}",
"class": "carousel"},
type:"div",
nodeType:1,
children:(function(){
var vnodes = [];
vnodes.push({
dynamic:"for",
vmodel:__vmodel__,
nodeType:8,
type:"#comment",
nodeValue:"ms-for:item in @$imageSlick2",
signature:"for4700485000000001",
template:"&lt;div class=\"slide padding-20 height-200\" ms-css=\"{ background: 'url(\\\\'' + item[0] + '\\\\')' }\"&gt;&lt;h5 class=\"text-bold text-extra-small text-dark-transparent text-uppercase\"&gt; 信息中���用户 &lt;i class=\"fa fa-arrow-circle-o-right\"&gt;&lt;/i&gt;&lt;/h5&gt;&lt;h3 ms-text=\"item[1]\"&gt;&lt;/h3&gt;&lt;span class=\"label\" ms-class=\"item[3]\" ms-text=\"item[2]\"&gt;&lt;/span&gt;&lt;span class=\"cl-effect-3 links block margin-top-10\"&gt;&lt;a href=\"#\" class=\"uppercase text-dark text-uppercase text-bold text-extra-small\"&gt; 显示详情 &lt;i class=\"padding-left-5 fa fa-angle-right\"&gt;&lt;/i&gt;&lt;/a&gt;&lt;/span&gt;&lt;/div&gt;"});

var loop = (function(){
try{
var __value__ = __vmodel__.$imageSlick2
return __value__
}catch(e){
	avalon.warn(e, "parse other binding【 @$imageSlick2 】fail")
	return ""
}
})() 
avalon._each(loop,function($key, item, traceKey, __local__, vnodes){
vnodes.push({
props: {"class": "slide padding-20 height-200"},
type:"div",
nodeType:1,
"ms-css":(function(){
try{
var __value__ = { background: 'url(\\'' + item[0] + '\\')' }
return __value__
}catch(e){
	avalon.warn(e, "parse css binding【 { background: 'url(\\\\'' + item[0] + '\\\\')' } 】fail")
	return ""
}
})(),
order:"ms-css",
children:(function(){
var vnodes = [];
vnodes.push(avalon.getCachedNode("h5;class-text-bold text-extra-small text-dark-transparent text-uppercase;133"));

vnodes.push({
props: {},
type:"h3",
nodeType:1,
"ms-text":1,
children:[{
nodeType:3,
type:"#text",
dynamic:true,
nodeValue:avalon.parsers.string((function(){
try{
var __value__ = item[1]
return avalon.parsers.string(__value__)
}catch(e){
	avalon.warn(e, "parse text binding【 item[1] 】fail")
	return ""
}
})())}],
order:"ms-text",
dynamic:true});

vnodes.push({
props: {"class": "label"},
type:"span",
nodeType:1,
"ms-class":(function(){
try{
var __value__ = item[3]
return __value__
}catch(e){
	avalon.warn(e, "parse class binding【 item[3] 】fail")
	return ""
}
})(),
"ms-text":1,
children:[{
nodeType:3,
type:"#text",
dynamic:true,
nodeValue:avalon.parsers.string((function(){
try{
var __value__ = item[2]
return avalon.parsers.string(__value__)
}catch(e){
	avalon.warn(e, "parse text binding【 item[2] 】fail")
	return ""
}
})())}],
order:"ms-class,ms-text",
dynamic:true});

vnodes.push(avalon.getCachedNode("span;class-cl-effect-3 links block margin-top-10;199"));

return vnodes
})(),
dynamic:true});

vnodes.push({
nodeType:8,
type:"#comment",
nodeValue:"for4700485000000001",
key:traceKey});
},__local__,vnodes)
vnodes.push({
nodeType:8,
type:"#comment",
signature:"for4700485000000001",
nodeValue:"ms-for-end:"});

return vnodes
})(),
skipAttrs:true});

return vnodes
})(),
skipAttrs:true});

return vnodes
})(),
skipAttrs:true});

vnodes.push(avalon.getCachedNode("8; / 图片展示2 "));

return vnodes
})(),
skipAttrs:true});

vnodes.push(avalon.getCachedNode("div;class-col-sm-6;ms-skip-;836"));

vnodes.push(avalon.getCachedNode("div;class-col-sm-6;ms-skip-;1250"));

return vnodes
})(),
dynamic:true});

})(__vmodel__);
return vnodes
 parse error
avalon.js?bust=1470295160317:6984 Uncaught TypeError: renderFn is not a function

</code>
</pre>

**Comment by RubyLouvre** [comment]
这样无法 看啊，写一个精简的例子

**Comment by RubyLouvre** [comment]
你改成每个属性值是双引号括起，里面用单引号试试

**Comment by gogtz** [comment]
控制台就是这么输出，，，，只是今天偶尔打开之前没问题的模块时，控制台报的错
里面的代码应该是avalon2编译后生成的代码吧

**Comment by gogtz** [comment]
ms-for="item in @$imageSlick2" ms-css="{ background: 'url(\'' + item[0] + '\')' }"

会是这里的问题吗？

**Comment by gogtz** [comment]
就是ms-css的问题，我把ms-css删除了就好了

**Comment by gogtz** [comment]
写了一个例子，正美你看一下
<pre>
<code>
&lt;!DOCTYPE html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
    &lt;meta charset="UTF-8"&gt;
    &lt;script type="text/javascript" src="/vendor/plug-in/avalon2/avalon.js"&gt;&lt;/script&gt;
    &lt;script type="text/javascript" src="/vendor/plug-in/jquery/jquery.js"&gt;&lt;/script&gt;
    &lt;script&gt;
        avalon.define({
            $id: "test",
            data1: [
                '1.png', '2.png', '3.png', '4.png', '5.png'
            ]
        })
    &lt;/script&gt;
&lt;/head&gt;
&lt;body&gt;
&lt;div ms-controller="test"&gt;
    &lt;div :for="item in @data1" :css="{ background: 'url(\'' + item + '\')' }"&gt;{{item}}&lt;/div&gt;
&lt;/div&gt;

&lt;/body&gt;
&lt;/html&gt;
</code>
</pre>

**Comment by gogtz** [comment]
:css="{ background: 'url(' + item + ')' }"写成这样就不报错了
