### ISSUE TITLE
请教：avalon组件中的select含有ms-for会警告id

### ISSUE THREAD

**Issue by rubyisapm** [RubyLouvre/avalon#1667]
项目中有个组件的tpl是这样的：
'<select class="form-control" ms-duplex="@form.ExpiryTimeStamp"  ms-widget="{$id:1}">' +
                '<option ms-for="(index,el) in @formSource.ExpiryTimeStamp" ms-attr="{value:el.id}">{{el.name}}</option>' +
                '</select>'

avalon警告：组件没有在ms-widget配置对象中指定全局不重复的$id
但是如何将option上加上ms-widget，avalon会提示: option不合适做组件的标签

请问老师，这种情况该怎么解决呢？

**Comment by RubyLouvre** [comment]
http://avalonjs.coding.me/component.html

看这里，不是所有元素节点都可以作为**组件容器**

只有wbr, tempalte, xmp,及ms-*元素可以。

组件需要在ms-widget配置对象上添加一个$id配置项
