### ISSUE TITLE
avalon学习中的几个问题

### ISSUE THREAD

**Issue by noman798** [RubyLouvre/avalon#1679]
1.

warning! ms-view 组件最好在ms-widget配置对象中指定全局不重复的$id以提高性能!

自定义组件一定要有一个id吗？不写性能会差多少？

2.

<ms-view>
<div slot="content">这是子视图的内容</div>
</ms-view>

用这种方法声明的怎么写id？ 文档上没说明

3.
另外，为什么一定要组件手工写id呢？
为了性能，是不是可以自动给组件生成一个id

4.
『onInit, onReady, onViewChange, onDispose四大生命周期钩子』这个只有组件才有吗？
如果是用avalon.define的vm对象，怎么监控生命周期。

5.
组件一定要隶属于一个ms-controller吗？是不是可以单独声明并使用（类似vue那样）

6.
controller这个单词好长，写起来麻烦，也容易打错。
是不是可以考虑提供一个简写，比如 ctrl

**Comment by RubyLouvre** [comment]
1.  不一定要。写$id会让这个组件存活在内存里面。这是做路由组件非常有用。其次，是$id，不是id

2. 写ms-widget的配置对象。官网上肯定写了

3. 不写$id,有些状态不能保存。不能写死，因为有的人只想用一次。

4. 普通的vm只有onReady钩子，它们是不能销毁。

5. 必须要隶属。要不它怎么给它传数据

6. ms-controller就是这么长。不能改。
