### ISSUE TITLE
给controller动态追加组件的html，如何让组件生效？avalon.scan无效

### ISSUE THREAD

**Issue by noman798** [RubyLouvre/avalon#1680]
给controller动态追加组件的html，如何让组件生效？avalon.scan无效

**Comment by RubyLouvre** [comment]
看了ISSUE的提示信息没有，连可运行的例子都没有！

**Comment by noman798** [comment]
演示代码
http://sandbox.runjs.cn/show/6g1blbss

**Comment by noman798** [comment]
@RubyLouvre 演示代码
http://sandbox.runjs.cn/show/6g1blbss

**Comment by RubyLouvre** [comment]
用错了
avalon2不支持手动追加！
一开始 就应该用ms-html进行占位。
