### ISSUE TITLE
请问如何动态增加多级循环的数据。

### ISSUE THREAD

**Issue by cloudus** [RubyLouvre/avalon#1687]
![image](https://cloud.githubusercontent.com/assets/12695053/17727173/26ea38b2-648a-11e6-84eb-7eb0ad59e309.png)
![image](https://cloud.githubusercontent.com/assets/12695053/17727194/4415125e-648a-11e6-939c-ba1a893518f4.png)
请问，我有二级循环，如何动态增加第二级的循环数组？

**Comment by RubyLouvre** [comment]
http://avalonjs.coding.me/vm.html#监控数组

http://avalonjs.coding.me/directives/ms-for.html

你的ISSUE完全不符合格式！


无法运行也不是BUG

你应该到segementFault中提问

**Comment by cloudus** [comment]
谢谢~，下次我注意~

**Comment by cloudus** [comment]
请问怎样动态增加二级数组，实在抱歉，困扰我很久了，也找不到解决办法，还请不吝指导，谢谢~
![image](https://cloud.githubusercontent.com/assets/12695053/17734965/25b6fac0-64b2-11e6-91bf-9627cf913ea3.png)
![image](https://cloud.githubusercontent.com/assets/12695053/17734972/364300f0-64b2-11e6-97bd-a6c04989f3ee.png)

**Comment by cloudus** [comment]
@RubyLouvre
