### ISSUE TITLE
请问怎样动态增加二级数组，实在抱歉。

### ISSUE THREAD

**Issue by cloudus** [RubyLouvre/avalon#1689]
请问怎样动态增加二级数组，实在抱歉，困扰我很久了，也找不到解决办法，还请不吝指导，谢谢~
![image](https://cloud.githubusercontent.com/assets/12695053/17734965/25b6fac0-64b2-11e6-91bf-9627cf913ea3.png)
![image](https://cloud.githubusercontent.com/assets/12695053/17734972/364300f0-64b2-11e6-97bd-a6c04989f3ee.png)

**Comment by RubyLouvre** [comment]
你的例子不完整我运行不了，讲了这么久，你还不会参考别人的ISSUE来写吗？！

**Comment by RubyLouvre** [comment]
你要写一个简单的例子啊，不要将你的业务代码放上来！
