### ISSUE TITLE
更新后，ms-for报错

### ISSUE THREAD

**Issue by gogtz** [RubyLouvre/avalon#1690]
at built in 2016-8-18:1 version 2.111 by 司徒正美

以下测试，浏览器控制台报错：

> Uncaught TypeError: Cannot read property 'replace' of undefined

测试代码：
<code>
<pre>
&lt;!DOCTYPE html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
    &lt;meta charset="UTF-8"&gt;
    &lt;script type="text/javascript" src="/vendor/plug-in/avalon2/avalon.js"&gt;&lt;/script&gt;
    &lt;script type="text/javascript" src="/vendor/plug-in/jquery/jquery.js"&gt;&lt;/script&gt;
&lt;/head&gt;

&lt;body&gt;
&lt;script&gt;
    var vm = avalon.define({
        $id: "test",
        cfg: {
            'navbar-fixed': {
                $name: 'test0'
            },
            'footer-fixed': {
                $name: 'test1'
            },
            'skinColor': 1
        },
        $lyt: [
            'navbar-fixed', 'footer-fixed'
        ]
    })
&lt;/script&gt;

&lt;div ms-controller="test"&gt;
    &lt;div :for="item in @$lyt" &gt;
        &lt;span&gt; {{ @cfg[item].$name}} &lt;/span&gt;
    &lt;/div&gt;
&lt;/div&gt;

&lt;/body&gt;
&lt;/html&gt;
</pre>
</code>

之前在【built in 2016-8-9:11 version 2.111 by 司徒正美 】中正常。

**Comment by RubyLouvre** [comment]
可以了

但不要这么用。 在循环中不要使用中括号
