### ISSUE TITLE
与ie8polyfill.js在ie8下冲突问题

### ISSUE THREAD

**Issue by areyouse7en** [RubyLouvre/avalon#1695]
avalon版本是2.*，这个冲突所有版本都会碰到。倒不是avalon代码问题，只是想请大神帮忙看看能否解决这个冲突。
问题描述：
ie8下，遇到兼容问题，因为要用到amazeui的样式库，需要加载它的ie8polyfill.js，然后在ie8polyfill.js 里也有写到defineProperty的定义，这可能就跟avalon的那块冲突了。
报错信息如下：
消息: 例外被抛出且未被接住
行: 2466
字符: 17
代码: 0
URI: http://cdn.amazeui.org/amazeui/2.7.2/js/amazeui.ie8polyfill.js

页面就引用两个js，定义了一下vm。
```html
<div ms-controller="vm"></div>
<script src="http://cdn.amazeui.org/amazeui/2.7.2/js/amazeui.ie8polyfill.js"></script>
<script src="http://cdn.bootcss.com/avalon.js/2.1.5/avalon.min.js"></script>
<script>
    var vm = avalon.define({
        $id: 'vm'
    })
</script>
```

**Comment by RubyLouvre** [comment]
不是,一引入就报错了.
我试了一下,将里面1到2601 行的代码全部 干 掉就好了. 不要它里面的 es5 补丁,因为 avalon内部也有一份
