### ISSUE TITLE
ep._lookupSetter__  少写了个下划线 应为 ep.__lookupSetter__ 

### ISSUE THREAD

**Issue by duanSD** [RubyLouvre/avalon#1698]
//safari 9.1.2使用Object.defineProperty重写innerHTML会抛
        // Attempting to change the setter of an unconfigurable property.
        if (ep && ep._lookupSetter__) {

ep._lookupSetter__  少写了个下划线 应为 ep.__lookupSetter__

**Comment by RubyLouvre** [comment]
好了，thanks

**Comment by duanSD** [comment]
还有，为什么不把Promise添加到框架中去呢。做表单验证还要处理这块的兼容性问题，很麻烦的。

**Comment by duanSD** [comment]
建议可以把原来的avalon.promise整合去去

**Comment by RubyLouvre** [comment]
正在测试mmRequest，这个以后也有一套例子

**Comment by duanSD** [comment]
mmRequest，原来的那些功能组件，我都有整合的项目中的用了。我这边的自动化也是webpack、感觉不会很麻烦。加油吧。我在公司强烈要求下使用avalon，同事都在问我和这框架什么关系了。由于很多常用的组件没有avalon1的那么多。我的团队用起来的还是有很多抱怨说要造太多轮子的。我们的产品业务开发量比较多。也希望能提供更多可用组件。一开始打算还大伙完成avalon1到avalon2的组件转换的。但公司实际情况一直只是做到临时使用。或只是拼接JQ插件。所在现在项目的代码量还是比较重的。还好是产品前期。期待司徒能完善

**Comment by Lihuanghe** [comment]
提供丰富的组件这个就不要指望正美一个人能出什么效果了。avalon毕竟比较小众，还是配合jq的组件一起用吧。

**Comment by duanSD** [comment]
结合JQ 基本代码量就会上2.6w行。这量有些大。
