### ISSUE TITLE
[2.1.13]fail to apply effect 

### ISSUE THREAD

**Issue by bakabird** [RubyLouvre/avalon#1702]
## problem
**All In Chorme**

1. I ues avalon(2.1.13) to apply effect to my component (ms-for) ,but it doesn't work.

2. I have uesed chrome to debug,and finding a strange thing:
>When a `father` find `his father` he will lose  his `sons` :)

## code

    <!DOCTYPE html>
    <html lang="zh-cn">
    
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no">
        <title>effect-bug?_issue</title>
    
    
        <script src="http://7xp7u3.com1.z0.glb.clouddn.com/o_1aqrf90bb1s5c89dmo7e6772f.js
    "></script>
        
        <script>
        var vm = avalon.define({
            $id: "sky",
            auth_name: "RDD",
            starsArr: [1, 2, 3, 4, 5, 6],
            action: "enter",
        })
    
        avalon.component("ms-star", {
            template: '<div>为了<slot /></div>',
            defaults: {
                starwish: "世界和平",
            },
            soleSlot: "starwish"
        })
    
        avalon.effect("star", {
            enterClass: "star-enter",
            enterActiveClass: "star-enter-active",
        })
        </script>
    
    
        <style>
        * {
            margin: 0;
            padding: 0;
        }
    
        body {
            overflow: hidden;
            width: 100vw;
            height: 100vh;
            background: linear-gradient(top, rgb(77, 55, 99) 27%, rgb(32, 36, 103) 100%);
            background: -o-linear-gradient(top, rgb(77, 55, 99) 27%, rgb(32, 36, 103) 100%);
            background: -ms-linear-gradient(top, rgb(77, 55, 99) 27%, rgb(32, 36, 103) 100%);
            background: -moz-linear-gradient(top, rgb(77, 55, 99) 27%, rgb(32, 36, 103) 100%);
            background: -webkit-linear-gradient(top, rgb(77, 55, 99) 27%, rgb(32, 36, 103) 100%);
        }
    
        .star-enter {
            font-size: 10vw;
            line-height: 19vw;
            position: relative;
            left: 100vw;
            height: 19vw;
            list-style: none;
            -webkit-transition: left 2s;
            -o-transition: left 2s;
            transition: left 2s;
            text-align: left;
            color: #fff;
        }
    
        .star-enter-active {
            left: 5vw;
        }
        </style>
    
    
    </head>
    
    <body ms-controller="sky">
        <ms-star ms-for="starnumber in [0,1,2,3,4,5]" ms-widget='{starwish:@starsArr[starnumber],$id:"star"+starnumber}' ms-effect='{is:"star",action:@action}'>
        </ms-star>
    </body>
    
    </html>

## error

![使用Chrome浏览器][1]
*（Chrome）*

![使用Chrome浏览器][2]
*（Chrome）*

![使用Chrome浏览器][3]
*（Chrome）*

## version

> * built in 2016-8-23:18 version 2.113 by 司徒正美
> * 2.1.5 and npm 2.1.15

## try

I find it work perfectly in:

1. https://cdnjs.cloudflare.com/ajax/libs/avalon.js/2.1.5/avalon.js
2. version 2.1.11

  [1]: https://sfault-image.b0.upaiyun.com/293/875/293875864-57bc3cf27d24f
  [2]: https://sfault-image.b0.upaiyun.com/373/300/3733009622-57bc3e3d75238
  [3]: https://sfault-image.b0.upaiyun.com/173/387/1733877514-57bc41e637356

**Comment by RubyLouvre** [comment]
```html
<!DOCTYPE html>
<html lang="zh-cn">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no">
    <title>effect-bug?_issue</title>


    <script src="../dist/avalon.js"></script>
    <!-- 😀已经下载了最新版本，并上传到了自己的七牛空间 -->
    <script>
    var vm = avalon.define({
        $id: "sky",
        auth_name: "RDD",
        starsArr: [1, 2, 3, 4, 5, 6],
        action: "enter",
    })

    avalon.component("ms-star", {
        template: '<div>为了<slot /></div>',
        defaults: {
            starwish: "世界和平",
        },
        soleSlot: "starwish"
    })

    avalon.effect("star", {
        enterClass: "star-enter",
        enterActiveClass: "star-enter-active",
    })
    </script>


    <style>
    * {
        margin: 0;
        padding: 0;
    }

    body {
        overflow: hidden;
        width: 100vw;
        height: 100vh;
        background: linear-gradient(top, rgb(77, 55, 99) 27%, rgb(32, 36, 103) 100%);
        background: -o-linear-gradient(top, rgb(77, 55, 99) 27%, rgb(32, 36, 103) 100%);
        background: -ms-linear-gradient(top, rgb(77, 55, 99) 27%, rgb(32, 36, 103) 100%);
        background: -moz-linear-gradient(top, rgb(77, 55, 99) 27%, rgb(32, 36, 103) 100%);
        background: -webkit-linear-gradient(top, rgb(77, 55, 99) 27%, rgb(32, 36, 103) 100%);
    }

    .star-enter {
        font-size: 10vw;
        line-height: 19vw;
        position: relative;
        left: 300px;
        height: 19px;
        width: 200px;
        list-style: none;
        background: red;
        -webkit-transition: left 2s;
        -o-transition: left 2s;
        transition: left 2s;
        text-align: left;
        color: #fff;
    }

    .star-enter-active {
        left: 5px;
    }
    </style>


</head>

<body ms-controller="sky">
    <ms-star ms-for="starnumber in @starsArr" ms-widget='{starwish:@starsArr[starnumber],$id:"star"+starnumber}' ms-effect="{is:'star',action:@action}">
    </ms-star>
</body>

</html>

```

**Comment by RubyLouvre** [comment]
`ms-effect='{is:"star",action:@action}'` ==> ms-effect="{is:'star',action:@action}"

双括号在外

更新
