### ISSUE TITLE
复杂对象监听

### ISSUE THREAD

**Issue by bibiuc** [RubyLouvre/avalon#1705]
![image](https://cloud.githubusercontent.com/assets/5752354/17954393/5cf09df6-6aad-11e6-8fd0-77471a55dfad.png)
这两个this作用域不同导致设置复杂对象时第一个参数是undefined

**Comment by RubyLouvre** [comment]
这样的问题无法牗 ，this都是undefined.你不会bind一下吗

**Comment by bibiuc** [comment]
v1.4
![image](https://cloud.githubusercontent.com/assets/5752354/17955891/018d75dc-6ab8-11e6-98f6-bb43017be405.png)
正常使用
vm.$watch("object",function ( val /*undefined*/,  oldVal /*oldVal*/){

})
需要怎么绑定？不想改你的代码
