### ISSUE TITLE
avalon 手机上 onReady 只触发一次（pc上没问题）

### ISSUE THREAD

**Issue by noman798** [RubyLouvre/avalon#1709]
演示页面 http://output.jsbin.com/vojuze

PC上点击计数器会累加，如下图1
![image](https://cloud.githubusercontent.com/assets/12876555/18002889/453620bc-6bbd-11e6-87df-5c4e277c18f4.png)

手机微信上不管点多少次，始终是1、2，如图2
![1162165913](https://cloud.githubusercontent.com/assets/12876555/18002865/1baad44a-6bbd-11e6-800c-e70b8544bd3b.jpg)

有点类似这个人的提问
【求助】avalon2 调用组件在ms-html显示，能不能重复使用onReady？
https://segmentfault.com/q/1010000006241353

**Comment by noman798** [comment]
我是在onDispose的时候，删除的vmodel上id对应的对象，但是在手机微信浏览器上，貌似这样做并没有清理干净

**Comment by RubyLouvre** [comment]
什么版本啊

**Comment by noman798** [comment]
最新github版

**Comment by noman798** [comment]
@RubyLouvre http://o8o3padwl.bkt.clouddn.com/avalon.modern.2.113.js 
/*!
 * built in 2016-8-26:14 version 2.113 by 司徒正美
 * 2.1.5 and npm 2.1.15

**Comment by RubyLouvre** [comment]
```
div.addEventListener("DOMNodeRemovedFromDocument", function () {
      console.log("ddd")
    })
```

微信X5 支持这事件吗?

**Comment by RubyLouvre** [comment]
那你从主干上拉一下吧。

如果微信真的这么不堪，那么

dispose.compact.js与dispose.modern就没有必要区分。它们都合并成一个。

**Comment by noman798** [comment]
@RubyLouvre 囧，标准版本可以，modern不可以，太囧了。
