### ISSUE TITLE
2.1.14 错误提示

### ISSUE THREAD

**Issue by rubyisapm** [RubyLouvre/avalon#1717]
老师好，
      因为ms-controller类的问题，我将版本升级至2.1.14;
页面中有编辑操作，它的实现方案是后台返回数据并同步至vm中，通过双向绑定初始化页面中的控件。
问题描述：
第一次点击编辑，正常；
第二次点击编辑，请求成功后渲染页面时报错：
avalon.min.js:3 Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
我不了解avalon的报错都表示什么含义，不知道老师能从这些实现中大致知道是哪里的问题吗？
备注：2.1.10版本不会出现这个问题。

**Comment by RubyLouvre** [comment]
看了提示没有，你没有完整简洁的页面我不理你的。

这是浏览器的自己抛的错误！
