### ISSUE TITLE
github上少提交了一个share.js的文件。在dom/event/目录下

### ISSUE THREAD

**Issue by duanSD** [RubyLouvre/avalon#1724]
dom/event/compact.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./share in 
我也不是很确定。也有可能是require引入share.js的路径不对。但我没有找到相关调用的内容。在其它的share.js文件中

**Comment by RubyLouvre** [comment]
什么时候的版本，怎么我打包时没错？
