### ISSUE TITLE
tab按键触发了表单验证的validateInBlur事件的bug

### ISSUE THREAD

**Issue by excellnn** [RubyLouvre/avalon#1728]
在chrome和ie下都有
avalon 2.1.14
我用键盘的上的tab，把光标从第一个input移动到第二个input，结果触发了第二个input的离开验证，是bug吗？

![qq 20160907200104](https://cloud.githubusercontent.com/assets/2382830/18311256/eed1d1c6-7535-11e6-8933-5dc907a37a49.png)
![qq 20160907200107](https://cloud.githubusercontent.com/assets/2382830/18311269/fc01363e-7535-11e6-9fa1-401e3f27d1e7.png)
![qq 20160907200234](https://cloud.githubusercontent.com/assets/2382830/18311283/0d361d3e-7536-11e6-8dc3-b72476120de0.png)

**Comment by RubyLouvre** [comment]
没有完整的页面啊，不要这样截图好不好，我还得敲一遍！
