### ISSUE TITLE
avalon 1.5.6，config component as 'ms-attr-button-a' not work

### ISSUE THREAD

**Issue by xxapp** [RubyLouvre/avalon#1729]
Here is a demo.
http://runjs.cn/code/d1jxbkzg

I had a config like this ```<ms:button ms-attr-button-a="$index+ 10"></ms:button>``` in```ms-repeat```,but it still show the default text as '1'.

**Comment by RubyLouvre** [comment]
ms-attr-a="$index+10" (动态)

改成这样了

或直接 a="10" （静态）

**Comment by RubyLouvre** [comment]
我修改了一下官网的描述～

**Comment by xxapp** [comment]
It works, thank you very much.
