### ISSUE TITLE
The Chrome version 53. X.X.X ms - duplex, lyrics, most of the time JS for less than the value

### ISSUE THREAD

**Issue by 8473874** [RubyLouvre/avalon#1732]
The Chrome version 53. X.X.X ms - duplex, lyrics, most of the time background JS for less than the value
--Chrome 版本 53.X.X.X ms-duplex，中文赋值时，大部分时候后台JS获取不到值

**Comment by RubyLouvre** [comment]
```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Document</title>
        <script type="text/javascript" src="../dist/avalon.js"></script>
    </head>
    <body>
        <div ms-controller="test">
            <input ms-duplex="@aaa"/> {{@aaa}}
        </div>
        <script type="text/javascript">
            var vm = avalon.define({
                $id: 'test',
                aaa: 111
            });
        </script>
    </body>
</html>
```

什么输入 法，我的万寿果五笔好好的

**Comment by 8473874** [comment]
不是输入法的问题，我们的AVALON是1.42版本的。demo如下
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Document</title>
        <script type="text/javascript" src="js/avalon.js"></script>
        <script type="text/javascript">
            var vm = avalon.define({
                $id: 'test',
                searcher: {
                    userName:''
                },
                onsearch:function(argument) {
                    alert(vm.searcher.userName);
                }
            });
        </script>
    </head>
    <body>
        <div ms-controller="test">
            <input type="text" ms-duplex="searcher.userName"/>
            <input type="button" value="搜索" ms-click="onsearch" />
        </div>
    </body>
</html>

输入中文，中文会显示，点击 搜索 按钮，弹出来是空的，如果输入“测试1”，可以正常显示，输入“测试”，则不行。先输入“测试1”，点击按钮，再输入“测试”，也可以正常显示

**Comment by RubyLouvre** [comment]
2.×系列如何?

**Comment by 8473874** [comment]
2.1试了，是好的。但是现在项目太大，要改的东西太多了，不能直接升级2.1

**Comment by RubyLouvre** [comment]
已经修复，快去试试。你这边没问题我就去打TAG
