### ISSUE TITLE
在avalon 2下,使用了双向绑定的输入框,在使用科大讯飞手写输入法时第偶数个字会被忽略

### ISSUE THREAD

**Issue by realperson** [RubyLouvre/avalon#1733]
在avalon 2下,使用了双向绑定的输入框,在使用科大讯飞手写输入法输入时第偶数个字会被忽略.
经检测,在avalon 1下没有这个问题.
请问会是因为avalon 2的绑定机制不一样造成的这个问题吗?

**Comment by RubyLouvre** [comment]
几乎都一样啊

这是手机上的吧。

**Comment by realperson** [comment]
是手机上的,avalon 1下不会有这个问题

**Comment by RubyLouvre** [comment]
你试一下修修

**Comment by realperson** [comment]
昨天想下载最新版试下看可不可以解决这个问题,然后放进项目后报renderFn is not a function的错误

**Comment by RubyLouvre** [comment]
你应该下打TAG的版本

**Comment by realperson** [comment]
OK

**Comment by RubyLouvre** [comment]
可以了吧？

**Comment by realperson** [comment]
下载了avalon-2.1.5放进项目里,renderFn没有报错了
