### ISSUE TITLE
数据绑定语法与c#的Razor的@冲突，可以把@改为别的吗?

### ISSUE THREAD

**Issue by KissKissyou** [RubyLouvre/avalon#1734]
数据绑定中的{{@name}}语法与c#的Razor的@指令冲突，可以把@改为别的吗?

**Comment by sunriseyuen** [comment]
你不是用两个@ 就可以了吗？一个后台运行的razor 以后前端运行的 ，不存在冲突啊

**Comment by areyouse7en** [comment]
用##代替@
{{##name}}
