### ISSUE TITLE
avalon  v1.46  上在谷歌浏览器最新版本 53.0.2785.89  上,中文输入法无法绑定到值

### ISSUE THREAD

**Issue by fireflyhoo** [RubyLouvre/avalon#1735]
1. 普通的input 绑定值, 输入中文后绑定值为空,按空格键后,绑定值正常
2.由于使用了avalon   自带的那套ui组件,所以暂时没有办法升级到 2.x 据测试,2.x 版本值绑定正常.

**Comment by fireflyhoo** [comment]
![image](https://cloud.githubusercontent.com/assets/3061324/18374385/fb411ce2-767e-11e6-82c6-a5198b762d10.png)
我修改代码后在谷歌浏览器输入中文后有如下日志输出


![image](https://cloud.githubusercontent.com/assets/3061324/18374403/20be2f32-767f-11e6-9cdb-f09ffa77c135.png)

**Comment by fireflyhoo** [comment]
`//处理radio, checkbox, text, textarea, password
duplexBinding.INPUT = function (elem, evaluator, data) {
    var $type = elem.type,
            bound = data.bound,
            $elem = avalon(elem),
            composing = false

    function callback(value) {
        data.changed.call(this, value, data)
    }

    function compositionStart() {        
        composing = true;
        console.log('compositionStart');
    }

    function compositionEnd() {
        composing = false;
        console.log('compositionEnd');
        updateVModel();

    }
    var IE9Value
    //当value变化时改变model的值
    var updateVModel = function () {
        console.log('updateVModel');
        var val = elem.value //防止递归调用形成死循环
        if (composing || val === IE9Value){ //处理中文输入法在minlengh下引发的BUG
            console.log('skip');
            return
        }

        var lastValue = data.pipe(val, data, "get")
        if ($elem.data("duplexObserve") !== false) {
            IE9Value = val
            evaluator(lastValue)
            callback.call(elem, lastValue)
        }
    }` 建议  修改事件或者使用延时处理下下

**Comment by 8473874** [comment]
你和我遇到的问题一样

**Comment by yuwgle** [comment]
同样遇到这个问题，新版本升级要改太多东西了。

求补丁

**Comment by herubber** [comment]
还好，我刚开始接触avalon，直接用上最新的 avalon 2

**Comment by RubyLouvre** [comment]
嗯，那我研究研究

**Comment by RubyLouvre** [comment]
已经修复！

**Comment by RubyLouvre** [comment]
大家快去试试，没有问题我就去打tag

**Comment by RubyLouvre** [comment]
```javascript
function compositionEnd() {
    composing = false;

    setTimeout(updateVModel)

}

```

**Comment by monkindey** [comment]
加上去，可行，暂时还没出现其他问题

**Comment by RubyLouvre** [comment]
如果不想升级，自己源码里 搜 compositionEnd方法
改成
```
function compositionEnd() {
    composing = false;
    setTimeout(updateVModel)
}
```
