### ISSUE TITLE
tree组件例子，在IE8报错

### ISSUE THREAD

**Issue by herubber** [RubyLouvre/avalon#1736]
例子：
https://github.com/RubyLouvre/avalon/blob/master/perf/component/树(组件形式).html
avalon版本是 [built in 2016-9-5:15 version 2.114 by 司徒正美] 
操作系统win7，IE11使用仿真模式选择IE8后，出现以下问题：
SCRIPT1041: 名称重定义
文件: avalon.js，行: 8862，列: 25

仿真选到IE9 ，或者用chrome浏览器没有问题

**Comment by RubyLouvre** [comment]
已经修复，等2.1.15
