### ISSUE TITLE
关于$fire和$watch的BUG

### ISSUE THREAD

**Issue by chen77134056** [RubyLouvre/avalon#1739]
================
- 在什么浏览器下,IE6,IE7,chrome51?

- 在avalon什么版本下? 你如果打开avalon源码,将最开头的那段注释贴上来!

- 提供一个可以运行的例子,比如像这人,请认真用``` code ```及与markdown语法编写ISSUE

https://github.com/RubyLouvre/avalon/issues/1665

在chrome51中测试
测试版本1.5.6   更新时间是 2015.9.6

```
avalon.ready(function(){

            var vm=avalon.define({
                $id:'ceshi',
                value1:'测试值',
                $skipArray:['value1'],
                fn:function(){
                      // vm.value1='测试值11';
                    //console.log(vm['value1']);

                         vm.$fire('value1','a','测试值');  //使用.$fire重新监听属性value1
                }

            });

            vm.$watch('value1',function(a,b,c){
                 console.log(a,b,c);   
            });

            avalon.scan(document.getElementsByTagName('body')[0]);
        });


<body ms-controller="ceshi">

   <button ms-click="fn()">{{value1}}</button>

</body>
```

在控制台中返回的结果是：
a undefined value1
为什么无法获取到 之前的旧值？
理论上来说应该返回的是：
a 测试值 value1

开始以为自己的语法写错了，就使用2.114加载，语法不变。（我还记得加上@）
在控制台中返回的结果是：a 测试值 value1

**Comment by RubyLouvre** [comment]
avalon2的$watch传参是 新值，旧值， 属性名！

http://avalonjs.coding.me/vm.html
