### ISSUE TITLE
Avalon 1.57 报*语法错误问题

### ISSUE THREAD

**Issue by rocbin** [RubyLouvre/avalon#1742]
因为中文输入在Chrome53出现duplex同步失效，更新到1.57之后发现类似于如下的代码都会出现如下的错误提示：
SyntaxError: Unexpected token *

Microsoft Edge运行情况也是一样出错。

下面的代码可以重现这个错误：
`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script src="avalon.modern.js"></script>
    <title>Avalon 1.57 demo</title>

    <script>

        avalon.ready(function () {

            avalon.define({
                $id: "test",
                categories: {
                    1: {id: 1, name: "ready"},
                    2: {id: 2, name: "pending"},
                    3: {id: 3, name: "complete"},
                    4: {id: 4, name: "canceled"}
                },
                jobs: [
                    {id: 11, name: 'Todo 11', status: 1},
                    {id: 12, name: 'Todo 12', status: 2},
                    {id: 13, name: 'Todo 13', status: 4},
                    {id: 14, name: 'Todo 14', status: 3}
                ]
            });
            avalon.scan();
        });
    </script>
</head>
<body ms-controller="test">
<h1>TODO List:</h1>
    <ul>
        <li ms-repeat="jobs">
            {{el.id}}_{{el.name}}_{{categories[el.status].name}}
        </li>
    </ul>
</body>
</html>`

上面的代码我在Chrome使用变量监控添加一个监控属性“console.log(array)”使scpCompile函数的array参数打印到控制台方便快速跟踪出错的代码:

```
VM105:1 ["vm1473840017463_0", "'use strict';?var jobs = vm1473840017463_0.jobs;?t…evar_0841473393157 = jobs}catch(e){}?return jobs;"]
VM112:1 ["vm1473840054331_0", "'use strict';?var el = vm1473840054331_0.el;?try{v…ar_0122837320054 = el.id}catch(e){}?return el.id;"]
VM119:1 ["vm1473840055241_0", "'use strict';?var el = vm1473840055241_0.el;?try{v…538932391123 = el.name}catch(e){}?return el.name;"]
VM126:1 ["vm1473840055934_0", "vm1473840055934_1", "'use strict';?var el = vm1473840055934_0.el;?try{v…ame}catch(e){}?return categories[el.status].name;"]0: "vm1473840055934_0"1: "vm1473840055934_1"2: "'use strict';?var el = vm1473840055934_0.el;?try{var _nousevar_0725685237707 = el.status}catch(e){};?var categories = vm1473840055934_1.categories;?try{var _nousevar_013656595586 = categories.*.name}catch(e){}?return categories[el.status].name;"length: 3__proto__: Array[0]
avalon.modern.js:47 warning:exception throwed in [avalon.injectBinding]  SyntaxError: Unexpected token *(…)
```
出错的根本原因是scpCompile函数里面Function编译的字符串有问题：
categories.*.name

之前和司徒正美聊过，按道理说try catch就应该不会抛出异常的，但这直接就Javascript语法错误，没等到执行就报错了。

**Comment by Lihuanghe** [comment]
` try {var ...}catch {} ` 这块代码是我加的。因为你的这个'{{categories[el.status].name}}`绑定，属性里带有变量，获取watch变量时会替换成categories.*.name,结果造成Compile失败。

我还没想要怎么改。
但这个改起来很复杂，要考虑绑定属性有多个变量的情况，如：`categories[el.status].[el.status].[el.status]`
即使修改后也会因无法收集依赖，造成当`el.status`改变时无法更新'{{categories[el.status].name}}`绑定的view.

建议你不要使用这个带变量的绑定。

**Comment by rocbin** [comment]
OK，以前是不知道会有你说的‘修改后也会因无法收集依赖’的这种情况出现的。
如果不支持这样写会非常麻烦，必须得在ajax.success回调里面循环处理data数组增加对应的name。

在我的软件系统里面还存在很多这样的代码，暂时切换回1.56，希望能等你们能帮忙修复这个问题。
谢谢！ @Lihuanghe

**Comment by RubyLouvre** [comment]
应该用一个正则处理一下*

**Comment by RubyLouvre** [comment]
```
<!DOCTYPE html>
<html>
    <head>
        <title>TODO supply a title</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="./dist/avalon.js"></script>
        <script>
           var vm = avalon.define({
               $id: 'test',
                aaa: {
                    b: 222
                }
            })
        </script>
    </head>
    <body>
        <div ms-controller='test'>
            <input ms-duplex="aaa.b"/>{{aaa.b}}
        </div>
    </body>
</html>

```

**Comment by RubyLouvre** [comment]
更新到1.5.8

**Comment by Lihuanghe** [comment]
这个bug，暂未想到更好的解决办法。增加一个表达式是否包含变量的判断。
如果表达式 `a.*.b`这种的，不生成附值 语句。

```
                //bugfix:https://github.com/RubyLouvre/avalon/issues/1742
                //考虑如果绑定表达式中包含变量，会生成'obj.*.property'这样的表达式
                //会造成var x = obj.*.property;语句编译失败。
                
                //表达式中包含变量的不生成附值语句
                if(oldprop.indexOf('.*')<0)
                    ret.push(generateID('_nousevar_' + i) + ' = '+ oldprop)
             
```
