### ISSUE TITLE
用hash做rooter， 用ms-html 根据不同的hash实现组件动态加载， 组件绑定事件失效。

### ISSUE THREAD

**Issue by appletxm** [RubyLouvre/avalon#1743]
用hash做rooter， 用ms-html 根据不同的hash实现组件动态加载，组件设置了cached="true"，第一次成功，第二次再访问组件时，组件所绑定的事件失效。 请大神帮我分析一下，看是不是我的用法有问题。

**Comment by appletxm** [comment]
补充： 我的动态组件都有一个ms-controller包住

**Comment by RubyLouvre** [comment]
这种东西不要到这里问，到segmentFault!   https://github.com/RubyLouvre/avalon/blob/master/perf/component/%E8%B7%AF%E7%94%B1%E7%BB%84%E4%BB%B6.html 

https://segmentfault.com/t/avalon
