### ISSUE TITLE
关于数据视图同步问题！

### ISSUE THREAD

**Issue by sayll** [RubyLouvre/avalon#1749]
遇到的场景如下：
1：数据ajax获取，赋值给vm项，让视图填充。视图一开始就直接找vm的数据项，因为ajax还未执行完毕，数据为空，报出一堆警告信息；
2：有些需要某些文件为前提执行，同样需要异步请求文件，然后构建vm，视图同步出现问题，ajax获取的文件无法同步到视图；
大致代码结构：
```
require.ensure([],function () {
			var vm =  avalon.define({
				$id              : 'vm',
				city:require('../../../_json/city.json'),
				data:{},
			});
			vm.$watch('onReady', function () {
				avalon.ajax({
					/*省略*/
					success:function (data) {
						vm.data = data;
						// 去同步视图去了。
					}
				})
			})
			module.exports = vm;
		},'city')
```

最后想请教一下，有木有什么方法，能标识我数据准备完毕了，然avalon去拿这些数据去渲染页面。
记得以前就一个重新让视图同步的办法。不过我感觉，给个标识，让avalon知道何时去同步视图会更好。这些只是我的愚见。请前辈多多指点啦。

**Comment by starmarker** [comment]
既然你用了ajax……那么ajax就有个配置项complete，可以写在success后边，当然这个complete无论成功与否都会执行，你可以在success里面写个flag=1;判断flag，再同步数据，更新VM

**Comment by sayll** [comment]
你的意思是，先去ajax请求，然后把vm定义在complete这个回调中？
如果这样，HTML视图会报错，因为ajax请求前，它找不到vm这个控制器片段啊。
其实我是想知道有什么好的方法处理数据异步（require or ajax）,vm数据视图化的时机。

**Comment by Lihuanghe** [comment]
视图用到的数据都给一个初值，别懒省事写一个`{}`完事。

**Comment by RubyLouvre** [comment]
LS说得对

**Comment by sayll** [comment]
好吧，那前辈，现在新版有木有办法控制avalon扫描html的时间。以便换种思路，等数据准备完整后，自行去控制扫描视图

**Comment by RubyLouvre** [comment]
这个控制不了，avalon还好暴露了 scan方法，vue ,angular都没有暴露，都是DOMReady后

**Comment by Lihuanghe** [comment]
@sayll 你可以用变通的方法，等数据请求完成后再定义vm. 定义完再手动scan
