### ISSUE TITLE
webpack打包错误 Cannot read property 'type' of null

### ISSUE THREAD

**Issue by momtboy** [RubyLouvre/avalon#1750]
ERROR in ./src/js/lib/avalon.modern.js
Module parse failed: D:\gulp-webpack-avalon\src\js\lib\avalon.modern.js Cannot read property 'type' of null
TypeError: Cannot read property 'type' of null

使用webpack+gulp打包 出现上述错误 版本2.1.4   2.1.5都是同样的问题，其他版本没有测试

**Comment by RubyLouvre** [comment]
不知道啊

https://github.com/RubyLouvre/avalon/blob/master/webpack.config.js

用我这里的配置打包
