### ISSUE TITLE
avalon2遇到了很大的性能问题

### ISSUE THREAD

**Issue by finefun55** [RubyLouvre/avalon#1752]
```
onToogleRootCollapsed: function(obj) {

	var collapsed = !obj.__collapsed;
	obj.__collapsed = collapsed;
	_.forEach(obj.array, toogle);

	function toogle(node) {
		if (node.isParent) {
			node.__collapsed = collapsed;
		}
	}
},
```

大概300多个节点，展开操作。每个节点的object 可以有10个字段，绑定了其中7个，每个节点只有一层，在avalon1.5以下，并没有性能问题。我打算迁移到2.15，可行直接卡死。

![image](https://cloud.githubusercontent.com/assets/6128731/18816529/af2dae76-837e-11e6-8052-2dea9ba2eae6.png)

![qq 20160926003347](https://cloud.githubusercontent.com/assets/6128731/18816668/ea207020-8380-11e6-8a28-084ddcf6fa44.png)

![qq 20160926003625](https://cloud.githubusercontent.com/assets/6128731/18816711/6ca65b9a-8381-11e6-9bb0-564ad69dfd71.png)

**Comment by RubyLouvre** [comment]
这是数组太深吧，这个我下个版本修复
