### ISSUE TITLE
avalon2在所有浏览器下， 嵌套组件的问题

### ISSUE THREAD

**Issue by yyqhlw** [RubyLouvre/avalon#1755]
avalon2在所有浏览器下， 嵌套组件中， 如果子组件和父组件有相同的属性， 那么在子组件中会优先取父组件的属性值，   设计如此？ 还是bug?

**Comment by RubyLouvre** [comment]
是的，因此你需要在ms-widget中指定值

**Comment by RubyLouvre** [comment]
比职子组件有aa,父组件也有aa属性，那么你在使用子组件时，就要
```
<ms-son :widget="{aa: 'cccc'}"></ms-son>
```

**Comment by yyqhlw** [comment]
这种设计有什么特别的好处吗，  在实战复杂的项目中，   嵌套的controller 和 组件很正常，   这样子组件有很大的可能性取到错误的值， 比如说一个弹框组件 有个方法是show,但父级有show 是布尔属性， 一下就挂了啊。 像这种方法我不能也在外面配置吧

**Comment by yyqhlw** [comment]
这样很容易埋雷

**Comment by RubyLouvre** [comment]
是的，正在改进

**Comment by yyqhlw** [comment]
正在基于2.0写state路由系统，  写view标签的时候遇到这个问题，  子级的view用于取顶级的view模板， 造成死循环， 现在的解决办法是把每个view的模板放到随机的属性上了。  
这个问题大概什么时候能修复啊，  感觉avalon2用的更顺手

**Comment by yyqhlw** [comment]
还有一个问题就是关于组件生命周期的， 在可以重写DOM API的浏览器中是重写replaceChild，removeChild等方法来监听组件销毁的。 单这样就有个漏洞， 如果是组件的父级被remove了，这个时候就不会调用组件的onDispose方法了

**Comment by yyqhlw** [comment]
问题有点多，我就都在这里提了。
第三个问题   如果把包含ms-controller的dom移除界面，再添加回来，那么包含在该DOM下的组件不会触发onReady事件，   如果只是单独的移除组件dom再添加回来 是会触发onReady事件的

**Comment by yyqhlw** [comment]
这都是我在写路由系统时遇到的问题，   关于上面的问题通过绕的方式可以避免，但对于想利于avalon2来定制开发一些东西的时候会变的困难重重。    最后祝avalon2发展越来越好.

**Comment by RubyLouvre** [comment]
还有一个问题就是关于组件生命周期的， 在可以重写DOM API的浏览器中是重写replaceChild，removeChild等方法来监听组件销毁的。 单这样就有个漏洞， 如果是组件的父级被remove了，这个时候就不会调用组件的onDispose方法了

这个是怎么被remove掉的啊？ 移出DOM树了，我们这些方法还检测不到吗？

**Comment by yyqhlw** [comment]
在可重写dom方法的浏览器你们只是监听了组件本身被移除dom树，如果是组件的父级被移除监听就失效了

**Comment by RubyLouvre** [comment]
这个也要一级级监听？应该是它本身也没有被ready吧，只有ready后它的dispose回调才生效
