### ISSUE TITLE
百度fis2.0和avalon2.1.8结合使用的问题

### ISSUE THREAD

**Issue by harkhua** [RubyLouvre/avalon#1759]
avalon.js放在static/js下面 直接引入时候浏览器控制台报错：avalon not defined
断点跟踪运行时发现在avalon.js第13行
	else if(typeof define === 'function' && define.amd)
		define([], factory);
factory改成factory()可以解决 不知道这问题是遗漏了括号 还是在判断的时候少了一个分支？

**Comment by PetersonLian** [comment]
直接由 factory 改成 factory()，这肯定是有问题的。

**Comment by PetersonLian** [comment]
你的背景上下文太少，导致这个问题的原因很多

**Comment by RubyLouvre** [comment]
```
 */
(function webpackUniversalModuleDefinition(root, factory) {
	if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory();
	else if(typeof define === 'function' && define.amd)
		define([], factory);
	else if(typeof exports === 'object')
		exports["avalon"] = factory();
	else
		root["avalon"] = factory();
})(this, function() {

```
最开始 不是都这样吗？ 这是webpack自动生成的？

**Comment by RubyLouvre** [comment]
看一下你是不是用了其他框架，它们自带了define方法，

**Comment by PetersonLian** [comment]
所以，怀疑是具体使用的时候的问题。跟avalon无关

**Comment by harkhua** [comment]
fis中有个mod.js类似于require.js

**Comment by RubyLouvre** [comment]
mod.js里面的define方法有没有amd属性啊

**Comment by PetersonLian** [comment]
亲，mod.js的define函数和requirejs的define函数不一样的。
mod.js的define函数，第一个参数是id，而且，没做类型判断。
代码如下：
https://github.com/fex-team/mod/blob/master/mod.js#L109
如mod文档所说，`modJS只实现了AMD的一个子集，如果需要使用完整兼容AMD规范的版本，请使用amd目录下的esl-mod.js，这个版本是基于esl版本基础之上实现了fis的需求。`
总之，不能用fis2自带的mod函数。
解决方案：
1 mod文档里头提到的，你自己去看。使用mod-amd.js之类的。[文档](https://github.com/fex-team/mod)
2 或者，看一下fis2能否不使用modjs，而改成使用requirejs。具体fis2我不清楚了，我用fis3.

**Comment by harkhua** [comment]
好的 谢谢
