### ISSUE TITLE
avalon 新版本Google Chrome中 ms-duplex 无法双向绑定

### ISSUE THREAD

**Issue by 502647092** [RubyLouvre/avalon#1760]
测试版本 1.5, 2.0
Google Chrome升级到最版本 53.0.2785.143 m
中文输入法 我测试的是百度输入法 ms-duplex 无法双向绑定
只能修改数据然后改变视图
INPUT输入不用输入法可以绑定 用输入法就无效了

**Comment by 502647092** [comment]
找了一下issues找到了

**Comment by RubyLouvre** [comment]
如果不想升级，自己源码里  搜 `compositionEnd`方法
改成
```javascript
function compositionEnd() {
    composing = false;
    setTimeout(updateVModel)
}
```
