### ISSUE TITLE
最新google version 53.0.2785.116 ,ms-duplex绑定中文失效

### ISSUE THREAD

**Issue by becky-guo** [RubyLouvre/avalon#1761]
google version is 53.0.2785.116 m
avalon version is 1.45 

ms-duplex中文输入失效，无法将输入的值绑定到vm对象上，输入一个英文以后再输入中文就可以了。因为1.5以上版本改动比较大  不想升级avalon版本，有什么好的解决方案么

**Comment by RubyLouvre** [comment]
如果不想升级，自己源码里  搜 `compositionEnd`方法
改成
```javascript
function compositionEnd() {
    composing = false;
    setTimeout(updateVModel)
}
```
