### ISSUE TITLE
表单验证中，规则描述中语法解析问题

### ISSUE THREAD

**Issue by gogtz** [RubyLouvre/avalon#1765]
更新后的版本：【built in 2016-10-7:23 version 2.115 by 司徒正美】

在:rules指令中的JSON描述的解析过于严格，这样书写兼容性太差，还不好调试！
比如：:rules="{ required: true, minlength: 4 }"  这样写OK!
          :rules="{ required: true, minlength:4 }"   把4前面的空格去掉，在验证时浏览器控制台报错:avalon.js:4916 Uncaught TypeError: Cannot read property 'get' of undefined

浏览器用的是：QQ浏览器9.5(9244)  Chromium50.0.2661.95 极速模式

以下是测试代码：
<code>
<pre>
&lt;!DOCTYPE html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
    &lt;meta charset="UTF-8"&gt;
    &lt;script type="text/javascript" src="/vendor/plug-in/avalon2/avalon.js"&gt;&lt;/script&gt;
    &lt;script type="text/javascript" src="/vendor/plug-in/jquery/jquery.js"&gt;&lt;/script&gt;
&lt;/head&gt;

&lt;body&gt;
&lt;script&gt;
    var vm = avalon.define({
        $id: "test",
        firstName: '',
        validate: {
            onSuccess: function(reasons, event) {
                console.info('OK')
            },
            onError: function(reasons, event) {
                console.info('error')
            }
        }
    })
&lt;/script&gt;

&lt;div ms-controller="test"&gt;
    &lt;form :validate="@validate"&gt;
        &lt;input type="text" placeholder="Insert your First Name" :duplex="@firstName" :rules="{ required: true, minlength:4 }" /&gt;
    &lt;/form&gt;
&lt;/div&gt;

&lt;/body&gt;
&lt;/html&gt;
</pre>
</code>

**Comment by RubyLouvre** [comment]
https://github.com/RubyLouvre/avalon/commit/fe53c3e5e5d04c8235f5cd26e4b4a6fae893b7ae
