### ISSUE TITLE
webpack 打包的amdcss-loader这个插可以分享下吗

### ISSUE THREAD

**Issue by becky-guo** [RubyLouvre/avalon#1766]
oniui上的插件 css 打包就报错,不支持amd css的加载。
require-css-preloader 不好使，哪里有amdcss-loader可以安装上试试

**Comment by becky-guo** [comment]
我现在直接把css拎到模块里面用require加载可以搞定，但是这样太繁琐了,总觉得不爽爽爽爽.....啊

**Comment by RubyLouvre** [comment]
http://www.cnblogs.com/rubylouvre/p/4963984.html

看这篇文章，自己写一个吧

**Comment by RubyLouvre** [comment]
https://github.com/iamllitog/avalonjsLearn/tree/2eca5f5e7db05a1d8be2ca020f07c452837cce98

**Comment by becky-guo** [comment]
@RubyLouvre  看到了，那个和require-css-preloader是一样的代码。thanks!
