### ISSUE TITLE
双向绑定在新版chrome中不能同步中文输入！！！

### ISSUE THREAD

**Issue by qiakr** [RubyLouvre/avalon#1770]
1.x和2.x都有这样的问题，输入中文无法同步到VM,
演示地址 http://codepen.io/roscoe054/pen/XXKYMj?editors=1111

chrome 版本 53.0.2785.101 m (64-bit)

**Comment by RubyLouvre** [comment]
如果不想升级，自己源码里  搜 `compositionEnd`方法
改成
```javascript
function compositionEnd() {
    composing = false;
    setTimeout(updateVModel)
}
```

**Comment by hui453694187** [comment]
<input type="text" id="cardNumber" :duplex="@cardNumber" > 

window.onload = function () {
        $("#cardNumber").focus();
    }
加了 duplex 属性后  ,  输入框无法自动获取焦点了， 去掉就可以，这是为什么？？
