### ISSUE TITLE
双花括号，隐藏没效果

### ISSUE THREAD

**Issue by gongchao** [RubyLouvre/avalon#1772]
avalon 2.1.16 chrome 53

`当avalon的扫描引擎打描到ms-controller/ms-important所在元素时, 会尝试移除ms-controller类名.因此基于此特性,我们可以在首页渲染页面时, 想挡住双花括号乱码问题,可以尝试这样干(与avalon1有点不一样)。`

实际查看dom树，ms-controller 并没有被移除？

**Comment by RubyLouvre** [comment]
你加了类名没有？

**Comment by gongchao** [comment]
@RubyLouvre  这里指的类名是？className??

**Comment by RubyLouvre** [comment]
`<div ms-controller="aaa" class="ms-controller" >`

**Comment by gongchao** [comment]
@RubyLouvre 谢谢，看错了，以为是 属性。。可以请问下最新的2.1.16支持ie8吗？

**Comment by RubyLouvre** [comment]
支持
