### ISSUE TITLE
请问如何在ms-for循环中给js赋值？

### ISSUE THREAD

**Issue by cloudus** [RubyLouvre/avalon#1777]
如题，我想把js代码也循环，传入所需的参数。 麻烦指导一下~谢谢~
![image](https://cloud.githubusercontent.com/assets/12695053/19375741/e018b424-9209-11e6-8528-b70212146eac.png)

**Comment by RubyLouvre** [comment]
不能啊，你的思路不对，你所有操作 都在VM中进行
