### ISSUE TITLE
perf目录下的onViewChange的两个例子不触发onViewChange

### ISSUE THREAD

**Issue by zybn2004** [RubyLouvre/avalon#1778]
浏览器版本：版本 53.0.2785.143 (64-bit)
avalon版本：built in 2016-10-12:10 version 2.1.16（另外通过webpack把mmRouter打包进去了）

《onViewChange的触发.html》和《onViewChange的触发2.html》这两个例子不触发onViewChange，但是《生命周期.html》和《生命周期2.html》都可以触发onViewChange

官网描述的“onViewChange，当这个组件或其子孙节点的某些属性值或文本内容发生变化，就会触发它。”其中对于这句话的“某些属性值”以及“文本内容”发生变化感觉还是有点笼统的哦，“某些”是哪些或者除了哪些？至于文本内容的变化我自己试了下《生命周期2.html》似乎只有去修改vm中的属性值才会触发onViewChange，而直接通过chrome直接修改dom中的文本内容是木有触发onViewChange的

**Comment by RubyLouvre** [comment]
必须通过改数据才行啊！我的触发机制是基于VM，又不是在document  的所有节点上加上监听器！

**Comment by zybn2004** [comment]
恩，可是《onViewChange的触发2.html》中那个update方法执行之后为啥onViewChange木有触发呢？

**Comment by RubyLouvre** [comment]
要属性值与文本发生变化才行

**Comment by zybn2004** [comment]
update方法执行后组件VM中的pageList的值变化了哦，pageList就是属性值吧，这~~~

**Comment by zybn2004** [comment]
@RubyLouvre 司徒老师哇，呃~~~ 这怎么就closed了呢？《onViewChange的触发.html》和《onViewChange的触发2.html》中的onViewChange确实是木有触发呀

**Comment by RubyLouvre** [comment]
在2.2 上基本上解决了
