### ISSUE TITLE
ms-for与ms-duplex的疑惑

### ISSUE THREAD

**Issue by cloudus** [RubyLouvre/avalon#1779]
大大~我有一个这样的需求，在双工绑定和验证遇到了疑惑：
![image](https://cloud.githubusercontent.com/assets/12695053/19384929/b4941eda-923e-11e6-8d7a-be54e2a6f6be.png)

![image](https://cloud.githubusercontent.com/assets/12695053/19384982/eeecf6e2-923e-11e6-86de-ba4ed8d2ed1a.png)

我的所有表单项是不固定的，后台自定义之后，前台获取数据显示所定义的表单项的。
dsData是后台定义的表单项信息。表单类型有text、checkbox、number等，每一个类型可能会有多条表单项。
所有表单项没有默认的数据，然后我想对这些自定义的表单项进行双工绑定到formData，其中formData初始也是空的。
最后我再把formData的数据提交到后台处理。
但是遇到了问题，不知道应该如何对这些不确定的表单项进行绑定。因为还请大大不吝指导~谢谢~

**Comment by RubyLouvre** [comment]
这种应该是搞不定

**Comment by cloudus** [comment]
请问可以这样的不？formData['text'+firld.refid]作为绑定项呢？
或者有没有自定义表单双工绑定的例子呢？

**Comment by RubyLouvre** [comment]
你写一个可以调试的例子吧

**Comment by cloudus** [comment]
谢谢，已经解决了，写了很复杂的逻辑……

**Comment by herubber** [comment]
不知道能不能这样，我没有测试也没看源码，所以参考价值比较低，我猜测和angular一样，js基于原形连继承方式，在ms-for循环的对象不是vm上的对象了，所以双工绑定修改的不是同一个对象，这样，在ms-for循环的时候获取$index, 在双工绑定用 @vmData.listField[$index].field 这样，希望帮忙测试下
