### ISSUE TITLE
请问Promise is not defined应该如何解决？

### ISSUE THREAD

**Issue by cloudus** [RubyLouvre/avalon#1781]
请问Promise is not defined应该如何解决？
我看了一个类似的问题，您说需要引入库？请问是什么库呢？

**Comment by RubyLouvre** [comment]
我不是在控制下提示吗
npm install blurbird什么吗，下载回来，自己在页面引用这个库

**Comment by cloudus** [comment]
更新到最新版本是提示
Uncaught Error: please npm install avalon-promise or bluebird at resource/js/avalon.js:104 
了的，但是引用了
http://bluebirdjs.com/docs/install.html
下的
<script src="//cdn.jsdelivr.net/bluebird/3.4.5/bluebird.js"></script>
还是会提示这个哦~麻烦大大了…

**Comment by RubyLouvre** [comment]
这百度一下就有相关的CDN了

http://www.bootcdn.cn/es6-promise/

<script src="//cdn.bootcss.com/es6-promise/4.0.5/es6-promise.js"></script>
<script src="avalon.js" ></script>

**Comment by cloudus** [comment]
![image](https://cloud.githubusercontent.com/assets/12695053/19464181/d004fa5e-952c-11e6-8e48-7e30543578ca.png)

**Comment by RubyLouvre** [comment]
你前面就报错了吧，因此让它没有装上Promise
