### ISSUE TITLE
mac系统下chrome浏览器用输入法输入ms-duplex无法监听

### ISSUE THREAD

**Issue by penweizgx** [RubyLouvre/avalon#1791]
发现一个诡异的问题，之前一直没有注意，mac系统+chrome浏览器下input调用输入法输入的会ms-duplex无法监听，但是在safari浏览器下又正常监听，不会出现这个问题；在window系统下chrome浏览器也能正常监听！
或用mac系统的同学帮忙测试一下呢？

**Comment by RubyLouvre** [comment]
https://github.com/RubyLouvre/avalon/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20%20%E8%BE%93%E5%85%A5%E6%B3%95

先看一下别人有没有提过类似的ISSUE

这早就解决了
