### ISSUE TITLE
avalonjs能够作为一个模块让requirejs引用吗

### ISSUE THREAD

**Issue by wwwsoftwares** [RubyLouvre/avalon#1792]
avalonjs能够作为一个模块让requirejs引用吗，因为我的项目需要avalonjs的模型绑定功能。选了很多家发现avalon的比较中意
<!--
Thank you for contributing! Please carefully read the following before opening your issue.

中文用户：请尽量用英文描述你的 issue，这样能够让尽可能多的人帮到你。

如何提问
===============
请在提问前详细阅读下面内部

- 没有看过官网先看一遍官网: http://avalonjs.coding.me/
- 没有看过教程先看一遍教程: https://segmentfault.com/u/situzhengmei/articles
- 到论坛用关键查一下有没有人遇到与你相同的问题: http://www.avalon.org.cn/
- 到**segementFault**搜索: https://segmentfault.com/search?q=avalon
- 检查一下已关掉的issue有没有与你相同的问题: https://github.com/RubyLouvre/avalon/issues?q=is%3Aissue+is%3Aclosed

为了提高avalon的影响力,如果确定不是BUG,是你一些疑问与业务难题,请到**segementFault**上发贴子

当然有你有什么分享或avalon组件也建议直接在**segementFault**上发贴子

如果你确定是BUG,请按以下格式提问
================
- 在什么浏览器下,IE6,IE7,chrome51?

- 在avalon什么版本下? 你如果打开avalon源码,将最开头的那段注释贴上来!

- 提供一个可以运行的例子,比如像这人,请认真用``` code ```及与markdown语法编写ISSUE

https://github.com/RubyLouvre/avalon/issues/1665

- 想快点得到解决,请提供具体的操作步骤

- 想快点得到解决, 最好将控制如的错误信息也截图贴上来!

**Comment by RubyLouvre** [comment]
支持

**Comment by wwwsoftwares** [comment]
直接跟模块化js一样的使用么，需要注意的地方吗

**Comment by RubyLouvre** [comment]
自己看requirejs 官网吧。我们都是用webpack等工具来打包JS

**Comment by gogoyqj** [comment]
https://github.com/gogoyqj/mmRouter-demo-list/blob/master/requirejs/gulpfile.js
