### ISSUE TITLE
过滤器在ms-attr{value}中的使用方法

### ISSUE THREAD

**Issue by msak222** [RubyLouvre/avalon#1795]
插值表达式中：{{@reciveBox.subject|isReplyOverFirst}}  正常
，
属性里面使用:attr="{value:@reciveBox.subject|isReplyOverFirst}"报错

**Comment by RubyLouvre** [comment]
{value:@reciveBox.subject}  | isReplyOverFirst

**Comment by msak222** [comment]
Thank you！
