### ISSUE TITLE
avalon使用webpack打包后IE提示缺少标识符、字符串或数字

### ISSUE THREAD

**Issue by Anoxia** [RubyLouvre/avalon#1796]
使用webpack打包avalon-2.1.6，我的代码非常简单，如下：

``` javascript
// 登录页样式
var avalon = require('avalon2');

console.log('console');

var model = avalon.define({
    $id: 'root',
    name: '我是名字'
});
```

在IE8下提示`缺少标识符、字符串或数字`。
使用avalon1.5也是同样的问题，不知哪位有没有遇到过，求解！

**Comment by RubyLouvre** [comment]
看一下那个数组里面多了一个逗号

**Comment by NicholasNC** [comment]
[Babel转换es6怎么支持ie8?](https://segmentfault.com/q/1010000005095558)

```
$ npm install --save-dev babel-plugin-transform-es2015-modules-simple-commonjs

配置：

    

//webpack.config.js
        "plugins": ["transform-es2015-modules-simple-commonjs"]
```

或者在 `.babelrc` 文件中写
```
{
  "presets": ["es2015"],
  "plugins": [
        "transform-es2015-modules-simple-commonjs"
    ]
}
```

不知道这样能不能解决问题

**Comment by RubyLouvre** [comment]
使用es3ify 试试，avalon2.2就是用这个进行转换！

**Comment by twinklexp** [comment]
`    var propMap = { //不规则的属性名映射
        'accept-charset': 'acceptCharset',
        'char': 'ch',
        charoff: 'chOff',
        'class': 'className',
        'for': 'htmlFor',
        'http-equiv': 'httpEquiv'
    };`
avalon.js代码的1677行，在webpack打包后，json对象的key值得单引号被去掉了，导致class裸露在外面，因为class是js保留字，在ie8,ie7里面就报错了，请问这个怎么解决，可以怎么配置webpack,去掉这种压缩吗？
求解

**Comment by yuandyu** [comment]
你这个问题解决了没有？我现在也遇到这个问题

**Comment by Anoxia** [comment]
禁用HTML压缩就好了
