### ISSUE TITLE
 avalon2.1.16版本，使用过滤器的时候无法通过as生成新引用的数组

### ISSUE THREAD

**Issue by liuYuFeng123** [RubyLouvre/avalon#1797]
`<div ms-controller="test">`
<br/>
`<p ms-for="(index,el) in @arr as newArray | filterBy(@fn)">{{el.name}}::{{index}}::{{newArray.length}}</p>`
<br/>
    `</div>`
avalon2.1.16版本，无法通过as生成新引用的数组,控制台提示'ReferenceError:newArray is not defined(…) "parse text binding【 newArray.length 】fail"'

**Comment by RubyLouvre** [comment]
这个在2.2已经修复，很快放出
