### ISSUE TITLE
form验证规则，功能没问题，但会抛出错误。

### ISSUE THREAD

**Issue by sayll** [RubyLouvre/avalon#1800]
built in 2016-10-10:21 version 2.1.16.1 (Enhanced Edition)

Uncaught TypeError: validator.validate is not a function

代码事例，采用https://segmentfault.com/a/1190000004947858

**Comment by RubyLouvre** [comment]
```
/*!
 * built in 2016-11-2:13 version 2.1.17 by 司徒正美
 * https://github.com/RubyLouvre/avalon/tree/2.1.8
 *     修复validate BUG
 */
```
