### ISSUE TITLE
继自定义过滤器在attr上的使用问题

### ISSUE THREAD

**Issue by msak222** [RubyLouvre/avalon#1801]
__
![qq 20161102102549](https://cloud.githubusercontent.com/assets/19371846/19914623/0dd8b67a-a0e7-11e6-93d2-d1e19ecf95ab.png)

自定义过滤器用在attr-value上
:attr="{value:@reciveBox.subject}|isReplyOverFirst"，
突然发现它接收的值不是@reciveBox.subject，而是它前面整个，最后也没有显示结果到输入框

**Comment by msak222** [comment]
按理说，str应该直接是个String，是吗？

**Comment by RubyLouvre** [comment]
http://avalonjs.coding.me/filter.html

看这个页面，拉到最下面，有教你怎么定义过滤器，都不看文档的
