### ISSUE TITLE
ms-html渲染Cannot set property 'textContent' of undefined

### ISSUE THREAD

**Issue by foxinmy** [RubyLouvre/avalon#1802]
非常好用，但遇到一问题。

浏览器：Chrome 版本 54.0.2840.71 (64-bit)

avalon：built in 2016-8-30:17 version 2.114

利用avalon写了一个树形检索的功能，完整代码见[kpcategory.zip](https://github.com/RubyLouvre/avalon/files/568125/kpcategory.zip)。

`npm install `然后 `webpack` 打包，再用浏览器打开`index.html`即可看到效果。

问题重现步骤：

问题一：在文本框中输入`分类1`后，得到结果只有一条，但是页面渲染有两条。

![image](https://cloud.githubusercontent.com/assets/1318274/19953994/c3a4d444-a1ae-11e6-90a7-f023ea346912.png)

问题二：在文本框钟输入`分类11`后，然后删减至`分类`出现渲染失败的异常。

![image](https://cloud.githubusercontent.com/assets/1318274/19954023/139b2e12-a1af-11e6-831a-a37d96f42731.png)

谢谢，期待解决。

**Comment by RubyLouvre** [comment]
新版已经好了
