### ISSUE TITLE
1.5.6版本ms-duplex双向绑定数据有时无法成功赋值或会过滤掉中文

### ISSUE THREAD

**Issue by jwRock** [RubyLouvre/avalon#1806]
hi，在做一个avalon项目的维护，不时出现如题的问题（或许跟浏览器版本有关？测试一般都是在chrome浏览器下遇到），请问可能是什么原因引起的，以前没有接触过avalon框架，没有什么头绪 -_-|||

**Comment by RubyLouvre** [comment]
如果不想升级，自己源码里 搜 compositionEnd方法
改成
```
function compositionEnd() {
    composing = false;
    setTimeout(updateVModel)
}
```

**Comment by RubyLouvre** [comment]
这是chrome53升级改变了事件机制引起的
