### ISSUE TITLE
IE6环境，2.1.17版本下子controller失效

### ISSUE THREAD

**Issue by pyworkshop** [RubyLouvre/avalon#1807]
http://avalonjs.coding.me/directives/ms-controller.html 官方代码无法在ie6环境下生效

chrome下正常
![image](https://cloud.githubusercontent.com/assets/6822879/20124541/16bfed28-a662-11e6-9e7e-dda513486c5b.png)

IE6下失效
![image](https://cloud.githubusercontent.com/assets/6822879/20124552/3ca95efc-a662-11e6-9a50-2ab9d64b22bc.png)

**Comment by RubyLouvre** [comment]
下一个版本修好
