### ISSUE TITLE
2.1.16.1 ms-for 有时页面上的数据没有渲染出来

### ISSUE THREAD

**Issue by digdeep126** [RubyLouvre/avalon#1809]
版本：
/*!
 * built in 2016-10-10:21 version 2.1.16.1 (Enhanced Edition) by 司徒正美
 * https://github.com/RubyLouvre/avalon/tree/2.1.7
 */
问题描述：ms-for 循环在渲染数据时，时常遇到页面上的数据没有渲染出来的问题；需要触发第二次事件才能渲染出来。在chrome, firefox浏览器中都出现过。
没有任何报错。数据确定获取到了，就是没有渲染出来。

**Comment by RubyLouvre** [comment]
要有例子啊
