### ISSUE TITLE
ms-controller 嵌套报错

### ISSUE THREAD

**Issue by juefeng** [RubyLouvre/avalon#1811]
built in 2016-10-10:21 version 2.1.16ee (Enhanced Edition) by 司徒正美 谷歌浏览器
<pre><code class="hljs"><span class="xml"><span class="hljs-tag">&lt;<span class="hljs-title">script</span>&gt;</span><span class="javascript">
    <span class="hljs-function"><span class="hljs-keyword">function</span> <span class="hljs-title">heredoc</span><span class="hljs-params">(fn)</span> </span>{
        <span class="hljs-keyword">return</span> fn.toString().replace(<span class="hljs-regexp">/^[^\/]+\/\*!?\s?/</span>, <span class="hljs-string">''</span>).
                    replace(<span class="hljs-regexp">/\*\/[^\/]+$/</span>, <span class="hljs-string">''</span>).trim().replace(<span class="hljs-regexp">/&gt;\s*&lt;/g</span>, <span class="hljs-string">'&gt;&lt;'</span>)
        }
    <span class="hljs-keyword">var</span> v123 = heredoc(<span class="hljs-function"><span class="hljs-keyword">function</span> <span class="hljs-params">()</span> </span>{
        <span class="hljs-comment">/*
        &lt;div ms-controller="test1"&gt;
        &lt;p ms-click="@alert"&gt;123&lt;/p&gt;
        </span></span></span><span class="hljs-expression">{{@<span class="hljs-variable">ggg</span>}}</span><span class="xml"><span class="gherkin">
        <span class="hljs-variable">&lt;/div&gt;</span>
        <span class="hljs-keyword">*</span>/
    })
</span><span class="hljs-tag">&lt;/<span class="hljs-title">script</span>&gt;</span>
<span class="hljs-tag">&lt;<span class="hljs-title">script</span>&gt;</span><span class="php">
    <span class="hljs-keyword">var</span> vm = avalon.define({
        <span class="hljs-variable">$id</span>: <span class="hljs-string">'test'</span>,
        tpl: <span class="hljs-string">""</span>,
        ggg:{value:<span class="hljs-string">""</span>},
        switch1: <span class="hljs-function"><span class="hljs-keyword">function</span> <span class="hljs-params">()</span> </span>{
            setTimeout(<span class="hljs-function"><span class="hljs-keyword">function</span> <span class="hljs-params">()</span> </span>{
                vm.tpl = v123
            })
        }
    });

    <span class="hljs-keyword">var</span> vm2 = avalon.define({
        <span class="hljs-variable">$id</span>: <span class="hljs-string">'test1'</span>,
        ddd: <span class="hljs-string">'aaaa'</span>,
        alert: <span class="hljs-function"><span class="hljs-keyword">function</span><span class="hljs-params">()</span></span>{
            avalon.log(<span class="hljs-string">'????'</span>)
        }
    });

</span><span class="hljs-tag">&lt;/<span class="hljs-title">script</span>&gt;</span>
<span class="hljs-tag">&lt;<span class="hljs-title">div</span> <span class="hljs-attribute">ms-controller</span>=<span class="hljs-value">"test"</span>&gt;</span>
    <span class="hljs-tag">&lt;<span class="hljs-title">div</span> <span class="hljs-attribute">ms-html</span>=<span class="hljs-value">"@tpl"</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-title">div</span>&gt;</span>
    <span class="hljs-tag">&lt;<span class="hljs-title">button</span> <span class="hljs-attribute">ms-click</span>=<span class="hljs-value">"@switch1"</span>&gt;</span>aaaa<span class="hljs-tag">&lt;/<span class="hljs-title">button</span>&gt;</span>
<span class="hljs-tag">&lt;/<span class="hljs-title">div</span>&gt;</span></span>
</code></pre>

报错信息
render parse error
warn @ avalon.js:99
render @ avalon.js:7300
update @ avalon.js:4124
update @ avalon.js:4037
diff @ avalon.js:4106
diffProps @ avalon.js:6591
diff @ avalon.js:6561
diff @ avalon.js:6565
diff @ avalon.js:6565
batchUpdate @ avalon.js:6625
batchUpdateView @ avalon.js:3435
set @ avalon.js:3419

**Comment by RubyLouvre** [comment]
```html
  it('ms-controller 嵌套报错', function (done) {
        //https://github.com/RubyLouvre/avalon/issues/1811
        div.innerHTML = heredoc(function () {
            /*
              <div ms-controller="ctrl11">
 <blockquote ms-html="@tpl"></blockquote>
 <button ms-click="@switch1" type='button'>aaaa</button>
</div>
             */
        })
        var v123 = heredoc(function () {
            /*
            <div ms-controller="ctrl12">
            <p ms-click="@alert">123</p>
            {{@ggg.value}}
            </div>
            */
        })
        delete avalon.vmodels.ccc
        vm = avalon.define({
            $id: 'ctrl11',
            tpl: "",
            ggg: { value: 111 },
            switch1: function () {

                vm.tpl = v123
            }
        });

        var vm2 = avalon.define({
            $id: 'ctrl22',
            ddd: 'aaaa',
            alert: function () {
                avalon.log('????')
            }
        });
        avalon.scan(div)
        setTimeout(function () {
            var button = div.getElementsByTagName('button')[0]
            fireClick(button)
            console.log('33333')
            setTimeout(function () {
                var blockquote = div.getElementsByTagName('blockquote')[0]
                console.log( blockquote[textProp], '111')
                var text = blockquote[textProp].replace(/[\r\n\s]/g, '').trim()
                expect(text).toBe('123111')
                delete avalon.vmodels.ccc1
                done()

            }, 100)
        }, 100)


    })

```

下一版修好了

**Comment by RubyLouvre** [comment]
下一周已经修好了，等下周发布
