### ISSUE TITLE
 动态改变值 ，双花括号绑值第一次成功，第二次失败，然后继续失败

### ISSUE THREAD

**Issue by iizhangchao** [RubyLouvre/avalon#1812]
动态改变值 ，双花括号绑值第一次成功，第二次失败，然后继续失败，使用ms-text 指令 可以赋值成功,但是ms-text 第一次赋值为 X ； 
chrome 49  /  win10  / avalon.js 2.1.17

<body >

    <div :controller="mainCtr">
        <div :html="@indexTpl"></div>
    </div>

    <script>
        var v123 = '<div :controller="drawingCtr">'+
                        '<div class="drag-add" :css="{left:@leftTopCom.left,top:@leftTopCom.top}">'+
                            '<span id="compName" >{{@leftTopCom.com}}</span>'+
                        '</div>'+
                    '</div>';

        var vmMain = avalon.define({
            $id:'mainCtr',
            indexTpl: v123,

        });

        function getRandom(n){
            return Math.floor(Math.random()*n+1)
        }

        var vmDrawing = avalon.define({
            $id:'drawingCtr',
            company:[
                {com:'成都科技有限公司',x:'159',y:'176',name:'四川'},
                {com:'新疆实业有限公司',x:'47',y:'108',name:'新疆'},
                {com:'青海实业有限公司',x:'119',y:'113',name:'青海'},
                {com:'西藏实业有限公司',x:'61',y:'153',name:'西藏'},
                {com:'云南实业有限公司',x:'147',y:'220',name:'云南'},
                {com:'贵州实业有限公司',x:'189',y:'193',name:'贵州'},
                {com:'广西实业有限公司',x:'197',y:'228',name:'广西'},
                {com:'黑龙江实业有限公司',x:'286',y:'33',name:'黑龙江'},
                {com:'内蒙古实业有限公司',x:'216',y:'83',name:'内蒙古'},
                {com:'广东实业有限公司',x:'226',y:'223',name:'广东'},
                {com:'湖南实业有限公司',x:'214',y:'190',name:'湖南'},
                {com:'江西实业有限公司',x:'242',y:'189',name:'江西'},
                {com:'浙江实业有限公司',x:'268',y:'180',name:'浙江'},
                {com:'上海实业有限公司',x:'276',y:'161',name:'上海'},
                {com:'北京实业有限公司',x:'237',y:'98',name:'北京'},
                {com:'天津实业有限公司',x:'238',y:'89',name:'天津'},
                {com:'山西实业有限公司',x:'215',y:'119',name:'山西'},
                {com:'甘肃实业有限公司',x:'215',y:'102',name:'甘肃'},
                {com:'宁夏实业有限公司',x:'180',y:'184',name:'宁夏'},
                {com:'重庆实业有限公司',x:'191',y:'178',name:'重庆'}
            ],
            leftTopCom:{left:'159',top:'176',com:'成都科技有限公司'},

        });

        function autoShowCompany(){
            var n = vmDrawing.company.length;
            var i = getRandom(n) -1;
            var curCom = vmDrawing.company[i];
            var ltc = vmDrawing.leftTopCom;

            ltc.com = curCom.com;
            ltc.left = curCom.x;
            ltc.top= curCom.y;
            console.log(ltc);

            setTimeout(autoShowCompany,1000);
        }
        autoShowCompany();
    </script>
</body>

avalon.js:94 ReferenceError: 北京实业有限公司 is not defined(…) "parse text binding【 北京实业有限公司 】fail"

**Comment by RubyLouvre** [comment]
下一版已经修好，等下周发布吧
