### ISSUE TITLE
一个表单验证使用问题？如何把某个input的错误信息显示在模版上？

### ISSUE THREAD

**Issue by jinwyp** [RubyLouvre/avalon#1815]
例如在angular1 里面可以直接用 内置提供的变量 例如 myForm.username.$error.required

```html
<form name="myForm" ng-controller="FormController" class="my-form">
  userType: <input name="username" ng-model="userType" required>
  <span class="error" ng-show="myForm.username.$error.required">Required!</span><br>
  <code>userType = {{userType}}</code><br>
  <code>myForm.input.$valid = {{myForm.input.$valid}}</code><br>
  <code>myForm.input.$error = {{myForm.input.$error}}</code><br>
  <code>myForm.$valid = {{myForm.$valid}}</code><br>
  <code>myForm.$error.required = {{!!myForm.$error.required}}</code><br>
 </form>
```

avalon2 如何实现？ 难道只能手动把所有输入框的错误信息 都手动定义错误信息变量？ 这样太多了啊
而且 如何判断错误信息属于哪个输入框的？ 而且如何同时需要根据某个字段的是否错误改变样式正确还是错误。

```javascript
var vm = avalon.define({
        $id: "loginController",
        user : {
            username : '',
            password : ''
        },
        errorUsernameMessage : '',
        errorPasswordMessage : '',
        // 这里要定义若干个输入框的错误信息变量？太麻烦了
        loginValidate : {
            onError: function (reasons) {
                // 这里如何判断错误信息属于哪个输入框的？
                vm.errorUsernameMessage = reasons[0].getMessage()
                console.log("错误： ", reasons)
            },
            onValidateAll: function (reasons) {
                console.log("错误222： ", reasons)
                if (reasons.length) {
                    console.log('有表单没有通过')
                } else {
                    console.log('全部通过')
                }
            }
        }
    });
```

**Comment by RubyLouvre** [comment]
这个很简单啊，你定义一个数组，因为validateAll是返回一个数组的

**Comment by jinwyp** [comment]
validateAll 是必须点击这个表单form的submit才能触发，就是说整个表单form所有的input都验证了。 而我只想要在输入某个input时才触发验证并显示该input 的错误信息。

**Comment by jinwyp** [comment]
经过我不懈的努力，终于摸索出一种方法，这样再多的input项也不用起更多的变量命了
···javascript
    var vm = avalon.define({
        $id: "loginController",
        user : {
            username : '',
            password : ''
        },
        errorMessage : '',
        successInputName : [],
        errorInputName : [],
        loginValidate : {
            onSuccess : function (reasons){
                if (vm.successInputName.indexOf(this.id) === -1) vm.successInputName.push(this.id.toString());
                if (vm.errorInputName.indexOf(this.id) > -1) vm.errorInputName.splice(vm.errorInputName.indexOf(this.id),1);
            },
            onError: function (reasons) {
                vm.errorMessage = reasons[0].getMessage();

                if (vm.successInputName.indexOf(this.id) > -1) vm.successInputName.splice(vm.successInputName.indexOf(this.id),1);
                if (vm.errorInputName.indexOf(this.id.toString()) === -1) vm.errorInputName.push(this.id.toString());

            }
        }
    });
···


···html
<div class="block-center mt-xl wd-xl">
        
        <div class="panel panel-dark panel-flat">
            <div class="panel-body" ms-controller="loginController">

                <h4 class="text-center pv">仓押系统登录 {{@errorInputName.indexOf('inputUsername')}}</h4>

                <form role="form" data-parsley-validate="" novalidate="" class="mb-lg" ms-validate="@loginValidate">
                    <div class="form-group has-feedback " ms-class="[@errorInputName.indexOf('inputUsername')>-1 && 'has-error',  @successInputName.indexOf('inputUsername')>-1 &&'has-success'] ">
                        <input id="inputUsername" type="text" placeholder="用户名" class="form-control" ms-duplex="@user.username" ms-rules='{required:true,minlength:4,maxlength:20}'
                               data-required-message="请输入用户名" data-minlength-message="用户名长度不能少于4位" data-maxlength-message="用户名长度不能大于20位">
                        <span class="fa fa-user form-control-feedback text-muted"></span>
                    </div>

                    <div class="form-group has-feedback" ms-class="[@errorInputName.indexOf('inputPassword')>-1 && 'has-error',  @successInputName.indexOf('inputPassword')>-1 &&'has-success'] ">
                        <input id="inputPassword" type="password" placeholder="密码" class="form-control" ms-duplex="@user.password" ms-rules='{required:true,minlength:6,maxlength:20}'
                               data-required-message="请输入密码" data-minlength-message="密码长度不能少于6位" data-maxlength-message="密码长度不能大于20位">
                        <span class="fa fa-lock form-control-feedback text-muted"></span>
                    </div>

                    <span id="error" class="help-block">{{@errorMessage}}</span>
                    <button type="submit" class="btn btn-block btn-primary mt-lg">登录</button>
                </form>
                <#--<p class="pt-lg text-center">Need to Signup?</p><a href="register.html" class="btn btn-block btn-default">Register Now</a>-->
            </div>
        </div>
        
    </div>

···

**Comment by RubyLouvre** [comment]
是吗，我写到最佳实践中
