### ISSUE TITLE
2.2 版本 webpack 打包会返回一个空对象.

### ISSUE THREAD

**Issue by liujunchina** [RubyLouvre/avalon#1819]
因为前面版本组件之间都是共用作用域，所以感觉需要独立就迫不及待的测试了最新版本。
然后发现两个小问题 
1、 如果我页面 有ms-controller='xxCrl' ，但是在js 里面没有通过 avalon.define 去定义这个作用域的时候就会抛出异常。
![image](https://cloud.githubusercontent.com/assets/6283929/20452493/e57a76a2-ae45-11e6-93fd-c3b6647aba5a.png)

2、通过 webpack 去打包的时候，require 之后返回的是一个空的对象，同时会加载全局变量 
```
(function () {
    // 这里会 返回一个 空对象 {}
    // 同时会照样有一个 全局变量 avalon
    let avalon = require('avalon');
    console.log(avalon);
})();

var vm;
// 因为全局变量 avalon 所以这里并不会抛出异常
console.log('全局变量',avalon);
vm = avalon.define({
    $id:'testCrl',
    str:'父组件str',
    config:{
        test:'父组件测试对象',
        testObj : {
            objStr : '父级对象'
        }
    }
})
```
![image](https://cloud.githubusercontent.com/assets/6283929/20452618/085948e4-ae49-11e6-891c-d384fc91ca4f.png)

输出模块的时候回返回一个空对象 orz

**Comment by RubyLouvre** [comment]
没有例子，我无法还原你的场景

**Comment by RubyLouvre** [comment]
第一个例 子搞定，第二个自己研究打包

**Comment by RubyLouvre** [comment]
已经修复
