### ISSUE TITLE
avalon2.1.16的组件该如何写？

### ISSUE THREAD

**Issue by starmarker** [RubyLouvre/avalon#1820]
在2.1.15上的组件是没有问题，以作者自己写的例子作为例子：

> 
            avalon.component('ms-list', {
                template: '<div><input type="checkbox" ms-for="el in @list" data-duplex-changed="@change" ms-duplex-number="@selected" ms-attr="{value:el}"/></div>'
                , defaults: {
                    selected: [1, 2],
                    list: [1,2,3,4,5],
                    change:function(){
                        console.log('------')
                        console.log(this.selected)
                    }
                }
            });

在2.1.15上是正常的。
但是在2.1.16上。直接报"Uncaught ReferenceError: e is not defined"，
只能求指点了！

**Comment by starmarker** [comment]
经过进一步测试……我发现引用avalon.min.js的时候有这个问题，而引用avalon.js的时候没有这个问题，只是报了其他组件的slot没有闭合！

**Comment by RubyLouvre** [comment]
2.1.16与2.1.16ee都是有问题的
改用rollup后，许多不熟悉
