### ISSUE TITLE
v1.5.6中evaluatorPool使用有缺陷

### ISSUE THREAD

**Issue by sunmaobin** [RubyLouvre/avalon#1833]
> 
> //line 2894
> var getter = evaluatorPool.get(exprId) //直接从缓存，免得重复生成
> if (getter) {
>             if (dataType === "duplex") {
>                 var setter = evaluatorPool.get(exprId + "setter")
>                 binding.setter = setter.apply(setter, binding.args)
>             }
>             return binding.getter = getter
>         }

对于duplex类型的数据，avalon在写入缓存的时候，会同时写入2条记录，key分别是：

- exprId
- exprId + setter

而默认的缓存key大小为128，当超过时，会删除一个（shift）。

> //line 2848
> //缓存求值函数，以便多次利用
>     var evaluatorPool = new Cache(128)

假如缓存池size达到128时，就可能会出现缓存中只有key `exprId`  而没有 `exprId+setter`这个key。

于是 `evaluatorPool.get(exprId + "setter")` 就会获取到 `undefined` ， 接下来 `setter.apply` 就会报错。

我现在已经遇到这个问题了。。。

**Comment by RubyLouvre** [comment]
https://segmentfault.com/a/1190000007614967

已经改好了
