### ISSUE TITLE
chrome版本兼容有问题

### ISSUE THREAD

**Issue by bensontung** [RubyLouvre/avalon#1838]
同样引用度入门例子，
用https://cdnjs.cloudflare.com/ajax/libs/avalon.js/2.1.8/avalon.js没问题，
用https://cdnjs.cloudflare.com/ajax/libs/avalon.js/2.2.0/avalon.js及以后的版本，都提示
Uncaught TypeError: el.attachEvent is not a function
avalon._nativeBind @ avalon.js:2997
avalon.bind @ avalon.js:2767
bootstrap @ avalon.js:3109
(anonymous function) @ avalon.js:3112
(anonymous function) @ avalon.js:18
(anonymous function) @ avalon.js:19
test2.html:9 
Uncaught TypeError: avalon.define is not a function
但现在chrome更新到54版的就没出现此问题，之前是4X版本的

**Comment by RubyLouvre** [comment]
那直接用2.2.2，之前忘记了 export avalon到全局中
