### ISSUE TITLE
avalon2.2.2版本中watch监听问题

### ISSUE THREAD

**Issue by aLoNeIT** [RubyLouvre/avalon#1841]
2.2做了作用于隔离。
经过测试，页面的ms-controller内的提供给组件用的config项内可以不再定义组件内的成员，比如data成员只需要再组件内的defaults下定义，无需再ms-controller中的config下定义，也可以正常使用。
但是当使用$watch时候，传递过来的value就是undefined了。
如果在config内定义了data，那么就不会出现这个问题。

**Comment by RubyLouvre** [comment]
最好有简单的例子
