### ISSUE TITLE
IE8下面ms-for循环出来的input无法获取值

### ISSUE THREAD

**Issue by digdeep126** [RubyLouvre/avalon#1843]
0. avalon.js版本信息：
 * built in 2016-10-10:21 version 2.1.16.1 (Enhanced Edition) by 司徒正美
 * https://github.com/RubyLouvre/avalon/tree/2.1.7
 *     解决$render方法不存在的BUG， 这个是老BUG，在2.1.14已经修了
 *     fix IE6 fixEvent BUG
 *     fix IE6-8 script元素由虚拟DOM变成DOM的BUG
 *     fix IE6-8 对noscript元素innerText操作时抛错的BUG
 *     fix IE6-8 对opacity对值不正确的BUG
 *     fix  Object.freeze方法不存在的BUG
 *     添加可用的arthur.js迷你库
1. IE8版本信息：
   版本：8.0.7601.17514
2. 重现代码：
```<!DOCTYPE HTML>
<html>
<head>
<title>avalon.js-bug</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>
<body ms-controller="orderManage">
	<form method="post">
		<table>
			<tr>
				<th>指标名称</th>
				<th>指标值</th>
			</tr>
			<tr ms-for=" item in @data.examineItemList " style="bgcolor=#FF0000">
				<td ms-text="item.itemName"></td>
				<td>
					<input type="text" ms-duplex="item.itemValue"/>
				</td>
			</tr>
		</table>
		<br>
		<div>
			<button onclick="submit_examineItemResult()">提交</button>
		</div>
	</form>
   
<script type="text/javascript" src="../avalon/jquery.js"></script>
<script type="text/javascript" src="../avalon/dist/avalon.js"></script>
<script type="text/javascript">

var vm = avalon.define({
    $id: "orderManage",
    data: {
    	name: '',
    	user: {},
    	org: {},
    	examineItemList: []
    }
});

$(function(){
	vm.data.examineItemList.push({itemName: 'name1', itemValue: ''});
	vm.data.examineItemList.push({itemName: 'name2', itemValue: ''})
});

function submit_examineItemResult(){
	debugger;
	
	var itemList = vm.data.examineItemList.$model;
	if(itemList != null && itemList.length > 0){
		for(var i=0; i<itemList.length; i++){
			alert(itemList[i].itemValue);	// IE8下面，这里无法获取 input 值，获取到的是空字符串。chrome是正常的。
		}
	}
}

</script>
  </body>
</html>

```
3. 说明，在input输入值，点击 提交按钮，在IE8下面会发现弹出的是空字符串。

**Comment by digdeep126** [comment]
<!DOCTYPE HTML>
<html>
<head>
<title>avalon.js-bug</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>
<body ms-controller="orderManage">
	<form method="post">
		<table>
			<tr>
				<th>指标名称</th>
				<th>指标值</th>
			</tr>
			<tr ms-for=" item in @data.examineItemList " style="bgcolor=#FF0000">
				<td ms-text="item.itemName"></td>
				<td>
					<input type="text" ms-duplex="item.itemValue"/>
				</td>
			</tr>
		</table>
		<br>
		<div>
			<button onclick="submit_examineItemResult()">提交</button>
		</div>
	</form>
   
<script type="text/javascript" src="../avalon/jquery.js"></script>
<script type="text/javascript" src="../avalon/dist/avalon.js"></script>
<script type="text/javascript">

var vm = avalon.define({
    $id: "orderManage",
    data: {
    	name: '',
    	user: {},
    	org: {},
    	examineItemList: []
    }
});

$(function(){
	vm.data.examineItemList.push({itemName: 'name1', itemValue: ''});
	vm.data.examineItemList.push({itemName: 'name2', itemValue: ''})
});

function submit_examineItemResult(){
	debugger;
	
	var itemList = vm.data.examineItemList.$model;
	if(itemList != null && itemList.length > 0){
		for(var i=0; i<itemList.length; i++){
			alert(itemList[i].itemValue);	// IE8下面，这里无法获取 input 值，获取到的是空字符串。chrome是正常的。
		}
	}
}

</script>
  </body>
</html>

**Comment by digdeep126** [comment]
```
<script>
<!DOCTYPE HTML>
<html>
<head>
<title>avalon.js-bug</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>
<body ms-controller="orderManage">
	<form method="post">
		<table>
			<tr>
				<th>指标名称</th>
				<th>指标值</th>
			</tr>
			<tr ms-for=" item in @data.examineItemList " style="bgcolor=#FF0000">
				<td ms-text="item.itemName"></td>
				<td>
					<input type="text" ms-duplex="item.itemValue"/>
				</td>
			</tr>
		</table>
		<br>
		<div>
			<button onclick="submit_examineItemResult()">提交</button>
		</div>
	</form>
   
<script type="text/javascript" src="../avalon/jquery.js"></script>
<script type="text/javascript" src="../avalon/dist/avalon.js"></script>
<script type="text/javascript">

var vm = avalon.define({
    $id: "orderManage",
    data: {
    	name: '',
    	user: {},
    	org: {},
    	examineItemList: []
    }
});

$(function(){
	vm.data.examineItemList.push({itemName: 'name1', itemValue: ''});
	vm.data.examineItemList.push({itemName: 'name2', itemValue: ''})
});

function submit_examineItemResult(){
	debugger;
	
	var itemList = vm.data.examineItemList.$model;
	if(itemList != null && itemList.length > 0){
		for(var i=0; i<itemList.length; i++){
			alert(itemList[i].itemValue);	// IE8下面，这里无法获取 input 值，获取到的是空字符串。chrome是正常的。
		}
	}
}

</script>
  </body>
</html>

</script>
```

**Comment by digdeep126** [comment]
var itemList = list;
	if(itemList != null && itemList.length > 0){
		for(var i=0; i<itemList.length; i++){
			alert(itemList[i].$model.itemValue);
		}
	}
改成如上，绕过了该bug

**Comment by RubyLouvre** [comment]
为了解决这问题，我只能引入一个新API了

 ```javascript
 toJSON: function(){
        //为了解决IE6-8的解决,通过此方法显式地求取数组的$model
        return this.$model = platform.toJson(this)
    },
```
