### ISSUE TITLE
BUG?? ms-rules 正则写法报错

### ISSUE THREAD

**Issue by jinwyp** [RubyLouvre/avalon#1849]
使用最新版 的 "avalon2": "^2.2.2",

chrome  Version 55.0.2883.75 (64-bit)

例子中 

http://avalonjs.coding.me/directives/ms-rules.html

```html
<input id="firstname" 
                           name="firstname" 
                           ms-duplex="@firstname"
                           ms-rules="{required:true, pattern: /[\u4e00-\u9fa5a-z]{2-8}/i }" 
                           data-required-message="必须是中文或字母(3-8个字符)" >

```

pattern: /[\u4e00-\u9fa5a-z]{2-8}/i  这句话 写成 pattern:/  就是去掉:后面的空格.

例如 
ms-rules="{ required:true, pattern:/^1[358][0123456789]\d{8}$/ }"  就报错了. 就是说 pattern: 后面必须要根一个空格 才可以继续写正则表达式吗?  

parse getter: [ { required:true, pattern:/^1[358][0123456789]\d{8}$/ } {required :true, __vmodel__.pattern:/^1[358][0123456789]\d{8}$/  } ]error

如果要加空格, 最好在文档里面说一下

**Comment by RubyLouvre** [comment]
![image](https://cloud.githubusercontent.com/assets/190846/21000076/ad82e230-bd53-11e6-99c0-43e654c2bcb9.png)

**Comment by RubyLouvre** [comment]
![image](https://cloud.githubusercontent.com/assets/190846/21000218/8cc63c12-bd54-11e6-80e3-4293419b1fa3.png)

**Comment by RubyLouvre** [comment]
已经修正，处理正则的问题

**Comment by jinwyp** [comment]
赞, 
有个问题, 修正了后 是不是版本号应该2.2.2 变更一下.  否则现在 npm install avalon2 后还是老版本吧?

**Comment by RubyLouvre** [comment]
还有几个BUG，等修了一起发

**Comment by RubyLouvre** [comment]
https://github.com/RubyLouvre/avalon/issues/1845 这是使用别人的正则一知半解所知。 parser模块太乱了，这么多正则，以后会重构
