### ISSUE TITLE
avalon直接暴露全局变量导致无法webpackcmd打包，tap事件的一处targetTagName的定义也是全局变量

### ISSUE THREAD

**Issue by paul-xia** [RubyLouvre/avalon#1852]
http://cdn.bootcss.com/avalon.js/1.5.9/avalon.mobile.js
113行定义avalon
6174行定义targetTagName

**Comment by RubyLouvre** [comment]
我自己改改，我已经更新了targetTagName，在主干上

**Comment by RubyLouvre** [comment]
你可以改一下它的打包工具

**Comment by paul-xia** [comment]
我自己在项目里改了

**Comment by RubyLouvre** [comment]
avalon不全局就行了？是不是最后面要返回一个avalon?

**Comment by RubyLouvre** [comment]
已经提交
