### ISSUE TITLE
2016-12-9更新的2.2.2 版本数组传入不到组件中

### ISSUE THREAD

**Issue by blanche91** [RubyLouvre/avalon#1855]
2016-12-9更新的2.2.2 版本    谷歌浏览器    数组传入不到组件中 

组件代码：
`class Test{
    /**
     * constructor
     */
    constructor(data) {
        this.template = template;
        this.defaults = {
            pics: []
        };

    }
}
avalon.component('test', new Test());`

组件调用代码：
`<template  ms-widget="{is:'test',pics:@pics}"></template>`

VM代码：
`var vm = avalon.define({
    $id: 'TestCtrl',
    pics: [],
    loadPic: function(){

    	var vmodel = avalon.vmodels.TestCtrl;
	 vmodel.pics = [1,2,,3,4];	
    },
    init: function() {
    	vm.loadPic();
    },
});
avalon.ready(function() {
	vm.init();
});`

**Comment by aben711** [comment]
补充个完整例子
```
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <script src="avalon.js"></script>
    <script>
        avalon.component("vip-test",{
            template:'<div><span ms-for="(index,value) in @data">{{value}}</span></div>',
            defaults:{
                data:[]
            }
        })
        var vm = avalon.define({ 
                $id: "test", 
                data:[]
            }) 
            setTimeout(function(){
             //   vm.data.set(0,123)
                vm.data =  [1,3,4,5,6]
            },500)
    </script>
</head>
<body>
    <div ms-controller="test">
        <xmp ms-widget="{is:'vip-test', id:'vip',data:@data}"></xmp>
    </div>
</body>
</html>
```

**Comment by RubyLouvre** [comment]
已经修好了
