### ISSUE TITLE
2.1.17  对象赋值报错

### ISSUE THREAD

**Issue by dylan20161212** [RubyLouvre/avalon#1858]
![data](https://cloud.githubusercontent.com/assets/24515406/21087475/094cbcca-c061-11e6-9ac2-f21d71ffabdc.png)

赋值的时候报错，数据大概如上图！

avalon.js:5812 Uncaught TypeError: Cannot read property 'insertBefore' of undefined

**Comment by RubyLouvre** [comment]
例子不完整，无法处理，建议升级
