### ISSUE TITLE
2.2.2组件中的onReady函数执行时，为插入真实节点

### ISSUE THREAD

**Issue by aLoNeIT** [RubyLouvre/avalon#1859]
在做组件开发，移植以前写的amap地图组件时候发现，在onReady函数内调用amap进行地图渲染时候，amap无法获取到指定id的dom元素，听过调试发现，在onReady函数中，此时还未插入真实的dom节点。
这个与2.1时不一致，也与官网生命周期描述不一致，不值是否bug？

**Comment by aLoNeIT** [comment]
onReady: function(){
	var oSelf=this;
	//这里写入载入完毕后初始化的代码
        //这里this.$domId是div的id值，因为amap需要这个id来渲染地图，this.$amapConfig是amap的配置项
	this.$amap=new AMap.Map(this.$domId,this.$amapConfig);
        //渲染结束发现this.$amap里面重要的C成员是null
}

**Comment by RubyLouvre** [comment]
做一个简单的例子吧，都不知你说什么。onReady是指组件本身插入到dom树中
