### ISSUE TITLE
components/pager IE6

### ISSUE THREAD

**Issue by sajiang** [RubyLouvre/avalon#1860]
https://github.com/RubyLouvre/avalon/blob/master/components/pager/component%E5%BD%A2%E5%BC%8F.html
under IE8 
![image](https://cloud.githubusercontent.com/assets/13673408/21123399/638a01e0-c113-11e6-89ea-d2e7d7ed92a7.png)

avalon version 2.1.16.1

**Comment by RubyLouvre** [comment]
2.2.2版本应该修好了
