### ISSUE TITLE
技术手册中组件窗口描述与示例代码不一致

### ISSUE THREAD

**Issue by bigqiang** [RubyLouvre/avalon#1864]
技术手册中关于 [组件容器](http://avalonjs.coding.me/component.html#组件容器) 描述的结尾部份提到：

> 组件容器里是不支持ms-widget之外的其他绑定属性
```<wbr :widget="{is:'ms-button'}" :attr="{title:@aaa}" />```
> 上面的:attr属性被忽略

但在部分示例代码中，却发现这种被特别提到的“不支持”用法实际上是支持的。比如 [这个示例代码](https://github.com/RubyLouvre/avalon/blob/master/perf/component/%E5%8D%95%E4%B8%AA%E6%8C%89%E9%92%AE.html) 中35行如下用法：
```html
<xmp :widget="{is:'ms-button'}" :click="@ddd" :attr="{title:@bb}">{{@bb}}</xmp>
```
实际测试表明avalon新版本对组件容器绑定的属性是支持的。建议手册中描述与示例用法保持一致。

**Comment by RubyLouvre** [comment]
我准备去掉了
