### ISSUE TITLE
关于scan过程及onDispose如何触发

### ISSUE THREAD

**Issue by aLoNeIT** [RubyLouvre/avalon#1875]
#### 2：avalonjs.coding.me上面介绍了onDispose生命周期，也说了当真实dom节点移除时会销毁对应组件，那么这个时候会触发onDispose吗？能否给个稍微详细的说明？

**Comment by RubyLouvre** [comment]
scan问题我会修的

2 onDispose的触发机制现在 改变了
 vm上有一个$render对象 它负责视图的扫描，绑定与销毁。

当我们调用avalon.scan时，就会产生一个新的Render对象，它会先将扫描区域移出DOM树，然后扫描每个节点，抽取里面的所有ms-*或:xxx属性 ，将它转换为一个个Action对象。Render对象有一个数组保存所有Action对象，如果这个Render对象被调用了dispose方法 ，就会触发组件中的onDispose钩子。

详见  https://github.com/RubyLouvre/avalon/blob/master/src/renders/domRender.js
