### ISSUE TITLE
avalon2.2.2及以上不支持gb2312编码

### ISSUE THREAD

**Issue by lisleyang** [RubyLouvre/avalon#1876]
测试浏览器 ： chrome;
测试代码 ：
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="gb2312">
    <title>Document</title>
    <script type="text/javascript" src="./avalon/avalon_2.2.2.js"></script>
</head>
<body>
</body>
</html>

```

报错内容 ：
Uncaught SyntaxError: Invalid regular expression: missing /

**Comment by RubyLouvre** [comment]
![image](https://cloud.githubusercontent.com/assets/190846/21313959/79ea7ea8-c62f-11e6-8087-200abb5e61f7.png)

没有报错，看是不是装了什么插件

**Comment by lisleyang** [comment]
不对呀老大，确实是有报错的，这个文件只引用了avalon2.2.2.js一个文件。昨天和群里人讨论过了，把☥符号替换掉就可以了。

![qq 20161220093255](https://cloud.githubusercontent.com/assets/11387234/21335519/77387d5c-c69a-11e6-985a-cf683b5455ce.png)
![qq 20161220093309](https://cloud.githubusercontent.com/assets/11387234/21335520/789bb84e-c69a-11e6-8a79-42f564c6a610.png)
![qq 20161220093516](https://cloud.githubusercontent.com/assets/11387234/21335522/7a200bca-c69a-11e6-8bdf-7e539da7d637.png)

**Comment by RubyLouvre** [comment]
估计你下回来时，转码将原文件转坏了
