### ISSUE TITLE
avalon组件第一次显示undefined无法使用过滤器操作

### ISSUE THREAD

**Issue by DrWeiZhou** [RubyLouvre/avalon#1879]
新手使用avalon 2.2.3
页面上表单组件绑定了一个属性，该属性（后台对应一个hashMap对象）第一次显示时在对象中没有定义，因此avalon组件第一次显示时会显示undefined，希望使用过滤器将undefined转化成空串，但是提示报错。
原先页面是使用java el显示的，el对空值是显示空白的，这样用户可以输入新值，传到后台（springmvc）后会创建出该Java对象并返回对应的json对象在页面上显示，所以avalon显示已有数据没有问题，但是第一次显示新的数据就会出现undefined，不知该如何解决,非常感谢~
```html
<textarea cols="120" class="form-control textarea easyui-validatebox" data-options="required:true" id="detail" name="outlays['device'].detail" ms-duplex="check.outlays['device'].detail | ced"/></textarea><span style="color:red">*</span>
```
```javascript
avalon.filters.ced = function(a){
			alert(a);
       		if( a == undefined || a instanceof undefined){
	       		alert('haha');
	       		return ''
       		}else{
       			return 'haha'
       		}
   		} 
		//创建avalon vm
		var vm = avalon.define({
				$id: 'model',
				check: null,
				delFile: function(delId,name){
					//alert(delId + name);
					deleteFile(delId,name);
				}
			});
		avalon.scan(document.body);
```
加载数据代码
```
function initData(){
    		$.ajax({
			      	data : {checkId: ${checkId}},
			      	dataType : "json",
			      	error : function(XMLHttpRequest, textStatus, errorThrown){
			      		alert("数据加载错误!");
			      	},
			      	success : function(data){
			      		//alert(data['checkReport'].fileName);
                   		vm.check = data; 
			      	},
			      	type : "get",
			 		url: "<%=basePath%>do/check/show"
			 		});
			 //alert('initData');
    	}    	
```
控制台提示错误
```
function anonymous(__vmodel__
/**/) {
return __vmodel__.check.outlays [''device'].detail;
} exec error
function anonymous(__vmodel__
/**/) {
return avalon.composeFilters(["ced"])(__vmodel__.check.outlays ['device' ].detail);
} exec error
```

<!--
Thank you for contributing! Please carefully read the following before opening your issue.

中文用户：请尽量用英文描述你的 issue，这样能够让尽可能多的人帮到你。

如何提问
===============
请在提问前详细阅读下面内部

- 没有看过官网先看一遍官网: http://avalonjs.coding.me/
- 没有看过教程先看一遍教程: https://segmentfault.com/u/situzhengmei/articles
- 到论坛用关键查一下有没有人遇到与你相同的问题: http://www.avalon.org.cn/
- 到**segementFault**搜索: https://segmentfault.com/search?q=avalon
- 检查一下已关掉的issue有没有与你相同的问题: https://github.com/RubyLouvre/avalon/issues?q=is%3Aissue+is%3Aclosed

为了提高avalon的影响力,如果确定不是BUG,是你一些疑问与业务难题,请到**segementFault**上发贴子

当然有你有什么分享或avalon组件也建议直接在**segementFault**上发贴子

如果你确定是BUG,请按以下格式提问
================
- 在什么浏览器下,IE6,IE7,chrome51?

- 在avalon什么版本下? 你如果打开avalon源码,将最开头的那段注释贴上来!

- 提供一个可以运行的例子,比如像这人,请认真用``` code ```及与markdown语法编写ISSUE

https://github.com/RubyLouvre/avalon/issues/1665

- 想快点得到解决,请提供具体的操作步骤

- 想快点得到解决, 最好将控制如的错误信息也截图贴上来!

**Comment by jinwyp** [comment]
avalon2 2.2.3 不会自动过滤 对象没有该属性,原来老版本是可以.

模板中{{@test.text}} 2.2.3 会显示 undefined, 老版会直接不显示任何东西.

**Comment by RubyLouvre** [comment]
已经修正了
