### ISSUE TITLE
data-for-rendered列表渲染完成的问题

### ISSUE THREAD

**Issue by polsnet** [RubyLouvre/avalon#1881]
<body :controller="test">
		<table id="t1">
			<tr :for="($index,item) in ##result" data-for-rendered="##rendered">
				<td>{{item.name}}</td>
				<td><input :duplex-number="item.num" maxlength="9" type="text" class="NumText" /></td>
			</tr> 
		</table>
	</body>

	<script type="text/javascript">
		var vm = avalon.define({
			$id: 'test',
			result: [{
				"name": "登录1",
				"num": 9
			}, {
				"name": "登录2",
				"num": 9
			}],
			rendered: function() {
				alert(1);
				console.log($("#t1 tr"));
				//$(".NumText").numeral();限制文件框只能输入数字
			}
		});
	</script>

在rendered方法被执行时发现页面上的列表相关dom还没有出来。
需要在列表显示出来后执行jquery相关方法对里面的input进行相关操作。是应该用data-for-rendered吗？

**Comment by RubyLouvre** [comment]
已经修正
