### ISSUE TITLE
2.2.0到2.2.3版本中 使用了ms-validate 结果解析后把form解析成novalidate了

### ISSUE THREAD

**Issue by yangzhongye** [RubyLouvre/avalon#1885]
2.2.0到2.2.3版本中 使用了ms-validate 结果解析后把form解析成novalidate了，结果是表单不填任何东西就通过了
以下代码：
`var vm = avalon.define({
		$id:"test",
		adults:[],
		validate:{
			onError: function (reasons) {
                reasons.forEach(function (reason) {
                    console.log(reason.getMessage());
                })
            },
            onValidateAll: function (reasons) {
            	console.log(reasons);
                if (reasons.length) {
                    console.log('有表单没有通过');
                } else {
                    console.log('全部通过');
                }
            }
		},
		subInfo:function(){
			console.log(vm.adults.$model);
			vm.validate.onManual();
		}
	});
	for(var i = 0; i < 3; i++){
		var obj = {};
		obj.name="";
		obj.mobile="";
		obj.cardType="";
		obj.cardNo="";
		vm.adults.push(obj);
	}`

html：`<div ms-controller="test">
		<form ms-validate="@validate">
			<div ms-for="adu in @adults" style="margin-top: 30px;" >
				<div>姓名：<input type="text" ms-duplex="adu.name" ms-rules="{required:true}" /></div>
				<div>手机号：<input type="text" ms-duplex="adu.mobile" ms-rules="{required:true}" /></div>
				<div>证件类型： 
					<select ms-duplex="adu.cardType" ms-rules="{required:true}">
						<option value="">请选择</option>
						<option value="1">身份证</option>
						<option value="2">护照</option>
						<option value="3">其他</option>
					</select>
				</div>
				<div>证件号：<input type="text" ms-duplex="adu.cardNo" ms-rules="{required:true}" /></div>
			</div>
			<button type="button" ms-click="@subInfo">提交</button>
		</form>
	</div>`

![qq 20161226160706](https://cloud.githubusercontent.com/assets/7693130/21478426/53b9e334-cb86-11e6-8369-1ad890ac2cd7.png)
![qq 20161226160823](https://cloud.githubusercontent.com/assets/7693130/21478441/6b75a9fe-cb86-11e6-9939-6299baf12032.png)

**Comment by yangzhongye** [comment]
[NewFile.txt](https://github.com/RubyLouvre/avalon/files/672767/NewFile.txt)
文件是整个页面代码

**Comment by RubyLouvre** [comment]
已经修正

**Comment by RubyLouvre** [comment]
```html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>Insert title here</title>
    <script src="./dist/avalon.js"></script>
    <script type="text/javascript">
        var vm = avalon.define({
            $id: "test",
            adults: [],
            validate: {
                onError: function(reasons) {
                    reasons.forEach(function(reason) {
                        console.log(reason.getMessage())
                    })
                },
                onValidateAll: function(reasons) {
                    console.log(reasons)
                    if (reasons.length) {
                        console.log('有表单没有通过')
                    } else {
                        console.log('全部通过')
                    }
                }
            },
            subInfo: function() {
                console.log(vm.adults.$model)
                vm.validate.onManual()
            }
        })
        for (var i = 0; i < 3; i++) {
            var obj = {}
            obj.name = ""
            obj.mobile = ""
            obj.cardType = ""
            obj.cardNo = ""
            vm.adults.push(obj)
        }
    </script>
</head>

<body>
    <div ms-controller="test">
        <form ms-validate="@validate">
            <div ms-for="adu in @adults" style="margin-top: 30px;">
                <div>姓名：<input type="text" ms-duplex="adu.name" ms-rules="{required:true}" /></div>
                <div>手机号：<input type="text" ms-duplex="adu.mobile" ms-rules="{required:true}" /></div>
                <div>证件类型：
                    <select ms-duplex="adu.cardType" ms-rules="{required:true}">
						<option value="">请选择</option>
						<option value="1">身份证</option>
						<option value="2">护照</option>
						<option value="3">其他</option>
					</select>
                </div>
                <div>证件号：<input type="text" ms-duplex="adu.cardNo" ms-rules="{required:true}" /></div>
            </div>
            <button type="button" ms-click="@subInfo">提交</button>
        </form>
    </div>
</body>

</html>
```
