### ISSUE TITLE
avalon2.2.3 组件独立作用域问题

### ISSUE THREAD

**Issue by MaxSherry** [RubyLouvre/avalon#1886]
```html
<!DOCTYPE html>
<html lang="zh-CN">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <link href="//cdn.bootcss.com/bootstrap/2.3.2/css/bootstrap.min.css" rel="stylesheet">

        <script src="../../dist/avalon.js"></script>


    </head>
    <body>
        <div ms-controller="test">
            <xmp is="ms-select" ms-widget="{items:@items, value:@value}" ></xmp>
            {{@value}}
            <button ms-click="@change">test</button>
        </div>

        <xmp is="ms-button" ms-widget="{buttonText:'click me',uu:'bbb'}"></xmp>
        <div id="select_tpl" style="display:none;" ms-skip>

        </div>
        <script>
            var vm = avalon.define({
                $id: 'test',
                //msSelect:{
                //    id:'sel',
                    items: ['请选择', '选项一', '选项二'],
                    value: '请选择',
                    onChange:function(a, b){
                        console.log(a,b)

                    },
                //}
                change:function(){
                    this.value=""+new Date
                }
            });
            function heredoc(fn) {
                return fn.toString().replace(/^[^\/]+\/\*!?\s?/, '').
                        replace(/\*\/[^\/]+$/, '').trim().replace(/>\s*</g, '><')
            }
            var sel = avalon.component("ms-select", {
                template: heredoc(function () {
                    /*
                     <div ms-class="['btn-group', @_open && 'open']">
                     <a name="dropdown-toggle" class="btn dropdown-toggle" 
                     data-toggle="dropdown" ms-click="@_openDropDown | prevent" href="#">
                     {{@value}}
                     <input ms-attr="{name:@name,value:@value}" type="hidden">
                     <span class="caret"></span>
                     </a>
                     <ul class="dropdown-menu" >
                     <li ms-for="(key, val) in @items" >
                     <a href="javascript:;" class="not-close" 
                     ms-click="@_selectValue(key, $event)">{{val}}</a>
                     </li>
                     </ul>
                     </div>
                     */
                }),
                defaults: {
                    items: [],
                    value: '',
                    _open: false,
                    name: '',
                    onInit: function (e) {
                        var vm = this;
                        avalon(document).bind('click', function (e) {
                            if (e.target.name !== 'dropdown-toggle') {
                                vm._open = false
                            }
                        })
                    },
                    _selectValue: function (key) {
                        var old = this.value
                        var neo = this.items[key]
                        if (old !== neo) {
                            this.value = neo
                            console.log("a", this.hasOwnProperty('onChange'),this)
                            if (this.hasOwnProperty('onChange') && typeof this.onChange === 'function') {
                                 console.log("b")
                                var ret = this.onChange(neo, old)
                                if (ret !== false) {
                                    this._open = false
                                }
                            }
                        }
                    },
                    _openDropDown: function () {
                        this._open = true
                    }
                }
            });
            /*sel.defaults.onChange = function(o,n){
                console.log('cg', o,n)
            }*/

            avalon.component('ms-button', {
                template: '<button type="button" ms-click="@val"><span><slot /></span></button>',
                defaults: {
                    buttonText: "button",
                    val:function(){
                        vm.value="testmvalue"+new Date
                    }
                },
                soleSlot:"buttonText"
            })
        </script>
        <p>给用户用的API有</p>
        <ul>
            <li>value:用于提交表单</li>
            <li>name:用于提交表单</li>
            <li>onChange:当value改变时触发,如果它返回false则不会自动关闭菜单</li>
            <li>items:列表中的内容</li>
        </ul>
    </body>
</html>
```

![0f77bdd6-4b9a-4fc7-a654-8f826fd7cdf](https://cloud.githubusercontent.com/assets/3919535/21480218/e5612dc4-cb95-11e6-94bb-414e794ec214.jpg)

我点击"changeVal"按钮,按理说应该button前的展示的值会变"newvalue",而下拉列表的值应该还是保持不变是"请选择",但是现在是全都跟着变了;请问这是个bug,还是属正常情况?

**Comment by RubyLouvre** [comment]
```
           当你点击下面的按钮 -->
            进入val回调
            它改变页面的主vm的value
            主vm的作用范围覆盖下面的两个组件(ms-select,ms-button),
            ms-select是通过ms-widget="{items:@items, value:@value}"进行传参
            于是这个组件的value也变
            这个与react的行为一致的
```

**Comment by MaxSherry** [comment]
`<script>
            var vm = avalon.define({
                $id: 'test',
                items: ['请选择', '选项一', '选项二'],
                value: '请选择',
                onChange:  function(a, b){
                    //vm.value = a; 此处将付值操作注释
                },
                changeVal:function(){
                    this.value = 'newvalue';
                }
            });
            function heredoc(fn) {
                return fn.toString().replace(/^[^\/]+\/\*!?\s?/, '').
                        replace(/\*\/[^\/]+$/, '').trim().replace(/>\s*</g, '><')
            }
            avalon.component("ms-select", {
                template: heredoc(function () {
                    /*
                     <div ms-class="['btn-group', @_open && 'open']">
                     <a name="dropdown-toggle" class="btn dropdown-toggle" 
                     data-toggle="dropdown" ms-click="@_openDropDown | prevent" href="#">
                     {{@value}}
                     <input ms-attr="{name:@name,value:@value}" type="hidden">
                     <span class="caret"></span>
                     </a>
                     <ul class="dropdown-menu" >
                     <li ms-for="(key, val) in @items" >
                     <a href="javascript:;" class="not-close" 
                     ms-click="@_selectValue(key, $event)">{{val}}</a>
                     </li>
                     </ul>
                     </div>
                     */
                }),
                defaults: {
                    items: [],
                    value: '',
                    _open: false,
                    name: '',
                    onInit: function (e) {
                        var vm = this;
                        avalon(document).bind('click', function (e) {
                            if (e.target.name !== 'dropdown-toggle') {
                                vm._open = false
                            }
                        })
                    },
                    onChange:  function(a, b){
                       //默认方法
                    },
                    _selectValue: function (key) {
                        var old = this.value
                        var neo = this.items[key]
                        if (old !== neo) {
                            this.value = neo
                         
                            var ret = this.onChange(neo, old)
                            if (ret !== false) {
                                this._open = false
                            }
                        
                        }
                    },
                    _openDropDown: function () {
                        this._open = true
                    }
                }
            });
        </script>`

如果这样的话,我把主vm里的onChange方法里的内容注释,不改变主vm的value; 会出现这样的情况:
点击"changeVal" 按钮,主vm里的value改变了,"ms-select"里的value也同步改变了; 但是点击下拉框修改值后,,"ms-select"里的value改变了,而主vm里的value没有变化.
这样就是主vm里的value --> "ms-select"里的value 是同步的
"ms-select"里的value --> 主vm里的value 不是同步的
个人感觉组件独立作用域并没有完全被独立

在vue里使用情况,有一个sync来做控制,如果使用了sync,数据是双向绑定的; 如果没有使用sync,主vm将"ms-select"里的value付值完之后,各自都是独立的,各自的value改变不会对对方的value做改变操作.

**Comment by RubyLouvre** [comment]
自己独立了
改变父节点，肯定改变子节点，这是react 的思路，vue2也没有sync。因为 vue1 的思路不对，都改成react

**Comment by RubyLouvre** [comment]
http://www.tuicool.com/articles/AzQzEbq

**Comment by MaxSherry** [comment]
收到,十分感谢
