### ISSUE TITLE
for循环一个数组生成option出现getOptionValue(...).trim is not a function

### ISSUE THREAD

**Issue by buxkk321** [RubyLouvre/avalon#1891]
代码如下
http://runjs.cn/code/r4byupaa
如果:for遍历的是一个对象 就不会出现这个问题

**Comment by buxkk321** [comment]
找到一个解决办法   
:attr="{value:window.String(i)}"
不过感觉还是有点麻烦啊

**Comment by RubyLouvre** [comment]
已经修复，下周一发个新版本
