### ISSUE TITLE
 avalon.js 1.5.5 has compatibility issue with jquery.livequery.js

### ISSUE THREAD

**Issue by foresightyj** [RubyLouvre/avalon#1893]
I have a minimal test case for this problem:

```
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body>
	<div class="lq">livequery</div>
</body>
<script type="text/javascript" src="http://apps.bdimg.com/libs/jquery/1.11.3/jquery.min.js"></script>
<script type="text/javascript" src="jquery.livequery.js"></script>
<script type="text/javascript" src="http://cdn.bootcss.com/avalon.js/1.5.9/avalon.js"></script>
<script type="text/javascript">
	$('.lq').livequery(function(){
		alert("livequery success!");
	});
</script>
</html>

```

Sorry, I couldn't find a livequery cdn path and also I am having problems in uploading a zipped project file here so I am pasting the path to the jquery.livequery.js below:

http://github.com/brandonaaron/livequery/raw/master/jquery.livequery.js

And the error message is:

![image](https://cloud.githubusercontent.com/assets/1296736/21564538/be0ba948-cec9-11e6-85a3-bf1975d4534f.png)

Switching the loading order of livequery and avalon.js, the error will disappear.

This error doesn't occur in avalon2, but as I need to support IE8, I am heavily dependent on avalon1 right now.

I also encountered in the past compatibility issues of avalon1 with moment.js.

I really love avalon so I am trying to figure out the root cause. Thanks.

**Comment by RubyLouvre** [comment]
http://avalonjs.github.io/index2.html#tutorial/engineering/jquery.html

![image](https://cloud.githubusercontent.com/assets/190846/21581305/7db00606-d067-11e6-893c-f384748dc8b0.png)
