### ISSUE TITLE
if指令问题

### ISSUE THREAD

**Issue by tandaly** [RubyLouvre/avalon#1898]
## 问题描述

在for指令里用了if指令，且在if指令前用了click指令，会出现问题，如果把click指令去掉或者放在if指令后面就不会有问题，具体现象如下：

## 代码
![image](https://cloud.githubusercontent.com/assets/3762187/21673331/63fc1b4c-d363-11e6-81e9-a6b27397bb7f.png)

## 结果
![image](https://cloud.githubusercontent.com/assets/3762187/21673336/69ce6cf0-d363-11e6-93b7-b04c8748fe6f.png)

## avalon版本  
`avalon.modern.js`

```
built in 2017-1-4:13:3 version 2.2.4 by 司徒正美
https://github.com/RubyLouvre/avalon/tree/2.2.3

更改下载Promise的提示
修正IE下 orderBy BUG
修复ms-for在循环利用对象数组的元素时,旧有元素的指令没有进行刷新的BUG
修复effect内部传参 BUG
重构ms-validate的绑定事件的机制

```

**Comment by RubyLouvre** [comment]
能给一个完整的简单的例子吗，不要截图
