### ISSUE TITLE
avalon2.2不能兼容到IE浏览器

### ISSUE THREAD

**Issue by zyw976532735** [RubyLouvre/avalon#1901]
司徒老师，我在使用avalon过程中遇到不能兼容IE 浏览器问题，avalon版本2.2，不兼容IE6,7,8,9，其它浏览器支持，具体报错：
![all](https://cloud.githubusercontent.com/assets/18543159/21704922/65cb3a2c-d3f7-11e6-8ccb-be245aa5ac72.png)

第一个错误对应位置：
![1](https://cloud.githubusercontent.com/assets/18543159/21704923/67a7b17c-d3f7-11e6-809b-2edc4c4bb692.png)

第二个错误对应位置：
![2](https://cloud.githubusercontent.com/assets/18543159/21704942/78222654-d3f7-11e6-9889-c394d005763f.png)

非常感谢！

**Comment by RubyLouvre** [comment]
能啊，你要给出完整的例子，我都在IE6下测试过

**Comment by zyw976532735** [comment]
猿代码：
<div class="wrap tabCon hide clr bg-f ms-controller" ms-controller="all_pic">
    <div ms-if="@data == ''" class="search-explain">@{{ warn }}</div>
    <div class=""></div>
    <div class="container goods goods__list clr container1">
        <div class="artist-tp_pic ajax_img">
            <img ms-attr="{src:@val.thumb}" alt="">
        </div>
        <div class="artist-tp_txt">
            <p class="artist-tp_artistName">@{{ val.title }}</p>
        </div>
    </div>
</div>
脚本区：
var  all_pic= avalon.define({
   $id : 'all_pic',
   data : '',
   warn : ''
})
数据请求：
$.ajax({
   type: 'GET',
   url: "   ",
   data: {‘’},
   dataType: 'json',
   success: function (data) {
      if(data != ''){
        all_pic.data = data.all_pic;
     }else{
       all_pic.warn = '暂无内容，敬请期待'
     }
  }
})
chrome浏览器效果图：
![11](https://cloud.githubusercontent.com/assets/18543159/21706923/8b99622a-d405-11e6-9e9b-9819e323397e.png)
IE浏览器效果图：
![22](https://cloud.githubusercontent.com/assets/18543159/21706924/8bd6631e-d405-11e6-84ae-ede1d8a59f04.png)

**Comment by zyw976532735** [comment]
这个不知道是网速问题，还是GitHub问题，三张图片加载不到，稍等下

**Comment by zyw976532735** [comment]
html部分：
![html](https://cloud.githubusercontent.com/assets/18543159/21708377/c965dde2-d412-11e6-9af8-ded4e417b755.png)
脚本部分
![js](https://cloud.githubusercontent.com/assets/18543159/21708385/e712523a-d412-11e6-9e65-246094be546d.png)

**Comment by zyw976532735** [comment]
chrome效果：
![11](https://cloud.githubusercontent.com/assets/18543159/21708393/07a333c0-d413-11e6-8c48-22e988011448.png)
IE效果：
![22](https://cloud.githubusercontent.com/assets/18543159/21708397/13e94926-d413-11e6-8668-76d9ac4a8144.png)

**Comment by RubyLouvre** [comment]
不要截图，将代码简化一下，成一个简单的页面贴上来，ajax用setTimeout代替

**Comment by zyw976532735** [comment]
现在是简化了的代码了吧？不是很明白这位仁兄的意思

**Comment by MaxSherry** [comment]
是让你把页面简化成一个简单的测试页面,把文字代码贴出来,不要上图

**Comment by zyw976532735** [comment]
<html>
<head>
    <title>first example</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script type="text/javascript" src="/res/js/jquery.min.js"></script>
    <script type="text/javascript" src="/res/js/avalon2.2.js"></script>
</head>

<body ms-controller="test">
    <input ms-duplex="@name">
    <p>Hello,@{{name}}!</p>
    <ul>
        <li ms-for="@($index,el) in @datas">
            <a ms-attr="{href:@el.thumb}">@{{el.thumb}}</a>
            <span>@{{ el.id }}</span>
        </li>
    </ul>
</body>
</html>

<script>
    var vm = avalon.define({
        $id : 'test',
        name : "mr zhang",
        datas : ''
    })
    $(function(){
        var page=1;
        $.ajax({
            type: 'GET',
            url: '/test_avalon',
            dataType: 'json',
            success:function(data) {
                vm.datas=data;
            }
        });
    })
</script>

**Comment by zyw976532735** [comment]
上面这个测试代码，在chrome没有问题，但是在IE显示   Hello,{{name}}!    {{el.thumb}} {{ el.id }} 
报错 ：
SCRIPT438: 对象不支持“apply”属性或方法 
avalon2.2.js, 行574 字符5
SCRIPT438: 对象不支持“define”属性或方法 
zhangyuwei.ping99.com, 行24 字符5
 不知道这次描述清楚没有，希望大虾们还能帮忙解决一下，非常感谢！

**Comment by RubyLouvre** [comment]
不知你的data是什么啊，叫你用setTimeout代替 ajax

**Comment by zyw976532735** [comment]
非常感谢您的回答，还是没有尝试出来，不太理解setTimeout怎么代替ajax，我们的前端也没有理解。我在找找原因，非常感谢您的热心帮助。如果方便给我一个兼容IE的ajax  demo，再次感谢。

**Comment by RubyLouvre** [comment]
我知道了

 ```html
  <li ms-for="@($index,el) in @datas">
            <a ms-attr="{href:@el.thumb}">@{{el.thumb}}</a>
            <span>@{{ el.id }}</span>
        </li>

```
要改成
```html
     <li ms-for="@($index,el) in @datas">
            <a ms-attr="{href:el.thumb}">@{{el.thumb}}</a>
            <span>@{{ el.id }}</span>
        </li>
```
ms-attr指令的值 ，el前多了一个`@`

**Comment by crazyliuzc** [comment]
@zyw976532735 司徒大大的意思应该是问题不会出现在ajax取值上，而是获取数据后的显示；
为了方便调试要有个不需要ajax获取就能看到的数据源data，使用setTimeout来模拟赋值。

**Comment by DOLLOR** [comment]
1楼的第一个错误：
在IE8，**console**是特殊的对象，是**不允许**call/apply操作的。这跟本框架没有任何关系。
```javascript
console.log.call(console, [1,2,3]);//ie8报错
console.log.apply(console, [1,2,3]);//ie8报错
```
你只能老老实实地这样调用
```javascript
console.log([1,2,3]);
console.log(1,2,3);
```

**Comment by RubyLouvre** [comment]
你升到更高的版本啊

相关的地方已经改成：
```javascript
(function() {
    var welcomeIntro = ["%cavalon.js %c" + avalon.version + " %cin debug mode, %cmore...", "color: rgb(114, 157, 52); font-weight: normal;", "color: rgb(85, 85, 85); font-weight: normal;", "color: rgb(85, 85, 85); font-weight: normal;", "color: rgb(82, 140, 224); font-weight: normal; text-decoration: underline;"];
    var welcomeMessage = "You're running avalon in debug mode - messages will be printed to the console to help you fix problems and optimise your application.\n\n" +
        'To disable debug mode, add this line at the start of your app:\n\n  avalon.config({debug: false});\n\n' +
        'Debug mode also automatically shut down amicably when your app is minified.\n\n' +
        "Get help and support:\n  https://segmentfault.com/t/avalon\n  http://avalonjs.coding.me/\n  http://www.baidu-x.com/?q=avalonjs\n  http://www.avalon.org.cn/\n\nFound a bug? Raise an issue:\n  https://github.com/RubyLouvre/avalon/issues\n\n";
    if (typeof console === 'object') {
        var con = console
        var method = con.groupCollapsed || con.log
        Function.apply.call(method, con, welcomeIntro)
        con.log(welcomeMessage)
        if (method !== console.log) {
            con.groupEnd(welcomeIntro);
        }
    }
})()

```

**Comment by zyw976532735** [comment]
好，我升级版本，avalon社区人员活跃。没有想到

**Comment by zyw976532735** [comment]
更新到avalon2.24版本后，问题完美解决，兼容到IE6，感谢司徒大大以及其他大虾们的意见。
