### ISSUE TITLE
容器vm,组件vm及模板vm的不同步问题

### ISSUE THREAD

**Issue by 5ftech** [RubyLouvre/avalon#1904]
/*!
 built in 2017-1-6:14:21 version 2.2.4 by 司徒正美
 https://github.com/RubyLouvre/avalon/tree/2.2.4
 修正IE下 orderBy BUG
 更改下载Promise的提示
 修复avalon.modern 在Proxy 模式下使用ms-for 循环对象时出错的BUG
 修复effect内部传参 BUG
 重构ms-validate的绑定事件的机制
 */

样例代码在如下地方clone：
https://github.com/5ftech/avalontest.git

使用2.2.4版本的avalon.js文件，创建一个容器vm作为主要的数据vm.
然后创建一个组件，在defaults属性，将容器vm的值绑定到组件的属性。
然后使用ms-html,引用一个html模板，里面观察容器的vm.

3秒后，业务逻辑主动改变容器vm的数组长度。可以观察到组件、模板的数组长度是有变化。这时对任何一个数组的元素进行点击，其它数组的长度是会发生变化的，这一点是没有问题的。

问题出现在改变input框里面的值。一旦在任何一个input框修改过值，数组就变得不同步了。

所以问题应该是出在组件的vm跟容器vm的同步机制这里。

**Comment by RubyLouvre** [comment]
已经修正了
