### ISSUE TITLE
处理中文输入后的avalon版本 无法同步jq.datepicker日期选择器的数据

### ISSUE THREAD

**Issue by 502647092** [RubyLouvre/avalon#1905]
因为之前的JS在新的Chrome浏览器存在中文输入的BUG 然后项目就升级了avalon的版本 
之后发现jq的datepicker插件选择的 日期 无法同步
![image](https://cloud.githubusercontent.com/assets/10203793/21748491/63ebda60-d5c1-11e6-9c52-947d73242fa6.png)
对比新旧版本的事件绑定
旧版本
![image](https://cloud.githubusercontent.com/assets/10203793/21748497/893908a6-d5c1-11e6-95fe-5aac029f7793.png)
新版本
![image](https://cloud.githubusercontent.com/assets/10203793/21748500/92175770-d5c1-11e6-8973-b9eb2c68cd10.png)

我发现这个是新增的绑定
![image](https://cloud.githubusercontent.com/assets/10203793/21748515/c2860d66-d5c1-11e6-92cd-2968718eec76.png)
会不会是这个导致的原因

**Comment by RubyLouvre** [comment]
https://github.com/RubyLouvre/avalon/issues/1804 

https://github.com/RubyLouvre/avalon/issues/1735

**Comment by RubyLouvre** [comment]
以前解决过了，你升级一下，或自己根据上面的ISSUE改源码

**Comment by 502647092** [comment]
那个 我说的不是中文的问题
而是 用了中文问题修复之后的版本 导致了jq的datepicker插件 选择日期之后那个日期没有同步
我现在用的是1.5分支的最新版本

**Comment by RubyLouvre** [comment]
那你去掉 DOMAutoComplete看看

**Comment by 502647092** [comment]
My97DatePicker 日期选择是这个JS

**Comment by 502647092** [comment]
![image](https://cloud.githubusercontent.com/assets/10203793/21790357/918e19aa-d716-11e6-95d6-0578880a1680.png)
我把这里的input改成change就好了
问下会不会有什么问题

**Comment by 502647092** [comment]
再问个问题
![image](https://cloud.githubusercontent.com/assets/10203793/21790748/6153b5bc-d719-11e6-83b5-714b4c88835d.png)
以前的$remove改成啥了

**Comment by RubyLouvre** [comment]
直接用  array.remove(el)
