### ISSUE TITLE
请问老师，如何监听一个div宽度的变化？

### ISSUE THREAD

**Issue by xingwen1987** [RubyLouvre/avalon#1909]
老师您好，我这么写去监视这个div的宽度变化，但是不能够执行，请老师协助看看，谢谢！
我想监视通过jquery去改变的元素宽度值。
![image](https://cloud.githubusercontent.com/assets/15207100/21802198/b3101954-d75f-11e6-9c0d-d19b365b24b8.png)

**Comment by RubyLouvre** [comment]
不能啊。只有你手动对vm.cw 进行改动时， $watch回调才会作用。JQ改动或用户修改元素节点的大小，是不会触发$watch的。你对avalon理解错误了
