### ISSUE TITLE
想问一个HTML渲染的问题

### ISSUE THREAD

**Issue by xingwen1987** [RubyLouvre/avalon#1910]
![image](https://cloud.githubusercontent.com/assets/15207100/21882133/14e9e936-d8e4-11e6-9a69-427d9529160e.png)
老师您好，请问我应该如何在这种情况下输出 HTML 代码到页面上？
![image](https://cloud.githubusercontent.com/assets/15207100/21882257/a25a1de0-d8e4-11e6-9100-246cdb3edf0d.png)
还有一种需要按照顺序逐个按顺序输出，我查了很多资料，没有看到关于 {{ if ..... else..... }}的写法，请问老师，我应该怎么去处理？

**Comment by RubyLouvre** [comment]
ms-for指令啊 http://avalonjs.coding.me/

**Comment by xingwen1987** [comment]
老师您好，我第一张图，在底部红框的位置，就已经使用了 ms-for 指令，但是，按照我第一张图的输出结果，并不是 html 元素，请问老师，第一张图的问题，我应该怎么解决？

第二张图，问题在于，我不知道 ms-for 指令应该添加在哪个标签上，是td标签，还是tr标签？
如果在td标签，当 el.checkbox===true 时，需要输出第二张图红框中第二行代码，其它的时候，需要输出类似第一张图中第一行的代码，请问老师，我应该怎么写？

**Comment by xingwen1987** [comment]
在使用中，发现一个符号冲突，但不影响使用，如果在 Visual Studio 中，使用 .Net MVC 开发的话，@符号会合 MVC HTML 引擎 Razor 的关键字 @ 冲突，(●'◡'●)

**Comment by RubyLouvre** [comment]
看官网，官网已经提示用`##`代替了 http://avalonjs.coding.me/home.html

晕死，都没学，就乱用。
