### ISSUE TITLE
请问avalon2做html5 app现实么？对mmState和mmRouter的关系傻傻分不清……

### ISSUE THREAD

**Issue by cloudus** [RubyLouvre/avalon#1912]
一直在用avalon2，感觉非常好用。
请问avalon2做html5 app现实么？
对mmState和mmRouter的关系傻傻分不清……不知道哪一个才是最新的……应该用哪一个

**Comment by RubyLouvre** [comment]
avalon2没有mmState了。只有mmRouter

这里有例子

https://github.com/crazyliuzc/webpack-avalon2-SPA-seed.git

**Comment by cloudus** [comment]
请问具体文档有木有呢？比如返回的方法

**Comment by RubyLouvre** [comment]
https://github.com/RubyLouvre/mmRouter

**Comment by cloudus** [comment]
谢谢大大，不知道avalon.oniui什么时候有avalon2版本呢？现在抛弃了其他框架了，但是想找一个下拉刷新都很难……

**Comment by RubyLouvre** [comment]
http://weeksun23.github.io/AvalonBootstrap/index.html#overview
