### ISSUE TITLE
删除了vm后，对应的数据还没有清空……

### ISSUE THREAD

**Issue by cloudus** [RubyLouvre/avalon#1915]
我仿照这个例子做了一个小东西，但是纠结于其中的这个问题……

地址是：https://github.com/crazyliuzc/webpack-avalon2-SPA-seed

尚未解决的问题

使用avalon.modern.js或使用avalon.js路由都可以跳转，但跳转后前个路由页面数据没有统一清除，需要一一重置；

**Comment by cloudus** [comment]
大大，不知道svalon2有没有讨论群呢？

**Comment by crazyliuzc** [comment]
javascript罗浮宫4群，208841633 @cloudus

**Comment by RubyLouvre** [comment]
数据需要自己手动处理
