### ISSUE TITLE
2.2.4/avalon.min.js在win10的IE8(IE11模拟)下报class和for关键字错误

### ISSUE THREAD

**Issue by meepo3927** [RubyLouvre/avalon#1918]
如题，2.2.4压缩版本在IE8下报语法错误，因为把class和for当作关键字解析，
如：{class:"xx"} 或者 Foo.for = "xxx"  
测试环境：
--win10+IE11模拟IE8
--win7+IE9模拟IE8

在未压缩版JS中，因为使用双引号，所以没有此问题。
我尝试了使用混淆压缩，也避免了这个问题，

2.2.4混淆压缩后是79kb ， 是否考虑出一个混淆压缩版本，以方便IE8测试？

**Comment by RubyLouvre** [comment]
应该是压缩得不好吗，我官方本来就没有提供压缩版，自己压缩时注意一下

**Comment by meepo3927** [comment]
恩，是压缩的不好。

这里：https://cdnjs.com/libraries/avalon.js 
用的是：https://cdnjs.cloudflare.com/ajax/libs/avalon.js/2.2.4/avalon.min.js

不是官方的吗，看上去挺正式的？

**Comment by xiyiaoo** [comment]
加引号`{‘class’: xxx}`

**Comment by RubyLouvre** [comment]
那个当然不是官方的
