### ISSUE TITLE
官网教程上的小问题

### ISSUE THREAD

**Issue by suaidan** [RubyLouvre/avalon#1922]
在讲解ms-skip时，aaa:"xxxx"后面应该有 ，

**Comment by hefeng1208** [comment]
![image](https://cloud.githubusercontent.com/assets/24466340/23733620/f700a318-04b4-11e7-9204-74d288c940f6.png)按着教程上来的不好使？这是为什么呢
![image](https://cloud.githubusercontent.com/assets/24466340/23733649/1f612210-04b5-11e7-8d6b-3991f24a4f84.png)

**Comment by hefeng1208** [comment]
![image](https://cloud.githubusercontent.com/assets/24466340/23733685/46f48466-04b5-11e7-976a-1e18d1627eef.png)
按教程来的科室为什么不好使呢？求大神帮忙
![image](https://cloud.githubusercontent.com/assets/24466340/23733711/6526e244-04b5-11e7-8ea0-c8e925050b83.png)

**Comment by RubyLouvre** [comment]
ms-hover='[el === currentPage? "111": "22"]'

**Comment by hefeng1208** [comment]
嗯嗯， 已改过来了。多谢多谢
