### ISSUE TITLE
avalon2.2.4未压缩版在IE下，渲染不稳定

### ISSUE THREAD

**Issue by JuseChen** [RubyLouvre/avalon#1924]
司老师您好：
我现在在使用avalon的时候遇到一个问题，刷新页面时，有时候渲染成功，有时候不成功，显示{{el.name}}这个样子，在IE8下更频繁发生，很少渲染出来，查了提供的网站都没有找到答案

为了提高avalon的影响力,如果确定不是BUG,是你一些疑问与业务难题,请到**segementFault**上发贴子

当然有你有什么分享或avalon组件也建议直接在**segementFault**上发贴子

如果你确定是BUG,请按以下格式提问
================
- 在什么浏览器下,IE6,IE7,chrome51?

- 在avalon什么版本下? 你如果打开avalon源码,将最开头的那段注释贴上来!

- 提供一个可以运行的例子,比如像这人,请认真用``` code ```及与markdown语法编写ISSUE

https://github.com/RubyLouvre/avalon/issues/1665

- 想快点得到解决,请提供具体的操作步骤

- 想快点得到解决, 最好将控制如的错误信息也截图贴上来!

**Comment by JuseChen** [comment]
<div class="p-box" :controller="wrap">
        <div class="p-box-left">
            <ul>
                <li :for="(index, el) in @items" :class="[(@showCont==index?'hover':''),(el.filled?'filled':'')]" :click="!el.hover && @chooseClick(index)">{{el.name}}</li>
            </ul>
            <button>完成</button>
        </div>

        
    </div>


			let _this=this;
			let wrapOption={
				$id:'wrap',
				showCont:0,
				items:[{
					name:'基本信息',
					filled:true,
					type:'base'
				},{
					name:'教育背景',
					type:'edu'
				},{
					name:'获奖信息',
					type:'prize'
				},{
					name:'能力状况',
					type:'able'
				},{
					name:'社团经验',
					type:'assn'
				},{
					name:'工作经验',
					type:'work'
				},{
					name:'培训信息',
					type:'train'
				},{
					name:'家庭信息',
					type:'family'
				},{
					name:'特长爱好',
					type:'hobby'
				},{
					name:'自我评价',
					type:'selfeval'
				}],
				chooseClick(index){
					this.showCont=index;
				}
			}
			this.wrapVm=avalon.define(wrapOption);
这是代码

**Comment by LiPinghai** [comment]
解决了吗？遇到类似问题，chrome下一切正常。用ie8，页面不渲染，按f12打开ie控制台，再刷新页面，就正常渲染了。非常奇怪。avalon2.2.4版本

**Comment by RubyLouvre** [comment]
是不是有console.log

**Comment by LiPinghai** [comment]
是的，平时都知道，今天健忘了！谢谢司徒大大！

**Comment by JuseChen** [comment]
我的好像是因为本地的服务的原因，用grunt work的，用的seajs，就会渲染不稳定，可能和本地的什么逻辑冲突，到服务器上就好了。另外IE8不渲染，我的也没console，我就只能手动scan了一下解决的
