### ISSUE TITLE
<input ms-duplex="@a" /> 输入中文时，双向绑定失效

### ISSUE THREAD

**Issue by Jogiter** [RubyLouvre/avalon#1931]
代码来源：[avalon2学习教程01](https://segmentfault.com/a/1190000004882326)

```hml
<div ms-controller="test">
      <input ms-duplex="@a" />
     <p>{{@a}}</p>
</div>
```
在`chrome版本 56.0.2924.87`中
在`input`框中输入中文时，双向绑定失效，只有输入非中文时才会生效

**Comment by Jogiter** [comment]
补充，引用的js是`https://cdn.bootcss.com/avalon.js/2.0s/avalon.js`

**Comment by RubyLouvre** [comment]
升级，2.2.4

**Comment by RubyLouvre** [comment]
常见问题
