### ISSUE TITLE
avalon2.2.4 IE11文档模式为IE7下报错，winxp sp3 IE7下avalon无法运行

### ISSUE THREAD

**Issue by jation** [RubyLouvre/avalon#1933]
## 版本
avalon 2.2.4

### 浏览器与运行环境
windows10 IE11 文档模式IE7 下正则表达式报错
已按照`http://avalonjs.coding.me/questions.html`引入对应脚本

### 具体描述
控制台报错
```text
SCRIPT5019: 正则表达式中缺少 ']'
avalon2.js (1272,62)
```
其源码为
```javascript
array.$track.replace(/[^☥]+/g, function (k) {
```
此处改写`new RegExp('[^☥]+','g')`形式之后，就没有报错了。
同理的还有
```text
SCRIPT1012: 缺少 '/'
avalon2.js (4396,64)
```
源吗为
```javascript
var arr = val.$track.match(/[^☥]+/g) || [];
```
此处改写`new RegExp('[^☥]+','g')`后，就没有报错了。

### 浏览器与运行环境
winXP SP3 IE7

**Comment by jation** [comment]
问题2中，在IE11 文档模式为IE7的环境下，是可以alert出`typeof avalon == 'function'`为`true`的

**Comment by jation** [comment]
目前可以在winxp sp3 ie7运行了
把四个包分开而不是一起打包才能运行

**Comment by jation** [comment]
请关闭此issue，是我个人误操作所致，抱歉。

**Comment by RubyLouvre** [comment]
正则也有问题吗？

**Comment by jation** [comment]
正则没有问题
