### ISSUE TITLE
:visible不能用自定义的function了？

### ISSUE THREAD

**Issue by penweizgx** [RubyLouvre/avalon#1943]
之前的版本:visible可以直接使用自定义的function（非VM定义的方法）返回true/false 来显示和隐藏，现在切换到新版本后就不能用了，在VM中定义的function是可以正常切换的。
```
<div :click="@open('attendance', 'attendance/attendance_main_win.html')" class="aui-col-xs-3" :visible="hasMod('stuCheck')">
    <i class="icon iconfont icon-qiandao1" style="font-size: 30px; color: #F5A623;"></i>
    <div class="aui-grid-label">学生出勤</div>
</div>
```
控制台报的错误：
```
function anonymous(__vmodel__
/**/) {
return __vmodel__.hasMod('stuCheck' );
} exec error at avalon.tap.js : 217

```

**Comment by RubyLouvre** [comment]
hasMod('stuCheck')这个不是VM中的方法， VM的方法都要带@，否则不行

**Comment by penweizgx** [comment]
就是说:visible或:if里面的变量或方法必须是VM中定义的，不能用VM之外的了？


原始邮件
发件人:司徒正美notifications@github.com
收件人:RubyLouvre/avalonavalon@noreply.github.com
抄送:penweipnwazgx@163.com; Authorauthor@noreply.github.com
发送时间:2017年3月8日(周三) 00:47
主题:Re: [RubyLouvre/avalon] :visible不能用自定义的function了？ (#1943)


hasMod('stuCheck')这个不是VM中的方法， VM的方法都要带@，否则不行
