### ISSUE TITLE
在ie8下，操作数组很慢，如pushArray，clear等

### ISSUE THREAD

**Issue by gxt1103** [RubyLouvre/avalon#1945]
在ie8下，操作数组很慢，如pushArray，clear等，主要是把一个请求到的数组pushArray到当前空数组中

**Comment by RubyLouvre** [comment]
是不是数组太大啊

因为它同时要转换数组里面的元素，还有操作DOM。加之IE8下是VBScript。

你只能减少数组的长度，并且数组元素的结构弄简单些

**Comment by gxt1103** [comment]
数组长度不到20，是有点复杂
