### ISSUE TITLE
avalon使用webpack打包后IE提示缺少标识符、字符串或数字

### ISSUE THREAD

**Issue by twinklexp** [RubyLouvre/avalon#1948]
![avalon](https://cloud.githubusercontent.com/assets/17263696/23939626/954632fe-099c-11e7-806a-38a8c57dff81.png)
var propMap = { //不规则的属性名映射 'accept-charset': 'acceptCharset', 'char': 'ch', charoff: 'chOff', 'class': 'className', 'for': 'htmlFor', 'http-equiv': 'httpEquiv' };
avalon.js代码的1677行，在webpack打包后，json对象的key值得单引号被去掉了，导致class裸露在外面，因为class是js保留字，在ie8,ie7里面就报错了，请问这个怎么解决，可以怎么配置webpack,去掉这种压缩吗？
求解

**Comment by RubyLouvre** [comment]
es3ify-loader   http://www.aliued.com/?p=3240 建议看这个
