### ISSUE TITLE
ie8一下 for in 错误

### ISSUE THREAD

**Issue by juefeng** [RubyLouvre/avalon#1951]
built in 2017-3-8:0:37 version 2.2.4 by 司徒正美

    var test = avalon.define({
        $id: 'test',
        test:{a:1,b:2,c:3},
        _test:function() {
            var data = {};
            for(var i in this.test) {
                console.log(i);
                data[i] = this.test[i];
            }
        }
    });
    test._test();

会出现 “$vbthis” key ，报对象不支持此属性或方法

**Comment by RubyLouvre** [comment]
IE8下对VM for in循环必须使用hasOwnProperty。不要问我为什么，VBScript就是这么任性！
