### ISSUE TITLE
avalon2.2.4 ie8下filterBy过滤器无法传参

### ISSUE THREAD

**Issue by EdwinLam** [RubyLouvre/avalon#1954]
`ms-for="(index,el) in data | filterBy(@filterByKeyWord,@keyWord)`
ie8下使用filterBy会没有参数传过来，chrome正常，用的是2.2.4版本

ie8
![qq 20170322113237](https://cloud.githubusercontent.com/assets/1481470/24181065/aa4fa03e-0ef3-11e7-926c-67050e83a454.png)
chrome
![qq 20170322113327](https://cloud.githubusercontent.com/assets/1481470/24181080/b5ebe7ea-0ef3-11e7-9cf4-aef194dede2e.png)

**Comment by RubyLouvre** [comment]
data是不是漏了一个@

**Comment by EdwinLam** [comment]
加上也不行 好像valon变量去掉@也正常的样子 很多变量我都直接去掉了
好像ie8 filterBy(@filterByKeyWord,arg1,arg2,arg3)arg1到 arg3都传不到
```
ms-for="(index,el) in data | filterBy(@filterByKeyWord,@keyWord)

 filterByKeyWord:function(el,i,keyWord){
          console.log(arguments);
           return keyWord==""?true:el.name.indexOf(keyWord)!=-1;
        },
```

**Comment by EdwinLam** [comment]
@RubyLouvre 好像ie8运行这个avalon.slice([1,2,3,4],2)会返回空数组

**Comment by EdwinLam** [comment]
不知道是不是ie8 _slice.call(nodes, start, end) end参数不能传空undefined
