### ISSUE TITLE
attr指令不同步bug

### ISSUE THREAD

**Issue by wangzf-no1** [RubyLouvre/avalon#1955]
当用`for` `attr`指令相结合时候，出现`attr`同步失效现象

### avalon
built in 2017-3-8:0:37 version 2.2.4 by 司徒正美

### browser
360 **User-Agent**: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36

### code  [_online_](http://runjs.cn/code/ittqk7hi)

 ```html
	<body ms-controller="app">
		<ul ms-attr="@attr">
			<li ms-for="(k,v) in @attr">
				{{k}} :{{v}} <input ms-duplex="v" />
			</li>
		</ul>
	</body>
	<script>
		var app = avalon.define({
			$id: 'app',
			attr: {
				id: 'test'
			}
		})
	</script>
 ```

**Comment by RubyLouvre** [comment]
是的，这个是解决不了。除非你用了`el.xxx`，avalon只能改对象的属性，对这种临时生成的变成玩不转。我正在想办法，待我将React的源码看完后
