### ISSUE TITLE
avalon 2.2.4 没有把插卡元素保存在vm上

### ISSUE THREAD

**Issue by xxapp** [RubyLouvre/avalon#1957]
avalon 版本：2.2.4

根据这个 [issue](https://github.com/RubyLouvre/avalon/issues/1606)，插卡元素会以字符串的形式保存在 组件 vm 上，但是 2.2.4 版本好像不会保存插卡元素，见 demo http://codepen.io/xxapp/pen/NpBQGW

大概看了下源码中这个部分的实现，在 2.1版本中是在 vm 上保存了插卡元素的，2.2 好像去掉了这个东西，但是编写组件是很多地方需要用到这个。请司徒大神帮忙看下这个问题。

**Comment by RubyLouvre** [comment]
不放了。会容易引发内存泄漏

**Comment by xxapp** [comment]
如果我想利用插卡元素做一些判断，或者提取一些信息如何处理呢？

或者这样一个场景，一个dialog组件，不希望它的内容渲染在它实例化的地方，而是插入到 body 下的 一个 div 元素中， 怎么处理比较好呢？目前是利用组件 VM 上的 $render.root，通过 avalon.vdom 的 toHTML 来实现。不过这个方法好像是 avalon 框架内部使用，这么用是不是不太好。
