### ISSUE TITLE
vm.attr.$model  IE8不支持，版本2.25

### ISSUE THREAD

**Issue by fwyjack** [RubyLouvre/avalon#1961]
> var vm = avalon.define({
    $id: 'test',
    attr: [{
        a: 1
    }, {
        a: 2
    }, {
        a: 3
    }]
});
var vm_attr1 = vm.attr,
    vm_attr2 = vm.attr.$model;
avalon.log(vm_attr1);
avalon.log(vm_attr2);

谷歌浏览器，输出：
[IProxy, IProxy, IProxy, set: function, toJSON: function, contains: function, ensure: function, pushArray: function…]
 [Object, Object, Object]

IE8，输出：
日志: [object]
日志: undefined

**Comment by RubyLouvre** [comment]
```javascript
vm_attr2 = vm.attr.toJSON()
```

  http://avalonjs.coding.me/vm.html#监控数组
