### ISSUE TITLE
avalon在ajax回调上调用无效?

### ISSUE THREAD

**Issue by qgwolf** [RubyLouvre/avalon#1962]
这是我的代码

![m](https://cloud.githubusercontent.com/assets/25898117/24474183/5bbb17f8-14fe-11e7-88f5-d22f572a82f8.PNG)

运行结果
![m2](https://cloud.githubusercontent.com/assets/25898117/24474203/6f52a6a0-14fe-11e7-93c1-556094c3e81e.PNG)

想不明白这为什么这样?

注:我不是专业的前端,我不懂太懂AMD或者CMD的方式.

**Comment by RubyLouvre** [comment]
不是已经生效了吗
