### ISSUE TITLE
当html字符串中的文本节点含有一个“时，用ms-html填充html字符串时的报错

### ISSUE THREAD

**Issue by twinklexp** [RubyLouvre/avalon#1963]
我是用的是2.2.4版本
我需要填充的html字符串如下：
![avalon1](https://cloud.githubusercontent.com/assets/17263696/24484894/45bf8a1c-1533-11e7-9fa5-95af00919f2e.png)
然后通过avalon的clearString运算后
![avalon2](https://cloud.githubusercontent.com/assets/17263696/24484903/57a87aa4-1533-11e7-9463-febe61f64210.png)
原因是：readString方法在风格字符串的时候是以单引号和双引号分割的，然后我的html字符串的文本几点中正好有一个双引号
报错入下：
![avalon](https://cloud.githubusercontent.com/assets/17263696/24484953/93a783ce-1533-11e7-8bea-e721f05e0d26.png)

建议：在<>符号内做分割

**Comment by twinklexp** [comment]
目前修改成如下代码，但是应该有bug，往强大的博主尽快修复
`
 function readString(str) {
        var end,
            s = str.indexOf('<');

        var ret = [];
            s++;
        for (var i = s, n = str.length; i < n; i++) {
            var c = str.charAt(i);
            if (!end && c === '>') {
                s = str.indexOf('<', i + 1);
                if (s >= 0) {
                    s += 1;
                    i = s;
                }
            } else {
                if (!end) {
                    if (c === "'") {
                        end = "'";
                        s = i;
                    } else if (c === '"') {
                        end = '"';
                        s = i;
                    }
                } else {
                    if (c === end) {
                        ret.push(str.slice(s, i + 1));
                        end = false;
                    }
                }
            }
        }
        return ret;
    }
`

**Comment by RubyLouvre** [comment]
已经发布2.2.5了

**Comment by twinklexp** [comment]
新版也是有这个问题的啊

**Comment by RubyLouvre** [comment]
这个今天已经修复！
