### ISSUE TITLE
IE8下，2.2.5版本   ms-for 下DOM生成的特别慢

### ISSUE THREAD

**Issue by maybenana** [RubyLouvre/avalon#1964]
这个版本的
/*!
built in 2017-3-28:16:5 version 2.2.5 by 司徒正美
https://github.com/RubyLouvre/avalon/tree/2.2.4

修正IE下 orderBy BUG
更改下载Promise的提示
修复avalon.modern 在Proxy 模式下使用ms-for 循环对象时出错的BUG
修复effect内部传参 BUG
重构ms-validate的绑定事件的机制

*/

用循环
\<li ms-for = "el in @data" ms-text="el.a"\>\</li\>
这样在ie8下页面渲染很慢，这样一个简单的渲染在ie8下面要以秒为单位，最少都有1到2秒，数据多就更慢了。

**Comment by fwyjack** [comment]
这个不是IE8下慢，我在谷歌浏览器里面用2.2.5版本渲染800条数据，就要3-4秒钟。

**Comment by fwyjack** [comment]
后来没办法又只能用JS拼接，用ms-html输出到页面了。

**Comment by RubyLouvre** [comment]
用法不对啊，不能有多少条，就全部放到VM。 如果数组里面的元素是对象，会进行VM转换，超耗性能，你只能用多少转换多少 
```
var arrayFormBackEnd = [/*500条*/]
var vm = avalon.define({
   $id: 'ddd',
   arr: []

})
//深拷贝，防止影响原数组，只取前50条
vm.arr = avalon.mix(true, [], arrayFormBackEnd.slice(0,50)) 
```
