### ISSUE TITLE
组件树层级如果深一点，内部的中文和正则都会被转义

### ISSUE THREAD

**Issue by xxapp** [RubyLouvre/avalon#1974]
built in 2017-3-28:16:5 version 2.2.5 by 司徒正美

运行在 Windows7 Internet Explorer 8 环境

这是可运行的重新代码：

http://codepen.io/xxapp/pen/YZOXRW

组件结构是这样的：

``` js
  <xmp is="ms-container">
    <ms-container>
      <ms-container>
        <ms-form :widget="{ rules: { pattern: /\\d\d{0,2}/, message: '中文' } }"></ms-form>
      </ms-container>
    </ms-container>
  </xmp>
```

1. message 属性中文会被转为 unicode 编码显示 `\u4e2d\u6587`
2. pattern 属性会被多重转义，上面的正则会变成这样 `/\\\\\\\\d\\\\d{0,2}/`，这一条在 chrome 里面也会出现

**Comment by xxapp** [comment]
请司徒大神看下这个问题

**Comment by RubyLouvre** [comment]
你就不应该在那里面写正则

**Comment by xxapp** [comment]
那中文被转义改怎么办呢？

**Comment by RubyLouvre** [comment]
是个别浏览器吧

**Comment by xxapp** [comment]
@RubyLouvre 中文转义这个是只有 IE8 才有

**Comment by xxapp** [comment]
Internet Explorer Version: 8.0.7601.17514

**Comment by lit520** [comment]
同遇到该情况 。IE8 中文被转义，其他浏览器正常

**Comment by xxapp** [comment]
#2020 提出的解决办法可以解决我的问题。
