### ISSUE TITLE
IE8下 大量数据渲染 IE运行缓慢

### ISSUE THREAD

**Issue by lmiogit** [RubyLouvre/avalon#1979]
运行环境:IE8
avalon版本:2.2.5

由于需求关系 需要对大量数据进行渲染
向vm中更新数据等待渲染时耗时太多, 同等数据量 chrome只需要2-3秒 IE8下直接弹窗提示IE运行缓慢

更新数据方法 vm.data = [xx,xx,xx];

**Comment by lmiogit** [comment]
更新的数据中有少量 二维数组  html中也有少量 ms-for的嵌套

**Comment by RubyLouvre** [comment]
如果不存在交互，这里只能用JQ  实现

**Comment by lmiogit** [comment]
感谢回答   方案改掉了 放弃IE8
