### ISSUE TITLE
avalon2.2.5 循环指令失效

### ISSUE THREAD

**Issue by crazysavage** [RubyLouvre/avalon#1982]
</div>

**Comment by ryomi** [comment]
<select ms-duplex="@model.selected">
        <option ms-for="el in @model.arr" ms-attr="{value:el.value}">{{el.text}}</option>
</select>

avalon.js:2538 Uncaught 找不到界定符}}

**Comment by RubyLouvre** [comment]
升紴到2.2.6就好了
