### ISSUE TITLE
2.2.6 组件二维数组视图更新bug

### ISSUE THREAD

**Issue by wangzf-no1** [RubyLouvre/avalon#1983]
当更改组件数据的时候，一维数组可以刷新，二维数组更新失效

### avalon
built in 2017-4-25:15:9 version 2.2.6 by 司徒正美

### browser
360 **User-Agent**: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36

### code  [_online_](http://runjs.cn/code/39cawsjo)

 ```html
<body ms-controller="app">
	<wbr ms-widget="{is:'list',id:'w'}" />
</body>

<script>
	avalon.component('list', {
		template: '<table><tr :for="(r,tr) in data"><td :for="(d,td) in tr" ms-text="td"></td></tr></table>',
		defaults: {
			data: [
				[0, 1]
			]
		}
	})

	avalon.define({
		$id: 'app'
	})

	setTimeout(function() {
		avalon.vmodels.w.data.set(0, [3, 4])
	}, 1000)

	/*注意这里是二维数组*/
	setTimeout(function() {
		avalon.vmodels.w.data[0].set(0, 'ww')
	}, 2000)
</script>
 ```

**Comment by RubyLouvre** [comment]
```avalon.vmodels.w.data.set(0,["www"])``` ，改成这样吧

**Comment by wangzf-no1** [comment]
这个应该和架构有关系了, `controller` 与 `component`。
好吧，把精力放在有价值的地方吧
