### ISSUE TITLE
avalon 2.2.6 div为contenteditable的，双向绑定，输入的值存在问题

### ISSUE THREAD

**Issue by thomasyus** [RubyLouvre/avalon#1992]
所有浏览器下，当一个contenteditable的div，进行输入，使用ms-duplex的情况下，输入的焦点始终位于最左侧。

demo代码地址：
https://codepen.io/anon/pen/gWoXEB

**Comment by RubyLouvre** [comment]
没有办法的事，这个好像无法处理

**Comment by thomasyus** [comment]
好吧，只能用|change 过滤器来避免了
