### ISSUE TITLE
2.2.6之后的avalon版本配合路由使用，导致页面卡死，浏览器卡死

### ISSUE THREAD

**Issue by thomasyus** [RubyLouvre/avalon#2004]
使用这个SPA脚手架：
https://github.com/crazyliuzc/webpack-avalon2-SPA-seed

尚未解决的问题最后一条。

**Comment by crazyliuzc** [comment]
今天测试了一下，是“ built in 2017-4-19:16:1 version 2.2.5 by 司徒正美”以后的版本都有这个问题

**Comment by thomasyus** [comment]
其实我发现了是ms-view组件的xmp标签的问题，改成wbr或者template就没有这个问题了

**Comment by xxapp** [comment]
你是 xmp 里面套 xmp 了吧

**Comment by crazyliuzc** [comment]
@xxapp 
没有，可以看一下avalon代码里面的路由，这个是司徒大大写的
