### ISSUE TITLE
Select ms-duplex绑定默认值不生效

### ISSUE THREAD

**Issue by he644017879** [RubyLouvre/avalon#2009]
Select 元素绑定默认值无效，
生成的option 默认全部选中，不显示默认值的option
<select class="form-control" ms-duplex="floor">

<option selected="true">1</option>

<option selected="true">2</option>

<option selected="true">3</option>

<option selected="true">4</option>

<option selected="true">5</option>

<option selected="true">6</option>
</select>

**Comment by RubyLouvre** [comment]
没有例子啊

先看这里

http://avalonjs.coding.me/directives/ms-duplex.html

**Comment by he644017879** [comment]
我找到可能的原因了，我的那一部分html先用display:none隐藏了，然后通过弹窗的形式弹出来，发现这样的话avalon会有失效的情况，有时候会click失效，有时候会绑定失效

**Comment by chenlixin93** [comment]
你要检查一下有没有语法上的错误呀

**Comment by RubyLouvre** [comment]
这个已经 修复
