### ISSUE TITLE
测试显示avalon2比avalon1的性能差了上百倍！

### ISSUE THREAD

**Issue by hykjtt** [RubyLouvre/avalon#2024]
使用自己写的demo测试 2.2.8与1.4性能，chrome 22下，循环4000条数据，首次渲染的速度，2.2.8版本需要半分钟，1.4版本只需要2秒左右。当然再次更新的效率2.2.8速度更快。
    使用官方demo，2.2.8 chrome 22 首次渲染500行数据需要16秒，1.4只需要几十毫秒。更新速度2.2.8也比1.4慢接近10倍！
    不知道是我代码有问题还是avalon本身问题，虚拟dom的创建会影响首次渲染速度吗？

**Comment by RubyLouvre** [comment]
2.2.8没有完全用上虚拟DOM，因为双向绑定中有些东西虚拟DOM搞不定
