### ISSUE TITLE
一个页面多次scan无效

### ISSUE THREAD

**Issue by xcmonline** [RubyLouvre/avalon#2027]
avalon与treegrid进行配合使用，treegrid是采用动态加载的方式，当一个节点加载时会对字段进行 formatter 处理增加<a>标签，这时就需要进行数据加载 onLoadSuccess 成功后进行 avalon.scan(document.body)处理，第一次加载的节点能成功绑定 <a>标签的 ms-onclik相关事件，当第二次或更多次的节点展开 执行了 avalon.scan(document.body) 就无法绑定 ms-click事件了。
难道avalon.scan(document.body)只能在一个页面中执行一次吗？

**Comment by RubyLouvre** [comment]
不允许这样干啊
