### ISSUE TITLE
select 渲染和预期不一样。

### ISSUE THREAD

**Issue by doocal** [RubyLouvre/avalon#2029]
# 问题列表：
## 2、后赋值，默认选种不是：“苹果”，而是：“黄皮”，期望值：“苹果”

&lt;div id=&quot;fruit&quot; ms-controller=&quot;fruit&quot;&gt;
    &lt;h3&gt;文本域与下拉框的联动&lt;/h3&gt;
    &lt;input ms-duplex=&quot;@selected&quot;/&gt;
    &lt;select id=&quot;id1&quot; ms-duplex=&quot;@selected&quot;&gt;
        &lt;option ms-for=&quot;el in @options&quot; ms-attr=&quot;{value: el}&quot;&gt;
            {{el}}
        &lt;/option&gt;
    &lt;/select&gt;
&lt;/div&gt;

`<script>

    var initAvalon = function () {
        var vm = avalon.define({
            $id: "fruit",
            options: [],
            selected: ""
        });

        avalon.scan(document.getElementById("fruit"));

        return vm;
    }

    //延时
    setTimeout(function () {

        var vm = initAvalon();

        vm.options = ["苹果", "香蕉", "桃子", "雪梨", "葡萄", "哈蜜瓜", "橙子", "火龙果", "荔技", "黄皮"];
        //vm.options.push("苹果", "香蕉", "桃子", "雪梨", "葡萄", "哈蜜瓜", "橙子", "火龙果", "荔技", "黄皮");

    }, 2000)

</script>`

**Comment by RubyLouvre** [comment]
发现的确没有触发duplex的联动。。。

**Comment by RubyLouvre** [comment]
```
<!DOCTYPE html>
<html>

<head>
    <script src="./dist/avalon.js"></script>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
</head>


</body>
<div id="fruit" ms-controller="fruit">
    <h3>文本域与下拉框的联动</h3>
    <input ms-duplex="@selected" />
    <select id="id1" ms-duplex="@selected">
<option ms-for="el in @options" ms-attr="{value: el}">
{{el}}
</option>
</select>
</div>
<script>
   // var initAvalon = function () {
        var vm = avalon.define({
            $id: "fruit",
            options: [],
            selected: "桃子"
        });

  //      avalon.scan(document.getElementById("fruit"));

   //     return vm;
  //  }

    //延时
    setTimeout(function () {

      //  var vm = initAvalon();

        vm.options = ["苹果", "香蕉", "桃子", "雪梨", "葡萄", "哈蜜瓜", "橙子", "火龙果", "荔技", "黄皮"];
        //vm.options.push("苹果", "香蕉", "桃子", "雪梨", "葡萄", "哈蜜瓜", "橙子", "火龙果", "荔技", "黄皮");

    }, 2000)
</script>

</html>
```

**Comment by RubyLouvre** [comment]
已经修复了，从主干上拉那个吧。晚上我再publish，公司的网不好用

**Comment by chenwei0930** [comment]
@doocal 第一个问题，所有option都被设上selected的问题解决了吗，我 在chrome下也出现了。版本，2.2.10
