### ISSUE TITLE
IOS下，click事件不起作用

### ISSUE THREAD

**Issue by leecanzeng** [RubyLouvre/avalon#2032]
IOS下，在div上面绑定 ms-click="@fnClick"，不起作用，而PC、安卓却是正常的。
var vm = avalon.define({
 $id:'vm',
 fnClick:function(){ alert(123)}
})

**Comment by thomasyus** [comment]
请参考这个

**Comment by leecanzeng** [comment]
@thomasyus 
谢谢，ios的问题，已解决。
