### ISSUE TITLE
在render 的时候,IE7，8,9都很卡，有时直接卡死

### ISSUE THREAD

**Issue by zengAlex** [RubyLouvre/avalon#2038]
![image](https://user-images.githubusercontent.com/13888110/28701857-ae8b54de-738b-11e7-910b-fa3a7316eba2.png)
 
 
![image](https://user-images.githubusercontent.com/13888110/28701875-c8c02d34-738b-11e7-879d-0e01e179eda0.png)

初始化数据量60左右

**Comment by zengAlex** [comment]
在IE7 的时候页面加载完 ，$watch("onReady").也要等很久，如果能监听到就大概10秒左右渲染出来40条数据，如果一直监听不了，就会一直卡死

**Comment by RubyLouvre** [comment]
是不是数据很复杂，你使用一个定时器分派加入数组吧

```javascrit
 var id = setInterval(function () {
            //分派加入
            var list = data.splice(0, 15);

            if(list.length == 0){
               clearInterval(id)
            }else{
                var items = list.map(function(data){
                     //加工数据
                     return item
                })
                //datas应该为一个VM数组
                datas.pushArray(items)
            }

        }, 300)
```

**Comment by zengAlex** [comment]
好的，试试看，谢谢答复。

**Comment by zengAlex** [comment]
能不能兼容sea来加载的avalon？

**Comment by zengAlex** [comment]
![image](https://user-images.githubusercontent.com/13888110/28706885-cd59aeac-73a8-11e7-9d52-45ac639e3663.png)

然后就报了以下这个错误....
![image](https://user-images.githubusercontent.com/13888110/28706755-2b72b598-73a8-11e7-91d9-56d5dfa645fa.png)
