### ISSUE TITLE
avalon导致页面其他的js文件重复加载

### ISSUE THREAD

**Issue by liubin595338764** [RubyLouvre/avalon#2040]
# avalon导致页面其他的js文件重复加载，在ie8里面

- 浏览器：IE8
- 例子：
  这哥们用avalon.js写的页面，他的js文件也被加载了两次；
  [https://hmhao.github.io/avalon2-webpack2-spa/](https://hmhao.github.io/avalon2-webpack2-spa/)

- 详情：
在IE8里面，引入avalon.js之后，页面中其他的js文件都会加载两次，是不是因为代码只会执行一次，所以大家都忽略了？

请看下图，即使我的js文件里面什么都不写，依然会被加载两次。感觉这个是avalon.js导致的。

![ie8_avalon](https://user-images.githubusercontent.com/5274428/28760263-225593e0-75d8-11e7-8411-0bf0bb6f70cd.png)

![ie8_avalon2](https://user-images.githubusercontent.com/5274428/28760266-2a63fa0e-75d8-11e7-8a20-cb3fd67c9143.png)

**Comment by hmhao** [comment]
@liubin595338764 由于avalon在dom ready时scan整个body
```
    avalon.ready(function () {
        avalon.scan && avalon.scan(document$1.body);
    });
```
然后会执行dumpTree，将body上的元素都移除（包括script），后面又重新加回去（导致ie8-会重新加载一遍script）
```
function dumpTree(elem) {
        var firstChild;
        while (firstChild = elem.firstChild) {
            if (firstChild.nodeType === 1) {
                dumpTree(firstChild);
            }
            elem.removeChild(firstChild);
        }
    }
```
