### ISSUE TITLE
arthur.js有语法错误

### ISSUE THREAD

**Issue by jasstion** [RubyLouvre/avalon#2055]
我克隆此项目后，使用dist目录下的arthur.js文件时发生了语法错误。看一下代码，好像是observeArray函数缺少结束的大括号，手动添加后发出现createAccessor is not defined。

**Comment by RubyLouvre** [comment]
那个试验性项目

**Comment by jasstion** [comment]
意思是不能用吗？

**Comment by jasstion** [comment]
我不想用太多的功能，就想实现一个双向绑定，想用这个，有什么办法吗？
