### ISSUE TITLE
后端渲染报错，不知原因，请指正，谢谢

### ISSUE THREAD

**Issue by 79229788** [RubyLouvre/avalon#2067]
npm install avalon2@2.2.9  

```
const avalon = require('avalon2/dist/avalon');
const serveRender = require('avalon2/src/renders/serverRender');
const obj = serveRender(avalon.define({
  $id: 'test',
  aaa: 'hello'
}), '<div :controller="test">{{ @aaa }}</div>');
console.log(obj);
```

在node上运行一个简单的例子，请问为啥要报错呢？是不是哪里不对呢，求指正（项目需要兼容ie8，所以没有选用avalon.modern类版本）

--------------------------------
我没有用最新版本，而选择了你们的示例版本，可以渲染了（可能是新版本没有兼容服务端渲染），但是你们的示例版本又发现一个新问题，使用组件则报错
```
  require('../assets/library/avalon-server/avalon2.2');
  const serveRender = require('../assets/library/avalon-server/serverRender2.2');
  avalon.component('ms-view',{
    template:'<div class="view"></div>',
    defaults: {

    }
  });
  const obj = serveRender(avalon.define({
    $id: 'test',
    aaa: 'hello'
  }), `<div :controller="test"><ms-view></ms-view></div>`);

  console.log(obj.html);

```
TypeError: Cannot read property 'firstChild' of undefined

-------------------------------------------------------------------
发现源码中这里有问题，elem是一个undefined，我只好判断了一下加了一个return然后就可以渲染了。也不知道具体是做啥的，也没有时间研究你们的源码，只有在继续试探下了。希望你们能修复下，感谢！因为这套框架很不错的
![image](https://user-images.githubusercontent.com/11959954/33232291-7dea72d0-d23e-11e7-8e8f-eb21805c952f.png)

**Comment by RubyLouvre** [comment]
修好了
