### ISSUE TITLE
如何避免avalon扫描整个document.body?

### ISSUE THREAD

**Issue by foresightyj** [RubyLouvre/avalon#2073]
问这个问题是因为avalon.js (2.2.4) 的源码有这么一行，
    
    avalon.ready(function () {
        avalon.scan && avalon.scan(document$1.body);
    });

自动扫描中整个document.body. 我发现在我的项目中，因为avalon默认扫描整个document.body导致很多其他的库出现问题，譬如说kindEditor。 我试验过，一个kindeditor的最简单引用，就因为引入avalon.js，而且什么都不做，就出现富文本框中文字消失，而且无法点击focus文本框。

在我的项目中，只有dom上面某个id里面的元素才需要使用avalon，有没有办法不修改avalon.js的源码的情况下，阻止avalon.js自动扫描整个document.body?

**Comment by RubyLouvre** [comment]
你可以在kindeditor所在的元素加上一个ms-skip

**Comment by foresightyj** [comment]
好吧。多谢。
