### ISSUE TITLE
IE8下报错“已终止操作”和对象不支持“createViewModel”属性或方法

### ISSUE THREAD

**Issue by LongHuGu** [RubyLouvre/avalon#2088]
SCRIPT16388: 已中止操作
avalon.js (4795,13)

SCRIPT438: 对象不支持“createViewModel”属性或方法
avalon.js (4424,9)

**Comment by RubyLouvre** [comment]
应该是没有定义就使用吧

**Comment by z-gg-lab** [comment]
这个问题怎么解决呢？
