### ISSUE TITLE
绑定select标签中的option的selected这个属性，绑定不了

### ISSUE THREAD

**Issue by xdlover** [RubyLouvre/avalon#2089]
\<select>
             \<option ms-attr="{selected:@selected}">启用</option>
              \<option>禁用</option>
 \</select>

**Comment by lujiaxing** [comment]
用 ms-duplex.
`<select ms-duplex="@selected">`
`  <option value="1">Option 1</option>`
`  <option value="2">Option 2</option>`
`  <option value="3">Option 3</option>`
`  <option>Disabled</option>`
`</select>`

**Comment by RubyLouvre** [comment]
用ms-selected
