### ISSUE TITLE
avalon导致inline-block元素水平间距消失

### ISSUE THREAD

**Issue by chenwei0930** [RubyLouvre/avalon#2094]
- 在什么浏览器下：chrome 69，IE11

- 在avalon什么版本下? 2.2.10

> <html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Document</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://cdn.rawgit.com/RubyLouvre/avalon/master/dist/avalon.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </head>
    <body>
        <a class="btn btn-default" href="#" role="button">Link</a>
        <button class="btn btn-default" type="submit">Button</button>
        <input class="btn btn-default" type="button" value="Input">
        <input class="btn btn-default" type="submit" value="Submit">
    </body>
</html>

页面不引入avalon.js，则按钮间距正常

**Comment by Lihuanghe** [comment]
这是因为button间的换行（或者空白字符引起的）,avalon会去掉这些所以影响浏览器的默认行为了。

**Comment by chenwei0930** [comment]
@Lihuanghe 试了一下，果然是这样的。有办法可以解决吗？这个行为挺不好理解

**Comment by Lihuanghe** [comment]
把换行去掉，或者写成这样：
```
   <span class="line-box style-color1"></span><!--  
--><span class="line-box style-color2"></span>
```

**Comment by chenwei0930** [comment]
@Lihuanghe 试了一下，chrome下还是不行，算了，用margin做一下吧。十分感谢

**Comment by RubyLouvre** [comment]
用CSS 处理吧
