### ISSUE TITLE
jquery post提交vm的问题

### ISSUE THREAD

**Issue by linsmod** [RubyLouvre/avalon#273]
你好，我在使用jq $.post方法提交数据的时候把avalon模型中的属性作为data的参数，不过我发现在该方法直接使用参数会因为附加了avalon的对象而造成堆栈溢出（应该是post方法枚举子对象造成的），当我使用vm.$model的时候虽然没有溢出了，但是因为avalon重写了hasOwnPropertiy方法造成判断失败，因为这时vm.$model.$model的值为undefined，
我在hasOwnProperty中加一了个判断可以解决此问题。在1045行，原：

``` javascript
vmodel.hasOwnProperty = function (name) {
 return false;
 }
```

改为：

``` javascript
vmodel.hasOwnProperty = function (name) {
 if (vmodel.$model)
 return name in vmodel.$model
 return false;
```

（由于网络原因github没有加载样式表，抱歉没有格式化代码）

**Comment by liudianpeng** [comment]
如何用json进行数据传输，ajax

**Comment by kissstudio** [comment]
楼上你是来挖坟的吗？

**Comment by liudianpeng** [comment]
@kissstudio 不是啊，我就是想问一下，怎么用

**Comment by kissstudio** [comment]
框架一般都有文档的，看文档就会了。不用谢，也不要在这里回了。
