### ISSUE TITLE
希望提供较复杂单页面的指导及示例

### ISSUE THREAD

**Issue by bigqiang** [RubyLouvre/avalon#406]
已经尝试使用avalonJS做项目近两个月了。初期写得很顺，随着页面逻辑越来越复杂，遇到诸多困境。

单页面中包含大量事件处理，基本可将一个单页面切分在一个js文件和一个html模板文件来实现。随着逻辑的复杂加剧，代码越来越冗长，js中要维护跟踪的页面状态变量就越来越多，维护也越来越麻烦，就需要进一步的功能代码切分。曾尝试使用 ms-include 对模板进行分隔，不过js只能放在一起，如果js代码与 ms-include 分离的模板放到一起进行维护感觉比较好。但能力所限，不知道如何操作。

曾按 mmRouter中的路由示例代码进行模板与js细分维护，我的理解上需要制订好详细的路由策略。但在复杂单页面下要定义的路由就太多了，适合某些状态变化性相关性较强的定义成一个路由来单独维护，但当这个路由下的状态变化量越来越多时就不太方便在其下继续进行路由划分了。

为了维护增多的状态变量，通常我会将要跟踪的状态变量封装在一个对象内，导致一个对象结构会颇为复杂。鉴于Avalon最佳实践中提到对象复杂层数不要超过四层，这样会拆分成多个对象。而且目前这样的对象内还不好封装进函数。这都造成了在单页面下维护的困难。

我想我对avalonJS的理解还差很多，希望能有一个针对复杂页面下开发的一个指导实践的说明及示例，目的在于让开发的代码与模板间关联的逻辑更清楚更易于维护。

**Comment by rengeng1986** [comment]
对VM进行模块化js处理，VM里独立负责对模版的载入、扫描、绑定处理。（有点像是一个独立的UI组件）
这样会不会清晰点

**Comment by ascoders** [comment]
mmState模块化版本解决你的问题

http://www.avalon.org.cn/art/5516af0236803509f1000003
