### ISSUE TITLE
ms-duplex 双向绑定能否考虑指定默认值

### ISSUE THREAD

**Issue by lovefishs** [RubyLouvre/avalon#448]
#### 遇到的问题

信息编辑页面，模板后台组装，有以下代码：

```
<form ms-controller="edit">
  <input type="text" ms-duplex="id" name="id" value="$!{id}">
</form>
```

有js：

```
avalon.define('edit', function(vm) {
  vm.id = 0; // 这个地方给 id 赋值为 0 ，会同步到页面，但是其实页面的默认值应该是 $!{id} (假设是 10)
});
```

这样的问题虽然可以把 页面模板 与 数据都分开来解决，但是在实际需求中，并不是只有这样一种场景。不是所有的数据都能在 js 中来定义的或者是通过ajax来获取的，某些值想放在 模板 上通过 value 属性指定。  
是否可以有一个这样的功能，使用占位符 `$value` 来告诉 `avalon` 这个属性的值来自于 dom 的 value 属性：

```
avalon.define('edit', function(vm) {
  vm.id = $value; // 这里的 $value 其实就是 $!{id} 的值
});
```

希望能够考虑一下这样的需求，或者给出其他解决的方法。

**Comment by niltor** [comment]
和楼主一样的问题,入门教程有相关的说明么?
在删除或修改的过程中,经常有<input type="hidden" value={$id}>这样的写法,就是为了取得id然后提交给服务器.它并不需要改变.

**Comment by RubyLouvre** [comment]
http://avalonjs.github.io/ 

看新官网
