### ISSUE TITLE
我所知道的MVVM框架

### ISSUE THREAD

**Issue by RubyLouvre** [RubyLouvre/avalon#480]
avalon
http://avalonjs.github.io/ (使用Object.defineProperties、 VBScript、 Object.observe，纯事件驱动，兼容IE6，DOM的兼容性处理可与jQuery媲美，体积少)

早期的四大MVVM框架，都有大公司引衔

https://angularjs.org/ （google出品，思想来自flex，IoC， 脏检测，自定义标签，受限于绑定数量，一般不能超过2000个，入门容易上手难，大量避不开的概念）

http://emberjs.com/ （ 原来是苹果公司的内部项目，使用Object.defineProperties， 体型庞大，MVVM只是其很少一部分）

http://knockoutjs.com/ （微软出品，使用函数偷龙转凤，最短编辑长度算法实现DOM的同步，兼容IE6，实现高超，但源码极其难读）

http://dev.windows.com/en-us/develop/winjs （微软出品，使用Object.defineProperties，一个庞大的UI库）

这一两年冒出来的

http://facebook.github.io/react/ （facebook出品，带来virtual dom的革命性概念，受限于视图的规模）

http://rivetsjs.com/  （API比较精致）

http://gwendall.github.io/way/  (使用定时间同步)

http://vuejs.org/ （使用Object.defineProperties实现同步，实现精致，但功能薄弱）

https://github.com/regularjs/regular   
（最近一个月才冒出来的新东西，网易推出的JS框架，自称AngularJS与React的合体）

http://jsblocks.com/ jsblocks  knockout的改进版,性能奇高,但无法处理复杂数据

https://github.com/vilic/drop 在知乎又刚刚听说一个，用TypeScript写的http://www.zhihu.com/question/26938742/answer/34629835

knot.js  http://www.cnblogs.com/knotjs/p/Knotjs_release_announcement.html

**Comment by xuzicn** [comment]
React算MVVM吗，好像什么都没提供

**Comment by RubyLouvre** [comment]
react不算

**Comment by andyforever** [comment]
Kendo也支持MVVM了

**Comment by RubyLouvre** [comment]
<div class="WB_text" node-type="feed_list_reason">感觉 React Native 一发布，其它类似的产品就都坐不住了，最近好多跟风发布：Ionic 1.0.0 <a class="W_btn_b btn_22px W_btn_cardlink" title="https://github.com/driftyco/ionic/releases/tag/v1.0.0" href="http://t.cn/R2wUDC4" target="_blank" mt="url" action-type="feed_list_url"><i class="W_ficon ficon_cd_link S_ficon">O</i><i class="W_vline S_line1"></i><em class="W_autocut S_link1">网页链接</em></a> NativeScript 1.0.0 <a class="W_btn_b btn_22px W_btn_cardlink" title="https://github.com/NativeScript/NativeScript/releases/tag/v1.0.0" href="http://t.cn/R2wUDCG" target="_blank" mt="url" action-type="feed_list_url"><i class="W_ficon ficon_cd_link S_ficon">O</i><i class="W_vline S_line1"></i><em class="W_autocut S_link1">网页链接</em></a> Reapp <a class="W_btn_b btn_22px W_btn_cardlink" title="https://reapp.io/" href="http://t.cn/R2wUDCb" target="_blank" mt="url" action-type="feed_list_url"><i class="W_ficon ficon_cd_link S_ficon">O</i><i class="W_vline S_line1"></i><em class="W_autocut S_link1">网页链接</em></a> Tabris.js <a class="W_btn_b btn_22px W_btn_cardlink" title="https://tabrisjs.com/" href="http://t.cn/R2wUDCq" target="_blank" mt="url" action-type="feed_list_url"><i class="W_ficon ficon_cd_link S_ficon">O</i><i class="W_vline S_line1"></i><em class="W_autocut S_link1">网页链接</em></a> deku <a class="W_btn_b btn_22px W_btn_cardlink" title="https://github.com/segmentio/deku" href="http://t.cn/RAFQeKu" target="_blank" mt="url" action-type="feed_list_url"><i class="W_ficon ficon_cd_link S_ficon">O</i><i class="W_vline S_line1"></i><em class="W_autocut S_link1">网页链接</em></a> 看不过来了</div>

**Comment by mylyh** [comment]
恩 有点道理

**Comment by simphp** [comment]
vue现在很热

**Comment by cocody** [comment]
习惯用VUE.JS再用avalon，感觉就像从现代文明回到石器时代一般，:(

**Comment by IndexXuan** [comment]
@cocody  不过可见用vue.js的用户并没有小右那种干净，风度与自信，哎。

**Comment by codering** [comment]
@cocody 一直想用vue，可恨的IE8〜！！

**Comment by cdll** [comment]
现在感觉加载器在项目中的主导作用比框架重要，我觉得这是vue比avalon略欠缺的一个关键～

**Comment by IndexXuan** [comment]
@cdll 感觉恰恰相反，现代web前端更看重“静态编译”以及更多的预处理。而amd如果不打包或者处理不当，看起来按需加载，实则处处加载，体验不流畅。很多模板样式甚至js模块应该在上线前就静态编译好，成为内聚的一块，而非线上拉取组合执行。个人愚见～

**Comment by cdll** [comment]
@IndexXuan 也不无道理～
