### ISSUE TITLE
性能问题

### ISSUE THREAD

**Issue by weeksun23** [RubyLouvre/avalon#496]
基于avalon，我写了一个tree ui组件，但发现性能不堪入目，加载1000个节点需要5秒多，加载10000个节点就直接挂掉了
代码链接：<a href='https://github.com/weeksun23/YuriUI/blob/master/src/tree/avalon.tree.js'>tree.js</a>,
刚学avalon不久，希望大家多多指教。

**Comment by zinda2000** [comment]
@weeksun23 兄：
树数据加载的性能问题，有什么新的进展吗？
你说的加载时间，是否除开获取数据的时间。
miniui有例子，加载10000个，秒内，链接： http://www.miniui.com/BigTest/10000-tree.html 但其树数据是js生成的

**Comment by weeksun23** [comment]
@zinda2000 当然除开了获取数据的时间，miniui那种是分层加载的，就是第一次只加载第一层的节点，点击它加载其下一层的，这样只要每层节点不多的话加载10W个节点也不会卡拉。。。。。。我最后也是采取分层加载的方式。
