### ISSUE TITLE
关于UC浏览器安卓版本：手势导致avalon swipe事件失效的问题

### ISSUE THREAD

**Issue by EdwonLim** [RubyLouvre/avalon#523]
较新版本的UC浏览器支持手势操作 —— “左右滑屏前进后退”。
当用户手指向左右滑动时，会被浏览器认为是手势操作，而直接触发`touchcancel`事件。
图示的红色部分，其实是前进的页面。
如果没有前进页面，**灰边会被用户认为是页面的一个弹性效果**，而此时`avalon`并没有触发`swipe`事件，所以**很像** `avalon`的一个`bug`。
用户关闭手势功能后，`avalon`正常。

![图示](http://ww3.sinaimg.cn/bmiddle/71c50075jw1elc38ebmt7j20s01am76l.jpg)

好了，现在问题来了：这个“bug”是否要修？

浏览器触发`touchcancel`事件了，告知开发者`touch`事件被取消了，是浏览器行为，需要框架来修正吗？

测试版本 UC浏览器安卓9.9版本，IOS测试没此问题（没有`touchcancel`）。

PS：有可能别的支持手势的浏览器也有此问题。

**Comment by dannyliou** [comment]
UC，移动端的IE6啊，没事加什么手势
