### ISSUE TITLE
avalon 内存泄露严重

### ISSUE THREAD

**Issue by qinerg** [RubyLouvre/avalon#590]
我们有个视频聊天室项目曾计划深度使用avalon技术实现。
例：http://www.xiu8.com/912278
其中用户列表、聊天区使用 avalon 数组绑定，节省了大量代码。但灰度发布后发现在IE浏览器下内存泄露非常严重，基本5分钟以后就挂了，实在没有办法熬了一个通宵，又将代码切换回 jquery 。
目前线上部分只有小部分基于 avalon ，不敢大规模使用了。
希望官方能够重视此问题，谢谢！

**Comment by RubyLouvre** [comment]
已经修好了
