### ISSUE TITLE
ms-attr-*不能使用过滤器？

### ISSUE THREAD

**Issue by zaaack** [RubyLouvre/avalon#604]
这是我的html代码

``` html
<input name='publish_time' ms-attr-value='{{now | date("yyyy-MM-dd HH:mm:ss")}}'/>
```

这是我的js

``` js
var now =new Date();
avalon.define('article_edit',function (vm) {
    vm.columnList=columnList;
    vm.stateList=userStateList;
    vm.now=now;
});
```

但是input的value并没有输出期望的格式化的时间，
经过测试，`<div>{{now | date("yyyy-MM-dd HH:mm:ss")}}</div>`可以显示，`<input name='publish_time' ms-attr-value='{{now}}'/>`也可以显示，是不是节点属性不能用过滤器啊？希望能增加这个功能就好了。。

**Comment by andycao** [comment]
@zaaack ms-text, ms-html, {{prop}}, {{prop}} 这写标签可以使用filter，我觉得他不支持更多的是因为双向绑定。可能avalon就是想要轻量，所以吧功能都给拆开了，一些东西就舍弃掉了
