### ISSUE TITLE
如何在数据改变后，且视图同步后执行回调？

### ISSUE THREAD

**Issue by ascoders** [RubyLouvre/avalon#635]
我想用$('.timeage').timeago()功能，但必须得dom加载完毕使用才有效。
1. $watch的时候dom没加载完毕，执行那段代码并没有产生效果。
2. data-include-rendered可以达成目的，但在没有新页面被渲染，只改变变量的视图同步没有监听作用。

想问下这种情况怎么做比较妥当？

**Comment by RubyLouvre** [comment]
data-include-rendered就是干这事的

**Comment by RubyLouvre** [comment]
https://github.com/RubyLouvre/avalon/blob/master/src/15%20directive/attr.js

**Comment by ascoders** [comment]
这仅仅在模版渲染完毕才触发，但模版不变，只更新变量触发的改变就无法捕捉了

**Comment by RubyLouvre** [comment]
那没有办法
模板必须变化，你偷偷一个空白进去

**Comment by RubyLouvre** [comment]
ms-repeat也有回调

**Comment by ascoders** [comment]
能否给个文档，如何回调？

**Comment by RubyLouvre** [comment]
乱炖上有一整个系列的教程 http://www.html-js.com/article/2239

**Comment by ascoders** [comment]
找到了与repeat配合使用的data-with-sorted，不过它是在渲染前执行的，有没有在渲染后执行的回调？

**Comment by RubyLouvre** [comment]
data-repeat-rendered, data-each-rendered, data-with-rendered

**Comment by ascoders** [comment]
````
<div ms-repeat='a' data-repeat-rendered='aRendered'>
    <div ms-repeat='el.b'></div>
</div>
````
这个是等最外层全部渲染完再回调吧，如果只为了全部渲染完回调，是否最外层加个监听即可？

**Comment by ascoders** [comment]
index.html
````
<!DOCTYPE html>
<html lang='zh-cn'>
<meta charset='utf-8'>

<div ms-controller='model'>
  <div ms-include='router'></div>
  <button ms-click='changeRouter'>click</button>
</div>

<textarea id='loading' style='display:none;'>
  loading..
</textarea>

<textarea id='list' style='display:none;'>
  <div ms-each-el='data' data-each-rendered='render'></div>
</textarea>

<script src='avalon.js'></script>
<script src='index.js'></script>
````
index.js
````
var model = avalon.define({
  $id: 'model',
  router: '',
  data: [],
  render: function(type) {
    console.log(type);
  },
  changeRouter: function() {
    model.router = 'loading';
    model.data = [];
    model.router = 'list';
  }
});
````
不知道这样切换模板对不对，第一次点击type=add，第二次点击type=clear add index add
已经确认是loading影响了list的render回调，去除` model.router = 'loading';`这段代码，第二次点击变为type = clear add index

**Comment by ascoders** [comment]
如果把`model.data = [];`这段代码删除，每次点击都是一个add，这样才正常。
但每次切换模板时给监听的变量重新复制的需求很普遍，似乎这块有问题。
