### ISSUE TITLE
vm里的变量再追加变量不可以吗？

### ISSUE THREAD

**Issue by alayii** [RubyLouvre/avalon#640]
比如有一个

>  vm.articles = {
        data: [id: xxx, views: xxx]
} 

这样的变量，然后点击一个checkbox时，遍历数组，向里面添加一个 selected 变量，使其变成 true, 即 vm.articles 变成 
> {data: [id: xxx, views: xxx, selected: true]}

在视图里，其他的 checkbox 的 ms-duplex-checked 都绑定在 selected 上，selected 添加且变成 true 后，checkbox 并未选中。

因为我这里的要实现的全选功能是要全选一个 table 里的东西，不太清楚跟 checkboxlist 如何合作，上面的方法是否有问题呢？或者要如何实现这一功能

ps: 新官网现在无法使用了

**Comment by RubyLouvre** [comment]
重新赋一个新对象就行了

**Comment by alayii** [comment]
data 里的数据是遍历出来的，如果新建一个对象，貌似无法把它跟 data 里的每一项联系起来，data 是 API 里的数据。

**Comment by RubyLouvre** [comment]
写个简单的HTML贴上来

**Comment by alayii** [comment]
> <table>
  <thead>
    <tr>
      <td>
        <input type="checkbox" ms-duplex-checked="selectAll"
ms-click="checkAll" />
      </td>
    </tr>
    <tr>
        <td>test</td>
    </tr>
  </thead>
  <tbody>
    <tr ms-repeat-article="articles.data">
      <td>
        <input type="checkbox" ms-duplex-checked="article.selected" />
      </td>
      <td>{{ article.title }}</td>
    </tr>
  </tbody>
</table>

点击上面的 checkbox 时，修改每个 article 里的 selected.

**Comment by RubyLouvre** [comment]
没有JS啊

**Comment by alayii** [comment]
vm.checkAll = function (articles) {
  articles.data.forEach(function (article) {
    article.selected = true;
  });
};

selected 本来是没有的。

**Comment by RubyLouvre** [comment]
selected必须要有啊

**Comment by RubyLouvre** [comment]
http://www.html-js.com/article/Avalon-tutorial-12-data-linkage

**Comment by RubyLouvre** [comment]
看一下这个

**Comment by alayii** [comment]
那即是说无法追加咯

**Comment by RubyLouvre** [comment]
认真看readme的例子，里面就有实现全选非全选的例子
