### ISSUE TITLE
组件库smartgrid Api getSelected 貌似有个bug

### ISSUE THREAD

**Issue by cxyguopong** [RubyLouvre/avalon#642]
当我全选之后，这时返回的getSelected 是列表 中的所有数据。如果这时我点击 每一行的checkbox取消选择，这时再进行全选，此时虽然呈现的全部勾选，但我调用getSelected 时，之前单独取消勾选的行并未选中。
在源码中进行全选操作的方法_selectAll有一行“vmodel._enabledData = vmodel._allEnabledData;”。将vmodel._enabledData指向了vmodel._allEnabledData的引用 ，在单独取消一条勾选时会直接将vmodel._enabledData对应的数据移除“avalon.Array.remove(enabledData, rowData);”。
我通过avalon.mix( vmodel._enabledData , vmodel._allEnabledData );不知道这样修改有没有问题

**Comment by RubyLouvre** [comment]
请到oniui里面提问

**Comment by cxyguopong** [comment]
好的
