### ISSUE TITLE
新版本的实例教学，有些代码已经过时且无法运行了。

### ISSUE THREAD

**Issue by 178220709** [RubyLouvre/avalon#644]
比如class1.html
里面的avalon.scanCallback 已经被移出avalon.js，当作插件放在其他地方了。
然后这里直接报空值异常。
希望能将教学实例重新整理下 或者用版本迭代的时候，连这个一起迭代。
这样比较方便我等新手的学习。
感谢司徒大神及其他维护人员。

**Comment by RubyLouvre** [comment]
已经修了,你也可以提pull request
