### ISSUE TITLE
应用中的一些问题

### ISSUE THREAD

**Issue by lonelyclick** [RubyLouvre/avalon#648]
1、avalon是不是可以完全的不操作DOM呢，如果在有必要的时候操作DOM，不是还要用选择器选择么？是否有angular那样的指令的东西呢？目前在用bootstrap，但是一些JS组件还是需要操作DOM的，很矛盾。
2、目前应用avalon时发现插件比较稀少（去哪网的UI组件不是很大众化），以后是否有打算将avalon与bootstrap做集成呢，觉得这样会加速avalon的发展呀？
3、看文档的时候，觉得语言很不平实，也不太详细，大部分情况下都是一掠而过。

**Comment by RubyLouvre** [comment]
1 可以操作DOM啊，没有说不可以—— 但你有了手机了，还用得着每次想与父母说话时都要乘火车对父母面对面说吗？！
2 指令， 就是avalon的绑定， 比如ng-if是angular的一个指令，对应就是avalon的ms-if。angular可以使用<dialog xxx=yyy kkk=ddd></dialog> 这样的自定义元素实现弹出层， avalon也则用<div ms-widget="dialog"></div>实现弹出层。
    就是名字不一样，外观有点不一样
   像我们中国人说不行，英国人说no, 日本人说鸦灭爹……
   angular的指令有四种形式， 标签， mg-*属性， 类名， 注释
   avalon暂时只有两种形式， 文本节点{{}} ， ms-*属性
3 这个你自己搞

**Comment by lonelyclick** [comment]
我觉得这是个生态环境的问题，用angularjs，能直接拿来写好的bootstrap指令来用，要是用这个，就说所有的插件不都得重写（特别是对于大点的后台系统），这不就要累哭了。如果我在avalon里面再操作DOM，就违背了它的思想了（大部分的插件都要依赖jquery，avalon很明显有一部分代码跟jquery的功能一直，造成重复）。并且，如果是展示性的门户网站，用MVVM的框架的必要性很小，场景大部分都是单页面的网站系统，要用的控件比较多，所以强烈建议适配bootstrap啊，个人觉得对这个框架以后的发展肯定大好。（再度脑补，如果要适配bootstrap等UI控件，就少不了jquery，是不是可以把avalon里面跟jquery功能差不多的代码提取出来），见识有限，司徒大大多多包涵哈。

**Comment by RubyLouvre** [comment]
你快去适配，这责任就交给你了

**Comment by lonelyclick** [comment]
好吧好吧，结贴吧。
