### ISSUE TITLE
ms-each中的ms-include模板经常容易输出空节点

### ISSUE THREAD

**Issue by xw332** [RubyLouvre/avalon#660]
暂时没有必现的测试例子，但是在实际项目中出现频率非常高，ms-include里的模板经常在外层的数组赋值时随机性地只输出空节点
初步感觉和数组渲染速度有关，如果节点比较少没问题，数据多了或结构复杂了，就直接不输出。

另外一个问题是，现在从体验上ms-each的机制改了，数组赋值之后，跟着的语句取不到ms-each节点的子节点了，以前很多写好的页面，现在都要加setTimeout才能取到里面的东西，对以前的项目都有影响。

这现在是两个问题，也可能是一个，反正现在都是在用setTimeout临时解决，求修正

**Comment by RubyLouvre** [comment]
没有例子，无法修正啊，都不明白你说什么

**Comment by xw332** [comment]
简单的说就是ms-include属性完全失效，不是必现，但是希望能从执行原理上给点解释

**Comment by RubyLouvre** [comment]
必须提供例子啊, 就像你看病, 什么都不给看, 治过毛

你的ms-each与ms-include是写在同一元素上,还是 ms-include放在ms-each的内部元素中,是ms-include-src绑定还是ms-include……要不怎么查啊

**Comment by RubyLouvre** [comment]
你之前没出问题的是什么版本啊

**Comment by xw332** [comment]
之前用的是11月的版本，换了新版，问题有点多多点乱，都来不及整理，各种奇葩问题：
ms-include是在ms-each里面的，是两个标签
有时候双向绑定的input，在内容删掉一部分的时候提交表单，会直接提交空的字段值
有时会报$special出错，以前都没有的
现在反正都还在整理

**Comment by xw332** [comment]
双向绑定的input以前是修改后会把光标后面的文字都删掉，这个问题，更新了早上的版本已经好了，其他还没好

**Comment by RubyLouvre** [comment]
https://github.com/ecomfe/esl/blob/master/src/esl.js

**Comment by xw332** [comment]
ms-include模板的问题终于搞清楚了，最后发现居然是同时加载了两个版本的avalon.js
模板的问题确实是存在的，必现的测试用例都写好了，但是只出现在旧的1.0的版本里的，最新版本貌似没这个问题，怪不得测了几个小时，时好时坏，推翻了多少方案，心都碎了。。
不过其他那些出现的问题，还是要继续调，明天还得继续燃烧生命
