### ISSUE TITLE
avalon.mobile版本router报错

### ISSUE THREAD

**Issue by tower1229** [RubyLouvre/avalon#686]
router自带示例（https://github.com/RubyLouvre/mmRouter/blob/master/index2.html ）换上avalon.mobile.js后无法运行，报错："warning: contacts状态对象的【】视图对象 必须存在template, templateUrl, templateProvider中的一个"。
    自己的项目也有这个问题，换回全兼容版本就好了，这是为什么？不同版本有不同的路由写法吗？

**Comment by RubyLouvre** [comment]
什么浏览器啊，这点信息无法调试，必须提供页面与HTML

**Comment by RubyLouvre** [comment]
这个以后要提到mmRouter中，不要提在这里
