### ISSUE TITLE
刚开始使用avalon，ms-include-src的问题

### ISSUE THREAD

**Issue by tairuichen** [RubyLouvre/avalon#687]
使用 ms-include-src="include/{{url}}"  通过 ms-click="setUrl('aaa.html')" 和 ms-click="setUrl('bbb.html')" 来切换include-src的路径 include/aaa.html和 include/bbb.html  都有各自的
var vm = avalon.define({
        $id: "aaa",
        list: {}
    });

但这个时候来回切换aaa和bbb页面的话 console会报warning: aaa 已经存在于avalon.vmodels中  这个该如何处理 谢谢

**Comment by RubyLouvre** [comment]
```javascript
var vm = avalon.vmodels.xxx || avalon.define({})
```
