### ISSUE TITLE
数组清空内部对象报错

### ISSUE THREAD

**Issue by wf123537200** [RubyLouvre/avalon#690]
在实现一个较复杂的业务时出现如下问题：
对于这样一个数组，看到里面有值
![image](https://cloud.githubusercontent.com/assets/5130528/5972140/aa2161fa-a88f-11e4-9b63-6c882455250e.png)
但是在执行clear(splice)以后就报错
![image](https://cloud.githubusercontent.com/assets/5130528/5972155/e022f4da-a88f-11e4-9782-5cde8a8bdac8.png)
但是数组清空了，结果也正确，就是抛出了一个错误
![image](https://cloud.githubusercontent.com/assets/5130528/5972200/7ec51348-a890-11e4-94d9-69df17a183bb.png)
现在问题在于，报错阻止了后面代码执行，麻烦正美帮忙看看，谢谢！

**Comment by RubyLouvre** [comment]
没有测试页面，看过毛，又不是站在你背后
