### ISSUE TITLE
希望在 avalonjs.github.io 提供一个示例专区

### ISSUE THREAD

**Issue by ufologist** [RubyLouvre/avalon#691]
首先觉得教程还是蛮多的, 都分了很多篇章来讲,  但可能第一印象就是想先看看跑起来的示例.

因此建议将 https://github.com/RubyLouvre/avalon/tree/master/examples 都发布到 avalonjs.github.io, 并希望提供更多的运用到avalon的真实项目作为参考.

**Comment by RubyLouvre** [comment]
以后再说
