### ISSUE TITLE
什么时候用scan

### ISSUE THREAD

**Issue by likyh** [RubyLouvre/avalon#694]
scan(el?, vmodels?)	★★★扫描DOM树，抽取绑定(el默认为DOM,vmodels默认为空数组
avalon默认在domReady时，从body开始扫描一次，以后自己动态添加了新内容，需要自己手动scan。
如果你的VM是定义在某个回调里面，如require回调，也需要自己手动扫描

api里面是这样介绍的，只是我很想知道到底该怎么样“自己动态添加新内容".

**Comment by RubyLouvre** [comment]
你用jquery 的append方法，或原生的document.createElement方法，添加新节点或文档碎片后， 或对某一元素使用innerHTML后
