### ISSUE TITLE
ms-if 无法代码防御

### ISSUE THREAD

**Issue by 554943871** [RubyLouvre/avalon#696]
<pre><code>
    avalon.ready(function(){
            avalon.define("view",function(vm){
                 vm.tt=[['test']]//2纬数组
                 vm.clear=function(){
                     vm.tt.clear()
                 }
            })
            avalon.scan()
    })
   
   &lt;body ms-controller="view"&gt;
       &lt;button ms-click="clear"&gt;clear&lt;/button&gt;
         &lt;div ms-if="tt.size()>0"&gt;
                      &lt;div&gt;{{tt[0][0]}}&lt;/div&gt;
           &lt;/div&gt;
    &lt;/body&gt;
</code></pre>
执行clear会报错，因为 = 号赋值也会先clear，赋值也无发成功。
ms-if不是用来做代码防御的吗？扫描到ms-if为false,下边的绑定就应该不再执行了才对，当数组只有一层的时候不会暴露这个问题一旦多层了就有问题

**Comment by RubyLouvre** [comment]
没有错，自己好好理解一下

**Comment by 554943871** [comment]
<pre><code>
        avalon.ready(function(){
            avalon.define("view",function(vm){
                 vm.tt=[{name:'test'}]
                 vm.clear=function(){
                     vm.tt.clear()
                 }
            })
            avalon.scan()
        })
&lt;body ms-controller="view"&gt;
     &lt;button ms-click="clear"&gt;clear&lt;/button&gt;
     &lt;div ms-if="tt.size()&gt;0"&gt;
         &lt;div ms-repeat="tt"&gt;{{el.name}}&lt;/div&gt;//1处
         {{tt[0].name}}//2处
     &lt;/div&gt;
&lt;/body&gt;
&lt;/html&gt;
</code></pre>
我试了下1处的可以防御住，2处的报错了。看来数组类型的只能放在放在ms-repeat里取出来，ms-if才能起作用
