### ISSUE TITLE
测试出错

### ISSUE THREAD

**Issue by mrzzcn** [RubyLouvre/avalon#699]
info index.js:137 | Specified labors automatically by server < chrome >
warn index.js:137 | Proxy response error { orderId: '96mTssyPj6Nv2RnyAAAD',
  path: '/avalon/src/jQuery/jquery-1.11.2.js',
  status: 404 }

测试代码没有更新？

**Comment by RubyLouvre** [comment]
那里看到index.js？

**Comment by RubyLouvre** [comment]
你应该看examples目录下的例子， 其他的都是我临时的例子，方便我回到家继续测试
