### ISSUE TITLE
一个数组同步的问题，请教

### ISSUE THREAD

**Issue by jscsscom** [RubyLouvre/avalon#700]
http://5.wmei.sinaapp.com/Public/View/My/Default/DistributionShopPackage/test.html 
初始时修改数量时，上面的商品总价会同步更改。
但是当执行添加，这时再修改原来的商品数量，会同步变化，修改新增加的就不会同步更改了。
不能这样用吗

**Comment by RubyLouvre** [comment]
你这样写没法调试
