### ISSUE TITLE
数组监控无效

### ISSUE THREAD

**Issue by Billskate** [RubyLouvre/avalon#701]
avalon版本：1.391 build in 2015.2.4 
chrome版本：40.0.2214.93

测试代码：
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title></title>
  <script src="avalon.js"></script>
  <script>
    var vmodel = avalon.define('test', function (vm) {
      vm.testArr1 = [];
      vm.testArr2 = [1];
      vm.testArr3 = null;

      vm.$watch('testArr1', function () {
        console.log('testArr1 success');
      });
      vm.$watch('testArr2', function () {
        console.log('testArr2 success');
      });
      vm.$watch('testArr3', function () {
        console.log('testArr3 success');
      });
    });
    vmodel.testArr1 = [1];
    vmodel.testArr2.pushArray([1]);
    vmodel.testArr3 = [1];
  </script>
</head>
<body ms-controller="test">
  {{testArr1.size()}}
  {{testArr2.size()}}
  {{testArr3.size()}}
</body>
</html>
```

测试结果：测试1失败，测试2失败，测试3成功

**Comment by 178220709** [comment]
怎么我这里是
testArr1 success 
testArr3 success 
测试1也成功了啊。。。

监控数组 应该监控长度lenght 。

vmodel.testArr1 = [1];
vmodel.testArr3 = [1];
是重新赋值，所以 console.log('testArr1 success'); 可以生效
 vmodel.testArr2.pushArray([1]);无效

页面显示：1 2 {{testArr3.size()}}
是因为你监控的是vm的testArr3 而不是vm.testArr3.size()
只有在 avalon.define的时候添加的东西才会被双向绑定。

**Comment by 178220709** [comment]
上面解释的简单了，真实情况应该更复杂，
 vm.testArr1 = [];
vm.testArr3 = null;
这两个的区别，一个是定义的object类型，一个是值类型。
avalon.define里面做vm初始化的时候，对它们的处理估计会有不通，
这个是我的猜测，具体情况得去看源码了。

当然无论如何，楼主这种写法都是不推荐的，vm定义的属性，不应该有类型改变，是array就一直是array

**Comment by Billskate** [comment]
@178220709 

testArr1的测试，在没更新之前，也是成功的，就是因为今天更新了才发现的问题，可以先更新再试一下。

之前我的用法就是
```javascript
vm.testArr1 = [];
vmodel.testArr1 = [1];
```

只是今天更新发现问题，做了个测试，多写了两种情况。

**Comment by RubyLouvre** [comment]
$watch只能监听 简单数据类型
