### ISSUE TITLE
head 中为何要添加 <avalon> 标签？

### ISSUE THREAD

**Issue by zTree** [RubyLouvre/avalon#706]
近期升级到最新版本的 avalon 后， 发现 avalon 会在 head 内添加 avalon标签， 专门用于保存 页面中 ms-if 隐藏的模板。

但因为 avalon标签不是标准的 head 内的标准标签名称， 导致 用 avalon 生成的页面，如果被保存 html 后， 用浏览器打开， avalon 标签以及head内的所有标签都会被自动解析到 body 内，从而将其内部的 html 内容全部显示出来，导致页面显示异常。

不知道 avalon 是处于哪种目的必须要做这种处理？ 是否可以将此 非标准的标签移除， 直接使用类似于 document.createElement('div') 的方式创建一个 DOM 树之外的 element 对象保存 需要隐藏的模板？？ 

希望能够尽快解决此问题， 谢谢。

**Comment by RubyLouvre** [comment]
导致 用 avalon 生成的页面，如果被保存 html 后， 用浏览器打开， avalon 标签都会被自动解析到 body 内，从而将其内部的 html 内容全部显示出来，导致页面显示异常?

什么浏览器什么版本下,我测试了这么多浏览器都没有事

**Comment by zTree** [comment]
ie11/chrome / firfox  都会这样的。

我直接使用 if3.html 这个demo， 让 modal.aaa = false 后， 的html 源码  生成 html 页面后， 所有的浏览器打开都会能看到 X 以及 那个 333333 
~~~
<!DOCTYPE html>
<html>
<head>
    <avalon ms-skip="1">X
        <style id="avalonStyle">.avalonHide {
            display: none !important
        }</style>
        <div id="remove">
            <div>333333</div>
        </div>
    </avalon>
    <title>ms-if</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <style>
        #aaa {
            width: 200px;
            height: 200px;
            background: red;
            display: none;
        }
    </style>
</head>
<body ryt14262="1">

<div id="testDiv" avalonctrl="test">
    asdfasdfsdf
</div>

</body>
</html>
~~~

**Comment by zTree** [comment]
原始运行中的页面是没有问题， 问题是将页面的 html 保存后， 重新打开这个保存后的 html 就会出问题

**Comment by RubyLouvre** [comment]
你为什么要保存呢

**Comment by RubyLouvre** [comment]
你应该还是用原始页面,不要使用渲染后的页面

**Comment by RubyLouvre** [comment]
已修
