### ISSUE TITLE
mmRouter-master中的Example有问题

### ISSUE THREAD

**Issue by 398218995** [RubyLouvre/avalon#709]
我是angular那边转战过来的。。
测试了一下发现mmRouter-master中的Example   index2.html
这个页面用avalon.js就可以运行   用avalon.mobile.js或avalon.modern.js他就会报

contacts状态对象的【】视图对象 必须存在template, templateUrl, templateProvider中的一个
我的avalon.js、avalon.mobile.js、avalon.modern.js
都是1.391版本

**Comment by gogoyqj** [comment]
[http://ued.qunar.com/oniui/mmRouter/avalon.mmRouter.doc.html](http://ued.qunar.com/oniui/mmRouter/avalon.mmRouter.doc.html) 用这里的
