### ISSUE TITLE
作用域嵌套问题

### ISSUE THREAD

**Issue by lankeren** [RubyLouvre/avalon#710]
<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>demo</title>
        <script src="avalon.js"></script>
    </head>
    <body>
        <div ms-controller="outer">
            <div ms-controller="inner" ms-if="step==1">
                $ {{ amount }}
            </div>
        </div>
        <script>
            avalon.define({
                $id: 'outer',
                step: 1
            }) 
            avalon.scan()
            avalon.define({
                $id: 'inner',
                amount: 100
            })
            avalon.scan()
        </script>
    </body>
    </html>

{{amount}}没有输出

**Comment by zymiboxpay** [comment]
你可以把第一个 avalon.scan() 去掉
也可以把两个 avalon.scan() 都去掉

问题的原因在于第一个 avalon.scan() 执行之后，会把所有 ms-controller 属性去掉，你之后定义的 inner 就没有用了。

**Comment by RubyLouvre** [comment]
去掉所有avalon.scan
