### ISSUE TITLE
vbs

### ISSUE THREAD

**Issue by rachardking** [RubyLouvre/avalon#711]
"\tPublic Property Get [" + name + "]", //getter
"\tOn Error Resume Next", //必须优先使用set语句,否则它会误将数组当字符串返回
"\t\tSet[" + name + "] = [__proxy__](Me,[__data__],\"" + name + "\")",
 "\tIf Err.Number <> 0 Then",
"\t\t[" + name + "] = [__proxy__](Me,[__data__],\"" + name + "\")",
 "\tEnd If",
"\tOn Error Goto 0",
"\tEnd Property"

如果get返回的对象不是个object，将再执行一边下面的
这样acconser连续执行2遍，会不会有问题

**Comment by RubyLouvre** [comment]
没有问题,都用了快2年了
