### ISSUE TITLE
avalon如何做权限控制?

### ISSUE THREAD

**Issue by arccode** [RubyLouvre/avalon#712]
请问如何使用avalon做页面按钮粒度级别的权限控制.

**Comment by Lihuanghe** [comment]
avalon用来解决view跟model的同步问题，权限，角色是业务层面的问题，这是两个维度。
如果用mvvm的框架来实现功能权限，菜单权限，应该首先在viewmodel层面去思考model如何设计，之后再考虑view层面如何展示和交互。
首先用户登陆后，获得用户所有的菜单权限(能操作哪些菜单)，及该用户的默认首页。这个信息要记录在model里。
然后在查询用户在某一个菜单对应page的功能权限（按扭），也保存在model里。
最后考虑怎么根据model里权限信息渲染view.
=========下面是后端服务器代码。
如果权限非常复杂的话，后端要用user ,usergroup,role,menupage,operator,operatorgroup来管理权限。最细粒度的权限是每一个用户--某一个page--某一个按钮。

**Comment by RubyLouvre** [comment]
使用ms-if让不够权限的人看到相应区域；后端也应该不输出相关数据，防止被人反编译出来

**Comment by arccode** [comment]
谢谢两位的回答, 以下做法是否可行
1. 用户访问某个页面, 后端返回用户拥有的权限集合
2. 前端根据ms-if判断当前按钮(或菜单)的权限是否在集合中, 在-> 显示, 不再-> 不显示
3. 用户点击后, 后台再进行一次权限合法性校验

**Comment by Lihuanghe** [comment]
可行，合法性校验要抽象出来一层做为filter来实现a或者springmvc的interceptor。不要对业务有侵入。
