### ISSUE TITLE
package.json里面的version错误，导致npm install 不能成功

### ISSUE THREAD

**Issue by yaoduren123** [RubyLouvre/avalon#714]
npm ERR! install Couldn't read dependencies
npm ERR! Error: Invalid version: "1.391"
npm ERR!     at Object.module.exports.fixVersionField (d:\Application\nodejs\nod
e_modules\npm\node_modules\read-package-json\node_modules\normalize-package-data
\lib\fixer.js:183:13)
npm ERR!     at d:\Application\nodejs\node_modules\npm\node_modules\read-package
-json\node_modules\normalize-package-data\lib\normalize.js:30:38
npm ERR!     at Array.forEach (native)
npm ERR!     at normalize (d:\Application\nodejs\node_modules\npm\node_modules\r
ead-package-json\node_modules\normalize-package-data\lib\normalize.js:29:15)
npm ERR!     at final (d:\Application\nodejs\node_modules\npm\node_modules\read-
package-json\read-json.js:342:33)
npm ERR!     at then (d:\Application\nodejs\node_modules\npm\node_modules\read-p
ackage-json\read-json.js:126:33)
npm ERR!     at d:\Application\nodejs\node_modules\npm\node_modules\read-package
-json\read-json.js:331:40
npm ERR!     at evalmachine.<anonymous>:272:14
npm ERR!     at d:\Application\nodejs\node_modules\npm\node_modules\graceful-fs\
graceful-fs.js:102:5
npm ERR!     at Object.oncomplete (evalmachine.<anonymous>:108:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "d:\\Application\\nodejs\\node.exe" "d:\\Application\\nodejs\\n
ode_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd e:\git\github\avalon
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     e:\git\github\avalon\npm-debug.log
npm ERR! not ok code 0

**Comment by RubyLouvre** [comment]
版本已经升级了,再不行就不要用package.json
