### ISSUE TITLE
$watch 监控 object 类型属性有问题

### ISSUE THREAD

**Issue by darklx** [RubyLouvre/avalon#725]
$watch 监控 primitiveType 可以，但是如果是 {}、[] 类型则有问题，直接上代码：

var testVM = avalon.define("test", function (vm) {
    vm.primitiveType = 1;
    vm.objectType1 = {};
    vm.objectType2 = [];
    vm.objectType3 = null;
});

setTimeout(function () {
    testVM.primitiveType = 2;
    testVM.objectType1 = { xx: "hehe" };
    testVM.objectType2 = [{}, {}];
    testVM.objectType3 = [{}, {}];
}, 1000);

testVM.$watch("primitiveType", function (newValue) {
    console.log("primitiveType $watch:" + newValue);
});

testVM.$watch("objectType1", function (newValue) {
    console.log("objectType1 $watch:" + newValue);
});

testVM.$watch("objectType2", function (newValue) {
    console.log("objectType2 $watch:" + newValue);
});

testVM.$watch("objectType3", function (newValue) {
    console.log("objectType3 $watch:" + newValue);
});

实际输出：
primitiveType $watch:2
objectType3 $watch:[object Object],[object Object]

这个问题已影响到了复杂情况下多个 View Model 之间相互通信了！希望老大能解决下 :-)

版本：avalon.js 1.391 build in 2015.1.27

**Comment by RubyLouvre** [comment]
$watch只能监听简单数据类型，官网有写

**Comment by darklx** [comment]
实际上是 object 类型也需要监听啊！

**Comment by darklx** [comment]
两个模块进行相互通信的时候，$watch 是很好的机制，但是不能 $watch 不能监听 object 的变化，限制很大。

**Comment by darklx** [comment]
一个实际的场景：
用户登录后，通知中心 ajax 异步拉取通知数据，我希望监听通知数据的变化，产生变化后做一些额外的处理。由于 $watch 不能监听，便只能在 ajax 成功回调函数里面做处理了。

**Comment by RubyLouvre** [comment]
不能，这性能太差了

**Comment by Lihuanghe** [comment]
跨vm的通信是模块化之后必定遇到的问题。系统复杂度上升以后中，模块越来越多，模块间的依赖就会越来越重，越来越复杂。但并不是无解的。
1： 可以参考后端系统经验，如java的模块化原则： 如定义模块接口，依赖于接口，不依赖实现等。
对于js语言来说，主要关注vm的外部接口，把vm的职责划分清晰，规划vm的api，vm间尽量只依赖公开的api，而不依赖vm内部的model或者私有方法（vm间只有api调用，不要修改其它vm的内部model）。
2： @darklx 所说的，ajax调用成功后，除修改自身vm的数据外，可能还要更新vm_A ,vm_C 。可以直接调用vm_A.api().方法。如果需要异步调用，可以借助js的事件机制，或者消息系统来实现。
3：如果vm太多，几百个，甚至上千的话，vm间的依赖可能就理不清了。这时可以使用js的一些Ioc方案，通过配置来管理依赖。虽然js的Ioc一些开源实现功能还比较弱，但随着js的职责越来越重，对Ioc的使用越来越多，相信功能也会越来越完善。
4： 以上的前提，都是在vm职责清晰的情况下。这需要对业务进行分析，在设计vm时不能随手开写，vm需要规划。

**Comment by Lihuanghe** [comment]
我觉得watch监控简单类型已经够用了。如果你要watch 一些复杂的model，那说明你的vm已经开始臃肿了，vm的职责需要再进行细分了。

**Comment by darklx** [comment]
@RubyLouvre 
性能差？不是特别理解，我以为只是需要保存对象的修改前和修改后的状态呀～

**Comment by RubyLouvre** [comment]
那你自己用$fire, $watch搞定
