### ISSUE TITLE
avalon.js怎么改造成seajs的cmd模块?

### ISSUE THREAD

**Issue by unknown-coder** [RubyLouvre/avalon#732]
用的avalon版本是2015.01.29  1.391版本.
目前我改成这样.
```javascript
define("avalon", [], function (require, exports, module) {
    //源码...
    
    avalon.config({
        loader: false
    })
    
    //源码...
})
```
但是页面上
![image](https://cloud.githubusercontent.com/assets/9328734/6476982/10263d5e-c258-11e4-8795-23ec19c1b3ec.png)
还是把avalon暴露到window去了。
![image](https://cloud.githubusercontent.com/assets/9328734/6476992/210babea-c258-11e4-8763-fb765cc38133.png)

按照 #313 加上
```javascript
if (typeof module !== "undefined" && typeof module !== "function") {
        module.exports = avalon;
} else if (typeof define === "function") {
        define(avalon);
}
```
问题依旧。

应该怎么改？ @RubyLouvre

**Comment by RubyLouvre** [comment]
https://github.com/RubyLouvre/avalon/issues/313  看这个

**Comment by unknown-coder** [comment]
还是一样会暴露到window @RubyLouvre

**Comment by RubyLouvre** [comment]
是的，必须会暴露

**Comment by RubyLouvre** [comment]
这个用AMD，可以用init方法可以动态删除它；你看一下cmd有没有 类似的方法
