### ISSUE TITLE
哪一个service实现比较好

### ISSUE THREAD

**Issue by xxapp** [RubyLouvre/avalon#735]
![qq 20150304150830](https://cloud.githubusercontent.com/assets/5040144/6479450/64bb7f50-c280-11e4-8196-e5b9acc3fcc6.png)
![qq 20150304150844](https://cloud.githubusercontent.com/assets/5040144/6479449/64aeb680-c280-11e4-8786-d45a2084347c.png)

**Comment by RubyLouvre** [comment]
这是什么加载器？AMD还是CMD？

**Comment by xxapp** [comment]
我用的百度fis 的mod.js
因为require函数不能使用变量作为参数，所以我写了一个分配的service。

**Comment by xxapp** [comment]
我想问的是如果用一个vm作为service，但不和页面同步，这样写好不好。

**Comment by RubyLouvre** [comment]
前面的解藕更好

**Comment by xxapp** [comment]
非常感谢回答。
