### ISSUE TITLE
avalon.mobile.js 下的require 无法回调 callback not work

### ISSUE THREAD

**Issue by code33** [RubyLouvre/avalon#742]
rt
avalon.require(['a'],function(){
//回调无效
})

但是在调用 avalon.js require 回调是正常的

版本号 avalon.mobile.js(支持触屏事件) 1.39 build in 2015.1.15 

求解

**Comment by RubyLouvre** [comment]
升级一下, 改成3月份的,可能是之前的构建工具有问题

**Comment by code33** [comment]
哦,我是直接bower install的呃~

**Comment by RubyLouvre** [comment]
那个版本太旧

**Comment by code33** [comment]
换上这个版本依然不行,

require([ 'domReady!',"mmState","mmRequest"], function () {
//回调有效

    avalon.require(['a'],funtion(){
        //回调无效
    })

});

版本号: avalon.mobile.js 1.4 built in 2015.3.5 故障

版本号: avalon.js 1.391 build in 2015.1.27  正常

**Comment by RubyLouvre** [comment]
不要使用avalon.require，直接用require

**Comment by RubyLouvre** [comment]
```html
<!DOCTYPE html>
<html>
    <head>
        <title>test avalon</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge" /> 
        <script src="avalon.js"></script>
        <script>
            console.log(require)
            require([ 'domReady!', "mmState", "mmRequest"], function() {
                console.log("outer")
                        avalon.require(['aaa'], function(b){
                        console.log(b)
                    })
            });
        </script>
    </head>

    <body ms-controller="test">
     
    </body>
</html>

```
![image](https://cloud.githubusercontent.com/assets/190846/6523046/ecafe87c-c426-11e4-88bc-b3963baac35f.png)

然后将avalon.js改成avalon.modern.js


然后换成chrome也可以
