### ISSUE TITLE
处理元素转场动画的问题

### ISSUE THREAD

**Issue by darklx** [RubyLouvre/avalon#743]
avalon js 已经非常好用了。
现在我们通过 VM 去驱动元素的隐藏显示，但是只有很生硬的 display:none 效果，用户体验不好。
MVVM 已经用到了这一步，已不想再去写 js 去同步 VM 变化和元素显示、隐藏动画效果代码，那不又倒退回了 jQuery 时代吗？

送佛送到西，框架能否提供一套元素转场动画的解决方案？

**Comment by aaronStac** [comment]
用css3 呗

**Comment by RubyLouvre** [comment]
这个需要等好久，相关组件还没有开发
