### ISSUE TITLE
最新版avalon在您的lession2课程里有点问题，

### ISSUE THREAD

**Issue by WriterLuo** [RubyLouvre/avalon#745]
会报： GET http://localhost:61839/vendor/modules/aaa/aaa.js 

需要再main.js里把：
require(['../modules/aaa/aaa'], function() {
改成
require(['../../modules/aaa/aaa'], function() {

**Comment by RubyLouvre** [comment]
哪里，不知道你说什么，视频教程？

**Comment by WriterLuo** [comment]
是的，视频里的lession2

**Comment by RubyLouvre** [comment]
是下载的PPT或文件吗,如果在讲解视频里面不好改

**Comment by WriterLuo** [comment]
的确是在讲解的视频里，因为慕课没提供下载你课程是课件，我也是在腾讯视频那看到你有百度云的课件下载，那里面是对的，但用最新版的avalon跟随着视频学习操作的话就会碰到问题，我只是提一下而已...生怕别的人学习时候遇到此问题  ^_^

**Comment by RubyLouvre** [comment]
我让人在评论里面注明了
