### ISSUE TITLE
"与富本文编辑器的整合"例子执行起来有问题

### ISSUE THREAD

**Issue by zhangchunlin** [RubyLouvre/avalon#746]
chrome40 和 firefox35 测试结果一致

http://avalonjs.github.io/#zh/engineering/integratewithrichtext.html

比如说编辑器里是 ddd 但底下绑定的结果是 <p>dd</p>

**Comment by RubyLouvre** [comment]
什么编辑器啊,这里有3个编辑器

**Comment by zhangchunlin** [comment]
汗,才发现有3个
tinymce里输 ddd,底下出来的是
```
<p>dd</p>
```
点击以后会刷新成正确的

kindeditor没有问题

UEditor里输 ddd ,底下绑定的结果是
```
<p>ddd</p>
```

**Comment by RubyLouvre** [comment]
UEditor听百度的人说不再维护了
