### ISSUE TITLE
实际开发一个页面只用一个VMODEL，所以建议默认一个$id

### ISSUE THREAD

**Issue by wyshk2007** [RubyLouvre/avalon#747]
实际开发中一个页面大多只用到一个VMODEL，所以建议默认一个$id，
这样在定义VM时候可以不用传$id这个属性了

请原谅我已懒得无可救药！！！
![qq 20150311094810](https://cloud.githubusercontent.com/assets/2402800/6588886/39350f38-c7d3-11e4-85dc-6bee0c14e7a0.png)

**Comment by RubyLouvre** [comment]
那是你们公司赚少能力太差,没什么业务!
