### ISSUE TITLE
ms-data-duplex-focus 在ie下的焦点控制bug

### ISSUE THREAD

**Issue by shileinb** [RubyLouvre/avalon#754]
avalon.js 1.4 built in 2015.3.13 

<input ms-duplex="opts.gridClazz" ms-data-duplex-focus="true"/>

在chrome 下是 页面打开时获得焦点(正常）
但是在ie6，8 下 却始终获得焦点。其他输入框 点不了，无法使用（异常）

**Comment by RubyLouvre** [comment]
请给出页面
