### ISSUE TITLE
avalon mobile中的触屏事件问题

### ISSUE THREAD

**Issue by Canyun** [RubyLouvre/avalon#755]
下面的代码在触控设备的环境中swipe事件会导致click事件不生效，只有swipe事件有效，pc上表现正常。
```javascript
<script>
    avalon.config({
        loader: false
    });
    avalon.define("touch", function (vm) {
        vm.click = function (e) {
            console.log("你好！");
        }
        vm.clickChild = function (e) {
            console.log("你不好");
        }
    });

</script>
```
```html
<body ms-controller="touch">
<div id="screen" style="background-color: #cccccc;width: 80%;height: 300px;" ms-on-swipeleft="click">

    <div style="background-color: red; width: 200px;height: 300px;" ms-on-click="clickChild"></div>

</div>
</body>
```

**Comment by Canyun** [comment]
<script>
    avalon.config({
        loader: false
    });
    avalon.define("touch", function (vm) {
        vm.click = function (e) {
            console.log("你好！");
        }
        vm.clickChild = function (e) {
            console.log("你不好");
        }
    });

</script>
<body ms-controller="touch">
<div id="screen" style="background-color: #cccccc;width: 80%;height: 300px;" ms-on-swipeleft="click">

    <div style="background-color: red; width: 200px;height: 300px;" ms-on-click="clickChild"></div>

</div>
</body>

**Comment by RubyLouvre** [comment]
请说明是什么设备，什么浏览器

**Comment by weeksun23** [comment]
我也遇到了同样的问题，只要父元素绑定了swipe*事件，子元素绑定的tap事件就不能被触发，测试环境：
1.chrome 版本 40.0.2214.93 m 自带的手机模拟器
2.iphone 5s Safari

**Comment by RubyLouvre** [comment]
swipe后应该不会触发click吧

**Comment by weeksun23** [comment]
swipe后是不会触发click，但我click子元素的时候都没有触发所绑定的click事件

**Comment by Canyun** [comment]
是在chrome环境下，设备就是一般的触摸设备。

**Comment by weeksun23** [comment]
求解决。。。

**Comment by shirlyLoveU** [comment]
已解决
