### ISSUE TITLE
avalon + jquery.ui.sortable 【View】 中【数组】顺序改变，如何同步到 【ViewModel】

### ISSUE THREAD

**Issue by ascoders** [RubyLouvre/avalon#756]

**Comment by rengeng1986** [comment]
1、用同一个数据源avalon.define({id:'id',list:[]});
2、拖拽完毕后，通过索引来更新list数组，list.set(index, el)
应该可以，试试

**Comment by RubyLouvre** [comment]
不懂，没有代码，无法判定

**Comment by ascoders** [comment]
@rengeng1986 你的方法可以，但我这样用的时候遇到了些bug，明天上例子

**Comment by ascoders** [comment]
@rengeng1986 你的方法可以，但我这样用的时候遇到了些bug，明天上例子

**Comment by ascoders** [comment]
````
<!DOCTYPE html>
<body ms-controller='main'>
  <ul class='sortable'>
    <li ms-repeat='tree'>{{el}}</li>
  </ul>

  <ul class='sortable'>
    <li ms-repeat='tree'>{{el}}</li>
  </ul>
</body>

<script src='http://cdn.bootcss.com/jquery/2.1.3/jquery.min.js'></script>
<script src='http://cdn.bootcss.com/jqueryui/1.11.2/jquery-ui.min.js'></script>
<script src='avalon.js'></script>

<script>
  avalon.define({
    $id: 'main',
    tree:[1,2,3,4,5],
  });

  avalon.nextTick(function(){
    $(".sortable").sortable();
    $(".sortable").disableSelection();
  });
</script>
````

上面的例子，拖动数组，另一个数组的位置不会移动，说明数组顺序v->vm的同步是没有的

**Comment by ascoders** [comment]
````
<!DOCTYPE html>
<body ms-controller='main'>
  <ul class='sortable'>
    <li ms-repeat='tree'>{{el.name}} 序号：{{el.index}}</li>
  </ul>

  <ul class='sortable'>
    <li ms-repeat='tree'>{{el.name}} 序号：{{el.index}}</li>
  </ul>
</body>

<script src='http://cdn.bootcss.com/jquery/2.1.3/jquery.min.js'></script>
<script src='http://cdn.bootcss.com/jqueryui/1.11.2/jquery-ui.min.js'></script>
<script src='avalon.js'></script>

<script>
  avalon.define({
    $id: 'main',
    tree:[
      {name:'第一章',index:0},
      {name:'第二章',index:1},
      {name:'第三章',index:2},
      {name:'第四章',index:3},
      {name:'第五章',index:4},
    ],
  });

  avalon.nextTick(function(){
    var startIndex;

    $(".sortable").sortable({
        items: "> li",
        cursor: "move",
        zIndex: 1,
        start: function (event, ui) {
          startIndex = ui.item.index();
        },
        update: function (event, ui) { // 位置发生改变
          var endIndex = ui.item.index();

            // 此位置之前的组件，下标依次减少
            if (startIndex < endIndex) {
              for (var i = startIndex + 1; i <= endIndex; i++) {
                avalon.vmodels.main.tree[i].index = avalon.vmodels.main.tree[i].index - 1;
              }
            } else {
              for (var i = startIndex - 1; i >= endIndex; i--) {
                avalon.vmodels.main.tree[i].index = avalon.vmodels.main.tree[i].index + 1;
              }
            }

            // 更新拖拽组件位置
            avalon.vmodels.main.tree[startIndex].index = endIndex;

            // 重新排序
            avalon.vmodels.main.tree.sort(function compare(a, b) {
              return a.index > b.index;
            });
        }
      });
    $(".sortable").disableSelection();
  });
</script>
````
试着给把数组元素变成对象，加上index
排序后，重排index，再sort，以更新vm数组顺序。
这里有个bug
1.把第一章拖到第五章下面
2.把第五章拖到第二章上面

第二次的时候，排序混乱了。从index和下面数组可以看出，avalon内部数组结构排序正确，但显示的顺序不正确。

**Comment by gxrsprite** [comment]
给你个参考
; (function () {
    function factory(avalon) {
        var pluginname = "sortable";
        var widget = avalon.ui[pluginname] = function (element, data, vmodels) {
            var options = data[pluginname + "Options"];

            var vmodel = avalon.define(data[pluginname + "Id"], function (vm) {
                //avalon.mix(vm, options)
                vm.widgetElement = element
                vm.$skipArray = ["widgetElement"]

                var inited
                vm.$init = function () {
                    if (inited) return
                    inited = true

                    $(element).sortable(
                        {
                            connectWith: "div",
                            beforeStop: function (event, ui) {
                                var index = $(event.toElement).prevAll().size();
                                var to = $(event.target);
                                var element = ui.item;
                            },
                            start: function (event, ui) {
                                from = $(event.target);
                                fromindex = $(event.toElement).prevAll().size();
                            },
                            stop: function (event, ui) {

                            },
                            update: function (event, ui) {
                                var crtfrom = $(ui.sender);
                                var index = $(event.toElement).prevAll().size();
                                var to = $(event.target);
                                var element = ui.item;
                                if (from == to) {//当前内排序
                                    options.droped(from, fromindex, to, index);
                                    console.log(element, from, fromindex, to, index);
                                }
                                if (ui.sender != null) {//跨div排序而且是第二次
                                    options.droped(from, fromindex, to, index);
                                    console.log(element, from, fromindex, to, index);
                                }

                            }
                        }
                    );

                    avalon.scan(element, [vmodel].concat(vmodels))
                    if (typeof options.onInit === "function") {
                        //vmodels是不包括vmodel的 
                        options.onInit.call(element, vmodel, options, vmodels)
                    }
                }
                vm.$remove = function () {

                }

            })

            return vmodel
        }
        widget.defaults = {
            droped: function () {

            }
        }

        return avalon;
    }

    define("avalon.sortable", ["avalon", "jquery-ui"], factory)
}());

**Comment by ascoders** [comment]
@gxrsprite 能否写个完整例子出来？

**Comment by gxrsprite** [comment]
了解widget后你就知道怎么调用了 ms-widget="sortable,$,$opts"
$opts = {
droped:function(from,fromindex,to ,toindex){

}
}

**Comment by ascoders** [comment]
看懂了，把sort包装成组件了啊。

可是droped怎么写？能否指出我例子中的问题

**Comment by gxrsprite** [comment]
from to 是div，自己得找到对应哪个数组，index是第几个。有可能一个div里放两个数组，所以剩下的自己看吧。

**Comment by Lihuanghe** [comment]
http://lihuanghe.github.io/avalon-easyui-demo/jqueryUIwrapper.html
这里包装了很多jqueryUI的例子

**Comment by ascoders** [comment]
@Lihuanghe  非常感谢。
但里面没有此issue提及的sortable+avalon组合

**Comment by iulo** [comment]
@ascoders 这个问题解决了吗
