### ISSUE TITLE
avalon.filters.date这个控件在火狐和谷歌上有兼容性问题

### ISSUE THREAD

**Issue by songzhibin** [RubyLouvre/avalon#761]
“20150319”通过avalon.filters.date(p.begindate,'yyyy-MM-dd') 调用， 在火狐上显示“NaN-NaN-NaN-NaN”,在谷歌上显示“2015-03-19”。

**Comment by RubyLouvre** [comment]
20150319这格式不对,请使用2015-03-19，你要看文档啊，不要乱写

**Comment by songzhibin** [comment]
不好意思，我写错了。后台传来的数值是这样的。"begindate":"2015-03-01 00:00:00"

**Comment by RubyLouvre** [comment]
换新版本试试
