### ISSUE TITLE
avalon中是否能自己修改“{{}}”语法？ 

### ISSUE THREAD

**Issue by shenyushun** [RubyLouvre/avalon#762]
作者您好，我是一个python开发者，使用jinja2模板引擎，刚接触avalon发现它和jinjia2默认的“{{}} ” 语法冲突，虽然可以使用其他方式进行解决，不过这样代码结构就变得有些复杂了。不知道avalon中是否有类似于angularjs中
var my_app = angular.module('MyApp').config(function($interpolateProvider) {
    $interpolateProvider.startSymbol('{$');
    $interpolateProvider.endSymbol('$}');
});
这种解决方式呢？

**Comment by ouxmm** [comment]
默认情况下，我们是使用{{ }} 进行插值，如果有特殊需求，我们还可以配置它们：
```javascript
avalon.config({
   interpolate:["<%","%>"]
})
```

**Comment by ouxmm** [comment]
记得正美博客园入门文章里有提到过，刚帮你翻了下你可以看看
http://www.cnblogs.com/rubylouvre/p/3181291.html

**Comment by RubyLouvre** [comment]
可以配置，如LS所说

**Comment by shenyushun** [comment]
多谢回复，是我没看仔细，以为所有文档都在https://avalonjs.github.io/ 呢，就没再去其它网站看。

**Comment by RubyLouvre** [comment]
http://avalonjs.github.io/#zh/configuration/index.html
