### ISSUE TITLE
ms-attr-*的值如与id值一致 validation 里reason.element.getAttribute("ms-attr-*")报错

### ISSUE THREAD

**Issue by kusajin** [RubyLouvre/avalon#777]

**Comment by RubyLouvre** [comment]
描述不清,请给写HTML与JS

**Comment by kusajin** [comment]
<input type="password" maxlength="20" minlength="6" ms-duplex-maxlength-minlength="orgInfo.loginPassword"  ms-attr-flag="loginPassword"   id="loginPassword" />


validation: {
onError: function(reasons) {
                reasons.forEach(function(reason) {
                    avalon(this).removeClass("success").addClass("error")
                    var flag=avalon(this).data().checkType;
                    if(flag){
                    	 reason.message= errMsg[flag] ;
                    }
                    showError(this, reason)
                    if(reasons.length>1){
                    	return false;
                    }
                }, this)
            }
}


function showError(el, data) {
	    vm.errArray[el.getAttribute("ms-attr-flag")].fieldName=data.getMessage();
    }

el.getAttributes 将 ms-attr-flag 转化为 flag nodevalue 为object htmlelement 而不是 loginPassword
貌似不能与 id的值一致

**Comment by RubyLouvre** [comment]
是的

**Comment by RubyLouvre** [comment]
```
 reasons.forEach(function(reason) {
  console.log(reason)
```
你可以在reason里面拿到许多东西
