### ISSUE TITLE
avalon realClassName = window['findOrDefineVBClass'](className, code) 这一行出bug

### ISSUE THREAD

**Issue by ascoders** [RubyLouvre/avalon#779]
例子地址

（ie6 7 8 才出此bug）

http://pan.baidu.com/s/1sjPYezN

**Comment by ascoders** [comment]
非法key
可能是内存泄露

**Comment by RubyLouvre** [comment]
已经修复 https://github.com/RubyLouvre/avalon/commit/52b1ecd33c668b37c30b90adba8321f8faf67e9e
