### ISSUE TITLE
自带加载器 绝对路径无效

### ISSUE THREAD

**Issue by ascoders** [RubyLouvre/avalon#782]
> 如果模块ID在paths配置项里配置了，如果它的值是绝对路径，那么就直接用这个没有什么好说的。 如果是相对路径，那么先找父模块的路径，没有父模块使用baseUrl。

试了下绝对路径，发现和相对路径没啥两样.

avalon放在根目录下，都是以根目录开始的，但放在例如/x目录下，require(['/a']) 并没有加载 /a.js 而是加载了 /x/a.js

**Comment by RubyLouvre** [comment]
http://avalonjs.github.io/#zh/engineering/loader.html

**Comment by ascoders** [comment]
是的，根据这个思路，paths也支持绝对路径吧。但其实是不支持的。

demo中avalon总是放在根目录下，如果调整到子目录，这个路径总是相对于avalon所在的目录，或者data-main所在的目录。没什么影响，但无法使用绝对路径。

![eept z5bytrj l t1do cd](https://cloud.githubusercontent.com/assets/7970947/6918494/bea0144c-d7e1-11e4-8220-09d82e8dbbfa.png)

![qn60uk wak_ga k3efeyx](https://cloud.githubusercontent.com/assets/7970947/6918496/c0a2c154-d7e1-11e4-8a87-2a7cca2ca85a.png)

**Comment by RubyLouvre** [comment]
那试一下修修，现在没时间，正在做agate  https://github.com/RubyLouvre/agate

**Comment by ascoders** [comment]
恩，我试试。

另外顶这个项目
