### ISSUE TITLE
1.3.4升级1.4.1后，对数组进行push操作，repeat里面的跟$last有关的计算没有重新计算。

### ISSUE THREAD

**Issue by 178220709** [RubyLouvre/avalon#785]
avalon/examples/repeat3.html 
修改如下：
    <li  ms-repeat="array">数组的第{{$index+1}}个元素为{{el}}   <span style="color: red" ms-if-loop="$last">(is last)</span>     </li>

http://jsbin.com/fojutecubi/1/edit?html,output 
这是1.3.4版本 正常

升级1.4.1（ avalon.js 1.41 built in 2015.4.1）后就:

数组的第1个元素为1
数组的第2个元素为2
数组的第3个元素为3
数组的第4个元素为4 (is last)
数组的第5个元素为1 (is last)
数组的第6个元素为2 (is last)
数组的第7个元素为3 (is last)

**Comment by RubyLouvre** [comment]
已经修复
