### ISSUE TITLE
A 标签建议参考 angularjs，换成绝对路径写法，支持后期seo优化时，让蜘蛛可以爬到有效页面

### ISSUE THREAD

**Issue by ascoders** [RubyLouvre/avalon#786]
#!/xxx

对搜索引擎只是一个锚点，并不会抓取内容，抓取了也无法解析到正确url

建议仿照angularjs，href使用正常url，监听即可。

**Comment by RubyLouvre** [comment]
angularjs也不能啊

**Comment by RubyLouvre** [comment]
你应该在后端生成这些A标签的href

**Comment by ascoders** [comment]
http://www.angularjs.cn/

你看下angularjs社区的标签

````
<a ng-href="/A12P" class="ng-binding" href="/A12P"><i class="primary fa fa-external-link" ng-class="{'fa fa-hand-o-up':article.status==2, 'fa fa-external-link':article.status!=2}"></i>如何快速学会app开发 如何从web开发屌丝向移动互联网转型</a>
````

ng-href后面，有个href标签供浏览器抓取，avalon直接占用了href，没法搞呀。

**Comment by RubyLouvre** [comment]
你可以搞一个ms-href处理啊

**Comment by ascoders** [comment]
angularjs生成的a标签有 `ng-href` 和 `href` ， 但avalon `ms-href` 处理后只有一个 `href` 标签，而且路径是无法抓取的 #!/xxx
