### ISSUE TITLE
avalon文本编辑器

### ISSUE THREAD

**Issue by davidduwei** [RubyLouvre/avalon#787]
用了路由，在某个页面使用了ueditor.第一次进入此页面，显示正常，然后进入到另外一个页面后，再次进入的这个页面ueditor就显示不出来呢。
http://avalonjs.github.io/#zh/engineering/integratewithrichtext.html
然后我查看了avalon官网 tinymce，kindeditor也存在这样的问题。

**Comment by RubyLouvre** [comment]
这是缓存问题,我是远程加载的,你弄到本地就好了

**Comment by davidduwei** [comment]
avalon.state("orderList", {
                    controller: "root",
                    url: "/orderList",
                    //abstract:!_.contains(permission, 'dealer'),
                    onChange: function() {
                         checkLogin()
                         if(avalon.vmodels.root.loginedsuccess == 0){
                         	this.views = {}
                         	avalon.vmodels['dialog'].toggle = true;
                         }
                    },
                   	onBeforeLoad: function() {
                        avalon.vmodels.loadingId.showLoading()
                    },
                    onAfterLoad: function() {
                       avalon.vmodels.loadingId.hideLoading()
                    },
                    views: {
                        "": {
                            templateUrl:  "/ordermanagers/orderList.html?v="+(new Date().getTime())
                        }
                    }

                })
我都是本地项目 加上版本号同样没有效果。第二次进入该页面应该是html js都不会再发请求呢。

**Comment by RubyLouvre** [comment]
那等我同事放假回来再看看吧

**Comment by davidduwei** [comment]
我用最新版还是存在该问题。
我多次进入同一个页面 存在的dialog会重复添加新的dom元素到页面上，导致编辑器不可用呢。

**Comment by davidduwei** [comment]
我用最新版还是存在该问题。
我多次进入同一个页面 存在的dialog会重复添加新的dom元素到页面上，导致编辑器不可用呢。

**Comment by davidduwei** [comment]
我用最新版还是存在该问题。
我多次进入同一个页面 存在的dialog会重复添加新的dom元素到页面上，导致编辑器不可用呢。

**Comment by davidduwei** [comment]
我用最新版还是存在该问题。
我多次进入同一个页面 存在的dialog会重复添加新的dom元素到页面上，导致编辑器不可用呢。

**Comment by MisterRay** [comment]
销毁了再调用 。
![image](https://cloud.githubusercontent.com/assets/5857166/7174715/acaf540a-e43e-11e4-9f02-141e62d7d9cd.png)

**Comment by davidduwei** [comment]
thanks，后来是这样用就好了，如果编辑器是放在dialog层中的话，但还得把之前的dialog给remove掉。每次进入到这个页面都会创建一个新的dialog.
