### ISSUE TITLE
avalon.mobile 划动事件无法正确执行

### ISSUE THREAD

**Issue by Canox3** [RubyLouvre/avalon#788]
测试中发现最新版（2015.4.4）的avalon.mobile.js绑定事件在iOS可以正常执行，在安卓,WP和和PC端Chrome游览器中，滑动事件都无法正常执行

测试代码如下

![qq20150406151317](https://cloud.githubusercontent.com/assets/7719747/7001621/b3eae45e-dc6f-11e4-8a52-1ca022f414e0.jpg)

在1.4.1初版（2015.3.23） iOS和PC端Chrome中可正确执行，安卓和WP中依然无法正确绑定

**Comment by shirlyLoveU** [comment]
http://shirlyloveu.github.io/staticTests/mobileExample/touchEvents.html
你运行这个链接里的demo，看看是否都ok，如果依然有问题请说明你系统的版本

**Comment by Canox3** [comment]
你给我这个demo链接的avalon.mobile版本(2015.3.18) ，iOS，安卓和WP设备下能够正常执行，不过在PC下用Chrome不能执行。我用上面提到的测试代码换了这个版本的js也是跟测试demo一样的结果。新发布的几版是不是源码哪有冲突了。

**Comment by Canox3** [comment]
PC的系统版本是win7 64 Chrome版本 40.0.2214.115

**Comment by shirlyLoveU** [comment]
你重新拉下avalon

**Comment by Canox3** [comment]
最新版(2015.4.8)版本我测试还是存在无法正常执行的情况，在(2015.3.18) 的版本下依然是正常。我用的是手机实际测试，另外就是用chorme模拟客户端，情况都一样。我测试的是你给的那个demo和我上面的那个demo

**Comment by RubyLouvre** [comment]
又加了一些补丁,你去试试好了没有

**Comment by fastpoint** [comment]
正好需要用到，一看你的，赶紧w一把，功德无量啊



 
王东刚    [Fastpoint]
手机:15336873800  邮件:fastpoint@fastpoint.cn
 
 
发件人： 司徒正美
发送时间： 2015-04-15 12:09
收件人： RubyLouvre/avalon
主题： Re: [avalon] avalon.mobile 划动事件无法正确执行 (#788)
又加了一些补丁,你去试试好了没有

**Comment by Canox3** [comment]
还是不行，avalon1.42(2015.4.15) 这个版本跟之前几个版本遇到的情况还是一样，同环境下测试还是只有(2015.3.18)这个版本能在所有手机客户端下执行

**Comment by shirlyLoveU** [comment]
http://shirlyloveu.github.io/staticTests/mobileExample/touchEvents.html  

麻烦你运行下这个demo，然后告诉我在android的什么版本的什么浏览器下面失效，谢谢，可以的话麻烦附上你自己的demo

**Comment by Canox3** [comment]
我重新在lumia920和SONY的Z3上测试了一下，你提供的demo中avalon.mobile版本和新的1.42版都可以执行。

早上我直接用chorme模拟客户端模拟测了一下不能执行，就仓促回复了，实在是抱歉。
感谢你们耐心的回答。

**Comment by shirlyLoveU** [comment]
有问题及时提出来方便我们尽快完善，谢谢
