### ISSUE TITLE
新版本的特性积累

### ISSUE THREAD

**Issue by RubyLouvre** [RubyLouvre/avalon#790]
1.4.2
修正parseHTML 对非标签类型的字符串解析失败的BUG
修正监控数组push方法没有同步$last属性的BUG
更改safari5.x下contains方法的存在性检测
更改对avalon.*.shim文件的构建
修正IE6-11下的ms-duplex-checked BUG 
优化提示信息
添加data-include-cache辅助指令

**Comment by RubyLouvre** [comment]
1.4.3
修复ms-attr绑定对布尔属性的值为false的BUG，必须先设置为false，再用removeAttribute移除
修复avalon.modern下data()方法 BUG
修复postion()对父元素出现滚动条取值不正确的BUG

**Comment by RubyLouvre** [comment]
1.4.4
强制触发 widget 的$init方法

scanAttr不能对VML元素访问nodeType属性；IE6-8下如果访问VML元素的type属性,就让会它的所有属性值都变成<Failed>,这时我们再访问它的这些属性时,就会抛错

修复 为监控数组删除或添加项时会让触发其它项更新的BUG， 修复方法为$index, $first, $last, el不再共享订阅数组，el进行依赖收集时是通过$index实现的，在收集前，将$index的订阅数组改为el的 https://github.com/RubyLouvre/avalon/issues/817

toggleClass 第一个参数必须为字符串

**Comment by zhangfisher** [comment]
希望能增加动态添加删除绑定属性的功能

**Comment by RubyLouvre** [comment]
1.4.4
更新随机数的生成策略
内部方法registerSubscriber更名为avalon.injectBinding并暴露出来

**Comment by RubyLouvre** [comment]
1.4.5
fix IE()方法的BUG，非IE浏览器下都返回NaN

**Comment by RubyLouvre** [comment]
1.4.6

修复对flexbox的CSS属性支持 https://github.com/RubyLouvre/avalon/issues/926

**Comment by RubyLouvre** [comment]
1.5
加强对数组set方法的检测，index不能大于数组长度
计算属性只能定义在$computed对象中

**Comment by RubyLouvre** [comment]
1.5.1

1. 精简自定义标签的设计
2. fix cache内存泄漏
3. 添加$fire("all!xxx")的支持
4. fix ms-duplex使用拦截器时触发多次的BUG
5. 公开openTag, closeTag到avalon.config
6. fix isWidget BUG

**Comment by RubyLouvre** [comment]
1.5.2

1. configs 改名为 config
2. $extends  改名为 $extend
3. fix loader不能正确处理url path map之后带query的BUG
4. fix ms-if 与 HTML5 form validation共用时的BUG
5. fix $watch回调this指向BUG 
6. fix  ms-if 碰到子对象的属性不存在时不插入节点的 BUG
7. fix ms-include不存在动画时不会移除旧节点的BUG

**Comment by RubyLouvre** [comment]
1.4.7

修复repeat clear时回收data后导致scan模版出错的问题
修复对二维数组项repeat时，变换下标不能触发视图更新，及更新前后数组长度一样时不能更新的bug

修复ms-duplex光标移动问题

**Comment by RubyLouvre** [comment]
1.5.4

fix 1.5.4 select 的 duplex 变成了单向的BUG

**Comment by jincan39** [comment]
前排。。

**Comment by RubyLouvre** [comment]
1.5.5
<ol>
<li>终于比较完美地解决光标问题</li>
<li>fix data-duplex-changed执行两次的BUG</li>
<li>启动全新的UI库 <a href="https://github.com/RubyLouvre/avalon.bootstrap">avalon.bootstrap</a> 欢迎大家踊跃参与</li>
<li>fix IE下onchange与oninput无法共存的BUG</li>
<li>以 component组件进行增强,现在支持对on-xxx属性在vmodels查找回调的功能</li>
</ol>

**Comment by RubyLouvre** [comment]
1.5.6
修复组件样式丢失BUG
修复扫描引擎两次进入组件内部引发的BUG
实现对$watch("*", callback)的支持

**Comment by RubyLouvre** [comment]
fix {{}}里面存在换行的BUG
fix 1.5.5的clear方法与1.4.7的行为不一致的BUG
