### ISSUE TITLE
avalon1.4 加载器 packages

### ISSUE THREAD

**Issue by cxyguopong** [RubyLouvre/avalon#796]
大神 avalon1.4 加载器 packages 感觉有问题啊 。如果配制最简单的包packages:[ 'cat' ] , 在require(['cat'])是可以载入cat/main.js的，可是一旦加上location和main就有问题了。他会加载 http://localhost/loader6/cat.js

**Comment by RubyLouvre** [comment]
能有更具体的例子吗

**Comment by cxyguopong** [comment]
用的是你官方 关于avalon自带加载器 配置项 packages 最后的那个例子 。在main.js中将packages: ["cat"]改成 packages: [ { name : "cat1"  , location :'cat' , main :'main' } ] 。require( [ 'cat/main' ] ) 是可以访问的

**Comment by cxyguopong** [comment]
不小心 把主题关了！！！
