### ISSUE TITLE
VM新添加的属性无法视图同步

### ISSUE THREAD

**Issue by yomefeling** [RubyLouvre/avalon#798]
<body ms-controller="ivm">
      <p>{{title}}</p>
</body>

var vm=avalon.define({
	$id:'ivm',
})
avalon.scan();
vm.title="hahaha"   //此时视图不会同步

临时解决方案就是加上title:null,再改变title是没有问题的，请问这个是不是设计如此？

**Comment by 554943871** [comment]
就是这样涉及的啊，教程说了啊

**Comment by yomefeling** [comment]
哦   好的 谢谢  没注意到
