### ISSUE TITLE
在android手机qq和微信内置浏览器中，swipeXXX事件无效

### ISSUE THREAD

**Issue by abbleto** [RubyLouvre/avalon#799]

**Comment by Canox3** [comment]
我也遇到这个问题，建议先使用2015年3月18日版本的avalon.mobile.js。我测试这个版本的所有客户端都支持，后来的这几版就是iOS的能正常执行，安卓和WP都无法正确执行。

**Comment by RubyLouvre** [comment]
又加了一些补丁,你去试试好了没有

**Comment by shirlyLoveU** [comment]
刚更新了代码，你现在拉下代码看看

**Comment by abbleto** [comment]
多谢，android 微信版本swipe已经可以了，android qq内置浏览器还是不行。

**Comment by shirlyLoveU** [comment]
我在三星s3下的android 4.3中qq浏览器测试ok的，所以需要你提供下你的android版本

**Comment by abbleto** [comment]
...今天再次打开居然可以了 ，可能上次浏览器缓存。不好意思，多谢！
