### ISSUE TITLE
duplex-observe 文档示例

### ISSUE THREAD

**Issue by myqianlan** [RubyLouvre/avalon#801]
index_duplex2.html 示例。

当把avalon.js改为avalon.modern.js或者其他版本时候，示例duplex-observe均变为无效了。

不知是何原因？

版本：1.4.1.1
浏览器：Chrome 41

**Comment by RubyLouvre** [comment]
已经修复 https://github.com/RubyLouvre/avalon/commit/90f16e9153e9b6ef68dfa4b483197bafd6f3f5a5
