### ISSUE TITLE
关于在ms-repeat里使用ms-include-src加载模板的问题

### ISSUE THREAD

**Issue by andyforever** [RubyLouvre/avalon#805]
每次循环都会发起请求加载模板，是否可以进行缓存处理？或者其他处理方式？
![default](https://cloud.githubusercontent.com/assets/3242791/7179191/e59b72f2-e467-11e4-9faa-61191f950304.PNG)

![123](https://cloud.githubusercontent.com/assets/3242791/7179172/b058d094-e467-11e4-87e3-2ffabbc6e917.PNG)
![111](https://cloud.githubusercontent.com/assets/3242791/7179178/bd986a58-e467-11e4-990b-46f0daccf491.gif)

**Comment by RubyLouvre** [comment]
做个例子看看

**Comment by andyforever** [comment]
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>duplexHooks</title>
        <meta http-equiv="X-UA-Compatible" content="IE=8" />
        <script src="../avalon.modern.js"></script>
        <style>
            .bp{
                border: 1px  solid green;
            }
            .contain{
                border: 1px solid red;
            }
        </style>
        <script>
            var count = 0
            var a = avalon.define({
                $id: "test",
                aaa: "aaa.html",
                checked: function(){
                    count++
                    if(count == 2){
                        //cg
                    }
                },
                array:[1,2,3,4,5,6],
                change: function() {
                    a.aaa = a.aaa === "aaa.html" ? "bbb.html" : "aaa.html"
                }
            })

        </script>
    </head>
    <body ms-controller="test">
        <button type="button" ms-click="change">change</button>
        <div ms-repeat-el="array">
            <div ms-include-src="'include2'+aaa" class="contain" data-include-rendered="checked"></div>
                    <div ms-include-src="'include2'+aaa" class="contain" data-include-replace="true" data-include-rendered="checked"></div>
        </div>

    </body>
</html>

**Comment by RubyLouvre** [comment]
这是你在循环中同时发出许多相同的请求,这时它们还没有一个请求完成,进行缓存

**Comment by RubyLouvre** [comment]
你可以自己在avalon.templateCache['include2aaa.html'] = "xxxxxxxxxxxxxx" 将要请求的内容放好,这样它就不会发出请求

**Comment by andyforever** [comment]
在什么时候执行这个操作？

**Comment by RubyLouvre** [comment]
在它之前

**Comment by andyforever** [comment]
没懂......

有对这个问题的版本改进计划么？或者这个不是常规需求？

**Comment by RubyLouvre** [comment]
好了，我修改了avalon的源码，原生支持它；你升级吧

**Comment by andyforever** [comment]
+1
么么哒
