### ISSUE TITLE
请教一个关于avalon.define定义的问题

### ISSUE THREAD

**Issue by liuwei3230** [RubyLouvre/avalon#810]
我现在用avalon做一个内部的系统,现在有个问题，因为未采用iframe结构，所以目前是用
 $.ajax({url : url, type : "GET", dataType : "html", cache : false})加载子模块页面，
然后$("#content").html(data);这样方式
目前有个问题，
因为会可能重复点击一个模块，那就会不停的执行子页面里的
```javascript
var b=avalon.define({
        $id:"test",
        aaa:1,
		bb:function(){}
 });
```
类似的定义。
这样不停下去会不会有啥问题。
我想问下返回的b对象有没有提供删除之类的方法，让我释放这个vm.

**Comment by wyzfzu** [comment]
通过avalon.vmodels['test'] 来获取vm，如果vm存在就返回，不存在就定义。

**Comment by liuwei3230** [comment]
但是我切换时候，会把 test作用域下面的html全部清空替换成别的，，，这样不会有问题么

**Comment by wyzfzu** [comment]
在再次加载这个html的时候，重新再scan一下。 或者你可以看下教程里面的ms-include-src指令。

**Comment by RubyLouvre** [comment]
http://avalonjs.github.io/#zh/bindings/include.html 使用这个 ms-include-src='xxx' data-include-cache="true"
