### ISSUE TITLE
IE8缓存js时require加载依赖js失败

### ISSUE THREAD

**Issue by WangJinglin** [RubyLouvre/avalon#811]
定义a.js依赖b.js。然后使用require加载a.js.
```javascript
/**   a.js  */
define('modelA',['b.js'],function(b){

});
/**  b.js  */
define('modelB',function(){
    var  b=function(){   }
   return b;
});
```
调用
```javascript
 require(['a.js'],function(a){
            avalon.log('a.js---------OK');
  });
```
在IE8标准模式下，如果设置了缓存js，第一次请求时控制台正常输出“a.js---------OK”,
点刷新按钮，加载js状态是304，此时控制台也正常输出“a.js---------OK”,
在地址栏回车再次访问时，加载js状态是Cache，此时控制台无显示，require回调没有执行。
切换到IE8兼容模式后正常执行回调。

**Comment by WangJinglin** [comment]
截图
![qq 20150422163303](https://cloud.githubusercontent.com/assets/3089737/7270255/71883904-e90d-11e4-81b0-d667c336d3ad.jpg)

**Comment by RubyLouvre** [comment]
IE8下特别配置一下
```javascript
if(window.VBArray && !window.addEventListener){
  require.config({
     urlArgs: {
        "*" :"v="+ Math.random()
    }
 })
}

```
