### ISSUE TITLE
ie8下data-include-rendered 问题,报“缺少对象”错误

### ISSUE THREAD

**Issue by endichen** [RubyLouvre/avalon#814]
两个文件index.html和header.html
index里面引入了header， "
div ms-include-src="header" data-include-rendered='headerRender'></div"
同时：var indexModel = avalon.define({
                    $id: "index",
                    header: "header.html",
                    footer: "footer.html",
                    headerRender: function(){
                        someMethodInHeaderHtml();
                    }
                });
在ie8下运行 someMethodInHeaderHtml();会报“缺少对象”错误。
someMethodInHeaderHtml()方法是直接定义在header.html的js代码里。

**Comment by RubyLouvre** [comment]
someMethodInHeaderHtml 与 avalon不在同一作用域

**Comment by endichen** [comment]
哦  我试试

**Comment by endichen** [comment]
我在header.html定义了var loginModel = avalon.define({
        $id: "login",
someMethodInHeaderHtml ：function()...

indexModel 和loginModel 是属于两个不同的作用域？

**Comment by endichen** [comment]
不知道什么原因，ie8下面可以正常运行了，采用avalon.vmodels.login.someMethodInHeaderHtml();
