### ISSUE TITLE
数组push新成员时，上一个成员的视图会被重新渲染

### ISSUE THREAD

**Issue by Broltes** [RubyLouvre/avalon#818]
我用一个数组存储一个单页面应用的视图：

    var viewsModel = avalon.define({
        $id: 'views',
        array: []// 所有视图
    });

当我往array里push新的view时，上一个view对应的页面元素会被重新渲染。
即：

    var vm = viewsModel.array[viewsModel.array.push(newViewModel)-2];

vm对应的html元素重新渲染了一下（因为我需要保持不同view的滚动条位置，这就导致上一个view的滚动条位置回到0了）。

1.4.1还没有这个问题，1.4.2有。不知是不是哪里姿势不对

**Comment by RubyLouvre** [comment]
到runjs里面写例子

**Comment by RubyLouvre** [comment]
这个比较麻烦，我需要重新设计内部的依赖收集与触发机制，可能要等上一个月

**Comment by RubyLouvre** [comment]
问题同这个 https://github.com/RubyLouvre/avalon/issues/817
