### ISSUE TITLE
不支持 ms-attr-style

### ISSUE THREAD

**Issue by darklx** [RubyLouvre/avalon#819]
例如这样的代码：

```html
<div ms-attr-style="text-align:center;height:{{layout.content.height}}px;line-height:{{layout.content.height}}px;" ms-visible="!ifArray(NewFlowedQuestions) && !ifArray(SubscrptionUpdateQuestions)">空空</div>
```

而如果不用：attr-style ，用 attr-a，则是可以的。

**Comment by RubyLouvre** [comment]
http://avalonjs.github.io/#zh/bindings/attr.html

这里已经明确告诉你不支持了
多看新官网吧
还有,你不应该在视图上写这么长的业务逻辑

**Comment by darklx** [comment]
@RubyLouvre 
抱歉，之前搜索引擎搜过没有搜到相关资料，以为是 BUG，所以提出来也是想促进 avalon 更好用。

我之所以需要用动态的 style，是因为有些如宽高是动态计算出来的。
想知道的是，既然可以支持 ms-css-xxx ，为啥不支持 ms-style 呢？样式的控制写在一行 style 里，比分散在 ms-css 里更好呀。

还有，这本来就是用 avalon 去控制动态样式的一个场景，都是样式的控制，里面的 layout 哪个 VM 就是一个专门控制 window、body、main content 等元素的宽高的专用 VM。可以理解为用 avalon 来代替原来用 js 动态修改样式的工作，或者说是用 avalon 去代替原本用 jQuery 写插件的工作，
