### ISSUE TITLE
$unwatch文档太模糊了，希望提供例子

### ISSUE THREAD

**Issue by 21paradox** [RubyLouvre/avalon#821]
同 https://github.com/RubyLouvre/avalon/issues/795

$unwatch(type? , fn? ), 它共有三种用法, 第一个参数代表类型, 第二个是回调, 如果两个都传入, 那么就移除此回调; 如果只传一个参数type, 那么就将所有该类型的回调都移除; 如果不会参数, 那么相当移除所有回调

文档写的看不懂啊！！！
第一个参数代表属性名吧，麻烦这个地方配一点例子吧，感觉 unwatch这一块还是挺有用的。

vm.$watch('current', loadFriendsIfNoFriends) 返回的是 vm，这个没说

**Comment by RubyLouvre** [comment]
一个参数就是将VM的某个属性的$watch回调移除；
零参数是将这个VM的所有$watch回调暂时性移除

**Comment by 21paradox** [comment]
@RubyLouvre 感谢回复。

**Comment by RubyLouvre** [comment]
http://avalonjs.github.io/#zh/concepts/$unwatch.html

**Comment by RubyLouvre** [comment]
添加多点内容
