### ISSUE TITLE
avalon.mobile.js在移动端影响select使用的bug

### ISSUE THREAD

**Issue by FaceRollTheKeyboard** [RubyLouvre/avalon#826]
在使用avalon.mobile.js的时候，如果页面中使用了select，点击select的时候将无法弹出option，导致下拉选择框无法选择，目前很多人都发现了这个问题~

具体的测试项目在这里：http://git.oschina.net/mooshroom/selectOnMobile

**Comment by RubyLouvre** [comment]
已经修复
