### ISSUE TITLE
如何在a标签的点击回调事件里,操作dom(就是a标签)呢

### ISSUE THREAD

**Issue by yangqinjiang** [RubyLouvre/avalon#827]

**Comment by yangqinjiang** [comment]
collect:function  (e,vid) {
            e.style.background = "url('/img/icon_2.png') 0px 5px no-repeat";
        }

**Comment by RubyLouvre** [comment]
请给一个完整简单的页面

**Comment by yangqinjiang** [comment]
意思是说,响应a的点击事件,在函数里修改a的样式,不想使用ms-attr-*

**Comment by RubyLouvre** [comment]
请给一个完整简单的页面
