### ISSUE TITLE
avalon如何加载artdialog

### ISSUE THREAD

**Issue by kuafuwang** [RubyLouvre/avalon#828]
在加载artdialong之前，能看到avalon的require不是undefined

![1](https://cloud.githubusercontent.com/assets/3636678/7512599/baa2ef10-f4e0-11e4-9151-e63571ade385.png)
![2](https://cloud.githubusercontent.com/assets/3636678/7512616/d5a892f6-f4e0-11e4-9957-71168a5bd9b8.png)

载arddialong时候，发现require是undefined的
![3](https://cloud.githubusercontent.com/assets/3636678/7512623/dd0bc4aa-f4e0-11e4-8959-16c998af86bb.png)
![4](https://cloud.githubusercontent.com/assets/3636678/7512630/e18c8dac-f4e0-11e4-806b-003aacb2f49a.png)

我使用requiejs加载时候是正常的
![5](https://cloud.githubusercontent.com/assets/3636678/7512684/325b6ece-f4e1-11e4-9c6b-3bd53b93efb6.png)

但是artdialog是能用seajs和reqirejs加载的。

我使用的
/*!
 * artDialog
 * Date: 2014-11-09
 * https://github.com/aui/artDialog
 * (c) 2009-2014 TangBin, http://www.planeArt.cn
 *
 * This is licensed under the GNU LGPL, version 2.1 or later.
 * For details, see: http://www.gnu.org/licenses/lgpl-2.1.html
 */

**Comment by kuafuwang** [comment]
![Uploading 8.png…]()
![Uploading 10.png…]()

**Comment by RubyLouvre** [comment]
https://github.com/aui/artDialog/blob/master/dist/dialog.js  你应该使用这个，然后通过require的shim机制加载；建议不要用它，改成oniui的弹出层

**Comment by kuafuwang** [comment]
好的，谢谢。

**Comment by zinda2000** [comment]
oniui还不完善，不是很漂亮，功能上不如 jqueryui
