### ISSUE TITLE
二维数组，动态添加数据，绑定不成功

### ISSUE THREAD

**Issue by endichen** [RubyLouvre/avalon#829]
下面的代码，一开始segmentArray是有初始值的，显示正常。但点击click按钮之后，动态修改了segmentArray的值，绑定就失效了，table无法正常显示。请问这该如何解决？

    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <script src="avalon.js"></script>
        <script>
            var model = avalon.define({
                $id: "test",
                onBtnClick: function(){
                    model.segmentArray = [];
                    for(var i = 0; i != 4; i++){
                        model.segmentArray[i] = [];
                        for(var j = 0; j != 4; j++){
                            var obj = new Object();
                            obj.id = "id" + ((i+1)*(j+1));
                            model.segmentArray[i][j] = obj;    
                        }
                    }
                    avalon.log(model.segmentArray);
                },
           
                segmentArray: [[{"id":"id1"}, {"id":2}, {"id":3}, {"id":4}], [{"id":5}, {"id":6}, {"id":7}, {"id":8}], [{"id":9}, {"id":10}, {"id":11}, {"id":12}]]
            })
        </script>
    </head>
    <body ms-controller="test">
        <button ms-click="onBtnClick">click</button>
        <table border="1">
            <tr ms-repeat-segment="segmentArray">
                <td ms-repeat-item="segment">{{item.id}}  它位于第<b style="color:orchid">{{$outer.$index}}</b>行</td>
            </tr>
        </table>
</body>

**Comment by RubyLouvre** [comment]
不要一个个元素赋值，然后放到一个新数组是，然后  model.segmentArray = newArray

**Comment by endichen** [comment]
试了一下，可以了。
        onBtnClick: function(){
                    var array = [];
                    // model.segmentArray = [];
                    for(var i = 0; i != 4; i++){
                        array[i] = [];
                        // model.segmentArray[i] = [];
                        for(var j = 0; j != 4; j++){
                            var obj = new Object();
                            obj.id = "id" + ((i+1)*(j+1));
                            // model.segmentArray[i][j] = obj;  
                            array[i][j] = obj;  
                        }
                    }
                    model.segmentArray = array;
                    // avalon.log(model.segmentArray);
                },
