### ISSUE TITLE
同级结构循环问题

### ISSUE THREAD

**Issue by QzhouZ** [RubyLouvre/avalon#830]
移动端有一个滑动组件，HTML结构如下：

	<div class="slider-wrapper">
		<div class="slider-slide">
			<div class="hd>">第一块标题</div>
			<div class="info">第一块说明</div>
		</div>
		<div class="slider-slide">
			<div class="hd>">第一块子项标题</div>
			<div class="info">第一块子项说明</div>
		</div>
		<div class="slider-slide">
			<div class="hd>">第一块子项标题</div>
			<div class="info">第一块子项说明</div>
		</div>
		
		<div class="slider-slide">
			<div class="hd>">第二块标题</div>
			<div class="info">第二块说明</div>
		</div>
		<div class="slider-slide">
			<div class="hd>">第二块子项标题</div>
			<div class="info">第二块子项说明</div>
		</div>
		<div class="slider-slide">
			<div class="hd>">第二块子项标题</div>
			<div class="info">第二块子项说明</div>
		</div>
	</box>
	
	
在不改变结构的情况下，JSP可以这么实现：

	<div class="slider-wrapper">
	<c:forEach items="${paper.paperModule }" var="m">
		<div class="slider-slide">
			<div class="hd>">${m.name}</div>
			<div class="info">${m.info}</div>
		</div>
		<c:forEach items="${m.itemList }" var="i" varStatus="status">
			<div class="slider-slide">
				<div class="hd>">${i.name}</div>
				<div class="info">${i.info}</div>
			</div>
		</c:forEach>
	</c:forEach>
	</div>
	

以下是用alalon写的,由于ms-repeat要绑定到具体html标签上，就多了个div标签，由于改变了组件结构，组件无效了，请问用alalon有什么好的办法实现吗？

	<div class="slider-wrapper">
	<div ms-repeat="data">
		<div class="slider-slide">
			<div class="hd>">{{el.name}}</div>
			<div class="info">{{el.info}}</div>
		</div>
		
		<div class="slider-slide" ms-repeat-el2="el.paperModule">
			<div class="hd>">{{el2.name}}</div>
			<div class="info">{{el2.info}}</div>
		</div>
	</div>	
	</div>

**Comment by a122676890** [comment]
同问

**Comment by xyz327** [comment]
试试 ms-each?

**Comment by QzhouZ** [comment]
@xyz327 一样的，而且新版本这方法已经废弃了

**Comment by a122676890** [comment]
我的问题是跟题主的问题类似 不过没它这么复杂 比方说后台有100条数据 我每2个就生成<div class="slider-slide">最终结果类似下面
    <div class="slider-slide">
        <div class="hd>">1</div>
        <div class="info">2</div>
    </div>
    <div class="slider-slide">
        <div class="hd>">3</div>
        <div class="info">4</div>
    </div>

该如何做

**Comment by a122676890** [comment]
<div class="slider-slide">
        <div class="hd>">{{el.name}}</div>
        <div class="info">{{el.info}}</div>
    </div>

    <div class="slider-slide" ms-repeat-el2="el.paperModule">
        <div class="hd>">{{el2.name}}</div>
        <div class="info">{{el2.info}}</div>
    </div>

**Comment by RubyLouvre** [comment]
到runjs 写个例子吧

**Comment by RubyLouvre** [comment]
```
<div class="slider-wrapper">
<div ms-each="data">
    <div class="slider-slide">
        <div class="hd>">{{el.name}}</div>
        <div class="info">{{el.info}}</div>
    </div>

    <div class="slider-slide" ms-repeat-el2="el.paperModule">
        <div class="hd>">{{el2.name}}</div>
        <div class="info">{{el2.info}}</div>
    </div>
</div>  
</div>
```
改成这个

**Comment by QzhouZ** [comment]
@RubyLouvre 嗯，谢谢回答，我觉得ms-each可以解决当前问题

**Comment by a122676890** [comment]
@RubyLouvre  意思是 如果有100条数据 循环的时候 
10条一个组合
用repeat 或者each等方法 不能很好的循环出来 或者说 我没用正确的方法？
循环出来的样子如下
<div class="slider-slide">
       0-10条数据
    </div>
<div class="slider-slide">
       11-20条数据
    </div>
我有点笨 能细点吗

**Comment by a122676890** [comment]
郁闷 没发上去 我在看看您发的把 @RubyLouvre

**Comment by RubyLouvre** [comment]
runjs

**Comment by a122676890** [comment]
@RubyLouvre 
Ok
