### ISSUE TITLE
avalon1.4.2 require模块在ie8中BUG

### ISSUE THREAD

**Issue by plains** [RubyLouvre/avalon#831]
```
row[5280]:
var rreadyState = DOC.documentMode >= 8 ? /loaded/ : /complete|loaded/;
```
判断文件是否加载完毕的状态有错误

在IE8中`script`的`readyState`的值是有可能是（缓存） `complete`

测试： xp ie8，先打开页面，然后再改变url参数敲回车，这时js文件的`readyState`值为`complete`
```
row[5280]:建议修改为
var rreadyState =  /complete|loaded/;
```

**Comment by RubyLouvre** [comment]
星期一看看

**Comment by RubyLouvre** [comment]
现在IE8也使用 /complete|loaded/ 了

**Comment by RubyLouvre** [comment]
https://github.com/RubyLouvre/avalon/commit/75cb51cec3da0ecb04ccdeec3d0c9389c52c48cc
