### ISSUE TITLE
数组数据无法更新？

### ISSUE THREAD

**Issue by kingzyl** [RubyLouvre/avalon#833]
我是这样写的
console.log('再次')
console.log(data)
vm.items=data.items,
vm.loginout=data.loginout,
vm.next_page=data.next_page,
........	
console.log(vm.items.size())	

data.items是数据对象，里面放的是json对象，当data.items数组里面只有一个json对象时，页面中ms-repeat="items" 就不再更新（通过控制台显示，其实是vm.items没有更新。）

**Comment by RubyLouvre** [comment]
到runjs写一个例子，这样说我没法调
