### ISSUE TITLE
avalon 自带require 加载顺序问题

### ISSUE THREAD

**Issue by 493409332** [RubyLouvre/avalon#834]
avalon 自带 require 在面对 simplegrid 这种依赖较多的控件时 回调函数 在依赖模块加载完毕之前

**Comment by RubyLouvre** [comment]
到runjs写例子 http://runjs.cn/

**Comment by 493409332** [comment]
define(["text!/Admin/Navigation/Index",  "simplegrid", "dialog"], function (){
  sleep(3000);
.............................
.............................
});
debug: 正准备加载 http://localhost:1753/Admin/Navigation/Index
avalon.js (第 48 行)
debug: 正准备加载 http://localhost:1753/Scripts/avalon/simplegrid/avalon.simplegrid.js?bust=1431314152693
avalon.js (第 48 行)
debug: 正准备加载 http://localhost:1753/Scripts/avalon/dialog/avalon.dialog.js?bust=1431314152693
avalon.js (第 48 行)
debug: 已成功加载 http://localhost:1753/Areas/Admin/Views/Navigation/Index.js?bust=1431314152693
avalon.js (第 48 行)
debug: 已成功加载 http://localhost:1753/Admin/Navigation/Index

休眠3秒

也就是执行了回调方法后 继续加载  
simplegrid 的依赖 如下 导致  simplegrid 加载不成功









debug: 已成功加载 http://localhost:1753/Scripts/avalon/simplegrid/avalon.simplegrid.html?bust=1431314362934
avalon.js (第 48 行)
GET http://localhost:1753/Scripts/avalon/loading/avalon.loading.html?bust=1431314362934
	
200 OK
		9ms	
avalon.js (第 5317 行)
debug: 正准备加载 http://localhost:1753/Scripts/avalon/loading/avalon.loading.html?bust=1431314362934
avalon.js (第 48 行)
GET http://localhost:1753/Scripts/avalon/loading/avalon.loading.bar.html?bust=1431314362934
	
200 OK
		69ms	
avalon.js (第 5317 行)
debug: 正准备加载 http://localhost:1753/Scripts/avalon/loading/avalon.loading.bar.html?bust=1431314362934
avalon.js (第 48 行)
debug: 已成功加载 http://localhost:1753/Scripts/avalon/loading/avalon.loading.css?bust=1431314362934
avalon.js (第 48 行)
debug: 已成功加载 http://localhost:1753/Scripts/avalon/loading/avalon.loading.js?bust=1431314362934
avalon.js (第 48 行)
GET http://localhost:1753/Scripts/avalon/dropdown/avalon.dropdown.html?bust=1431314362934
	
200 OK
		13ms	
avalon.js (第 5317 行)
debug: 正准备加载 http://localhost:1753/Scripts/avalon/dropdown/avalon.dropdown.html?bust=1431314362934
avalon.js (第 48 行)
debug: 已成功加载 http://localhost:1753/Scripts/avalon/dropdown/avalon.dropdown.css?bust=1431314362934
avalon.js (第 48 行)
debug: 已成功加载 http://localhost:1753/Scripts/avalon/dropdown/avalon.dropdown.js?bust=1431314362934
avalon.js (第 48 行)
GET http://localhost:1753/Scripts/avalon/pager/avalon.pager.html?bust=1431314362934
	
200 OK
		32ms	
avalon.js (第 5317 行)
debug: 正准备加载 http://localhost:1753/Scripts/avalon/pager/avalon.pager.html?bust=1431314362934
avalon.js (第 48 行)
debug: 已成功加载 http://localhost:1753/Scripts/avalon/pager/avalon.pager.css?bust=1431314362934
avalon.js (第 48 行)
debug: 已成功加载 http://localhost:1753/Scripts/avalon/pager/avalon.pager.js?bust=1431314362934
avalon.js (第 48 行)
debug: 已成功加载 http://localhost:1753/Scripts/avalon/dialog/avalon.dialog.html?bust=1431314362934
avalon.js (第 48 行)
debug: 已成功加载 http://localhost:1753/Scripts/avalon/avalon.getModel.js?bust=1431314362934
avalon.js (第 48 行)
debug: 已成功加载 http://localhost:1753/Scripts/avalon/button/avalon.button.css?bust=1431314362934
avalon.js (第 48 行)
debug: 已成功加载 http://localhost:1753/Scripts/avalon/button/avalon.button.js?bust=1431314362934
avalon.js (第 48 行)
debug: 已成功加载 http://localhost:1753/Scripts/avalon/loading/avalon.loading.html?bust=1431314362934
avalon.js (第 48 行)
debug: 已成功加载 http://localhost:1753/Scripts/avalon/dropdown/avalon.dropdown.html?bust=1431314362934
avalon.js (第 48 行)
debug: 已成功加载 http://localhost:1753/Scripts/avalon/pager/avalon.pager.html?bust=1431314362934
avalon.js (第 48 行)
debug: 已成功加载 http://localhost:1753/Scripts/avalon/loading/avalon.loading.bar.html?bust=1431314362934

**Comment by 493409332** [comment]
好的我去写个例子

**Comment by RubyLouvre** [comment]
https://github.com/RubyLouvre/avalon/commit/75cb51cec3da0ecb04ccdeec3d0c9389c52c48cc
