### ISSUE TITLE
avalon什么时候可以支持一下ms-repeat filter的实现

### ISSUE THREAD

**Issue by skyline0705** [RubyLouvre/avalon#836]
实际上对于现在的代码，我可能会用
``` html
<li ms-repeat-item="getSelected(items)"></li>
```
但是这种方式在items进行修改之后并没有触发repeat-item数目的变化，如果针对每一个需要repeat的都去实际声明一个数组，资源耗费还是比较大的

谢谢

**Comment by skyline0705** [comment]
或者如果针对上面getSelected(items)这种情况也能在触发items变更时，li节点的repeat同步更新，这样就省去每需要一个特定repeat都要声明一个array的情况了

**Comment by RubyLouvre** [comment]
不支持，因为这样会生成一个中间的数组，这数组由于不在VM上，因此无法处理。

avalon要求所有操作资源都在VM中

**Comment by skyline0705** [comment]
那能否针对getSelected(items)这种形式进行词法分析，在items进行变化的时候出发li repeat的变化呢？

**Comment by RubyLouvre** [comment]
不行，以后的升级路线是减少DOM操作，而不是对ms-repeat支持过滤器

**Comment by 178220709** [comment]
但是确实是数据改变了啊,items发生了变化,dom跟随变化不是很自然的事情么?
减少dom操作是什么意思?

**Comment by RubyLouvre** [comment]
getSelected要看你的内部是怎么实现的，不能返回一个新数组，只能对原来的监控数组进行处理
