### ISSUE TITLE
oniui 的api页面在mac chrome下cpu狂飙

### ISSUE THREAD

**Issue by hizhengfu** [RubyLouvre/avalon#838]
mac probook
chrome 42
打开
http://ued.qunar.com/oniui/index.html#pages/apis/index.html
这个页面，cpu使用就开始疯狂了。占用直接飙到120%。关闭后恢复。应该是什么地方处理有问题吧。
![image](https://cloud.githubusercontent.com/assets/446359/7605384/7ce5fb54-f981-11e4-89f4-c0e3546acb5e.png)

**Comment by RubyLouvre** [comment]
看你使用的是什么组件了

**Comment by RubyLouvre** [comment]
我的这个官网是个单页应该,至少十万个绑定

**Comment by weeksun23** [comment]
十万个绑定啊，牛逼

**Comment by RubyLouvre** [comment]
因为没有后台,只好全部放到一个页面加iframe搞定
