### ISSUE TITLE
input type为number时, 外部为input赋值无效?

### ISSUE THREAD

**Issue by 178220709** [RubyLouvre/avalon#840]
avalon/examples/duplex3.html
给input加上type="number" , 上面赋值改为数字 ,即可看到效果.
avalon版本 : 1.43 built in 2015.5.12

**Comment by RubyLouvre** [comment]
不支持number, 只支持text, textarea, password, hidden, select, radio, checkbox

**Comment by 178220709** [comment]
不太理解,既然可以绑定duplex,为什么不能顺便监控changed事件呢?

**Comment by RubyLouvre** [comment]
<input type="number"/>只有一部分浏览器支持,它的解发机制与HTML4的不太一样

**Comment by 178220709** [comment]
原来是这个原因,
建议加个warning,因为我感觉既然duplex生效,顺便监听changed是很自然的一种开发思路
倒是没想到是底层浏览器的问题,调试了老半天...
