### ISSUE TITLE
avalon debug提示错误

### ISSUE THREAD

**Issue by dan0314** [RubyLouvre/avalon#842]
![1](https://cloud.githubusercontent.com/assets/7309546/7627065/f377dd28-fa44-11e4-8797-c33c561b1920.png)
控制台输出
![2](https://cloud.githubusercontent.com/assets/7309546/7627067/03f61fe8-fa45-11e4-970c-5364cf376769.png)
js页面typeof
![3](https://cloud.githubusercontent.com/assets/7309546/7627072/121b4eb8-fa45-11e4-97bb-3f3a92481d3d.png)
jsp页面

hotels.resultList可以进行循环 控制台一直提示 hotels.resultList只能为数组或对象

**Comment by RubyLouvre** [comment]
typeof 碰到null 正则 也是object啊

**Comment by dan0314** [comment]
![18_9a cdotg tsiycqb7k](https://cloud.githubusercontent.com/assets/7309546/7627978/0cfe1fea-fa50-11e4-8363-85eb3b4a3623.png)
js部分
![b 9 t6ok r1sar k 2lxi j](https://cloud.githubusercontent.com/assets/7309546/7627982/13c900c4-fa50-11e4-9002-214bbf72e58f.png)
控制台输出 

请无视那鬼一样的涂鸦……喵″

**Comment by dan0314** [comment]
![7lki398zgbt_ 0ftmkp 89s](https://cloud.githubusercontent.com/assets/7309546/7628077/1c579bf0-fa51-11e4-9bbb-1cfd4fd94493.png)
![i f t y2 9z kzea1i69j](https://cloud.githubusercontent.com/assets/7309546/7628079/2073a92c-fa51-11e4-90b1-f0aa5a1c32e2.png)

**Comment by RubyLouvre** [comment]
你的hotels是动态添加的吧

**Comment by dan0314** [comment]
…………………………………………

**Comment by Aladingding** [comment]
..........................................................................................................

**Comment by dan0314** [comment]
这都可以………………………………

**Comment by weeksun23** [comment]
看不懂

**Comment by RubyLouvre** [comment]
分正不用管它;想忽略所有调试信息,可以
```
avalon.config({debug: false})

```
