### ISSUE TITLE
avalon和微信JS-SDK冲突，导致其失效

### ISSUE THREAD

**Issue by Canox3** [RubyLouvre/avalon#845]
微信JS-SDK是微信提供给针对微信开发的网页js集成工具包

JS-SDK的说明文档：
http://mp.weixin.qq.com/wiki/7/aaa137b55fb2e0456bf8dd9148dd613f.html#.E6.A6.82.E8.BF.B0

调用微信的示例如下：
http://www.weizhile.cn/sample.php

调用微信的示例并加入avalon示例如下：
http://www.weizhile.cn/sampleandavalon.php

没有avalon运行正常
加入avalon以后console中直接给出wx is not defined的结果，导致完全无法使用微信的JS-SDK
这样无法在微信的环境中正常用avalon开发

**Comment by RubyLouvre** [comment]
自己排查一下到底是什么问题，没有开发环境

**Comment by Canox3** [comment]
应该是加载器的冲突
具体解决办法：修改js引用循序，微信的JS-SDK必须在引用avalon之前调用。

**Comment by RubyLouvre** [comment]
ok

**Comment by Leagueen** [comment]
遇到了这个问题
