### ISSUE TITLE
同一个页面的不同视图之间通信使用$watch和$fire就可以了，但是不同页面之间不同视图如何通信呢？

### ISSUE THREAD

**Issue by xhanglizhu** [RubyLouvre/avalon#850]
同一个页面的不同视图之间通信使用$watch和$fire就可以了，但是不同页面之间不同视图如何通信呢？
尝试未果。

**Comment by RubyLouvre** [comment]
这个做不到,页面关了没有,除非你保存到后端数据或本地储存上;这就不是avalon的职责范围;


如果你使用express.js 可以使用flash中间件做到

**Comment by xhanglizhu** [comment]
@RubyLouvre 好的，感谢回复。
