### ISSUE TITLE
与另外一个baidu的图表框架echarts好像有冲突，或者我使用有问题？

### ISSUE THREAD

**Issue by penweizgx** [RubyLouvre/avalon#851]
页面引入JS冲突：
< script src="http://echarts.baidu.com/build/dist/echarts.js"></script>
< script src="http://rubylouvre.github.io/mvvm/javascripts/avalon.js"></script>  
< script type="text/javascript">
        // 路径配置
        require.config({
            paths: {
                echarts: 'http://echarts.baidu.com/build/dist'
            }
        });
        
        // 使用
        require(
            [
                'echarts',
                'echarts/chart/bar' // 使用柱状图就加载bar模块，按需加载
            ],
            function (ec) {
                // 基于准备好的dom，初始化
..........................）
然后再页面加载的时候出问题了：
![image](https://cloud.githubusercontent.com/assets/6983487/7773721/ee66897a-00d8-11e5-9681-8f14ffafeecb.png)

**Comment by RubyLouvre** [comment]
不行吧，echart不能引入页面，而是通过avalon的AMD加载器引入

http://echarts.baidu.com/doc/doc.html#%E5%BC%95%E5%85%A5ECharts1
