### ISSUE TITLE
请求公开 scanExpr 方法

### ISSUE THREAD

**Issue by darklx** [RubyLouvre/avalon#852]
做 avalon 插件的时候，需要解析复杂的表达式，parseExprProxy 需要传入 tokens 参数，但是这个 tokens 参数需要通过 avalon 内部的 scanExpr 方法才可以获得。
现在是手动改的 avalon 源码。

希望这个方法可以公开，因为 parseExprProxy 是公开的，那么它所接受的参数，也应当有公开的方法可以传入。

谢谢！

**Comment by RubyLouvre** [comment]
直接用parseExprProxy 不够吗， scanExpr 以后可能大改动；易变的东西不能给你们用
