### ISSUE TITLE
能用avalonjs做webim吗？

### ISSUE THREAD

**Issue by oooodo** [RubyLouvre/avalon#853]
求教

**Comment by RubyLouvre** [comment]
是微信吗？应该都能吧。
看一下这里的案例
http://avalonjs.github.io/#zh/exhibitions/index.html

还有这里（要往下拉一下滚动条才看到）
http://ued.qunar.com/oniui/home.htm

**Comment by oooodo** [comment]
单页面引用 (SPA), 被定义成一个目的在于提供一种接近桌面应用程序的流畅用户体验单web页面应用程序，或者说网站. 在一个SPA中, 所有必需的代码 – HTML, JavaScript, 以及 CSS – 都是在单页面加载的时候获取，或者相关的资源被动态的加载并按需添加到页面中, 这常常是在响应用户动作的时候发生的. 尽管现代的Web技术（比如那些在HTML5中引入的技术）提供了应用程序中各自独立的逻辑页面相互感知和导航的能力，页面却不会在过程中重新加载任何端点，或者将控制转到另外一个页面. 同单页面应用程序的交互常常设计到同位于后台的web服务器的动态交互.

那么拿这项技术同 ASP.NET 的母版页Master Pages相比呢? 诚然 ASP.NET 的母版页让你可以为自己应用程序里的页面创建一个一直的布局。一个单独的母版页就可以定义好你想要在整个应用程序中的所有页面（或者一组页面）上应用的外观和标准动作. 然后你就可以再来创建你想要展示的内容各自独立页面. 当用户发起对内容页面的请求时，它们会将来自母版页的布局和来自内容页面的内容混合到一起，产生输出.

当你深入研究SPA和ASP.NET母版页实现这两者之间的不同时，你就开始会意识到它们之间相同的地方多于不同的地方——那就是SPA可以看做是一个简单的装着内容页面的外壳页面，就像是一个母版页, 只是SPA中的外壳页面不能像母版页那样根据每一个新的页面请求来重新装载和执行.

也许“单页面应用”是个不幸运的名字（像唐娜`程一样），让你相信这个技术不适合开发需要拓展到企业级，可能 包含上百页面以及数千用户的Web应用。

本文的目标是基于单页面应用程序开发出拥有数百页的内容，包括认证，授权，会话状态等功能，可以支持上千个用户的企业级应用。

司徒大大，能不能通过这个角度来阐述下怎么用avalon来做一些这样的应用？
因为任何一项新的思想和框架的产生都需要各方的人去推动，而在推动的过程中，又需要不断的刺激来巩固开发者的信心。
在推动的过程中，又需要很多的知识点，比如我需要用avalon来架构一个应用，那我需要的不只是avalon，我还需要avalon的三柱臣，缺一不可，因为只有这样，架构的应用才是系统性的，可用的，有价值的。而我目前能够搜到的一些avalon应用的案例，都是单个知识点，而不能总体的，系统性的组织在一起。
其实我刚接触avalon3天，对于使用jquery频繁的人来说，突然间介入avalon，总感觉到无所是从，不知道该从何下手，但是我特别认同你博文里面的think in avalon，摘抄如下：

1.不要设计，也不要通过DOM操作去改变你的页面

你用jQuery去设计一个页面，并让它动起来。这是因为jQuery就是让一切简单的事情变复杂的罪魁祸首。

但是用avalon，你必须从零开始去构思你的架构。"我有这么一些DOM，我想要它去做XXX"，不，你不该这么想，你首先应该想到你要完成的是什么， 然后去设计你的整个应用，最后去设计你的view。

2.不要在avalon的代码里混杂着jQuery代码

不要首先想到用jQuery去解决问题。首先想到的应当是avalon的VM与$watch。 你刚开始学avalon的时候jQuery特别诱人，所以我才建议新的avalon开发者坚决不用jQuery， 至少等到你能够按MVVM的方式去处理问题时再说吧。

3.要一直想着架构

首先你要明白，SPA(single-page applications)也是applications。不是零散的网页。 因此我们不能仅仅从客户端开发者的角度去考虑，还需要把自己当成服务器端工程师。 我们要想这把我们的application分离成独立的，可扩展的，可供测试的组件。

为了达到这一点，你要把你重复利用的视图独立成一个模板，通过ms-include引入。 你要把你经常用到的方法，封装成VM的一个个方法或过滤器。 你要学会切割页面 ，让它交由不同的ms-controller来处理。 你要学会使用mmRouter，路由器是你掌握SPA的证明。 你要学会用ms-widget封装UI组件，这是对你未来的投资！

**Comment by oooodo** [comment]
请问司徒大大，avalon在去哪儿都具体应用在哪些模块，前端的页面不知道是不是也是学习的一个好渠道？

**Comment by RubyLouvre** [comment]
许多模块，基本上是内部应用
