### ISSUE TITLE
avalonjs可以监听一个对象下面的所有方法和属性吗？（包括对象下的对象）

### ISSUE THREAD

**Issue by kiner-tang** [RubyLouvre/avalon#854]
使用$watch("$all")可以监控一个对象下所有的属性的数据变化，但是，如果该属性的值本身就是一个对象，则没办法监控。而在实际应用中，数据往往是从后台传回，一般是比较复杂的json对象，进场会出现对象中包含对象的情况，这样，就需要对整个对象进行监控了，请问有方法可以解决这个问题吗？

**Comment by RubyLouvre** [comment]
没有

**Comment by kiner-tang** [comment]
那请问有没有什么方法可以让我主动更新界面的，也就是说，我一调用那个方法就可以根据model里面的数据渲染页面

**Comment by RubyLouvre** [comment]
avalon.scan需要传入两个参数， 详见 http://avalonjs.github.io/#zh/apis/index.html
