### ISSUE TITLE
avalon.js 事件绑定【ms-on-*】

### ISSUE THREAD

**Issue by behind2** [RubyLouvre/avalon#855]
看图说话吧，如下：
![image](https://cloud.githubusercontent.com/assets/7901705/7829900/9549b926-0479-11e5-8dba-2003a08995a7.png)
运行结果：
![image](https://cloud.githubusercontent.com/assets/7901705/7829985/6b1a022c-047a-11e5-881e-f01a001d9099.png)

-----------------------------------------------------华丽的分割线--------------------------------------------------------------- 
稍微做下改动：
![image](https://cloud.githubusercontent.com/assets/7901705/7830015/b3636550-047a-11e5-8e0a-a17a358833f7.png)
运行结果：
![image](https://cloud.githubusercontent.com/assets/7901705/7829997/99eba86c-047a-11e5-98cf-0f247c45796c.png)

<br />
>如此一看，事件的注册并没有按照指定期望的顺序添加到回调队列里。
其他：Chrome 43， avalon.js 1.43

**Comment by behind2** [comment]
```javascript
<!DOCTYPE HTML>
<html>
    <head>
        <title>ms-on</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <script src="avalon.js" ></script>
        <script>
            avalon.define({
                $id: "xxx",
                fn: function() {
                    console.log("11111111")
                },
                fn1: function() {
                    console.log("2222222")
                },
                fn2: function() {
                    console.log("3333333")
                }
            })
        </script>
    </head>
    <body>

        <div ms-controller="xxx" ms-on-mouseenter-3="fn" ms-on-mouseenter-2="fn1" ms-on-mouseenter-1="fn2" style="width:100px;height:100px;background: red;">
        </div>

<!--         <div ms-controller="xxx" ms-on-mouseenter-1="fn2" ms-on-mouseenter-2="fn1" ms-on-mouseenter-3="fn" style="width:100px;height:100px;background: red;">
        </div> -->

    </body>
</html>
```

**Comment by RubyLouvre** [comment]
chrome与firefox下Number(param)得到的值不一样
