### ISSUE TITLE
关于配合r.js打包的优化建议

### ISSUE THREAD

**Issue by VaJoy** [RubyLouvre/avalon#856]
使用了r.js之后，各入口文件里还得继续配置require.config来指定模块路径，否则文件路径将获取不正确。

如果是 requireJS 的话，只要用上 r.js 在 build.js 里写好配置之后，入口文件里是无需再配置require.config的。可以参考我以前的[这篇文章](http://www.cnblogs.com/vajoy/p/3920163.html)

正美看下能否优化下，让我们使用r.js的时候，入口文件无须再配置 require.config 呢

**Comment by gogoyqj** [comment]
如果要打包，截止目前，就requirejs的loader取代avalon的loader吧
