### ISSUE TITLE
object.prototype添加自定义方法后，avalon报错

### ISSUE THREAD

**Issue by peterPan-1989** [RubyLouvre/avalon#858]
![image](https://cloud.githubusercontent.com/assets/6194604/7876068/5f5ee5ea-05f8-11e5-8b1d-fd1619795eb0.png)
我在object.prtotype里面添加了一个自定义方法，但是modelFactory里面的for循环把我的自定义方法bind了一下，导致出错。

**Comment by RubyLouvre** [comment]
本来就不能在Object.prototype上添加;那你自己在for循环搞一下吧

**Comment by peterPan-1989** [comment]
请问为什么不能在Object.prototype里面添加函数？？

**Comment by peterPan-1989** [comment]
@RubyLouvre 为什么不能在Object.prototype上添加？会有什么不良影响吗？你叫我在for循环搞一下是指checkout一个分支fix了这个bug吗？

**Comment by RubyLouvre** [comment]
Object.prototype添加方法就会页面上所有对象上添加了这方法了!这是对整个原型链的污染  这是常识啊；
http://www.th7.cn/web/js/201503/94002.shtml
