### ISSUE TITLE
ms-repeat对某些为$skipArray里面的数组变量执行出错

### ISSUE THREAD

**Issue by peterPan-1989** [RubyLouvre/avalon#860]
![image](https://cloud.githubusercontent.com/assets/6194604/7908030/275c263a-0873-11e5-9c4f-2a49d59a6f85.png)
在使用avalon.datepicker时，datepicker对weekNames放进$skipArray，这样导致ms-repeat解释时报错。avalon版本为1.43。

**Comment by RubyLouvre** [comment]
你应该使用打tag的版本，而不是直接下载  https://github.com/RubyLouvre/avalon/blob/1.4.3/avalon.js

**Comment by peterPan-1989** [comment]
@RubyLouvre 问题来了，这个tag的shim版本的ready队列函数是不正常的。。。。只能自己复制解决了
