### ISSUE TITLE
虚拟DOM实现方案

### ISSUE THREAD

**Issue by RubyLouvre** [RubyLouvre/avalon#861]
实现一个VTree，作为缓冲层。其主要组成单元为VElement。VElement有一个dirty属性，为true时就执行其 tasks刷新队列。

updateVTree 用于更新VTree
updateDTree 用于更新DOM Tree
创建 VText VDocumentFragment VElement VComment 这几个构造器
VTree 就是nodeName为HTML的VElement

扫描系统应该同支持扫描DOM Tree与VTree
HTML字符串与虚拟DOM树的互转(比如后端渲染, 虚拟文档碎片)
真实节点与虚拟节点的互转
真实节点与虚拟节点的互动
以最少步骤更新DOM结构

**Comment by simphp** [comment]
这是要有大的版本升级吗？

**Comment by RubyLouvre** [comment]
当前的扫描流程  scanTag --> scanAttr --> scanNodeList --> scanText --> scanElement --> scanTag/scanVTag

**Comment by RubyLouvre** [comment]
uid生成策略,是基于页面结果,而不是高度随机不重复的数字

v-repeat0.12.23.3243.234:xxxxx:end
```
<html>
注释节点不移动
<body>
  <ul><li ms-repeat=array>{{}}</li></ul>

</body>
```

**Comment by RubyLouvre** [comment]
VM只能修改VTree
```
vm.array = [1,2,3,4] 生成 
<span vid=1> <span vid=2> <span vid=3> 
及 <span id=1> <span id=2> <span id=3> 
再次对vm.array 赋值 [4,5,6,7] 生成 
<span vid=4> <span vid=5> <span vid=6> 
现在需要修正成<span vid=1> <span vid=2> <span vid=3> 
```

**Comment by bzksx2** [comment]
如何加快dom节点的扫描速度？目前页面的dom节点数过多的话，扫描是很慢的，白屏现象严重。而且使用oniui组件，如果页面上创建较多的组件(>50)，页面渲染也是极慢的，个人觉得对avalon.scan()部分的代码太需要优化了

**Comment by RubyLouvre** [comment]
那你提出优化方案

**Comment by bzksx2** [comment]
能力有限啊，只是调试的时候，发现这部分耗时严重，觉得需要优化，也许只是愚见

**Comment by darklx** [comment]
戏说一下楼上两位对话：
@bzksx2 ：我觉得页面上组件多了页面渲染慢，能不能优化下？
@RubyLouvre ：你行你上啊
@bzksx2 ：没你行，你牛逼，我只是提一个反馈&意见
