### ISSUE TITLE
 使用模版和路由遇到的问题：Unhandled promise rejection 

### ISSUE THREAD

**Issue by oooodo** [RubyLouvre/avalon#862]
全局vm和require
require.config({
	baseUrl: 'js/', //相对于index.html页面文件的地址
	paths: { //这里配置的地址，都是相对于上方的baseUrl的
		avalon: 'avalon',
		mmHistory: 'mmHistory',
		mmRouter: 'mmRouter',
		mmState:"mmState",
		mmPromise:'mmPromise'
	},
	shim: {
		avalon: {
			exports: "avalon"
		},
		mmHistory: {
			deps: ['avalon']
		},
		mmRouter: {
			deps: ['avalon']
		},
		mmState:{
			deps: ["avalon"]
		},
		mmPromise:{
			deps: ["avalon"]
		}
	}
});

var global = avalon.define({
	$id: 'global',
	title:'crm',	
	$skipArray: []
});
////
//路由状态
////
require(['mmState','mmHistory','mmPromise','mmRouter'], function ($) {	
	//首页
	avalon.state("index", {
		controller: "global",
		url: "/",
		views: {
			"container": {				
				templateUrl: 'clues/clues.html',		
				controllerUrl: ["leads.js"]
			}
		},
		onEnter:function(){
			console.log(global);
		}
	});

	// 启动路由
	avalon.history.start({
		fireAnchor: false
	});

	// 扫描
	avalon.scan();
});
html：
<html xmlns="http://www.w3.org/1999/xhtml" id="global" ms-controller="global">

	<head>
		<meta charset="utf-8">
		<title>{title}</title>
		
		<script src="js/avalon.js"></script>
		<script src="js/base.js"></script>
	</head>

	<body>		
		<div class="container" id="container" ms-view='container'>			
			
		</div>
      </body></html>
日志：
 debug: 正准备加载 http://127.0.0.1:8020/crm/js/mmState.js
avalon.js:48 debug: 正准备加载 http://127.0.0.1:8020/crm/js/mmHistory.js
avalon.js:48 debug: 正准备加载 http://127.0.0.1:8020/crm/js/mmPromise.js
avalon.js:48 debug: 正准备加载 http://127.0.0.1:8020/crm/js/mmRouter.js
avalon.js:48 debug: 已成功加载 http://127.0.0.1:8020/crm/js/mmState.js
avalon.js:48 debug: 已成功加载 http://127.0.0.1:8020/crm/js/mmHistory.js
avalon.js:48 debug: 已成功加载 http://127.0.0.1:8020/crm/js/mmPromise.js
avalon.js:48 debug: 已成功加载 http://127.0.0.1:8020/crm/js/mmRouter.js
avalon.js:48 begin transitionTo index from unknown
base.js:83 Object {title: (...), $id: "global", $model: Object, $events: Object, $watch: function…}
avalon.js:48 debug: 正准备加载 http://127.0.0.1:8020/crm/js/leads.js
avalon.js:48 debug: 已成功加载 http://127.0.0.1:8020/crm/js/leads.js
mmState.js:486 Unhandled promise rejection Promise {done: function, fail: function, $then: function, [[PromiseStatus]]: "rejected", [[PromiseValue]]: TypeError: Cannot read property '$vmodels' of undefined}
127.0.0.1/:1 Resource interpreted as Font but transferred with MIME type text/html: "http://127.0.0.1:8020/crm/css/font/fontawesome-webfont.woff?v=3.0.1".
模版上的信息加载不出来？麻烦给看下？这是什么错误？

**Comment by oooodo** [comment]
controller的定义在最顶部：
<html xmlns="http://www.w3.org/1999/xhtml" id="global" ms-controller="global">

**Comment by oooodo** [comment]
\<html id="global" ms-controller="global">

**Comment by gogoyqj** [comment]
。。。贴leads.js，你看你的controller定义跟例子一样么。。。

**Comment by oooodo** [comment]
少了这么一段：
return avalon.controller(function($ctrl) {
		$ctrl.$vmodels = [vm];
		$ctrl.$onEnter = function(param, rs, rj) {			
		}
		$ctrl.$onRendered = function() {}
	});

**Comment by gogoyqj** [comment]
对啊，必须返回一个avalon.controller(fn) 或着哪怕一个空对象啊
