### ISSUE TITLE
IE 6的性能问题 特别慢，请问有什么解决方案吗

### ISSUE THREAD

**Issue by cshua** [RubyLouvre/avalon#864]
在项目中使用到了AVALON，在chrome下运行没有问题，使用IE6的时候，特别特别的慢。通过测试，简单一点的页面，就一个列表，AJAX查询数据绑定，需要5秒，复杂一点的需要10到30秒。通过测试发现主要时间浪费在scan上面。请问有什么解决的方法吗？

**Comment by RubyLouvre** [comment]
简化你的结构,对象层次不能太深
