### ISSUE TITLE
ms-duplex 和 select 的应用疑问

### ISSUE THREAD

**Issue by treenew** [RubyLouvre/avalon#866]
```html
            <select ms-duplex="args.state">
                <option value="">所有</option>
                <option value="2">正常</option>
                <option value="1">禁止登录</option>
                <option value="0">尚未初始化</option>
            </select>
```
以上代码，如何在 args.state 值为 null 时和 *字符串空值* 都会选中第一个选项？
要不然我一定要加上这样的代码
```js
if(!model.state) model.state = "";
```

**Comment by treenew** [comment]
然后最新版的 avalon.shim.js 有BUG。
数据第一次填充可以正确渲染。假设 table 下10 行，那是正确的。
第二次渲染就错误了。比如我将数据变成5行，显示的还是 10行数据

**Comment by RubyLouvre** [comment]
例子不全,无法调试

**Comment by RubyLouvre** [comment]
必须的，因为option.value总是为字符串，字符串不等于null，这是常识

**Comment by treenew** [comment]
我当然知道这是常识了……后台 Model 对象使用强类型的，无法使用空字符串表示一个非字符串的类型。
能否告诉我在源码哪里可以修改这个判定呢？

**Comment by treenew** [comment]
找到了。 avalon.shim.js 第 3813 行。
将源码
```
val = val && val.$model || val
```
改为
```
val = val && val.$model || val || ""
```

**Comment by treenew** [comment]
这明明是 bug，司徒还不说的那么正经。
如果是null 值，下面的
```javascript
val = Array.isArray(val) ? val.map(String) : val + ""
```
将会输出 "null" ，是一个字符串。。。“      "null" ”

**Comment by RubyLouvre** [comment]
人家传一个0,false进来怎么办 ,你的数据必须直接处理才能赋给VM

**Comment by treenew** [comment]
这是 select，若是 false，0，字符串空值，null，理论上来讲，应该是表示同一个意思（在 select 的值中）。个人理解，你说的也没错。
我的意思是，
···
var p = null;
var str = p + "";
···
这样的代码，业务角度上其实我str要的是 ""，而不是"null"，但执行结果确实 "null"。不过你说的对，false和0不应该被忽略，代码应该改成
```
            val = val && val.$model || val
            if (val === null) val = "";
```
