### ISSUE TITLE
模板切换和VM的问题

### ISSUE THREAD

**Issue by 372987001** [RubyLouvre/avalon#868]
如`<div ms-controller="test" ms-include-src="a.tpl"></div>`
由于业务原因，VM和对应的模板要一并切换，现在做法是切换时`delete avalon.vmodels['test']`, 然后在对应模块的js中重新`avalon.define('test', function(vm){})`, 并同时切换模板，然后重新扫描，但现在问题是模板切换过来了，数据没有更新，依旧是老的数据，请问这样的思路合理吗？还是用mmstate可以解决问题？
.

**Comment by RubyLouvre** [comment]
不需要啊
```html
<div ms-controller="mainVM">
  <div ms-include-src="href"></div>
</div>
avalon.define({$id: "mainVM", href:href})
avalon.define({$id: "aVM", })
avalon.define({$id: "bVM", })

a.html

<div ms-contoller="aVM">
 {{a}}
</div>

b.html

<div ms-contoller="bVM">
 {{b}}
</div>

```

每个模板上定义一个ms-controller
然后早早定义好所有的VM

**Comment by 372987001** [comment]
因为涉及到6个tab页，每个tab页结构是上面是搜索条件，下面是数据列表，结构大致相同，但业务不太一致，为了更好的业务维护扩展，就将6个tab页进行了拆分，每个tab页作为一个模块存在，因业务相似，所以定义了一个公用的VM, 模块内部结构就是一个VM.js和两个模板
`index.html
<div>
    <ul>
        <li>a</li>
        <li>b</li>
        <li>c</li>
        <li>d</li>
        <li>e</li>
        <li>f</li>
    </ul>
    <div ms-include-src="searchTemplate" ms-controller="searchController"></div> 
    <div ms-controller="listController">
         <div ms-widget="pager,pager1,$pager"></div>
         <div ms-include-src="listTemplate"></div>
         <div ms-widget="pager,pager2,$pager"></div>
    </div> 
</div>

baseVM.js:
define([], function(){
    return{
                  searchVM:{
                        a: "",
                        b: ""
                  },
                  listVM:{
                        data: [],
                        totalItems: 0,
                        $pager:{
                              onJump: function(){}
                        }
                 }
             }
})

模块A，（其他模块类似）
a.js
define([
    'avalon',
    'baseVM',
    'text!search.html', 
    'text!list.html'], 
function(avalon, base, searchHTML, listHTML){
     avalon.templateCache['a_search'] = searchHTML;
    avalon.templateCache['a_list'] = listHTML;
    
    return {
           init: function(){
                avalon.vmodels['searchController'] && delete avalon.vmodels['searchController'];
                avalon.vmodels['listController'] && delete avalon.vmodels['listController'];
               
                 var vmSearch = avalon.define(avalon.mix(base.searchVM, {
                             $id: "searchController",
                             $dataUrl: dataUrl
                 }));
                 var vmDatalist = avalon.define(avalon.mix(baseVM.listVM, {
                             $id: "listController",
                 }));
                
                //模板切换，扫描绑定等动作
          }
    }
})


`

**Comment by RubyLouvre** [comment]
用我的方式就行了,不用多想
