### ISSUE TITLE
1.44avalon.shim.js版本bug

### ISSUE THREAD

**Issue by liuwei3230** [RubyLouvre/avalon#874]
替换项目中的1.42版本，结果出现initCallbacks未定义，，我看了下avalon.shim.js版本里的源码查找了下这个变量，似乎没有定义咧

**Comment by RubyLouvre** [comment]
请使用下这里的版本 https://github.com/RubyLouvre/avalon/releases

**Comment by liuwei3230** [comment]
ok,好了，谢谢!
