### ISSUE TITLE
看源码的一些不解

### ISSUE THREAD

**Issue by peterPan-1989** [RubyLouvre/avalon#888]
w3c，world wide web，万维网
dom，Document Object Model  页面对象模型
看了一下源码，发现源码有个地方var W3C = window.dispatchEvent ，源码也有很多地方用到了w3c来做判断
不解的有
1.为什么用dispatchEvent来判断是否w3c，这是一个dom2的标准
2.源码多处用到w3c来做验证，是否是用来判断是否满足dom1，2，3，4标准吗？还是仅仅是dom2标准

**Comment by RubyLouvre** [comment]
符合W3C标准的浏览器为IE9+  ,firefox, chrome, 在IE9直接用window.dispatchEvent 就能判定了
