### ISSUE TITLE
希望修改异常捕捉的代码

### ISSUE THREAD

**Issue by taoliujun** [RubyLouvre/avalon#889]
在avalon.modern.js的line 4725左右的捕捉异常的代码：
log("执行[" + id + "]模块的factory抛错： " + e); //会默认执行e.toStrong()，只看到报错信息，无法追踪上下文。
希望简单的改成：
log("执行[" + id + "]模块的factory抛错： " , e);

**Comment by RubyLouvre** [comment]
已改,在下一次发布合并到主干
