### ISSUE TITLE
1.4.4的内存泄漏问题

### ISSUE THREAD

**Issue by zhangchunlin** [RubyLouvre/avalon#890]
我这里发现1.4.4解决了之前的一个数组刷新问题,但是使用了1.4.4以后又发现有一个内存泄漏问题,我这里的现象是点击一个表格次数多了以后会出现内存占用急剧上升,然后CPU占用也急剧上升最终在chrome里会没有反应

表格项的点击函数为:
```
        item_click : function(i) {
            vm.item_click_index = i
            var item_select = vm.item_list[i].$model
            vm.item_select = item_select
            vm.update_can_submit_add()
        },
```
其中vm.item_select = item_select 这一行去掉以后就不会出现内存泄漏的问题

用二分查找找改出此问题的版本,最终定位在这两个:

commit 3fc95bf3ec9ebbc2a5eaad5f6ea8c6fffefd1158
Author: qincheng <qincheng@unitedstack.com>
Date:   Tue Jun 16 09:08:13 2015 +0800

    update avalon

commit ea2ebf547f732cc662ea3f72827f191ec415e56e
Author: RubyLouvre <cheng19840218@gmail.com>
Date:   Mon Jun 15 19:26:27 2015 +0800

    开始1.4.5的新里程

其中ea2ebf547f732cc662ea3f72827f191ec415e56e没办法测试,因为没办法正常运行,所以没办法知道是不是这个版本改出来的,3fc95bf3ec9ebbc2a5eaad5f6ea8c6fffefd1158是第一个确认重现泄漏问题的版本

本来想要在 runjs 上创建一个最小化例子,但是没办法重现,只有在我这里比较复杂的页面上能重现

**Comment by RubyLouvre** [comment]
看来是计算属性了BUG了,现在计划去掉定时器

**Comment by zhangchunlin** [comment]
@RubyLouvre 看起来知道原因了哈,太好了,如果有改好的版本可以给我测试验证一下

**Comment by RubyLouvre** [comment]
https://github.com/RubyLouvre/avalon/commit/614b378c21f256995024480fcb20641b3e99dbb3

搞定了

**Comment by zhangchunlin** [comment]
我试过了最新的版本,还是有这个问题,仍然内存会暴涨,cpu也暴涨

**Comment by RubyLouvre** [comment]
?

**Comment by RubyLouvre** [comment]
https://github.com/RubyLouvre/avalon/commit/cdf043d58ca97bc5c9f3b265fb2ce1481f0c88cb

试试这个

**Comment by zhangchunlin** [comment]
最新版本还是一样会出现这样的问题,我之后再尝试想想看如何能在runjs上重现这个问题

**Comment by zhangchunlin** [comment]
终于在runjs上重现了这个问题,请看: http://sandbox.runjs.cn/show/zhtwiot4
重现方法就是反复点击上面的表格项,不用很多次就能重现这个问题了

**Comment by RubyLouvre** [comment]
搞定了，这出现在复杂绑定上

**Comment by zhangchunlin** [comment]
@RubyLouvre  avalon.min.js 没更新? 我刚才测了还是有,看了一下这个文件没有更新

**Comment by zhangchunlin** [comment]
拿最新的 avalon.js 测试确实没有问题了
