### ISSUE TITLE
关于迷你教程中的[非监控属性]的问题

### ISSUE THREAD

**Issue by Runaria** [RubyLouvre/avalon#891]
页面地址如下：
http://avalonjs.github.io/#zh/concepts/unobservable.html

这个教程的示例代码中，click事件中有如下代码：
    
    vm.$aaa = vm.aaa = vm.bbb = vm.ccc = "change"

但是点击了按钮之后，只有aaa的改变同步到了dom中，bbb和ccc的值虽然变了但是dom没有更新

请问这是专门这样设定的，还是单纯的BUG了？

**Comment by RubyLouvre** [comment]
是专门这样设计,只同步视图一次
