### ISSUE TITLE
avalon loading导致ie10 ie11选择 文件-打印预览 打印空白

### ISSUE THREAD

**Issue by davidduwei** [RubyLouvre/avalon#892]
http://hotelued.qunar.com/oniui/loading/avalon.loading.ex.html
上为官网地址 同样存在此问题。
require("loading/avalon.loading")执行后 head中的avalon标签会添加<animate></animate>;此时打印预览显示始终为空白。
在html结构中将animate标签删除后即可打印预览

**Comment by RubyLouvre** [comment]
```html
 <style media="print">   animate{display:none} </style>
```

**Comment by davidduwei** [comment]
试过了
@media print{
 animate{display:none}
}不行。
发现是animate标签作祟，就直接粗暴的在Domready后将head中生成的avalon标签remove掉了就可以打印呢。

**Comment by RubyLouvre** [comment]
应该不支持 @media

**Comment by davidduwei** [comment]
@media ie11应该是支持的哦。其他样式生效。<style media="print">   animate{display:none} </style>同样试过也不行。不能够理解为啥avalon标签中含有animate会导致打印空白，之前也是一个元素一个元素的删除来排查原因， 最后才发现这个导致这种问题。测试环境在win7 ie11 以及兼容模式ie10 多台机器都存在这样问题 ie9是好的。
