### ISSUE TITLE
ms-focus   ms-visible="function()"  ms-click 发生冲突,是用法问题还是bug?

### ISSUE THREAD

**Issue by 178220709** [RubyLouvre/avalon#893]
ms-focus的vm事件修改一个flag, 而ms-visible="function()"里面的function会根据flag来返回,
ms-visible 这个div里面如果有个按钮 同时触发外部的ms-focus 和自己的ms-click
则自己的click不会生效.
这样说大家不好理解,我说下我的需求,
其实就是智能提示, 上面一个input输入框 focus和blur控制下面自动完成单词所在div的visible
而div里面的一个item click事件就是修改input输入值,同时触发blur,隐藏掉提示div
这样就会发生bug,后台只响应了blur方法,没有响应click方法.

演示demo:
http://jsbin.com/xilejovudo/1/edit?html,output
不触发blur  直接点击提示的item 生效,
如果焦点在input里面 则  只有blur生效
Ps:找不到最新的cdn ,就用老版代替,最新版也有这个问题

**Comment by zousandian** [comment]
@178220709  点击 div 前面先触发了 input 的 blur 事件的，导致 div 已经消失了，所以根本就没有触发 click 事件。加个延时就行了。
另外你写的代码也太冗余了。。改了一下看看是不是你要的效果
http://jsbin.com/vizosenexi/edit?html,output

**Comment by 178220709** [comment]
"导致 div 已经消失了"
visible应该控制的是display : none /block 吧 ,
隐藏之后 事件也没了?

**Comment by zousandian** [comment]
@178220709 不是事件没了，是在你点击之前就隐藏了，所以根本没有触发点击事件

**Comment by 178220709** [comment]
@zousandian 
明白了 
感谢解答
