### ISSUE TITLE
数组、ms-visible的问题，为何点击链接，对应的div不显示呢？

### ISSUE THREAD

**Issue by zinda2000** [RubyLouvre/avalon#894]
<!DOCTYPE HTML>
	<html>
	<head>
	<title></title>
	<script src="avalon.js"></script>
	</head>
	<body>
	<div ms-controller="hm">
		<div>
			<a ms-click="switchPage(0)" href="#">&gt;&gt; 1</a>
			<a ms-click="switchPage(1)" href="#">&gt;&gt; 2</a>
		</div>
		<div ms-visible="vm.toggle[0]">
			<h4>第1区</h4>
		</div>
		<div ms-visible="vm.toggle[1]">
			<h4>第2区</h4>
		</div>
	</div>
	<script>
	var vm = avalon.define({
		$id: "hm",
		toggle: [false, false],
		switchPage: function (n) { vm.toggle[n] = !(vm.toggle[n]);alert(vm.toggle[n]);}
	});
	</script>

	</body>
	</html>

**Comment by zinda2000** [comment]
toggle的成员如果是对象就可以了。但是简单的数组不能运行，会让人困惑。

**Comment by RubyLouvre** [comment]
连一个切换卡都写不好，还能让我说什么好呢！
这里的例子看过了没有  https://github.com/RubyLouvre/avalon/tree/master/examples ？！
这里的视频看过了没有 http://www.imooc.com/learn/270 ？！
avalon论坛上的基础教程看过了没有 http://www.avalon.org.cn/?number=20&category=1&from=20 ？！

```html
<!DOCTYPE HTML>
<html>
    <head>
        <title></title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <script src="avalon.js"></script>
    </head>
    <body>
        <div ms-controller="hm">
            <div>
                <a ms-repeat="array"  ms-click="switchPage($index)" href="javascript:void(0)">&gt;&gt; {{$index}}</a>
            </div>
            <div ms-repeat="array"  ms-visible="$index === curIndex">
                <h4>第{{$index}}区</h4>
            </div>
        </div>
        <script>
            var vm = avalon.define({
                $id: "hm",
                curIndex: 0,
                array: [1,2,3],
                switchPage: function (a) {
                    vm.curIndex = a;
                }
            });
        </script>

    </body>
</html> 
```

**Comment by RubyLouvre** [comment]
vm.toggle[n] = !(vm.toggle[n])

加上，你这里的是布尔，布尔当然无法监听
avalon的监听是基于对象的属性变化的

true不是对象，当然监听不了

当数组的元素是对象时， 对 对象的属性进行改动 才会触发视图变动
