### ISSUE TITLE
循环一个数组对象时候，尝试交换元素位置出现的问题

### ISSUE THREAD

**Issue by paul-xia** [RubyLouvre/avalon#895]
<div ms-controller="demo">
		<p ms-repeat="list">aa: {{el.aa}}, bb: {{el.bb}}</p>
		<button ms-click="exChange">切换位置</button>

		<button ms-click="oExChange">另一个切换位置方法</button>

		<button ms-click="rightExChange">笨办法解决</button>
	</div>
	<script>
		var objArray = avalon.define('demo', function(vm){
		     vm.list =  [{aa:11,bb:11}, {aa:22,bb:22}, {aa:33, bb:33}];
		    

		      //对数组内元素交换位置exchange,第二次位置错误
		     vm.exChange = function(){
		     	vm.list.exchange(1,2);
		     };

		     //直接赋值，位置错误
		     vm.oExChange = function(){
		     	var arr = vm.list.newExchange(1,2);
		     	vm.list = arr;
		     }

		     //笨办法解决,但是会重置数组，开销大
		     vm.rightExChange = function(){
		     	var arr = vm.list.newExchange(1,2);
		     	vm.list.clear();
		     	vm.list = arr;
		     }
		});

		avalon.scan()

		Array.prototype.exchange = function(oldIndex, newIndex) {
			this.set(oldIndex, this.splice(newIndex, 1, this.$model[oldIndex])[0].$model);
		};

		Array.prototype.newExchange = function(oldIndex, newIndex) {
			var model = avalon.slice(this.$model);
			model[oldIndex] = model.splice(newIndex, 1, model[oldIndex])[0];
			return model;
		};
	</script>

**Comment by RubyLouvre** [comment]
```javascript

function swapArray(array, newIndex, oldIndex){
   var el = array.splice(oldIndex, 1)
   if(el.length){
     array.splice(newIndex, 0, e1[0])
   }
}
```
