### ISSUE TITLE
ms-on-keyup绑定在input上，如果是粘帖字符串上去，会执行两次

### ISSUE THREAD

**Issue by liminghui** [RubyLouvre/avalon#899]
如下面的change调用
===========

	<!DOCTYPE html>
	<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>ms-duplex2.0</title>
		<style type="text/css">
			td { padding :0 20px;border:solid 1px #666;}
		</style>
		<script src="avalon.js"></script>
		<script type="text/javascript">
			avalon.ready(function(){
				
				avalon.define({
					$id:"test",
					change:function(){
						console.log("change");
					}
				});
				
				avalon.scan();
			});
		</script>
	</head>
	<body>
		<div ms-controller="test">
			<h3 style="text-align:center">ms-duplex2.0</h3>
			<table>
				<tr>
					<td>
						<p>ms-on-keyup<input ms-on-keyup="change" /></p>
					</td>
				</tr>
			</table>
		</div>
	</body>
	</html>

**Comment by survivol** [comment]
js最先主要就是为input和form表单而服务的， 不适用于通用的js自定义属性方法？

**Comment by liminghui** [comment]
不懂是什么意思= =

**Comment by liminghui** [comment]
知道原因了因为<code>ctrl+v</code>执行了两次<code>keyup</code>
