### ISSUE TITLE
对象的属性未定义的时候，avalon报错

### ISSUE THREAD

**Issue by taoliujun** [RubyLouvre/avalon#903]
&lt;input ms-duplex-value="data.username"&gt;

avalon.define({
  $id: ...,
  data: {}
})

avalon是否需要data对象中的属性先定义后使用？是否需要预先定义为 data: {username:null}，这有点不合理，因为通常从后端读取的数据库字段很多，不需要在前端一一声明。

而avalon源码中有三处 bindingHandlers[data.type]... ，其中1032行左右是否可以改成：
(undefined != data.type) && bindingHandlers[data.type]...

**Comment by darklx** [comment]
确实是这样的，而且是有意为之。Model 的结构应事先定义，据说这是为了避免 Model 的定义分散在各处项目以后不利于维护。
虽然会带来一些不便，但我支持这么做。
不过，某些特殊情况下，得用一些起头办法绕过这个限制了。

**Comment by gogoyqj** [comment]
这是为了兼容IE 8-

**Comment by taoliujun** [comment]
我了解了。如果是为了兼容ie8-。 那么希望modern版本中可以抛弃这个定义的做法
