### ISSUE TITLE
在IE8下面报错： Error: 意外地调用了方法或属性访问。

### ISSUE THREAD

**Issue by night2007** [RubyLouvre/avalon#906]
执行[callback8372]模块的factory抛错： Error: 意外地调用了方法或属性访问。

请大神指点下到底怎么了？

我引用了最新的avalon.js 1.4.4

**Comment by night2007** [comment]
初步排查是使用：<article ms-include-src="page" /> 这个标签引起的，里面的vm.page是准备引用一个外部的页面，比如：/page/hello.html

**Comment by RubyLouvre** [comment]
没有例子，无法测试

**Comment by RubyLouvre** [comment]
这说明你没有在VM定义该 属性，然后后来动态添加它导致这BUG

**Comment by night2007** [comment]
嗯，是我自己弄错了，是<article> 这个html5标签导致的，而我将html5.js放到页面最后加载没起作用。非常感谢您。
