### ISSUE TITLE
关于公开 scanExpr 方法

### ISSUE THREAD

**Issue by darklx** [RubyLouvre/avalon#908]
这个上一次有提过，https://github.com/RubyLouvre/avalon/issues/852
直接用 parseExprProxy 不够。
因为上次的提问关闭了，而且补充回复好像看不到。
而且这次不太一样，我用 avalon 做了一个插件，里面就需要用到 avalon 内部的 parseExpr，详见：https://github.com/darklx/dynamic-css

**Comment by RubyLouvre** [comment]
https://github.com/RubyLouvre/avalon/issues/920

参看这里，以后使用全新的方式来定义指令，data.expr为你要解析的部分，解析得到的结果将传到update的第一个参数中～

**Comment by darklx** [comment]
@RubyLouvre 谢！那就等新版了！
