### ISSUE TITLE
global的获取问题

### ISSUE THREAD

**Issue by gogoyqj** [RubyLouvre/avalon#912]
```javascript
var global = this || (0, eval)("this")
```
avalon和mmRequest组件里都有这行代码去获取window对象，但是用webpack打包的时候，由于webpack会给代码块套上一层皮，this就会指向一个空对象，除非给每个有这行代码的文件添加到 module.noparse属性里，略显不方便

**Comment by RubyLouvre** [comment]
那你就改一下吧
```
 global = typeof window === "object" ? window: this

```
