### ISSUE TITLE
avalon 过滤器命名是否有要求

### ISSUE THREAD

**Issue by net027** [RubyLouvre/avalon#913]
avalon自带过滤器 html，
如果我再自定义一个过滤器html2，
```javascript
avalon.filters.html2=function(str){
    if(!str){return '';}
    return str.replace(/\n/g,'<br/>');
}
```
这时anvalon解析的时候既不报错但是现实结果不正确，模板中是这样写的

{{el.content|html2|html}}

结果显示的像这样 
{{el.content}}

过滤器名称改为
avalon.filters.br=.....
或者avalon.filters.br2=...

{{el.content|br|html}}显示结果是正常的。

avalon 版本 1.45

**Comment by RubyLouvre** [comment]
不能带有html的字样

**Comment by net027** [comment]
这样啊，学习了，之前用的1.39的时候写的代码，显示正常，后来换成1.45后发现显示不正常了。

**Comment by RubyLouvre** [comment]
已经修复了,就一个正则出错了
