### ISSUE TITLE
一个循环的问题.

### ISSUE THREAD

**Issue by ybp825** [RubyLouvre/avalon#915]
![qq 20150716154659](https://cloud.githubusercontent.com/assets/7724264/8717880/eb2525d6-2bd1-11e5-8085-2ab00b0bfaf9.png)

两个数组，一个是所有数据，第二个是动态的，如果第二个数组的元素有在第一个数组里就勾上。
要怎么优雅的实现啊？

**Comment by wyzfzu** [comment]
在所有数据的数据项上加check属性，在server端就初始化，之后只要更新这个check属性就可以了。

**Comment by RubyLouvre** [comment]
你起码自己有个页面～不能让人家帮你写业务啊！
