### ISSUE TITLE
建议不要取消data-duplex-changed

### ISSUE THREAD

**Issue by gxrsprite** [RubyLouvre/avalon#916]
如果没有这个东西，只有两个办法
1：拦截器
拦截器主要用于通用功能，但是比如我要保存数据呢？ 做个savedata拦截器？ 这个方法理因在vm内部的，而不是变成通用方法，更不应该能横跨多个vm。意义完全不同。

2：$watch
watch也是类似的，一方面功能放到了vm外部 脱离vm，另一方面也没法监控数组内的更改有局限性。
意义有点类似但有局限性。

所以没有东西能够代替data-duplex-changed，反而需要加强他。

**Comment by RubyLouvre** [comment]
嗯
