### ISSUE TITLE
请问子模块从隐藏变成显示的话可以提供一个回调处理吗

### ISSUE THREAD

**Issue by lkiarest** [RubyLouvre/avalon#921]
比如在首页上有一个菜单定义了很多子模块如下：
```
<div ms-if="page == 'warning'" ms-include-src="pageWarning"></div>
```
在首页的模块里通过点击菜单切换page来显示、隐藏各个子模块，
请问在warning的这个模块里可以监听到自己被隐藏/显示并进行对应的处理吗？

**Comment by RubyLouvre** [comment]
有data-include-rendered 这个回调 http://avalonjs.github.io/#zh/callbacks/index.html

**Comment by lkiarest** [comment]
@RubyLouvre 我之前看过这个，不过这个回调应该是在外部的首页上用的吧，比如我在warning里面定义的onShow,onHide可以调用到吗~~

**Comment by RubyLouvre** [comment]
可以做到啊，CSS3都可以搞

过段时间我实现ms-transition解决动画的问题吧

**Comment by lkiarest** [comment]
@RubyLouvre ^ ^ 司徒哥是不是发错主题了。。

**Comment by lkiarest** [comment]
data-include-rendered  这个接口只能监听到页面的第一次渲染事件，如果用菜单来回切换视图也监听不到的~~

**Comment by RubyLouvre** [comment]
没有，就是使用这东西;
