### ISSUE TITLE
{{}}可以被替换吗？

### ISSUE THREAD

**Issue by michaelzw** [RubyLouvre/avalon#924]
在使用laravel时，{{}}已被使用，在结合avalon时，laravel会提前填充{{}}中内容。有替换{{}}的方法吗？

**Comment by RubyLouvre** [comment]
入门教程上有写啊
```javascript


    avalon.config({
                interpolate: ["{&","&}"]
            })
       
```
http://avalonjs.github.io/#zh/configuration/index.html
