### ISSUE TITLE
avalon.mobile tap事件在PC上有问题

### ISSUE THREAD

**Issue by weeksun23** [RubyLouvre/avalon#925]
用PC查看，发现绑定的tap事件需要鼠标点击两次才能触发。。。。因为手机上的页面希望PC端也能正常浏览，用avalon.modern在手机中体验又不好。。。希望能解决。。

**Comment by IndexXuan** [comment]
今天也发现。mobile分支在手机端还会造成一些冲突和bug。。。比如input radio的点击区域变得极小，仅仅在中心点（用label包起来就是想让移动端单选按钮点击区域变大，方便触摸）。结果手机触屏完全无法接受啊。

**Comment by weeksun23** [comment]
@shirlyLoveU

**Comment by shirlyLoveU** [comment]
已修复

**Comment by weeksun23** [comment]
谢谢美女。

**Comment by weeksun23** [comment]
还没更新么。？

**Comment by shirlyLoveU** [comment]
更新了

**Comment by weeksun23** [comment]
现在触发都触发不了。。。。。。

**Comment by RubyLouvre** [comment]
PC上只能用 click,
