### ISSUE TITLE
avalon.mobile.js导致去哪网Yo css组件的单选复选点击区域变得极小（只能为radio中心点）。应该是框架对click300ms延迟的修复导致的。

### ISSUE THREAD

**Issue by IndexXuan** [RubyLouvre/avalon#927]
调试了一大会，想css，html都一样，渲染区域都一样。怎么就是点击区域这么小。。。（label包起来就是让移动端单选按钮点击区域大些，适合移动端），结果手机触屏体验完全无法接受。
后来突然想到可能是框架对移动端click事件的修复导致的，去掉了avalon.mobile.js果然就好了。
建议正妹老师看看提供一种修复办法，或者添加特殊类名规避修复或是什么完全之策。
又不想舍弃mobile.js对移动端的小巧和友好。希望mobile分支更加给力。

**Comment by RubyLouvre** [comment]
正在外地出差,我让同事看攫

**Comment by IndexXuan** [comment]
您辛苦了。我先切换回了主分支，都没问题了。另外modern分支居然也有问题，我的ms-visible不出来。。。相同的代码，mobile有点击问题，modern的ms-visible不出来。果断用原版，哈哈。
ps：太感谢老师你的mmState，加了controllerUrl功能后，工程化很方便，太有生产力了。谢谢！

**Comment by shirlyLoveU** [comment]
已修复
