### ISSUE TITLE
widget配置项的一个BUG

### ISSUE THREAD

**Issue by taoliujun** [RubyLouvre/avalon#934]
avalon.modern.js的3978行：
var options = data[widget + "Options"] = avalon.mix({}, constructor.defaults, vmOptions || {}, widgetData) 
这行代码是合并配置项。
假设defaults配置项的代码如下：
widget.defaults = {
		css: {
			left: 100 ,//定位
			top: 100 , //定位
			width: 300, //宽度
			'max-height': 400 //最大高度
		}
	};

父控制器的配置项是
$cuser: {
				css: {
					'max-height': 600
				}
}

合并后的配置项的css的值是
css: {
					'max-height': 600
				}
，而期望的css值应该是：
css: {
			left: 100 ,//定位
			top: 100 , //定位
			width: 300, //宽度
			'max-height': 600 //最大高度
		}

所以，3978行代码是否应该改成：
var options = data[widget + "Options"] = avalon.mix(true,{}, constructor.defaults, vmOptions || {}, widgetData)

**Comment by RubyLouvre** [comment]
如果是需要深度复制,自己在组件里面处理一下
