### ISSUE TITLE
ms-duplex 不触发 input onchange，oninput 等事件

### ISSUE THREAD

**Issue by darklx** [RubyLouvre/avalon#935]
如下：(http://jsfiddle.net/90vgyzc6/)
```html
<script src="http://localhost:2688/Content/Scripts/jquery.js"></script>
<script src="http://avalonjs.github.io/static/script/avalon.js"></script>
    登录密码
<input ms-controller="passwordEncryptVM" ms-duplex="clearText" type="password" />
<input ms-controller="passwordEncryptVM" ms-duplex="encryptedText" type="text" id="password-encrypted-text1" name="Password" value="" />

<script>
    avalon.define("passwordEncryptVM", function (vm) {

        vm.clearText = "";
        vm.confirmClearText = "";
        vm.encryptedText = "";
        vm.confirmEncryptedText = "";
        vm.clean = (function () {
            vm.clearText = "";
            vm.confirmClearText = "";
            vm.encryptedText = "";
            vm.confirmEncryptedText = "";
        });
    });


    $("#password-encrypted-text1").bind("input change propertychange", function () {
        alert("changed!");
    });
</script>
```
因为需要配合其它 js 框架使用，它们使用的是绑定 oninput onchange 事件的方式，现在配合 avalon 就不灵了。

**Comment by RubyLouvre** [comment]
可以使用 data-duplex-changed回调实现相同的功能;因为我已经重写了 input.value

**Comment by darklx** [comment]
@RubyLouvre 问题是，data-duplex-changed 自己写自己用还可以，而我碰到的情况是，事件的绑定和处理，是另一个通用js组件去做的，就不能用 data-duplex-changed 了哦，除非我手动在 data-duplex-changed 里面去触发 change，那代码就 ugly 了...

**Comment by RubyLouvre** [comment]
input.value = "xx"当然是什么事件也不会触发;你找一个没有 avalon的页面，在控制台下调用 input.value = "xx"就知了。我重写了input.value就是为了让它能触发oninput事件

**Comment by darklx** [comment]
@RubyLouvre 
是这么个情况，由两个 input，对应两个 duplex，
一个是明文密码，这个 input 是让用户输入的用户输入明文，对应 duplex-"clearText"，另一个对应 md5 加密后的 duplex-"encryptedText"，clearText 一变化，encryptedText 就会联动变化，也就是两个 input 的 value 都在变化

前一个 duplex-"clearText" input，可以按照你说的触发事件
后一个，不会触发 oninput onchange 事件，即使是失去了焦点。

这是 Demo：http://jsfiddle.net/90vgyzc6/8/

<script src="http://avalonjs.github.io/static/script/avalon.js"></script>

<script src="http://lib.sinaapp.com/js/jquery/1.9.1/jquery-1.9.1.min.js"></script>

登录密码
<input ms-controller="passwordEncryptVM" ms-duplex="clearText" type="password" id="password-clear-text1" />
<input ms-controller="passwordEncryptVM" ms-duplex="encryptedText" type="text" id="password-encrypted-text1" name="Password" value="" />

<script>
    var vm = avalon.define("passwordEncryptVM", function (vm) {
        vm.clearText = "";
        vm.encryptedText = "";
    });
    vm.$watch("clearText", function (newValue) {
        vm.encryptedText = "md5:" + newValue;
    });

    $("#password-encrypted-text1").bind("input change propertychange", function () {
        alert("encrypted-text1 changed!");
    });
</script>

**Comment by RubyLouvre** [comment]
是你用得不对，你必须要等到domReady之后才能绑定JQ事件
```html
<!DOCTYPE html>
<html>
    <head>
        <title>TODO supply a title</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="avalon.js"></script>
        <script src="jquery.js"></script>
        <script>
            avalon.define({
                $id:"test",
                aaa: "xxx"
            })
            $(function(){
                $("input").on("input", function(){
                    console.log(this.value)
                })
            })
        </script>
    </head>
    <body>
        <div ms-controller="test">
            <input ms-duplex="aaa">{{aaa}}
            
        </div>
    </body>
</html>
```

**Comment by RubyLouvre** [comment]
```javascript

$(function(){

    $("#password-encrypted-text1").bind("input change propertychange", function () {
        alert("encrypted-text1 changed!");
    });})


```

**Comment by darklx** [comment]
@RubyLouvre 
不是 Ready 的问题，是有两个 duplex input ，一个 input 变化会触发另一个 input 变化，这样另一个 input 就不会触发事件。

你看看这个 Demo，应该 alert：
alert("clear-text1 changed!");
以及
alert("encrypted-text1 changed!");

但是无论 dom 是否 Ready，都不会 alert("encrypted-text1 changed!");

http://jsfiddle.net/90vgyzc6/12/

**Comment by RubyLouvre** [comment]
你去掉 avalon试试

**Comment by darklx** [comment]
@RubyLouvre 去掉 avalon当然也不会了，因为是用 avalon 的绑定以实现一个 input 触发另一个 input value 的变化，我觉得你根本没用真正看过我说的意思。

**Comment by xiarugu** [comment]
司徒正解
对input.value进行赋值是不会触发任何事件的, 不管是原生javascript还是jQuery
input和change事件都是针对用户操作的, 比如你在文本框中用键盘进行输入操作的时候

你可以去掉avalon以后试着
setTimeout(function()
{
    $('#password-encrypted-text1').val(Math.random());
}, 1000);
按照你说的, 页面应该每隔一秒跳出个alert('encrypted-text1 changed!')
实际上是nothing happy

在早期的jQuery(大概是1.4之前)进行$(xxx).val('xx')赋值的时候会触发change事件, 但是在后来的版本中作为bug修复了.
PS, 这个bug复现的前提还是赋值操作发生在文本框的正常change事件中.(即val赋值导致change发生多次).
