### ISSUE TITLE
外部干预DOM后, 对VM重新赋值不能刷新DOM

### ISSUE THREAD

**Issue by xiarugu** [RubyLouvre/avalon#939]
见 http://jsfiddle.net/xiarugu/d0yjgkc0/10/

用vm对数组进行赋值以后, 外部用js修改DOM, 重新用vm赋值不能刷新DOM

例如, vm.list = ['A', 'B', 'C'];
&lt;ul ms-each="list"&gt;&lt;li&gt;{{el}}&lt;/li&gt;&lt;/ul&gt;

赋值以后, 手工修改li的内容, document.querySelector('li').textContent = 'hello';
再次进行赋值 vm.list = ['A', 'B', 'C']

第一个li的内容依然是hello, 不会被刷新为 'A'

**Comment by RubyLouvre** [comment]
当然不能手动更新 li里面的内容！因此我在框架里面保存的是之前的文本节点
