### ISSUE TITLE
1.4.3升级到1.4.5报错

### ISSUE THREAD

**Issue by airclear** [RubyLouvre/avalon#941]
![image](https://cloud.githubusercontent.com/assets/4103690/8921838/d508da1e-350d-11e5-93e1-ebe3d92c5435.png)

![image](https://cloud.githubusercontent.com/assets/4103690/8921847/ea617fc4-350d-11e5-9140-061d82ebedc2.png)

**Comment by RubyLouvre** [comment]
有可以运行的页面吗？或一个例子;起码让我能够调试～
