### ISSUE TITLE
关于avalon的vm不能继承的想法

### ISSUE THREAD

**Issue by SkunkHusband** [RubyLouvre/avalon#944]
既然改变this指向不能完美解决问题，那可否换个对象来完成这个艰巨的任务？比如说vm的方法本身？
具体说来：
1、在define时候，给每个vm的方法体都加上一个约定好的属性（$vm？），引用到生成后的vm
2、方法体内部不用this，而用arguments.callee.$vm来访问vm
3、可能需要一个防止内存泄露的机制
不知道这个方法可行不，我是忽然想到，没有进行推敲，大家不喜勿喷。

**Comment by ChieveiT** [comment]
没太理解...可否先说说vm继承的使用场景？

**Comment by SkunkHusband** [comment]
比如说项目中有大量页面都有一些共同的功能，需要将这些功能抽象为一个基类vm（抽象的层次可能有多层），然后每个页面都可以继承这个基类，实现自己的vm。

**Comment by zeusro** [comment]
JavaScript不是给你面向对象吧.也许typescript适合你....

**Comment by SkunkHusband** [comment]
你说的话扯远了，跟我说的不是一个话题

**Comment by wonderbeyond** [comment]
@SkunkHusband的想法我觉得可行, 在方法自身加一个引用vm的属性靠谱!

**Comment by RubyLouvre** [comment]
arguments.callee　在严格模式下不支持，垃圾回收是一个难题; this指向不正确，只在IE6－8下出现;只有等时代来消灭这需求！
