### ISSUE TITLE
是否考虑做个集成avalon的nuget包

### ISSUE THREAD

**Issue by zeusro** [RubyLouvre/avalon#945]
这样既可以版本管理.
也可以清晰的指导自己引用的avalon是哪个版本.

**Comment by RubyLouvre** [comment]
不知道什么是nuget

**Comment by zeusro** [comment]
@RubyLouvre 
就是.net的包管理器

https://www.nuget.org/

**Comment by zeusro** [comment]
发布项目到nuget社区的官方指引

http://docs.nuget.org/Create/creating-and-publishing-a-package

**Comment by RubyLouvre** [comment]
不用VS，想做自己做;

**Comment by zeusro** [comment]
既然你这么说,那我就发布了

https://www.nuget.org/packages/avalon/1.45.0
