### ISSUE TITLE
ms-attr-value属性能否用在select上，用于选中所属的option ..

### ISSUE THREAD

**Issue by xyhp915** [RubyLouvre/avalon#951]
```html
<select name="material" id="" class="form-control" ms-attr-value="data.material">
  <option value…
</select>
```

或者有什么其他的方法？

**Comment by xingxiulaoxian** [comment]
<select  ms-each="scanType" ms-duplex-string="scanTypeNow">
	<option>{{el}}</option>
</select>
不知道这样可以不。。反正我就是这么写的，仅供参考

**Comment by xingxiulaoxian** [comment]
<select ms-each="scanType" ms-duplex-string="scanTypeNow">
						<option>{{el}}</option>
					</select>
仅供参考

**Comment by RubyLouvre** [comment]
https://github.com/RubyLouvre/avalon/tree/master/examples  认真看完这里duplex 开头的例子 ;

**Comment by RubyLouvre** [comment]
你都没有入门http://avalonjs.github.io/   http://edu.51cto.com/course/course_id-2533-page-1.html 　看这里先入门吧

**Comment by xyhp915** [comment]
嗯，MVVM难啃，确实是入门 :cry:  ，可能是我描述的问题，其实我是特意避开双工绑定的，可是当我将指令`ms-attr-value`用于`select`没起效果，后来单独测试了下，是可以的，可能是我这表单太特么复杂了，不知道哪儿出了问题，手头事情比较多，也来不及即刻仔细拜读源码，得空再看看。暂时用的$watch挂的钩子独立逻辑解决的。Thanks:)
