### ISSUE TITLE
IE8 数据 绑定问题

### ISSUE THREAD

**Issue by MaxMooc** [RubyLouvre/avalon#952]
IE8 打开页面时  有个AJAX会自动请求后台拿到返回数据后给VM属性赋值，但是页面的对应数据绑定不上，按照@盐城--学习者的方法，在定义属性时就写个假数据绑定上，等AJAX返回数据后再重新赋值，这样也没有成功，有解决办法吗？谢谢

**Comment by RubyLouvre** [comment]
写个例子，AJAX改成setTimeout
