### ISSUE TITLE
更新avalon为1.4.5之后，ms-visible为true时，display属性的问题

### ISSUE THREAD

**Issue by liminghui** [RubyLouvre/avalon#953]
当a为true的时候，display属性不会为block

	<!DOCTYPE HTML>
	<html>
	    <head>
	        <title>ms-visible</title>
	        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	        <meta http-equiv="X-UA-Compatible" content="IE=edge" /> 
	        <script src="../avalon.js" ></script>
	        <script>
	            var model = avalon.define("test", function(vm) {
	                vm.a = true
	            })
	        </script>
	        <style>
	            .rect{
	                width:100px;
	                height:100px;
	                background: red;
	                display: none;
	                border:1px solid red; 
	                text-align: center
	            }
	        </style>
	    </head>
	    <body>
	        <h3>ms-visible</h3>
	        <div ms-controller="test">
	            <p>点我隐藏或显示下面的方块<input ms-duplex-checked="a"  type="radio"></p>
	            <div class="rect" ms-visible="a" >visible</div>
	        </div>
	    </body>
	</html>

**Comment by RubyLouvre** [comment]
应该更新到最新的版本就好了

**Comment by liminghui** [comment]
已经是最新版本啦，1.4.4都没问题

**Comment by xingxiulaoxian** [comment]
因为你样式里面加了display：none
新版本好像只是添加删除这个属性

**Comment by liminghui** [comment]
之前的版本都会display:block，如果新版本改了这个，只能用样式控制了吧

**Comment by xingxiulaoxian** [comment]
你可以改下源码啊。。
bindingExecutors.visible = function(val, elem, data) {
    elem.style.display = val ? "data.display" : "none"
}

这里面的data.display改成block就可以了啊，不过这样的话你如果有定义inline的就会出现布局错了啊

**Comment by liminghui** [comment]
好的，我明白什么问题了
