### ISSUE TITLE
微信中加载和pc中渲染速度相差10倍

### ISSUE THREAD

**Issue by gmcheng** [RubyLouvre/avalon#954]
![a](https://cloud.githubusercontent.com/assets/7368262/9054602/bf0e548e-3ab5-11e5-9a54-e48cf7ade1e8.jpg)

在pc上chrome42中加载速度为80ms，在微信中加载为800ms，请问这是什么原因导致的(用的avalon.mobile.shim.js)

**Comment by RubyLouvre** [comment]
网速慢
