### ISSUE TITLE
 ms-widget的一个小问题

### ISSUE THREAD

**Issue by yutent** [RubyLouvre/avalon#959]
在用 ms-include-src="tpl" 载入一个包含 ms-widget="plugin, xxoo”时， 如果来回切换 tpl ，则会报warning: xxoo 已经存在于avalon.vmodels中。 如果不指定xxoo，如ms-widget="plugin”，那样就不会报这个warning。

**Comment by RubyLouvre** [comment]
http://avalonjs.github.io/#zh/bindings/include.html  

avalon1.4.2中，添加了data-include-cache="true"辅助指令，它会保存之前的模板被扫描后的DOM节点。

ms-duplex-src所在元素加上这个辅助指令，就可以了

**Comment by yutent** [comment]
哦，好的。
如果框架直接 默认为true，会有什么缺点么
