### ISSUE TITLE
在jQuery环境下是否可以让ms-data同步到jQuery的data缓存

### ISSUE THREAD

**Issue by xiarugu** [RubyLouvre/avalon#961]
在jQuery环境下对data-xxx的取值赋值是通过jQuery的data缓存实现的
建议司徒是否可以在对ms-data视图进行数据绑定的时候同时更新jQuery中的data缓存

这样avalon和jQuery混用的时候就可以让avalon很方便得驱动原来用jQuery写的一些页面与组件了.

**Comment by RubyLouvre** [comment]
jquery也是读data-xxx属性的啊

**Comment by RubyLouvre** [comment]
有需求自己对data绑定进行修改
```javascript
      var elem = this.element
        var key = "data-" + this.param
        jQuery && jQuery(elem).data(this.param, val)
        if (val && typeof val === "object") {
            elem[key] = val
        } else {
            elem.setAttribute(key, String(val))
        }
```

**Comment by xiarugu** [comment]
jQuery.fn.data第一次调用取值的时候会从data-xxx属性读取, 之后就缓存起来了.
后面再通过vm进行赋值的时候, 虽然data-xxx属性值变了, 但是 jQuery读取不会再从属性读, 而是直接读他之前的缓存了

**Comment by xiarugu** [comment]
或者可以多设计一些开发接口, 方便大家做些实现类似功能的插件呢

**Comment by RubyLouvre** [comment]
是的
但我这种方法是可行的
