### ISSUE TITLE
ms-class-1失效

### ISSUE THREAD

**Issue by davidduwei** [RubyLouvre/avalon#962]
.abc{width: 100px; height: 100px; background-color: #000;}
	
	<script>
	avalon.define('test',function(vm){
		vm.a = true
	})
	</script>

<script src="avalon.js"></script>

<div ms-controller="test">

     < div ms-class-1="abc:a" >< /div >

       < div class="dd" ms-class-1="{{a?'abc':''}}" >< /div >
</div >
</html>

浏览器中显示为
<pre>
&lt;div ms-class-1="abc:a" class="abc"&gt;&lt;/div&gt;

&lt;div class="dd abc"&gt;&lt;/div&gt;
</pre>

**Comment by RubyLouvre** [comment]
```html
<!DOCTYPE HTML>
<html>
    <head>
        <title>TODO supply a title</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="avalon.js"></script>

    </head>
    <body ms-controller="test">

        <style>
            .abc{width: 100px; height: 100px; background-color: #000;}
        </style>
        <script>
            avalon.define('test', function (vm) {
                vm.a = true
            })
        </script>

        <div ms-class-1="abc:a" >1111</div>

       <div class="dd" ms-class-1="{{a?'abc':''}}" >1111</div>
    </body>
</html>```
