### ISSUE TITLE
modern版本中建议隐藏$model,$watch等系统属性和方法

### ISSUE THREAD

**Issue by xiarugu** [RubyLouvre/avalon#963]
在环境允许的情况下, 例如modern版本中, 建议用defineProperty方法来定义$model, $watch, $unwatch等系统属性, 并设置enumerable为false
Object.defineProperty(fn, "$watch", {
    value: xxx,
    writable: false,
    enumerable: false,
    configurable: true
});

这样业务代码在对array或object对象进行foreach的时候不会误把avalon的系统属性也读取出来.

**Comment by RubyLouvre** [comment]
在avalon1.5中已经这样做
