### ISSUE TITLE
avalon.define($id, fn)中fn被调用两次

### ISSUE THREAD

**Issue by xiarugu** [RubyLouvre/avalon#964]
avalon.define($id, fn)方式中fn被调用了两次, 请问这是bug还是有什么特别的用意必须如此?
我在fn中做了检测如果已经被调用过就直接return(不执行model赋值), 页面也正常, 没有发现少一次调用有什么问题啊.

**Comment by Runaria** [comment]
看这个
[#767](https://github.com/RubyLouvre/avalon/issues/767)

**Comment by RubyLouvre** [comment]
晕，连入门教程都没有认真看;上面写得清清楚楚

**Comment by xiarugu** [comment]
用新方法就可以"避免"这个问题, 不过旧方法有旧方法的好处, 因为是一个函数, 可以在这里进行一些与视图模型相关的计算工作.
既然执行一次也可以, 为何不从根源上把执行两次的问题解决掉呢.
