### ISSUE TITLE
源码中getCurrentScript() 在ShowDialog打开的模态窗口中返回的url是错误的

### ISSUE THREAD

**Issue by myseemylife** [RubyLouvre/avalon#965]
写好的js模块和绑定的html,win.open打开页面运行很好。
但是使用IE Firfox的ShowDialog打开页面。getCurrentScript()每次获取到的url都是http://localhost/js/avalon.js，导致其他依赖的模块的state 永远都是1，最后回调不能触发

**Comment by RubyLouvre** [comment]
有例子吗; 在runjs写例子让我看看
