### ISSUE TITLE
如何$watch数组元素的某个属性？

### ISSUE THREAD

**Issue by treenew** [RubyLouvre/avalon#969]
假设有10个元素 {name: "a"} 这样的数组。
请问如何监听 name 发生变化时的事件？

```javascript
             var array = [];
            for (var i = 0; i < 10; i++) {
                array.push({ name: "index" + i });
            }

            var vm = avalon.define({ $id: "default", model: array });

            //???

            vm.model[5].name = "changed";//- 任意索引的 name 发生变化都会监听
```
除了循环每一个数组元素进行 watch，还有其他办法吗？

**Comment by xingxiulaoxian** [comment]
不能监听到数组里面的变化，只能看到数组长度的改变
http://avalonjs.github.io/#zh/concepts/$watch.html

**Comment by treenew** [comment]
@xingxiulaoxian 我就是看了API才来提问的，要不然要一个一个的监听，push后还需要再次watch

**Comment by RubyLouvre** [comment]
http://www.html-js.com/article/Avalon-tutorial-15-property-monitoring-and-communication-module
目前不支持，只能通过一些委婉的方式实现
