### ISSUE TITLE
IE下ms-duplex的问题

### ISSUE THREAD

**Issue by magnww** [RubyLouvre/avalon#977]
http://avalonjs.github.io/#zh/concepts/observable.html
这个页面
IE6-8下，输入单个字符时，属性值没有刷新。
需要再输入一个字符或者文本框失去焦点才能刷新。

比如在xxx后面随便输入一个字符，这时文本框右侧的显示值没有变化
IE9+是正常的

**Comment by RubyLouvre** [comment]
最新的已经好了

**Comment by magnww** [comment]
最新的是指？
我这一开始用的1.4.4
后来更新到1.4.5，也是有问题。
master的试过也是不行

**Comment by RubyLouvre** [comment]
没问题啊

**Comment by magnww** [comment]
https://output.jsbin.com/lexefa/

发现和绑定数据方式有关系。
不知是不是我写法不对。
