### ISSUE TITLE
希望ms-widget的格式可以使用变量

### ISSUE THREAD

**Issue by cathzhang** [RubyLouvre/avalon#979]
ms-widget="uiName,id?, optsName?"

这个调用格式，是否可以对id，optsName支持变量，以提高在动态生成的页面中可使用的方便性。

**Comment by RubyLouvre** [comment]
这个怎么改也是这样了，等1.5的新组件吧

**Comment by RubyLouvre** [comment]
http://avalonjs.github.io/#zh/bindings/component.html

**Comment by zinda2000** [comment]
github这里的1.5分枝还是1.46
