### ISSUE TITLE
ms-repeat  能否 不绑定 标签 

### ISSUE THREAD

**Issue by forbreak** [RubyLouvre/avalon#981]
![image](https://cloud.githubusercontent.com/assets/6947976/9272491/803ab5a6-42b5-11e5-8d95-8e4615114a38.png)

如果我有这样一个数据,如下面 我想生成一个 table  ms-repeat 绑定在 tr上面 数组循环一次生成一个 tr .
 如果节点中存在 data 属性的时候,我想在table 里面 多生成一个 tr  里面放一个 内嵌的 table 用来显示 data 的数据.  因为  ms-repeat  与tr 绑定,我不能让让我们的内容超出tr, 但是table 里面 又不能在tr外面放其他比如 div 之类的标签. 
    其实如果在div 下面是没有这个问题的 我可以在外面再加一个div用来做循环来实现此效果, 但是在table里面就不可以了.
```
    [{
        a:1,
        b:2,
        c:3,
        data:[{
            test1:1,
            test2:2,
            test3:3
        }]
    },{
        a:1,
        b:2,
        c:3
    },{
        a:1,
        b:2,
        c:3,
        data:[{
            test1:1,
            test2:2,
            test3:3
        }]
    }]
```

**Comment by RubyLouvre** [comment]
不能
