### ISSUE TITLE
新版本class绑定的格式设定

### ISSUE THREAD

**Issue by xiarugu** [RubyLouvre/avalon#982]
感觉
ms-class="c1:condition1" ms-class-1"c2:condition2" ms-class-3
这样的设定不太美观和谐

如果是这样就好了:
ms-class="c1:condition1,c2:condition2"
多组className:条件之间用逗号或者分号隔开.

**Comment by RubyLouvre** [comment]
这算多个指令在一起，超出我之前的设计了

**Comment by xiarugu** [comment]
确实会增加设计复杂度, 就看司徒君怎么取舍了, 选择语法优美还是选择实现简单.
很多设计是对使用者来说很小的细节改动, 对开发者可能就是额外多做了很多工作. 所谓台上十分钟台下十年功一样的感觉. 乔帮主的很多设计都是这样.

**Comment by lazyhero** [comment]
凡是框架，其实应该要高度封装，语法优美(使用者理解解答，轻易记忆) 才能做到来一个实习生 让他看天文档 做个demo就能上手参与项目；建议还是把语法尽量简单(易于理解，轻易记忆)；
最终要的效果就是一个团队有个把核心维护框架，廉价程序员(实习生，初级)来码业务代码；学有余力 感兴趣 也可以去接触核心；
