### ISSUE TITLE
希望在二级计算属性中提供对上级对象的调用

### ISSUE THREAD

**Issue by xiarugu** [RubyLouvre/avalon#984]
```
avalon.define({
  $id: 'page',
  name: 'topparent',
  child: {
    id: 1,
    desc: {
      get: function(){ return '我的上上级对象是' + this.$parent.name; }
    }
  }
}
```

此处this只能指向child, 希望提供一种类似类似$parent的机制来指向this对象的父级对象.

**Comment by RubyLouvre** [comment]
这个有点困难啊

**Comment by RubyLouvre** [comment]
我在1.5打算搞一个类似的$up
$parent太大众化了

**Comment by xiarugu** [comment]
在each和repeat循环中不是有个$outer来引用上级吗, 是否可以考虑根据这个来保持一个较为统一的风格.
之前没有接触过有up来表示上级的, parent, outer, container 这些命名都不错.

**Comment by RubyLouvre** [comment]
$outer不一样啊，$outer指向与它完全不相同的作用域对象
