### ISSUE TITLE
触屏swipe体验改进建议

### ISSUE THREAD

**Issue by xiarugu** [RubyLouvre/avalon#985]
最近在一个银行项目中使用了avalon的触屏功能, 用avalon给一个日历控件加了左右滑动跳转月份的功能.
发现一个小问题:

用户点击日期输入框弹出日历DIV
根据浏览的正常流程, 输入框一般在屏幕的中下部, 这时候出来的日期控件是在偏下方的, 
用户会将触屏向上滑动, 来看到完整的日历.

这里就有个问题, 一般手机用单手操作的时候, 是用大拇指向上滑动来拖动页面的, 而大拇指向上滑动其实不是直上直下的, 而是一条斜的弧线.

这里avalon的swipe会触发向左滑动的事件, 于是就发生了客户预期之外的结果.

只针对这单个应用场景来说, 可以用固定日历位置来一定程度上避免这个问题.

不过我想在很多其他场合也一定会遇到这个问题, 就是上下拖动网页导致触发左右滑动事件.

建议的改进是:
在滑动时判断左右位移和上下位移, 以位移大的方向作为滑动方向.
某些特殊场景可能会同时需要检测上下和左右滑动, 具体解决的方法或者增加事件, 或者在事件中带额外参数, 看司徒怎么设计了.

**Comment by RubyLouvre** [comment]
swipe的判定已经 改进
