### ISSUE TITLE
翻页。。。应该是个bug

### ISSUE THREAD

**Issue by xingxiulaoxian** [RubyLouvre/avalon#989]
下边这个是测试地址，在操作数组的时候不管是for循环还是slice截取数组都会改变父亲数组。。如果写法不对请大神原谅。。
http://runjs.cn/detail/ns7glvxj

**Comment by xingxiulaoxian** [comment]
<pre>
function newfixPage(start , len , arr){
		var begin = (start-1)*len,
			end = len*start;
		var tempData = [];
		for(var i = begin; i< end; i++){
			
			tempData.push(avalon.mix({},arr[i]))
		}
		//console.info(arr instanceof Array)
		console.info(tempData)
		//tempData = arr.slice(begin,end)
		return tempData
	}

</pre>

使用克隆里面的对象竟然好了。。难道和avalon没关系只是因为引用数组里面的对象么。。。

**Comment by RubyLouvre** [comment]
https://github.com/RubyLouvre/avalon/wiki/%E5%A4%A7%E5%AE%B6%E8%AE%A8%E8%AE%BA%E5%87%BA%E6%9D%A5%E7%9A%84%E6%9C%89%E7%94%A8%E8%B4%B4%E5%AD%90

**Comment by RubyLouvre** [comment]
这里有说交换数组的，理由相同
