### ISSUE TITLE
关于ms-attr-selected的一些问题 

### ISSUE THREAD

**Issue by a578242325** [RubyLouvre/avalon#997]
直接上代码
```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>Document</title>
	<script type="text/javascript" src="avalon.modern.min.js"></script>
</head>
<div ms-controller="content">
	<input type="button" value="点击添加" ms-click="add(team1)" />
	<div ms-repeat="team1">
		<select>
			<option ms-repeat-sel="size"  ms-attr-selected="selectedFc(sel,$outer.el.Size)">{{sel}}</option>
		</select>
	</div>
</div>
<body>
	<script type="text/javascript">
	avalon.ready(function() {
		// 初始化的数据
		var size=["S","M","L","XL"]
		var team1 =[{Size:"M"},{Size:"L"}]


	    var content = avalon.define({
	          $id: "content",
	          team1 : team1,
	     	  size : size,
	     	  selectedFc:function(el,qsize){
				if(el ==qsize){
	          		return true;
	          	}
	     	  },
	     	  add:function(el){
	     	  	//空数据
	     	  	var kong = {Size:"S"}
	     	  	el.unshift(kong)
	     	    //空数据已经添加进去了 之前的数据也保留下来！！
	     	  	console.log(el)
	     	  }
	      });

	      avalon.scan();
	      
	 })
	</script>
</body>
</html>
```

**Comment by RubyLouvre** [comment]
好遗憾，你根本没有入门，都在乱写
```html
<!doctype hmtl>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
        <title>Document</title>
        <script type="text/javascript" src="avalon.js"></script>
        <script type="text/javascript">
            avalon.ready(function () {
                // 初始化的数据
                var size = ["S", "M", "L", "XL"]
                var team1 = [{Size: "M"}, {Size: "L"}]


                var content = avalon.define({
                    $id: "content",
                    team1: team1,
                    size: size,
                    selectedFc: function (el, qsize) {
                        if (el == qsize) {
                            return true;
                        }
                    },
                    add: function (el) {
                        //空数据
                        var kong = {Size: "S"}
                        el.unshift(kong)
                        //空数据已经添加进去了 之前的数据也保留下来！！
                        console.log(el)
                    }
                });

                avalon.scan();

            })
        </script>
    </head>
    <body>
        <div ms-controller="content">
            <input type="button" value="点击添加" ms-click="add(team1)" />
            <select ms-duplex="size" multiple="">
                <option ms-repeat="team1"  >{{el.Size}}</option>
            </select>
        </div>
    </body>


</html>```

**Comment by RubyLouvre** [comment]
https://github.com/RubyLouvre/avalon/issues/867

**Comment by RubyLouvre** [comment]
你连操作 表单元素使用ms-duplex也没有想到 https://github.com/RubyLouvre/avalon/tree/master/examples
例子都不看

**Comment by RubyLouvre** [comment]
我不明白两个数组，它们又不是一个二维数组，怎么能使用ms-repeat来搞一个双重循环呢

**Comment by a578242325** [comment]
demo我可能是写错了 实际的项目中 结构是这样的
data[{size : ["S", "M", "L", "XL"] },{team1: [{Size: "M"}, {Size: "L"} ] }];

**Comment by RubyLouvre** [comment]
也一样，它们之间是没有关联的，二维数组是[[], [], []]

**Comment by a578242325** [comment]
谢谢 正美 我回去在研究下

**Comment by liudianpeng** [comment]
@a578242325 {
    "xinxiguanli":{"name":"\u4fe1\u606f\u7ba1\u7406","url":"\/home.html",
      "subMenu":[{"xinxiguanli_gerenxinxi":{"name":"\u4e2a\u4eba\u4fe1\u606f","url":"\/xinxiguanli\/gerenxinxi.html","sequence":100}},
        {"xinxiguanli_gerenjianli":{"name":"\u4e2a\u4eba\u7b80\u5386","url":"\/xinxiguanli\/gerenjianli.html","sequence":99}},
        {"xinxiguanli_fanzuishishi":{"name":"\u72af\u7f6a\u4e8b\u5b9e","url":"\/xinxiguanli\/fanzuishishi.html","sequence":98}},
        {"xinxiguanli_shehuiguanxi":{"name":"\u793e\u4f1a\u5173\u7cfb","url":"\/xinxiguanli\/shehuiganxi.html","sequence":97}},
        {"xinxiguanli_chaoshigouwu":{"name":"\u8d85\u5e02\u8d2d\u7269","url":"\/xinxiguanli\/chaoshigouwu.html","sequence":96}},
        {"xinxiguanli_gerenzhanghu":{"name":"\u4e2a\u4eba\u5e10\u6237","url":"\/xinxiguanli\/gerenzhanghu.html","sequence":95}},
        {"xinxiguanli_gerenjiangcheng":{"name":"\u4e2a\u4eba\u5956\u60e9","url":"\/xinxiguanli\/gerenjiangcheng.html","sequence":94}},
        {"xinxiguanli_qinqingduanxin":{"name":"\u4eb2\u60c5\u77ed\u4fe1","url":"\/xinxiguanli\/qinqingduanxin.html","sequence":93}},
        {"xinxiguanli_qinqingdianhua":{"name":"\u4eb2\u60c5\u7535\u8bdd","url":"\/xinxiguanli\/qinqingdianhua.html","sequence":92}},
        {"xinxiguanli_qinqinghuijian":{"name":"\u4eb2\u60c5\u4f1a\u89c1","url":"\/xinxiguanli\/qinqinghuijian.html","sequence":91}},
        {"xinxiguanli_gerenkaohe":{"name":"\u4e2a\u4eba\u8003\u6838","url":"\/xinxiguanli\/gerenkaohe.html","sequence":90}},
        {"xinxiguanli_rujianziliao":{"name":"\u5165\u76d1\u8d44\u6599","url":"\/xinxiguanli\/rujianziliao.html","sequence":89}}],"sequence":10},

    "xitongguanli":{"name":"\u7cfb\u7edf\u7ba1\u7406","url":"\/xitongguanli\/xitongyonghu.html",
      "subMenu":[{"xitongguanli_xitongyonghu":{"name":"\u7cfb\u7edf\u7528\u6237","url":"\/xitongguanli\/xitongyonghu.html","sequence":100}},
        {"xitongguanli_xitongyonghuzu":{"name":"\u7cfb\u7edf\u7528\u6237\u7ec4","url":"\/xitongguanli\/xitongyonghuzu.html","sequence":99}},
        {"xitongguanli_xitongcaidan":{"name":"\u7cfb\u7edf\u83dc\u5355","url":"\/xitongguanli\/xitongcaidan.html","sequence":98}},
        {"xitongguanli_xitongjuese":{"name":"\u7cfb\u7edf\u89d2\u8272","url":"\/xitongguanli\/xitongjuese.html","sequence":97}},
        {"xitongguanli_xitongquyu":{"name":"\u7cfb\u7edf\u533a\u57df","url":"\/xitongguanli\/xitongquyu.html","sequence":96}},
        {"xitongguanli_xitongjianqu":{"name":"\u7cfb\u7edf\u76d1\u533a","url":"\/xitongguanli\/xitongjianqu.html","sequence":95}},
        {"xitongguanli_pingtairizhi":{"name":"\u5e73\u53f0\u65e5\u5fd7","url":"\/xitongguanli\/pingtairizhi.html","sequence":94}},
        {"xitongguanli_quanxianpeizhi":{"name":"\u6743\u9650\u914d\u7f6e","url":"\/xitongguanli\/quanxianpeizhi.html","sequence":93}},
        {"xitongguanli_zidianguanli":{"name":"\u5b57\u5178\u7ba1\u7406","url":"\/xitongguanli\/zidianguanli.html","sequence":92}},
        {"xitongguanli_xiugaimima":{"name":"\u4fee\u6539\u5bc6\u7801","url":"\/xitongguanli\/xiugaimima.html","sequence":91}}],"sequence":7},

    "jifenkaohe":{"name":"\u79ef\u5206\u8003\u6838","url":"\/jifenkaohe\/shujuchaxun.html",
      "subMenu":[{"jifengkaohe_shujuchaxun":{"name":"\u6570\u636e\u67e5\u8be2","url":"\/jifenkaohe\/shujuchaxun.html","sequence":99}},
        {"jifengkaohe_jifenluru":{"name":"\u79ef\u5206\u5f55\u5165","url":"\/jifenkaohe\/jifenluru.html","sequence":98}},
        {"jifengkaohe_jifenshenhe":{"name":"\u79ef\u5206\u5ba1\u6838","url":"\/jifenkaohe\/jifenshenhe.html","sequence":97}},
        {"jifengkaohe_liuchengpeizhi":{"name":"\u6d41\u7a0b\u914d\u7f6e","url":"\/jifenkaohe\/liuchengpeizhi.html","sequence":96}}],"sequence":9},
    "quyuguanli":{"name":"\u533a\u57df\u7ba1\u7406","url":"\/quyuguanli\/renyuanzhangtai.html",
      "subMenu":[{"quanyuguanli_renyuanzhuangtai":{"name":"\u4eba\u5458\u72b6\u6001","url":"\/quyuguanli\/quyuhuafen.html","sequence":99}},
        {"quanyuguanli_quyuhuafen":{"name":"\u533a\u57df\u5212\u5206","url":"\/quyuguanli\/quyuhuafen.html","sequence":98}}],"sequence":8}
  }
]

**Comment by liudianpeng** [comment]
@a578242325 你看我这样的数据该怎么弄
