### ISSUE TITLE
1.4.6 mobile版本键盘"前往"不能submit表单

### ISSUE THREAD

**Issue by xiarugu** [RubyLouvre/avalon#998]
mobile版本提现在PC上按了回车键不能触发表单提交,
在iPhone上的表现就是键盘上的"前往"点击后不能触发表单提交

modern版本没这个问题, 就是mobile版本有这个问题.

急待解决!!

**Comment by gogoyqj** [comment]
里边这行写错了。。。是||不是&&
```javascript
target.tagName.toLowerCase() === 'input' && element.tagName.toLowerCase() === "label"
```

**Comment by xiarugu** [comment]
可不可以发个小版本fix一下

**Comment by gogoyqj** [comment]
@xiarugu  你可以先改成 target.tagName.toLowerCase() === 'input' || target.tagName.toLowerCase() === 'input'  && element.tagName.toLowerCase() === "label" 赶脚，针对input和label元素的处理

**Comment by RubyLouvre** [comment]
改了一下

**Comment by xiarugu** [comment]
司徒, 1.5这算是正式发布了么?

**Comment by shirlyLoveU** [comment]
http://shirlyloveu.github.io/staticTests/situDemo/submit.html   进到这个链接看看在你的手机上是否有问题，把有问题的机器版本型号列出来，谢谢了

**Comment by xiarugu** [comment]
iOS的safari需要写了form的action以后才会出现"前往"按钮. 麻烦改一下demo

**Comment by xiarugu** [comment]
Chrome模拟环境用键盘回车键也不能触发(正常情况下回车键应该是可以触发submit才对)

**Comment by xiarugu** [comment]
Uncaught TypeError: Cannot read property 'tagName' of undefined
onMouse @ avalon.mobile.js:5093

在PC环境下input获得焦点即抛错

**Comment by aaronStac** [comment]
我试了可以诶

**Comment by xiarugu** [comment]
不是点击按钮, 是在input焦点状态下用回车键, 以及手机上的"前往"键

**Comment by shirlyLoveU** [comment]
fixed
