### ISSUE TITLE
对于如下形式的数据 支持动态同步增加删除吗

### ISSUE THREAD

**Issue by lazyhero** [RubyLouvre/avalon#999]
{
1:{title:""},2:{title:""},3:{title:""}
}
之所以用这种形式是想用对象属性名来作为唯一id 获取对应内容
现在我想添加一个4:{title:""} 但是用xxxvm.data["4"]={title:""}的方式 无法让其同步到视图中

**Comment by IndexXuan** [comment]
为什么不用【｛title： “”｝，｛title： “”｝， ｛title： “”｝】格式。。。隐含的下标不就是那个id1，2，3吗。

**Comment by lazyhero** [comment]
之所以没用数组，是因为这些菜单要可拖拽排序，用数组的后果就是 页面视图的顺序都变了，可数组的顺序还是原来那样；其数组和视图同步仅支持添加和删除 不支持随意调换

**Comment by xiarugu** [comment]
sort对视图是否有影响我没试过, 不过我用splice是有用的, 也就意味着当你需要把A元素从位置5放到位置3的时候, 是可以通过移除再插入的方式排序的
```
var item = vm.list.splice(5, 1)[0]; //移除位于位置5的元素A并返回
vm.list.splice(3, 0, item);    //将元素A再次插入到位置3
```

**Comment by IndexXuan** [comment]
ls说的很对，拖拽排序或者任何炫酷diao炸天的操作都是表征，本质都可以用简单的数据结构表达，不要迷惑。而且就算用对象，可以好好看看文档有没有例子，我记得例子里说了更新要整个对象替换。

**Comment by lazyhero** [comment]
如果仅仅是一层菜单目录拖拽 也OK ，但是 下面还有一层；还有一个问题是，vm.list.splice(5, 1)[0]这种需要明确由第几插入到第几，可页面视图在拖拽，无法得知你当前选中的元素被挪到了第几；
我用{{},{}}这种形式实现了需求效果，目前线上的有添加的bug 线下已经修复；但感觉这种思路不好；
实现DEMO https://github.com/lazyhero/lazyui/blob/master/sortablemenu/demo.gif

**Comment by xiarugu** [comment]
数组indexOf(el)即可获取指定元素在数组中的脚标
另外这种方式的排序建议就不要太依赖MVVM了, 像后台提交排序请求的之后直接顺序获取DOM, 把每个DOM对应对象的id按顺序提交给后台就好了.

**Comment by lazyhero** [comment]
ok多谢各位 虽然这些都想到了 并且也尝试实现了 有各种问题……，可以参见https://github.com/lazyhero/lazyui/blob/master/sortablemenu/demo.gif 
目前已经用一些hack方式完成；
